-- Dynatrace — every call this API accepts, as data.
--
-- GENERATED from https://api.dynatrace.com/openapi.json
-- Published on the vendor's own documentation site (https://api.dynatrace.com).
-- 87 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "dynatrace",
  name = "Dynatrace",
  base = "https://{environmentId}.live.dynatrace.com",
  docs = "https://nango.dev/docs/api-integrations/dynatrace",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Api-Token {token}",
    env = "DYNATRACE_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = { ["environmentId"] = "DYNATRACE_ENVIRONMENTID" },
  headers = {},
  operations = {
    ["dynatrace.accounts_controller_create_costcenter_cost_allocation_values"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/v1/accounts/{account-uuid}/settings/costcenters", path = {"account-uuid"}, body = {"values"} },
    ["dynatrace.accounts_controller_create_product_cost_allocation_values"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/v1/accounts/{account-uuid}/settings/products", path = {"account-uuid"}, body = {"values"} },
    ["dynatrace.accounts_controller_delete_costcenter_cost_allocation_value"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/v1/accounts/{account-uuid}/settings/costcenters/{key}", path = {"account-uuid"} },
    ["dynatrace.accounts_controller_delete_product_cost_allocation_value"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/v1/accounts/{account-uuid}/settings/products/{key}", path = {"account-uuid"} },
    ["dynatrace.accounts_controller_list_costcenter_cost_allocation_values"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/v1/accounts/{account-uuid}/settings/costcenters", path = {"account-uuid"}, query = {"page", "page-size"} },
    ["dynatrace.accounts_controller_list_product_cost_allocation_values"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/v1/accounts/{account-uuid}/settings/products", path = {"account-uuid"}, query = {"page", "page-size"} },
    ["dynatrace.accounts_controller_replace_costcenter_cost_allocation_values"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/v1/accounts/{account-uuid}/settings/costcenters", path = {"account-uuid"}, body = {"values"} },
    ["dynatrace.accounts_controller_replace_product_cost_allocation_values"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/v1/accounts/{account-uuid}/settings/products", path = {"account-uuid"}, body = {"values"} },
    ["dynatrace.append_level_policy_bindings"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/{policy-uuid}", path = {"policy-uuid", "level-id", "level-type"}, body = {"groups", "boundaries"} },
    ["dynatrace.append_particular_group_binding"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/{policy-uuid}/{group-uuid}", path = {"group-uuid", "policy-uuid", "level-id", "level-type"}, body = {"parameters", "metadata", "boundaries"} },
    ["dynatrace.audits_controller_list_audits_by_account"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/audit/v1/accounts/{account-uuid}", path = {"account-uuid"}, query = {"startTime", "endTime", "addFields", "filter", "limit", "scanLimitGigabyte", "resultSizeLimitMegabyte"} },
    ["dynatrace.create_level_policy"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/policies", path = {"level-id", "level-type"}, body = {"name", "description", "tags", "statementQuery"} },
    ["dynatrace.create_wif_service_user_mapping"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}/mappings", path = {"account-uuid", "trust-policy-uuid"}, body = {"serviceUserUuid", "environmentId", "scopes", "claimMappings"} },
    ["dynatrace.create_wif_trust_policy"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies", path = {"account-uuid"}, body = {"name", "issuerUrl", "jwksUri", "audience", "description"} },
    ["dynatrace.delete_level_policy"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/policies/{policy-uuid}", path = {"policy-uuid", "level-id", "level-type"}, query = {"force"} },
    ["dynatrace.delete_level_policy_bindings"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings", path = {"level-id", "level-type"} },
    ["dynatrace.delete_level_policy_bindings_for_policy"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/{policy-uuid}", path = {"policy-uuid", "level-id", "level-type"}, query = {"forceMultiple", "query-params"} },
    ["dynatrace.delete_level_policy_bindings_for_policy_and_group"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/{policy-uuid}/{group-uuid}", path = {"group-uuid", "policy-uuid", "level-id", "level-type"}, query = {"forceMultiple", "query-params"} },
    ["dynatrace.delete_platform_token"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/platform-tokens/{platform-token-id}", path = {"account-uuid", "platform-token-id"} },
    ["dynatrace.delete_policy_boundary"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/account/{account-id}/boundaries/{policy-boundary-uuid}", path = {"policy-boundary-uuid", "account-id"} },
    ["dynatrace.delete_wif_service_user_mapping"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}/mappings/{mapping-uuid}", path = {"account-uuid", "trust-policy-uuid", "mapping-uuid"} },
    ["dynatrace.delete_wif_trust_policy"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}", path = {"account-uuid", "trust-policy-uuid"} },
    ["dynatrace.environment_resources_controller_get_clusters"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/env/v2/accounts/{account-uuid}/clusters", path = {"account-uuid"} },
    ["dynatrace.environment_resources_controller_get_config"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/env/v1/accounts/{account-uuid}/environments/{environment-uuid}/ip-allowlist", path = {"account-uuid", "environment-uuid"} },
    ["dynatrace.environment_resources_controller_get_environment_resources"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/env/v1/accounts/{account-uuid}/environments", path = {"account-uuid"} },
    ["dynatrace.environment_resources_controller_get_environments"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/env/v2/accounts/{account-uuid}/environments", path = {"account-uuid"} },
    ["dynatrace.environment_resources_controller_set_config"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/env/v1/accounts/{account-uuid}/environments/{environment-uuid}/ip-allowlist", path = {"account-uuid", "environment-uuid"}, body = {"enabled", "allowWebhookOverride", "allowlist"} },
    ["dynatrace.generate_platform_token"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/platform-tokens", path = {"account-uuid"}, body = {"name", "scope", "resource", "tags", "expirationDate", "userUuid"} },
    ["dynatrace.get_all_level_policies_bindings"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings", path = {"level-id", "level-type"} },
    ["dynatrace.get_effective_permissions"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/resolution/{level-type}/{level-id}/effectivepermissions", path = {"level-id", "level-type"}, query = {"size", "page", "services", "entityId", "entityType"} },
    ["dynatrace.get_environment_cost_v3"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/sub/v3/accounts/{account-uuid}/subscriptions/{subscription-uuid}/environments/cost", path = {"account-uuid", "subscription-uuid"}, query = {"startTime", "endTime", "environmentIds", "capabilityKeys", "clusterIds", "page-key", "page-size"} },
    ["dynatrace.get_environment_usage_v3"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/sub/v3/accounts/{account-uuid}/subscriptions/{subscription-uuid}/environments/usage", path = {"account-uuid", "subscription-uuid"}, query = {"startTime", "endTime", "environmentIds", "capabilityKeys", "clusterIds", "page-key", "page-size"} },
    ["dynatrace.get_level_descendants_policy_bindings"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/descendants/{policy-uuid}", path = {"policy-uuid", "level-id", "level-type"}, query = {"size", "page"} },
    ["dynatrace.get_level_policies"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/policies", path = {"level-id", "level-type"}, query = {"categories", "name"} },
    ["dynatrace.get_level_policy"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/policies/{policy-uuid}", path = {"policy-uuid", "level-id", "level-type"} },
    ["dynatrace.get_level_policy_bindings"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/{policy-uuid}", path = {"policy-uuid", "level-id", "level-type"} },
    ["dynatrace.get_level_policy_bindings_for_group"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/{policy-uuid}/{group-uuid}", path = {"group-uuid", "policy-uuid", "level-id", "level-type"} },
    ["dynatrace.get_limits_for_account"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/limits", path = {"account-uuid"} },
    ["dynatrace.get_limits_for_level"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/limits", path = {"level-id", "level-type"} },
    ["dynatrace.get_platform_tokens_for_account"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/platform-tokens", path = {"account-uuid"}, query = {"searchTerm", "status", "page", "size"} },
    ["dynatrace.get_policy_boundaries"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/account/{account-id}/boundaries", path = {"account-id"}, query = {"size", "page"} },
    ["dynatrace.get_policy_boundary"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/account/{account-id}/boundaries/{policy-boundary-uuid}", path = {"policy-boundary-uuid", "account-id"} },
    ["dynatrace.get_policy_overview_list"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/policies/aggregate", path = {"level-id", "level-type"} },
    ["dynatrace.get_policy_uuids_bindings"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/groups/{group-uuid}", path = {"group-uuid", "level-id", "level-type"}, query = {"details"} },
    ["dynatrace.get_wif_service_user_mapping"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}/mappings/{mapping-uuid}", path = {"account-uuid", "trust-policy-uuid", "mapping-uuid"} },
    ["dynatrace.get_wif_trust_policy"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}", path = {"account-uuid", "trust-policy-uuid"} },
    ["dynatrace.groups_controller_create_groups"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/groups", path = {"account-uuid"} },
    ["dynatrace.groups_controller_delete_group"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/groups/{group-uuid}", path = {"account-uuid", "group-uuid"} },
    ["dynatrace.groups_controller_edit_group"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/groups/{group-uuid}", path = {"account-uuid", "group-uuid"}, body = {"uuid", "name", "description", "federatedAttributeValues"} },
    ["dynatrace.groups_controller_get_groups"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/groups", path = {"account-uuid"} },
    ["dynatrace.groups_controller_get_users_for_group"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/groups/{group-uuid}/users", path = {"account-uuid", "group-uuid"} },
    ["dynatrace.insights_controller_get_cost_allocation_breakdown_page"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/v1/subscriptions/{subscription-uuid}/cost-allocation", path = {"subscription-uuid"}, query = {"field", "environment-id", "from", "to", "page-size", "page-key"} },
    ["dynatrace.list_notifications_v2"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/v2/accounts/{account-uuid}/notifications", path = {"account-uuid"}, query = {"page-key", "page-size", "sorts", "environments", "capabilities", "severities", "types", "end-time", "start-time"} },
    ["dynatrace.list_wif_service_user_mappings"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}/mappings", path = {"account-uuid", "trust-policy-uuid"}, query = {"pageNumber", "pageSize"} },
    ["dynatrace.list_wif_trust_policies"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies", path = {"account-uuid"}, query = {"pageNumber", "pageSize"} },
    ["dynatrace.patch_wif_service_user_mapping_status"] = { method = "PATCH", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}/mappings/{mapping-uuid}", path = {"account-uuid", "trust-policy-uuid", "mapping-uuid"}, body = {"status"} },
    ["dynatrace.patch_wif_trust_policy_status"] = { method = "PATCH", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}", path = {"account-uuid", "trust-policy-uuid"}, body = {"status"} },
    ["dynatrace.post_policy_boundary"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/account/{account-id}/boundaries", path = {"account-id"}, body = {"name", "boundaryQuery", "metadata"} },
    ["dynatrace.put_policy_boundary"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/account/{account-id}/boundaries/{policy-boundary-uuid}", path = {"policy-boundary-uuid", "account-id"}, body = {"name", "boundaryQuery", "metadata"} },
    ["dynatrace.reference_data_controller"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/ref/v1/time-zones" },
    ["dynatrace.reference_data_controller"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/ref/v1/regions" },
    ["dynatrace.reference_data_controller_get_permissions"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/ref/v1/account/permissions" },
    ["dynatrace.service_users_controller_create_service_user_for_account"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/service-users", path = {"account-uuid"}, body = {"name", "description"} },
    ["dynatrace.service_users_controller_delete_user"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/service-users/{user-uuid}", path = {"account-uuid", "user-uuid"} },
    ["dynatrace.service_users_controller_get_service_user"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/service-users/{user-uuid}", path = {"account-uuid", "user-uuid"} },
    ["dynatrace.service_users_controller_get_service_users_from_account"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/service-users", path = {"account-uuid"}, query = {"page", "page-size", "page-key"} },
    ["dynatrace.service_users_controller_update_service_user_for_account"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/service-users/{user-uuid}", path = {"account-uuid", "user-uuid"}, body = {"name", "description"} },
    ["dynatrace.subscriptions_controller_get_forecast"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/sub/v2/accounts/{account-uuid}/subscriptions/forecast", path = {"account-uuid"} },
    ["dynatrace.subscriptions_controller_get_subscription"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/sub/v2/accounts/{account-uuid}/subscriptions/{subscription-uuid}", path = {"account-uuid", "subscription-uuid"} },
    ["dynatrace.subscriptions_controller_get_total_subscription_cost"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/sub/v2/accounts/{account-uuid}/subscriptions/{subscription-uuid}/cost", path = {"account-uuid", "subscription-uuid"}, query = {"environmentIds", "capabilityKeys", "clusterIds"} },
    ["dynatrace.subscriptions_controller_get_total_subscription_usage"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/sub/v2/accounts/{account-uuid}/subscriptions/{subscription-uuid}/usage", path = {"account-uuid", "subscription-uuid"}, query = {"environmentIds", "capabilityKeys", "clusterIds"} },
    ["dynatrace.subscriptions_controller_list_rate_cards"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/sub/v1/accounts/{account-uuid}/rate-cards", path = {"account-uuid"} },
    ["dynatrace.subscriptions_controller_list_subscriptions"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/sub/v2/accounts/{account-uuid}/subscriptions", path = {"account-uuid"} },
    ["dynatrace.update_level_policy"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/policies/{policy-uuid}", path = {"policy-uuid", "level-id", "level-type"}, body = {"name", "description", "tags", "statementQuery"} },
    ["dynatrace.update_level_policy_binding_for_policy_and_group"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/{policy-uuid}/{group-uuid}", path = {"group-uuid", "policy-uuid", "level-id", "level-type"}, query = {"query-params"}, body = {"parameters", "metadata", "boundaries"} },
    ["dynatrace.update_platform_token_expiration_date"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/platform-tokens/{platform-token-id}/expiration-date", path = {"account-uuid", "platform-token-id"}, body = {"expirationDate"} },
    ["dynatrace.update_platform_token_status"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/platform-tokens/{platform-token-id}/status", path = {"account-uuid", "platform-token-id"}, body = {"status"} },
    ["dynatrace.update_policy_bindings_to_group"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/repo/{level-type}/{level-id}/bindings/groups/{group-uuid}", path = {"group-uuid", "level-id", "level-type"}, body = {"policyUuids"} },
    ["dynatrace.update_wif_service_user_mapping"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}/mappings/{mapping-uuid}", path = {"account-uuid", "trust-policy-uuid", "mapping-uuid"}, body = {"serviceUserUuid", "environmentId", "scopes", "claimMappings"} },
    ["dynatrace.update_wif_trust_policy"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/wif/trust-policies/{trust-policy-uuid}", path = {"account-uuid", "trust-policy-uuid"}, body = {"name", "issuerUrl", "jwksUri", "audience", "description"} },
    ["dynatrace.users_controller_add_user_to_groups"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/users/{email}", path = {"account-uuid", "email"} },
    ["dynatrace.users_controller_create_user_for_account"] = { method = "POST", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/users", path = {"account-uuid"}, body = {"email"} },
    ["dynatrace.users_controller_get_user_groups"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/users/{email}", path = {"account-uuid", "email"} },
    ["dynatrace.users_controller_get_users"] = { method = "GET", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/users", path = {"account-uuid"}, query = {"service-users"} },
    ["dynatrace.users_controller_remove_user_from_account"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/users/{email}", path = {"account-uuid", "email"} },
    ["dynatrace.users_controller_remove_user_from_groups"] = { method = "DELETE", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/users/{email}/groups", path = {"account-uuid", "email"}, query = {"group-uuid"} },
    ["dynatrace.users_controller_replace_user_groups"] = { method = "PUT", url = "https://{environmentId}.live.dynatrace.com/iam/v1/accounts/{account-uuid}/users/{email}/groups", path = {"account-uuid", "email"} },
  },
}
