-- Vimeo — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/vimeo.com/3.4/openapi.json
-- APIs.guru's mirror, matched on vimeo.com. A mirror lags the vendor.
-- 326 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "vimeo",
  name = "Vimeo",
  base = "https://api.vimeo.com",
  docs = "https://nango.dev/docs/integrations/all/vimeo",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "VIMEO_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["vimeo.add_channel_categories"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/categories", path = {"channel_id"}, body = {"channels"} },
    ["vimeo.add_channel_moderator"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/moderators/{user_id}", path = {"channel_id", "user_id"} },
    ["vimeo.add_channel_moderators"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/moderators", path = {"channel_id"}, body = {"user_uri"} },
    ["vimeo.add_channel_tag"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/tags/{word}", path = {"channel_id", "word"} },
    ["vimeo.add_tags_to_channel"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/tags", path = {"channel_id"} },
    ["vimeo.add_video_credit"] = { method = "POST", url = "https://api.vimeo.com/videos/{video_id}/credits", path = {"video_id"} },
    ["vimeo.add_video_credit_alt1"] = { method = "POST", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/credits", path = {"channel_id", "video_id"} },
    ["vimeo.add_video_embed_preset"] = { method = "PUT", url = "https://api.vimeo.com/videos/{video_id}/presets/{preset_id}", path = {"preset_id", "video_id"} },
    ["vimeo.add_video_privacy_domain"] = { method = "PUT", url = "https://api.vimeo.com/videos/{video_id}/privacy/domains/{domain}", path = {"domain", "video_id"} },
    ["vimeo.add_video_privacy_user"] = { method = "PUT", url = "https://api.vimeo.com/videos/{video_id}/privacy/users/{user_id}", path = {"user_id", "video_id"} },
    ["vimeo.add_video_privacy_users"] = { method = "PUT", url = "https://api.vimeo.com/videos/{video_id}/privacy/users", path = {"video_id"} },
    ["vimeo.add_video_privacy_users_alt1"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/privacy/users", path = {"channel_id", "video_id"} },
    ["vimeo.add_video_tag"] = { method = "PUT", url = "https://api.vimeo.com/videos/{video_id}/tags/{word}", path = {"video_id", "word"} },
    ["vimeo.add_video_tags"] = { method = "PUT", url = "https://api.vimeo.com/videos/{video_id}/tags", path = {"video_id"} },
    ["vimeo.add_video_to_album"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/videos/{video_id}", path = {"album_id", "user_id", "video_id"} },
    ["vimeo.add_video_to_album_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/albums/{album_id}/videos/{video_id}", path = {"album_id", "video_id"} },
    ["vimeo.add_video_to_channel"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}", path = {"channel_id", "video_id"} },
    ["vimeo.add_video_to_group"] = { method = "PUT", url = "https://api.vimeo.com/groups/{group_id}/videos/{video_id}", path = {"group_id", "video_id"} },
    ["vimeo.add_video_to_portfolio"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/portfolios/{portfolio_id}/videos/{video_id}", path = {"portfolio_id", "user_id", "video_id"} },
    ["vimeo.add_video_to_portfolio_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/portfolios/{portfolio_id}/videos/{video_id}", path = {"portfolio_id", "video_id"} },
    ["vimeo.add_video_to_project"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/projects/{project_id}/videos/{video_id}", path = {"project_id", "user_id", "video_id"} },
    ["vimeo.add_video_to_project_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/projects/{project_id}/videos/{video_id}", path = {"project_id", "video_id"} },
    ["vimeo.add_video_to_vod"] = { method = "PUT", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/videos/{video_id}", path = {"ondemand_id", "video_id"} },
    ["vimeo.add_video_to_watch_later"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/watchlater/{video_id}", path = {"user_id", "video_id"} },
    ["vimeo.add_video_to_watch_later_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/watchlater/{video_id}", path = {"video_id"} },
    ["vimeo.add_videos_to_channel"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/videos", path = {"channel_id"}, body = {"video_uri"} },
    ["vimeo.add_videos_to_project"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/projects/{project_id}/videos", path = {"project_id", "user_id"}, query = {"uris"} },
    ["vimeo.add_videos_to_project_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/projects/{project_id}/videos", path = {"project_id"}, query = {"uris"} },
    ["vimeo.add_vod_genre"] = { method = "PUT", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/genres/{genre_id}", path = {"genre_id", "ondemand_id"} },
    ["vimeo.add_vod_poster"] = { method = "POST", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/pictures", path = {"ondemand_id"} },
    ["vimeo.add_vod_region"] = { method = "PUT", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/regions/{country}", path = {"country", "ondemand_id"} },
    ["vimeo.categorize_channel"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/categories/{category}", path = {"category", "channel_id"} },
    ["vimeo.check_category_for_video"] = { method = "GET", url = "https://api.vimeo.com/categories/{category}/videos/{video_id}", path = {"category", "video_id"} },
    ["vimeo.check_if_channel_has_tag"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/tags/{word}", path = {"channel_id", "word"} },
    ["vimeo.check_if_user_is_following"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/following/{follow_user_id}", path = {"follow_user_id", "user_id"} },
    ["vimeo.check_if_user_is_following_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/following/{follow_user_id}", path = {"follow_user_id"} },
    ["vimeo.check_if_user_joined_group"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/groups/{group_id}", path = {"group_id", "user_id"} },
    ["vimeo.check_if_user_joined_group_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/groups/{group_id}", path = {"group_id"} },
    ["vimeo.check_if_user_liked_video"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/likes/{video_id}", path = {"user_id", "video_id"} },
    ["vimeo.check_if_user_liked_video_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/likes/{video_id}", path = {"video_id"} },
    ["vimeo.check_if_user_owns_video"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/videos/{video_id}", path = {"user_id", "video_id"} },
    ["vimeo.check_if_user_owns_video_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/videos/{video_id}", path = {"video_id"} },
    ["vimeo.check_if_user_subscribed_to_category"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/categories/{category}", path = {"category", "user_id"} },
    ["vimeo.check_if_user_subscribed_to_category_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/categories/{category}", path = {"category"} },
    ["vimeo.check_if_user_subscribed_to_channel"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/channels/{channel_id}", path = {"channel_id", "user_id"} },
    ["vimeo.check_if_user_subscribed_to_channel_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/channels/{channel_id}", path = {"channel_id"} },
    ["vimeo.check_if_vod_was_purchased"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/ondemand/purchases", path = {"user_id"} },
    ["vimeo.check_if_vod_was_purchased_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/ondemand/purchases/{ondemand_id}", path = {"ondemand_id"} },
    ["vimeo.check_video_for_tag"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/tags/{word}", path = {"video_id", "word"} },
    ["vimeo.check_watch_later_queue"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/watchlater/{video_id}", path = {"user_id", "video_id"} },
    ["vimeo.check_watch_later_queue_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/watchlater/{video_id}", path = {"video_id"} },
    ["vimeo.client_auth"] = { method = "POST", url = "https://api.vimeo.com/oauth/authorize/client" },
    ["vimeo.complete_streaming_upload"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/uploads/{upload}", path = {"upload", "user_id"}, query = {"signature", "video_file_id"} },
    ["vimeo.convert_access_token"] = { method = "POST", url = "https://api.vimeo.com/oauth/authorize/vimeo_oauth1" },
    ["vimeo.create_album"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/albums", path = {"user_id"} },
    ["vimeo.create_album_alt1"] = { method = "POST", url = "https://api.vimeo.com/me/albums" },
    ["vimeo.create_album_custom_thumb"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/custom_thumbnails", path = {"album_id", "user_id"} },
    ["vimeo.create_album_logo"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/logos", path = {"album_id", "user_id"} },
    ["vimeo.create_channel"] = { method = "POST", url = "https://api.vimeo.com/channels" },
    ["vimeo.create_comment"] = { method = "POST", url = "https://api.vimeo.com/videos/{video_id}/comments", path = {"video_id"} },
    ["vimeo.create_comment_alt1"] = { method = "POST", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/comments", path = {"channel_id", "video_id"} },
    ["vimeo.create_comment_reply"] = { method = "POST", url = "https://api.vimeo.com/videos/{video_id}/comments/{comment_id}/replies", path = {"comment_id", "video_id"} },
    ["vimeo.create_custom_logo"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/customlogos", path = {"user_id"} },
    ["vimeo.create_custom_logo_alt1"] = { method = "POST", url = "https://api.vimeo.com/me/customlogos" },
    ["vimeo.create_group"] = { method = "POST", url = "https://api.vimeo.com/groups" },
    ["vimeo.create_picture"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/pictures", path = {"user_id"} },
    ["vimeo.create_picture_alt1"] = { method = "POST", url = "https://api.vimeo.com/me/pictures" },
    ["vimeo.create_project"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/projects", path = {"user_id"}, body = {"name"} },
    ["vimeo.create_project_alt1"] = { method = "POST", url = "https://api.vimeo.com/me/projects", body = {"name"} },
    ["vimeo.create_text_track"] = { method = "POST", url = "https://api.vimeo.com/videos/{video_id}/texttracks", path = {"video_id"} },
    ["vimeo.create_text_track_alt1"] = { method = "POST", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/texttracks", path = {"channel_id", "video_id"} },
    ["vimeo.create_video_custom_logo"] = { method = "POST", url = "https://api.vimeo.com/videos/{video_id}/timelinethumbnails", path = {"video_id"} },
    ["vimeo.create_video_thumbnail"] = { method = "POST", url = "https://api.vimeo.com/videos/{video_id}/pictures", path = {"video_id"} },
    ["vimeo.create_video_thumbnail_alt1"] = { method = "POST", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/pictures", path = {"channel_id", "video_id"} },
    ["vimeo.create_video_version"] = { method = "POST", url = "https://api.vimeo.com/videos/{video_id}/versions", path = {"video_id"} },
    ["vimeo.create_vod"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/ondemand/pages", path = {"user_id"}, body = {"accepted_currencies", "buy", "content_rating", "description", "domain_link", "episodes", "link", "name", "rent", "subscription", "type"} },
    ["vimeo.create_vod_alt1"] = { method = "POST", url = "https://api.vimeo.com/me/ondemand/pages", body = {"accepted_currencies", "buy", "content_rating", "description", "domain_link", "episodes", "link", "name", "rent", "subscription", "type"} },
    ["vimeo.create_vod_background"] = { method = "POST", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/backgrounds", path = {"ondemand_id"} },
    ["vimeo.create_vod_promotion"] = { method = "POST", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/promotions", path = {"ondemand_id"} },
    ["vimeo.delete_album"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}", path = {"album_id", "user_id"} },
    ["vimeo.delete_album_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/albums/{album_id}", path = {"album_id"} },
    ["vimeo.delete_album_custom_thumbnail"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/custom_thumbnails/{thumbnail_id}", path = {"album_id", "thumbnail_id", "user_id"} },
    ["vimeo.delete_album_logo"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/logos/{logo_id}", path = {"album_id", "logo_id", "user_id"} },
    ["vimeo.delete_channel"] = { method = "DELETE", url = "https://api.vimeo.com/channels/{channel_id}", path = {"channel_id"} },
    ["vimeo.delete_channel_category"] = { method = "DELETE", url = "https://api.vimeo.com/channels/{channel_id}/categories/{category}", path = {"category", "channel_id"} },
    ["vimeo.delete_channel_privacy_user"] = { method = "DELETE", url = "https://api.vimeo.com/channels/{channel_id}/privacy/users/{user_id}", path = {"channel_id", "user_id"} },
    ["vimeo.delete_comment"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}/comments/{comment_id}", path = {"comment_id", "video_id"} },
    ["vimeo.delete_from_watch_history"] = { method = "DELETE", url = "https://api.vimeo.com/me/watched/videos/{video_id}", path = {"video_id"} },
    ["vimeo.delete_group"] = { method = "DELETE", url = "https://api.vimeo.com/groups/{group_id}", path = {"group_id"} },
    ["vimeo.delete_picture"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/pictures/{portraitset_id}", path = {"portraitset_id", "user_id"} },
    ["vimeo.delete_picture_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/pictures/{portraitset_id}", path = {"portraitset_id"} },
    ["vimeo.delete_project"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/projects/{project_id}", path = {"project_id", "user_id"}, query = {"should_delete_clips"} },
    ["vimeo.delete_project_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/projects/{project_id}", path = {"project_id"}, query = {"should_delete_clips"} },
    ["vimeo.delete_tag_from_channel"] = { method = "DELETE", url = "https://api.vimeo.com/channels/{channel_id}/tags/{word}", path = {"channel_id", "word"} },
    ["vimeo.delete_text_track"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}/texttracks/{texttrack_id}", path = {"texttrack_id", "video_id"} },
    ["vimeo.delete_token"] = { method = "DELETE", url = "https://api.vimeo.com/tokens" },
    ["vimeo.delete_video"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}", path = {"video_id"} },
    ["vimeo.delete_video_credit"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}/credits/{credit_id}", path = {"credit_id", "video_id"} },
    ["vimeo.delete_video_embed_preset"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}/presets/{preset_id}", path = {"preset_id", "video_id"} },
    ["vimeo.delete_video_from_channel"] = { method = "DELETE", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}", path = {"channel_id", "video_id"} },
    ["vimeo.delete_video_from_group"] = { method = "DELETE", url = "https://api.vimeo.com/groups/{group_id}/videos/{video_id}", path = {"group_id", "video_id"} },
    ["vimeo.delete_video_from_portfolio"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/portfolios/{portfolio_id}/videos/{video_id}", path = {"portfolio_id", "user_id", "video_id"} },
    ["vimeo.delete_video_from_portfolio_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/portfolios/{portfolio_id}/videos/{video_id}", path = {"portfolio_id", "video_id"} },
    ["vimeo.delete_video_from_vod"] = { method = "DELETE", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/videos/{video_id}", path = {"ondemand_id", "video_id"} },
    ["vimeo.delete_video_from_watch_later"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/watchlater/{video_id}", path = {"user_id", "video_id"} },
    ["vimeo.delete_video_from_watch_later_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/watchlater/{video_id}", path = {"video_id"} },
    ["vimeo.delete_video_privacy_domain"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}/privacy/domains/{domain}", path = {"domain", "video_id"} },
    ["vimeo.delete_video_privacy_user"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}/privacy/users/{user_id}", path = {"user_id", "video_id"} },
    ["vimeo.delete_video_tag"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}/tags/{word}", path = {"video_id", "word"} },
    ["vimeo.delete_video_thumbnail"] = { method = "DELETE", url = "https://api.vimeo.com/videos/{video_id}/pictures/{picture_id}", path = {"picture_id", "video_id"} },
    ["vimeo.delete_vod_background"] = { method = "DELETE", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/backgrounds/{background_id}", path = {"background_id", "ondemand_id"} },
    ["vimeo.delete_vod_draft"] = { method = "DELETE", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}", path = {"ondemand_id"} },
    ["vimeo.delete_vod_genre"] = { method = "DELETE", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/genres/{genre_id}", path = {"genre_id", "ondemand_id"} },
    ["vimeo.delete_vod_promotion"] = { method = "DELETE", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/promotions/{promotion_id}", path = {"ondemand_id", "promotion_id"} },
    ["vimeo.delete_vod_region"] = { method = "DELETE", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/regions/{country}", path = {"country", "ondemand_id"} },
    ["vimeo.delete_vod_regions"] = { method = "DELETE", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/regions", path = {"ondemand_id"} },
    ["vimeo.delete_watch_history"] = { method = "DELETE", url = "https://api.vimeo.com/me/watched/videos" },
    ["vimeo.edit_album"] = { method = "PATCH", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}", path = {"album_id", "user_id"} },
    ["vimeo.edit_album_alt1"] = { method = "PATCH", url = "https://api.vimeo.com/me/albums/{album_id}", path = {"album_id"} },
    ["vimeo.edit_channel"] = { method = "PATCH", url = "https://api.vimeo.com/channels/{channel_id}", path = {"channel_id"} },
    ["vimeo.edit_comment"] = { method = "PATCH", url = "https://api.vimeo.com/videos/{video_id}/comments/{comment_id}", path = {"comment_id", "video_id"} },
    ["vimeo.edit_embed_preset"] = { method = "PATCH", url = "https://api.vimeo.com/users/{user_id}/presets/{preset_id}", path = {"preset_id", "user_id"} },
    ["vimeo.edit_embed_preset_alt1"] = { method = "PATCH", url = "https://api.vimeo.com/me/presets/{preset_id}", path = {"preset_id"} },
    ["vimeo.edit_picture"] = { method = "PATCH", url = "https://api.vimeo.com/users/{user_id}/pictures/{portraitset_id}", path = {"portraitset_id", "user_id"} },
    ["vimeo.edit_picture_alt1"] = { method = "PATCH", url = "https://api.vimeo.com/me/pictures/{portraitset_id}", path = {"portraitset_id"} },
    ["vimeo.edit_project"] = { method = "PATCH", url = "https://api.vimeo.com/users/{user_id}/projects/{project_id}", path = {"project_id", "user_id"}, body = {"name"} },
    ["vimeo.edit_project_alt1"] = { method = "PATCH", url = "https://api.vimeo.com/me/projects/{project_id}", path = {"project_id"}, body = {"name"} },
    ["vimeo.edit_text_track"] = { method = "PATCH", url = "https://api.vimeo.com/videos/{video_id}/texttracks/{texttrack_id}", path = {"texttrack_id", "video_id"} },
    ["vimeo.edit_user"] = { method = "PATCH", url = "https://api.vimeo.com/users/{user_id}", path = {"user_id"} },
    ["vimeo.edit_user_alt1"] = { method = "PATCH", url = "https://api.vimeo.com/me" },
    ["vimeo.edit_video"] = { method = "PATCH", url = "https://api.vimeo.com/videos/{video_id}", path = {"video_id"} },
    ["vimeo.edit_video_credit"] = { method = "PATCH", url = "https://api.vimeo.com/videos/{video_id}/credits/{credit_id}", path = {"credit_id", "video_id"} },
    ["vimeo.edit_video_thumbnail"] = { method = "PATCH", url = "https://api.vimeo.com/videos/{video_id}/pictures/{picture_id}", path = {"picture_id", "video_id"} },
    ["vimeo.edit_vod"] = { method = "PATCH", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}", path = {"ondemand_id"} },
    ["vimeo.edit_vod_background"] = { method = "PATCH", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/backgrounds/{background_id}", path = {"background_id", "ondemand_id"} },
    ["vimeo.edit_vod_poster"] = { method = "PATCH", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/pictures/{poster_id}", path = {"ondemand_id", "poster_id"} },
    ["vimeo.exchange_auth_code"] = { method = "POST", url = "https://api.vimeo.com/oauth/access_token" },
    ["vimeo.follow_user"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/following/{follow_user_id}", path = {"follow_user_id", "user_id"} },
    ["vimeo.follow_user_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/following/{follow_user_id}", path = {"follow_user_id"} },
    ["vimeo.follow_users"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/following", path = {"user_id"}, body = {"users"} },
    ["vimeo.follow_users_alt1"] = { method = "POST", url = "https://api.vimeo.com/me/following", body = {"users"} },
    ["vimeo.get_album"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}", path = {"album_id", "user_id"} },
    ["vimeo.get_album_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/albums/{album_id}", path = {"album_id"} },
    ["vimeo.get_album_custom_thumbnail"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/custom_thumbnails/{thumbnail_id}", path = {"album_id", "thumbnail_id", "user_id"} },
    ["vimeo.get_album_custom_thumbs"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/custom_thumbnails", path = {"album_id", "user_id"}, query = {"page", "per_page"} },
    ["vimeo.get_album_logo"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/logos/{logo_id}", path = {"album_id", "logo_id", "user_id"} },
    ["vimeo.get_album_logos"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/logos", path = {"album_id", "user_id"}, query = {"page", "per_page"} },
    ["vimeo.get_album_video"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/videos/{video_id}", path = {"album_id", "user_id", "video_id"}, query = {"password"} },
    ["vimeo.get_album_video_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/albums/{album_id}/videos/{video_id}", path = {"album_id", "video_id"}, query = {"password"} },
    ["vimeo.get_album_videos"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/videos", path = {"album_id", "user_id"}, query = {"containing_uri", "direction", "filter", "filter_embeddable", "page", "password", "per_page", "query", "sort", "weak_search"} },
    ["vimeo.get_album_videos_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/albums/{album_id}/videos", path = {"album_id"}, query = {"containing_uri", "direction", "filter", "filter_embeddable", "page", "password", "per_page", "query", "sort", "weak_search"} },
    ["vimeo.get_albums"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/albums", path = {"user_id"}, query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_albums_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/albums", query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_appearances"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/appearances", path = {"user_id"}, query = {"direction", "filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_appearances_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/appearances", query = {"direction", "filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_available_video_channels"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/available_channels", path = {"video_id"} },
    ["vimeo.get_categories"] = { method = "GET", url = "https://api.vimeo.com/categories", query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_category"] = { method = "GET", url = "https://api.vimeo.com/categories/{category}", path = {"category"} },
    ["vimeo.get_category_channels"] = { method = "GET", url = "https://api.vimeo.com/categories/{category}/channels", path = {"category"}, query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_category_groups"] = { method = "GET", url = "https://api.vimeo.com/categories/{category}/groups", path = {"category"}, query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_category_subscriptions"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/categories", path = {"user_id"}, query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_category_subscriptions_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/categories", query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_category_videos"] = { method = "GET", url = "https://api.vimeo.com/categories/{category}/videos", path = {"category"}, query = {"direction", "filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_cc_licenses"] = { method = "GET", url = "https://api.vimeo.com/creativecommons" },
    ["vimeo.get_channel"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}", path = {"channel_id"} },
    ["vimeo.get_channel_categories"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/categories", path = {"channel_id"} },
    ["vimeo.get_channel_moderator"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/moderators/{user_id}", path = {"channel_id", "user_id"} },
    ["vimeo.get_channel_moderators"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/moderators", path = {"channel_id"}, query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_channel_privacy_users"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/privacy/users", path = {"channel_id"}, query = {"direction", "page", "per_page"} },
    ["vimeo.get_channel_subscribers"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/users", path = {"channel_id"}, query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_channel_subscriptions"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/channels", path = {"user_id"}, query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_channel_subscriptions_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/channels", query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_channel_tags"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/tags", path = {"channel_id"} },
    ["vimeo.get_channel_video"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}", path = {"channel_id", "video_id"} },
    ["vimeo.get_channel_videos"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/videos", path = {"channel_id"}, query = {"containing_uri", "direction", "filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_channels"] = { method = "GET", url = "https://api.vimeo.com/channels", query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_comment"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/comments/{comment_id}", path = {"comment_id", "video_id"} },
    ["vimeo.get_comment_replies"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/comments/{comment_id}/replies", path = {"comment_id", "video_id"}, query = {"page", "per_page"} },
    ["vimeo.get_comments"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/comments", path = {"video_id"}, query = {"direction", "page", "per_page"} },
    ["vimeo.get_comments_alt1"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/comments", path = {"channel_id", "video_id"}, query = {"direction", "page", "per_page"} },
    ["vimeo.get_content_ratings"] = { method = "GET", url = "https://api.vimeo.com/contentratings" },
    ["vimeo.get_custom_logo"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/customlogos/{logo_id}", path = {"logo_id", "user_id"} },
    ["vimeo.get_custom_logo_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/customlogos/{logo_id}", path = {"logo_id"} },
    ["vimeo.get_custom_logos"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/customlogos", path = {"user_id"} },
    ["vimeo.get_custom_logos_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/customlogos" },
    ["vimeo.get_embed_preset"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/presets/{preset_id}", path = {"preset_id", "user_id"} },
    ["vimeo.get_embed_preset_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/presets/{preset_id}", path = {"preset_id"} },
    ["vimeo.get_embed_preset_videos"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/presets/{preset_id}/videos", path = {"preset_id", "user_id"}, query = {"page", "per_page"} },
    ["vimeo.get_embed_preset_videos_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/presets/{preset_id}/videos", path = {"preset_id"}, query = {"page", "per_page"} },
    ["vimeo.get_embed_presets"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/presets", path = {"user_id"}, query = {"page", "per_page"} },
    ["vimeo.get_embed_presets_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/presets", query = {"page", "per_page"} },
    ["vimeo.get_endpoints"] = { method = "GET", url = "https://api.vimeo.com/", query = {"openapi"} },
    ["vimeo.get_feed"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/feed", path = {"user_id"}, query = {"offset", "page", "per_page", "type"} },
    ["vimeo.get_feed_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/feed", query = {"offset", "page", "per_page", "type"} },
    ["vimeo.get_followers"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/followers", path = {"user_id"}, query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_followers_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/followers", query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_genre_vod"] = { method = "GET", url = "https://api.vimeo.com/ondemand/genres/{genre_id}/pages/{ondemand_id}", path = {"genre_id", "ondemand_id"} },
    ["vimeo.get_genre_vods"] = { method = "GET", url = "https://api.vimeo.com/ondemand/genres/{genre_id}/pages", path = {"genre_id"}, query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_group"] = { method = "GET", url = "https://api.vimeo.com/groups/{group_id}", path = {"group_id"} },
    ["vimeo.get_group_members"] = { method = "GET", url = "https://api.vimeo.com/groups/{group_id}/users", path = {"group_id"}, query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_group_video"] = { method = "GET", url = "https://api.vimeo.com/groups/{group_id}/videos/{video_id}", path = {"group_id", "video_id"} },
    ["vimeo.get_group_videos"] = { method = "GET", url = "https://api.vimeo.com/groups/{group_id}/videos", path = {"group_id"}, query = {"direction", "filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_groups"] = { method = "GET", url = "https://api.vimeo.com/groups", query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_languages"] = { method = "GET", url = "https://api.vimeo.com/languages", query = {"filter"} },
    ["vimeo.get_likes"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/likes", path = {"user_id"}, query = {"filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_likes_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/likes", query = {"filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_picture"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/pictures/{portraitset_id}", path = {"portraitset_id", "user_id"} },
    ["vimeo.get_picture_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/pictures/{portraitset_id}", path = {"portraitset_id"} },
    ["vimeo.get_pictures"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/pictures", path = {"user_id"}, query = {"page", "per_page"} },
    ["vimeo.get_pictures_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/pictures", query = {"page", "per_page"} },
    ["vimeo.get_portfolio"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/portfolios/{portfolio_id}", path = {"portfolio_id", "user_id"} },
    ["vimeo.get_portfolio_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/portfolios/{portfolio_id}", path = {"portfolio_id"} },
    ["vimeo.get_portfolio_video"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/portfolios/{portfolio_id}/videos/{video_id}", path = {"portfolio_id", "user_id", "video_id"} },
    ["vimeo.get_portfolio_video_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/portfolios/{portfolio_id}/videos/{video_id}", path = {"portfolio_id", "video_id"} },
    ["vimeo.get_portfolio_videos"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/portfolios/{portfolio_id}/videos", path = {"portfolio_id", "user_id"}, query = {"containing_uri", "filter", "filter_embeddable", "page", "per_page", "sort"} },
    ["vimeo.get_portfolio_videos_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/portfolios/{portfolio_id}/videos", path = {"portfolio_id"}, query = {"containing_uri", "filter", "filter_embeddable", "page", "per_page", "sort"} },
    ["vimeo.get_portfolios"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/portfolios", path = {"user_id"}, query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_portfolios_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/portfolios", query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_project"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/projects/{project_id}", path = {"project_id", "user_id"} },
    ["vimeo.get_project_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/projects/{project_id}", path = {"project_id"} },
    ["vimeo.get_project_videos"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/projects/{project_id}/videos", path = {"project_id", "user_id"}, query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_project_videos_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/projects/{project_id}/videos", path = {"project_id"}, query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_projects"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/projects", path = {"user_id"}, query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_projects_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/projects", query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_region"] = { method = "GET", url = "https://api.vimeo.com/ondemand/regions/{country}", path = {"country"} },
    ["vimeo.get_regions"] = { method = "GET", url = "https://api.vimeo.com/ondemand/regions" },
    ["vimeo.get_related_videos"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/videos", path = {"video_id"}, query = {"filter", "page", "per_page"} },
    ["vimeo.get_tag"] = { method = "GET", url = "https://api.vimeo.com/tags/{word}", path = {"word"} },
    ["vimeo.get_text_track"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/texttracks/{texttrack_id}", path = {"texttrack_id", "video_id"} },
    ["vimeo.get_text_tracks"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/texttracks", path = {"video_id"} },
    ["vimeo.get_text_tracks_alt1"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/texttracks", path = {"channel_id", "video_id"} },
    ["vimeo.get_upload_attempt"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/uploads/{upload}", path = {"upload", "user_id"} },
    ["vimeo.get_user"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}", path = {"user_id"} },
    ["vimeo.get_user_alt1"] = { method = "GET", url = "https://api.vimeo.com/me" },
    ["vimeo.get_user_following"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/following", path = {"user_id"}, query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_user_following_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/following", query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_user_groups"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/groups", path = {"user_id"}, query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_user_groups_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/groups", query = {"direction", "filter", "page", "per_page", "query", "sort"} },
    ["vimeo.get_user_vods"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/ondemand/pages", path = {"user_id"}, query = {"direction", "filter", "page", "per_page", "sort"} },
    ["vimeo.get_user_vods_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/ondemand/pages", query = {"direction", "filter", "page", "per_page", "sort"} },
    ["vimeo.get_video"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}", path = {"video_id"} },
    ["vimeo.get_video_categories"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/categories", path = {"video_id"} },
    ["vimeo.get_video_credit"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/credits/{credit_id}", path = {"credit_id", "video_id"} },
    ["vimeo.get_video_credits"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/credits", path = {"video_id"}, query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_video_credits_alt1"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/credits", path = {"channel_id", "video_id"}, query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.get_video_custom_logo"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/timelinethumbnails/{thumbnail_id}", path = {"thumbnail_id", "video_id"} },
    ["vimeo.get_video_embed_preset"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/presets/{preset_id}", path = {"preset_id", "video_id"} },
    ["vimeo.get_video_likes"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/likes", path = {"video_id"}, query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_video_likes_alt1"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/likes", path = {"channel_id", "video_id"}, query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_video_privacy_domains"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/privacy/domains", path = {"video_id"}, query = {"page", "per_page"} },
    ["vimeo.get_video_privacy_users"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/privacy/users", path = {"video_id"}, query = {"page", "per_page"} },
    ["vimeo.get_video_privacy_users_alt1"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/privacy/users", path = {"channel_id", "video_id"}, query = {"page", "per_page"} },
    ["vimeo.get_video_tags"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/tags", path = {"video_id"} },
    ["vimeo.get_video_thumbnail"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/pictures/{picture_id}", path = {"picture_id", "video_id"} },
    ["vimeo.get_video_thumbnails"] = { method = "GET", url = "https://api.vimeo.com/videos/{video_id}/pictures", path = {"video_id"}, query = {"page", "per_page"} },
    ["vimeo.get_video_thumbnails_alt1"] = { method = "GET", url = "https://api.vimeo.com/channels/{channel_id}/videos/{video_id}/pictures", path = {"channel_id", "video_id"}, query = {"page", "per_page"} },
    ["vimeo.get_videos"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/videos", path = {"user_id"}, query = {"containing_uri", "direction", "filter", "filter_embeddable", "filter_playable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_videos_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/videos", query = {"containing_uri", "direction", "filter", "filter_embeddable", "filter_playable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_videos_with_tag"] = { method = "GET", url = "https://api.vimeo.com/tags/{word}/videos", path = {"word"}, query = {"direction", "page", "per_page", "sort"} },
    ["vimeo.get_vod"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}", path = {"ondemand_id"} },
    ["vimeo.get_vod_background"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/backgrounds/{background_id}", path = {"background_id", "ondemand_id"} },
    ["vimeo.get_vod_backgrounds"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/backgrounds", path = {"ondemand_id"}, query = {"page", "per_page"} },
    ["vimeo.get_vod_genre"] = { method = "GET", url = "https://api.vimeo.com/ondemand/genres/{genre_id}", path = {"genre_id"} },
    ["vimeo.get_vod_genre_by_ondemand_id"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/genres/{genre_id}", path = {"genre_id", "ondemand_id"} },
    ["vimeo.get_vod_genres"] = { method = "GET", url = "https://api.vimeo.com/ondemand/genres" },
    ["vimeo.get_vod_genres_by_ondemand_id"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/genres", path = {"ondemand_id"} },
    ["vimeo.get_vod_likes"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/likes", path = {"ondemand_id"}, query = {"direction", "filter", "page", "per_page", "sort"} },
    ["vimeo.get_vod_poster"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/pictures/{poster_id}", path = {"ondemand_id", "poster_id"} },
    ["vimeo.get_vod_posters"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/pictures", path = {"ondemand_id"}, query = {"page", "per_page"} },
    ["vimeo.get_vod_promotion"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/promotions/{promotion_id}", path = {"ondemand_id", "promotion_id"} },
    ["vimeo.get_vod_promotion_codes"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/promotions/{promotion_id}/codes", path = {"ondemand_id", "promotion_id"}, query = {"page", "per_page"} },
    ["vimeo.get_vod_promotions"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/promotions", path = {"ondemand_id"}, query = {"filter", "page", "per_page"} },
    ["vimeo.get_vod_purchases"] = { method = "GET", url = "https://api.vimeo.com/me/ondemand/purchases", query = {"direction", "filter", "page", "per_page", "sort"} },
    ["vimeo.get_vod_region"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/regions/{country}", path = {"country", "ondemand_id"} },
    ["vimeo.get_vod_regions"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/regions", path = {"ondemand_id"} },
    ["vimeo.get_vod_season"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/seasons/{season_id}", path = {"ondemand_id", "season_id"} },
    ["vimeo.get_vod_season_videos"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/seasons/{season_id}/videos", path = {"ondemand_id", "season_id"}, query = {"filter", "page", "per_page", "sort"} },
    ["vimeo.get_vod_seasons"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/seasons", path = {"ondemand_id"}, query = {"direction", "filter", "page", "per_page", "sort"} },
    ["vimeo.get_vod_video"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/videos/{video_id}", path = {"ondemand_id", "video_id"} },
    ["vimeo.get_vod_videos"] = { method = "GET", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/videos", path = {"ondemand_id"}, query = {"direction", "filter", "page", "per_page", "sort"} },
    ["vimeo.get_watch_history"] = { method = "GET", url = "https://api.vimeo.com/me/watched/videos", query = {"page", "per_page"} },
    ["vimeo.get_watch_later_queue"] = { method = "GET", url = "https://api.vimeo.com/users/{user_id}/watchlater", path = {"user_id"}, query = {"direction", "filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.get_watch_later_queue_alt1"] = { method = "GET", url = "https://api.vimeo.com/me/watchlater", query = {"direction", "filter", "filter_embeddable", "page", "per_page", "query", "sort"} },
    ["vimeo.join_group"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/groups/{group_id}", path = {"group_id", "user_id"} },
    ["vimeo.join_group_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/groups/{group_id}", path = {"group_id"} },
    ["vimeo.leave_group"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/groups/{group_id}", path = {"group_id", "user_id"} },
    ["vimeo.leave_group_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/groups/{group_id}", path = {"group_id"} },
    ["vimeo.like_video"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/likes/{video_id}", path = {"user_id", "video_id"} },
    ["vimeo.like_video_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/likes/{video_id}", path = {"video_id"} },
    ["vimeo.remove_channel_moderator"] = { method = "DELETE", url = "https://api.vimeo.com/channels/{channel_id}/moderators/{user_id}", path = {"channel_id", "user_id"} },
    ["vimeo.remove_channel_moderators"] = { method = "DELETE", url = "https://api.vimeo.com/channels/{channel_id}/moderators", path = {"channel_id"} },
    ["vimeo.remove_video_from_album"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/videos/{video_id}", path = {"album_id", "user_id", "video_id"} },
    ["vimeo.remove_video_from_album_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/albums/{album_id}/videos/{video_id}", path = {"album_id", "video_id"} },
    ["vimeo.remove_video_from_project"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/projects/{project_id}/videos/{video_id}", path = {"project_id", "user_id", "video_id"} },
    ["vimeo.remove_video_from_project_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/projects/{project_id}/videos/{video_id}", path = {"project_id", "video_id"} },
    ["vimeo.remove_videos_from_channel"] = { method = "DELETE", url = "https://api.vimeo.com/channels/{channel_id}/videos", path = {"channel_id"}, body = {"video_uri"} },
    ["vimeo.remove_videos_from_project"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/projects/{project_id}/videos", path = {"project_id", "user_id"}, query = {"should_delete_clips", "uris"} },
    ["vimeo.remove_videos_from_project_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/projects/{project_id}/videos", path = {"project_id"}, query = {"should_delete_clips", "uris"} },
    ["vimeo.replace_album_custom_thumb"] = { method = "PATCH", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/custom_thumbnails/{thumbnail_id}", path = {"album_id", "thumbnail_id", "user_id"} },
    ["vimeo.replace_album_logo"] = { method = "PATCH", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/logos/{logo_id}", path = {"album_id", "logo_id", "user_id"} },
    ["vimeo.replace_channel_moderators"] = { method = "PATCH", url = "https://api.vimeo.com/channels/{channel_id}/moderators", path = {"channel_id"}, body = {"user_uri"} },
    ["vimeo.replace_videos_in_album"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/videos", path = {"album_id", "user_id"}, body = {"videos"} },
    ["vimeo.replace_videos_in_album_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/albums/{album_id}/videos", path = {"album_id"}, body = {"videos"} },
    ["vimeo.search_users"] = { method = "GET", url = "https://api.vimeo.com/users", query = {"direction", "page", "per_page", "query", "sort"} },
    ["vimeo.search_videos"] = { method = "GET", url = "https://api.vimeo.com/videos", query = {"direction", "filter", "links", "page", "per_page", "query", "sort", "uris"} },
    ["vimeo.set_channel_privacy_user"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/privacy/users/{user_id}", path = {"channel_id", "user_id"} },
    ["vimeo.set_channel_privacy_users"] = { method = "PUT", url = "https://api.vimeo.com/channels/{channel_id}/privacy/users", path = {"channel_id"} },
    ["vimeo.set_video_as_album_thumbnail"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/albums/{album_id}/videos/{video_id}/set_album_thumbnail", path = {"album_id", "user_id", "video_id"}, body = {"time_code"} },
    ["vimeo.set_video_as_album_thumbnail_alt1"] = { method = "POST", url = "https://api.vimeo.com/me/albums/{album_id}/videos/{video_id}/set_album_thumbnail", path = {"album_id", "video_id"}, body = {"time_code"} },
    ["vimeo.set_vod_regions"] = { method = "PUT", url = "https://api.vimeo.com/ondemand/pages/{ondemand_id}/regions", path = {"ondemand_id"} },
    ["vimeo.subscribe_to_category"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/categories/{category}", path = {"category", "user_id"} },
    ["vimeo.subscribe_to_category_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/categories/{category}", path = {"category"} },
    ["vimeo.subscribe_to_channel"] = { method = "PUT", url = "https://api.vimeo.com/users/{user_id}/channels/{channel_id}", path = {"channel_id", "user_id"} },
    ["vimeo.subscribe_to_channel_alt1"] = { method = "PUT", url = "https://api.vimeo.com/me/channels/{channel_id}", path = {"channel_id"} },
    ["vimeo.suggest_video_category"] = { method = "PUT", url = "https://api.vimeo.com/videos/{video_id}/categories", path = {"video_id"} },
    ["vimeo.unfollow_user"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/following/{follow_user_id}", path = {"follow_user_id", "user_id"} },
    ["vimeo.unfollow_user_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/following/{follow_user_id}", path = {"follow_user_id"} },
    ["vimeo.unlike_video"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/likes/{video_id}", path = {"user_id", "video_id"} },
    ["vimeo.unlike_video_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/likes/{video_id}", path = {"video_id"} },
    ["vimeo.unsubscribe_from_category"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/categories/{category}", path = {"category", "user_id"} },
    ["vimeo.unsubscribe_from_category_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/categories/{category}", path = {"category"} },
    ["vimeo.unsubscribe_from_channel"] = { method = "DELETE", url = "https://api.vimeo.com/users/{user_id}/channels/{channel_id}", path = {"channel_id", "user_id"} },
    ["vimeo.unsubscribe_from_channel_alt1"] = { method = "DELETE", url = "https://api.vimeo.com/me/channels/{channel_id}", path = {"channel_id"} },
    ["vimeo.upload_video"] = { method = "POST", url = "https://api.vimeo.com/users/{user_id}/videos", path = {"user_id"} },
    ["vimeo.upload_video_alt1"] = { method = "POST", url = "https://api.vimeo.com/me/videos" },
    ["vimeo.verify_token"] = { method = "GET", url = "https://api.vimeo.com/oauth/verify" },
  },
}
