-- Figma — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/figma/rest-api-spec/main/openapi/openapi.yaml
-- Published by figma, the vendor's own GitHub organisation.
-- 50 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "figma-scim",
  name = "Figma",
  base = "https://{host}/scim/v2/{tenantId}",
  docs = "https://nango.dev/docs/integrations/all/figma-scim",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "FIGMA_SCIM_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = { ["host"] = "FIGMA_SCIM_HOST", ["tenantId"] = "FIGMA_SCIM_TENANTID" },
  headers = {},
  operations = {
    ["figma-scim.delete_comment"] = { method = "DELETE", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/comments/{comment_id}", path = {"file_key", "comment_id"} },
    ["figma-scim.delete_comment_reaction"] = { method = "DELETE", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/comments/{comment_id}/reactions", path = {"file_key", "comment_id"}, query = {"emoji"} },
    ["figma-scim.delete_dev_resource"] = { method = "DELETE", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/dev_resources/{dev_resource_id}", path = {"file_key", "dev_resource_id"} },
    ["figma-scim.delete_webhook"] = { method = "DELETE", url = "https://{host}/scim/v2/{tenantId}/v2/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["figma-scim.get_activity_logs"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/activity_logs", query = {"events", "start_time", "end_time", "limit", "order"} },
    ["figma-scim.get_ai_usage_daily"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/ai_usage/daily", query = {"start_date", "end_date", "user_email", "limit", "cursor"} },
    ["figma-scim.get_comment_reactions"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/comments/{comment_id}/reactions", path = {"file_key", "comment_id"}, query = {"cursor"} },
    ["figma-scim.get_comments"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/comments", path = {"file_key"}, query = {"as_md"} },
    ["figma-scim.get_component"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/components/{key}" },
    ["figma-scim.get_component_set"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/component_sets/{key}" },
    ["figma-scim.get_dev_resources"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/dev_resources", path = {"file_key"}, query = {"node_ids"} },
    ["figma-scim.get_developer_logs"] = { method = "POST", url = "https://{host}/scim/v2/{tenantId}/v1/developer_logs", body = {"token_type", "token_name", "user_email", "ip_address", "event_source", "date_range", "limit", "cursor"} },
    ["figma-scim.get_file"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}", path = {"file_key"}, query = {"version", "ids", "depth", "geometry", "plugin_data", "branch_data"} },
    ["figma-scim.get_file_component_sets"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/component_sets", path = {"file_key"} },
    ["figma-scim.get_file_components"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/components", path = {"file_key"} },
    ["figma-scim.get_file_meta"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/meta", path = {"file_key"} },
    ["figma-scim.get_file_nodes"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/nodes", path = {"file_key"}, query = {"ids", "version", "depth", "geometry", "plugin_data"} },
    ["figma-scim.get_file_styles"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/styles", path = {"file_key"} },
    ["figma-scim.get_file_versions"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/versions", path = {"file_key"}, query = {"page_size", "before", "after"} },
    ["figma-scim.get_folder_files"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v2/folders/{folder_id}/files", path = {"folder_id"}, query = {"branch_data"} },
    ["figma-scim.get_folder_folders"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v2/folders/{folder_id}/folders", path = {"folder_id"} },
    ["figma-scim.get_folder_meta"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v2/folders/{folder_id}/meta", path = {"folder_id"} },
    ["figma-scim.get_image_fills"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/images", path = {"file_key"} },
    ["figma-scim.get_images"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/images/{file_key}", path = {"file_key"}, query = {"ids", "version", "scale", "format", "svg_outline_text", "svg_include_id", "svg_include_node_id", "svg_simplify_stroke", "contents_only", "use_absolute_bounds"} },
    ["figma-scim.get_library_analytics_component_actions"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/analytics/libraries/{file_key}/component/actions", path = {"file_key"}, query = {"cursor", "group_by", "start_date", "end_date"} },
    ["figma-scim.get_library_analytics_component_usages"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/analytics/libraries/{file_key}/component/usages", path = {"file_key"}, query = {"cursor", "group_by"} },
    ["figma-scim.get_library_analytics_style_actions"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/analytics/libraries/{file_key}/style/actions", path = {"file_key"}, query = {"cursor", "group_by", "start_date", "end_date"} },
    ["figma-scim.get_library_analytics_style_usages"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/analytics/libraries/{file_key}/style/usages", path = {"file_key"}, query = {"cursor", "group_by"} },
    ["figma-scim.get_library_analytics_variable_actions"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/analytics/libraries/{file_key}/variable/actions", path = {"file_key"}, query = {"cursor", "group_by", "start_date", "end_date"} },
    ["figma-scim.get_library_analytics_variable_usages"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/analytics/libraries/{file_key}/variable/usages", path = {"file_key"}, query = {"cursor", "group_by"} },
    ["figma-scim.get_local_variables"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/variables/local", path = {"file_key"} },
    ["figma-scim.get_me"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/me" },
    ["figma-scim.get_oembed"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/oembed", query = {"url", "maxwidth", "maxheight"} },
    ["figma-scim.get_payments"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/payments", query = {"plugin_payment_token", "user_id", "community_file_id", "plugin_id", "widget_id"} },
    ["figma-scim.get_published_variables"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/variables/published", path = {"file_key"} },
    ["figma-scim.get_style"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/styles/{key}" },
    ["figma-scim.get_team_component_sets"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/teams/{team_id}/component_sets", path = {"team_id"}, query = {"page_size", "after", "before"} },
    ["figma-scim.get_team_components"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/teams/{team_id}/components", path = {"team_id"}, query = {"page_size", "after", "before"} },
    ["figma-scim.get_team_folders"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v2/teams/{team_id}/folders", path = {"team_id"} },
    ["figma-scim.get_team_styles"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v1/teams/{team_id}/styles", path = {"team_id"}, query = {"page_size", "after", "before"} },
    ["figma-scim.get_webhook"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v2/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["figma-scim.get_webhook_requests"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v2/webhooks/{webhook_id}/requests", path = {"webhook_id"} },
    ["figma-scim.get_webhooks"] = { method = "GET", url = "https://{host}/scim/v2/{tenantId}/v2/webhooks", query = {"context", "context_id", "plan_api_id", "cursor"} },
    ["figma-scim.post_comment"] = { method = "POST", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/comments", path = {"file_key"}, body = {"message", "comment_id", "client_meta"} },
    ["figma-scim.post_comment_reaction"] = { method = "POST", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/comments/{comment_id}/reactions", path = {"file_key", "comment_id"}, body = {"emoji"} },
    ["figma-scim.post_dev_resources"] = { method = "POST", url = "https://{host}/scim/v2/{tenantId}/v1/dev_resources", body = {"dev_resources"} },
    ["figma-scim.post_variables"] = { method = "POST", url = "https://{host}/scim/v2/{tenantId}/v1/files/{file_key}/variables", path = {"file_key"}, body = {"variableCollections", "variableModes", "variables", "variableModeValues"} },
    ["figma-scim.post_webhook"] = { method = "POST", url = "https://{host}/scim/v2/{tenantId}/v2/webhooks", body = {"event_type", "team_id", "context", "context_id", "endpoint", "passcode", "status", "description"} },
    ["figma-scim.put_dev_resources"] = { method = "PUT", url = "https://{host}/scim/v2/{tenantId}/v1/dev_resources", body = {"dev_resources"} },
    ["figma-scim.put_webhook"] = { method = "PUT", url = "https://{host}/scim/v2/{tenantId}/v2/webhooks/{webhook_id}", path = {"webhook_id"}, body = {"event_type", "endpoint", "passcode", "status", "description"} },
  },
}
