-- Outline — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/outline/openapi/main/spec3.json
-- Published by outline, the vendor's own GitHub organisation.
-- 154 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "outline",
  name = "Outline",
  base = "https://app.getoutline.com/api",
  docs = "https://nango.dev/docs/api-integrations/outline",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "OUTLINE_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["outline.access_requests_approve"] = { method = "POST", url = "https://app.getoutline.com/api/accessRequests.approve", body = {"id", "permission"} },
    ["outline.access_requests_create"] = { method = "POST", url = "https://app.getoutline.com/api/accessRequests.create", body = {"documentId"} },
    ["outline.access_requests_dismiss"] = { method = "POST", url = "https://app.getoutline.com/api/accessRequests.dismiss", body = {"id"} },
    ["outline.access_requests_info"] = { method = "POST", url = "https://app.getoutline.com/api/accessRequests.info", body = {"id", "documentId"} },
    ["outline.api_keys_create"] = { method = "POST", url = "https://app.getoutline.com/api/apiKeys.create", body = {"name", "expiresAt", "scope"} },
    ["outline.api_keys_delete"] = { method = "POST", url = "https://app.getoutline.com/api/apiKeys.delete", body = {"id"} },
    ["outline.api_keys_list"] = { method = "POST", url = "https://app.getoutline.com/api/apiKeys.list", body = {"offset", "limit"} },
    ["outline.attachments_create"] = { method = "POST", url = "https://app.getoutline.com/api/attachments.create", body = {"name", "documentId", "contentType", "size"} },
    ["outline.attachments_create_from_url"] = { method = "POST", url = "https://app.getoutline.com/api/attachments.createFromUrl", body = {"url", "documentId", "id"} },
    ["outline.attachments_delete"] = { method = "POST", url = "https://app.getoutline.com/api/attachments.delete", body = {"id"} },
    ["outline.attachments_list"] = { method = "POST", url = "https://app.getoutline.com/api/attachments.list", body = {"offset", "limit"} },
    ["outline.attachments_redirect"] = { method = "POST", url = "https://app.getoutline.com/api/attachments.redirect", body = {"id"} },
    ["outline.auth_config"] = { method = "POST", url = "https://app.getoutline.com/api/auth.config" },
    ["outline.auth_delete"] = { method = "POST", url = "https://app.getoutline.com/api/auth.delete" },
    ["outline.auth_info"] = { method = "POST", url = "https://app.getoutline.com/api/auth.info" },
    ["outline.collections_add_group"] = { method = "POST", url = "https://app.getoutline.com/api/collections.add_group", body = {"id", "groupId", "permission"} },
    ["outline.collections_add_user"] = { method = "POST", url = "https://app.getoutline.com/api/collections.add_user", body = {"id", "userId", "permission"} },
    ["outline.collections_archive"] = { method = "POST", url = "https://app.getoutline.com/api/collections.archive", body = {"id", "reason"} },
    ["outline.collections_create"] = { method = "POST", url = "https://app.getoutline.com/api/collections.create", body = {"name", "description", "data", "permission", "icon", "color", "sharing"} },
    ["outline.collections_delete"] = { method = "POST", url = "https://app.getoutline.com/api/collections.delete", body = {"id", "reason"} },
    ["outline.collections_documents"] = { method = "POST", url = "https://app.getoutline.com/api/collections.documents", body = {"id"} },
    ["outline.collections_duplicate"] = { method = "POST", url = "https://app.getoutline.com/api/collections.duplicate", body = {"id", "name"} },
    ["outline.collections_export"] = { method = "POST", url = "https://app.getoutline.com/api/collections.export", body = {"format", "id"} },
    ["outline.collections_export_all"] = { method = "POST", url = "https://app.getoutline.com/api/collections.export_all", body = {"format", "includeAttachments", "includePrivate"} },
    ["outline.collections_group_memberships"] = { method = "POST", url = "https://app.getoutline.com/api/collections.group_memberships", body = {"offset", "limit"} },
    ["outline.collections_import"] = { method = "POST", url = "https://app.getoutline.com/api/collections.import", body = {"attachmentId", "format", "permission"} },
    ["outline.collections_info"] = { method = "POST", url = "https://app.getoutline.com/api/collections.info", body = {"id"} },
    ["outline.collections_list"] = { method = "POST", url = "https://app.getoutline.com/api/collections.list", body = {"offset", "limit"} },
    ["outline.collections_memberships"] = { method = "POST", url = "https://app.getoutline.com/api/collections.memberships", body = {"offset", "limit"} },
    ["outline.collections_move"] = { method = "POST", url = "https://app.getoutline.com/api/collections.move", body = {"id", "index"} },
    ["outline.collections_remove_group"] = { method = "POST", url = "https://app.getoutline.com/api/collections.remove_group", body = {"id", "groupId"} },
    ["outline.collections_remove_user"] = { method = "POST", url = "https://app.getoutline.com/api/collections.remove_user", body = {"id", "userId"} },
    ["outline.collections_restore"] = { method = "POST", url = "https://app.getoutline.com/api/collections.restore", body = {"id"} },
    ["outline.collections_update"] = { method = "POST", url = "https://app.getoutline.com/api/collections.update", body = {"id", "name", "description", "data", "permission", "icon", "color", "sharing", "deprecatedReason"} },
    ["outline.comments_add_reaction"] = { method = "POST", url = "https://app.getoutline.com/api/comments.add_reaction", body = {"id", "emoji"} },
    ["outline.comments_create"] = { method = "POST", url = "https://app.getoutline.com/api/comments.create", body = {"id", "documentId", "parentCommentId", "data", "text", "anchorText", "anchorPrefix", "anchorSuffix"} },
    ["outline.comments_delete"] = { method = "POST", url = "https://app.getoutline.com/api/comments.delete", body = {"id"} },
    ["outline.comments_info"] = { method = "POST", url = "https://app.getoutline.com/api/comments.info", body = {"id", "includeAnchorText"} },
    ["outline.comments_list"] = { method = "POST", url = "https://app.getoutline.com/api/comments.list", body = {"offset", "limit"} },
    ["outline.comments_remove_reaction"] = { method = "POST", url = "https://app.getoutline.com/api/comments.remove_reaction", body = {"id", "emoji"} },
    ["outline.comments_resolve"] = { method = "POST", url = "https://app.getoutline.com/api/comments.resolve", body = {"id"} },
    ["outline.comments_unresolve"] = { method = "POST", url = "https://app.getoutline.com/api/comments.unresolve", body = {"id"} },
    ["outline.comments_update"] = { method = "POST", url = "https://app.getoutline.com/api/comments.update", body = {"id", "data"} },
    ["outline.data_attributes_create"] = { method = "POST", url = "https://app.getoutline.com/api/dataAttributes.create", body = {"name", "description", "dataType", "options", "pinned"} },
    ["outline.data_attributes_delete"] = { method = "POST", url = "https://app.getoutline.com/api/dataAttributes.delete", body = {"id"} },
    ["outline.data_attributes_info"] = { method = "POST", url = "https://app.getoutline.com/api/dataAttributes.info", body = {"id"} },
    ["outline.data_attributes_list"] = { method = "POST", url = "https://app.getoutline.com/api/dataAttributes.list", body = {"offset", "limit"} },
    ["outline.data_attributes_update"] = { method = "POST", url = "https://app.getoutline.com/api/dataAttributes.update", body = {"id", "name", "description", "options", "pinned"} },
    ["outline.documents_add_group"] = { method = "POST", url = "https://app.getoutline.com/api/documents.add_group", body = {"id", "groupId", "permission"} },
    ["outline.documents_add_user"] = { method = "POST", url = "https://app.getoutline.com/api/documents.add_user", body = {"id", "userId", "permission"} },
    ["outline.documents_answer_question"] = { method = "POST", url = "https://app.getoutline.com/api/documents.answerQuestion", body = {"query", "userId", "collectionId", "documentId", "statusFilter", "dateFilter"} },
    ["outline.documents_archive"] = { method = "POST", url = "https://app.getoutline.com/api/documents.archive", body = {"id", "reason"} },
    ["outline.documents_archived"] = { method = "POST", url = "https://app.getoutline.com/api/documents.archived", body = {"offset", "limit"} },
    ["outline.documents_create"] = { method = "POST", url = "https://app.getoutline.com/api/documents.create", body = {"id", "title", "text", "icon", "color", "collectionId", "parentDocumentId", "templateId", "publish", "fullWidth", "preferences", "createdAt", "dataAttributes"} },
    ["outline.documents_delete"] = { method = "POST", url = "https://app.getoutline.com/api/documents.delete", body = {"id", "permanent", "reason"} },
    ["outline.documents_deleted"] = { method = "POST", url = "https://app.getoutline.com/api/documents.deleted", body = {"offset", "limit"} },
    ["outline.documents_documents"] = { method = "POST", url = "https://app.getoutline.com/api/documents.documents", body = {"id"} },
    ["outline.documents_drafts"] = { method = "POST", url = "https://app.getoutline.com/api/documents.drafts", body = {"offset", "limit"} },
    ["outline.documents_duplicate"] = { method = "POST", url = "https://app.getoutline.com/api/documents.duplicate", body = {"id", "title", "recursive", "publish", "collectionId", "parentDocumentId"} },
    ["outline.documents_empty_trash"] = { method = "POST", url = "https://app.getoutline.com/api/documents.empty_trash" },
    ["outline.documents_export"] = { method = "POST", url = "https://app.getoutline.com/api/documents.export", body = {"id", "paperSize", "signedUrls", "includeChildDocuments"} },
    ["outline.documents_group_memberships"] = { method = "POST", url = "https://app.getoutline.com/api/documents.group_memberships", body = {"offset", "limit"} },
    ["outline.documents_import"] = { method = "POST", url = "https://app.getoutline.com/api/documents.import", body = {"file", "collectionId", "parentDocumentId", "publish"} },
    ["outline.documents_info"] = { method = "POST", url = "https://app.getoutline.com/api/documents.info", body = {"id", "shareId"} },
    ["outline.documents_insights"] = { method = "POST", url = "https://app.getoutline.com/api/documents.insights", body = {"id", "startDate", "endDate"} },
    ["outline.documents_list"] = { method = "POST", url = "https://app.getoutline.com/api/documents.list", body = {"offset", "limit"} },
    ["outline.documents_memberships"] = { method = "POST", url = "https://app.getoutline.com/api/documents.memberships", body = {"id", "query", "permission"} },
    ["outline.documents_move"] = { method = "POST", url = "https://app.getoutline.com/api/documents.move", body = {"id", "collectionId", "parentDocumentId", "index"} },
    ["outline.documents_remove_group"] = { method = "POST", url = "https://app.getoutline.com/api/documents.remove_group", body = {"id", "groupId"} },
    ["outline.documents_remove_user"] = { method = "POST", url = "https://app.getoutline.com/api/documents.remove_user", body = {"id", "userId"} },
    ["outline.documents_restore"] = { method = "POST", url = "https://app.getoutline.com/api/documents.restore", body = {"id", "collectionId", "revisionId"} },
    ["outline.documents_search"] = { method = "POST", url = "https://app.getoutline.com/api/documents.search", body = {"offset", "limit"} },
    ["outline.documents_search_titles"] = { method = "POST", url = "https://app.getoutline.com/api/documents.search_titles", body = {"offset", "limit"} },
    ["outline.documents_templatize"] = { method = "POST", url = "https://app.getoutline.com/api/documents.templatize", body = {"id", "collectionId", "publish"} },
    ["outline.documents_unpublish"] = { method = "POST", url = "https://app.getoutline.com/api/documents.unpublish", body = {"id", "detach"} },
    ["outline.documents_update"] = { method = "POST", url = "https://app.getoutline.com/api/documents.update", body = {"id", "title", "text", "icon", "color", "fullWidth", "preferences", "templateId", "collectionId", "insightsEnabled", "editMode", "findText", "publish", "lastRevision", "dataAttributes", "deprecatedReason"} },
    ["outline.documents_users"] = { method = "POST", url = "https://app.getoutline.com/api/documents.users", body = {"id", "query", "userId"} },
    ["outline.documents_viewed"] = { method = "POST", url = "https://app.getoutline.com/api/documents.viewed", body = {"offset", "limit"} },
    ["outline.events_list"] = { method = "POST", url = "https://app.getoutline.com/api/events.list", body = {"offset", "limit"} },
    ["outline.file_operations_delete"] = { method = "POST", url = "https://app.getoutline.com/api/fileOperations.delete", body = {"id"} },
    ["outline.file_operations_info"] = { method = "POST", url = "https://app.getoutline.com/api/fileOperations.info", body = {"id"} },
    ["outline.file_operations_list"] = { method = "POST", url = "https://app.getoutline.com/api/fileOperations.list", body = {"offset", "limit"} },
    ["outline.file_operations_redirect"] = { method = "POST", url = "https://app.getoutline.com/api/fileOperations.redirect", body = {"id"} },
    ["outline.group_memberships_list"] = { method = "POST", url = "https://app.getoutline.com/api/groupMemberships.list", body = {"offset", "limit"} },
    ["outline.groups_add_user"] = { method = "POST", url = "https://app.getoutline.com/api/groups.add_user", body = {"id", "userId"} },
    ["outline.groups_create"] = { method = "POST", url = "https://app.getoutline.com/api/groups.create", body = {"name", "description"} },
    ["outline.groups_delete"] = { method = "POST", url = "https://app.getoutline.com/api/groups.delete", body = {"id"} },
    ["outline.groups_info"] = { method = "POST", url = "https://app.getoutline.com/api/groups.info", body = {"id"} },
    ["outline.groups_list"] = { method = "POST", url = "https://app.getoutline.com/api/groups.list", body = {"offset", "limit"} },
    ["outline.groups_memberships"] = { method = "POST", url = "https://app.getoutline.com/api/groups.memberships", body = {"offset", "limit"} },
    ["outline.groups_remove_user"] = { method = "POST", url = "https://app.getoutline.com/api/groups.remove_user", body = {"id", "userId"} },
    ["outline.groups_update"] = { method = "POST", url = "https://app.getoutline.com/api/groups.update", body = {"id", "name"} },
    ["outline.groups_update_user"] = { method = "POST", url = "https://app.getoutline.com/api/groups.update_user", body = {"id", "userId", "permission"} },
    ["outline.notifications_list"] = { method = "POST", url = "https://app.getoutline.com/api/notifications.list", body = {"offset", "limit"} },
    ["outline.notifications_update"] = { method = "POST", url = "https://app.getoutline.com/api/notifications.update", body = {"id", "viewedAt", "archivedAt"} },
    ["outline.notifications_update_all"] = { method = "POST", url = "https://app.getoutline.com/api/notifications.update_all", body = {"viewedAt", "archivedAt"} },
    ["outline.oauth_authentications_delete"] = { method = "POST", url = "https://app.getoutline.com/api/oauthAuthentications.delete", body = {"oauthClientId", "scope"} },
    ["outline.oauth_authentications_list"] = { method = "POST", url = "https://app.getoutline.com/api/oauthAuthentications.list", body = {"offset", "limit"} },
    ["outline.oauth_clients_create"] = { method = "POST", url = "https://app.getoutline.com/api/oauthClients.create", body = {"name", "description", "developerName", "developerUrl", "avatarUrl", "redirectUris", "published"} },
    ["outline.oauth_clients_delete"] = { method = "POST", url = "https://app.getoutline.com/api/oauthClients.delete", body = {"id"} },
    ["outline.oauth_clients_info"] = { method = "POST", url = "https://app.getoutline.com/api/oauthClients.info", body = {"id", "clientId"} },
    ["outline.oauth_clients_list"] = { method = "POST", url = "https://app.getoutline.com/api/oauthClients.list", body = {"offset", "limit"} },
    ["outline.oauth_clients_rotate_secret"] = { method = "POST", url = "https://app.getoutline.com/api/oauthClients.rotate_secret", body = {"id"} },
    ["outline.oauth_clients_update"] = { method = "POST", url = "https://app.getoutline.com/api/oauthClients.update", body = {"id", "name", "description", "developerName", "developerUrl", "avatarUrl", "redirectUris", "published"} },
    ["outline.pins_create"] = { method = "POST", url = "https://app.getoutline.com/api/pins.create", body = {"documentId", "collectionId", "index"} },
    ["outline.pins_delete"] = { method = "POST", url = "https://app.getoutline.com/api/pins.delete", body = {"id"} },
    ["outline.pins_info"] = { method = "POST", url = "https://app.getoutline.com/api/pins.info", body = {"documentId", "collectionId"} },
    ["outline.pins_list"] = { method = "POST", url = "https://app.getoutline.com/api/pins.list", body = {"offset", "limit"} },
    ["outline.pins_update"] = { method = "POST", url = "https://app.getoutline.com/api/pins.update", body = {"id", "index"} },
    ["outline.reactions_list"] = { method = "POST", url = "https://app.getoutline.com/api/reactions.list", body = {"offset", "limit"} },
    ["outline.revisions_delete"] = { method = "POST", url = "https://app.getoutline.com/api/revisions.delete", body = {"id"} },
    ["outline.revisions_export"] = { method = "POST", url = "https://app.getoutline.com/api/revisions.export", body = {"id"} },
    ["outline.revisions_info"] = { method = "POST", url = "https://app.getoutline.com/api/revisions.info", body = {"id"} },
    ["outline.revisions_list"] = { method = "POST", url = "https://app.getoutline.com/api/revisions.list", body = {"offset", "limit"} },
    ["outline.revisions_update"] = { method = "POST", url = "https://app.getoutline.com/api/revisions.update", body = {"id", "name"} },
    ["outline.shares_create"] = { method = "POST", url = "https://app.getoutline.com/api/shares.create", body = {"documentId", "collectionId"} },
    ["outline.shares_info"] = { method = "POST", url = "https://app.getoutline.com/api/shares.info", body = {"id", "documentId"} },
    ["outline.shares_list"] = { method = "POST", url = "https://app.getoutline.com/api/shares.list", body = {"offset", "limit"} },
    ["outline.shares_revoke"] = { method = "POST", url = "https://app.getoutline.com/api/shares.revoke", body = {"id"} },
    ["outline.shares_update"] = { method = "POST", url = "https://app.getoutline.com/api/shares.update", body = {"id", "published", "title", "iconUrl"} },
    ["outline.stars_create"] = { method = "POST", url = "https://app.getoutline.com/api/stars.create", body = {"documentId", "collectionId", "index"} },
    ["outline.stars_delete"] = { method = "POST", url = "https://app.getoutline.com/api/stars.delete", body = {"id"} },
    ["outline.stars_list"] = { method = "POST", url = "https://app.getoutline.com/api/stars.list", body = {"offset", "limit"} },
    ["outline.stars_update"] = { method = "POST", url = "https://app.getoutline.com/api/stars.update", body = {"id", "index"} },
    ["outline.subscriptions_create"] = { method = "POST", url = "https://app.getoutline.com/api/subscriptions.create", body = {"event", "documentId", "collectionId"} },
    ["outline.subscriptions_delete"] = { method = "POST", url = "https://app.getoutline.com/api/subscriptions.delete", body = {"id"} },
    ["outline.subscriptions_info"] = { method = "POST", url = "https://app.getoutline.com/api/subscriptions.info", body = {"event", "documentId", "collectionId"} },
    ["outline.subscriptions_list"] = { method = "POST", url = "https://app.getoutline.com/api/subscriptions.list", body = {"offset", "limit"} },
    ["outline.templates_create"] = { method = "POST", url = "https://app.getoutline.com/api/templates.create", body = {"id", "title", "data", "icon", "color", "collectionId", "publish"} },
    ["outline.templates_delete"] = { method = "POST", url = "https://app.getoutline.com/api/templates.delete", body = {"id"} },
    ["outline.templates_duplicate"] = { method = "POST", url = "https://app.getoutline.com/api/templates.duplicate", body = {"id", "title", "collectionId"} },
    ["outline.templates_info"] = { method = "POST", url = "https://app.getoutline.com/api/templates.info", body = {"id"} },
    ["outline.templates_list"] = { method = "POST", url = "https://app.getoutline.com/api/templates.list", body = {"offset", "limit"} },
    ["outline.templates_restore"] = { method = "POST", url = "https://app.getoutline.com/api/templates.restore", body = {"id"} },
    ["outline.templates_update"] = { method = "POST", url = "https://app.getoutline.com/api/templates.update", body = {"id", "title", "data", "icon", "color", "fullWidth", "collectionId", "publish"} },
    ["outline.user_memberships_list"] = { method = "POST", url = "https://app.getoutline.com/api/userMemberships.list", body = {"offset", "limit"} },
    ["outline.user_memberships_update"] = { method = "POST", url = "https://app.getoutline.com/api/userMemberships.update", body = {"id", "index"} },
    ["outline.users_activate"] = { method = "POST", url = "https://app.getoutline.com/api/users.activate", body = {"id"} },
    ["outline.users_delete"] = { method = "POST", url = "https://app.getoutline.com/api/users.delete", body = {"id"} },
    ["outline.users_info"] = { method = "POST", url = "https://app.getoutline.com/api/users.info", body = {"id"} },
    ["outline.users_invite"] = { method = "POST", url = "https://app.getoutline.com/api/users.invite", body = {"invites", "suppressEmail"} },
    ["outline.users_list"] = { method = "POST", url = "https://app.getoutline.com/api/users.list", body = {"offset", "limit"} },
    ["outline.users_notifications_subscribe"] = { method = "POST", url = "https://app.getoutline.com/api/users.notificationsSubscribe", body = {"eventType"} },
    ["outline.users_notifications_unsubscribe"] = { method = "POST", url = "https://app.getoutline.com/api/users.notificationsUnsubscribe", body = {"eventType"} },
    ["outline.users_resend_invite"] = { method = "POST", url = "https://app.getoutline.com/api/users.resendInvite", body = {"id"} },
    ["outline.users_suspend"] = { method = "POST", url = "https://app.getoutline.com/api/users.suspend", body = {"id"} },
    ["outline.users_update"] = { method = "POST", url = "https://app.getoutline.com/api/users.update", body = {"name", "language", "avatarUrl", "preferences"} },
    ["outline.users_update_email"] = { method = "POST", url = "https://app.getoutline.com/api/users.updateEmail", body = {"email", "id"} },
    ["outline.users_update_role"] = { method = "POST", url = "https://app.getoutline.com/api/users.update_role", body = {"id", "role"} },
    ["outline.views_list"] = { method = "POST", url = "https://app.getoutline.com/api/views.list", body = {"documentId", "includeSuspended"} },
    ["outline.webhook_subscriptions_create"] = { method = "POST", url = "https://app.getoutline.com/api/webhookSubscriptions.create", body = {"name", "url", "events"} },
    ["outline.webhook_subscriptions_delete"] = { method = "POST", url = "https://app.getoutline.com/api/webhookSubscriptions.delete", body = {"id"} },
    ["outline.webhook_subscriptions_list"] = { method = "POST", url = "https://app.getoutline.com/api/webhookSubscriptions.list", body = {"offset", "limit"} },
    ["outline.webhook_subscriptions_update"] = { method = "POST", url = "https://app.getoutline.com/api/webhookSubscriptions.update", body = {"id", "name", "url", "events"} },
  },
}
