-- Todoist — every call this API accepts, as data.
--
-- GENERATED from https://developer.todoist.com/openapi.json
-- Published on the vendor's own documentation site (https://developer.todoist.com).
-- 108 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "todoist",
  name = "Todoist",
  base = "https://api.todoist.com",
  docs = "https://nango.dev/docs/integrations/all/todoist",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "TODOIST_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["todoist.accept_invitation_api_v1_workspaces_invitations_invite_code_accept_put"] = { method = "PUT", url = "https://api.todoist.com/api/v1/workspaces/invitations/{invite_code}/accept", path = {"invite_code"} },
    ["todoist.active_projects_api_v1_workspaces_workspace_id_projects_active_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/workspaces/{workspace_id}/projects/active", path = {"workspace_id"}, query = {"cursor", "limit"} },
    ["todoist.add_comment_reaction_api_v1_comments_comment_id_reactions_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/comments/{comment_id}/reactions", path = {"comment_id"}, body = {"reaction"} },
    ["todoist.all_invitations_api_v1_workspaces_invitations_all_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/workspaces/invitations/all", query = {"workspace_id"} },
    ["todoist.archive_project_api_v1_projects_project_id_archive_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/projects/{project_id}/archive", path = {"project_id"} },
    ["todoist.archive_section_api_v1_sections_section_id_archive_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/sections/{section_id}/archive", path = {"section_id"} },
    ["todoist.archived_projects_api_v1_workspaces_workspace_id_projects_archived_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/workspaces/{workspace_id}/projects/archived", path = {"workspace_id"}, query = {"cursor", "limit"} },
    ["todoist.cancel_plan_with_redirect_to_stripe_api_v1_payments_cancel_plan_with_redirect_to_stripe_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/payments/cancel_plan_with_redirect_to_stripe", body = {"reason_flag", "reason_description", "reason_text", "return_url"} },
    ["todoist.close_task_api_v1_tasks_task_id_close_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/tasks/{task_id}/close", path = {"task_id"} },
    ["todoist.create_comment_api_v1_comments_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/comments", body = {"content", "project_id", "task_id", "attachment", "uids_to_notify"} },
    ["todoist.create_folder_api_v1_folders_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/folders", body = {"name", "workspace_id", "default_order", "child_order"} },
    ["todoist.create_label_api_v1_labels_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/labels", body = {"name", "order", "color", "is_favorite"} },
    ["todoist.create_location_reminder_api_v1_location_reminders_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/location_reminders", body = {"task_id", "name", "loc_lat", "loc_long", "loc_trigger", "radius"} },
    ["todoist.create_project_api_v1_projects_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/projects", body = {"name", "description", "parent_id", "color", "is_favorite", "view_style", "workspace_id"} },
    ["todoist.create_project_from_file_api_v1_templates_create_project_from_file_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/templates/create_project_from_file", body = {"name", "workspace_id", "file"} },
    ["todoist.create_reminder_api_v1_reminders_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/reminders", body = {"task_id", "reminder_type", "minute_offset", "due", "service", "is_urgent"} },
    ["todoist.create_section_api_v1_sections_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/sections", body = {"name", "project_id", "order", "description"} },
    ["todoist.create_task_api_v1_tasks_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/tasks", body = {"content", "description", "project_id", "section_id", "parent_id", "order", "labels", "priority", "assignee_id", "due_string", "due_date", "due_datetime", "due_lang", "duration", "duration_unit", "deadline_date"} },
    ["todoist.create_workspace_api_v1_workspaces_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/workspaces", body = {"name", "description", "is_link_sharing_enabled", "is_guest_allowed", "domain_name", "domain_discovery", "restrict_email_domains", "properties", "is_trial_pending"} },
    ["todoist.delete_comment_api_v1_comments_comment_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/comments/{comment_id}", path = {"comment_id"} },
    ["todoist.delete_folder_api_v1_folders_folder_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/folders/{folder_id}", path = {"folder_id"} },
    ["todoist.delete_invitation_api_v1_workspaces_invitations_delete_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/workspaces/invitations/delete", body = {"workspace_id", "user_email"} },
    ["todoist.delete_label_api_v1_labels_label_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/labels/{label_id}", path = {"label_id"} },
    ["todoist.delete_location_reminder_api_v1_location_reminders_reminder_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/location_reminders/{reminder_id}", path = {"reminder_id"} },
    ["todoist.delete_project_api_v1_projects_project_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/projects/{project_id}", path = {"project_id"} },
    ["todoist.delete_reminder_api_v1_reminders_reminder_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/reminders/{reminder_id}", path = {"reminder_id"} },
    ["todoist.delete_section_api_v1_sections_section_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/sections/{section_id}", path = {"section_id"} },
    ["todoist.delete_task_api_v1_tasks_task_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/tasks/{task_id}", path = {"task_id"} },
    ["todoist.delete_upload_api_v1_uploads_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/uploads", query = {"file_url"} },
    ["todoist.delete_workspace_api_v1_workspaces_workspace_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/workspaces/{workspace_id}", path = {"workspace_id"} },
    ["todoist.download_backup_api_v1_backups_download_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/backups/download", query = {"file"} },
    ["todoist.email_disable_api_v1_emails_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/emails", query = {"obj_type", "obj_id"} },
    ["todoist.email_get_or_create_api_v1_emails_put"] = { method = "PUT", url = "https://api.todoist.com/api/v1/emails", body = {"obj_type", "obj_id"} },
    ["todoist.export_as_file_api_v1_templates_file_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/templates/file", query = {"project_id", "use_relative_dates"} },
    ["todoist.export_as_url_api_v1_templates_url_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/templates/url", query = {"project_id", "use_relative_dates"} },
    ["todoist.get_activity_logs_api_v1_activities_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/activities", query = {"object_type", "object_id", "parent_project_id", "parent_item_id", "include_parent_object", "include_child_objects", "initiator_id", "initiator_id_null", "event_type", "ensure_last_state", "object_event_types", "workspace_id", "annotate_notes", "annotate_parents", "cursor", "limit", "date_from", "date_to"} },
    ["todoist.get_archived_api_v1_projects_archived_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/projects/archived", query = {"cursor", "limit"} },
    ["todoist.get_backups_api_v1_backups_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/backups", query = {"mfa_token"} },
    ["todoist.get_comment_api_v1_comments_comment_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/comments/{comment_id}", path = {"comment_id"} },
    ["todoist.get_comments_api_v1_comments_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/comments", query = {"project_id", "task_id", "cursor", "limit", "public_key"} },
    ["todoist.get_folder_api_v1_folders_folder_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/folders/{folder_id}", path = {"folder_id"} },
    ["todoist.get_folders_api_v1_folders_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/folders", query = {"workspace_id", "cursor", "limit"} },
    ["todoist.get_label_api_v1_labels_label_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/labels/{label_id}", path = {"label_id"} },
    ["todoist.get_labels_api_v1_labels_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/labels", query = {"cursor", "limit"} },
    ["todoist.get_location_reminder_api_v1_location_reminders_reminder_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/location_reminders/{reminder_id}", path = {"reminder_id"} },
    ["todoist.get_location_reminders_api_v1_location_reminders_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/location_reminders", query = {"task_id", "cursor", "limit"} },
    ["todoist.get_productivity_stats_api_v1_tasks_completed_stats_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/tasks/completed/stats" },
    ["todoist.get_project_api_v1_projects_project_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/projects/{project_id}", path = {"project_id"} },
    ["todoist.get_project_collaborators_api_v1_projects_project_id_collaborators_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/projects/{project_id}/collaborators", path = {"project_id"}, query = {"cursor", "limit", "public_key"} },
    ["todoist.get_projects_api_v1_projects_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/projects", query = {"folder_id", "workspace_id", "cursor", "limit"} },
    ["todoist.get_reminder_api_v1_reminders_reminder_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/reminders/{reminder_id}", path = {"reminder_id"} },
    ["todoist.get_reminders_api_v1_reminders_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/reminders", query = {"task_id", "cursor", "limit"} },
    ["todoist.get_section_api_v1_sections_section_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/sections/{section_id}", path = {"section_id"}, query = {"public_key"} },
    ["todoist.get_sections_api_v1_sections_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/sections", query = {"project_id", "workspace_id", "cursor", "limit", "public_key"} },
    ["todoist.get_subscription_info_api_v1_payments_get_subscription_info_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/payments/get_subscription_info" },
    ["todoist.get_task_api_v1_tasks_task_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/tasks/{task_id}", path = {"task_id"}, query = {"public_key"} },
    ["todoist.get_tasks_api_v1_tasks_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/tasks", query = {"project_id", "section_id", "parent_id", "label", "ids", "cursor", "limit"} },
    ["todoist.get_tasks_by_filter_api_v1_tasks_filter_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/tasks/filter", query = {"query", "lang", "cursor", "limit"} },
    ["todoist.get_workspace_api_v1_workspaces_workspace_id_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/workspaces/{workspace_id}", path = {"workspace_id"} },
    ["todoist.get_workspaces_api_v1_workspaces_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/workspaces" },
    ["todoist.get_workspaces_users_api_v1_workspaces_users_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/workspaces/users", query = {"workspace_id", "cursor", "limit", "sort"} },
    ["todoist.id_mappings_api_v1_id_mappings_obj_name_obj_ids_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/id_mappings/{obj_name}/{obj_ids}", path = {"obj_name", "obj_ids"} },
    ["todoist.import_into_project_from_file_api_v1_templates_import_into_project_from_file_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/templates/import_into_project_from_file", body = {"project_id", "file"} },
    ["todoist.import_into_project_from_template_id_api_v1_templates_import_into_project_from_template_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/templates/import_into_project_from_template_id", body = {"project_id", "template_id", "locale"} },
    ["todoist.invitations_api_v1_workspaces_invitations_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/workspaces/invitations", query = {"workspace_id"} },
    ["todoist.invite_workspace_users_api_v1_workspaces_workspace_id_users_invite_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/workspaces/{workspace_id}/users/invite", path = {"workspace_id"}, body = {"email_list", "role"} },
    ["todoist.join_api_v1_projects_project_id_join_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/projects/{project_id}/join", path = {"project_id"} },
    ["todoist.join_api_v1_workspaces_join_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/workspaces/join", body = {"invite_code", "workspace_id"} },
    ["todoist.migrate_personal_token_api_v1_access_tokens_migrate_personal_token_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/access_tokens/migrate_personal_token", body = {"client_id", "client_secret", "personal_token", "scope"} },
    ["todoist.move_task_api_v1_tasks_task_id_move_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/tasks/{task_id}/move", path = {"task_id"}, body = {"project_id", "section_id", "parent_id"} },
    ["todoist.permissions_api_v1_projects_permissions_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/projects/permissions" },
    ["todoist.plan_details_api_v1_workspaces_plan_details_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/workspaces/plan_details", query = {"workspace_id"} },
    ["todoist.quick_add_api_v1_tasks_quick_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/tasks/quick", body = {"text", "note", "reminder", "auto_reminder", "meta"} },
    ["todoist.reactivate_plan_api_v1_payments_reactivate_plan_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/payments/reactivate_plan" },
    ["todoist.reject_invitation_api_v1_workspaces_invitations_invite_code_reject_put"] = { method = "PUT", url = "https://api.todoist.com/api/v1/workspaces/invitations/{invite_code}/reject", path = {"invite_code"} },
    ["todoist.remove_comment_reaction_api_v1_comments_comment_id_reactions_remove_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/comments/{comment_id}/reactions/remove", path = {"comment_id"}, body = {"reaction"} },
    ["todoist.remove_workspace_user_api_v1_workspaces_workspace_id_users_user_id_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/workspaces/{workspace_id}/users/{user_id}", path = {"workspace_id", "user_id"} },
    ["todoist.reopen_task_api_v1_tasks_task_id_reopen_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/tasks/{task_id}/reopen", path = {"task_id"} },
    ["todoist.revoke_access_token_api_api_v1_access_tokens_delete"] = { method = "DELETE", url = "https://api.todoist.com/api/v1/access_tokens", query = {"client_id", "client_secret"} },
    ["todoist.revoke_token_rfc7009_compliant_api_v1_revoke_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/revoke", body = {"token_type_hint"} },
    ["todoist.search_labels_api_v1_labels_search_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/labels/search", query = {"query", "cursor", "limit"} },
    ["todoist.search_projects_api_v1_projects_search_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/projects/search", query = {"query", "cursor", "limit"} },
    ["todoist.search_sections_api_v1_sections_search_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/sections/search", query = {"query", "project_id", "workspace_id", "cursor", "limit"} },
    ["todoist.shared_labels_api_v1_labels_shared_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/labels/shared", query = {"omit_personal", "cursor", "limit"} },
    ["todoist.shared_labels_remove_api_v1_labels_shared_remove_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/labels/shared/remove", body = {"name"} },
    ["todoist.shared_labels_rename_api_v1_labels_shared_rename_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/labels/shared/rename", body = {"name", "new_name"} },
    ["todoist.tasks_completed_by_completion_date_api_v1_tasks_completed_by_completion_date_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/tasks/completed/by_completion_date", query = {"since", "until", "workspace_id", "project_id", "section_id", "parent_id", "filter_query", "filter_lang", "cursor", "limit", "public_key"} },
    ["todoist.tasks_completed_by_due_date_api_v1_tasks_completed_by_due_date_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/tasks/completed/by_due_date", query = {"since", "until", "workspace_id", "project_id", "section_id", "parent_id", "filter_query", "filter_lang", "cursor", "limit"} },
    ["todoist.unarchive_project_api_v1_projects_project_id_unarchive_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/projects/{project_id}/unarchive", path = {"project_id"} },
    ["todoist.unarchive_section_api_v1_sections_section_id_unarchive_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/sections/{section_id}/unarchive", path = {"section_id"} },
    ["todoist.update_comment_api_v1_comments_comment_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/comments/{comment_id}", path = {"comment_id"}, body = {"content"} },
    ["todoist.update_folder_api_v1_folders_folder_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/folders/{folder_id}", path = {"folder_id"}, body = {"name", "default_order"} },
    ["todoist.update_label_api_v1_labels_label_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/labels/{label_id}", path = {"label_id"}, body = {"name", "order", "color", "is_favorite"} },
    ["todoist.update_location_reminder_api_v1_location_reminders_reminder_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/location_reminders/{reminder_id}", path = {"reminder_id"}, body = {"name", "loc_lat", "loc_long", "loc_trigger", "radius"} },
    ["todoist.update_logo_api_v1_workspaces_logo_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/workspaces/logo", body = {"workspace_id", "delete", "file"} },
    ["todoist.update_notification_setting_api_v1_notification_setting_put"] = { method = "PUT", url = "https://api.todoist.com/api/v1/notification_setting", body = {"notification_type", "service", "dont_notify"} },
    ["todoist.update_project_api_v1_projects_project_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/projects/{project_id}", path = {"project_id"}, body = {"name", "description", "color", "is_favorite", "view_style", "child_order", "is_collapsed", "folder_id"} },
    ["todoist.update_reminder_api_v1_reminders_reminder_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/reminders/{reminder_id}", path = {"reminder_id"}, body = {"minute_offset", "due", "service", "is_urgent"} },
    ["todoist.update_section_api_v1_sections_section_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/sections/{section_id}", path = {"section_id"}, body = {"name", "section_order", "is_collapsed", "description"} },
    ["todoist.update_task_api_v1_tasks_task_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/tasks/{task_id}", path = {"task_id"}, body = {"content", "description", "labels", "priority", "due_string", "due_date", "due_datetime", "due_lang", "assignee_id", "duration", "duration_unit", "deadline_date", "child_order", "is_collapsed", "day_order"} },
    ["todoist.update_workspace_api_v1_workspaces_workspace_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/workspaces/{workspace_id}", path = {"workspace_id"}, body = {"name", "description", "is_link_sharing_enabled", "is_guest_allowed", "domain_name", "domain_discovery", "restrict_email_domains", "properties", "is_trial_pending", "invite_code", "is_collapsed"} },
    ["todoist.update_workspace_user_api_v1_workspaces_workspace_id_users_user_id_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/workspaces/{workspace_id}/users/{user_id}", path = {"workspace_id", "user_id"}, body = {"role"} },
    ["todoist.upload_file_api_v1_uploads_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/uploads", body = {"file_name", "project_id", "file"} },
    ["todoist.usage_billing_history_api_v1_usage_billing_history_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/usage_billing/history", query = {"product", "types", "cursor", "limit"} },
    ["todoist.usage_billing_state_api_v1_usage_billing_state_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/usage_billing/state", query = {"product"} },
    ["todoist.usage_billing_top_up_api_v1_usage_billing_top_up_post"] = { method = "POST", url = "https://api.todoist.com/api/v1/usage_billing/top_up", body = {"amount", "currency", "return_url"} },
    ["todoist.usage_billing_usage_summary_api_v1_usage_billing_usage_summary_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/usage_billing/usage_summary", query = {"product", "category", "since", "until"} },
    ["todoist.user_info_api_v1_user_get"] = { method = "GET", url = "https://api.todoist.com/api/v1/user" },
  },
}
