-- Asana — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/asana.com/1.0/openapi.json
-- APIs.guru's mirror of asana.com, matched on asana.com. A mirror lags the vendor.
-- 167 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "asana-scim",
  name = "Asana",
  base = "https://app.asana.com/api",
  docs = "https://nango.dev/docs/integrations/all/asana-scim",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "ASANA_SCIM_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["asana-scim.add_custom_field_setting_for_portfolio"] = { method = "POST", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/addCustomFieldSetting", path = {"portfolio_gid"}, query = {"opt_pretty"}, body = {"data"} },
    ["asana-scim.add_custom_field_setting_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/addCustomFieldSetting", path = {"project_gid"}, query = {"opt_pretty"}, body = {"data"} },
    ["asana-scim.add_dependencies_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/addDependencies", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_dependents_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/addDependents", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_followers"] = { method = "POST", url = "https://app.asana.com/api/1.0/goals/{goal_gid}/addFollowers", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_followers_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/addFollowers", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_followers_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/addFollowers", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_item_for_portfolio"] = { method = "POST", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/addItem", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_members_for_portfolio"] = { method = "POST", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/addMembers", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_members_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/addMembers", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_project_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/addProject", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_supporting_relationship"] = { method = "POST", url = "https://app.asana.com/api/1.0/goals/{goal_gid}/addSupportingRelationship", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_tag_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/addTag", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_task_for_section"] = { method = "POST", url = "https://app.asana.com/api/1.0/sections/{section_gid}/addTask", path = {"section_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_user_for_team"] = { method = "POST", url = "https://app.asana.com/api/1.0/teams/{team_gid}/addUser", path = {"team_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.add_user_for_workspace"] = { method = "POST", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/addUser", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_attachment_for_object"] = { method = "POST", url = "https://app.asana.com/api/1.0/attachments", query = {"opt_pretty", "opt_fields"}, body = {"connect_to_app", "file", "name", "parent", "resource_subtype", "url"} },
    ["asana-scim.create_batch_request"] = { method = "POST", url = "https://app.asana.com/api/1.0/batch", query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_custom_field"] = { method = "POST", url = "https://app.asana.com/api/1.0/custom_fields", query = {"opt_pretty", "opt_fields", "limit", "offset"}, body = {"data"} },
    ["asana-scim.create_enum_option_for_custom_field"] = { method = "POST", url = "https://app.asana.com/api/1.0/custom_fields/{custom_field_gid}/enum_options", path = {"custom_field_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"}, body = {"data"} },
    ["asana-scim.create_goal"] = { method = "POST", url = "https://app.asana.com/api/1.0/goals", query = {"opt_pretty", "opt_fields", "limit", "offset"}, body = {"data"} },
    ["asana-scim.create_goal_metric"] = { method = "POST", url = "https://app.asana.com/api/1.0/goals/{goal_gid}/setMetric", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_organization_export"] = { method = "POST", url = "https://app.asana.com/api/1.0/organization_exports", query = {"opt_pretty", "opt_fields", "limit", "offset"}, body = {"data"} },
    ["asana-scim.create_portfolio"] = { method = "POST", url = "https://app.asana.com/api/1.0/portfolios", query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects", query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_project_brief"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/project_briefs", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_project_for_team"] = { method = "POST", url = "https://app.asana.com/api/1.0/teams/{team_gid}/projects", path = {"team_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_project_for_workspace"] = { method = "POST", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/projects", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_project_status_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/project_statuses", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_section_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/sections", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_status_for_object"] = { method = "POST", url = "https://app.asana.com/api/1.0/status_updates", query = {"opt_pretty", "opt_fields", "limit", "offset"}, body = {"data"} },
    ["asana-scim.create_story_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/stories", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_subtask_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/subtasks", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_tag"] = { method = "POST", url = "https://app.asana.com/api/1.0/tags", query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_tag_for_workspace"] = { method = "POST", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/tags", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks", query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.create_team"] = { method = "POST", url = "https://app.asana.com/api/1.0/teams", query = {"opt_pretty", "opt_fields", "limit", "offset"}, body = {"data"} },
    ["asana-scim.create_webhook"] = { method = "POST", url = "https://app.asana.com/api/1.0/webhooks", query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.delete_attachment"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/attachments/{attachment_gid}", path = {"attachment_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_custom_field"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/custom_fields/{custom_field_gid}", path = {"custom_field_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_goal"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/goals/{goal_gid}", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_portfolio"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_project"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/projects/{project_gid}", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_project_brief"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/project_briefs/{project_brief_gid}", path = {"project_brief_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_project_status"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/project_statuses/{project_status_gid}", path = {"project_status_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_section"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/sections/{section_gid}", path = {"section_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_status"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/status_updates/{status_gid}", path = {"status_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_story"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/stories/{story_gid}", path = {"story_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_tag"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/tags/{tag_gid}", path = {"tag_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.delete_task"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/tasks/{task_gid}", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.delete_webhook"] = { method = "DELETE", url = "https://app.asana.com/api/1.0/webhooks/{webhook_gid}", path = {"webhook_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.duplicate_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/duplicate", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.duplicate_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/duplicate", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.get_attachment"] = { method = "GET", url = "https://app.asana.com/api/1.0/attachments/{attachment_gid}", path = {"attachment_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_attachments_for_object"] = { method = "GET", url = "https://app.asana.com/api/1.0/attachments", query = {"opt_pretty", "opt_fields", "limit", "offset", "parent"} },
    ["asana-scim.get_audit_log_events"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/audit_log_events", path = {"workspace_gid"}, query = {"start_at", "end_at", "event_type", "actor_type", "actor_gid", "resource_gid", "limit", "offset"} },
    ["asana-scim.get_custom_field"] = { method = "GET", url = "https://app.asana.com/api/1.0/custom_fields/{custom_field_gid}", path = {"custom_field_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_custom_field_settings_for_portfolio"] = { method = "GET", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/custom_field_settings", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_custom_field_settings_for_project"] = { method = "GET", url = "https://app.asana.com/api/1.0/projects/{project_gid}/custom_field_settings", path = {"project_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_custom_fields_for_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/custom_fields", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_dependencies_for_task"] = { method = "GET", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/dependencies", path = {"task_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_dependents_for_task"] = { method = "GET", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/dependents", path = {"task_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_events"] = { method = "GET", url = "https://app.asana.com/api/1.0/events", query = {"resource", "sync", "opt_pretty", "opt_fields"} },
    ["asana-scim.get_favorites_for_user"] = { method = "GET", url = "https://app.asana.com/api/1.0/users/{user_gid}/favorites", path = {"user_gid"}, query = {"opt_pretty", "opt_fields", "resource_type", "workspace"} },
    ["asana-scim.get_goal"] = { method = "GET", url = "https://app.asana.com/api/1.0/goals/{goal_gid}", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_goal_relationship"] = { method = "GET", url = "https://app.asana.com/api/1.0/goal_relationships/{goal_relationship_gid}", path = {"goal_relationship_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_goal_relationships"] = { method = "GET", url = "https://app.asana.com/api/1.0/goal_relationships", query = {"opt_pretty", "opt_fields", "supported_goal", "resource_subtype"} },
    ["asana-scim.get_goals"] = { method = "GET", url = "https://app.asana.com/api/1.0/goals", query = {"opt_pretty", "opt_fields", "limit", "offset", "portfolio", "project", "is_workspace_level", "team", "workspace", "time_periods"} },
    ["asana-scim.get_items_for_portfolio"] = { method = "GET", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/items", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_job"] = { method = "GET", url = "https://app.asana.com/api/1.0/jobs/{job_gid}", path = {"job_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_organization_export"] = { method = "GET", url = "https://app.asana.com/api/1.0/organization_exports/{organization_export_gid}", path = {"organization_export_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_parent_goals_for_goal"] = { method = "GET", url = "https://app.asana.com/api/1.0/goals/{goal_gid}/parentGoals", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_portfolio"] = { method = "GET", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_portfolio_membership"] = { method = "GET", url = "https://app.asana.com/api/1.0/portfolio_memberships/{portfolio_membership_gid}", path = {"portfolio_membership_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_portfolio_memberships"] = { method = "GET", url = "https://app.asana.com/api/1.0/portfolio_memberships", query = {"portfolio", "workspace", "user", "opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_portfolio_memberships_for_portfolio"] = { method = "GET", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/portfolio_memberships", path = {"portfolio_gid"}, query = {"user", "opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_portfolios"] = { method = "GET", url = "https://app.asana.com/api/1.0/portfolios", query = {"opt_pretty", "opt_fields", "limit", "offset", "workspace", "owner"} },
    ["asana-scim.get_project"] = { method = "GET", url = "https://app.asana.com/api/1.0/projects/{project_gid}", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_project_brief"] = { method = "GET", url = "https://app.asana.com/api/1.0/project_briefs/{project_brief_gid}", path = {"project_brief_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_project_membership"] = { method = "GET", url = "https://app.asana.com/api/1.0/project_memberships/{project_membership_gid}", path = {"project_membership_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_project_memberships_for_project"] = { method = "GET", url = "https://app.asana.com/api/1.0/projects/{project_gid}/project_memberships", path = {"project_gid"}, query = {"user", "opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_project_status"] = { method = "GET", url = "https://app.asana.com/api/1.0/project_statuses/{project_status_gid}", path = {"project_status_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_project_statuses_for_project"] = { method = "GET", url = "https://app.asana.com/api/1.0/projects/{project_gid}/project_statuses", path = {"project_gid", "project_gid"}, query = {"opt_pretty", "opt_fields", "opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_project_template"] = { method = "GET", url = "https://app.asana.com/api/1.0/project_templates/{project_template_gid}", path = {"project_template_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_project_templates"] = { method = "GET", url = "https://app.asana.com/api/1.0/project_templates", query = {"opt_pretty", "opt_fields", "workspace", "team", "limit", "offset"} },
    ["asana-scim.get_project_templates_for_team"] = { method = "GET", url = "https://app.asana.com/api/1.0/teams/{team_gid}/project_templates", path = {"team_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_projects"] = { method = "GET", url = "https://app.asana.com/api/1.0/projects", query = {"opt_pretty", "opt_fields", "limit", "offset", "workspace", "team", "archived"} },
    ["asana-scim.get_projects_for_task"] = { method = "GET", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/projects", path = {"task_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_projects_for_team"] = { method = "GET", url = "https://app.asana.com/api/1.0/teams/{team_gid}/projects", path = {"team_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset", "archived"} },
    ["asana-scim.get_projects_for_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/projects", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset", "archived"} },
    ["asana-scim.get_section"] = { method = "GET", url = "https://app.asana.com/api/1.0/sections/{section_gid}", path = {"section_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_sections_for_project"] = { method = "GET", url = "https://app.asana.com/api/1.0/projects/{project_gid}/sections", path = {"project_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_status"] = { method = "GET", url = "https://app.asana.com/api/1.0/status_updates/{status_gid}", path = {"status_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_statuses_for_object"] = { method = "GET", url = "https://app.asana.com/api/1.0/status_updates", query = {"opt_pretty", "opt_fields", "limit", "offset", "parent", "created_since"} },
    ["asana-scim.get_stories_for_task"] = { method = "GET", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/stories", path = {"task_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_story"] = { method = "GET", url = "https://app.asana.com/api/1.0/stories/{story_gid}", path = {"story_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_subtasks_for_task"] = { method = "GET", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/subtasks", path = {"task_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_tag"] = { method = "GET", url = "https://app.asana.com/api/1.0/tags/{tag_gid}", path = {"tag_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_tags"] = { method = "GET", url = "https://app.asana.com/api/1.0/tags", query = {"opt_pretty", "opt_fields", "limit", "offset", "workspace"} },
    ["asana-scim.get_tags_for_task"] = { method = "GET", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/tags", path = {"task_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_tags_for_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/tags", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_task"] = { method = "GET", url = "https://app.asana.com/api/1.0/tasks/{task_gid}", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_task_counts_for_project"] = { method = "GET", url = "https://app.asana.com/api/1.0/projects/{project_gid}/task_counts", path = {"project_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_tasks"] = { method = "GET", url = "https://app.asana.com/api/1.0/tasks", query = {"opt_pretty", "opt_fields", "limit", "offset", "assignee", "project", "section", "workspace", "completed_since", "modified_since"} },
    ["asana-scim.get_tasks_for_project"] = { method = "GET", url = "https://app.asana.com/api/1.0/projects/{project_gid}/tasks", path = {"project_gid"}, query = {"completed_since", "opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_tasks_for_section"] = { method = "GET", url = "https://app.asana.com/api/1.0/sections/{section_gid}/tasks", path = {"section_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_tasks_for_tag"] = { method = "GET", url = "https://app.asana.com/api/1.0/tags/{tag_gid}/tasks", path = {"tag_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_tasks_for_user_task_list"] = { method = "GET", url = "https://app.asana.com/api/1.0/user_task_lists/{user_task_list_gid}/tasks", path = {"user_task_list_gid"}, query = {"completed_since", "opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_team"] = { method = "GET", url = "https://app.asana.com/api/1.0/teams/{team_gid}", path = {"team_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_team_membership"] = { method = "GET", url = "https://app.asana.com/api/1.0/team_memberships/{team_membership_gid}", path = {"team_membership_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_team_memberships"] = { method = "GET", url = "https://app.asana.com/api/1.0/team_memberships", query = {"opt_pretty", "opt_fields", "limit", "offset", "team", "user", "workspace"} },
    ["asana-scim.get_team_memberships_for_team"] = { method = "GET", url = "https://app.asana.com/api/1.0/teams/{team_gid}/team_memberships", path = {"team_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_team_memberships_for_user"] = { method = "GET", url = "https://app.asana.com/api/1.0/users/{user_gid}/team_memberships", path = {"user_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset", "workspace"} },
    ["asana-scim.get_teams_for_user"] = { method = "GET", url = "https://app.asana.com/api/1.0/users/{user_gid}/teams", path = {"user_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset", "organization"} },
    ["asana-scim.get_teams_for_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/teams", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_time_period"] = { method = "GET", url = "https://app.asana.com/api/1.0/time_periods/{time_period_gid}", path = {"time_period_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_time_periods"] = { method = "GET", url = "https://app.asana.com/api/1.0/time_periods", query = {"opt_pretty", "opt_fields", "limit", "offset", "start_on", "end_on", "workspace"} },
    ["asana-scim.get_user"] = { method = "GET", url = "https://app.asana.com/api/1.0/users/{user_gid}", path = {"user_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_user_task_list"] = { method = "GET", url = "https://app.asana.com/api/1.0/user_task_lists/{user_task_list_gid}", path = {"user_task_list_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_user_task_list_for_user"] = { method = "GET", url = "https://app.asana.com/api/1.0/users/{user_gid}/user_task_list", path = {"user_gid"}, query = {"opt_pretty", "opt_fields", "workspace"} },
    ["asana-scim.get_users"] = { method = "GET", url = "https://app.asana.com/api/1.0/users", query = {"workspace", "team", "opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_users_for_team"] = { method = "GET", url = "https://app.asana.com/api/1.0/teams/{team_gid}/users", path = {"team_gid"}, query = {"opt_pretty", "opt_fields", "offset"} },
    ["asana-scim.get_users_for_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/users", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields", "offset"} },
    ["asana-scim.get_webhook"] = { method = "GET", url = "https://app.asana.com/api/1.0/webhooks/{webhook_gid}", path = {"webhook_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_webhooks"] = { method = "GET", url = "https://app.asana.com/api/1.0/webhooks", query = {"opt_pretty", "opt_fields", "limit", "offset", "workspace", "resource"} },
    ["asana-scim.get_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_workspace_membership"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspace_memberships/{workspace_membership_gid}", path = {"workspace_membership_gid"}, query = {"opt_pretty", "opt_fields"} },
    ["asana-scim.get_workspace_memberships_for_user"] = { method = "GET", url = "https://app.asana.com/api/1.0/users/{user_gid}/workspace_memberships", path = {"user_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_workspace_memberships_for_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/workspace_memberships", path = {"workspace_gid"}, query = {"user", "opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.get_workspaces"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces", query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.insert_enum_option_for_custom_field"] = { method = "POST", url = "https://app.asana.com/api/1.0/custom_fields/{custom_field_gid}/enum_options/insert", path = {"custom_field_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.insert_section_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/sections/insert", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.instantiate_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/project_templates/{project_template_gid}/instantiateProject", path = {"project_template_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.project_save_as_template"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/saveAsTemplate", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_custom_field_setting_for_portfolio"] = { method = "POST", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/removeCustomFieldSetting", path = {"portfolio_gid"}, query = {"opt_pretty"}, body = {"data"} },
    ["asana-scim.remove_custom_field_setting_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/removeCustomFieldSetting", path = {"project_gid"}, query = {"opt_pretty"}, body = {"data"} },
    ["asana-scim.remove_dependencies_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/removeDependencies", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_dependents_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/removeDependents", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_follower_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/removeFollowers", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_followers"] = { method = "POST", url = "https://app.asana.com/api/1.0/goals/{goal_gid}/removeFollowers", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_followers_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/removeFollowers", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_item_for_portfolio"] = { method = "POST", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/removeItem", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_members_for_portfolio"] = { method = "POST", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}/removeMembers", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_members_for_project"] = { method = "POST", url = "https://app.asana.com/api/1.0/projects/{project_gid}/removeMembers", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_project_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/removeProject", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_supporting_relationship"] = { method = "POST", url = "https://app.asana.com/api/1.0/goals/{goal_gid}/removeSupportingRelationship", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_tag_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/removeTag", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_user_for_team"] = { method = "POST", url = "https://app.asana.com/api/1.0/teams/{team_gid}/removeUser", path = {"team_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.remove_user_for_workspace"] = { method = "POST", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/removeUser", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.search_tasks_for_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/tasks/search", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields", "text", "resource_subtype", "assignee.any", "assignee.not", "portfolios.any", "projects.any", "projects.not", "projects.all", "sections.any", "sections.not", "sections.all", "tags.any", "tags.not", "tags.all", "teams.any", "followers.not", "created_by.any", "created_by.not", "assigned_by.any", "assigned_by.not", "liked_by.not", "commented_on_by.not", "due_on.before", "due_on.after", "due_on", "due_at.before", "due_at.after", "start_on.before", "start_on.after", "start_on", "created_on.before", "created_on.after", "created_on", "created_at.before", "created_at.after", "completed_on.before", "completed_on.after", "completed_on", "completed_at.before", "completed_at.after", "modified_on.before", "modified_on.after", "modified_on", "modified_at.before", "modified_at.after", "is_blocking", "is_blocked", "has_attachment", "completed", "is_subtask", "sort_by", "sort_ascending"} },
    ["asana-scim.set_parent_for_task"] = { method = "POST", url = "https://app.asana.com/api/1.0/tasks/{task_gid}/setParent", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.typeahead_for_workspace"] = { method = "GET", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}/typeahead", path = {"workspace_gid"}, query = {"resource_type", "type", "query", "count", "opt_pretty", "opt_fields"} },
    ["asana-scim.update_custom_field"] = { method = "PUT", url = "https://app.asana.com/api/1.0/custom_fields/{custom_field_gid}", path = {"custom_field_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_enum_option"] = { method = "PUT", url = "https://app.asana.com/api/1.0/enum_options/{enum_option_gid}", path = {"enum_option_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_goal"] = { method = "PUT", url = "https://app.asana.com/api/1.0/goals/{goal_gid}", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_goal_metric"] = { method = "POST", url = "https://app.asana.com/api/1.0/goals/{goal_gid}/setMetricCurrentValue", path = {"goal_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_goal_relationship"] = { method = "PUT", url = "https://app.asana.com/api/1.0/goal_relationships/{goal_relationship_gid}", path = {"goal_relationship_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_portfolio"] = { method = "PUT", url = "https://app.asana.com/api/1.0/portfolios/{portfolio_gid}", path = {"portfolio_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_project"] = { method = "PUT", url = "https://app.asana.com/api/1.0/projects/{project_gid}", path = {"project_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_project_brief"] = { method = "PUT", url = "https://app.asana.com/api/1.0/project_briefs/{project_brief_gid}", path = {"project_brief_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_section"] = { method = "PUT", url = "https://app.asana.com/api/1.0/sections/{section_gid}", path = {"section_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_story"] = { method = "PUT", url = "https://app.asana.com/api/1.0/stories/{story_gid}", path = {"story_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_tag"] = { method = "PUT", url = "https://app.asana.com/api/1.0/tags/{tag_gid}", path = {"tag_gid"}, query = {"opt_pretty", "opt_fields", "limit", "offset"} },
    ["asana-scim.update_task"] = { method = "PUT", url = "https://app.asana.com/api/1.0/tasks/{task_gid}", path = {"task_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_team"] = { method = "PUT", url = "https://app.asana.com/api/1.0/teams", query = {"opt_pretty", "opt_fields", "limit", "offset"}, body = {"data"} },
    ["asana-scim.update_webhook"] = { method = "PUT", url = "https://app.asana.com/api/1.0/webhooks/{webhook_gid}", path = {"webhook_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
    ["asana-scim.update_workspace"] = { method = "PUT", url = "https://app.asana.com/api/1.0/workspaces/{workspace_gid}", path = {"workspace_gid"}, query = {"opt_pretty", "opt_fields"}, body = {"data"} },
  },
}
