-- Okta — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/okta/okta-management-openapi-spec/master/dist/legacy-v1-swagger/spec.json
-- Published by okta, the vendor's own GitHub organisation.
-- 341 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "okta",
  name = "Okta",
  base = "https://{subdomain}.okta.com",
  docs = "https://nango.dev/docs/integrations/all/okta",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "OKTA_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = { ["subdomain"] = "OKTA_SUBDOMAIN" },
  headers = {},
  operations = {
    ["okta.activate_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/lifecycle/activate", path = {"appId"} },
    ["okta.activate_authenticator"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authenticators/{authenticatorId}/lifecycle/activate", path = {"authenticatorId"} },
    ["okta.activate_authorization_server"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/lifecycle/activate", path = {"authServerId"} },
    ["okta.activate_authorization_server_policy"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/lifecycle/activate", path = {"authServerId", "policyId"} },
    ["okta.activate_authorization_server_policy_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/rules/{ruleId}/lifecycle/activate", path = {"authServerId", "policyId", "ruleId"} },
    ["okta.activate_client_secret_for_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/secrets/{secretId}/lifecycle/activate", path = {"appId", "secretId"} },
    ["okta.activate_default_provisioning_connection_for_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/connections/default/lifecycle/activate", path = {"appId"} },
    ["okta.activate_event_hook"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/eventHooks/{eventHookId}/lifecycle/activate", path = {"eventHookId"} },
    ["okta.activate_factor"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors/{factorId}/lifecycle/activate", path = {"userId", "factorId"}, body = {"attestation", "clientData", "passCode", "registrationData", "stateToken", "body"} },
    ["okta.activate_group_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/groups/rules/{ruleId}/lifecycle/activate", path = {"ruleId"} },
    ["okta.activate_identity_provider"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/lifecycle/activate", path = {"idpId"} },
    ["okta.activate_inline_hook"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/inlineHooks/{inlineHookId}/lifecycle/activate", path = {"inlineHookId"} },
    ["okta.activate_network_zone"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/zones/{zoneId}/lifecycle/activate", path = {"zoneId"} },
    ["okta.activate_origin"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/trustedOrigins/{trustedOriginId}/lifecycle/activate", path = {"trustedOriginId"} },
    ["okta.activate_policy"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/lifecycle/activate", path = {"policyId"} },
    ["okta.activate_policy_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/rules/{ruleId}/lifecycle/activate", path = {"policyId", "ruleId"} },
    ["okta.activate_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/activate", path = {"userId"}, query = {"sendEmail"} },
    ["okta.add_all_apps_as_target_to_role"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/catalog/apps", path = {"userId", "roleId"} },
    ["okta.add_application_instance_target_to_app_admin_role_given_to_group"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}/targets/catalog/apps/{appName}/{applicationId}", path = {"groupId", "roleId", "appName", "applicationId"} },
    ["okta.add_application_target_to_admin_role_for_user"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/catalog/apps/{appName}", path = {"userId", "roleId", "appName"} },
    ["okta.add_application_target_to_admin_role_given_to_group"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}/targets/catalog/apps/{appName}", path = {"groupId", "roleId", "appName"} },
    ["okta.add_application_target_to_app_admin_role_for_user"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/catalog/apps/{appName}/{applicationId}", path = {"userId", "roleId", "appName", "applicationId"} },
    ["okta.add_group_target_to_group_administrator_role_for_group"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}/targets/groups/{targetGroupId}", path = {"groupId", "roleId", "targetGroupId"} },
    ["okta.add_group_target_to_role"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/groups/{groupId}", path = {"userId", "roleId", "groupId"} },
    ["okta.add_linked_object_definition"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/user/linkedObjects", body = {"_links", "associated", "primary", "linkedObject"} },
    ["okta.add_user_to_group"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/users/{userId}", path = {"groupId", "userId"} },
    ["okta.assign_role_to_group"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles", path = {"groupId"}, query = {"disableNotifications"}, body = {"type", "assignRoleRequest"} },
    ["okta.assign_role_to_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles", path = {"userId"}, query = {"disableNotifications"}, body = {"type", "assignRoleRequest"} },
    ["okta.assign_user_to_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/users", path = {"appId"}, body = {"_embedded", "_links", "created", "credentials", "externalId", "id", "lastSync", "lastUpdated", "passwordChanged", "profile", "scope", "status", "statusChanged", "syncState", "appUser"} },
    ["okta.change_password"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/credentials/change_password", path = {"userId"}, query = {"strict"}, body = {"newPassword", "oldPassword", "changePasswordRequest"} },
    ["okta.change_recovery_question"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/credentials/change_recovery_question", path = {"userId"}, body = {"password", "provider", "recovery_question", "userCredentials"} },
    ["okta.clear_user_sessions"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/sessions", path = {"userId"}, query = {"oauthTokens"} },
    ["okta.clone_application_key"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/keys/{keyId}/clone", path = {"appId", "keyId"}, query = {"targetAid"} },
    ["okta.clone_identity_provider_key"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/keys/{keyId}/clone", path = {"idpId", "keyId"}, query = {"targetIdpId"} },
    ["okta.create_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps", query = {"activate"}, header = {"OktaAccessGateway-Agent"}, body = {"_embedded", "_links", "accessibility", "created", "credentials", "features", "id", "label", "lastUpdated", "licensing", "name", "profile", "settings", "signOnMode", "status", "visibility", "application"} },
    ["okta.create_application_group_assignment"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/groups/{groupId}", path = {"appId", "groupId"}, body = {"_embedded", "_links", "id", "lastUpdated", "priority", "profile", "applicationGroupAssignment"} },
    ["okta.create_authenticator"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authenticators", query = {"activate"}, body = {"_links", "created", "id", "lastUpdated", "name", "provider", "settings", "status", "type", "authenticator"} },
    ["okta.create_authorization_server"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers", body = {"_links", "audiences", "created", "credentials", "default", "description", "id", "issuer", "issuerMode", "lastUpdated", "name", "status", "authorizationServer"} },
    ["okta.create_authorization_server_policy"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies", path = {"authServerId"}, body = {"_embedded", "_links", "conditions", "created", "description", "id", "lastUpdated", "name", "priority", "status", "system", "type", "policy"} },
    ["okta.create_authorization_server_policy_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/rules", path = {"authServerId", "policyId"}, body = {"actions", "conditions", "created", "id", "lastUpdated", "name", "priority", "status", "system", "type", "policyRule"} },
    ["okta.create_certificate"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/domains/{domainId}/certificate", path = {"domainId"}, body = {"certificate", "certificateChain", "privateKey", "type"} },
    ["okta.create_domain"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/domains", body = {"certificateSourceType", "dnsRecords", "domain", "id", "publicCertificate", "validationStatus"} },
    ["okta.create_email_template_customization"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/customizations", path = {"brandId", "templateName"}, body = {"body", "isDefault", "language", "subject", "customization"} },
    ["okta.create_event_hook"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/eventHooks", body = {"_links", "channel", "created", "createdBy", "events", "id", "lastUpdated", "name", "status", "verificationStatus", "eventHook"} },
    ["okta.create_group"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/groups", body = {"_embedded", "_links", "created", "id", "lastMembershipUpdated", "lastUpdated", "objectClass", "profile", "type", "group"} },
    ["okta.create_group_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/groups/rules", body = {"actions", "conditions", "created", "id", "lastUpdated", "name", "status", "type", "groupRule"} },
    ["okta.create_identity_provider"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps", body = {"_links", "created", "id", "issuerMode", "lastUpdated", "name", "policy", "protocol", "status", "type", "identityProvider"} },
    ["okta.create_identity_provider_key"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps/credentials/keys", body = {"_links", "alg", "created", "e", "expiresAt", "key_ops", "kid", "kty", "lastUpdated", "n", "status", "use", "x5c", "x5t", "x5t#S256", "x5u", "jsonWebKey"} },
    ["okta.create_inline_hook"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/inlineHooks", body = {"_links", "channel", "created", "id", "lastUpdated", "name", "status", "type", "version", "inlineHook"} },
    ["okta.create_network_zone"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/zones", body = {"_links", "asns", "created", "gateways", "id", "lastUpdated", "locations", "name", "proxies", "proxyType", "status", "system", "type", "usage", "zone"} },
    ["okta.create_new_client_secret_for_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/secrets", path = {"appId"}, body = {"client_secret", "metadata"} },
    ["okta.create_oauth2_claim"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/claims", path = {"authServerId"}, body = {"_links", "alwaysIncludeInToken", "claimType", "conditions", "group_filter_type", "id", "name", "status", "system", "value", "valueType", "oAuth2Claim"} },
    ["okta.create_oauth2_scope"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/scopes", path = {"authServerId"}, body = {"consent", "default", "description", "displayName", "id", "metadataPublish", "name", "system", "oAuth2Scope"} },
    ["okta.create_origin"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/trustedOrigins", body = {"_links", "created", "createdBy", "id", "lastUpdated", "lastUpdatedBy", "name", "origin", "scopes", "status", "trustedOrigin"} },
    ["okta.create_policy"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/policies", query = {"activate"}, body = {"_embedded", "_links", "conditions", "created", "description", "id", "lastUpdated", "name", "priority", "status", "system", "type", "policy"} },
    ["okta.create_policy_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/rules", path = {"policyId"}, body = {"actions", "conditions", "created", "id", "lastUpdated", "name", "priority", "status", "system", "type", "policyRule"} },
    ["okta.create_session"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/sessions", body = {"sessionToken", "createSessionRequest"} },
    ["okta.create_sms_template"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/templates/sms", body = {"created", "id", "lastUpdated", "name", "template", "translations", "type", "smsTemplate"} },
    ["okta.create_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users", query = {"activate", "provider", "nextLogin"}, body = {"credentials", "groupIds", "profile", "type", "body"} },
    ["okta.create_user_type"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/meta/types/user", body = {"_links", "created", "createdBy", "default", "description", "displayName", "id", "lastUpdated", "lastUpdatedBy", "name", "userType"} },
    ["okta.deactivate_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/lifecycle/deactivate", path = {"appId"} },
    ["okta.deactivate_authenticator"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authenticators/{authenticatorId}/lifecycle/deactivate", path = {"authenticatorId"} },
    ["okta.deactivate_authorization_server"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/lifecycle/deactivate", path = {"authServerId"} },
    ["okta.deactivate_authorization_server_policy"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/lifecycle/deactivate", path = {"authServerId", "policyId"} },
    ["okta.deactivate_authorization_server_policy_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/rules/{ruleId}/lifecycle/deactivate", path = {"authServerId", "policyId", "ruleId"} },
    ["okta.deactivate_client_secret_for_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/secrets/{secretId}/lifecycle/deactivate", path = {"appId", "secretId"} },
    ["okta.deactivate_default_provisioning_connection_for_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/connections/default/lifecycle/deactivate", path = {"appId"} },
    ["okta.deactivate_event_hook"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/eventHooks/{eventHookId}/lifecycle/deactivate", path = {"eventHookId"} },
    ["okta.deactivate_group_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/groups/rules/{ruleId}/lifecycle/deactivate", path = {"ruleId"} },
    ["okta.deactivate_identity_provider"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/lifecycle/deactivate", path = {"idpId"} },
    ["okta.deactivate_inline_hook"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/inlineHooks/{inlineHookId}/lifecycle/deactivate", path = {"inlineHookId"} },
    ["okta.deactivate_network_zone"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/zones/{zoneId}/lifecycle/deactivate", path = {"zoneId"} },
    ["okta.deactivate_or_delete_user"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}", path = {"userId"}, query = {"sendEmail"} },
    ["okta.deactivate_origin"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/trustedOrigins/{trustedOriginId}/lifecycle/deactivate", path = {"trustedOriginId"} },
    ["okta.deactivate_policy"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/lifecycle/deactivate", path = {"policyId"} },
    ["okta.deactivate_policy_rule"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/rules/{ruleId}/lifecycle/deactivate", path = {"policyId", "ruleId"} },
    ["okta.deactivate_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/deactivate", path = {"userId"}, query = {"sendEmail"} },
    ["okta.delete_application"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}", path = {"appId"} },
    ["okta.delete_application_group_assignment"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/groups/{groupId}", path = {"appId", "groupId"} },
    ["okta.delete_application_user"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/users/{userId}", path = {"appId", "userId"}, query = {"sendEmail"} },
    ["okta.delete_authorization_server"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}", path = {"authServerId"} },
    ["okta.delete_authorization_server_policy"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}", path = {"authServerId", "policyId"} },
    ["okta.delete_authorization_server_policy_rule"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/rules/{ruleId}", path = {"authServerId", "policyId", "ruleId"} },
    ["okta.delete_brand_theme_background_image"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes/{themeId}/background-image", path = {"brandId", "themeId"} },
    ["okta.delete_brand_theme_favicon"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes/{themeId}/favicon", path = {"brandId", "themeId"} },
    ["okta.delete_brand_theme_logo"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes/{themeId}/logo", path = {"brandId", "themeId"} },
    ["okta.delete_client_secret_for_application"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/secrets/{secretId}", path = {"appId", "secretId"} },
    ["okta.delete_domain"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/domains/{domainId}", path = {"domainId"} },
    ["okta.delete_email_template_customization"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/customizations/{customizationId}", path = {"brandId", "templateName", "customizationId"} },
    ["okta.delete_email_template_customizations"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/customizations", path = {"brandId", "templateName"} },
    ["okta.delete_event_hook"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/eventHooks/{eventHookId}", path = {"eventHookId"} },
    ["okta.delete_factor"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors/{factorId}", path = {"userId", "factorId"} },
    ["okta.delete_group"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}", path = {"groupId"} },
    ["okta.delete_group_rule"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/groups/rules/{ruleId}", path = {"ruleId"}, query = {"removeUsers"} },
    ["okta.delete_identity_provider"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}", path = {"idpId"} },
    ["okta.delete_identity_provider_key"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/idps/credentials/keys/{keyId}", path = {"keyId"} },
    ["okta.delete_inline_hook"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/inlineHooks/{inlineHookId}", path = {"inlineHookId"} },
    ["okta.delete_linked_object_definition"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/user/linkedObjects/{linkedObjectName}", path = {"linkedObjectName"} },
    ["okta.delete_network_zone"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/zones/{zoneId}", path = {"zoneId"} },
    ["okta.delete_oauth2_claim"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/claims/{claimId}", path = {"authServerId", "claimId"} },
    ["okta.delete_oauth2_scope"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/scopes/{scopeId}", path = {"authServerId", "scopeId"} },
    ["okta.delete_origin"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/trustedOrigins/{trustedOriginId}", path = {"trustedOriginId"} },
    ["okta.delete_policy"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}", path = {"policyId"} },
    ["okta.delete_policy_rule"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/rules/{ruleId}", path = {"policyId", "ruleId"} },
    ["okta.delete_sms_template"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/templates/sms/{templateId}", path = {"templateId"} },
    ["okta.delete_user_type"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/meta/types/user/{typeId}", path = {"typeId"} },
    ["okta.end_session"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/sessions/{sessionId}", path = {"sessionId"} },
    ["okta.enroll_factor"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors", path = {"userId"}, query = {"updatePhone", "templateId", "tokenLifetimeSeconds", "activate"}, body = {"_embedded", "_links", "created", "factorType", "id", "lastUpdated", "provider", "status", "verify", "body"} },
    ["okta.execute_inline_hook"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/inlineHooks/{inlineHookId}/execute", path = {"inlineHookId"}, body = {"payloadData"} },
    ["okta.expire_password"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/expire_password?tempPassword=false", path = {"userId"} },
    ["okta.expire_password_and_get_temporary_password"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/expire_password?tempPassword=true", path = {"userId"} },
    ["okta.extend_okta_support"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org/privacy/oktaSupport/extend" },
    ["okta.generate_application_key"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/keys/generate", path = {"appId"}, query = {"validityYears"} },
    ["okta.generate_csr_for_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/csrs", path = {"appId"}, body = {"subject", "subjectAltNames", "metadata"} },
    ["okta.generate_csr_for_identity_provider"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/csrs", path = {"idpId"}, body = {"subject", "subjectAltNames", "metadata"} },
    ["okta.generate_identity_provider_signing_key"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/keys/generate", path = {"idpId"}, query = {"validityYears"} },
    ["okta.get_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}", path = {"appId"}, query = {"expand"} },
    ["okta.get_application_group_assignment"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/groups/{groupId}", path = {"appId", "groupId"}, query = {"expand"} },
    ["okta.get_application_key"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/keys/{keyId}", path = {"appId", "keyId"} },
    ["okta.get_application_user"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/users/{userId}", path = {"appId", "userId"}, query = {"expand"} },
    ["okta.get_application_user_schema"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/apps/{appInstanceId}/default", path = {"appInstanceId"} },
    ["okta.get_authenticator"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authenticators/{authenticatorId}", path = {"authenticatorId"} },
    ["okta.get_authorization_server"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}", path = {"authServerId"} },
    ["okta.get_authorization_server_policy"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}", path = {"authServerId", "policyId"} },
    ["okta.get_authorization_server_policy_rule"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/rules/{ruleId}", path = {"authServerId", "policyId", "ruleId"} },
    ["okta.get_brand"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}", path = {"brandId"} },
    ["okta.get_brand_theme"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes/{themeId}", path = {"brandId", "themeId"} },
    ["okta.get_client_secret_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/secrets/{secretId}", path = {"appId", "secretId"} },
    ["okta.get_csr_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/csrs/{csrId}", path = {"appId", "csrId"} },
    ["okta.get_csr_for_identity_provider"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/csrs/{csrId}", path = {"idpId", "csrId"} },
    ["okta.get_current_configuration"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/threats/configuration" },
    ["okta.get_default_provisioning_connection_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/connections/default", path = {"appId"} },
    ["okta.get_domain"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/domains/{domainId}", path = {"domainId"} },
    ["okta.get_email_template"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}", path = {"brandId", "templateName"} },
    ["okta.get_email_template_customization"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/customizations/{customizationId}", path = {"brandId", "templateName", "customizationId"} },
    ["okta.get_email_template_customization_preview"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/customizations/{customizationId}/preview", path = {"brandId", "templateName", "customizationId"} },
    ["okta.get_email_template_default_content"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/default-content", path = {"brandId", "templateName"} },
    ["okta.get_email_template_default_content_preview"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/default-content/preview", path = {"brandId", "templateName"} },
    ["okta.get_event_hook"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/eventHooks/{eventHookId}", path = {"eventHookId"} },
    ["okta.get_factor"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors/{factorId}", path = {"userId", "factorId"} },
    ["okta.get_factor_transaction_status"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors/{factorId}/transactions/{transactionId}", path = {"userId", "factorId", "transactionId"} },
    ["okta.get_feature"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/features/{featureId}", path = {"featureId"} },
    ["okta.get_feature_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/features/{name}", path = {"appId", "name"} },
    ["okta.get_group"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}", path = {"groupId"} },
    ["okta.get_group_rule"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/rules/{ruleId}", path = {"ruleId"}, query = {"expand"} },
    ["okta.get_group_schema"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/group/default" },
    ["okta.get_identity_provider"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}", path = {"idpId"} },
    ["okta.get_identity_provider_application_user"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/users/{userId}", path = {"idpId", "userId"} },
    ["okta.get_identity_provider_key"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/credentials/keys/{keyId}", path = {"keyId"} },
    ["okta.get_identity_provider_signing_key"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/keys/{keyId}", path = {"idpId", "keyId"} },
    ["okta.get_inline_hook"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/inlineHooks/{inlineHookId}", path = {"inlineHookId"} },
    ["okta.get_linked_object_definition"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/user/linkedObjects/{linkedObjectName}", path = {"linkedObjectName"} },
    ["okta.get_linked_objects_for_user"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/linkedObjects/{relationshipName}", path = {"userId", "relationshipName"}, query = {"after", "limit"} },
    ["okta.get_logs"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/logs", query = {"since", "until", "filter", "q", "limit", "sortOrder", "after"} },
    ["okta.get_network_zone"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/zones/{zoneId}", path = {"zoneId"} },
    ["okta.get_oauth2_claim"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/claims/{claimId}", path = {"authServerId", "claimId"} },
    ["okta.get_oauth2_scope"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/scopes/{scopeId}", path = {"authServerId", "scopeId"} },
    ["okta.get_oauth2_token_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/tokens/{tokenId}", path = {"appId", "tokenId"}, query = {"expand"} },
    ["okta.get_okta_communication_settings"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/org/privacy/oktaCommunication" },
    ["okta.get_org_contact_types"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/org/contacts" },
    ["okta.get_org_contact_user"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/org/contacts/{contactType}", path = {"contactType"} },
    ["okta.get_org_okta_support_settings"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/org/privacy/oktaSupport" },
    ["okta.get_org_preferences"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/org/preferences" },
    ["okta.get_org_settings"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/org" },
    ["okta.get_origin"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/trustedOrigins/{trustedOriginId}", path = {"trustedOriginId"} },
    ["okta.get_policy"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}", path = {"policyId"}, query = {"expand"} },
    ["okta.get_policy_rule"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/rules/{ruleId}", path = {"policyId", "ruleId"} },
    ["okta.get_profile_mapping"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/mappings/{mappingId}", path = {"mappingId"} },
    ["okta.get_refresh_token_for_authorization_server_and_client"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/clients/{clientId}/tokens/{tokenId}", path = {"authServerId", "clientId", "tokenId"}, query = {"expand"} },
    ["okta.get_refresh_token_for_user_and_client"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/clients/{clientId}/tokens/{tokenId}", path = {"userId", "clientId", "tokenId"}, query = {"expand", "limit", "after"} },
    ["okta.get_role"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}", path = {"groupId", "roleId"} },
    ["okta.get_role_subscription_by_notification_type"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/roles/{roleTypeOrRoleId}/subscriptions/{notificationType}", path = {"roleTypeOrRoleId", "notificationType"} },
    ["okta.get_scope_consent_grant"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/grants/{grantId}", path = {"appId", "grantId"}, query = {"expand"} },
    ["okta.get_session"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/sessions/{sessionId}", path = {"sessionId"} },
    ["okta.get_sms_template"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/templates/sms/{templateId}", path = {"templateId"} },
    ["okta.get_user"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}", path = {"userId"} },
    ["okta.get_user_grant"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/grants/{grantId}", path = {"userId", "grantId"}, query = {"expand"} },
    ["okta.get_user_role"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}", path = {"userId", "roleId"} },
    ["okta.get_user_schema"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/user/{schemaId}", path = {"schemaId"} },
    ["okta.get_user_subscription_by_notification_type"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/subscriptions/{notificationType}", path = {"userId", "notificationType"} },
    ["okta.get_user_type"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/meta/types/user/{typeId}", path = {"typeId"} },
    ["okta.grant_consent_to_scope"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/grants", path = {"appId"}, body = {"_embedded", "_links", "clientId", "created", "createdBy", "id", "issuer", "lastUpdated", "scopeId", "source", "status", "userId", "oAuth2ScopeConsentGrant"} },
    ["okta.grant_okta_support"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org/privacy/oktaSupport/grant" },
    ["okta.hide_okta_uifooter"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org/preferences/hideEndUserFooter" },
    ["okta.link_user_to_identity_provider"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/users/{userId}", path = {"idpId", "userId"}, body = {"externalId", "userIdentityProviderLinkRequest"} },
    ["okta.list_app_links"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/appLinks", path = {"userId"} },
    ["okta.list_application_group_assignments"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/groups", path = {"appId"}, query = {"q", "after", "limit", "expand"} },
    ["okta.list_application_keys"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/keys", path = {"appId"} },
    ["okta.list_application_targets_for_application_administrator_role_for_group"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}/targets/catalog/apps", path = {"groupId", "roleId"}, query = {"after", "limit"} },
    ["okta.list_application_targets_for_application_administrator_role_for_user"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/catalog/apps", path = {"userId", "roleId"}, query = {"after", "limit"} },
    ["okta.list_application_users"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/users", path = {"appId"}, query = {"q", "query_scope", "after", "limit", "filter", "expand"} },
    ["okta.list_applications"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps", query = {"q", "after", "limit", "filter", "expand", "includeNonDeleted"} },
    ["okta.list_assigned_applications_for_group"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/apps", path = {"groupId"}, query = {"after", "limit"} },
    ["okta.list_assigned_roles_for_user"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles", path = {"userId"}, query = {"expand"} },
    ["okta.list_authenticators"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authenticators" },
    ["okta.list_authorization_server_keys"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/credentials/keys", path = {"authServerId"} },
    ["okta.list_authorization_server_policies"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies", path = {"authServerId"} },
    ["okta.list_authorization_server_policy_rules"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/rules", path = {"authServerId", "policyId"} },
    ["okta.list_authorization_servers"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers", query = {"q", "limit", "after"} },
    ["okta.list_brand_themes"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes", path = {"brandId"} },
    ["okta.list_brands"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands" },
    ["okta.list_client_secrets_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/secrets", path = {"appId"} },
    ["okta.list_csrs_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/csrs", path = {"appId"} },
    ["okta.list_csrs_for_identity_provider"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/csrs", path = {"idpId"} },
    ["okta.list_domains"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/domains" },
    ["okta.list_email_template_customizations"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/customizations", path = {"brandId", "templateName"} },
    ["okta.list_email_templates"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email", path = {"brandId"}, query = {"after", "limit"} },
    ["okta.list_event_hooks"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/eventHooks" },
    ["okta.list_factors"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors", path = {"userId"} },
    ["okta.list_feature_dependencies"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/features/{featureId}/dependencies", path = {"featureId"} },
    ["okta.list_feature_dependents"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/features/{featureId}/dependents", path = {"featureId"} },
    ["okta.list_features"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/features" },
    ["okta.list_features_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/features", path = {"appId"} },
    ["okta.list_grants_for_user_and_client"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/clients/{clientId}/grants", path = {"userId", "clientId"}, query = {"expand", "after", "limit"} },
    ["okta.list_group_assigned_roles"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles", path = {"groupId"}, query = {"expand"} },
    ["okta.list_group_rules"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/rules", query = {"limit", "after", "search", "expand"} },
    ["okta.list_group_targets_for_group_role"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}/targets/groups", path = {"groupId", "roleId"}, query = {"after", "limit"} },
    ["okta.list_group_targets_for_role"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/groups", path = {"userId", "roleId"}, query = {"after", "limit"} },
    ["okta.list_group_users"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/users", path = {"groupId"}, query = {"after", "limit"} },
    ["okta.list_groups"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/groups", query = {"q", "filter", "after", "limit", "expand", "search"} },
    ["okta.list_identity_provider_application_users"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/users", path = {"idpId"} },
    ["okta.list_identity_provider_keys"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/credentials/keys", query = {"after", "limit"} },
    ["okta.list_identity_provider_signing_keys"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/keys", path = {"idpId"} },
    ["okta.list_identity_providers"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps", query = {"q", "after", "limit", "type"} },
    ["okta.list_inline_hooks"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/inlineHooks", query = {"type"} },
    ["okta.list_linked_object_definitions"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/user/linkedObjects" },
    ["okta.list_network_zones"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/zones", query = {"after", "limit", "filter"} },
    ["okta.list_oauth2_claims"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/claims", path = {"authServerId"} },
    ["okta.list_oauth2_clients_for_authorization_server"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/clients", path = {"authServerId"} },
    ["okta.list_oauth2_scopes"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/scopes", path = {"authServerId"}, query = {"q", "filter", "cursor", "limit"} },
    ["okta.list_oauth2_tokens_for_application"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/tokens", path = {"appId"}, query = {"expand", "after", "limit"} },
    ["okta.list_origins"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/trustedOrigins", query = {"q", "filter", "after", "limit"} },
    ["okta.list_policies"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/policies", query = {"type", "status", "expand"} },
    ["okta.list_policy_rules"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/rules", path = {"policyId"} },
    ["okta.list_profile_mappings"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/mappings", query = {"after", "limit", "sourceId", "targetId"} },
    ["okta.list_refresh_tokens_for_authorization_server_and_client"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/clients/{clientId}/tokens", path = {"authServerId", "clientId"}, query = {"expand", "after", "limit"} },
    ["okta.list_refresh_tokens_for_user_and_client"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/clients/{clientId}/tokens", path = {"userId", "clientId"}, query = {"expand", "after", "limit"} },
    ["okta.list_role_subscriptions"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/roles/{roleTypeOrRoleId}/subscriptions", path = {"roleTypeOrRoleId"} },
    ["okta.list_scope_consent_grants"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/grants", path = {"appId"}, query = {"expand"} },
    ["okta.list_sms_templates"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/templates/sms", query = {"templateType"} },
    ["okta.list_social_auth_tokens"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/users/{userId}/credentials/tokens", path = {"idpId", "userId"} },
    ["okta.list_supported_factors"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors/catalog", path = {"userId"} },
    ["okta.list_supported_security_questions"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors/questions", path = {"userId"} },
    ["okta.list_user_clients"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/clients", path = {"userId"} },
    ["okta.list_user_grants"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/grants", path = {"userId"}, query = {"scopeId", "expand", "after", "limit"} },
    ["okta.list_user_groups"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/groups", path = {"userId"} },
    ["okta.list_user_identity_providers"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/idps", path = {"userId"} },
    ["okta.list_user_subscriptions"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/subscriptions", path = {"userId"} },
    ["okta.list_user_types"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/meta/types/user" },
    ["okta.list_users"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/users", query = {"q", "after", "limit", "filter", "search", "sortBy", "sortOrder"} },
    ["okta.opt_in_users_to_okta_communication_emails"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org/privacy/oktaCommunication/optIn" },
    ["okta.opt_out_users_from_okta_communication_emails"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org/privacy/oktaCommunication/optOut" },
    ["okta.partial_update_org_setting"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org", body = {"_links", "address1", "address2", "city", "companyName", "country", "created", "endUserSupportHelpURL", "expiresAt", "id", "lastUpdated", "phoneNumber", "postalCode", "state", "status", "subdomain", "supportPhoneNumber", "website", "orgSetting"} },
    ["okta.partial_update_sms_template"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/templates/sms/{templateId}", path = {"templateId"}, body = {"created", "id", "lastUpdated", "name", "template", "translations", "type", "smsTemplate"} },
    ["okta.partial_update_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}", path = {"userId"}, query = {"strict"}, body = {"_embedded", "_links", "activated", "created", "credentials", "id", "lastLogin", "lastUpdated", "passwordChanged", "profile", "status", "statusChanged", "transitioningToStatus", "type", "user"} },
    ["okta.post_api_v1_apps_appId_credentials_csrs_csrId_lifecycle_publish"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/csrs/{csrId}/lifecycle/publish", path = {"appId", "csrId"} },
    ["okta.post_api_v1_idps_idpId_credentials_csrs_csrId_lifecycle_publish"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/csrs/{csrId}/lifecycle/publish", path = {"idpId", "csrId"} },
    ["okta.post_api_v1_users_userId_credentials_forgot_password"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/credentials/forgot_password", path = {"userId"} },
    ["okta.preview_samlapp_metadata"] = { method = "GET", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/sso/saml/metadata", path = {"appId"}, query = {"kid"} },
    ["okta.reactivate_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/reactivate", path = {"userId"}, query = {"sendEmail"} },
    ["okta.refresh_session"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/sessions/{sessionId}/lifecycle/refresh", path = {"sessionId"} },
    ["okta.remove_application_target_from_administrator_role_for_user"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/catalog/apps/{appName}/{applicationId}", path = {"userId", "roleId", "appName", "applicationId"} },
    ["okta.remove_application_target_from_administrator_role_given_to_group"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}/targets/catalog/apps/{appName}/{applicationId}", path = {"groupId", "roleId", "appName", "applicationId"} },
    ["okta.remove_application_target_from_application_administrator_role_for_user"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/catalog/apps/{appName}", path = {"userId", "roleId", "appName"} },
    ["okta.remove_application_target_from_application_administrator_role_given_to_group"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}/targets/catalog/apps/{appName}", path = {"groupId", "roleId", "appName"} },
    ["okta.remove_group_target_from_group_administrator_role_given_to_group"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}/targets/groups/{targetGroupId}", path = {"groupId", "roleId", "targetGroupId"} },
    ["okta.remove_group_target_from_role"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}/targets/groups/{groupId}", path = {"userId", "roleId", "groupId"} },
    ["okta.remove_linked_object_for_user"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/linkedObjects/{relationshipName}", path = {"userId", "relationshipName"} },
    ["okta.remove_role_from_group"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/roles/{roleId}", path = {"groupId", "roleId"} },
    ["okta.remove_role_from_user"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/roles/{roleId}", path = {"userId", "roleId"} },
    ["okta.remove_user_from_group"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}/users/{userId}", path = {"groupId", "userId"} },
    ["okta.replace_user_type"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/meta/types/user/{typeId}", path = {"typeId"}, body = {"_links", "created", "createdBy", "default", "description", "displayName", "id", "lastUpdated", "lastUpdatedBy", "name", "userType"} },
    ["okta.reset_factors"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/reset_factors", path = {"userId"} },
    ["okta.reset_password"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/reset_password", path = {"userId"}, query = {"sendEmail"} },
    ["okta.revoke_csr_for_identity_provider"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/credentials/csrs/{csrId}", path = {"idpId", "csrId"} },
    ["okta.revoke_csr_from_application"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/credentials/csrs/{csrId}", path = {"appId", "csrId"} },
    ["okta.revoke_grants_for_user_and_client"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/clients/{clientId}/grants", path = {"userId", "clientId"} },
    ["okta.revoke_oauth2_token_for_application"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/tokens/{tokenId}", path = {"appId", "tokenId"} },
    ["okta.revoke_oauth2_tokens_for_application"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/tokens", path = {"appId"} },
    ["okta.revoke_okta_support"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org/privacy/oktaSupport/revoke" },
    ["okta.revoke_refresh_token_for_authorization_server_and_client"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/clients/{clientId}/tokens/{tokenId}", path = {"authServerId", "clientId", "tokenId"} },
    ["okta.revoke_refresh_tokens_for_authorization_server_and_client"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/clients/{clientId}/tokens", path = {"authServerId", "clientId"} },
    ["okta.revoke_scope_consent_grant"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/grants/{grantId}", path = {"appId", "grantId"} },
    ["okta.revoke_token_for_user_and_client"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/clients/{clientId}/tokens/{tokenId}", path = {"userId", "clientId", "tokenId"} },
    ["okta.revoke_tokens_for_user_and_client"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/clients/{clientId}/tokens", path = {"userId", "clientId"} },
    ["okta.revoke_user_grant"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/grants/{grantId}", path = {"userId", "grantId"} },
    ["okta.revoke_user_grants"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/grants", path = {"userId"} },
    ["okta.rotate_authorization_server_keys"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/credentials/lifecycle/keyRotate", path = {"authServerId"}, body = {"use"} },
    ["okta.send_test_email"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/test", path = {"brandId", "templateName"}, body = {"customizationId", "customization"} },
    ["okta.set_default_provisioning_connection_for_application"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/connections/default", path = {"appId"}, query = {"activate"}, body = {"profile"} },
    ["okta.set_linked_object_for_user"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/users/{associatedUserId}/linkedObjects/{primaryRelationshipName}/{primaryUserId}", path = {"associatedUserId", "primaryRelationshipName", "primaryUserId"} },
    ["okta.show_okta_uifooter"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org/preferences/showEndUserFooter" },
    ["okta.subscribe_role_subscription_by_notification_type"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/roles/{roleTypeOrRoleId}/subscriptions/{notificationType}/subscribe", path = {"roleTypeOrRoleId", "notificationType"} },
    ["okta.subscribe_user_subscription_by_notification_type"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/subscriptions/{notificationType}/subscribe", path = {"userId", "notificationType"} },
    ["okta.suspend_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/suspend", path = {"userId"} },
    ["okta.unlink_user_from_identity_provider"] = { method = "DELETE", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}/users/{userId}", path = {"idpId", "userId"} },
    ["okta.unlock_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/unlock", path = {"userId"} },
    ["okta.unsubscribe_role_subscription_by_notification_type"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/roles/{roleTypeOrRoleId}/subscriptions/{notificationType}/unsubscribe", path = {"roleTypeOrRoleId", "notificationType"} },
    ["okta.unsubscribe_user_subscription_by_notification_type"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/subscriptions/{notificationType}/unsubscribe", path = {"userId", "notificationType"} },
    ["okta.unsuspend_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/lifecycle/unsuspend", path = {"userId"} },
    ["okta.update_application"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}", path = {"appId"}, body = {"_embedded", "_links", "accessibility", "created", "credentials", "features", "id", "label", "lastUpdated", "licensing", "name", "profile", "settings", "signOnMode", "status", "visibility", "application"} },
    ["okta.update_application_policy"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/policies/{policyId}", path = {"appId", "policyId"} },
    ["okta.update_application_user"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/users/{userId}", path = {"appId", "userId"}, body = {"_embedded", "_links", "created", "credentials", "externalId", "id", "lastSync", "lastUpdated", "passwordChanged", "profile", "scope", "status", "statusChanged", "syncState", "appUser"} },
    ["okta.update_application_user_profile"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/apps/{appInstanceId}/default", path = {"appInstanceId"}, body = {"$schema", "_links", "created", "definitions", "id", "lastUpdated", "name", "properties", "title", "type", "body"} },
    ["okta.update_authenticator"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/authenticators/{authenticatorId}", path = {"authenticatorId"}, body = {"_links", "created", "id", "lastUpdated", "name", "provider", "settings", "status", "type", "authenticator"} },
    ["okta.update_authorization_server"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}", path = {"authServerId"}, body = {"_links", "audiences", "created", "credentials", "default", "description", "id", "issuer", "issuerMode", "lastUpdated", "name", "status", "authorizationServer"} },
    ["okta.update_authorization_server_policy"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}", path = {"authServerId", "policyId"}, body = {"_embedded", "_links", "conditions", "created", "description", "id", "lastUpdated", "name", "priority", "status", "system", "type", "policy"} },
    ["okta.update_authorization_server_policy_rule"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/policies/{policyId}/rules/{ruleId}", path = {"authServerId", "policyId", "ruleId"}, body = {"actions", "conditions", "created", "id", "lastUpdated", "name", "priority", "status", "system", "type", "policyRule"} },
    ["okta.update_brand"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}", path = {"brandId"}, body = {"_links", "agreeToCustomPrivacyPolicy", "customPrivacyPolicyUrl", "id", "removePoweredByOkta", "brand"} },
    ["okta.update_brand_theme"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes/{themeId}", path = {"brandId", "themeId"}, body = {"_links", "backgroundImage", "emailTemplateTouchPointVariant", "endUserDashboardTouchPointVariant", "errorPageTouchPointVariant", "primaryColorContrastHex", "primaryColorHex", "secondaryColorContrastHex", "secondaryColorHex", "signInPageTouchPointVariant", "theme"} },
    ["okta.update_configuration"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/threats/configuration", body = {"_links", "action", "created", "excludeZones", "lastUpdated", "ThreatInsightConfiguration"} },
    ["okta.update_email_template_customization"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/templates/email/{templateName}/customizations/{customizationId}", path = {"brandId", "templateName", "customizationId"}, body = {"body", "isDefault", "language", "subject", "customization"} },
    ["okta.update_event_hook"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/eventHooks/{eventHookId}", path = {"eventHookId"}, body = {"_links", "channel", "created", "createdBy", "events", "id", "lastUpdated", "name", "status", "verificationStatus", "eventHook"} },
    ["okta.update_feature_for_application"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/features/{name}", path = {"appId", "name"}, body = {"create", "update", "capabilities"} },
    ["okta.update_feature_lifecycle"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/features/{featureId}/{lifecycle}", path = {"featureId", "lifecycle"}, query = {"mode"} },
    ["okta.update_group"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/groups/{groupId}", path = {"groupId"}, body = {"_embedded", "_links", "created", "id", "lastMembershipUpdated", "lastUpdated", "objectClass", "profile", "type", "group"} },
    ["okta.update_group_rule"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/groups/rules/{ruleId}", path = {"ruleId"}, body = {"actions", "conditions", "created", "id", "lastUpdated", "name", "status", "type", "groupRule"} },
    ["okta.update_group_schema"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/group/default", body = {"$schema", "_links", "created", "definitions", "description", "id", "lastUpdated", "name", "properties", "title", "type", "body"} },
    ["okta.update_identity_provider"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/idps/{idpId}", path = {"idpId"}, body = {"_links", "created", "id", "issuerMode", "lastUpdated", "name", "policy", "protocol", "status", "type", "identityProvider"} },
    ["okta.update_inline_hook"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/inlineHooks/{inlineHookId}", path = {"inlineHookId"}, body = {"_links", "channel", "created", "id", "lastUpdated", "name", "status", "type", "version", "inlineHook"} },
    ["okta.update_network_zone"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/zones/{zoneId}", path = {"zoneId"}, body = {"_links", "asns", "created", "gateways", "id", "lastUpdated", "locations", "name", "proxies", "proxyType", "status", "system", "type", "usage", "zone"} },
    ["okta.update_oauth2_claim"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/claims/{claimId}", path = {"authServerId", "claimId"}, body = {"_links", "alwaysIncludeInToken", "claimType", "conditions", "group_filter_type", "id", "name", "status", "system", "value", "valueType", "oAuth2Claim"} },
    ["okta.update_oauth2_scope"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/authorizationServers/{authServerId}/scopes/{scopeId}", path = {"authServerId", "scopeId"}, body = {"consent", "default", "description", "displayName", "id", "metadataPublish", "name", "system", "oAuth2Scope"} },
    ["okta.update_org_contact_user"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/org/contacts/{contactType}", path = {"contactType"}, body = {"userId"} },
    ["okta.update_org_logo"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/org/logo", body = {"file"} },
    ["okta.update_org_setting"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/org", body = {"_links", "address1", "address2", "city", "companyName", "country", "created", "endUserSupportHelpURL", "expiresAt", "id", "lastUpdated", "phoneNumber", "postalCode", "state", "status", "subdomain", "supportPhoneNumber", "website", "orgSetting"} },
    ["okta.update_origin"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/trustedOrigins/{trustedOriginId}", path = {"trustedOriginId"}, body = {"_links", "created", "createdBy", "id", "lastUpdated", "lastUpdatedBy", "name", "origin", "scopes", "status", "trustedOrigin"} },
    ["okta.update_policy"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}", path = {"policyId"}, body = {"_embedded", "_links", "conditions", "created", "description", "id", "lastUpdated", "name", "priority", "status", "system", "type", "policy"} },
    ["okta.update_policy_rule"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/policies/{policyId}/rules/{ruleId}", path = {"policyId", "ruleId"}, body = {"actions", "conditions", "created", "id", "lastUpdated", "name", "priority", "status", "system", "type", "policyRule"} },
    ["okta.update_profile_mapping"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/mappings/{mappingId}", path = {"mappingId"}, body = {"_links", "id", "properties", "source", "target", "profileMapping"} },
    ["okta.update_sms_template"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/templates/sms/{templateId}", path = {"templateId"}, body = {"created", "id", "lastUpdated", "name", "template", "translations", "type", "smsTemplate"} },
    ["okta.update_user"] = { method = "PUT", url = "https://{subdomain}.okta.com/api/v1/users/{userId}", path = {"userId"}, query = {"strict"}, body = {"_embedded", "_links", "activated", "created", "credentials", "id", "lastLogin", "lastUpdated", "passwordChanged", "profile", "status", "statusChanged", "transitioningToStatus", "type", "user"} },
    ["okta.update_user_profile"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/meta/schemas/user/{schemaId}", path = {"schemaId"}, body = {"$schema", "_links", "created", "definitions", "id", "lastUpdated", "name", "properties", "title", "type", "userSchema"} },
    ["okta.update_user_type"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/meta/types/user/{typeId}", path = {"typeId"}, body = {"_links", "created", "createdBy", "default", "description", "displayName", "id", "lastUpdated", "lastUpdatedBy", "name", "userType"} },
    ["okta.upload_application_logo"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/apps/{appId}/logo", path = {"appId"}, body = {"file"} },
    ["okta.upload_brand_theme_background_image"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes/{themeId}/background-image", path = {"brandId", "themeId"}, body = {"file"} },
    ["okta.upload_brand_theme_favicon"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes/{themeId}/favicon", path = {"brandId", "themeId"}, body = {"file"} },
    ["okta.upload_brand_theme_logo"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/brands/{brandId}/themes/{themeId}/logo", path = {"brandId", "themeId"}, body = {"file"} },
    ["okta.verify_domain"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/domains/{domainId}/verify", path = {"domainId"} },
    ["okta.verify_event_hook"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/eventHooks/{eventHookId}/lifecycle/verify", path = {"eventHookId"} },
    ["okta.verify_factor"] = { method = "POST", url = "https://{subdomain}.okta.com/api/v1/users/{userId}/factors/{factorId}/verify", path = {"userId", "factorId"}, query = {"templateId", "tokenLifetimeSeconds"}, header = {"X-Forwarded-For", "User-Agent", "Accept-Language"}, body = {"activationToken", "answer", "attestation", "clientData", "nextPassCode", "passCode", "registrationData", "stateToken", "body"} },
  },
}
