-- Webflow — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/webflow/openapi-spec/main/openapi/v2.yml
-- Published by webflow, the vendor's own GitHub organisation.
-- 126 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "webflow",
  name = "Webflow",
  base = "https://api.webflow.com",
  docs = "https://nango.dev/docs/integrations/all/webflow",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "WEBFLOW_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["webflow.add_custom_code_to_page"] = { method = "PUT", url = "https://api.webflow.com/v2/pages/{page_id}/custom_code", path = {"page_id"}, body = {"scripts", "lastUpdated", "createdOn"} },
    ["webflow.add_custom_code_tosite"] = { method = "PUT", url = "https://api.webflow.com/v2/sites/{site_id}/custom_code", path = {"site_id"}, body = {"scripts", "lastUpdated", "createdOn"} },
    ["webflow.authorized_by"] = { method = "GET", url = "https://api.webflow.com/v2/token/authorized_by" },
    ["webflow.batch_create_custom_fonts"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/custom_fonts/batchCreate", path = {"site_id"}, body = {"items"} },
    ["webflow.batch_delete_custom_fonts"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/custom_fonts/batchDelete", path = {"site_id"}, body = {"items"} },
    ["webflow.collection_details"] = { method = "GET", url = "https://api.webflow.com/v2/collections/{collection_id}", path = {"collection_id"} },
    ["webflow.create_asset"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/assets", path = {"site_id"}, body = {"fileName", "fileHash", "parentFolder"} },
    ["webflow.create_asset_folder"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/asset_folders", path = {"site_id"}, body = {"displayName", "parentFolder"} },
    ["webflow.create_collection"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/collections", path = {"site_id"}, body = {"displayName", "singularName", "slug", "fields"} },
    ["webflow.create_comment_reply"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/comments/{comment_thread_id}/replies", path = {"site_id", "comment_thread_id"}, body = {"content"} },
    ["webflow.create_custom_font"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/custom_fonts", path = {"site_id"}, body = {"fileName", "fileHash", "fontFamily", "weight", "italic", "fontDisplay", "axes"} },
    ["webflow.create_field"] = { method = "POST", url = "https://api.webflow.com/v2/collections/{collection_id}/fields", path = {"collection_id"} },
    ["webflow.create_item"] = { method = "POST", url = "https://api.webflow.com/v2/collections/{collection_id}/items", path = {"collection_id"}, query = {"skipInvalidFiles"} },
    ["webflow.create_item_live"] = { method = "POST", url = "https://api.webflow.com/v2/collections/{collection_id}/items/live", path = {"collection_id"}, query = {"skipInvalidFiles"} },
    ["webflow.create_items"] = { method = "POST", url = "https://api.webflow.com/v2/collections/{collection_id}/items/bulk", path = {"collection_id"}, query = {"skipInvalidFiles"}, body = {"cmsLocaleIds", "lastPublished", "lastUpdated", "createdOn", "isArchived", "isDraft", "fieldData"} },
    ["webflow.create_product"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/products", path = {"site_id"}, body = {"publishStatus", "product", "sku"} },
    ["webflow.create_redirect"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/redirects", path = {"site_id"}, body = {"id", "fromUrl", "toUrl"} },
    ["webflow.create_site"] = { method = "POST", url = "https://api.webflow.com/v2/workspaces/{workspace_id}/sites", path = {"workspace_id"}, body = {"name", "templateName", "parentFolderId"} },
    ["webflow.create_skus"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/products/{product_id}/skus", path = {"site_id", "product_id"}, body = {"publishStatus", "skus"} },
    ["webflow.create_webhook"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/webhooks", path = {"site_id"}, body = {"id", "triggerType", "url", "workspaceId", "siteId", "filter", "lastTriggered", "createdOn"} },
    ["webflow.delete_asset"] = { method = "DELETE", url = "https://api.webflow.com/v2/assets/{asset_id}", path = {"asset_id"} },
    ["webflow.delete_collection"] = { method = "DELETE", url = "https://api.webflow.com/v2/collections/{collection_id}", path = {"collection_id"} },
    ["webflow.delete_custom_font"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}/custom_fonts/{font_id}", path = {"site_id", "font_id"} },
    ["webflow.delete_field"] = { method = "DELETE", url = "https://api.webflow.com/v2/collections/{collection_id}/fields/{field_id}", path = {"collection_id", "field_id"} },
    ["webflow.delete_form_submission"] = { method = "DELETE", url = "https://api.webflow.com/v2/form_submissions/{form_submission_id}", path = {"form_submission_id"} },
    ["webflow.delete_form_submission_by_site"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}/form_submissions/{form_submission_id}", path = {"site_id", "form_submission_id"} },
    ["webflow.delete_google_tag"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}/integrations/google_tags/{tag_id}", path = {"site_id", "tag_id"} },
    ["webflow.delete_google_tags"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}/integrations/google_tags", path = {"site_id"} },
    ["webflow.delete_item"] = { method = "DELETE", url = "https://api.webflow.com/v2/collections/{collection_id}/items/{item_id}", path = {"collection_id", "item_id"}, query = {"cmsLocaleId"} },
    ["webflow.delete_item_live"] = { method = "DELETE", url = "https://api.webflow.com/v2/collections/{collection_id}/items/{item_id}/live", path = {"collection_id", "item_id"}, query = {"cmsLocaleId"} },
    ["webflow.delete_items"] = { method = "DELETE", url = "https://api.webflow.com/v2/collections/{collection_id}/items", path = {"collection_id"}, body = {"items"} },
    ["webflow.delete_items_live"] = { method = "DELETE", url = "https://api.webflow.com/v2/collections/{collection_id}/items/live", path = {"collection_id"}, body = {"items"} },
    ["webflow.delete_page_custom_code"] = { method = "DELETE", url = "https://api.webflow.com/v2/pages/{page_id}/custom_code", path = {"page_id"} },
    ["webflow.delete_redirects"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}/redirects/{redirect_id}", path = {"site_id", "redirect_id"} },
    ["webflow.delete_robots_txt"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}/robots_txt", path = {"site_id"}, body = {"rules", "sitemap"} },
    ["webflow.delete_site"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}", path = {"site_id"} },
    ["webflow.delete_site_custom_code"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}/custom_code", path = {"site_id"} },
    ["webflow.delete_well_known"] = { method = "DELETE", url = "https://api.webflow.com/v2/sites/{site_id}/well_known", path = {"site_id"}, body = {"fileNames"} },
    ["webflow.ecommerce_settings"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/ecommerce/settings", path = {"site_id"} },
    ["webflow.fulfill_order"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/orders/{order_id}/fulfill", path = {"site_id", "order_id"}, body = {"sendOrderFulfilledEmail"} },
    ["webflow.get_analyze_time_on_page_report"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/analyze/reports/time_on_page", path = {"site_id"}, query = {"startTime", "endTime", "metricScope", "timeseries", "deviceType", "country", "pagePath", "trafficSource", "referrer", "browser", "utmCampaign", "utmMedium", "utmSource", "filter"} },
    ["webflow.get_analyze_top_dimensions_report"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/analyze/reports/top_dimensions", path = {"site_id"}, query = {"startTime", "endTime", "dimension", "metricScope", "limit", "deviceType", "country", "pagePath", "trafficSource", "referrer", "browser", "utmCampaign", "utmMedium", "utmSource", "filter"} },
    ["webflow.get_analyze_top_events_report"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/analyze/reports/top_events", path = {"site_id"}, query = {"startTime", "endTime", "limit", "timeseries", "deviceType", "country", "pagePath", "trafficSource", "browser", "utmCampaign", "utmMedium", "utmSource", "filter"} },
    ["webflow.get_analyze_top_pages_report"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/analyze/reports/top_pages", path = {"site_id"}, query = {"startTime", "endTime", "sortBy", "limit", "timeseries", "deviceType", "country", "pagePath", "trafficSource", "referrer", "browser", "utmCampaign", "utmMedium", "utmSource", "filter"} },
    ["webflow.get_analyze_traffic_report"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/analyze/reports/traffic", path = {"site_id"}, query = {"startTime", "endTime", "metricScope", "bucketTimeZone", "deviceType", "country", "pagePath", "trafficSource", "referrer", "browser", "utmCampaign", "utmMedium", "utmSource", "filter"} },
    ["webflow.get_asset"] = { method = "GET", url = "https://api.webflow.com/v2/assets/{asset_id}", path = {"asset_id"}, query = {"localeId"} },
    ["webflow.get_asset_folder"] = { method = "GET", url = "https://api.webflow.com/v2/asset_folders/{asset_folder_id}", path = {"asset_folder_id"} },
    ["webflow.get_comment_thread"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/comments/{comment_thread_id}", path = {"site_id", "comment_thread_id"}, query = {"localeId", "offset", "limit", "sortBy", "sortOrder"} },
    ["webflow.get_component_content"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/components/{component_id}/dom", path = {"site_id", "component_id"}, query = {"localeId", "branchId", "limit", "offset", "translatable"} },
    ["webflow.get_component_properties"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/components/{component_id}/properties", path = {"site_id", "component_id"}, query = {"localeId", "branchId", "limit", "offset", "translatable"} },
    ["webflow.get_custom_domains"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/custom_domains", path = {"site_id"} },
    ["webflow.get_custom_font"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/custom_fonts/{font_id}", path = {"site_id", "font_id"} },
    ["webflow.get_form_schema"] = { method = "GET", url = "https://api.webflow.com/v2/forms/{form_id}", path = {"form_id"} },
    ["webflow.get_form_submission"] = { method = "GET", url = "https://api.webflow.com/v2/form_submissions/{form_submission_id}", path = {"form_submission_id"} },
    ["webflow.get_form_submission_by_site"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/form_submissions/{form_submission_id}", path = {"site_id", "form_submission_id"} },
    ["webflow.get_item"] = { method = "GET", url = "https://api.webflow.com/v2/collections/{collection_id}/items/{item_id}", path = {"collection_id", "item_id"}, query = {"cmsLocaleId", "translatable"} },
    ["webflow.get_item_live"] = { method = "GET", url = "https://api.webflow.com/v2/collections/{collection_id}/items/{item_id}/live", path = {"collection_id", "item_id"}, query = {"cmsLocaleId", "translatable"} },
    ["webflow.get_order"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/orders/{order_id}", path = {"site_id", "order_id"} },
    ["webflow.get_page_custom_code"] = { method = "GET", url = "https://api.webflow.com/v2/pages/{page_id}/custom_code", path = {"page_id"} },
    ["webflow.get_page_metadata"] = { method = "GET", url = "https://api.webflow.com/v2/pages/{page_id}", path = {"page_id"}, query = {"localeId", "translatable"} },
    ["webflow.get_product"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/products/{product_id}", path = {"site_id", "product_id"} },
    ["webflow.get_redirects"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/redirects", path = {"site_id"} },
    ["webflow.get_robots_txt"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/robots_txt", path = {"site_id"} },
    ["webflow.get_scripts"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/registered_scripts", path = {"site_id"} },
    ["webflow.get_site"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}", path = {"site_id"} },
    ["webflow.get_site_activity_logs"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/activity_logs", path = {"site_id"}, query = {"limit", "offset"} },
    ["webflow.get_site_custom_code"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/custom_code", path = {"site_id"} },
    ["webflow.get_site_custom_code_blocks"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/custom_code/blocks", path = {"site_id"}, query = {"offset", "limit"} },
    ["webflow.get_site_plan"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/plan", path = {"site_id"} },
    ["webflow.get_static_content"] = { method = "GET", url = "https://api.webflow.com/v2/pages/{page_id}/dom", path = {"page_id"}, query = {"localeId", "limit", "offset", "translatable"} },
    ["webflow.get_webhook"] = { method = "GET", url = "https://api.webflow.com/v2/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["webflow.get_workspace_audit_logs"] = { method = "GET", url = "https://api.webflow.com/v2/workspaces/{workspace_id_or_slug}/audit_logs", path = {"workspace_id_or_slug"}, query = {"limit", "offset", "sortOrder", "eventType", "from", "to"} },
    ["webflow.introspect"] = { method = "GET", url = "https://api.webflow.com/v2/token/introspect" },
    ["webflow.list_asset_folders"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/asset_folders", path = {"site_id"} },
    ["webflow.list_assets"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/assets", path = {"site_id"}, query = {"localeId", "offset", "limit", "folderId"} },
    ["webflow.list_collection_items"] = { method = "GET", url = "https://api.webflow.com/v2/collections/{collection_id}/items", path = {"collection_id"}, query = {"cmsLocaleId", "offset", "limit", "name", "slug", "createdOn", "lastPublished", "lastUpdated", "filter", "sortBy", "sortOrder", "sort", "translatable"} },
    ["webflow.list_collection_items_live"] = { method = "GET", url = "https://api.webflow.com/v2/collections/{collection_id}/items/live", path = {"collection_id"}, query = {"cmsLocaleId", "offset", "limit", "name", "slug", "createdOn", "lastPublished", "lastUpdated", "filter", "sortBy", "sortOrder", "sort", "translatable"} },
    ["webflow.list_collections"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/collections", path = {"site_id"} },
    ["webflow.list_comment_replies"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/comments/{comment_thread_id}/replies", path = {"site_id", "comment_thread_id"}, query = {"localeId", "offset", "limit", "sortBy", "sortOrder"} },
    ["webflow.list_comment_threads"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/comments", path = {"site_id"}, query = {"localeId", "offset", "limit", "sortBy", "sortOrder"} },
    ["webflow.list_components"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/components", path = {"site_id"}, query = {"branchId", "limit", "offset"} },
    ["webflow.list_custom_fonts"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/custom_fonts", path = {"site_id"}, query = {"offset", "limit"} },
    ["webflow.list_forms"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/forms", path = {"site_id"}, query = {"limit", "offset"} },
    ["webflow.list_google_tags"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/integrations/google_tags", path = {"site_id"} },
    ["webflow.list_inventory"] = { method = "GET", url = "https://api.webflow.com/v2/collections/{sku_collection_id}/items/{sku_id}/inventory", path = {"sku_collection_id", "sku_id"} },
    ["webflow.list_orders"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/orders", path = {"site_id"}, query = {"status", "offset", "limit"} },
    ["webflow.list_pages"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/pages", path = {"site_id"}, query = {"localeId", "limit", "offset"} },
    ["webflow.list_products"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/products", path = {"site_id"}, query = {"offset", "limit"} },
    ["webflow.list_sites"] = { method = "GET", url = "https://api.webflow.com/v2/sites" },
    ["webflow.list_submissions"] = { method = "GET", url = "https://api.webflow.com/v2/forms/{form_id}/submissions", path = {"form_id"}, query = {"offset", "limit"} },
    ["webflow.list_submissions"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/forms/{form_id}/submissions", path = {"site_id", "form_id"}, query = {"offset", "limit"} },
    ["webflow.list_submissions_by_site"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/form_submissions", path = {"site_id"}, query = {"elementId", "offset", "limit"} },
    ["webflow.list_webhooks"] = { method = "GET", url = "https://api.webflow.com/v2/sites/{site_id}/webhooks", path = {"site_id"} },
    ["webflow.modify_form_submission"] = { method = "PATCH", url = "https://api.webflow.com/v2/form_submissions/{form_submission_id}", path = {"form_submission_id"}, body = {"formSubmissionData"} },
    ["webflow.modify_form_submission_by_site"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/form_submissions/{form_submission_id}", path = {"site_id", "form_submission_id"}, body = {"formSubmissionData"} },
    ["webflow.patch_asset"] = { method = "PATCH", url = "https://api.webflow.com/v2/assets/{asset_id}", path = {"asset_id"}, query = {"localeId"}, body = {"displayName", "altText"} },
    ["webflow.patch_collection"] = { method = "PATCH", url = "https://api.webflow.com/v2/collections/{collection_id}", path = {"collection_id"}, body = {"displayName", "singularName", "slug", "fieldGroups"} },
    ["webflow.post_hosted_script"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/registered_scripts/hosted", path = {"site_id"}, body = {"hostedLocation", "integrityHash", "canCopy", "version", "displayName"} },
    ["webflow.post_inline_scripts"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/registered_scripts/inline", path = {"site_id"}, body = {"sourceCode", "integrityHash", "canCopy", "version", "displayName"} },
    ["webflow.publish_item"] = { method = "POST", url = "https://api.webflow.com/v2/collections/{collection_id}/items/publish", path = {"collection_id"} },
    ["webflow.refund_order"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/orders/{order_id}/refund", path = {"site_id", "order_id"}, body = {"reason"} },
    ["webflow.remove_webhook"] = { method = "DELETE", url = "https://api.webflow.com/v2/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["webflow.replace_custom_font_file"] = { method = "PUT", url = "https://api.webflow.com/v2/sites/{site_id}/custom_fonts/{font_id}/file", path = {"site_id", "font_id"}, body = {"fileName", "fileHash", "axes"} },
    ["webflow.replace_robots_txt"] = { method = "PUT", url = "https://api.webflow.com/v2/sites/{site_id}/robots_txt", path = {"site_id"}, body = {"rules", "sitemap"} },
    ["webflow.resolve_comment_thread"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/comments/{comment_thread_id}", path = {"site_id", "comment_thread_id"}, body = {"resolved"} },
    ["webflow.set_well_known"] = { method = "PUT", url = "https://api.webflow.com/v2/sites/{site_id}/well_known", path = {"site_id"}, body = {"fileName", "fileData", "contentType"} },
    ["webflow.site_publish"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/publish", path = {"site_id"}, body = {"customDomains", "publishToWebflowSubdomain", "pageId"} },
    ["webflow.unfulfill_order"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/orders/{order_id}/unfulfill", path = {"site_id", "order_id"} },
    ["webflow.update_component_content"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/components/{component_id}/dom", path = {"site_id", "component_id"}, query = {"localeId", "branchId"}, body = {"nodes"} },
    ["webflow.update_component_properties"] = { method = "POST", url = "https://api.webflow.com/v2/sites/{site_id}/components/{component_id}/properties", path = {"site_id", "component_id"}, query = {"localeId", "branchId"}, body = {"properties"} },
    ["webflow.update_custom_font"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/custom_fonts/{font_id}", path = {"site_id", "font_id"}, body = {"fontFamily", "weight", "italic", "fontDisplay"} },
    ["webflow.update_field"] = { method = "PATCH", url = "https://api.webflow.com/v2/collections/{collection_id}/fields/{field_id}", path = {"collection_id", "field_id"}, body = {"isRequired", "displayName", "helpText"} },
    ["webflow.update_inventory"] = { method = "PATCH", url = "https://api.webflow.com/v2/collections/{sku_collection_id}/items/{sku_id}/inventory", path = {"sku_collection_id", "sku_id"}, body = {"inventoryType", "updateQuantity", "quantity"} },
    ["webflow.update_item"] = { method = "PATCH", url = "https://api.webflow.com/v2/collections/{collection_id}/items/{item_id}", path = {"collection_id", "item_id"}, query = {"skipInvalidFiles"}, body = {"id", "cmsLocaleId", "lastPublished", "lastUpdated", "createdOn", "isArchived", "isDraft", "fieldData"} },
    ["webflow.update_item_live"] = { method = "PATCH", url = "https://api.webflow.com/v2/collections/{collection_id}/items/{item_id}/live", path = {"collection_id", "item_id"}, query = {"skipInvalidFiles"}, body = {"id", "cmsLocaleId", "lastPublished", "lastUpdated", "createdOn", "isArchived", "isDraft", "fieldData"} },
    ["webflow.update_items"] = { method = "PATCH", url = "https://api.webflow.com/v2/collections/{collection_id}/items", path = {"collection_id"}, query = {"skipInvalidFiles"}, body = {"items"} },
    ["webflow.update_items_live"] = { method = "PATCH", url = "https://api.webflow.com/v2/collections/{collection_id}/items/live", path = {"collection_id"}, query = {"skipInvalidFiles"}, body = {"items"} },
    ["webflow.update_order"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/orders/{order_id}", path = {"site_id", "order_id"}, body = {"comment", "shippingProvider", "shippingTracking", "shippingTrackingURL"} },
    ["webflow.update_page_settings"] = { method = "PUT", url = "https://api.webflow.com/v2/pages/{page_id}", path = {"page_id"}, query = {"localeId"}, body = {"title", "slug", "seo", "openGraph"} },
    ["webflow.update_product"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/products/{product_id}", path = {"site_id", "product_id"}, body = {"publishStatus", "product", "sku"} },
    ["webflow.update_redirect"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/redirects/{redirect_id}", path = {"site_id", "redirect_id"}, body = {"id", "fromUrl", "toUrl"} },
    ["webflow.update_robots_txt"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/robots_txt", path = {"site_id"}, body = {"rules", "sitemap"} },
    ["webflow.update_site"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}", path = {"site_id"}, body = {"name", "parentFolderId"} },
    ["webflow.update_sku"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/products/{product_id}/skus/{sku_id}", path = {"site_id", "product_id", "sku_id"}, body = {"publishStatus", "sku"} },
    ["webflow.update_static_content"] = { method = "POST", url = "https://api.webflow.com/v2/pages/{page_id}/dom", path = {"page_id"}, query = {"localeId"}, body = {"nodes"} },
    ["webflow.upsert_google_tags"] = { method = "PATCH", url = "https://api.webflow.com/v2/sites/{site_id}/integrations/google_tags", path = {"site_id"}, body = {"googleTagIds"} },
  },
}
