-- Attio — every call this API accepts, as data.
--
-- GENERATED from https://attio.com/openapi.json
-- Published on the vendor's own documentation site (https://attio.com).
-- 96 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "attio-mcp",
  name = "Attio",
  base = "https://mcp.attio.com",
  docs = "https://nango.dev/docs/api-integrations/attio-mcp",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "ATTIO_MCP_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["attio-mcp.delete_v2_activities_activity"] = { method = "DELETE", url = "https://mcp.attio.com/v2/activities/{activity}", path = {"activity"} },
    ["attio-mcp.delete_v2_activities_activity_records_record_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/activities/{activity}/records/{record_id}", path = {"activity", "record_id"} },
    ["attio-mcp.delete_v2_comments_comment_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/comments/{comment_id}", path = {"comment_id"} },
    ["attio-mcp.delete_v2_files_file_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/files/{file_id}", path = {"file_id"} },
    ["attio-mcp.delete_v2_lists_list_entries_entry_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/lists/{list}/entries/{entry_id}", path = {"list", "entry_id"} },
    ["attio-mcp.delete_v2_meetings_meeting_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/meetings/{meeting_id}", path = {"meeting_id"} },
    ["attio-mcp.delete_v2_meetings_meeting_id_call_recordings_call_recording_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/meetings/{meeting_id}/call_recordings/{call_recording_id}", path = {"meeting_id", "call_recording_id"} },
    ["attio-mcp.delete_v2_notes_note_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/notes/{note_id}", path = {"note_id"} },
    ["attio-mcp.delete_v2_objects_object"] = { method = "DELETE", url = "https://mcp.attio.com/v2/objects/{object}", path = {"object"} },
    ["attio-mcp.delete_v2_objects_object_records_record_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/objects/{object}/records/{record_id}", path = {"object", "record_id"} },
    ["attio-mcp.delete_v2_tasks_task_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/tasks/{task_id}", path = {"task_id"} },
    ["attio-mcp.delete_v2_webhooks_webhook_id"] = { method = "DELETE", url = "https://mcp.attio.com/v2/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["attio-mcp.get_v2_activities"] = { method = "GET", url = "https://mcp.attio.com/v2/activities", query = {"limit", "cursor"} },
    ["attio-mcp.get_v2_activities_activity"] = { method = "GET", url = "https://mcp.attio.com/v2/activities/{activity}", path = {"activity"} },
    ["attio-mcp.get_v2_activities_activity_records_record_id"] = { method = "GET", url = "https://mcp.attio.com/v2/activities/{activity}/records/{record_id}", path = {"activity", "record_id"} },
    ["attio-mcp.get_v2_comments_comment_id"] = { method = "GET", url = "https://mcp.attio.com/v2/comments/{comment_id}", path = {"comment_id"} },
    ["attio-mcp.get_v2_emails"] = { method = "GET", url = "https://mcp.attio.com/v2/emails", query = {"limit", "cursor", "linked_object", "linked_record_ids", "participants", "domain", "sent_after", "sent_before", "exclude_automated_participants"} },
    ["attio-mcp.get_v2_files"] = { method = "GET", url = "https://mcp.attio.com/v2/files", query = {"object", "record_id", "storage_provider", "parent_folder_id", "limit", "cursor"} },
    ["attio-mcp.get_v2_files_file_id"] = { method = "GET", url = "https://mcp.attio.com/v2/files/{file_id}", path = {"file_id"} },
    ["attio-mcp.get_v2_files_file_id_download"] = { method = "GET", url = "https://mcp.attio.com/v2/files/{file_id}/download", path = {"file_id"} },
    ["attio-mcp.get_v2_lists"] = { method = "GET", url = "https://mcp.attio.com/v2/lists" },
    ["attio-mcp.get_v2_lists_list"] = { method = "GET", url = "https://mcp.attio.com/v2/lists/{list}", path = {"list"} },
    ["attio-mcp.get_v2_lists_list_entries_entry_id"] = { method = "GET", url = "https://mcp.attio.com/v2/lists/{list}/entries/{entry_id}", path = {"list", "entry_id"} },
    ["attio-mcp.get_v2_lists_list_entries_entry_id_attributes_attribute_values"] = { method = "GET", url = "https://mcp.attio.com/v2/lists/{list}/entries/{entry_id}/attributes/{attribute}/values", path = {"list", "entry_id", "attribute"}, query = {"show_historic", "limit", "offset"} },
    ["attio-mcp.get_v2_lists_list_views"] = { method = "GET", url = "https://mcp.attio.com/v2/lists/{list}/views", path = {"list"}, query = {"show_archived", "limit", "cursor"} },
    ["attio-mcp.get_v2_meetings"] = { method = "GET", url = "https://mcp.attio.com/v2/meetings", query = {"limit", "cursor", "linked_object", "linked_record_id", "participants", "sort", "ends_from", "starts_before", "timezone"} },
    ["attio-mcp.get_v2_meetings_meeting_id"] = { method = "GET", url = "https://mcp.attio.com/v2/meetings/{meeting_id}", path = {"meeting_id"} },
    ["attio-mcp.get_v2_meetings_meeting_id_call_recordings"] = { method = "GET", url = "https://mcp.attio.com/v2/meetings/{meeting_id}/call_recordings", path = {"meeting_id"}, query = {"limit", "cursor"} },
    ["attio-mcp.get_v2_meetings_meeting_id_call_recordings_call_recording_id"] = { method = "GET", url = "https://mcp.attio.com/v2/meetings/{meeting_id}/call_recordings/{call_recording_id}", path = {"meeting_id", "call_recording_id"} },
    ["attio-mcp.get_v2_meetings_meeting_id_call_recordings_call_recording_id_transcript"] = { method = "GET", url = "https://mcp.attio.com/v2/meetings/{meeting_id}/call_recordings/{call_recording_id}/transcript", path = {"meeting_id", "call_recording_id"}, query = {"cursor"} },
    ["attio-mcp.get_v2_notes"] = { method = "GET", url = "https://mcp.attio.com/v2/notes", query = {"limit", "offset", "parent_object", "parent_record_id"} },
    ["attio-mcp.get_v2_notes_note_id"] = { method = "GET", url = "https://mcp.attio.com/v2/notes/{note_id}", path = {"note_id"} },
    ["attio-mcp.get_v2_objects"] = { method = "GET", url = "https://mcp.attio.com/v2/objects" },
    ["attio-mcp.get_v2_objects_object"] = { method = "GET", url = "https://mcp.attio.com/v2/objects/{object}", path = {"object"} },
    ["attio-mcp.get_v2_objects_object_records_record_id"] = { method = "GET", url = "https://mcp.attio.com/v2/objects/{object}/records/{record_id}", path = {"object", "record_id"} },
    ["attio-mcp.get_v2_objects_object_records_record_id_attributes_attribute_values"] = { method = "GET", url = "https://mcp.attio.com/v2/objects/{object}/records/{record_id}/attributes/{attribute}/values", path = {"object", "record_id", "attribute"}, query = {"show_historic", "limit", "offset"} },
    ["attio-mcp.get_v2_objects_object_records_record_id_entries"] = { method = "GET", url = "https://mcp.attio.com/v2/objects/{object}/records/{record_id}/entries", path = {"object", "record_id"}, query = {"limit", "offset"} },
    ["attio-mcp.get_v2_objects_object_views"] = { method = "GET", url = "https://mcp.attio.com/v2/objects/{object}/views", path = {"object"}, query = {"show_archived", "limit", "cursor"} },
    ["attio-mcp.get_v2_self"] = { method = "GET", url = "https://mcp.attio.com/v2/self" },
    ["attio-mcp.get_v2_target_identifier_attributes"] = { method = "GET", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes", path = {"target", "identifier"}, query = {"limit", "offset", "show_archived"} },
    ["attio-mcp.get_v2_target_identifier_attributes_attribute"] = { method = "GET", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes/{attribute}", path = {"target", "identifier", "attribute"} },
    ["attio-mcp.get_v2_target_identifier_attributes_attribute_options"] = { method = "GET", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes/{attribute}/options", path = {"target", "identifier", "attribute"}, query = {"show_archived"} },
    ["attio-mcp.get_v2_target_identifier_attributes_attribute_statuses"] = { method = "GET", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes/{attribute}/statuses", path = {"target", "identifier", "attribute"}, query = {"show_archived"} },
    ["attio-mcp.get_v2_tasks"] = { method = "GET", url = "https://mcp.attio.com/v2/tasks", query = {"limit", "offset", "sort", "linked_object", "linked_record_id", "assignee", "is_completed"} },
    ["attio-mcp.get_v2_tasks_task_id"] = { method = "GET", url = "https://mcp.attio.com/v2/tasks/{task_id}", path = {"task_id"} },
    ["attio-mcp.get_v2_threads"] = { method = "GET", url = "https://mcp.attio.com/v2/threads", query = {"record_id", "object", "entry_id", "list", "limit", "offset"} },
    ["attio-mcp.get_v2_threads_thread_id"] = { method = "GET", url = "https://mcp.attio.com/v2/threads/{thread_id}", path = {"thread_id"}, query = {"limit", "cursor", "created_after"} },
    ["attio-mcp.get_v2_webhooks"] = { method = "GET", url = "https://mcp.attio.com/v2/webhooks", query = {"limit", "offset"} },
    ["attio-mcp.get_v2_webhooks_webhook_id"] = { method = "GET", url = "https://mcp.attio.com/v2/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["attio-mcp.get_v2_workspace_members"] = { method = "GET", url = "https://mcp.attio.com/v2/workspace_members" },
    ["attio-mcp.get_v2_workspace_members_workspace_member_id"] = { method = "GET", url = "https://mcp.attio.com/v2/workspace_members/{workspace_member_id}", path = {"workspace_member_id"} },
    ["attio-mcp.patch_v2_activities_activity"] = { method = "PATCH", url = "https://mcp.attio.com/v2/activities/{activity}", path = {"activity"}, body = {"data"} },
    ["attio-mcp.patch_v2_activities_activity_records_record_id"] = { method = "PATCH", url = "https://mcp.attio.com/v2/activities/{activity}/records/{record_id}", path = {"activity", "record_id"}, body = {"data"} },
    ["attio-mcp.patch_v2_lists_list"] = { method = "PATCH", url = "https://mcp.attio.com/v2/lists/{list}", path = {"list"}, body = {"data"} },
    ["attio-mcp.patch_v2_lists_list_entries_entry_id"] = { method = "PATCH", url = "https://mcp.attio.com/v2/lists/{list}/entries/{entry_id}", path = {"list", "entry_id"}, body = {"data"} },
    ["attio-mcp.patch_v2_meetings_meeting_id"] = { method = "PATCH", url = "https://mcp.attio.com/v2/meetings/{meeting_id}", path = {"meeting_id"}, body = {"data"} },
    ["attio-mcp.patch_v2_notes_note_id"] = { method = "PATCH", url = "https://mcp.attio.com/v2/notes/{note_id}", path = {"note_id"}, body = {"data"} },
    ["attio-mcp.patch_v2_objects_object"] = { method = "PATCH", url = "https://mcp.attio.com/v2/objects/{object}", path = {"object"}, body = {"data"} },
    ["attio-mcp.patch_v2_objects_object_records_record_id"] = { method = "PATCH", url = "https://mcp.attio.com/v2/objects/{object}/records/{record_id}", path = {"object", "record_id"}, body = {"data"} },
    ["attio-mcp.patch_v2_target_identifier_attributes_attribute"] = { method = "PATCH", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes/{attribute}", path = {"target", "identifier", "attribute"}, body = {"data"} },
    ["attio-mcp.patch_v2_target_identifier_attributes_attribute_options_option"] = { method = "PATCH", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes/{attribute}/options/{option}", path = {"target", "identifier", "attribute", "option"}, body = {"data"} },
    ["attio-mcp.patch_v2_target_identifier_attributes_attribute_statuses_status"] = { method = "PATCH", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes/{attribute}/statuses/{status}", path = {"target", "identifier", "attribute", "status"}, body = {"data"} },
    ["attio-mcp.patch_v2_tasks_task_id"] = { method = "PATCH", url = "https://mcp.attio.com/v2/tasks/{task_id}", path = {"task_id"}, body = {"data"} },
    ["attio-mcp.patch_v2_webhooks_webhook_id"] = { method = "PATCH", url = "https://mcp.attio.com/v2/webhooks/{webhook_id}", path = {"webhook_id"}, body = {"data"} },
    ["attio-mcp.post_v2_activities"] = { method = "POST", url = "https://mcp.attio.com/v2/activities", body = {"data"} },
    ["attio-mcp.post_v2_activities_activity_records"] = { method = "POST", url = "https://mcp.attio.com/v2/activities/{activity}/records", path = {"activity"}, body = {"data"} },
    ["attio-mcp.post_v2_activities_activity_records_query"] = { method = "POST", url = "https://mcp.attio.com/v2/activities/{activity}/records/query", path = {"activity"}, body = {"filter", "sorts", "limit", "offset"} },
    ["attio-mcp.post_v2_comments"] = { method = "POST", url = "https://mcp.attio.com/v2/comments", body = {"data"} },
    ["attio-mcp.post_v2_files"] = { method = "POST", url = "https://mcp.attio.com/v2/files" },
    ["attio-mcp.post_v2_files_upload"] = { method = "POST", url = "https://mcp.attio.com/v2/files/upload", body = {"file", "object", "record_id", "parent_folder_id"} },
    ["attio-mcp.post_v2_lists"] = { method = "POST", url = "https://mcp.attio.com/v2/lists", body = {"data"} },
    ["attio-mcp.post_v2_lists_list_entries"] = { method = "POST", url = "https://mcp.attio.com/v2/lists/{list}/entries", path = {"list"}, body = {"data"} },
    ["attio-mcp.post_v2_lists_list_entries_query"] = { method = "POST", url = "https://mcp.attio.com/v2/lists/{list}/entries/query", path = {"list"}, body = {"filter", "filter_view_id", "sorts", "limit", "offset"} },
    ["attio-mcp.post_v2_meetings"] = { method = "POST", url = "https://mcp.attio.com/v2/meetings", body = {"data"} },
    ["attio-mcp.post_v2_meetings_meeting_id_call_recordings"] = { method = "POST", url = "https://mcp.attio.com/v2/meetings/{meeting_id}/call_recordings", path = {"meeting_id"}, body = {"data"} },
    ["attio-mcp.post_v2_notes"] = { method = "POST", url = "https://mcp.attio.com/v2/notes", body = {"data"} },
    ["attio-mcp.post_v2_objects"] = { method = "POST", url = "https://mcp.attio.com/v2/objects", body = {"data"} },
    ["attio-mcp.post_v2_objects_object_records"] = { method = "POST", url = "https://mcp.attio.com/v2/objects/{object}/records", path = {"object"}, body = {"data"} },
    ["attio-mcp.post_v2_objects_object_records_merge"] = { method = "POST", url = "https://mcp.attio.com/v2/objects/{object}/records/merge", path = {"object"}, body = {"data"} },
    ["attio-mcp.post_v2_objects_object_records_query"] = { method = "POST", url = "https://mcp.attio.com/v2/objects/{object}/records/query", path = {"object"}, body = {"filter", "filter_view_id", "sorts", "limit", "offset"} },
    ["attio-mcp.post_v2_objects_records_search"] = { method = "POST", url = "https://mcp.attio.com/v2/objects/records/search", body = {"query", "limit", "objects", "request_as"} },
    ["attio-mcp.post_v2_sequences_unsubscribed_emails"] = { method = "POST", url = "https://mcp.attio.com/v2/sequences/unsubscribed_emails", body = {"data"} },
    ["attio-mcp.post_v2_sql"] = { method = "POST", url = "https://mcp.attio.com/v2/sql", body = {"sql"} },
    ["attio-mcp.post_v2_target_identifier_attributes"] = { method = "POST", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes", path = {"target", "identifier"}, body = {"data"} },
    ["attio-mcp.post_v2_target_identifier_attributes_attribute_options"] = { method = "POST", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes/{attribute}/options", path = {"target", "identifier", "attribute"}, body = {"data"} },
    ["attio-mcp.post_v2_target_identifier_attributes_attribute_statuses"] = { method = "POST", url = "https://mcp.attio.com/v2/{target}/{identifier}/attributes/{attribute}/statuses", path = {"target", "identifier", "attribute"}, body = {"data"} },
    ["attio-mcp.post_v2_tasks"] = { method = "POST", url = "https://mcp.attio.com/v2/tasks", body = {"data"} },
    ["attio-mcp.post_v2_webhooks"] = { method = "POST", url = "https://mcp.attio.com/v2/webhooks", body = {"data"} },
    ["attio-mcp.put_v2_activities_activity_records_record_id"] = { method = "PUT", url = "https://mcp.attio.com/v2/activities/{activity}/records/{record_id}", path = {"activity", "record_id"}, body = {"data"} },
    ["attio-mcp.put_v2_lists_list_entries"] = { method = "PUT", url = "https://mcp.attio.com/v2/lists/{list}/entries", path = {"list"}, body = {"data"} },
    ["attio-mcp.put_v2_lists_list_entries_entry_id"] = { method = "PUT", url = "https://mcp.attio.com/v2/lists/{list}/entries/{entry_id}", path = {"list", "entry_id"}, body = {"data"} },
    ["attio-mcp.put_v2_lists_list_entries_entry_id_attributes_attribute_values"] = { method = "PUT", url = "https://mcp.attio.com/v2/lists/{list}/entries/{entry_id}/attributes/{attribute}/values", path = {"list", "entry_id", "attribute"}, body = {"data"} },
    ["attio-mcp.put_v2_meetings_meeting_id"] = { method = "PUT", url = "https://mcp.attio.com/v2/meetings/{meeting_id}", path = {"meeting_id"}, body = {"data"} },
    ["attio-mcp.put_v2_objects_object_records"] = { method = "PUT", url = "https://mcp.attio.com/v2/objects/{object}/records", path = {"object"}, query = {"matching_attribute"}, body = {"data"} },
    ["attio-mcp.put_v2_objects_object_records_record_id"] = { method = "PUT", url = "https://mcp.attio.com/v2/objects/{object}/records/{record_id}", path = {"object", "record_id"}, body = {"data"} },
    ["attio-mcp.put_v2_objects_object_records_record_id_attributes_attribute_values"] = { method = "PUT", url = "https://mcp.attio.com/v2/objects/{object}/records/{record_id}/attributes/{attribute}/values", path = {"object", "record_id", "attribute"}, body = {"data"} },
  },
}
