-- CompanyCam — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/CompanyCam/openapi-spec/main/openapi.yaml
-- Published by CompanyCam, the vendor's own GitHub organisation.
-- 62 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "companycam",
  name = "CompanyCam",
  base = "https://api.companycam.com",
  docs = "https://nango.dev/docs/integrations/all/companycam",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "COMPANYCAM_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["companycam.archive_project"] = { method = "PATCH", url = "https://api.companycam.com/projects/{id}/archive", path = {"id"} },
    ["companycam.assign_user_to_project"] = { method = "PUT", url = "https://api.companycam.com/projects/{project_id}/assigned_users/{user_id}", path = {"project_id", "user_id"}, header = {"X-CompanyCam-User"} },
    ["companycam.create_group"] = { method = "POST", url = "https://api.companycam.com/groups", header = {"X-CompanyCam-User"}, body = {"group"} },
    ["companycam.create_invitation"] = { method = "POST", url = "https://api.companycam.com/projects/{project_id}/invitations", path = {"project_id"}, header = {"X-CompanyCam-User"} },
    ["companycam.create_photo_comment"] = { method = "POST", url = "https://api.companycam.com/photos/{photo_id}/comments", path = {"photo_id"}, header = {"X-CompanyCam-User"}, body = {"comment"} },
    ["companycam.create_photo_tags"] = { method = "POST", url = "https://api.companycam.com/photos/{photo_id}/tags", path = {"photo_id"}, body = {"tags"} },
    ["companycam.create_project"] = { method = "POST", url = "https://api.companycam.com/projects", header = {"X-CompanyCam-User"}, body = {"name", "address", "coordinates", "geofence", "primary_contact"} },
    ["companycam.create_project_checklist"] = { method = "POST", url = "https://api.companycam.com/projects/{project_id}/checklists", path = {"project_id"}, header = {"X-CompanyCam-User"}, body = {"checklist_template_id"} },
    ["companycam.create_project_comment"] = { method = "POST", url = "https://api.companycam.com/projects/{project_id}/comments", path = {"project_id"}, header = {"X-CompanyCam-User"}, body = {"comment"} },
    ["companycam.create_project_document"] = { method = "POST", url = "https://api.companycam.com/projects/{project_id}/documents", path = {"project_id"}, header = {"X-CompanyCam-User"}, body = {"document"} },
    ["companycam.create_project_labels"] = { method = "POST", url = "https://api.companycam.com/projects/{project_id}/labels", path = {"project_id"}, body = {"project"} },
    ["companycam.create_project_photo"] = { method = "POST", url = "https://api.companycam.com/projects/{project_id}/photos", path = {"project_id"}, header = {"X-CompanyCam-User"}, body = {"photo"} },
    ["companycam.create_tag"] = { method = "POST", url = "https://api.companycam.com/tags", body = {"tag"} },
    ["companycam.create_user"] = { method = "POST", url = "https://api.companycam.com/users", header = {"X-CompanyCam-User"}, body = {"user"} },
    ["companycam.create_webhook"] = { method = "POST", url = "https://api.companycam.com/webhooks", body = {"url", "scopes", "enabled"} },
    ["companycam.delete_group"] = { method = "DELETE", url = "https://api.companycam.com/groups/{id}", path = {"id"} },
    ["companycam.delete_photo"] = { method = "DELETE", url = "https://api.companycam.com/photos/{id}", path = {"id"}, header = {"X-CompanyCam-User"} },
    ["companycam.delete_project"] = { method = "DELETE", url = "https://api.companycam.com/projects/{id}", path = {"id"} },
    ["companycam.delete_project_label"] = { method = "DELETE", url = "https://api.companycam.com/projects/{project_id}/labels/{id}", path = {"id", "project_id"} },
    ["companycam.delete_tag"] = { method = "DELETE", url = "https://api.companycam.com/tags/{id}", path = {"id"} },
    ["companycam.delete_user"] = { method = "DELETE", url = "https://api.companycam.com/users/{id}", path = {"id"}, header = {"X-CompanyCam-User"} },
    ["companycam.delete_webhook"] = { method = "DELETE", url = "https://api.companycam.com/webhooks/{id}", path = {"id"} },
    ["companycam.get_current_company"] = { method = "GET", url = "https://api.companycam.com/company" },
    ["companycam.get_current_user"] = { method = "GET", url = "https://api.companycam.com/users/current" },
    ["companycam.get_group"] = { method = "GET", url = "https://api.companycam.com/groups/{id}", path = {"id"} },
    ["companycam.get_photo"] = { method = "GET", url = "https://api.companycam.com/photos/{id}", path = {"id"} },
    ["companycam.get_project"] = { method = "GET", url = "https://api.companycam.com/projects/{id}", path = {"id"} },
    ["companycam.get_project_checklist"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/checklists/{id}", path = {"project_id", "id"} },
    ["companycam.get_tag"] = { method = "GET", url = "https://api.companycam.com/tags/{id}", path = {"id"} },
    ["companycam.get_user"] = { method = "GET", url = "https://api.companycam.com/users/{id}", path = {"id"} },
    ["companycam.get_video"] = { method = "GET", url = "https://api.companycam.com/videos/{id}", path = {"id"} },
    ["companycam.get_webhook"] = { method = "GET", url = "https://api.companycam.com/webhooks/{id}", path = {"id"} },
    ["companycam.list_checklist_templates"] = { method = "GET", url = "https://api.companycam.com/templates/checklists" },
    ["companycam.list_checklists"] = { method = "GET", url = "https://api.companycam.com/checklists", query = {"page", "per_page", "completed"} },
    ["companycam.list_groups"] = { method = "GET", url = "https://api.companycam.com/groups", query = {"page", "per_page"} },
    ["companycam.list_photo_comments"] = { method = "GET", url = "https://api.companycam.com/photos/{photo_id}/comments", path = {"photo_id"}, query = {"page", "per_page"} },
    ["companycam.list_photo_tags"] = { method = "GET", url = "https://api.companycam.com/photos/{photo_id}/tags", path = {"photo_id"}, query = {"page", "per_page"} },
    ["companycam.list_photos"] = { method = "GET", url = "https://api.companycam.com/photos", query = {"page", "per_page", "after", "before", "start_date", "end_date", "project_ids", "user_ids", "group_ids", "tag_ids"} },
    ["companycam.list_project_assigned_users"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/assigned_users", path = {"project_id"}, query = {"page", "per_page"} },
    ["companycam.list_project_checklists"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/checklists", path = {"project_id"} },
    ["companycam.list_project_collaborators"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/collaborators", path = {"project_id"}, query = {"page", "per_page"} },
    ["companycam.list_project_comments"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/comments", path = {"project_id"}, query = {"page", "per_page"} },
    ["companycam.list_project_documents"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/documents", path = {"project_id"}, query = {"page", "per_page"} },
    ["companycam.list_project_invitations"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/invitations", path = {"project_id"}, query = {"page", "per_page"} },
    ["companycam.list_project_labels"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/labels", path = {"project_id"}, query = {"page", "per_page"} },
    ["companycam.list_project_photos"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/photos", path = {"project_id"}, query = {"page", "per_page", "after", "before", "start_date", "end_date", "user_ids", "group_ids", "tag_ids"} },
    ["companycam.list_project_videos"] = { method = "GET", url = "https://api.companycam.com/projects/{project_id}/videos", path = {"project_id"}, query = {"page", "per_page", "start_date", "end_date", "user_ids", "group_ids", "tag_ids"} },
    ["companycam.list_projects"] = { method = "GET", url = "https://api.companycam.com/projects", query = {"page", "per_page", "query", "modified_since", "status"} },
    ["companycam.list_tags"] = { method = "GET", url = "https://api.companycam.com/tags", query = {"page", "per_page"} },
    ["companycam.list_users"] = { method = "GET", url = "https://api.companycam.com/users", query = {"page", "per_page"} },
    ["companycam.list_videos"] = { method = "GET", url = "https://api.companycam.com/videos", query = {"page", "per_page", "start_date", "end_date", "project_ids", "user_ids", "group_ids", "tag_ids"} },
    ["companycam.list_webhooks"] = { method = "GET", url = "https://api.companycam.com/webhooks", query = {"page", "per_page"} },
    ["companycam.remove_user_from_project"] = { method = "DELETE", url = "https://api.companycam.com/projects/{project_id}/assigned_users/{user_id}", path = {"project_id", "user_id"}, header = {"X-CompanyCam-User"} },
    ["companycam.restore_project"] = { method = "PUT", url = "https://api.companycam.com/projects/{id}/restore", path = {"id"} },
    ["companycam.update_group"] = { method = "PUT", url = "https://api.companycam.com/groups/{id}", path = {"id"}, body = {"group"} },
    ["companycam.update_photo"] = { method = "PUT", url = "https://api.companycam.com/photos/{id}", path = {"id"}, body = {"photo"} },
    ["companycam.update_photo_description"] = { method = "POST", url = "https://api.companycam.com/photos/{photo_id}/descriptions", path = {"photo_id"}, body = {"description"} },
    ["companycam.update_project"] = { method = "PUT", url = "https://api.companycam.com/projects/{id}", path = {"id"}, body = {"name", "address", "coordinates", "geofence"} },
    ["companycam.update_project_notepad"] = { method = "PUT", url = "https://api.companycam.com/projects/{project_id}/notepad", path = {"project_id"}, body = {"notepad"} },
    ["companycam.update_tag"] = { method = "PUT", url = "https://api.companycam.com/tags/{id}", path = {"id"}, body = {"tag"} },
    ["companycam.update_user"] = { method = "PUT", url = "https://api.companycam.com/users/{id}", path = {"id"}, header = {"X-CompanyCam-User"}, body = {"first_name", "last_name", "email_address", "phone_number", "password"} },
    ["companycam.update_webhook"] = { method = "PUT", url = "https://api.companycam.com/webhooks/{id}", path = {"id"}, body = {"url", "scopes", "enabled"} },
  },
}
