-- Close — every call this API accepts, as data.
--
-- GENERATED from https://developer.close.com/openapi.json
-- Published on the vendor's own documentation site (https://developer.close.com).
-- 302 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "close",
  name = "Close",
  base = "https://api.close.com/api",
  docs = "https://nango.dev/docs/integrations/all/close",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "CLOSE_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["close.activities_calls_create"] = { method = "POST", url = "https://api.close.com/api/v1/activity/call/", body = {"activity_at", "contact_id", "conversation_type_id", "created_by", "date_created", "direction", "duration", "lead_id", "note", "note_html", "organization_id", "outcome_id", "phone", "playbook_id", "quality_info", "recording_url", "source", "status", "user_id", "voicemail_url"} },
    ["close.activities_calls_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/call/{id}/", path = {"id"} },
    ["close.activities_calls_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/call/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_calls_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/call/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_calls_update"] = { method = "PUT", url = "https://api.close.com/api/v1/activity/call/{id}/", path = {"id"}, body = {"activity_at", "contact_id", "conversation_type_id", "duration", "lead_id", "note", "note_html", "outcome_id", "phone", "playbook_id", "quality_info", "recording_url", "status", "user_id", "voicemail_url"} },
    ["close.activities_creations_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/created/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_creations_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/created/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_custom_activities_create"] = { method = "POST", url = "https://api.close.com/api/v1/activity/custom/", body = {"activity_at", "contact_id", "created_by", "custom_activity_type_id", "date_created", "lead_id", "organization_id", "pinned", "status", "user_id"} },
    ["close.activities_custom_activities_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/custom/{id}/", path = {"id"} },
    ["close.activities_custom_activities_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/custom/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_custom_activities_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/custom/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "custom_activity_type_id", "custom_activity_type_id__in", "_fields"} },
    ["close.activities_custom_activities_update"] = { method = "PUT", url = "https://api.close.com/api/v1/activity/custom/{id}/", path = {"id"}, body = {"activity_at", "contact_id", "pinned", "status"} },
    ["close.activities_email_threads_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/emailthread/{id}/", path = {"id"} },
    ["close.activities_email_threads_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/emailthread/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_email_threads_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/emailthread/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_emails_create"] = { method = "POST", url = "https://api.close.com/api/v1/activity/email/", body = {"activity_at", "attachments", "bcc", "body_html", "body_text", "cc", "contact_id", "created_by", "date_created", "email_account_id", "followup_date", "followup_sequence_add_cc_bcc", "followup_sequence_delay", "followup_sequence_id", "in_reply_to_id", "lead_id", "opens", "organization_id", "sender", "status", "subject", "template_id", "to", "user_id"} },
    ["close.activities_emails_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/email/{id}/", path = {"id"} },
    ["close.activities_emails_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/email/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_emails_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/email/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_emails_update"] = { method = "PUT", url = "https://api.close.com/api/v1/activity/email/{id}/", path = {"id"}, body = {"activity_at", "attachments", "bcc", "body_html", "body_text", "cc", "contact_id", "email_account_id", "followup_date", "followup_sequence_add_cc_bcc", "followup_sequence_delay", "followup_sequence_id", "in_reply_to_id", "opens", "sender", "status", "subject", "template_id", "to", "user_id"} },
    ["close.activities_form_submissions_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/form_submission/{id}/", path = {"id"} },
    ["close.activities_form_submissions_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/form_submission/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_form_submissions_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/form_submission/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "lead_id__in", "user_id__in", "contact_id__in", "_type__in", "form_id", "form_id__in", "_fields"} },
    ["close.activities_import_updates_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/import_update/{id}/", path = {"id"} },
    ["close.activities_import_updates_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/import_update/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_import_updates_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/import_update/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_lead_merges_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/lead_merge/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_lead_merges_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/lead_merge/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_lead_status_changes_create"] = { method = "POST", url = "https://api.close.com/api/v1/activity/status_change/lead/" },
    ["close.activities_lead_status_changes_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/status_change/lead/{id}/", path = {"id"} },
    ["close.activities_lead_status_changes_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/status_change/lead/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_lead_status_changes_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/status_change/lead/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "lead_id__in", "user_id__in", "contact_id__in", "_type__in", "_fields", "_order_by"} },
    ["close.activities_meetings_create_integration"] = { method = "POST", url = "https://api.close.com/api/v1/activity/meeting/{id}/integration/", path = {"id"} },
    ["close.activities_meetings_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/meeting/{id}/", path = {"id"} },
    ["close.activities_meetings_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/meeting/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_meetings_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/meeting/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_meetings_update"] = { method = "PUT", url = "https://api.close.com/api/v1/activity/meeting/{id}/", path = {"id"} },
    ["close.activities_notes_create"] = { method = "POST", url = "https://api.close.com/api/v1/activity/note/", body = {"activity_at", "attachments", "contact_id", "created_by", "date_created", "lead_id", "note", "note_html", "organization_id", "pinned", "title", "user_id"} },
    ["close.activities_notes_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/note/{id}/", path = {"id"} },
    ["close.activities_notes_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/note/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_notes_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/note/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_notes_update"] = { method = "PUT", url = "https://api.close.com/api/v1/activity/note/{id}/", path = {"id"}, body = {"activity_at", "attachments", "contact_id", "note", "note_html", "pinned", "title"} },
    ["close.activities_opportunity_status_changes_create"] = { method = "POST", url = "https://api.close.com/api/v1/activity/status_change/opportunity/" },
    ["close.activities_opportunity_status_changes_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/status_change/opportunity/{id}/", path = {"id"} },
    ["close.activities_opportunity_status_changes_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/status_change/opportunity/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_opportunity_status_changes_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/status_change/opportunity/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "opportunity_id", "_fields"} },
    ["close.activities_sms_create"] = { method = "POST", url = "https://api.close.com/api/v1/activity/sms/", query = {"send_to_inbox"}, body = {"activity_at", "attachments", "caller_id_mode", "contact_id", "created_by", "date_created", "direction", "lead_id", "local_phone", "organization_id", "remote_phone", "source", "status", "template_id", "text", "user_id"} },
    ["close.activities_sms_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/sms/{id}/", path = {"id"} },
    ["close.activities_sms_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/sms/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_sms_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/sms/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_sms_update"] = { method = "PUT", url = "https://api.close.com/api/v1/activity/sms/{id}/", path = {"id"}, body = {"activity_at", "attachments", "caller_id_mode", "contact_id", "lead_id", "local_phone", "remote_phone", "status", "template_id", "text", "user_id"} },
    ["close.activities_task_completions_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/task_completed/{id}/", path = {"id"} },
    ["close.activities_task_completions_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/task_completed/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_task_completions_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/task_completed/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "_fields"} },
    ["close.activities_whatsapp_messages_create"] = { method = "POST", url = "https://api.close.com/api/v1/activity/whatsapp_message/", query = {"send_to_inbox"}, body = {"activity_at", "attachments", "contact_id", "direction", "external_whatsapp_message_id", "integration_link", "lead_id", "local_phone", "message_markdown", "remote_phone", "response_to_id", "user_id"} },
    ["close.activities_whatsapp_messages_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/activity/whatsapp_message/{id}/", path = {"id"} },
    ["close.activities_whatsapp_messages_get"] = { method = "GET", url = "https://api.close.com/api/v1/activity/whatsapp_message/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.activities_whatsapp_messages_list"] = { method = "GET", url = "https://api.close.com/api/v1/activity/whatsapp_message/", query = {"_limit", "_skip", "id__in", "lead_id", "contact_id", "user_id", "organization_id", "_type", "date_created__gte", "date_created__lte", "date_created__gt", "date_created__lt", "activity_at__gte", "activity_at__lte", "activity_at__gt", "activity_at__lt", "external_whatsapp_message_id", "_fields"} },
    ["close.activities_whatsapp_messages_update"] = { method = "PUT", url = "https://api.close.com/api/v1/activity/whatsapp_message/{id}/", path = {"id"}, body = {"activity_at", "attachments", "contact_id", "direction", "integration_link", "local_phone", "message_markdown", "remote_phone", "response_to_id", "user_id"} },
    ["close.blocked_phone_numbers_create"] = { method = "POST", url = "https://api.close.com/api/v1/blocked_phone_number/", body = {"phone", "reason"} },
    ["close.blocked_phone_numbers_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/blocked_phone_number/{id}/", path = {"id"} },
    ["close.blocked_phone_numbers_get"] = { method = "GET", url = "https://api.close.com/api/v1/blocked_phone_number/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.blocked_phone_numbers_get_settings"] = { method = "GET", url = "https://api.close.com/api/v1/blocked_phone_number/settings/" },
    ["close.blocked_phone_numbers_list"] = { method = "GET", url = "https://api.close.com/api/v1/blocked_phone_number/", query = {"_limit", "_skip", "_fields"} },
    ["close.blocked_phone_numbers_update"] = { method = "PUT", url = "https://api.close.com/api/v1/blocked_phone_number/{id}/", path = {"id"}, body = {"reason"} },
    ["close.blocked_phone_numbers_update_settings"] = { method = "PUT", url = "https://api.close.com/api/v1/blocked_phone_number/settings/", body = {"reject_anonymous_inbound_calls"} },
    ["close.bulk_actions_delete_create"] = { method = "POST", url = "https://api.close.com/api/v1/bulk_action/delete/" },
    ["close.bulk_actions_delete_get"] = { method = "GET", url = "https://api.close.com/api/v1/bulk_action/delete/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.bulk_actions_delete_list"] = { method = "GET", url = "https://api.close.com/api/v1/bulk_action/delete/", query = {"_limit", "_skip", "_fields"} },
    ["close.bulk_actions_edit_create"] = { method = "POST", url = "https://api.close.com/api/v1/bulk_action/edit/" },
    ["close.bulk_actions_edit_get"] = { method = "GET", url = "https://api.close.com/api/v1/bulk_action/edit/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.bulk_actions_edit_list"] = { method = "GET", url = "https://api.close.com/api/v1/bulk_action/edit/", query = {"_limit", "_skip", "_fields"} },
    ["close.bulk_actions_email_create"] = { method = "POST", url = "https://api.close.com/api/v1/bulk_action/email/" },
    ["close.bulk_actions_email_get"] = { method = "GET", url = "https://api.close.com/api/v1/bulk_action/email/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.bulk_actions_email_list"] = { method = "GET", url = "https://api.close.com/api/v1/bulk_action/email/", query = {"_limit", "_skip", "_fields", "template_id"} },
    ["close.bulk_actions_sequence_subscriptions_create"] = { method = "POST", url = "https://api.close.com/api/v1/bulk_action/sequence_subscription/" },
    ["close.bulk_actions_sequence_subscriptions_get"] = { method = "GET", url = "https://api.close.com/api/v1/bulk_action/sequence_subscription/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.bulk_actions_sequence_subscriptions_list"] = { method = "GET", url = "https://api.close.com/api/v1/bulk_action/sequence_subscription/", query = {"_limit", "_skip", "_fields"} },
    ["close.comments_create"] = { method = "POST", url = "https://api.close.com/api/v1/comment/", body = {"body", "object_id"} },
    ["close.comments_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/comment/{id}/", path = {"id"} },
    ["close.comments_get"] = { method = "GET", url = "https://api.close.com/api/v1/comment/{id}/", path = {"id"} },
    ["close.comments_get_thread"] = { method = "GET", url = "https://api.close.com/api/v1/comment_thread/{id}/", path = {"id"} },
    ["close.comments_list"] = { method = "GET", url = "https://api.close.com/api/v1/comment/", query = {"thread_id", "object_id"} },
    ["close.comments_list_threads"] = { method = "GET", url = "https://api.close.com/api/v1/comment_thread/", query = {"_limit", "_skip", "ids", "object_ids"} },
    ["close.comments_update"] = { method = "PUT", url = "https://api.close.com/api/v1/comment/{id}/", path = {"id"}, body = {"body"} },
    ["close.connected_accounts_get"] = { method = "GET", url = "https://api.close.com/api/v1/connected_account/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.connected_accounts_list"] = { method = "GET", url = "https://api.close.com/api/v1/connected_account/", query = {"_fields", "user_id"} },
    ["close.contacts_create"] = { method = "POST", url = "https://api.close.com/api/v1/contact/", query = {"_fields"}, body = {"created_by", "date_created", "emails", "lead_id", "name", "phones", "timezone", "title", "urls"} },
    ["close.contacts_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/contact/{id}/", path = {"id"} },
    ["close.contacts_get"] = { method = "GET", url = "https://api.close.com/api/v1/contact/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.contacts_list"] = { method = "GET", url = "https://api.close.com/api/v1/contact/", query = {"_limit", "_skip", "_fields", "lead_id"} },
    ["close.contacts_update"] = { method = "PUT", url = "https://api.close.com/api/v1/contact/{id}/", path = {"id"}, query = {"_fields"}, body = {"emails", "lead_id", "name", "phones", "timezone", "title", "urls"} },
    ["close.custom_activity_types_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_activity/" },
    ["close.custom_activity_types_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_activity/{id}/", path = {"id"} },
    ["close.custom_activity_types_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_activity/{id}/", path = {"id"} },
    ["close.custom_activity_types_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_activity/" },
    ["close.custom_activity_types_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_activity/{id}/", path = {"id"} },
    ["close.custom_field_schemas_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field_schema/{object_type}/", path = {"object_type"} },
    ["close.custom_field_schemas_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_field_schema/{object_type}/", path = {"object_type"} },
    ["close.custom_fields_activity_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_field/activity/" },
    ["close.custom_fields_activity_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_field/activity/{id}/", path = {"id"} },
    ["close.custom_fields_activity_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/activity/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.custom_fields_activity_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/activity/", query = {"_limit", "_skip", "_fields"} },
    ["close.custom_fields_activity_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_field/activity/{id}/", path = {"id"} },
    ["close.custom_fields_contact_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_field/contact/" },
    ["close.custom_fields_contact_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_field/contact/{id}/", path = {"id"} },
    ["close.custom_fields_contact_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/contact/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.custom_fields_contact_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/contact/", query = {"_limit", "_skip", "_fields"} },
    ["close.custom_fields_contact_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_field/contact/{id}/", path = {"id"} },
    ["close.custom_fields_custom_object_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_field/custom_object_type/" },
    ["close.custom_fields_custom_object_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_field/custom_object_type/{id}/", path = {"id"} },
    ["close.custom_fields_custom_object_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/custom_object_type/{id}/", path = {"id"} },
    ["close.custom_fields_custom_object_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/custom_object_type/" },
    ["close.custom_fields_custom_object_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_field/custom_object_type/{id}/", path = {"id"} },
    ["close.custom_fields_lead_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_field/lead/" },
    ["close.custom_fields_lead_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_field/lead/{id}/", path = {"id"} },
    ["close.custom_fields_lead_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/lead/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.custom_fields_lead_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/lead/", query = {"_limit", "_skip", "_fields"} },
    ["close.custom_fields_lead_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_field/lead/{id}/", path = {"id"} },
    ["close.custom_fields_opportunity_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_field/opportunity/" },
    ["close.custom_fields_opportunity_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_field/opportunity/{id}/", path = {"id"} },
    ["close.custom_fields_opportunity_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/opportunity/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.custom_fields_opportunity_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/opportunity/", query = {"_limit", "_skip", "_fields"} },
    ["close.custom_fields_opportunity_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_field/opportunity/{id}/", path = {"id"} },
    ["close.custom_fields_shared_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_field/shared/" },
    ["close.custom_fields_shared_create_association"] = { method = "POST", url = "https://api.close.com/api/v1/custom_field/shared/{scf_id}/association/", path = {"scf_id"} },
    ["close.custom_fields_shared_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_field/shared/{id}/", path = {"id"} },
    ["close.custom_fields_shared_delete_association"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_field/shared/{scf_id}/association/{object_type}/", path = {"scf_id", "object_type"} },
    ["close.custom_fields_shared_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/shared/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.custom_fields_shared_get_association"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/shared/{scf_id}/association/{object_type}/", path = {"scf_id", "object_type"} },
    ["close.custom_fields_shared_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_field/shared/", query = {"_fields"} },
    ["close.custom_fields_shared_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_field/shared/{id}/", path = {"id"} },
    ["close.custom_fields_shared_update_association"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_field/shared/{scf_id}/association/{object_type}/", path = {"scf_id", "object_type"} },
    ["close.custom_object_types_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_object_type/" },
    ["close.custom_object_types_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_object_type/{id}/", path = {"id"} },
    ["close.custom_object_types_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_object_type/{id}/", path = {"id"} },
    ["close.custom_object_types_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_object_type/" },
    ["close.custom_object_types_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_object_type/{id}/", path = {"id"} },
    ["close.custom_objects_create"] = { method = "POST", url = "https://api.close.com/api/v1/custom_object/" },
    ["close.custom_objects_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/custom_object/{id}/", path = {"id"} },
    ["close.custom_objects_get"] = { method = "GET", url = "https://api.close.com/api/v1/custom_object/{id}/", path = {"id"} },
    ["close.custom_objects_list"] = { method = "GET", url = "https://api.close.com/api/v1/custom_object/", query = {"lead_id", "custom_object_type_id"} },
    ["close.custom_objects_update"] = { method = "PUT", url = "https://api.close.com/api/v1/custom_object/{id}/", path = {"id"} },
    ["close.dialers_get"] = { method = "GET", url = "https://api.close.com/api/v1/dialer/{id}/", path = {"id"}, query = {"organization_id"} },
    ["close.dialers_list"] = { method = "GET", url = "https://api.close.com/api/v1/dialer/", query = {"organization_id", "source_type", "source_value", "status", "status__in", "user_id", "_limit", "_skip"} },
    ["close.email_templates_create"] = { method = "POST", url = "https://api.close.com/api/v1/email_template/", query = {"_fields"} },
    ["close.email_templates_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/email_template/{id}/", path = {"id"} },
    ["close.email_templates_get"] = { method = "GET", url = "https://api.close.com/api/v1/email_template/{id}/", path = {"id"}, query = {"_fields", "include_embedded"} },
    ["close.email_templates_list"] = { method = "GET", url = "https://api.close.com/api/v1/email_template/", query = {"_limit", "_skip", "is_archived", "is_shared"} },
    ["close.email_templates_render"] = { method = "GET", url = "https://api.close.com/api/v1/email_template/{id}/render/", path = {"id"}, query = {"email_account_id", "bulk_object_type", "contact_id", "contact_preference", "entry", "lead_id", "limit", "query", "results_limit", "s_query", "sender", "sort", "mode"} },
    ["close.email_templates_update"] = { method = "PUT", url = "https://api.close.com/api/v1/email_template/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.events_get"] = { method = "GET", url = "https://api.close.com/api/v1/event/{id}/", path = {"id"} },
    ["close.events_list"] = { method = "GET", url = "https://api.close.com/api/v1/event/", query = {"_limit", "_skip", "object_type", "object_id", "lead_id", "action", "user_id", "date_updated__gt", "date_updated__gte", "date_updated__lt", "date_updated__lte"} },
    ["close.exports_create_lead"] = { method = "POST", url = "https://api.close.com/api/v1/export/lead/" },
    ["close.exports_create_opportunity"] = { method = "POST", url = "https://api.close.com/api/v1/export/opportunity/" },
    ["close.exports_get"] = { method = "GET", url = "https://api.close.com/api/v1/export/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.exports_get_lead"] = { method = "GET", url = "https://api.close.com/api/v1/export/lead/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.exports_get_opportunity"] = { method = "GET", url = "https://api.close.com/api/v1/export/opportunity/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.exports_list"] = { method = "GET", url = "https://api.close.com/api/v1/export/", query = {"_limit", "_skip", "_fields"} },
    ["close.exports_list_lead"] = { method = "GET", url = "https://api.close.com/api/v1/export/lead/", query = {"_limit", "_skip", "_fields"} },
    ["close.exports_list_opportunity"] = { method = "GET", url = "https://api.close.com/api/v1/export/opportunity/", query = {"_limit", "_skip", "_fields"} },
    ["close.field_enrichment_create"] = { method = "POST", url = "https://api.close.com/api/v1/enrich_field/", body = {"field_id", "object_id", "object_type", "organization_id", "overwrite_existing_value", "set_new_value"} },
    ["close.files_create"] = { method = "POST", url = "https://api.close.com/api/v1/files/upload/", body = {"content_type", "filename"} },
    ["close.forms_fetch"] = { method = "GET", url = "https://api.close.com/api/v1/form/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.forms_list"] = { method = "GET", url = "https://api.close.com/api/v1/form/", query = {"_limit", "_skip", "is_archived", "_fields"} },
    ["close.groups_add_member"] = { method = "POST", url = "https://api.close.com/api/v1/group/{group_id}/member/", path = {"group_id"}, body = {"user_id"} },
    ["close.groups_create"] = { method = "POST", url = "https://api.close.com/api/v1/group/", query = {"_fields"}, body = {"name"} },
    ["close.groups_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/group/{id}/", path = {"id"} },
    ["close.groups_get"] = { method = "GET", url = "https://api.close.com/api/v1/group/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.groups_list"] = { method = "GET", url = "https://api.close.com/api/v1/group/", query = {"_fields"} },
    ["close.groups_remove_member"] = { method = "DELETE", url = "https://api.close.com/api/v1/group/{group_id}/member/{user_id}/", path = {"group_id", "user_id"} },
    ["close.groups_update"] = { method = "PUT", url = "https://api.close.com/api/v1/group/{id}/", path = {"id"}, query = {"_fields"}, body = {"name"} },
    ["close.integration_links_create"] = { method = "POST", url = "https://api.close.com/api/v1/integration_link/", body = {"name", "type", "url"} },
    ["close.integration_links_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/integration_link/{id}/", path = {"id"} },
    ["close.integration_links_get"] = { method = "GET", url = "https://api.close.com/api/v1/integration_link/{id}/", path = {"id"} },
    ["close.integration_links_list"] = { method = "GET", url = "https://api.close.com/api/v1/integration_link/" },
    ["close.integration_links_update"] = { method = "PUT", url = "https://api.close.com/api/v1/integration_link/{id}/", path = {"id"}, body = {"name", "type", "url"} },
    ["close.lead_statuses_create"] = { method = "POST", url = "https://api.close.com/api/v1/status/lead/", body = {"color", "label"} },
    ["close.lead_statuses_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/status/lead/{id}/", path = {"id"} },
    ["close.lead_statuses_get"] = { method = "GET", url = "https://api.close.com/api/v1/status/lead/{id}/", path = {"id"} },
    ["close.lead_statuses_list"] = { method = "GET", url = "https://api.close.com/api/v1/status/lead/" },
    ["close.lead_statuses_update"] = { method = "PUT", url = "https://api.close.com/api/v1/status/lead/{id}/", path = {"id"}, body = {"color", "label"} },
    ["close.leads_create"] = { method = "POST", url = "https://api.close.com/api/v1/lead/" },
    ["close.leads_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/lead/{id}/", path = {"id"} },
    ["close.leads_files_create"] = { method = "POST", url = "https://api.close.com/api/v1/lead/{id}/files/", path = {"id"}, body = {"content_type", "filename", "url"} },
    ["close.leads_files_list"] = { method = "GET", url = "https://api.close.com/api/v1/lead/{id}/files/", path = {"id"}, query = {"_limit", "_skip", "_fields"} },
    ["close.leads_get"] = { method = "GET", url = "https://api.close.com/api/v1/lead/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.leads_list"] = { method = "GET", url = "https://api.close.com/api/v1/lead/", query = {"_limit", "_skip", "_fields"} },
    ["close.leads_merge"] = { method = "POST", url = "https://api.close.com/api/v1/lead/merge/" },
    ["close.leads_update"] = { method = "PUT", url = "https://api.close.com/api/v1/lead/{id}/", path = {"id"} },
    ["close.memberships_bulk_update"] = { method = "PUT", url = "https://api.close.com/api/v1/membership/", body = {"auto_record_calls", "default_caller_id", "default_caller_id_mode", "hangup_recording_url", "may_workflows_impersonate", "role_id", "track_email_opens"} },
    ["close.memberships_create"] = { method = "POST", url = "https://api.close.com/api/v1/membership/", body = {"email", "role_id"} },
    ["close.memberships_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/membership/{id}/", path = {"id"} },
    ["close.memberships_get_pinned_views"] = { method = "GET", url = "https://api.close.com/api/v1/membership/{id}/pinned_views/", path = {"id"} },
    ["close.memberships_update"] = { method = "PUT", url = "https://api.close.com/api/v1/membership/{id}/", path = {"id"}, body = {"auto_record_calls", "default_caller_id", "default_caller_id_mode", "hangup_recording_url", "may_workflows_impersonate", "role_id", "track_email_opens"} },
    ["close.memberships_update_pinned_views"] = { method = "PUT", url = "https://api.close.com/api/v1/membership/{id}/pinned_views/", path = {"id"}, body = {"saved_view_ids"} },
    ["close.opportunities_create"] = { method = "POST", url = "https://api.close.com/api/v1/opportunity/", body = {"attachments", "confidence", "contact_id", "created_by", "date_created", "date_won", "lead_id", "note", "note_html", "pipeline_id", "status_id", "user_id", "value", "value_period"} },
    ["close.opportunities_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/opportunity/{id}/", path = {"id"} },
    ["close.opportunities_get"] = { method = "GET", url = "https://api.close.com/api/v1/opportunity/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.opportunities_list"] = { method = "GET", url = "https://api.close.com/api/v1/opportunity/", query = {"_limit", "_skip", "_fields", "lead_id", "organization_id", "user_id", "user_id__in", "status_id", "status_id__in", "status_type", "status_type__in", "status_label", "status_label__in", "status", "status__in", "date_won", "date_won__gte", "date_won__gt", "date_won__lte", "date_won__lt", "date_created", "date_created__gte", "date_created__gt", "date_created__lte", "date_created__lt", "date_updated", "date_updated__gte", "date_updated__gt", "date_updated__lte", "date_updated__lt", "value_period", "value_period__in", "query", "lead_query", "lead_saved_search_id", "is_stalled", "_order_by", "_group_by"} },
    ["close.opportunities_update"] = { method = "PUT", url = "https://api.close.com/api/v1/opportunity/{id}/", path = {"id"}, body = {"attachments", "confidence", "contact_id", "date_won", "note", "note_html", "status", "status_id", "user_id", "value", "value_period"} },
    ["close.opportunity_statuses_create"] = { method = "POST", url = "https://api.close.com/api/v1/status/opportunity/", query = {"_fields"}, body = {"label", "pipeline_id", "type"} },
    ["close.opportunity_statuses_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/status/opportunity/{id}/", path = {"id"} },
    ["close.opportunity_statuses_get"] = { method = "GET", url = "https://api.close.com/api/v1/status/opportunity/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.opportunity_statuses_list"] = { method = "GET", url = "https://api.close.com/api/v1/status/opportunity/", query = {"_fields"} },
    ["close.opportunity_statuses_update"] = { method = "PUT", url = "https://api.close.com/api/v1/status/opportunity/{id}/", path = {"id"}, query = {"_fields"}, body = {"label", "pipeline_id"} },
    ["close.organizations_get"] = { method = "GET", url = "https://api.close.com/api/v1/organization/{id}/", path = {"id"}, query = {"_expand"} },
    ["close.organizations_update"] = { method = "PUT", url = "https://api.close.com/api/v1/organization/{id}/", path = {"id"}, query = {"_expand"}, body = {"currency", "enable_unsubscribe_link", "lead_statuses", "name", "require_unsubscribe_link"} },
    ["close.outcomes_create"] = { method = "POST", url = "https://api.close.com/api/v1/outcome/", body = {"applies_to", "description", "name", "type"} },
    ["close.outcomes_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/outcome/{id}/", path = {"id"} },
    ["close.outcomes_get"] = { method = "GET", url = "https://api.close.com/api/v1/outcome/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.outcomes_list"] = { method = "GET", url = "https://api.close.com/api/v1/outcome/", query = {"_limit", "_skip", "_fields"} },
    ["close.outcomes_update"] = { method = "PUT", url = "https://api.close.com/api/v1/outcome/{id}/", path = {"id"}, body = {"applies_to", "description", "name", "type"} },
    ["close.phone_numbers_create"] = { method = "POST", url = "https://api.close.com/api/v1/phone_number/request/internal/", body = {"assign_to", "bundle_id", "carrier_type", "country", "prefix", "sharing", "with_mms", "with_sms"} },
    ["close.phone_numbers_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/phone_number/{id}/", path = {"id"} },
    ["close.phone_numbers_get"] = { method = "GET", url = "https://api.close.com/api/v1/phone_number/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.phone_numbers_list"] = { method = "GET", url = "https://api.close.com/api/v1/phone_number/", query = {"_limit", "_skip", "_fields", "number", "user_id", "is_group_number", "participant_user_id"} },
    ["close.phone_numbers_update"] = { method = "PUT", url = "https://api.close.com/api/v1/phone_number/{id}/", path = {"id"}, body = {"forward_to", "forward_to_enabled", "inbound_ring_duration", "label", "participants", "phone_numbers", "press_1_to_accept", "voicemail_greeting_url"} },
    ["close.pipelines_create"] = { method = "POST", url = "https://api.close.com/api/v1/pipeline/", body = {"name", "statuses"} },
    ["close.pipelines_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/pipeline/{id}/", path = {"id"} },
    ["close.pipelines_get"] = { method = "GET", url = "https://api.close.com/api/v1/pipeline/{id}/", path = {"id"} },
    ["close.pipelines_list"] = { method = "GET", url = "https://api.close.com/api/v1/pipeline/" },
    ["close.pipelines_update"] = { method = "PUT", url = "https://api.close.com/api/v1/pipeline/{id}/", path = {"id"}, body = {"name", "statuses"} },
    ["close.playbooks_archive"] = { method = "POST", url = "https://api.close.com/api/v1/playbook/{id}/archive/", path = {"id"} },
    ["close.playbooks_create"] = { method = "POST", url = "https://api.close.com/api/v1/playbook/", body = {"custom_field_ids", "description", "name", "outcome_ids", "summary_guidance"} },
    ["close.playbooks_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/playbook/{id}/", path = {"id"} },
    ["close.playbooks_get"] = { method = "GET", url = "https://api.close.com/api/v1/playbook/{id}/", path = {"id"} },
    ["close.playbooks_list"] = { method = "GET", url = "https://api.close.com/api/v1/playbook/", query = {"_limit", "_skip", "is_archived", "position__gt", "created_at__lt"} },
    ["close.playbooks_unarchive"] = { method = "POST", url = "https://api.close.com/api/v1/playbook/{id}/unarchive/", path = {"id"} },
    ["close.playbooks_update"] = { method = "PUT", url = "https://api.close.com/api/v1/playbook/{id}/", path = {"id"}, body = {"custom_field_ids", "description", "name", "outcome_ids", "summary_guidance"} },
    ["close.reporting_get_activity"] = { method = "POST", url = "https://api.close.com/api/v1/report/activity/" },
    ["close.reporting_get_custom"] = { method = "GET", url = "https://api.close.com/api/v1/report/custom/{org_id}/", path = {"org_id"}, query = {"query", "x", "y", "group_by", "transform_y", "interval", "start", "end"} },
    ["close.reporting_get_funnel_stages"] = { method = "POST", url = "https://api.close.com/api/v1/report/funnel/opportunity/stages/" },
    ["close.reporting_get_funnel_totals"] = { method = "POST", url = "https://api.close.com/api/v1/report/funnel/opportunity/totals/" },
    ["close.reporting_get_lead_statuses"] = { method = "GET", url = "https://api.close.com/api/v1/report/statuses/lead/{org_id}/", path = {"org_id"}, query = {"date_start", "date_end", "query", "smart_view_id"} },
    ["close.reporting_get_opportunity_statuses"] = { method = "GET", url = "https://api.close.com/api/v1/report/statuses/opportunity/{org_id}/", path = {"org_id"}, query = {"date_start", "date_end", "query", "smart_view_id", "user_id"} },
    ["close.reporting_get_sent_emails"] = { method = "GET", url = "https://api.close.com/api/v1/report/sent_emails/{org_id}/", path = {"org_id"}, query = {"date_start", "date_end", "user_id"} },
    ["close.reporting_list_activity_metrics"] = { method = "GET", url = "https://api.close.com/api/v1/report/activity/metrics/" },
    ["close.roles_create"] = { method = "POST", url = "https://api.close.com/api/v1/role/" },
    ["close.roles_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/role/{id}/", path = {"id"} },
    ["close.roles_get"] = { method = "GET", url = "https://api.close.com/api/v1/role/{id}/", path = {"id"} },
    ["close.roles_list"] = { method = "GET", url = "https://api.close.com/api/v1/role/" },
    ["close.roles_update"] = { method = "PUT", url = "https://api.close.com/api/v1/role/{id}/", path = {"id"} },
    ["close.scheduling_links_create"] = { method = "POST", url = "https://api.close.com/api/v1/scheduling_link/" },
    ["close.scheduling_links_create_integration"] = { method = "POST", url = "https://api.close.com/api/v1/scheduling_link/integration/" },
    ["close.scheduling_links_create_shared"] = { method = "POST", url = "https://api.close.com/api/v1/shared_scheduling_link/" },
    ["close.scheduling_links_create_shared_association"] = { method = "POST", url = "https://api.close.com/api/v1/shared_scheduling_link_association/" },
    ["close.scheduling_links_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/scheduling_link/{id}/", path = {"id"} },
    ["close.scheduling_links_delete_integration"] = { method = "DELETE", url = "https://api.close.com/api/v1/scheduling_link/integration/{source_id}/", path = {"source_id"} },
    ["close.scheduling_links_delete_shared"] = { method = "DELETE", url = "https://api.close.com/api/v1/shared_scheduling_link/{id}/", path = {"id"} },
    ["close.scheduling_links_delete_shared_association"] = { method = "POST", url = "https://api.close.com/api/v1/shared_scheduling_link_association/unmap/" },
    ["close.scheduling_links_get"] = { method = "GET", url = "https://api.close.com/api/v1/scheduling_link/{id}/", path = {"id"} },
    ["close.scheduling_links_get_shared"] = { method = "GET", url = "https://api.close.com/api/v1/shared_scheduling_link/{id}/", path = {"id"} },
    ["close.scheduling_links_list"] = { method = "GET", url = "https://api.close.com/api/v1/scheduling_link/" },
    ["close.scheduling_links_list_shared"] = { method = "GET", url = "https://api.close.com/api/v1/shared_scheduling_link/" },
    ["close.scheduling_links_update"] = { method = "PUT", url = "https://api.close.com/api/v1/scheduling_link/{id}/", path = {"id"} },
    ["close.scheduling_links_update_shared"] = { method = "PUT", url = "https://api.close.com/api/v1/shared_scheduling_link/{id}/", path = {"id"} },
    ["close.send_as_bulk_create"] = { method = "POST", url = "https://api.close.com/api/v1/send_as/bulk/" },
    ["close.send_as_create"] = { method = "POST", url = "https://api.close.com/api/v1/send_as/" },
    ["close.send_as_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/send_as/{id}/", path = {"id"} },
    ["close.send_as_delete_by_user"] = { method = "DELETE", url = "https://api.close.com/api/v1/send_as/", query = {"allowed_user_id", "allowing_user_id"} },
    ["close.send_as_get"] = { method = "GET", url = "https://api.close.com/api/v1/send_as/{id}/", path = {"id"} },
    ["close.send_as_list"] = { method = "GET", url = "https://api.close.com/api/v1/send_as/", query = {"allowed_user_id", "allowing_user_id"} },
    ["close.sequences_create"] = { method = "POST", url = "https://api.close.com/api/v1/sequence/" },
    ["close.sequences_create_subscription"] = { method = "POST", url = "https://api.close.com/api/v1/sequence_subscription/" },
    ["close.sequences_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/sequence/{id}/", path = {"id"} },
    ["close.sequences_delete_subscription"] = { method = "DELETE", url = "https://api.close.com/api/v1/sequence_subscription/{id}/", path = {"id"} },
    ["close.sequences_get"] = { method = "GET", url = "https://api.close.com/api/v1/sequence/{id}/", path = {"id"}, query = {"_limit", "_skip"} },
    ["close.sequences_get_subscription"] = { method = "GET", url = "https://api.close.com/api/v1/sequence_subscription/{id}/", path = {"id"} },
    ["close.sequences_list"] = { method = "GET", url = "https://api.close.com/api/v1/sequence/", query = {"_limit", "_skip"} },
    ["close.sequences_list_subscriptions"] = { method = "GET", url = "https://api.close.com/api/v1/sequence_subscription/", query = {"_limit", "_skip", "contact_id", "lead_id", "sequence_id"} },
    ["close.sequences_update"] = { method = "PUT", url = "https://api.close.com/api/v1/sequence/{id}/", path = {"id"} },
    ["close.sequences_update_subscription"] = { method = "PUT", url = "https://api.close.com/api/v1/sequence_subscription/{id}/", path = {"id"} },
    ["close.smart_views_create"] = { method = "POST", url = "https://api.close.com/api/v1/saved_search/" },
    ["close.smart_views_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/saved_search/{id}/", path = {"id"} },
    ["close.smart_views_get"] = { method = "GET", url = "https://api.close.com/api/v1/saved_search/{id}/", path = {"id"} },
    ["close.smart_views_list"] = { method = "GET", url = "https://api.close.com/api/v1/saved_search/", query = {"_limit", "_skip", "type", "type__in"} },
    ["close.smart_views_update"] = { method = "PUT", url = "https://api.close.com/api/v1/saved_search/{id}/", path = {"id"} },
    ["close.sms_templates_create"] = { method = "POST", url = "https://api.close.com/api/v1/sms_template/", body = {"attachments", "is_shared", "name", "text"} },
    ["close.sms_templates_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/sms_template/{id}/", path = {"id"} },
    ["close.sms_templates_get"] = { method = "GET", url = "https://api.close.com/api/v1/sms_template/{id}/", path = {"id"}, query = {"include_attachments", "include_embedded"} },
    ["close.sms_templates_list"] = { method = "GET", url = "https://api.close.com/api/v1/sms_template/", query = {"_limit", "_skip"} },
    ["close.sms_templates_update"] = { method = "PUT", url = "https://api.close.com/api/v1/sms_template/{id}/", path = {"id"}, body = {"attachments", "is_shared", "name", "status", "text"} },
    ["close.tasks_bulk_update"] = { method = "PUT", url = "https://api.close.com/api/v1/task/", query = {"assigned_to", "format", "id", "id__in", "is_complete", "lead_id", "_order_by", "organization_id", "_type", "_type__in", "view", "date", "date__lt", "date__lte", "date__gt", "date__gte", "due_date", "due_date__lt", "due_date__lte", "due_date__gt", "due_date__gte", "date_created__lt", "date_created__lte", "date_created__gt", "date_created__gte", "date_updated__lt", "date_updated__lte", "date_updated__gt", "date_updated__gte", "_fields"}, body = {"assigned_to", "date", "is_complete", "organization_id", "priority", "resolution", "text"} },
    ["close.tasks_create"] = { method = "POST", url = "https://api.close.com/api/v1/task/", query = {"_fields"} },
    ["close.tasks_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/task/{id}/", path = {"id"} },
    ["close.tasks_get"] = { method = "GET", url = "https://api.close.com/api/v1/task/{id}/", path = {"id"}, query = {"_fields"} },
    ["close.tasks_list"] = { method = "GET", url = "https://api.close.com/api/v1/task/", query = {"_limit", "_skip", "assigned_to", "format", "id", "id__in", "is_complete", "lead_id", "_order_by", "organization_id", "_type", "_type__in", "view", "date", "date__lt", "date__lte", "date__gt", "date__gte", "due_date", "due_date__lt", "due_date__lte", "due_date__gt", "due_date__gte", "date_created__lt", "date_created__lte", "date_created__gt", "date_created__gte", "date_updated__lt", "date_updated__lte", "date_updated__gt", "date_updated__gte", "_fields"} },
    ["close.tasks_update"] = { method = "PUT", url = "https://api.close.com/api/v1/task/{id}/", path = {"id"}, query = {"_fields"}, body = {"agent_config_id", "assigned_to", "contact_id", "created_by", "date", "due_date", "is_complete", "is_dateless", "lead_id", "organization_id", "priority", "resolution", "text"} },
    ["close.unsubscribed_emails_create"] = { method = "POST", url = "https://api.close.com/api/v1/unsubscribe/email/", body = {"email"} },
    ["close.unsubscribed_emails_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/unsubscribe/email/{email_address}/", path = {"email_address"} },
    ["close.unsubscribed_emails_list"] = { method = "GET", url = "https://api.close.com/api/v1/unsubscribe/email/" },
    ["close.users_get"] = { method = "GET", url = "https://api.close.com/api/v1/user/{id}/", path = {"id"}, query = {"_order_by", "_limit", "_skip"} },
    ["close.users_get_me"] = { method = "GET", url = "https://api.close.com/api/v1/me/", query = {"_fields"} },
    ["close.users_list"] = { method = "GET", url = "https://api.close.com/api/v1/user/", query = {"_order_by", "_limit", "_skip"} },
    ["close.users_list_availabilities"] = { method = "GET", url = "https://api.close.com/api/v1/user/availability/", query = {"organization_id"} },
    ["close.webhooks_create"] = { method = "POST", url = "https://api.close.com/api/v1/webhook/", body = {"events", "url", "verify_ssl"} },
    ["close.webhooks_delete"] = { method = "DELETE", url = "https://api.close.com/api/v1/webhook/{id}/", path = {"id"} },
    ["close.webhooks_get"] = { method = "GET", url = "https://api.close.com/api/v1/webhook/{id}/", path = {"id"} },
    ["close.webhooks_list"] = { method = "GET", url = "https://api.close.com/api/v1/webhook/" },
    ["close.webhooks_update"] = { method = "PUT", url = "https://api.close.com/api/v1/webhook/{id}/", path = {"id"}, body = {"events", "status", "url", "verify_ssl"} },
  },
}
