-- Cloudbeds — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/cloudbeds/openapi-specs/main/src/pms-v1.3-openapi.yaml
-- Published by cloudbeds, the vendor's own GitHub organisation.
-- 115 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "cloudbeds",
  name = "Cloudbeds",
  base = "https://api.cloudbeds.com",
  docs = "https://nango.dev/docs/api-integrations/cloudbeds",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "CLOUDBEDS_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["cloudbeds.delete_deleteAdjustment"] = { method = "DELETE", url = "https://api.cloudbeds.com/deleteAdjustment", query = {"propertyID", "reservationID", "adjustmentID"} },
    ["cloudbeds.delete_deleteGuestNote"] = { method = "DELETE", url = "https://api.cloudbeds.com/deleteGuestNote", query = {"propertyID", "guestID", "noteID"} },
    ["cloudbeds.delete_deleteReservationNote"] = { method = "DELETE", url = "https://api.cloudbeds.com/deleteReservationNote", query = {"propertyID", "reservationID", "reservationNoteID"} },
    ["cloudbeds.delete_deleteWebhook"] = { method = "DELETE", url = "https://api.cloudbeds.com/deleteWebhook", query = {"propertyIDs", "subscriptionID"} },
    ["cloudbeds.get_getAllotmentBlocks"] = { method = "GET", url = "https://api.cloudbeds.com/getAllotmentBlocks", query = {"propertyID", "allotmentBlockCode", "allotmentBlockName", "groupCode", "groupProfileID", "eventCode", "allotmentBlockStatus", "allotmentBlockType", "roomTypeID", "pageSize", "pageNumber", "startDate", "endDate", "forUpdate", "includeResources"} },
    ["cloudbeds.get_getAppPropertySettings"] = { method = "GET", url = "https://api.cloudbeds.com/getAppPropertySettings", query = {"propertyID"} },
    ["cloudbeds.get_getAppSettings"] = { method = "GET", url = "https://api.cloudbeds.com/getAppSettings", query = {"propertyID"} },
    ["cloudbeds.get_getAppState"] = { method = "GET", url = "https://api.cloudbeds.com/getAppState", query = {"propertyID"} },
    ["cloudbeds.get_getAvailableRoomTypes"] = { method = "GET", url = "https://api.cloudbeds.com/getAvailableRoomTypes", query = {"propertyIDs", "startDate", "endDate", "rooms", "adults", "children", "promoCode", "detailedRates", "includeSharedRooms", "sort", "order", "minRate", "maxRate", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getCurrencySettings"] = { method = "GET", url = "https://api.cloudbeds.com/getCurrencySettings", query = {"propertyID"} },
    ["cloudbeds.get_getCustomFields"] = { method = "GET", url = "https://api.cloudbeds.com/getCustomFields", query = {"propertyID", "customFieldID", "shortcode"} },
    ["cloudbeds.get_getDashboard"] = { method = "GET", url = "https://api.cloudbeds.com/getDashboard", query = {"propertyID", "date"} },
    ["cloudbeds.get_getEmailSchedule"] = { method = "GET", url = "https://api.cloudbeds.com/getEmailSchedule", query = {"propertyID"} },
    ["cloudbeds.get_getEmailTemplates"] = { method = "GET", url = "https://api.cloudbeds.com/getEmailTemplates", query = {"propertyID"} },
    ["cloudbeds.get_getFiles"] = { method = "GET", url = "https://api.cloudbeds.com/getFiles", query = {"propertyID", "groupCode", "sortBy", "orderBy", "name", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getGroupNotes"] = { method = "GET", url = "https://api.cloudbeds.com/getGroupNotes", query = {"propertyID", "groupCode", "pageSize", "pageNumber"} },
    ["cloudbeds.get_getGroups"] = { method = "GET", url = "https://api.cloudbeds.com/getGroups", query = {"propertyID", "groupCode", "groupProfileID", "type", "status", "createdFrom", "createdTo", "pageSize", "pageNumber"} },
    ["cloudbeds.get_getGuest"] = { method = "GET", url = "https://api.cloudbeds.com/getGuest", query = {"propertyID", "reservationID", "guestID", "includeGuestRequirements"} },
    ["cloudbeds.get_getGuestList"] = { method = "GET", url = "https://api.cloudbeds.com/getGuestList", query = {"propertyIDs", "resultsFrom", "resultsTo", "checkInFrom", "checkInTo", "checkOutFrom", "checkOutTo", "guestFirstName", "guestLastName", "guestEmail", "guestPhone", "guestCellPhone", "status", "sortBy", "includeGuestInfo", "excludeSecondaryGuests", "includeGuestRequirements", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getGuestNotes"] = { method = "GET", url = "https://api.cloudbeds.com/getGuestNotes", query = {"propertyID", "guestID"} },
    ["cloudbeds.get_getGuestsByFilter"] = { method = "GET", url = "https://api.cloudbeds.com/getGuestsByFilter", query = {"propertyIDs", "status", "reservationID", "roomID", "guestName", "checkInFrom", "checkInTo", "checkOutFrom", "checkOutTo"} },
    ["cloudbeds.get_getGuestsByStatus"] = { method = "GET", url = "https://api.cloudbeds.com/getGuestsByStatus", query = {"status", "propertyID", "resultsFrom", "resultsTo", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getGuestsModified"] = { method = "GET", url = "https://api.cloudbeds.com/getGuestsModified", query = {"propertyIDs", "inHouse", "resultsFrom", "resultsTo", "checkInFrom", "checkInTo", "checkOutFrom", "checkOutTo", "includeGuestRequirements", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getHotelDetails"] = { method = "GET", url = "https://api.cloudbeds.com/getHotelDetails", query = {"propertyID"} },
    ["cloudbeds.get_getHotels"] = { method = "GET", url = "https://api.cloudbeds.com/getHotels", query = {"propertyIDs", "propertyName", "propertyCity", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getHouseAccountList"] = { method = "GET", url = "https://api.cloudbeds.com/getHouseAccountList", query = {"propertyID"} },
    ["cloudbeds.get_getHousekeepers"] = { method = "GET", url = "https://api.cloudbeds.com/getHousekeepers", query = {"propertyID", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getHousekeepingStatus"] = { method = "GET", url = "https://api.cloudbeds.com/getHousekeepingStatus", query = {"propertyID", "roomTypeIDs", "housekeeperIDs", "roomCondition", "roomOccupied", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getItem"] = { method = "GET", url = "https://api.cloudbeds.com/getItem", query = {"propertyID", "itemID"} },
    ["cloudbeds.get_getItemCategories"] = { method = "GET", url = "https://api.cloudbeds.com/getItemCategories", query = {"propertyID"} },
    ["cloudbeds.get_getItems"] = { method = "GET", url = "https://api.cloudbeds.com/getItems", query = {"propertyID", "itemCategoryID"} },
    ["cloudbeds.get_getPackageNames"] = { method = "GET", url = "https://api.cloudbeds.com/getPackageNames", query = {"propertyID"} },
    ["cloudbeds.get_getPackages"] = { method = "GET", url = "https://api.cloudbeds.com/getPackages", query = {"propertyID"} },
    ["cloudbeds.get_getPaymentMethods"] = { method = "GET", url = "https://api.cloudbeds.com/getPaymentMethods", query = {"propertyID", "lang"} },
    ["cloudbeds.get_getPaymentsCapabilities"] = { method = "GET", url = "https://api.cloudbeds.com/getPaymentsCapabilities", query = {"propertyID"} },
    ["cloudbeds.get_getRate"] = { method = "GET", url = "https://api.cloudbeds.com/getRate", query = {"roomTypeID", "startDate", "endDate", "adults", "children", "detailedRates", "promoCode"} },
    ["cloudbeds.get_getRateJobs"] = { method = "GET", url = "https://api.cloudbeds.com/getRateJobs", query = {"jobReferenceID", "status"} },
    ["cloudbeds.get_getRatePlans"] = { method = "GET", url = "https://api.cloudbeds.com/getRatePlans", query = {"propertyIDs", "rateIDs", "roomTypeID", "promoCode", "includePromoCode", "startDate", "endDate", "adults", "children", "detailedRates", "includeSharedRooms"} },
    ["cloudbeds.get_getReservation"] = { method = "GET", url = "https://api.cloudbeds.com/getReservation", query = {"propertyID", "reservationID", "includeGuestRequirements"} },
    ["cloudbeds.get_getReservationAssignments"] = { method = "GET", url = "https://api.cloudbeds.com/getReservationAssignments", query = {"propertyID", "date"} },
    ["cloudbeds.get_getReservationNotes"] = { method = "GET", url = "https://api.cloudbeds.com/getReservationNotes", query = {"propertyID", "reservationID"} },
    ["cloudbeds.get_getReservationRoomDetails"] = { method = "GET", url = "https://api.cloudbeds.com/getReservationRoomDetails", query = {"propertyID", "subReservationID"} },
    ["cloudbeds.get_getReservations"] = { method = "GET", url = "https://api.cloudbeds.com/getReservations", query = {"propertyID", "status", "resultsFrom", "resultsTo", "modifiedFrom", "modifiedTo", "checkInFrom", "checkInTo", "checkOutFrom", "checkOutTo", "datesQueryMode", "roomID", "roomName", "roomTypeID", "includeGuestsDetails", "includeGuestRequirements", "includeCustomFields", "includeAllRooms", "sourceId", "sourceReservationId", "ratePlanId", "firstName", "lastName", "guestID", "allotmentBlockCode", "groupCode", "sortByRecent", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getReservationsWithRateDetails"] = { method = "GET", url = "https://api.cloudbeds.com/getReservationsWithRateDetails", query = {"propertyID", "resultsFrom", "resultsTo", "modifiedFrom", "modifiedTo", "sortByRecent", "reservationID", "reservationCheckOutFrom", "reservationCheckOutTo", "includeDeleted", "excludeStatuses", "includeGuestsDetails", "includeGuestRequirements", "includeCustomFields", "guestID", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getRoomBlocks"] = { method = "GET", url = "https://api.cloudbeds.com/getRoomBlocks", query = {"propertyID", "roomBlockID", "roomTypeID", "roomID", "startDate", "endDate", "pageNumber", "pageSize"} },
    ["cloudbeds.get_getRoomTypes"] = { method = "GET", url = "https://api.cloudbeds.com/getRoomTypes", query = {"propertyIDs", "roomTypeIDs", "startDate", "endDate", "adults", "children", "detailedRates", "roomTypeName", "propertyCity", "propertyName", "maxGuests", "pageNumber", "pageSize", "sort"} },
    ["cloudbeds.get_getRooms"] = { method = "GET", url = "https://api.cloudbeds.com/getRooms", query = {"propertyIDs", "roomTypeID", "roomTypeNameShort", "startDate", "endDate", "includeRoomRelations", "pageNumber", "pageSize", "sort"} },
    ["cloudbeds.get_getRoomsFeesAndTaxes"] = { method = "GET", url = "https://api.cloudbeds.com/getRoomsFeesAndTaxes", query = {"propertyID", "startDate", "endDate", "roomsTotal", "roomsCount", "adultsPerRoom", "childrenPerRoom"} },
    ["cloudbeds.get_getRoomsUnassigned"] = { method = "GET", url = "https://api.cloudbeds.com/getRoomsUnassigned", query = {"propertyIDs"} },
    ["cloudbeds.get_getSources"] = { method = "GET", url = "https://api.cloudbeds.com/getSources", query = {"propertyIDs"} },
    ["cloudbeds.get_getTaxesAndFees"] = { method = "GET", url = "https://api.cloudbeds.com/getTaxesAndFees", query = {"propertyID", "includeDeleted", "includeExpired", "includeCustomItemTaxes", "availableFor", "sourceId", "isRootSource", "isHotelCollectBooking", "productId", "addonId"} },
    ["cloudbeds.get_getUsers"] = { method = "GET", url = "https://api.cloudbeds.com/getUsers", query = {"property_ids"} },
    ["cloudbeds.get_getWebhooks"] = { method = "GET", url = "https://api.cloudbeds.com/getWebhooks", query = {"propertyID"} },
    ["cloudbeds.get_listAllotmentBlockNotes"] = { method = "GET", url = "https://api.cloudbeds.com/listAllotmentBlockNotes", query = {"propertyID", "allotmentBlockCode", "status", "pageNumber", "pageSize"} },
    ["cloudbeds.get_oauth_metadata"] = { method = "GET", url = "https://api.cloudbeds.com/oauth/metadata" },
    ["cloudbeds.get_userinfo"] = { method = "GET", url = "https://api.cloudbeds.com/userinfo", query = {"property_id", "role_details"} },
    ["cloudbeds.post_access_token"] = { method = "POST", url = "https://api.cloudbeds.com/access_token", body = {"grant_type", "client_id", "client_secret", "redirect_uri", "code", "refresh_token"} },
    ["cloudbeds.post_appendCustomItem"] = { method = "POST", url = "https://api.cloudbeds.com/appendCustomItem", body = {"propertyID", "reservationID", "houseAccountID", "groupCode", "referenceID", "subReservationID", "roomID", "items", "saleDate", "guestID", "guestName", "payments", "itemPaid"} },
    ["cloudbeds.post_createAllotmentBlock"] = { method = "POST", url = "https://api.cloudbeds.com/createAllotmentBlock", body = {"groupCode", "eventCode", "allotmentBlockName", "rateType", "ratePlanId", "allotmentType", "allotmentBlockStatus", "allowOverbooking", "autoRelease", "allotmentIntervals", "resources"} },
    ["cloudbeds.post_createAllotmentBlockNotes"] = { method = "POST", url = "https://api.cloudbeds.com/createAllotmentBlockNotes", body = {"propertyID", "allotmentBlockCode", "text"} },
    ["cloudbeds.post_deleteAllotmentBlock"] = { method = "POST", url = "https://api.cloudbeds.com/deleteAllotmentBlock", body = {"allotmentBlockCode"} },
    ["cloudbeds.post_deleteAppPropertySettings"] = { method = "POST", url = "https://api.cloudbeds.com/deleteAppPropertySettings", body = {"propertyID"} },
    ["cloudbeds.post_deleteRoomBlock"] = { method = "POST", url = "https://api.cloudbeds.com/deleteRoomBlock", body = {"propertyID", "roomBlockID"} },
    ["cloudbeds.post_patchGroup"] = { method = "POST", url = "https://api.cloudbeds.com/patchGroup", body = {"groupCode", "propertyID", "name", "type", "status", "sourceID", "address1", "address2", "city", "zip", "state"} },
    ["cloudbeds.post_patchRate"] = { method = "POST", url = "https://api.cloudbeds.com/patchRate", body = {"rates"} },
    ["cloudbeds.post_postAdjustment"] = { method = "POST", url = "https://api.cloudbeds.com/postAdjustment", body = {"propertyID", "reservationID", "type", "amount", "notes", "itemID"} },
    ["cloudbeds.post_postAppError"] = { method = "POST", url = "https://api.cloudbeds.com/postAppError", body = {"propertyID", "timestamp", "eventType", "statusCode", "description", "errorMessage", "entityType", "entityID", "userID"} },
    ["cloudbeds.post_postAppPropertySettings"] = { method = "POST", url = "https://api.cloudbeds.com/postAppPropertySettings", body = {"propertyID", "appClientID", "value"} },
    ["cloudbeds.post_postAppState"] = { method = "POST", url = "https://api.cloudbeds.com/postAppState", body = {"propertyID", "app_state"} },
    ["cloudbeds.post_postCharge"] = { method = "POST", url = "https://api.cloudbeds.com/postCharge", body = {"propertyID", "reservationID", "houseAccountID", "groupID", "accountsReceivableLedgerID", "amount", "currency", "description", "cardToken", "paymentMethodId", "isDeposit", "redirectUrl"} },
    ["cloudbeds.post_postCreditCard"] = { method = "POST", url = "https://api.cloudbeds.com/postCreditCard", body = {"propertyID", "reservationID", "cardToken", "paymentMethodId", "returnUrl"} },
    ["cloudbeds.post_postCustomField"] = { method = "POST", url = "https://api.cloudbeds.com/postCustomField", body = {"propertyID", "name", "shortcode", "applyTo", "required", "maxCharacters", "type", "displayed", "isPersonal"} },
    ["cloudbeds.post_postCustomItem"] = { method = "POST", url = "https://api.cloudbeds.com/postCustomItem", body = {"propertyID", "reservationID", "houseAccountID", "groupCode", "referenceID", "subReservationID", "roomID", "items", "saleDate", "guestID", "guestName", "payments", "itemPaid"} },
    ["cloudbeds.post_postCustomPaymentMethod"] = { method = "POST", url = "https://api.cloudbeds.com/postCustomPaymentMethod", body = {"propertyID", "method", "methodName"} },
    ["cloudbeds.post_postEmailSchedule"] = { method = "POST", url = "https://api.cloudbeds.com/postEmailSchedule", body = {"propertyID", "emailTemplateID", "scheduleName", "schedule"} },
    ["cloudbeds.post_postEmailTemplate"] = { method = "POST", url = "https://api.cloudbeds.com/postEmailTemplate", body = {"propertyID", "emailType", "name", "from", "fromName", "subject", "body", "replyTo", "replyToName", "autofillAllLanguages", "cc", "bcc"} },
    ["cloudbeds.post_postFile"] = { method = "POST", url = "https://api.cloudbeds.com/postFile", body = {"propertyID", "file", "groupCode"} },
    ["cloudbeds.post_postGovernmentReceipt"] = { method = "POST", url = "https://api.cloudbeds.com/postGovernmentReceipt", body = {"propertyID", "reservationID", "houseAccountID", "name", "url", "amount", "identifier", "issueDate"} },
    ["cloudbeds.post_postGroupNote"] = { method = "POST", url = "https://api.cloudbeds.com/postGroupNote", body = {"propertyID", "groupCode", "groupNote"} },
    ["cloudbeds.post_postGuest"] = { method = "POST", url = "https://api.cloudbeds.com/postGuest", body = {"propertyID", "reservationID", "guestFirstName", "guestLastName", "guestGender", "guestEmail", "guestPhone", "guestCellPhone", "guestAddress1", "guestAddress2", "guestCity", "guestCountry", "guestNationality", "guestState", "guestZip", "guestBirthDate", "guestDocumentType", "guestDocumentNumber", "guestDocumentIssueDate", "guestDocumentIssuingCountry", "guestDocumentExpirationDate", "guestRequirements", "customFields", "guestNote", "reservationNote", "guestCompanyName", "guestCompanyTaxId", "guestTaxId"} },
    ["cloudbeds.post_postGuestDocument"] = { method = "POST", url = "https://api.cloudbeds.com/postGuestDocument", body = {"propertyID", "guestID", "file"} },
    ["cloudbeds.post_postGuestNote"] = { method = "POST", url = "https://api.cloudbeds.com/postGuestNote", body = {"propertyID", "guestID", "guestNote", "userID"} },
    ["cloudbeds.post_postGuestPhoto"] = { method = "POST", url = "https://api.cloudbeds.com/postGuestPhoto", body = {"guestID", "file"} },
    ["cloudbeds.post_postGuestsToRoom"] = { method = "POST", url = "https://api.cloudbeds.com/postGuestsToRoom", body = {"propertyID", "reservationID", "roomID", "guestIDs", "removeGuestIDs", "removeGuestIDsFromRoom", "removeAll", "mainGuestId"} },
    ["cloudbeds.post_postHousekeeper"] = { method = "POST", url = "https://api.cloudbeds.com/postHousekeeper", body = {"propertyID", "name"} },
    ["cloudbeds.post_postHousekeepingAssignment"] = { method = "POST", url = "https://api.cloudbeds.com/postHousekeepingAssignment", body = {"propertyID", "roomIDs", "housekeeperID"} },
    ["cloudbeds.post_postHousekeepingStatus"] = { method = "POST", url = "https://api.cloudbeds.com/postHousekeepingStatus", body = {"propertyID", "roomID", "roomCondition", "doNotDisturb", "roomComments", "refusedService", "vacantPickup"} },
    ["cloudbeds.post_postItem"] = { method = "POST", url = "https://api.cloudbeds.com/postItem", body = {"propertyID", "reservationID", "houseAccountID", "groupCode", "subReservationID", "itemID", "itemQuantity", "itemPrice", "itemNote", "itemPaid", "saleDate", "payments"} },
    ["cloudbeds.post_postItemCategory"] = { method = "POST", url = "https://api.cloudbeds.com/postItemCategory", body = {"propertyID", "categoryName", "categoryCode", "itemID", "categoryColor"} },
    ["cloudbeds.post_postItemsToInventory"] = { method = "POST", url = "https://api.cloudbeds.com/postItemsToInventory", body = {"item"} },
    ["cloudbeds.post_postNewHouseAccount"] = { method = "POST", url = "https://api.cloudbeds.com/postNewHouseAccount", body = {"propertyID", "accountName", "isPrivate"} },
    ["cloudbeds.post_postPayment"] = { method = "POST", url = "https://api.cloudbeds.com/postPayment", body = {"propertyID", "reservationID", "houseAccountID", "groupCode", "subReservationID", "type", "amount", "cardType", "description", "isDeposit"} },
    ["cloudbeds.post_postReservation"] = { method = "POST", url = "https://api.cloudbeds.com/postReservation", body = {"propertyID", "sourceID", "thirdPartyIdentifier", "startDate", "endDate", "guestFirstName", "guestLastName", "guestGender", "guestCountry", "guestNationality", "guestZip", "guestEmail", "guestPhone", "guestRequirements", "estimatedArrivalTime", "rooms", "adults", "children", "paymentMethod", "cardToken", "paymentAuthorizationCode", "customFields", "promoCode", "allotmentBlockCode", "groupCode", "dateCreated", "sendEmailConfirmation"} },
    ["cloudbeds.post_postReservationDocument"] = { method = "POST", url = "https://api.cloudbeds.com/postReservationDocument", body = {"propertyID", "reservationID", "file"} },
    ["cloudbeds.post_postReservationNote"] = { method = "POST", url = "https://api.cloudbeds.com/postReservationNote", body = {"propertyID", "reservationID", "reservationNote", "userID", "dateCreated"} },
    ["cloudbeds.post_postRoomAssign"] = { method = "POST", url = "https://api.cloudbeds.com/postRoomAssign", body = {"propertyID", "reservationID", "subReservationID", "reservationRoomID", "newRoomID", "roomTypeID", "oldRoomID", "overrideRates", "adjustPrice"} },
    ["cloudbeds.post_postRoomBlock"] = { method = "POST", url = "https://api.cloudbeds.com/postRoomBlock", body = {"propertyID", "roomBlockType", "roomBlockReason", "startDate", "endDate", "rooms", "firstName", "lastName", "lengthOfHoldInHours", "email", "phone"} },
    ["cloudbeds.post_postRoomCheckIn"] = { method = "POST", url = "https://api.cloudbeds.com/postRoomCheckIn", body = {"propertyID", "reservationID", "subReservationID", "roomID"} },
    ["cloudbeds.post_postRoomCheckOut"] = { method = "POST", url = "https://api.cloudbeds.com/postRoomCheckOut", body = {"propertyID", "reservationID", "subReservationID", "roomID"} },
    ["cloudbeds.post_postVoidItem"] = { method = "POST", url = "https://api.cloudbeds.com/postVoidItem", body = {"propertyID", "reservationID", "houseAccountID", "groupCode", "soldProductID"} },
    ["cloudbeds.post_postVoidPayment"] = { method = "POST", url = "https://api.cloudbeds.com/postVoidPayment", body = {"propertyID", "reservationID", "houseAccountID", "paymentID"} },
    ["cloudbeds.post_postWebhook"] = { method = "POST", url = "https://api.cloudbeds.com/postWebhook", body = {"propertyID", "object", "action", "endpointUrl", "authHeaderName", "authHeaderValue"} },
    ["cloudbeds.post_putAppPropertySettings"] = { method = "POST", url = "https://api.cloudbeds.com/putAppPropertySettings", body = {"propertyID", "value"} },
    ["cloudbeds.post_putGroup"] = { method = "POST", url = "https://api.cloudbeds.com/putGroup", body = {"propertyID", "name", "type", "status", "commissionType", "sourceID", "address1", "address2", "city", "zip", "state"} },
    ["cloudbeds.post_putRate"] = { method = "POST", url = "https://api.cloudbeds.com/putRate", body = {"rates"} },
    ["cloudbeds.post_updateAllotmentBlock"] = { method = "POST", url = "https://api.cloudbeds.com/updateAllotmentBlock", body = {"allotmentBlockCode", "allotmentBlockName", "allowOverbooking", "allotmentType", "allotmentBlockStatus", "autoRelease", "allotmentIntervals", "resources"} },
    ["cloudbeds.post_updateAllotmentBlockNotes"] = { method = "POST", url = "https://api.cloudbeds.com/updateAllotmentBlockNotes", body = {"propertyID", "allotmentBlockCode", "noteID", "text", "status"} },
    ["cloudbeds.put_putGuest"] = { method = "PUT", url = "https://api.cloudbeds.com/putGuest", body = {"propertyID", "guestID", "guestFirstName", "guestLastName", "guestGender", "guestEmail", "guestPhone", "guestCellPhone", "guestAddress1", "guestAddress2", "guestCity", "guestCountry", "guestNationality", "guestState", "guestZip", "guestBirthDate", "guestDocumentType", "guestDocumentNumber", "guestDocumentIssueDate", "guestDocumentIssuingCountry", "guestDocumentExpirationDate", "guestRequirements", "guestCustomFields", "guestCompanyName", "guestCompanyTaxId", "guestTaxId"} },
    ["cloudbeds.put_putGuestNote"] = { method = "PUT", url = "https://api.cloudbeds.com/putGuestNote", body = {"propertyID", "guestID", "noteID", "guestNote"} },
    ["cloudbeds.put_putHouseAccountStatus"] = { method = "PUT", url = "https://api.cloudbeds.com/putHouseAccountStatus", body = {"propertyID", "houseAccountID", "status"} },
    ["cloudbeds.put_putHousekeeper"] = { method = "PUT", url = "https://api.cloudbeds.com/putHousekeeper", body = {"propertyID", "name", "housekeeperID"} },
    ["cloudbeds.put_putItemToInventory"] = { method = "PUT", url = "https://api.cloudbeds.com/putItemToInventory", body = {"propertyID", "itemID", "itemName", "itemType", "itemSKU", "itemCode", "itemDescription", "itemPrice", "stockInventory", "itemQuantity", "reorderThreshold", "stopSellMet", "stopSell"} },
    ["cloudbeds.put_putReservation"] = { method = "PUT", url = "https://api.cloudbeds.com/putReservation", body = {"propertyID", "reservationID", "estimatedArrivalTime", "status", "checkoutDate", "customFields", "rooms", "dateCreated", "allotmentBlockCode", "eventCode", "sendStatusChangeEmail", "canceledByGuest"} },
    ["cloudbeds.put_putReservationNote"] = { method = "PUT", url = "https://api.cloudbeds.com/putReservationNote", body = {"propertyID", "reservationID", "reservationNoteID", "reservationNote"} },
    ["cloudbeds.put_putRoomBlock"] = { method = "PUT", url = "https://api.cloudbeds.com/putRoomBlock", body = {"propertyID", "roomBlockID", "roomBlockReason", "startDate", "endDate", "rooms", "firstName", "lastName", "lengthOfHoldInHours", "email", "phone"} },
  },
}
