-- Fiber AI — every call this API accepts, as data.
--
-- GENERATED from https://api.fiber.ai/openapi.json
-- Published on the vendor's own documentation site (https://api.fiber.ai).
-- 247 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "fiber-ai",
  name = "Fiber AI",
  base = "https://api.fiber.ai",
  docs = "https://nango.dev/docs/api-integrations/fiber-ai",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "FIBER_AI_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["fiber-ai.account_send_otp"] = { method = "POST", url = "https://api.fiber.ai/v1/account/send-otp", body = {"email", "purpose", "firstName", "lastName", "companyName"} },
    ["fiber-ai.account_verify_otp"] = { method = "POST", url = "https://api.fiber.ai/v1/account/verify-otp", body = {"verificationId", "otp"} },
    ["fiber-ai.add_companies_to_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/companies/add-to-list", body = {"listId", "companies"} },
    ["fiber-ai.add_profiles_to_list"] = { method = "POST", url = "https://api.fiber.ai/v1/job-changes/add-profiles", body = {"jobChangeListId", "profiles"} },
    ["fiber-ai.add_prospects_to_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/prospects/add-to-list", body = {"listId", "prospects"} },
    ["fiber-ai.add_tracker_companies"] = { method = "PUT", url = "https://api.fiber.ai/v1/tracker/company-lists/{listId}/companies", path = {"listId"}, body = {"companies", "initialSignals"} },
    ["fiber-ai.add_tracker_people"] = { method = "PUT", url = "https://api.fiber.ai/v1/tracker/person-lists/{listId}/people", path = {"listId"}, body = {"people", "initialSignals"} },
    ["fiber-ai.blue_collar_jobs_search"] = { method = "POST", url = "https://api.fiber.ai/v1/blue-collar-jobs/search", body = {"companySlug", "query", "location", "nextPageToken"} },
    ["fiber-ai.blue_collar_resolve_company"] = { method = "POST", url = "https://api.fiber.ai/v1/blue-collar-jobs/resolve-company", body = {"companyName", "domain"} },
    ["fiber-ai.build_audience"] = { method = "POST", url = "https://api.fiber.ai/v1/audiences/{audienceId}/build", path = {"audienceId"} },
    ["fiber-ai.bulk_company_logos"] = { method = "POST", url = "https://api.fiber.ai/v1/company-logos/bulk", body = {"companiesIdentifier"} },
    ["fiber-ai.bulk_profile_pic"] = { method = "POST", url = "https://api.fiber.ai/v1/profile-pic/bulk", body = {"linkedinUrls"} },
    ["fiber-ai.buy_credits"] = { method = "POST", url = "https://api.fiber.ai/v1/buy-credits", body = {"subscriptionId", "creditsToBuy", "sharedPaymentGrantedToken", "idempotencyKey"} },
    ["fiber-ai.cancel_batch_contact_details"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/batch/cancel", body = {"taskId"} },
    ["fiber-ai.cards_attach"] = { method = "POST", url = "https://api.fiber.ai/v1/cards/attach", body = {"sharedPaymentGrantedToken"} },
    ["fiber-ai.check_google_maps_results"] = { method = "POST", url = "https://api.fiber.ai/v1/google-maps-search/check", body = {"searchID"} },
    ["fiber-ai.combined_search_count"] = { method = "POST", url = "https://api.fiber.ai/v1/combined-search/count", body = {"companyParams", "profileParams", "companyExclusionListIDs", "prospectExclusionListIDs", "getFastEstimate"} },
    ["fiber-ai.company_count"] = { method = "POST", url = "https://api.fiber.ai/v1/company-count", body = {"searchParams", "companyExclusionListIDs"} },
    ["fiber-ai.company_live_enrich"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/company/single", body = {"type", "value", "getHistoricalHeadcount"} },
    ["fiber-ai.company_logo"] = { method = "POST", url = "https://api.fiber.ai/v1/company-logos/single", body = {"identifier"} },
    ["fiber-ai.company_posts_live_fetch"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/company-posts", body = {"identifier", "cursor"} },
    ["fiber-ai.company_search"] = { method = "POST", url = "https://api.fiber.ai/v1/company-search", body = {"searchParams", "pageSize", "cursor", "companyExclusionListIDs", "includeCount"} },
    ["fiber-ai.company_typeahead"] = { method = "POST", url = "https://api.fiber.ai/v1/typeahead/company", body = {"startsWith", "orgType"} },
    ["fiber-ai.create_audience"] = { method = "POST", url = "https://api.fiber.ai/v1/audiences/create", body = {"name", "creationMethod"} },
    ["fiber-ai.create_company_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/companies/create-list", body = {"name", "isOrganizationWide"} },
    ["fiber-ai.create_company_exclusion_list_from_audience"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/companies/audience/create-list", body = {"audienceId", "name", "isOrganizationWide"} },
    ["fiber-ai.create_job_change_list"] = { method = "POST", url = "https://api.fiber.ai/v1/job-changes/create-list", body = {"name"} },
    ["fiber-ai.create_prospect_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/prospects/create-list", body = {"name", "isOrganizationWide"} },
    ["fiber-ai.create_prospect_exclusion_list_from_audience"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/prospects/audience/create-list", body = {"audienceId", "name", "isOrganizationWide"} },
    ["fiber-ai.create_sandbox_api_key"] = { method = "POST", url = "https://api.fiber.ai/v1/api-keys/create-sandbox", body = {"name"} },
    ["fiber-ai.create_saved_search"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/create", body = {"name", "searchParams", "spawnFrequencyDays"} },
    ["fiber-ai.create_tracker_company_list"] = { method = "POST", url = "https://api.fiber.ai/v1/tracker/company-lists", body = {"name", "refreshIntervalDays", "trackingRules", "companySearchParams", "maxDynamicMembers"} },
    ["fiber-ai.create_tracker_person_list"] = { method = "POST", url = "https://api.fiber.ai/v1/tracker/person-lists", body = {"name", "refreshIntervalDays", "trackingRules", "prospectSearchParams", "companySearchParams", "maxDynamicMembers"} },
    ["fiber-ai.create_webhook_endpoint"] = { method = "POST", url = "https://api.fiber.ai/v1/webhooks/endpoints", body = {"url", "eventTypes", "description"} },
    ["fiber-ai.delete_audience"] = { method = "DELETE", url = "https://api.fiber.ai/v1/audiences/{audienceId}", path = {"audienceId"} },
    ["fiber-ai.delete_company_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/companies/delete-list", body = {"listIDs"} },
    ["fiber-ai.delete_job_change_list"] = { method = "POST", url = "https://api.fiber.ai/v1/job-changes/delete-list", body = {"jobChangeListId"} },
    ["fiber-ai.delete_profiles_from_job_change_list"] = { method = "POST", url = "https://api.fiber.ai/v1/job-changes/delete-profiles", body = {"profileIds", "jobChangeListId"} },
    ["fiber-ai.delete_prospect_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/prospects/delete-list", body = {"listIds"} },
    ["fiber-ai.delete_tracker_company_list"] = { method = "DELETE", url = "https://api.fiber.ai/v1/tracker/company-lists/{listId}", path = {"listId"} },
    ["fiber-ai.delete_tracker_person_list"] = { method = "DELETE", url = "https://api.fiber.ai/v1/tracker/person-lists/{listId}", path = {"listId"} },
    ["fiber-ai.delete_webhook_endpoint"] = { method = "DELETE", url = "https://api.fiber.ai/v1/webhooks/endpoints/{endpointId}", path = {"endpointId"} },
    ["fiber-ai.domain_lookup_polling"] = { method = "POST", url = "https://api.fiber.ai/v1/domain-lookup/polling", body = {"domainAgentRunId", "cursor", "pageSize"} },
    ["fiber-ai.domain_lookup_trigger"] = { method = "POST", url = "https://api.fiber.ai/v1/domain-lookup/trigger", body = {"overAllContext", "companyInfo"} },
    ["fiber-ai.email_bounce_detection"] = { method = "POST", url = "https://api.fiber.ai/v1/validate-email/single", body = {"email"} },
    ["fiber-ai.estimate_enrichment_cost"] = { method = "POST", url = "https://api.fiber.ai/v1/audiences/{audienceId}/enrichment/estimate", path = {"audienceId"}, body = {"maxProspectsToEnrich", "enrichmentType", "runCompanyLiveEnrichment", "runProfileLiveEnrichment", "runProfileSalesNav", "runContactEnrichment"} },
    ["fiber-ai.export_companies"] = { method = "POST", url = "https://api.fiber.ai/v1/audiences/{audienceId}/export/companies", path = {"audienceId"}, body = {"format", "maxRowsToExport", "excludeFields", "userEmail"} },
    ["fiber-ai.export_prospects"] = { method = "POST", url = "https://api.fiber.ai/v1/audiences/{audienceId}/export/prospects", path = {"audienceId"}, body = {"format", "maxRowsToExport", "excludeFields", "onlyWithContacts", "userEmail"} },
    ["fiber-ai.fetch_real_estate_listings"] = { method = "POST", url = "https://api.fiber.ai/v1/real-estate/listings", body = {"location", "nextPageToken", "sortBy", "listingStatus", "homeTypes", "price", "rent", "bedrooms", "bathrooms", "floorAreaSqFt", "lotAreaSqFt", "yearBuilt", "parkingSpots", "keywords", "features"} },
    ["fiber-ai.financial_instrument_lookup"] = { method = "POST", url = "https://api.fiber.ai/v1/finance/instrument", body = {"instrument", "window"} },
    ["fiber-ai.fire_tracker_dummy"] = { method = "POST", url = "https://api.fiber.ai/v1/tracker/fire-dummy/{listId}", path = {"listId"} },
    ["fiber-ai.flight_booking_options"] = { method = "POST", url = "https://api.fiber.ai/v1/flights/booking-options", body = {"bookingToken", "trip", "currencyCode", "searchMarketCountryCode", "languageCode"} },
    ["fiber-ai.flight_search"] = { method = "POST", url = "https://api.fiber.ai/v1/flights/search", body = {"travelClass", "adults", "children", "infantsInSeat", "infantsOnLap", "maxStops", "sortBy", "airlines", "minCarryOnBags", "minCheckedBags", "maxPrice", "outboundTimeWindow", "returnTimeWindow", "layoverDuration", "maxFlightDurationMinutes", "connectingAirports", "onlyShowLowEmissionFlights", "showHidden", "hideSeparateTickets", "currencyCode", "searchMarketCountryCode", "languageCode", "nextPageToken", "trip"} },
    ["fiber-ai.get_accelerators"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/accelerators" },
    ["fiber-ai.get_all_api_keys"] = { method = "POST", url = "https://api.fiber.ai/v1/api-keys", body = {"includeRevoked"} },
    ["fiber-ai.get_audience_companies"] = { method = "GET", url = "https://api.fiber.ai/v1/audiences/{audienceId}/companies", path = {"audienceId"}, query = {"pageSize", "cursor"} },
    ["fiber-ai.get_audience_prospects"] = { method = "GET", url = "https://api.fiber.ai/v1/audiences/{audienceId}/prospects", path = {"audienceId"}, query = {"pageSize", "cursor"} },
    ["fiber-ai.get_audience_status"] = { method = "GET", url = "https://api.fiber.ai/v1/audiences/{audienceId}/status", path = {"audienceId"} },
    ["fiber-ai.get_auto_topup_settings"] = { method = "GET", url = "https://api.fiber.ai/v1/auto-topup/settings" },
    ["fiber-ai.get_company_exclusion_lists"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/companies/get-lists" },
    ["fiber-ai.get_company_revenue"] = { method = "POST", url = "https://api.fiber.ai/v1/company-revenue", body = {"companyMetadata"} },
    ["fiber-ai.get_current_api_key"] = { method = "POST", url = "https://api.fiber.ai/v1/api-keys/current", body = {"target", "targetApiKey"} },
    ["fiber-ai.get_current_companies_in_saved_search"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/current/companies", body = {"savedSearchId", "statuses", "cursor", "pageSize"} },
    ["fiber-ai.get_current_profiles_in_saved_search"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/current/profiles", body = {"savedSearchId", "statuses", "cursor", "pageSize"} },
    ["fiber-ai.get_department_size"] = { method = "POST", url = "https://api.fiber.ai/v1/department-size", body = {"company", "departments"} },
    ["fiber-ai.get_enrichment_status"] = { method = "GET", url = "https://api.fiber.ai/v1/audiences/{audienceId}/enrichment/status", path = {"audienceId"} },
    ["fiber-ai.get_excluded_companies_for_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/companies/read-from-list", body = {"exclusionListId", "cursor", "pageSize"} },
    ["fiber-ai.get_excluded_prospects_for_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/prospects/read-from-list", body = {"exclusionListId", "cursor", "pageSize"} },
    ["fiber-ai.get_flight_regions"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/flight-regions" },
    ["fiber-ai.get_hotel_amenities"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/hotels/amenities" },
    ["fiber-ai.get_hotel_brands"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/hotels/brands" },
    ["fiber-ai.get_hotel_property_types"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/hotels/property-types" },
    ["fiber-ai.get_industries"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/industries" },
    ["fiber-ai.get_job_change_list"] = { method = "POST", url = "https://api.fiber.ai/v1/job-changes/get-list", body = {"jobChangeListId"} },
    ["fiber-ai.get_languages"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/languages" },
    ["fiber-ai.get_latest_saved_search_run"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/run/get-latest", body = {"savedSearchId"} },
    ["fiber-ai.get_metro_areas"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/metro-areas" },
    ["fiber-ai.get_naics_codes"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/naics-codes" },
    ["fiber-ai.get_open_api"] = { method = "GET", url = "https://api.fiber.ai/openapi.json" },
    ["fiber-ai.get_org_credits"] = { method = "GET", url = "https://api.fiber.ai/v1/get-org-credits" },
    ["fiber-ai.get_prospect_exclusion_lists"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/prospects/get-lists" },
    ["fiber-ai.get_quickstart_script"] = { method = "GET", url = "https://api.fiber.ai/quickstart" },
    ["fiber-ai.get_rate_limits"] = { method = "GET", url = "https://api.fiber.ai/v1/rate-limits" },
    ["fiber-ai.get_regions"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/regions" },
    ["fiber-ai.get_saved_search"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/get", body = {"savedSearchId"} },
    ["fiber-ai.get_saved_search_run"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/run/get", body = {"savedSearchRunId"} },
    ["fiber-ai.get_saved_search_run_companies"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/run/companies", body = {"savedSearchRunId", "statuses", "cursor", "pageSize"} },
    ["fiber-ai.get_saved_search_run_profiles"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/run/profiles", body = {"savedSearchRunId", "statuses", "cursor", "pageSize"} },
    ["fiber-ai.get_saved_search_run_status"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/run/status", body = {"savedSearchRunId"} },
    ["fiber-ai.get_scouting_report"] = { method = "POST", url = "https://api.fiber.ai/v1/scouting-report", body = {"company"} },
    ["fiber-ai.get_skills"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/skills" },
    ["fiber-ai.get_subdivisions"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/subdivisions", query = {"countryCode"} },
    ["fiber-ai.get_tags"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/tags" },
    ["fiber-ai.get_talent_flow"] = { method = "POST", url = "https://api.fiber.ai/v1/talent-flow", body = {"company", "direction", "dateRange"} },
    ["fiber-ai.get_talent_flow_rivals"] = { method = "POST", url = "https://api.fiber.ai/v1/talent-flow/rivals", body = {"company", "dateRange", "numCompaniesPerSide"} },
    ["fiber-ai.get_technologies"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/technologies" },
    ["fiber-ai.get_time_zones"] = { method = "GET", url = "https://api.fiber.ai/v1/enums/time-zones" },
    ["fiber-ai.get_tracker_company_list"] = { method = "GET", url = "https://api.fiber.ai/v1/tracker/company-lists/{listId}", path = {"listId"} },
    ["fiber-ai.get_tracker_overview"] = { method = "GET", url = "https://api.fiber.ai/v1/tracker/overview" },
    ["fiber-ai.get_tracker_person_list"] = { method = "GET", url = "https://api.fiber.ai/v1/tracker/person-lists/{listId}", path = {"listId"} },
    ["fiber-ai.get_webhook_endpoint"] = { method = "GET", url = "https://api.fiber.ai/v1/webhooks/endpoints/{endpointId}", path = {"endpointId"} },
    ["fiber-ai.github_lookup_poll"] = { method = "POST", url = "https://api.fiber.ai/v1/github-lookup/poll", body = {"githubAgentRunId"} },
    ["fiber-ai.github_lookup_trigger"] = { method = "POST", url = "https://api.fiber.ai/v1/github-lookup/trigger", body = {"overallContext", "people"} },
    ["fiber-ai.github_to_linked_in_polling"] = { method = "POST", url = "https://api.fiber.ai/v1/github-to-linkedin/polling", body = {"githubAgentRunId", "cursor", "pageSize"} },
    ["fiber-ai.github_to_linked_in_trigger"] = { method = "POST", url = "https://api.fiber.ai/v1/github-to-linkedin/trigger", body = {"overallContext", "people", "outputType"} },
    ["fiber-ai.github_to_linkedin_single"] = { method = "POST", url = "https://api.fiber.ai/v1/github-to-linkedin/single", body = {"githubUsername", "context", "outputType", "customerProvidedId"} },
    ["fiber-ai.google_maps_search"] = { method = "POST", url = "https://api.fiber.ai/v1/google-maps-search/start", body = {"name", "query", "maxResults", "strategy"} },
    ["fiber-ai.health_check"] = { method = "GET", url = "https://api.fiber.ai/health" },
    ["fiber-ai.hotel_property"] = { method = "POST", url = "https://api.fiber.ai/v1/hotels/property", body = {"propertyToken", "checkInDate", "checkOutDate", "adults", "children", "childrenAges", "currencyCode", "searchMarketCountryCode", "languageCode"} },
    ["fiber-ai.hotel_search"] = { method = "POST", url = "https://api.fiber.ai/v1/hotels/search", body = {"query", "checkInDate", "checkOutDate", "adults", "children", "childrenAges", "sortBy", "minRating", "priceRange", "category", "nextPageToken", "currencyCode", "searchMarketCountryCode", "languageCode"} },
    ["fiber-ai.instagram_post_comments"] = { method = "POST", url = "https://api.fiber.ai/v1/instagram/post-comments", body = {"postUrl", "nextPageToken"} },
    ["fiber-ai.instagram_post_details"] = { method = "POST", url = "https://api.fiber.ai/v1/instagram/post-details", body = {"postUrl"} },
    ["fiber-ai.instagram_profile"] = { method = "POST", url = "https://api.fiber.ai/v1/instagram/profile", body = {"handle"} },
    ["fiber-ai.instagram_user_posts"] = { method = "POST", url = "https://api.fiber.ai/v1/instagram/user-posts", body = {"handle", "nextPageToken"} },
    ["fiber-ai.instagram_user_reels"] = { method = "POST", url = "https://api.fiber.ai/v1/instagram/user-reels", body = {"handle", "nextPageToken"} },
    ["fiber-ai.instant_contact_reveal"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/instant", body = {"input", "enrichmentType"} },
    ["fiber-ai.job_posting_search"] = { method = "POST", url = "https://api.fiber.ai/v1/job-search", body = {"searchParams", "pageSize", "cursor"} },
    ["fiber-ai.job_posting_search_count"] = { method = "POST", url = "https://api.fiber.ai/v1/job-search/count", body = {"searchParams"} },
    ["fiber-ai.job_title_rewrite"] = { method = "POST", url = "https://api.fiber.ai/v1/typeahead/job-title", body = {"query", "limit"} },
    ["fiber-ai.kitchen_sink_bulk_company"] = { method = "POST", url = "https://api.fiber.ai/v1/kitchen-sink/bulk/company", body = {"companies"} },
    ["fiber-ai.kitchen_sink_bulk_profile"] = { method = "POST", url = "https://api.fiber.ai/v1/kitchen-sink/bulk/profile", body = {"profiles", "liveFetch", "forceCompanyMatch", "fuzzySearch", "thoroughness", "getDetailedEducation", "getDetailedWorkExperience"} },
    ["fiber-ai.kitchen_sink_company"] = { method = "POST", url = "https://api.fiber.ai/v1/kitchen-sink/company", body = {"companyIdentifier", "companyName", "companyDomain", "companyLocation", "numCompanies"} },
    ["fiber-ai.kitchen_sink_profile"] = { method = "POST", url = "https://api.fiber.ai/v1/kitchen-sink/person", body = {"profileIdentifier", "emailAddress", "personName", "jobTitle", "companyIdentifier", "linkedinHeadline", "companyName", "companyDomain", "profileLocation", "numProfiles", "liveFetch", "forceCompanyMatch", "schoolName", "schoolIdentifier", "schoolDomain", "fuzzySearch", "thoroughness", "getDetailedEducation", "getDetailedWorkExperience"} },
    ["fiber-ai.list_all_job_change_lists"] = { method = "POST", url = "https://api.fiber.ai/v1/job-changes/list-all", body = {"cursor", "pageSize"} },
    ["fiber-ai.list_all_profiles_from_job_change_list"] = { method = "POST", url = "https://api.fiber.ai/v1/job-changes/list-all-profiles", body = {"jobChangeListId", "movements", "cursor", "pageSize"} },
    ["fiber-ai.list_api_requests"] = { method = "POST", url = "https://api.fiber.ai/v1/api-requests", body = {"from", "to", "routePath", "method", "statusCode", "errorCode", "cursor", "pageSize"} },
    ["fiber-ai.list_audiences"] = { method = "GET", url = "https://api.fiber.ai/v1/audiences" },
    ["fiber-ai.list_available_tracker_rules"] = { method = "GET", url = "https://api.fiber.ai/v1/tracker/rules" },
    ["fiber-ai.list_company_rankings"] = { method = "POST", url = "https://api.fiber.ai/v1/company-rankings", body = {"rankings"} },
    ["fiber-ai.list_saved_search"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/list", body = {"cursor", "pageSize"} },
    ["fiber-ai.list_saved_search_runs"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/run/list", body = {"savedSearchId", "cursor", "pageSize"} },
    ["fiber-ai.list_tracker_company_lists"] = { method = "GET", url = "https://api.fiber.ai/v1/tracker/company-lists" },
    ["fiber-ai.list_tracker_person_lists"] = { method = "GET", url = "https://api.fiber.ai/v1/tracker/person-lists" },
    ["fiber-ai.list_tracker_signals"] = { method = "GET", url = "https://api.fiber.ai/v1/tracker/signals/{listId}", path = {"listId"}, query = {"since", "cursor", "pageSize", "filter"} },
    ["fiber-ai.list_webhook_endpoints"] = { method = "GET", url = "https://api.fiber.ai/v1/webhooks/endpoints" },
    ["fiber-ai.list_webhook_event_types"] = { method = "GET", url = "https://api.fiber.ai/v1/webhooks/event-types" },
    ["fiber-ai.lite_contact_reveal"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/lite", body = {"input", "enrichmentType", "patience"} },
    ["fiber-ai.lite_reverse_email_lookup"] = { method = "POST", url = "https://api.fiber.ai/v1/email-to-person/single/lite", body = {"email"} },
    ["fiber-ai.location_typeahead"] = { method = "POST", url = "https://api.fiber.ai/v1/typeahead/location", body = {"query"} },
    ["fiber-ai.manually_spawn_saved_search_run"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/spawn", body = {"savedSearchId"} },
    ["fiber-ai.multi_source_search"] = { method = "POST", url = "https://api.fiber.ai/v1/multi-source/search", body = {"search"} },
    ["fiber-ai.nlp_search_parse"] = { method = "POST", url = "https://api.fiber.ai/v1/nlp-search/parse", body = {"query"} },
    ["fiber-ai.paginated_combined_search"] = { method = "POST", url = "https://api.fiber.ai/v1/combined-search/paginated", body = {"companyConfig", "profileConfig"} },
    ["fiber-ai.people_search"] = { method = "POST", url = "https://api.fiber.ai/v1/people-search", body = {"searchParams", "pageSize", "cursor", "currentCompanies", "prospectExclusionListIDs", "companyExclusionListIDs", "includeCount"} },
    ["fiber-ai.people_search_count"] = { method = "POST", url = "https://api.fiber.ai/v1/people-search/count", body = {"searchParams", "currentCompanies", "prospectExclusionListIDs", "companyExclusionListIDs", "includeCount"} },
    ["fiber-ai.poll_batch_contact_details"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/batch/poll", body = {"taskId", "cursor", "take"} },
    ["fiber-ai.poll_batch_live_enrich"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/batch/poll", body = {"taskId", "cursor", "take"} },
    ["fiber-ai.poll_depth_chart"] = { method = "POST", url = "https://api.fiber.ai/v1/depth-chart/poll", body = {"reportId"} },
    ["fiber-ai.poll_exhaustive_contact_enrichment_result"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/exhaustive/poll", body = {"taskId"} },
    ["fiber-ai.poll_google_maps_results"] = { method = "POST", url = "https://api.fiber.ai/v1/google-maps-search/poll", body = {"searchID", "pageSize", "cursor"} },
    ["fiber-ai.poll_local_business_search"] = { method = "POST", url = "https://api.fiber.ai/v1/local-business-search/poll", body = {"researchRunId", "pageSize", "cursor"} },
    ["fiber-ai.poll_mosaic"] = { method = "POST", url = "https://api.fiber.ai/v1/mosaic/poll", body = {"runId"} },
    ["fiber-ai.post_comments_live_fetch"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/post-comments", body = {"contentId", "cursor", "includeTaggedUsers"} },
    ["fiber-ai.post_reactions_live_fetch"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/post-reactions", body = {"contentId", "reactionType", "cursor"} },
    ["fiber-ai.post_search_by_keywords"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/posts/search", body = {"keywords", "recency", "cursor"} },
    ["fiber-ai.premium_phone_reveal"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/premium-phone/sync", body = {"linkedinUrl", "patience"} },
    ["fiber-ai.preview_tracker_signal"] = { method = "POST", url = "https://api.fiber.ai/v1/tracker/rules/preview-signal", body = {"config"} },
    ["fiber-ai.profile_comments_live_fetch"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/profile-comments", body = {"identifier", "cursor"} },
    ["fiber-ai.profile_live_enrich"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/profile/single", body = {"identifier", "getDetailedEducation", "getDetailedWorkExperience"} },
    ["fiber-ai.profile_posts_live_fetch"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/profile-posts", body = {"identifier", "cursor"} },
    ["fiber-ai.profile_reactions_live_fetch"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/profile-reactions", body = {"identifier", "cursor"} },
    ["fiber-ai.quick_company_resolve"] = { method = "POST", url = "https://api.fiber.ai/v1/company-resolve", body = {"companies"} },
    ["fiber-ai.quick_person_resolve"] = { method = "POST", url = "https://api.fiber.ai/v1/person-resolve", body = {"people"} },
    ["fiber-ai.reddit_post_comments"] = { method = "POST", url = "https://api.fiber.ai/v1/reddit/post/comments", body = {"postUrlOrId", "nextPageToken"} },
    ["fiber-ai.reddit_search"] = { method = "POST", url = "https://api.fiber.ai/v1/reddit/search", body = {"query", "sort", "timeframe", "nextPageToken"} },
    ["fiber-ai.reddit_subreddit_posts"] = { method = "POST", url = "https://api.fiber.ai/v1/reddit/subreddit/posts", body = {"subreddit", "sort", "timeframe", "nextPageToken"} },
    ["fiber-ai.reddit_subreddit_search"] = { method = "POST", url = "https://api.fiber.ai/v1/reddit/subreddit/search", body = {"subreddit", "query", "sort", "timeframe", "nextPageToken"} },
    ["fiber-ai.refresh_tracker_company_list"] = { method = "POST", url = "https://api.fiber.ai/v1/tracker/company-lists/{listId}/refresh", path = {"listId"} },
    ["fiber-ai.refresh_tracker_person_list"] = { method = "POST", url = "https://api.fiber.ai/v1/tracker/person-lists/{listId}/refresh", path = {"listId"} },
    ["fiber-ai.remove_company_from_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/companies/remove-from-list", body = {"listId", "excludedCompanyDetails"} },
    ["fiber-ai.remove_prospect_from_exclusion_list"] = { method = "POST", url = "https://api.fiber.ai/v1/exclusions/prospects/remove-from-list", body = {"listId", "excludedProspectDetails"} },
    ["fiber-ai.remove_tracker_companies"] = { method = "DELETE", url = "https://api.fiber.ai/v1/tracker/company-lists/{listId}/companies", path = {"listId"}, body = {"companies"} },
    ["fiber-ai.remove_tracker_people"] = { method = "DELETE", url = "https://api.fiber.ai/v1/tracker/person-lists/{listId}/people", path = {"listId"}, body = {"people"} },
    ["fiber-ai.reset_api_key_usage"] = { method = "POST", url = "https://api.fiber.ai/v1/api-keys/usage/reset", body = {"target", "targetApiKey"} },
    ["fiber-ai.reverse_email_lookup"] = { method = "POST", url = "https://api.fiber.ai/v1/email-to-person/single", body = {"email"} },
    ["fiber-ai.reverse_phone_lookup"] = { method = "POST", url = "https://api.fiber.ai/v1/phone-to-person/single", body = {"phoneNumber"} },
    ["fiber-ai.revoke_current_api_key"] = { method = "POST", url = "https://api.fiber.ai/v1/api-keys/revoke", body = {"target", "targetApiKey"} },
    ["fiber-ai.rotate_webhook_endpoint_secret"] = { method = "POST", url = "https://api.fiber.ai/v1/webhooks/endpoints/{endpointId}/rotate-secret", path = {"endpointId"} },
    ["fiber-ai.send_test_webhook_event"] = { method = "POST", url = "https://api.fiber.ai/v1/webhooks/endpoints/{endpointId}/test-event", path = {"endpointId"}, body = {"eventType"} },
    ["fiber-ai.skills_typeahead"] = { method = "POST", url = "https://api.fiber.ai/v1/typeahead/skills", body = {"query"} },
    ["fiber-ai.skip_next_saved_search_run"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/skip-next-run", body = {"savedSearchId"} },
    ["fiber-ai.slushie_run"] = { method = "POST", url = "https://api.fiber.ai/v1/nlp-search/run", body = {"query", "pageSize", "companyExclusionListIDs", "peopleExclusionListIDs", "pageToken", "getDetailedEducation", "getDetailedWorkExperience"} },
    ["fiber-ai.social_media_lookup_batch_polling"] = { method = "POST", url = "https://api.fiber.ai/v1/social-media-lookup/batch/poll", body = {"runId", "nextPageToken", "pageSize"} },
    ["fiber-ai.social_media_lookup_batch_trigger"] = { method = "POST", url = "https://api.fiber.ai/v1/social-media-lookup/batch/trigger", body = {"overallContext", "platforms", "people"} },
    ["fiber-ai.social_media_lookup_polling"] = { method = "POST", url = "https://api.fiber.ai/v1/social-media-lookup/polling", body = {"socialMediaFinderRunId", "cursor", "pageSize"} },
    ["fiber-ai.social_media_lookup_trigger"] = { method = "POST", url = "https://api.fiber.ai/v1/social-media-lookup/trigger", body = {"overallContext", "platforms", "person"} },
    ["fiber-ai.standardize_company"] = { method = "POST", url = "https://api.fiber.ai/v1/standardize/company/single", body = {"identifier"} },
    ["fiber-ai.standardize_company_bulk"] = { method = "POST", url = "https://api.fiber.ai/v1/standardize/company/bulk", body = {"identifiers"} },
    ["fiber-ai.standardize_profile"] = { method = "POST", url = "https://api.fiber.ai/v1/standardize/profile/single", body = {"identifier"} },
    ["fiber-ai.start_batch_contact_details"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/batch/start", body = {"personDetails", "enrichmentTypes"} },
    ["fiber-ai.start_batch_live_enrich"] = { method = "POST", url = "https://api.fiber.ai/v1/linkedin-live-fetch/batch/start", body = {"type", "identifiers"} },
    ["fiber-ai.start_depth_chart"] = { method = "POST", url = "https://api.fiber.ai/v1/depth-chart/start", body = {"company", "functions"} },
    ["fiber-ai.start_local_business_search"] = { method = "POST", url = "https://api.fiber.ai/v1/local-business-search/start", body = {"companies", "jobTitles", "strictJobTitleMatch", "contactPreferences"} },
    ["fiber-ai.start_mosaic"] = { method = "POST", url = "https://api.fiber.ai/v1/mosaic/start", body = {"sourceUrl", "customInstructions", "options"} },
    ["fiber-ai.stealth_founders_count"] = { method = "POST", url = "https://api.fiber.ai/v1/stealth-founders/count", body = {"stealthConfig", "searchParams"} },
    ["fiber-ai.stealth_founders_search"] = { method = "POST", url = "https://api.fiber.ai/v1/stealth-founders/search", body = {"stealthConfig", "searchParams", "pageSize", "cursor"} },
    ["fiber-ai.sync_quick_contact_reveal"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/single", body = {"linkedinUrl", "enrichmentType", "patience", "validateEmails"} },
    ["fiber-ai.sync_turbo_contact_enrichment"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/turbo/sync", body = {"linkedinUrl", "enrichmentType", "patience"} },
    ["fiber-ai.tiktok_comment_replies"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/comment-replies", body = {"commentId", "videoUrl", "nextPageToken"} },
    ["fiber-ai.tiktok_popular_songs"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/popular-songs" },
    ["fiber-ai.tiktok_profile"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/profile", body = {"handle"} },
    ["fiber-ai.tiktok_search_hashtag"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/search-hashtag", body = {"query", "nextPageToken"} },
    ["fiber-ai.tiktok_search_keyword"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/search-keyword", body = {"query", "nextPageToken"} },
    ["fiber-ai.tiktok_search_users"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/search-users", body = {"query", "nextPageToken"} },
    ["fiber-ai.tiktok_song_details"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/song-details", body = {"songUrl"} },
    ["fiber-ai.tiktok_song_videos"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/song-videos", body = {"songUrl", "nextPageToken"} },
    ["fiber-ai.tiktok_trending_feed"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/trending-feed", body = {"nextPageToken"} },
    ["fiber-ai.tiktok_unified_search"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/unified-search", body = {"query", "nextPageToken"} },
    ["fiber-ai.tiktok_user_followers"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/user-followers", body = {"handle", "nextPageToken"} },
    ["fiber-ai.tiktok_user_following"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/user-following", body = {"handle", "nextPageToken"} },
    ["fiber-ai.tiktok_user_videos"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/user-videos", body = {"handle", "nextPageToken"} },
    ["fiber-ai.tiktok_video_comments"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/video-comments", body = {"videoUrl", "nextPageToken"} },
    ["fiber-ai.tiktok_video_details"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/video-details", body = {"videoUrl"} },
    ["fiber-ai.tiktok_video_transcript"] = { method = "POST", url = "https://api.fiber.ai/v1/tiktok/video-transcript", body = {"videoUrl"} },
    ["fiber-ai.trigger_enrichment"] = { method = "POST", url = "https://api.fiber.ai/v1/audiences/{audienceId}/enrich", path = {"audienceId"}, body = {"maxProspectsToEnrich", "enrichmentType", "runCompanyLiveEnrichment", "runProfileLiveEnrichment", "runProfileSalesNav", "runContactEnrichment", "userEmail"} },
    ["fiber-ai.trigger_exhaustive_contact_enrichment"] = { method = "POST", url = "https://api.fiber.ai/v1/contact-details/exhaustive/start", body = {"linkedinUrl", "enrichmentType"} },
    ["fiber-ai.twitter_handle_to_linkedin_url"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter-handle-to-linkedin/single", body = {"handle", "context"} },
    ["fiber-ai.twitter_profile"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/profile", body = {"handle"} },
    ["fiber-ai.twitter_search"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/search", body = {"query", "cursor"} },
    ["fiber-ai.twitter_tweet_details"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/tweet-details", body = {"tweetId"} },
    ["fiber-ai.twitter_tweet_quotes"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/tweet-quotes", body = {"tweetId", "cursor"} },
    ["fiber-ai.twitter_tweet_replies"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/tweet-replies", body = {"tweetId", "cursor"} },
    ["fiber-ai.twitter_tweet_retweeters"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/tweet-retweeters", body = {"tweetId", "cursor"} },
    ["fiber-ai.twitter_user_followers"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/user-followers", body = {"handle", "cursor"} },
    ["fiber-ai.twitter_user_following"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/user-following", body = {"handle", "cursor"} },
    ["fiber-ai.twitter_user_mentions"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/user-mentions", body = {"handle", "cursor"} },
    ["fiber-ai.twitter_user_tweets"] = { method = "POST", url = "https://api.fiber.ai/v1/twitter/user-tweets", body = {"handle", "cursor"} },
    ["fiber-ai.undo_skip_next_saved_search_run"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/undo-skip", body = {"savedSearchId"} },
    ["fiber-ai.update_api_key_expiration"] = { method = "POST", url = "https://api.fiber.ai/v1/api-keys/expiration", body = {"target", "targetApiKey", "operation", "expiresAt", "days"} },
    ["fiber-ai.update_api_key_limit"] = { method = "POST", url = "https://api.fiber.ai/v1/api-keys/limit", body = {"target", "targetApiKey", "operation", "credits", "factor"} },
    ["fiber-ai.update_audience_search_params"] = { method = "PATCH", url = "https://api.fiber.ai/v1/audiences/{audienceId}/search-params", path = {"audienceId"}, body = {"companySearchParams", "prospectSearchParams"} },
    ["fiber-ai.update_auto_topup_settings"] = { method = "POST", url = "https://api.fiber.ai/v1/auto-topup/configure", body = {"subscriptionId", "isEnabled", "creditThreshold", "creditsToBuy", "maxPerDay", "maxPerMonth"} },
    ["fiber-ai.update_job_change_list"] = { method = "POST", url = "https://api.fiber.ai/v1/job-changes/update-list", body = {"jobChangeListId", "newName", "isActive"} },
    ["fiber-ai.update_saved_search"] = { method = "POST", url = "https://api.fiber.ai/v1/saved-search/update", body = {"id", "name", "spawnFrequencyDays", "companyParams", "profileParams", "isActive"} },
    ["fiber-ai.update_tracker_company_list"] = { method = "PATCH", url = "https://api.fiber.ai/v1/tracker/company-lists/{listId}", path = {"listId"}, body = {"name", "refreshIntervalDays", "isActive", "maxDynamicMembers", "trackingRules", "addRules", "removeRuleIds", "updateRuleFlags", "initialSignals"} },
    ["fiber-ai.update_tracker_person_list"] = { method = "PATCH", url = "https://api.fiber.ai/v1/tracker/person-lists/{listId}", path = {"listId"}, body = {"name", "refreshIntervalDays", "isActive", "maxDynamicMembers", "trackingRules", "addRules", "removeRuleIds", "updateRuleFlags", "initialSignals"} },
    ["fiber-ai.update_webhook_endpoint"] = { method = "PATCH", url = "https://api.fiber.ai/v1/webhooks/endpoints/{endpointId}", path = {"endpointId"}, body = {"url", "eventTypes", "description", "disabled"} },
    ["fiber-ai.validate_phone_number"] = { method = "POST", url = "https://api.fiber.ai/v1/validate-phone/single", body = {"phoneNumber", "patience"} },
    ["fiber-ai.webpage_screenshot"] = { method = "POST", url = "https://api.fiber.ai/v1/live-fetch/webpage/screenshot", body = {"url", "fullPage", "format", "country"} },
    ["fiber-ai.yelp_place"] = { method = "POST", url = "https://api.fiber.ai/v1/yelp/place", body = {"placeId"} },
    ["fiber-ai.yelp_reviews"] = { method = "POST", url = "https://api.fiber.ai/v1/yelp/reviews", body = {"placeId", "sortBy", "ratings", "keywords", "languageCode", "nextPageToken"} },
    ["fiber-ai.yelp_search"] = { method = "POST", url = "https://api.fiber.ai/v1/yelp/search", body = {"categories", "location", "sortBy", "nextPageToken"} },
    ["fiber-ai.youtube_channel"] = { method = "POST", url = "https://api.fiber.ai/v1/youtube/channel", body = {"channelIdentifier", "nextPageToken"} },
    ["fiber-ai.youtube_search"] = { method = "POST", url = "https://api.fiber.ai/v1/youtube/search", body = {"query", "nextPageToken"} },
    ["fiber-ai.youtube_transcript"] = { method = "POST", url = "https://api.fiber.ai/v1/youtube/transcript", body = {"videoId", "languageCode"} },
    ["fiber-ai.youtube_video_comments"] = { method = "POST", url = "https://api.fiber.ai/v1/youtube/video-comments", body = {"videoId", "nextPageToken"} },
    ["fiber-ai.youtube_video_details"] = { method = "POST", url = "https://api.fiber.ai/v1/youtube/video-details", body = {"videoId"} },
  },
}
