-- Neon — every call this API accepts, as data.
--
-- GENERATED from https://neon.tech/openapi.json
-- Published on the vendor's own documentation site (https://neon.tech).
-- 163 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "neon",
  name = "Neon",
  base = "https://console.neon.tech/api",
  docs = "https://nango.dev/docs/api-integrations/neon",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "NEON_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["neon.accept_project_transfer_request"] = { method = "PUT", url = "https://console.neon.tech/api/v2/projects/{project_id}/transfer_requests/{request_id}", path = {"project_id", "request_id"}, body = {"org_id"} },
    ["neon.add_branch_neon_auth_oauth_provider"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/oauth_providers", path = {"project_id", "branch_id"}, body = {"id", "client_id", "client_secret", "microsoft_tenant_id"} },
    ["neon.add_branch_neon_auth_trusted_domain"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/domains", path = {"project_id", "branch_id"}, body = {"domain", "auth_provider"} },
    ["neon.add_project_jwks"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/jwks", path = {"project_id"}, body = {"jwks_url", "provider_name", "branch_id", "jwt_audience", "role_names", "skip_role_creation"} },
    ["neon.assign_organization_vpcendpoint"] = { method = "POST", url = "https://console.neon.tech/api/v2/organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}", path = {"org_id", "region_id", "vpc_endpoint_id"}, body = {"label"} },
    ["neon.assign_project_vpcendpoint"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/vpc_endpoints/{vpc_endpoint_id}", path = {"project_id", "vpc_endpoint_id"}, body = {"label"} },
    ["neon.count_project_branches"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/count", path = {"project_id"}, query = {"search"} },
    ["neon.create_api_key"] = { method = "POST", url = "https://console.neon.tech/api/v2/api_keys", body = {"key_name"} },
    ["neon.create_branch_neon_auth_new_user"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/users", path = {"project_id", "branch_id"}, body = {"email", "name"} },
    ["neon.create_credential"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/credentials", path = {"project_id", "branch_id"}, body = {"name", "scopes", "principal_type"} },
    ["neon.create_neon_auth"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth", path = {"project_id", "branch_id"}, body = {"auth_provider", "database_name"} },
    ["neon.create_neon_auth_provider_sdkkeys"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/auth/keys", body = {"project_id", "auth_provider"} },
    ["neon.create_org_api_key"] = { method = "POST", url = "https://console.neon.tech/api/v2/organizations/{org_id}/api_keys", path = {"org_id"}, body = {"key_name"} },
    ["neon.create_organization_invitations"] = { method = "POST", url = "https://console.neon.tech/api/v2/organizations/{org_id}/invitations", path = {"org_id"}, body = {"invitations"} },
    ["neon.create_project"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects", body = {"project"} },
    ["neon.create_project_branch"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches", path = {"project_id"}, body = {"endpoints", "branch"} },
    ["neon.create_project_branch_anonymized"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branch_anonymized", path = {"project_id"}, body = {"annotation_value"} },
    ["neon.create_project_branch_bucket"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/buckets", path = {"project_id", "branch_id"}, body = {"name", "access_level"} },
    ["neon.create_project_branch_data_api"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/data-api/{database_name}", path = {"project_id", "branch_id", "database_name"}, body = {"auth_provider", "jwks_url", "provider_name", "jwt_audience", "add_default_grants", "skip_auth_schema", "settings"} },
    ["neon.create_project_branch_database"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/databases", path = {"project_id", "branch_id"}, body = {"database"} },
    ["neon.create_project_branch_function_deployment"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/functions/{slug}/deployments", path = {"project_id", "branch_id", "slug"}, body = {"zip", "runtime", "environment"} },
    ["neon.create_project_branch_role"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/roles", path = {"project_id", "branch_id"}, body = {"role"} },
    ["neon.create_project_branch_trigger"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/triggers", path = {"project_id", "branch_id"} },
    ["neon.create_project_endpoint"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/endpoints", path = {"project_id"}, body = {"endpoint"} },
    ["neon.create_project_transfer_request"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/transfer_requests", path = {"project_id"}, body = {"ttl_seconds"} },
    ["neon.create_snapshot"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/snapshot", path = {"project_id", "branch_id"}, query = {"lsn", "timestamp", "name", "expires_at"} },
    ["neon.delete_branch_neon_auth_oauth_provider"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}", path = {"project_id", "branch_id", "oauth_provider_id"} },
    ["neon.delete_branch_neon_auth_trusted_domain"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/domains", path = {"project_id", "branch_id"}, body = {"auth_provider", "domains"} },
    ["neon.delete_branch_neon_auth_user"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}", path = {"project_id", "branch_id", "auth_user_id"} },
    ["neon.delete_organization_spending_limit"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/organizations/{org_id}/billing/spending_limit", path = {"org_id"} },
    ["neon.delete_organization_vpcendpoint"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}", path = {"org_id", "region_id", "vpc_endpoint_id"} },
    ["neon.delete_project"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}", path = {"project_id"} },
    ["neon.delete_project_branch"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}", path = {"project_id", "branch_id"} },
    ["neon.delete_project_branch_bucket"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}", path = {"project_id", "branch_id", "bucket_name"} },
    ["neon.delete_project_branch_bucket_object"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects/{object_key}", path = {"project_id", "branch_id", "bucket_name", "object_key"} },
    ["neon.delete_project_branch_bucket_objects_by_prefix"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects-by-prefix", path = {"project_id", "branch_id", "bucket_name"}, query = {"prefix"} },
    ["neon.delete_project_branch_custom_domain"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/custom-domains/{domain}", path = {"project_id", "branch_id", "domain"} },
    ["neon.delete_project_branch_data_api"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/data-api/{database_name}", path = {"project_id", "branch_id", "database_name"} },
    ["neon.delete_project_branch_database"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/databases/{database_name}", path = {"project_id", "branch_id", "database_name"} },
    ["neon.delete_project_branch_function"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/functions/{slug}", path = {"project_id", "branch_id", "slug"} },
    ["neon.delete_project_branch_role"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/roles/{role_name}", path = {"project_id", "branch_id", "role_name"} },
    ["neon.delete_project_branch_trigger"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/triggers/{trigger_id}", path = {"project_id", "branch_id", "trigger_id"} },
    ["neon.delete_project_endpoint"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/endpoints/{endpoint_id}", path = {"project_id", "endpoint_id"} },
    ["neon.delete_project_jwks"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/jwks/{jwks_id}", path = {"project_id", "jwks_id"} },
    ["neon.delete_project_vpcendpoint"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/vpc_endpoints/{vpc_endpoint_id}", path = {"project_id", "vpc_endpoint_id"} },
    ["neon.delete_snapshot"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/snapshots/{snapshot_id}", path = {"project_id", "snapshot_id"} },
    ["neon.disable_neon_auth"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth", path = {"project_id", "branch_id"}, body = {"delete_data"} },
    ["neon.finalize_restore_branch"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/finalize_restore", path = {"project_id", "branch_id"}, body = {"name"} },
    ["neon.get_active_regions"] = { method = "GET", url = "https://console.neon.tech/api/v2/regions", query = {"org_id"} },
    ["neon.get_anonymized_branch_status"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/anonymized_status", path = {"project_id", "branch_id"} },
    ["neon.get_auth_details"] = { method = "GET", url = "https://console.neon.tech/api/v2/auth" },
    ["neon.get_available_preload_libraries"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/available_preload_libraries", path = {"project_id"} },
    ["neon.get_connection_uri"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/connection_uri", path = {"project_id"}, query = {"branch_id", "endpoint_id", "database_name", "role_name", "pooled"} },
    ["neon.get_consumption_history_per_branch_v2"] = { method = "GET", url = "https://console.neon.tech/api/v2/consumption_history/v2/branches", query = {"cursor", "limit", "project_ids", "branch_ids", "from", "to", "granularity", "org_id", "metrics"} },
    ["neon.get_consumption_history_per_project"] = { method = "GET", url = "https://console.neon.tech/api/v2/consumption_history/projects", query = {"cursor", "limit", "project_ids", "from", "to", "granularity", "org_id", "include_v1_metrics", "metrics"} },
    ["neon.get_consumption_history_per_project_v2"] = { method = "GET", url = "https://console.neon.tech/api/v2/consumption_history/v2/projects", query = {"cursor", "limit", "project_ids", "from", "to", "granularity", "org_id", "metrics"} },
    ["neon.get_current_user_info"] = { method = "GET", url = "https://console.neon.tech/api/v2/users/me" },
    ["neon.get_current_user_organizations"] = { method = "GET", url = "https://console.neon.tech/api/v2/users/me/organizations" },
    ["neon.get_masking_rules"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/masking_rules", path = {"project_id", "branch_id"} },
    ["neon.get_neon_auth"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth", path = {"project_id", "branch_id"} },
    ["neon.get_neon_auth_allow_localhost"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/allow_localhost", path = {"project_id", "branch_id"} },
    ["neon.get_neon_auth_email_and_password_config"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/email_and_password", path = {"project_id", "branch_id"} },
    ["neon.get_neon_auth_email_provider"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/email_provider", path = {"project_id", "branch_id"} },
    ["neon.get_neon_auth_phone_number_plugin"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/plugins/phone-number", path = {"project_id", "branch_id"} },
    ["neon.get_neon_auth_plugin_configs"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/plugins", path = {"project_id", "branch_id"} },
    ["neon.get_neon_auth_webhook_config"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/webhooks", path = {"project_id", "branch_id"} },
    ["neon.get_organization"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}", path = {"org_id"} },
    ["neon.get_organization_invitations"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}/invitations", path = {"org_id"} },
    ["neon.get_organization_member"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}/members/{member_id}", path = {"org_id", "member_id"} },
    ["neon.get_organization_members"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}/members", path = {"org_id"}, query = {"sort_by", "cursor", "sort_order", "limit"} },
    ["neon.get_organization_spending_limit"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}/billing/spending_limit", path = {"org_id"} },
    ["neon.get_organization_vpcendpoint_details"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}", path = {"org_id", "region_id", "vpc_endpoint_id"} },
    ["neon.get_project"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}", path = {"project_id"} },
    ["neon.get_project_advisor_security_issues"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/advisors", path = {"project_id"}, query = {"branch_id", "database_name", "category", "min_severity"} },
    ["neon.get_project_branch"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}", path = {"project_id", "branch_id"} },
    ["neon.get_project_branch_ai_gateway"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/ai_gateway", path = {"project_id", "branch_id"} },
    ["neon.get_project_branch_bucket_object"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects/{object_key}/download", path = {"project_id", "branch_id", "bucket_name", "object_key"} },
    ["neon.get_project_branch_data_api"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/data-api/{database_name}", path = {"project_id", "branch_id", "database_name"} },
    ["neon.get_project_branch_database"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/databases/{database_name}", path = {"project_id", "branch_id", "database_name"} },
    ["neon.get_project_branch_function"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/functions/{slug}", path = {"project_id", "branch_id", "slug"} },
    ["neon.get_project_branch_role"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/roles/{role_name}", path = {"project_id", "branch_id", "role_name"} },
    ["neon.get_project_branch_role_password"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/roles/{role_name}/reveal_password", path = {"project_id", "branch_id", "role_name"} },
    ["neon.get_project_branch_schema"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/schema", path = {"project_id", "branch_id"}, query = {"db_name", "lsn", "timestamp", "format"} },
    ["neon.get_project_branch_schema_comparison"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/compare_schema", path = {"project_id", "branch_id"}, query = {"base_branch_id", "db_name", "lsn", "timestamp", "base_lsn", "base_timestamp"} },
    ["neon.get_project_branch_storage"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/storage", path = {"project_id", "branch_id"} },
    ["neon.get_project_branch_trigger"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/triggers/{trigger_id}", path = {"project_id", "branch_id", "trigger_id"} },
    ["neon.get_project_endpoint"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/endpoints/{endpoint_id}", path = {"project_id", "endpoint_id"} },
    ["neon.get_project_jwks"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/jwks", path = {"project_id"} },
    ["neon.get_project_operation"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/operations/{operation_id}", path = {"project_id", "operation_id"} },
    ["neon.get_snapshot_schedule"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/backup_schedule", path = {"project_id", "branch_id"} },
    ["neon.grant_permission_to_project"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/permissions", path = {"project_id"}, body = {"email"} },
    ["neon.list_api_keys"] = { method = "GET", url = "https://console.neon.tech/api/v2/api_keys" },
    ["neon.list_branch_neon_auth_oauth_providers"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/oauth_providers", path = {"project_id", "branch_id"} },
    ["neon.list_branch_neon_auth_trusted_domains"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/domains", path = {"project_id", "branch_id"} },
    ["neon.list_credentials"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/credentials", path = {"project_id", "branch_id"} },
    ["neon.list_org_api_keys"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}/api_keys", path = {"org_id"} },
    ["neon.list_organization_vpcendpoints"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints", path = {"org_id", "region_id"} },
    ["neon.list_organization_vpcendpoints_all_regions"] = { method = "GET", url = "https://console.neon.tech/api/v2/organizations/{org_id}/vpc/vpc_endpoints", path = {"org_id"} },
    ["neon.list_project_branch_bucket_objects"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects", path = {"project_id", "branch_id", "bucket_name"}, query = {"prefix", "delimiter", "cursor", "limit"} },
    ["neon.list_project_branch_buckets"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/buckets", path = {"project_id", "branch_id"} },
    ["neon.list_project_branch_custom_domains"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/custom-domains", path = {"project_id", "branch_id"}, query = {"cursor", "limit"} },
    ["neon.list_project_branch_databases"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/databases", path = {"project_id", "branch_id"} },
    ["neon.list_project_branch_endpoints"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/endpoints", path = {"project_id", "branch_id"} },
    ["neon.list_project_branch_functions"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/functions", path = {"project_id", "branch_id"}, query = {"cursor", "limit"} },
    ["neon.list_project_branch_log_field_values"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/logs/fields/{field_name}/values", path = {"project_id", "branch_id", "field_name"}, query = {"since", "start_time", "end_time", "source", "limit"} },
    ["neon.list_project_branch_log_fields"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/logs/fields", path = {"project_id", "branch_id"} },
    ["neon.list_project_branch_roles"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/roles", path = {"project_id", "branch_id"} },
    ["neon.list_project_branch_triggers"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/triggers", path = {"project_id", "branch_id"} },
    ["neon.list_project_branches"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches", path = {"project_id"}, query = {"search", "sort_by", "cursor", "sort_order", "limit", "include_deleted"} },
    ["neon.list_project_endpoints"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/endpoints", path = {"project_id"} },
    ["neon.list_project_members"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/members", path = {"project_id"}, query = {"cursor", "limit"} },
    ["neon.list_project_operations"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/operations", path = {"project_id"}, query = {"cursor", "limit"} },
    ["neon.list_project_permissions"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/permissions", path = {"project_id"} },
    ["neon.list_project_vpcendpoints"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/vpc_endpoints", path = {"project_id"} },
    ["neon.list_projects"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects", query = {"cursor", "limit", "search", "org_id", "timeout", "recoverable"} },
    ["neon.list_shared_projects"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/shared", query = {"cursor", "limit", "search", "timeout"} },
    ["neon.list_snapshots"] = { method = "GET", url = "https://console.neon.tech/api/v2/projects/{project_id}/snapshots", path = {"project_id"} },
    ["neon.presign_project_branch_bucket_object"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects/{object_key}/presign", path = {"project_id", "branch_id", "bucket_name", "object_key"}, body = {"operation", "content_type", "expires_in_seconds"} },
    ["neon.query_project_branch_logs"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/logs/query", path = {"project_id", "branch_id"}, body = {"since", "start_time", "end_time", "limit", "cursor", "sort_order", "source", "service_name", "scope_name", "minimum_severity", "severity_text", "body_contains", "trace_id", "logql"} },
    ["neon.recover_project"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/recover", path = {"project_id"} },
    ["neon.register_project_branch_custom_domain"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/custom-domains", path = {"project_id", "branch_id"}, body = {"domain", "entity_type", "entity_id"} },
    ["neon.remove_organization_member"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/organizations/{org_id}/members/{member_id}", path = {"org_id", "member_id"} },
    ["neon.remove_project_member_role"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/members/{member_id}/role", path = {"project_id", "member_id"}, query = {"confirm_self_lockout"} },
    ["neon.reset_project_branch_role_password"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/roles/{role_name}/reset_password", path = {"project_id", "branch_id", "role_name"} },
    ["neon.restart_project_endpoint"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/endpoints/{endpoint_id}/restart", path = {"project_id", "endpoint_id"} },
    ["neon.restore_project_branch"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/restore", path = {"project_id", "branch_id"}, body = {"source_branch_id", "source_lsn", "source_timestamp", "preserve_under_name"} },
    ["neon.restore_snapshot"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/snapshots/{snapshot_id}/restore", path = {"project_id", "snapshot_id"}, query = {"name"}, body = {"name", "target_branch_id", "finalize_restore"} },
    ["neon.reveal_credential"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/credentials/{token_id}/reveal", path = {"project_id", "branch_id", "token_id"} },
    ["neon.revoke_api_key"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/api_keys/{key_id}", path = {"key_id"} },
    ["neon.revoke_credential"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/credentials/{token_id}", path = {"project_id", "branch_id", "token_id"} },
    ["neon.revoke_org_api_key"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/organizations/{org_id}/api_keys/{key_id}", path = {"org_id", "key_id"} },
    ["neon.revoke_permission_from_project"] = { method = "DELETE", url = "https://console.neon.tech/api/v2/projects/{project_id}/permissions/{permission_id}", path = {"project_id", "permission_id"} },
    ["neon.rotate_credential"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/credentials/{token_id}/rotate", path = {"project_id", "branch_id", "token_id"} },
    ["neon.send_neon_auth_email_provider_test"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/email_provider/test", path = {"project_id", "branch_id"}, body = {"recipient_email"} },
    ["neon.set_default_project_branch"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/set_as_default", path = {"project_id", "branch_id"} },
    ["neon.set_organization_spending_limit"] = { method = "PUT", url = "https://console.neon.tech/api/v2/organizations/{org_id}/billing/spending_limit", path = {"org_id"}, body = {"spending_limit_cents"} },
    ["neon.set_project_member_role"] = { method = "PUT", url = "https://console.neon.tech/api/v2/projects/{project_id}/members/{member_id}/role", path = {"project_id", "member_id"}, query = {"confirm_self_demotion"}, body = {"role"} },
    ["neon.set_snapshot_schedule"] = { method = "PUT", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/backup_schedule", path = {"project_id", "branch_id"}, body = {"schedule"} },
    ["neon.start_anonymization"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/anonymize", path = {"project_id", "branch_id"} },
    ["neon.start_project_endpoint"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/endpoints/{endpoint_id}/start", path = {"project_id", "endpoint_id"} },
    ["neon.suspend_project_endpoint"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/{project_id}/endpoints/{endpoint_id}/suspend", path = {"project_id", "endpoint_id"} },
    ["neon.transfer_neon_auth_provider_project"] = { method = "POST", url = "https://console.neon.tech/api/v2/projects/auth/transfer_ownership", body = {"project_id", "auth_provider"} },
    ["neon.transfer_projects_from_org_to_org"] = { method = "POST", url = "https://console.neon.tech/api/v2/organizations/{source_org_id}/projects/transfer", path = {"source_org_id"}, body = {"destination_org_id", "project_ids"} },
    ["neon.update_branch_neon_auth_oauth_provider"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}", path = {"project_id", "branch_id", "oauth_provider_id"}, body = {"client_id", "client_secret", "microsoft_tenant_id"} },
    ["neon.update_masking_rules"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/masking_rules", path = {"project_id", "branch_id"}, body = {"masking_rules"} },
    ["neon.update_neon_auth_allow_localhost"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/allow_localhost", path = {"project_id", "branch_id"}, body = {"allow_localhost"} },
    ["neon.update_neon_auth_config"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/config", path = {"project_id", "branch_id"}, body = {"name"} },
    ["neon.update_neon_auth_email_and_password_config"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/email_and_password", path = {"project_id", "branch_id"}, body = {"enabled", "email_verification_method", "require_email_verification", "auto_sign_in_after_verification", "send_verification_email_on_sign_up", "send_verification_email_on_sign_in", "disable_sign_up"} },
    ["neon.update_neon_auth_email_provider"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/email_provider", path = {"project_id", "branch_id"} },
    ["neon.update_neon_auth_magic_link_plugin"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/plugins/magic-link", path = {"project_id", "branch_id"}, body = {"enabled", "expires_in", "disable_sign_up"} },
    ["neon.update_neon_auth_organization_plugin"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/plugins/organization", path = {"project_id", "branch_id"}, body = {"enabled", "organization_limit", "membership_limit", "creator_role", "send_invitation_email"} },
    ["neon.update_neon_auth_phone_number_plugin"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/plugins/phone-number", path = {"project_id", "branch_id"}, body = {"enabled", "otp_expires_in"} },
    ["neon.update_neon_auth_user_role"] = { method = "PUT", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}/role", path = {"project_id", "branch_id", "auth_user_id"}, body = {"roles"} },
    ["neon.update_neon_auth_webhook_config"] = { method = "PUT", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/auth/webhooks", path = {"project_id", "branch_id"}, body = {"enabled", "webhook_url", "enabled_events", "timeout_seconds"} },
    ["neon.update_organization_member"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/organizations/{org_id}/members/{member_id}", path = {"org_id", "member_id"}, body = {"role"} },
    ["neon.update_project"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}", path = {"project_id"}, body = {"project"} },
    ["neon.update_project_branch"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}", path = {"project_id", "branch_id"}, body = {"branch"} },
    ["neon.update_project_branch_data_api"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/data-api/{database_name}", path = {"project_id", "branch_id", "database_name"}, body = {"settings"} },
    ["neon.update_project_branch_database"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/databases/{database_name}", path = {"project_id", "branch_id", "database_name"}, body = {"database"} },
    ["neon.update_project_branch_function"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/functions/{slug}", path = {"project_id", "branch_id", "slug"}, body = {"name"} },
    ["neon.update_project_branch_trigger"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/branches/{branch_id}/triggers/{trigger_id}", path = {"project_id", "branch_id", "trigger_id"} },
    ["neon.update_project_endpoint"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/endpoints/{endpoint_id}", path = {"project_id", "endpoint_id"}, body = {"endpoint"} },
    ["neon.update_snapshot"] = { method = "PATCH", url = "https://console.neon.tech/api/v2/projects/{project_id}/snapshots/{snapshot_id}", path = {"project_id", "snapshot_id"}, body = {"snapshot"} },
  },
}
