-- Embat — every call this API accepts, as data.
--
-- GENERATED from https://api.embat.io/openapi.json
-- Published on the vendor's own documentation site (https://api.embat.io).
-- 104 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "embat",
  name = "Embat",
  base = "https://api.embat.io",
  docs = "https://nango.dev/docs/api-integrations/embat",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "EMBAT_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["embat.add_attribute_values_attributes_company_id_custom_id_values_bulk_post"] = { method = "POST", url = "https://api.embat.io/attributes/{companyId}/{customId}/values/bulk", path = {"customId", "companyId"}, body = {"data"} },
    ["embat.add_attribute_values_operations_company_id_attributes_bulk_post"] = { method = "POST", url = "https://api.embat.io/operations/{companyId}/attributes/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.auth_token_authentication_token_post"] = { method = "POST", url = "https://api.embat.io/authentication/token", body = {"email", "password"} },
    ["embat.create_accounting_entries_bulk_accountingentries_company_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/accountingentries/{companyId}/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.create_accounting_entry_accountingentries_company_id_post"] = { method = "POST", url = "https://api.embat.io/accountingentries/{companyId}", path = {"companyId"}, body = {"accountingCode", "counterpartAccountingCode", "accountingName", "assetAmount", "accountingAssetAmount", "balance", "liabilityAmount", "accountingLiabilityAmount", "currency", "accountingCurrency", "contactCustomId", "exchangeRate", "additionalInfo", "description", "documentId", "transactionsIds", "paymentId", "date", "attributes", "customId", "accountingEntryCode", "accountingEntryCodeId"} },
    ["embat.create_accountings_account_accountingaccounts_company_id_post"] = { method = "POST", url = "https://api.embat.io/accountingaccounts/{companyId}", path = {"companyId"}, body = {"active", "type", "accountingName", "collective", "additionalInfo", "attributes", "accountingCode"} },
    ["embat.create_accountings_accounts_bulk_accountingaccounts_company_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/accountingaccounts/{companyId}/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.create_attribute_attributes_company_id_post"] = { method = "POST", url = "https://api.embat.io/attributes/{companyId}", path = {"companyId"}, body = {"customId", "source", "active", "name", "type", "required", "values", "parentCustomId"} },
    ["embat.create_attributes_bulk_attributes_company_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/attributes/{companyId}/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.create_contact_contacts_company_id_post"] = { method = "POST", url = "https://api.embat.io/contacts/{companyId}", path = {"companyId"}, body = {"tradeName", "legalName", "taxId", "contact", "address", "contactType", "type", "accounts", "paymentsAccounts", "additionalInfo", "accountingCode", "paymentMethod", "paymentTerms", "attributes", "customId"} },
    ["embat.create_contacts_bulk_contacts_company_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/contacts/{companyId}/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.create_file_emission_files_company_id_bank_id_post"] = { method = "POST", url = "https://api.embat.io/files/{companyId}/{bankId}", path = {"companyId", "bankId"}, body = {"file", "format"} },
    ["embat.create_log_logs_company_id_post"] = { method = "POST", url = "https://api.embat.io/logs/{companyId}", path = {"companyId"}, body = {"erp", "erpVersion", "connectorVersion", "level", "code", "message"} },
    ["embat.create_logs_bulk_logs_company_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/logs/{companyId}/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.create_manual_transactions_bulk_transactions_company_id_product_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/transactions/{companyId}/{productId}/bulk", path = {"companyId", "productId"}, body = {"data"} },
    ["embat.create_operation_operations_company_id_post"] = { method = "POST", url = "https://api.embat.io/operations/{companyId}", path = {"companyId"}, body = {"status", "paymentDate", "chargeAccount", "contactAccount", "issuanceDate", "dueDate", "accountingCode", "accountingName", "operationsCustomIds", "concept", "amount", "accountingAmount", "pendingAmount", "pendingAccountingAmount", "currency", "accountingCurrency", "exchangeRate", "paymentMethod", "contact", "additionalInfo", "invoiceGroupDocumentId", "sync", "documentId", "attributes", "externalReference", "comments", "customId", "documentType", "generatedFrom"} },
    ["embat.create_operations_bulk_operations_company_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/operations/{companyId}/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.create_payment_payments_company_id_post"] = { method = "POST", url = "https://api.embat.io/payments/{companyId}", path = {"companyId"}, body = {"method", "transactionId", "operations", "productId", "contactCustomId", "date", "concept", "amount", "accountingAmount", "currency", "accountingCurrency", "exchangeRate", "additionalInfo", "attributes", "customId"} },
    ["embat.create_payments_bulk_payments_company_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/payments/{companyId}/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.create_reconciling_item_reconcilingitems_company_id_post"] = { method = "POST", url = "https://api.embat.io/reconcilingitems/{companyId}", path = {"companyId"}, body = {"amount", "currency", "date", "description", "metadata", "additionalInfo", "customId", "reconcilingSourceCustomId"} },
    ["embat.create_reconciling_items_bulk_reconcilingitems_company_id_bulk_post"] = { method = "POST", url = "https://api.embat.io/reconcilingitems/{companyId}/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.create_reconciling_source_reconcilingsources_company_id_post"] = { method = "POST", url = "https://api.embat.io/reconcilingsources/{companyId}", path = {"companyId"}, body = {"name", "additionalInfo", "matchingMetadataKey", "customId"} },
    ["embat.delete_accounting_entries_bulk_accountingentries_company_id_delete"] = { method = "DELETE", url = "https://api.embat.io/accountingentries/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.delete_accounting_entries_bulk_by_entry_code_accountingentries_accountingentrycode_company_id_delete"] = { method = "DELETE", url = "https://api.embat.io/accountingentries/accountingentrycode/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.delete_accounting_entry_accountingentries_company_id_custom_id_delete"] = { method = "DELETE", url = "https://api.embat.io/accountingentries/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.delete_accountings_account_accountingaccounts_company_id_accounting_code_delete"] = { method = "DELETE", url = "https://api.embat.io/accountingaccounts/{companyId}/{accountingCode}", path = {"accountingCode", "companyId"} },
    ["embat.delete_accountings_accounts_bulk_accountingaccounts_company_id_delete"] = { method = "DELETE", url = "https://api.embat.io/accountingaccounts/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.delete_attribute_attributes_company_id_custom_id_delete"] = { method = "DELETE", url = "https://api.embat.io/attributes/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.delete_attributes_bulk_attributes_company_id_delete"] = { method = "DELETE", url = "https://api.embat.io/attributes/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.delete_contact_contacts_company_id_custom_id_delete"] = { method = "DELETE", url = "https://api.embat.io/contacts/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.delete_contacts_bulk_contacts_company_id_delete"] = { method = "DELETE", url = "https://api.embat.io/contacts/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.delete_contacts_bulk_operations_company_id_attributes_bulk_delete"] = { method = "DELETE", url = "https://api.embat.io/operations/{companyId}/attributes/bulk", path = {"companyId"}, body = {"data"} },
    ["embat.delete_operation_operations_company_id_custom_id_delete"] = { method = "DELETE", url = "https://api.embat.io/operations/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.delete_operations_bulk_operations_company_id_delete"] = { method = "DELETE", url = "https://api.embat.io/operations/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.delete_payment_payments_company_id_custom_id_delete"] = { method = "DELETE", url = "https://api.embat.io/payments/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.delete_payments_bulk_payments_company_id_delete"] = { method = "DELETE", url = "https://api.embat.io/payments/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.delete_reconciling_item_reconcilingitems_company_id_custom_id_delete"] = { method = "DELETE", url = "https://api.embat.io/reconcilingitems/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.delete_reconciling_items_bulk_reconcilingitems_company_id_delete"] = { method = "DELETE", url = "https://api.embat.io/reconcilingitems/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.delete_reconciling_source_reconcilingsources_company_id_custom_id_delete"] = { method = "DELETE", url = "https://api.embat.io/reconcilingsources/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.download_payment_order_receipt_paymentorders_id_receipt_get"] = { method = "GET", url = "https://api.embat.io/paymentorders/{id}/receipt", path = {"id"} },
    ["embat.download_receptions_file_files_receptions_file_id_get"] = { method = "GET", url = "https://api.embat.io/files/receptions/{fileId}", path = {"fileId"} },
    ["embat.get_category_categories_company_id_id_get"] = { method = "GET", url = "https://api.embat.io/categories/{companyId}/{id}", path = {"id", "companyId"} },
    ["embat.list_accounting_entries_accountingentries_company_id_get"] = { method = "GET", url = "https://api.embat.io/accountingentries/{companyId}", path = {"companyId"}, query = {"reconciled", "accountingCode", "accountingEntryCode", "startDate", "endDate", "startUpdatedAt", "endUpdatedAt", "limit", "nextPageToken"} },
    ["embat.list_accountings_accounts_accountingaccounts_company_id_get"] = { method = "GET", url = "https://api.embat.io/accountingaccounts/{companyId}", path = {"companyId"}, query = {"limit", "nextPageToken"} },
    ["embat.list_attributes_attributes_company_id_get"] = { method = "GET", url = "https://api.embat.io/attributes/{companyId}", path = {"companyId"} },
    ["embat.list_balances_balances_company_id_get"] = { method = "GET", url = "https://api.embat.io/balances/{companyId}", path = {"companyId"}, query = {"productId", "startDate", "endDate", "limit", "nextPageToken"} },
    ["embat.list_banks_banks_company_id_get"] = { method = "GET", url = "https://api.embat.io/banks/{companyId}", path = {"companyId"} },
    ["embat.list_budgets_budgets_company_id_get"] = { method = "GET", url = "https://api.embat.io/budgets/{companyId}", path = {"companyId"}, query = {"startDate", "endDate", "status", "limit", "nextPageToken"} },
    ["embat.list_categories_categories_company_id_get"] = { method = "GET", url = "https://api.embat.io/categories/{companyId}", path = {"companyId"} },
    ["embat.list_companies_companies_get"] = { method = "GET", url = "https://api.embat.io/companies" },
    ["embat.list_company_users_companies_company_id_users_get"] = { method = "GET", url = "https://api.embat.io/companies/{companyId}/users", path = {"companyId"} },
    ["embat.list_contacts_contacts_company_id_get"] = { method = "GET", url = "https://api.embat.io/contacts/{companyId}", path = {"companyId"}, query = {"limit", "nextPageToken"} },
    ["embat.list_debt_schedule_configs_debtscheduleconfigs_company_id_get"] = { method = "GET", url = "https://api.embat.io/debtscheduleconfigs/{companyId}", path = {"companyId"}, query = {"startUpdatedAt", "endUpdatedAt", "limit", "nextPageToken"} },
    ["embat.list_files_emissions_files_emissions_get"] = { method = "GET", url = "https://api.embat.io/files/emissions", query = {"limit", "nextPageToken"} },
    ["embat.list_files_receptions_files_receptions_get"] = { method = "GET", url = "https://api.embat.io/files/receptions", query = {"limit", "nextPageToken"} },
    ["embat.list_forecasts_forecasts_company_id_get"] = { method = "GET", url = "https://api.embat.io/forecasts/{companyId}", path = {"companyId"}, query = {"scenarioId", "sync", "operations", "startDate", "endDate", "limit", "nextPageToken"} },
    ["embat.list_foreign_exchange_rates_foreignexchangerates_get"] = { method = "GET", url = "https://api.embat.io/foreignexchangerates", query = {"baseCurrency", "startDate", "endDate", "limit", "nextPageToken"} },
    ["embat.list_operations_operations_company_id_get"] = { method = "GET", url = "https://api.embat.io/operations/{companyId}", path = {"companyId"}, query = {"status", "sync", "generatedFrom", "startIssuanceDate", "endIssuanceDate", "limit", "nextPageToken"} },
    ["embat.list_operations_reconcilingitems_company_id_get"] = { method = "GET", url = "https://api.embat.io/reconcilingitems/{companyId}", path = {"companyId"}, query = {"reconcilingSourceCustomId", "reconciled", "startDate", "endDate", "limit", "nextPageToken"} },
    ["embat.list_payment_orders_paymentorders_company_id_get"] = { method = "GET", url = "https://api.embat.io/paymentorders/{companyId}", path = {"companyId"}, query = {"startPaymentDate", "endPaymentDate", "status", "beneficiaryLegalNameContains", "documentIdContains", "limit", "nextPageToken"} },
    ["embat.list_payments_payments_company_id_get"] = { method = "GET", url = "https://api.embat.io/payments/{companyId}", path = {"companyId"}, query = {"productId", "transactionId", "sync", "registered", "startDate", "endDate", "startUpdatedAt", "endUpdatedAt", "internalAttributes", "limit", "nextPageToken"} },
    ["embat.list_products_products_company_id_get"] = { method = "GET", url = "https://api.embat.io/products/{companyId}", path = {"companyId"}, query = {"manual"} },
    ["embat.list_reconciling_sources_reconcilingsources_company_id_get"] = { method = "GET", url = "https://api.embat.io/reconcilingsources/{companyId}", path = {"companyId"} },
    ["embat.list_scenarios_scenarios_company_id_get"] = { method = "GET", url = "https://api.embat.io/scenarios/{companyId}", path = {"companyId"} },
    ["embat.list_transactions_transactions_company_id_get"] = { method = "GET", url = "https://api.embat.io/transactions/{companyId}", path = {"companyId"}, query = {"productId", "sync", "startValueDate", "endValueDate", "startOperationDate", "endOperationDate", "startUpdatedAt", "endUpdatedAt", "limit", "nextPageToken"} },
    ["embat.read_operation_operations_company_id_custom_id_get"] = { method = "GET", url = "https://api.embat.io/operations/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.read_reconciling_item_reconcilingitems_company_id_custom_id_get"] = { method = "GET", url = "https://api.embat.io/reconcilingitems/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.remove_attribute_values_attributes_company_id_custom_id_values_delete"] = { method = "DELETE", url = "https://api.embat.io/attributes/{companyId}/{customId}/values", path = {"customId", "companyId"}, body = {"data"} },
    ["embat.retrieve_accounting_entry_accountingentries_company_id_custom_id_get"] = { method = "GET", url = "https://api.embat.io/accountingentries/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.retrieve_accountings_account_accountingaccounts_company_id_accounting_code_get"] = { method = "GET", url = "https://api.embat.io/accountingaccounts/{companyId}/{accountingCode}", path = {"accountingCode", "companyId"} },
    ["embat.retrieve_attribute_attributes_company_id_custom_id_get"] = { method = "GET", url = "https://api.embat.io/attributes/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.retrieve_balance_balances_company_id_id_get"] = { method = "GET", url = "https://api.embat.io/balances/{companyId}/{id}", path = {"id", "companyId"} },
    ["embat.retrieve_bank_banks_company_id_id_get"] = { method = "GET", url = "https://api.embat.io/banks/{companyId}/{id}", path = {"id", "companyId"} },
    ["embat.retrieve_company_companies_company_id_get"] = { method = "GET", url = "https://api.embat.io/companies/{companyId}", path = {"companyId"} },
    ["embat.retrieve_contact_contacts_company_id_custom_id_get"] = { method = "GET", url = "https://api.embat.io/contacts/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.retrieve_debt_schedule_config_debtscheduleconfigs_company_id_id_get"] = { method = "GET", url = "https://api.embat.io/debtscheduleconfigs/{companyId}/{id}", path = {"id", "companyId"} },
    ["embat.retrieve_forecast_forecasts_company_id_id_get"] = { method = "GET", url = "https://api.embat.io/forecasts/{companyId}/{id}", path = {"id", "companyId"} },
    ["embat.retrieve_foreign_exchange_rate_foreignexchangerates_id_get"] = { method = "GET", url = "https://api.embat.io/foreignexchangerates/{id}", path = {"id"} },
    ["embat.retrieve_payment_payments_company_id_custom_id_get"] = { method = "GET", url = "https://api.embat.io/payments/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.retrieve_product_products_company_id_id_get"] = { method = "GET", url = "https://api.embat.io/products/{companyId}/{id}", path = {"id", "companyId"} },
    ["embat.retrieve_reconciling_source_reconcilingsources_company_id_custom_id_get"] = { method = "GET", url = "https://api.embat.io/reconcilingsources/{companyId}/{customId}", path = {"customId", "companyId"} },
    ["embat.retrieve_scenario_scenarios_company_id_id_get"] = { method = "GET", url = "https://api.embat.io/scenarios/{companyId}/{id}", path = {"id", "companyId"} },
    ["embat.retrieve_transaction_transactions_company_id_id_get"] = { method = "GET", url = "https://api.embat.io/transactions/{companyId}/{id}", path = {"id", "companyId"} },
    ["embat.update_accounting_entries_bulk_accountingentries_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/accountingentries/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_accounting_entry_accountingentries_company_id_custom_id_patch"] = { method = "PATCH", url = "https://api.embat.io/accountingentries/{companyId}/{customId}", path = {"customId", "companyId"}, body = {"accountingCode", "counterpartAccountingCode", "accountingName", "assetAmount", "accountingAssetAmount", "balance", "liabilityAmount", "accountingLiabilityAmount", "currency", "accountingCurrency", "contactCustomId", "exchangeRate", "additionalInfo", "description", "documentId", "transactionsIds", "paymentId", "date", "attributes"} },
    ["embat.update_accountings_account_accountingaccounts_company_id_accounting_code_patch"] = { method = "PATCH", url = "https://api.embat.io/accountingaccounts/{companyId}/{accountingCode}", path = {"accountingCode", "companyId"}, body = {"active", "type", "accountingName", "collective", "additionalInfo", "attributes"} },
    ["embat.update_accountings_accounts_bulk_accountingaccounts_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/accountingaccounts/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_attribute_attributes_company_id_custom_id_patch"] = { method = "PATCH", url = "https://api.embat.io/attributes/{companyId}/{customId}", path = {"customId", "companyId"}, body = {"name", "active", "values", "parentCustomId"} },
    ["embat.update_attributes_bulk_attributes_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/attributes/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_contact_contacts_company_id_custom_id_patch"] = { method = "PATCH", url = "https://api.embat.io/contacts/{companyId}/{customId}", path = {"customId", "companyId"}, body = {"tradeName", "legalName", "taxId", "contact", "address", "contactType", "type", "accounts", "paymentsAccounts", "additionalInfo", "accountingCode", "paymentMethod", "paymentTerms", "attributes"} },
    ["embat.update_contacts_bulk_contacts_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/contacts/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_forecast_forecasts_company_id_id_patch"] = { method = "PATCH", url = "https://api.embat.io/forecasts/{companyId}/{id}", path = {"id", "companyId"}, body = {"additionalInfo", "sync"} },
    ["embat.update_forecasts_bulk_forecasts_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/forecasts/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_operation_operations_company_id_custom_id_patch"] = { method = "PATCH", url = "https://api.embat.io/operations/{companyId}/{customId}", path = {"customId", "companyId"}, body = {"status", "paymentDate", "chargeAccount", "contactAccount", "issuanceDate", "dueDate", "accountingCode", "accountingName", "operationsCustomIds", "concept", "amount", "accountingAmount", "pendingAmount", "pendingAccountingAmount", "currency", "accountingCurrency", "exchangeRate", "paymentMethod", "contact", "additionalInfo", "invoiceGroupDocumentId", "sync", "documentId", "attributes", "externalReference", "comments"} },
    ["embat.update_operations_bulk_operations_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/operations/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_payment_payments_company_id_custom_id_patch"] = { method = "PATCH", url = "https://api.embat.io/payments/{companyId}/{customId}", path = {"customId", "companyId"}, body = {"sync", "additionalInfo", "error", "registered"} },
    ["embat.update_payments_bulk_payments_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/payments/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_product_products_company_id_id_patch"] = { method = "PATCH", url = "https://api.embat.io/products/{companyId}/{id}", path = {"id", "companyId"}, body = {"additionalInfo", "accountingCode"} },
    ["embat.update_products_bulk_products_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/products/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_reconciling_item_reconcilingitems_company_id_custom_id_patch"] = { method = "PATCH", url = "https://api.embat.io/reconcilingitems/{companyId}/{customId}", path = {"customId", "companyId"}, body = {"amount", "currency", "date", "description", "metadata", "additionalInfo"} },
    ["embat.update_reconciling_items_bulk_reconcilingitems_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/reconcilingitems/{companyId}", path = {"companyId"}, body = {"data"} },
    ["embat.update_reconciling_source_reconcilingsources_company_id_custom_id_patch"] = { method = "PATCH", url = "https://api.embat.io/reconcilingsources/{companyId}/{customId}", path = {"customId", "companyId"}, body = {"name", "additionalInfo", "matchingMetadataKey"} },
    ["embat.update_transaction_transactions_company_id_id_patch"] = { method = "PATCH", url = "https://api.embat.io/transactions/{companyId}/{id}", path = {"id", "companyId"}, body = {"additionalInfo", "attributes", "sync"} },
    ["embat.update_transactions_bulk_transactions_company_id_patch"] = { method = "PATCH", url = "https://api.embat.io/transactions/{companyId}", path = {"companyId"}, body = {"data"} },
  },
}
