-- Atlas.so — every call this API accepts, as data.
--
-- GENERATED from https://api.atlas.so/openapi.json
-- Published on the vendor's own documentation site (https://api.atlas.so).
-- 67 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "atlas-so",
  name = "Atlas.so",
  base = "https://api.atlas.so/v1",
  docs = "https://nango.dev/docs/integrations/all/atlas-so",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "ATLAS_SO_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["atlas-so.add_conversation_tags_v1_conversations_id_tags_post"] = { method = "POST", url = "https://api.atlas.so/v1/conversations/{id}/tags", path = {"id"}, body = {"tags"} },
    ["atlas-so.create_api_v1_canned_responses_post"] = { method = "POST", url = "https://api.atlas.so/v1/canned_responses", body = {"name", "content"} },
    ["atlas-so.create_api_v1_custom_fields_post"] = { method = "POST", url = "https://api.atlas.so/v1/custom-fields", body = {"companyId", "displayName", "description", "category", "fieldMetadata", "dynamicFieldMetadata", "type", "required", "editableBy", "active", "rules", "dependsOn", "defaultValue"} },
    ["atlas-so.create_api_v1_customers_post"] = { method = "POST", url = "https://api.atlas.so/v1/customers", body = {"firstName", "lastName", "email", "phoneNumber", "externalUserId", "customFields", "defaultSenders"} },
    ["atlas-so.create_api_v1_sla_rules_post"] = { method = "POST", url = "https://api.atlas.so/v1/sla-rules", body = {"name", "segment", "priorities", "firstResponseTime", "nextResponseTime", "workingHours", "rank", "notifications", "channels", "tags", "teams", "subChannels"} },
    ["atlas-so.create_api_v1_users_post"] = { method = "POST", url = "https://api.atlas.so/v1/users", body = {"createdAt", "firstName", "lastName", "email", "profileUrl", "accessTypes"} },
    ["atlas-so.create_article_v1_helpcenter_articles_post"] = { method = "POST", url = "https://api.atlas.so/v1/helpcenter/articles", body = {"title", "categoryId", "content", "description", "tags", "slug"} },
    ["atlas-so.create_conversation_v1_conversations_post"] = { method = "POST", url = "https://api.atlas.so/v1/conversations", body = {"customerId", "startedAt", "subject", "messages", "status", "priority", "tags", "customFields", "assignedAgentId", "assignedTeamId"} },
    ["atlas-so.create_event_v1_events_post"] = { method = "POST", url = "https://api.atlas.so/v1/events", body = {"source", "icon", "objectType", "objectId", "name", "description", "payload", "createdAt"} },
    ["atlas-so.create_sidebar_v1_conversations_conversation_id_sidebars_create_post"] = { method = "POST", url = "https://api.atlas.so/v1/conversations/{conversation_id}/sidebars/create", path = {"conversation_id"}, body = {"agentEmail", "to", "cc", "subject", "body", "attachments"} },
    ["atlas-so.create_tag_groups_v1_tag_groups_post"] = { method = "POST", url = "https://api.atlas.so/v1/tag-groups", body = {"label", "color", "archived"} },
    ["atlas-so.create_tags_v1_tags_post"] = { method = "POST", url = "https://api.atlas.so/v1/tags", body = {"groupId", "label", "archived"} },
    ["atlas-so.create_webhook_subscriptions_v1_webhooks_post"] = { method = "POST", url = "https://api.atlas.so/v1/webhooks", body = {"event", "endpoint"} },
    ["atlas-so.delete_article_v1_helpcenter_articles_id_delete"] = { method = "DELETE", url = "https://api.atlas.so/v1/helpcenter/articles/{id}", path = {"id"} },
    ["atlas-so.ext_check_customer_sending_window_v1_whatsapp_messaging_is_template_required_get"] = { method = "GET", url = "https://api.atlas.so/v1/whatsapp/messaging/is-template-required", query = {"customer_id"} },
    ["atlas-so.get_api_v1_accounts_id_get"] = { method = "GET", url = "https://api.atlas.so/v1/accounts/{id}", path = {"id"} },
    ["atlas-so.get_api_v1_canned_responses_id_get"] = { method = "GET", url = "https://api.atlas.so/v1/canned_responses/{id}", path = {"id"} },
    ["atlas-so.get_api_v1_custom_fields_id_get"] = { method = "GET", url = "https://api.atlas.so/v1/custom-fields/{id}", path = {"id"} },
    ["atlas-so.get_api_v1_customers_id_get"] = { method = "GET", url = "https://api.atlas.so/v1/customers/{id}", path = {"id"} },
    ["atlas-so.get_api_v1_sla_rules_id_get"] = { method = "GET", url = "https://api.atlas.so/v1/sla-rules/{id}", path = {"id"} },
    ["atlas-so.get_api_v1_users_id_get"] = { method = "GET", url = "https://api.atlas.so/v1/users/{id}", path = {"id"} },
    ["atlas-so.get_article_v1_helpcenter_articles_id_get"] = { method = "GET", url = "https://api.atlas.so/v1/helpcenter/articles/{id}", path = {"id"} },
    ["atlas-so.get_conversation_v1_conversations_id_get"] = { method = "GET", url = "https://api.atlas.so/v1/conversations/{id}", path = {"id"} },
    ["atlas-so.get_user_status_api_v1_users_id_status_get"] = { method = "GET", url = "https://api.atlas.so/v1/users/{id}/status", path = {"id"} },
    ["atlas-so.get_via_id_v1_customers_lookup_post"] = { method = "POST", url = "https://api.atlas.so/v1/customers/lookup", body = {"id", "email", "phoneNumber", "userId"} },
    ["atlas-so.get_video_url_v1_sessions_session_id_video_get"] = { method = "GET", url = "https://api.atlas.so/v1/sessions/{session_id}/video", path = {"session_id"} },
    ["atlas-so.get_video_url_with_callback_v1_sessions_session_id_video_post"] = { method = "POST", url = "https://api.atlas.so/v1/sessions/{session_id}/video", path = {"session_id"}, body = {"callback"} },
    ["atlas-so.list_api_v1_accounts_get"] = { method = "GET", url = "https://api.atlas.so/v1/accounts", query = {"cursor", "limit"} },
    ["atlas-so.list_api_v1_custom_fields_get"] = { method = "GET", url = "https://api.atlas.so/v1/custom-fields", query = {"cursor", "limit"} },
    ["atlas-so.list_api_v1_customers_get"] = { method = "GET", url = "https://api.atlas.so/v1/customers", query = {"cursor", "limit"} },
    ["atlas-so.list_api_v1_sla_rules_get"] = { method = "GET", url = "https://api.atlas.so/v1/sla-rules", query = {"cursor", "limit"} },
    ["atlas-so.list_api_v1_users_get"] = { method = "GET", url = "https://api.atlas.so/v1/users", query = {"cursor", "limit", "email"} },
    ["atlas-so.list_articles_v1_helpcenter_articles_get"] = { method = "GET", url = "https://api.atlas.so/v1/helpcenter/articles", query = {"cursor", "limit", "categoryId", "tags", "status", "keyword"} },
    ["atlas-so.list_canned_responses_v1_canned_responses_get"] = { method = "GET", url = "https://api.atlas.so/v1/canned_responses", query = {"cursor", "limit"} },
    ["atlas-so.list_categories_v1_helpcenter_categories_get"] = { method = "GET", url = "https://api.atlas.so/v1/helpcenter/categories", query = {"cursor", "limit"} },
    ["atlas-so.list_category_articles_v1_helpcenter_categories_id_articles_get"] = { method = "GET", url = "https://api.atlas.so/v1/helpcenter/categories/{id}/articles", path = {"id"}, query = {"cursor", "limit"} },
    ["atlas-so.list_conversation_activities_v1_conversations_id_activities_get"] = { method = "GET", url = "https://api.atlas.so/v1/conversations/{id}/activities", path = {"id"}, query = {"cursor", "limit"} },
    ["atlas-so.list_conversation_messages_v1_conversations_id_messages_get"] = { method = "GET", url = "https://api.atlas.so/v1/conversations/{id}/messages", path = {"id"}, query = {"cursor", "limit"} },
    ["atlas-so.list_conversations_v1_conversations_get"] = { method = "GET", url = "https://api.atlas.so/v1/conversations", query = {"cursor", "limit", "assignedAgentId", "status", "customerId", "startDate", "endDate", "subject", "assignedToZeus"} },
    ["atlas-so.list_csat_surveys_v1_csat_surveys_get"] = { method = "GET", url = "https://api.atlas.so/v1/csat-surveys", query = {"cursor", "limit", "startDate", "endDate", "customerId", "conversationId", "hasResponse"} },
    ["atlas-so.list_events_v1_events_get"] = { method = "GET", url = "https://api.atlas.so/v1/events", query = {"cursor", "limit", "version"} },
    ["atlas-so.list_messages_from_customer_tickets_v1_messages_get"] = { method = "GET", url = "https://api.atlas.so/v1/messages", query = {"cursor", "limit", "customerId", "side", "startDate", "endDate"} },
    ["atlas-so.list_sessions_v1_sessions_get"] = { method = "GET", url = "https://api.atlas.so/v1/sessions", query = {"cursor", "limit", "externalId", "email", "pageUrl", "startedBefore", "startedAfter"} },
    ["atlas-so.list_sidebars_by_conversation_id_v1_conversations_conversation_id_sidebars_get"] = { method = "GET", url = "https://api.atlas.so/v1/conversations/{conversation_id}/sidebars", path = {"conversation_id"} },
    ["atlas-so.list_tag_groups_v1_tag_groups_get"] = { method = "GET", url = "https://api.atlas.so/v1/tag-groups", query = {"cursor", "limit"} },
    ["atlas-so.list_tags_v1_tags_get"] = { method = "GET", url = "https://api.atlas.so/v1/tags", query = {"cursor", "limit"} },
    ["atlas-so.list_wa_templates_v1_whatsapp_templates_get"] = { method = "GET", url = "https://api.atlas.so/v1/whatsapp/templates", query = {"cursor", "limit"} },
    ["atlas-so.list_webhook_logs_v1_webhooks_logs_get"] = { method = "GET", url = "https://api.atlas.so/v1/webhooks/logs", query = {"cursor", "limit"} },
    ["atlas-so.list_webhooks_v1_webhooks_get"] = { method = "GET", url = "https://api.atlas.so/v1/webhooks", query = {"cursor", "limit"} },
    ["atlas-so.patch_conversation_v1_conversations_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/conversations/{id}", path = {"id"}, body = {"updatedBy", "assignedAgentId", "subject", "status", "priority", "tags", "customFields", "snoozedUntil", "assignedTeamId", "assignedToZeus"} },
    ["atlas-so.patch_tag_groups_v1_tag_groups_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/tag-groups/{id}", path = {"id"}, body = {"label", "color", "archived"} },
    ["atlas-so.patch_tags_v1_tags_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/tags/{id}", path = {"id"}, body = {"groupId", "label", "archived"} },
    ["atlas-so.remove_conversation_tag_v1_conversations_id_tags_tag_id_delete"] = { method = "DELETE", url = "https://api.atlas.so/v1/conversations/{id}/tags/{tag_id}", path = {"id", "tag_id"} },
    ["atlas-so.save_customer_message_v1_conversations_id_customer_messages_post"] = { method = "POST", url = "https://api.atlas.so/v1/conversations/{id}/customer-messages", path = {"id"}, body = {"text", "customerId", "channel", "cc", "attachments", "subChannelIdentifier"} },
    ["atlas-so.send_csat_question_v1_csat_surveys_conversation_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/csat-surveys/{conversation_id}", path = {"conversation_id"} },
    ["atlas-so.send_message_v1_conversations_id_messages_post"] = { method = "POST", url = "https://api.atlas.so/v1/conversations/{id}/messages", path = {"id"}, body = {"text", "agentId", "type", "channel", "cc", "attachments", "whatsappTemplateId", "subChannelIdentifier"} },
    ["atlas-so.submit_csat_response_v1_csat_surveys_conversation_id_responses_post"] = { method = "POST", url = "https://api.atlas.so/v1/csat-surveys/{conversation_id}/responses", path = {"conversation_id"}, body = {"ratingStyle", "ratingValue", "comment"} },
    ["atlas-so.update_api_v1_canned_responses_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/canned_responses/{id}", path = {"id"}, body = {"name", "content"} },
    ["atlas-so.update_api_v1_custom_fields_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/custom-fields/{id}", path = {"id"}, body = {"companyId", "displayName", "description", "category", "fieldMetadata", "dynamicFieldMetadata", "type", "required", "editableBy", "active", "rules", "dependsOn", "defaultValue"} },
    ["atlas-so.update_api_v1_customers_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/customers/{id}", path = {"id"}, body = {"firstName", "lastName", "email", "phoneNumber", "externalUserId", "customFields", "defaultSenders"} },
    ["atlas-so.update_api_v1_sla_rules_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/sla-rules/{id}", path = {"id"}, body = {"name", "segment", "priorities", "firstResponseTime", "nextResponseTime", "workingHours", "rank", "notifications", "channels", "tags", "teams", "subChannels"} },
    ["atlas-so.update_api_v1_users_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/users/{id}", path = {"id"}, body = {"createdAt", "firstName", "lastName", "email", "profileUrl", "accessTypes"} },
    ["atlas-so.update_article_v1_helpcenter_articles_id_patch"] = { method = "PATCH", url = "https://api.atlas.so/v1/helpcenter/articles/{id}", path = {"id"}, body = {"title", "categoryId", "content", "description", "tags", "slug"} },
    ["atlas-so.update_sidebar_v1_conversations_conversation_id_sidebars_sidebar_id_update_post"] = { method = "POST", url = "https://api.atlas.so/v1/conversations/{conversation_id}/sidebars/{sidebar_id}/update", path = {"conversation_id", "sidebar_id"}, body = {"agentEmail", "subject", "to", "cc", "body", "attachments"} },
    ["atlas-so.update_webhook_subscriptions_v1_webhooks_id_post"] = { method = "POST", url = "https://api.atlas.so/v1/webhooks/{id}", path = {"id"}, body = {"endpoint", "status"} },
    ["atlas-so.upsert_api_v1_accounts_upsert_post"] = { method = "POST", url = "https://api.atlas.so/v1/accounts/upsert", body = {"name", "email", "website", "externalId", "customFields", "primaryContactId", "accountManagerId", "secondaryAccountManagerId"} },
    ["atlas-so.upsert_customer_api_v1_customers_upsert_post"] = { method = "POST", url = "https://api.atlas.so/v1/customers/upsert", body = {"id", "userId", "firstName", "lastName", "email", "phoneNumber", "customFields", "account", "alternatePhoneNumbers", "alternateEmails"} },
  },
}
