-- Resend — every call this API accepts, as data.
--
-- GENERATED from https://resend.com/openapi.json
-- Published on the vendor's own documentation site (https://resend.com).
-- 79 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "resend",
  name = "Resend",
  base = "https://api.resend.com",
  docs = "https://nango.dev/docs/api-integrations/resend",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "RESEND_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["resend.delete_api_keys_api_key_id"] = { method = "DELETE", url = "https://api.resend.com/api-keys/{api_key_id}", path = {"api_key_id"} },
    ["resend.delete_automations_automation_id"] = { method = "DELETE", url = "https://api.resend.com/automations/{automation_id}", path = {"automation_id"} },
    ["resend.delete_broadcasts_id"] = { method = "DELETE", url = "https://api.resend.com/broadcasts/{id}", path = {"id"} },
    ["resend.delete_contact_properties_id"] = { method = "DELETE", url = "https://api.resend.com/contact-properties/{id}", path = {"id"} },
    ["resend.delete_contacts_contact_id_segments_segment_id"] = { method = "DELETE", url = "https://api.resend.com/contacts/{contact_id}/segments/{segment_id}", path = {"contact_id", "segment_id"} },
    ["resend.delete_contacts_id"] = { method = "DELETE", url = "https://api.resend.com/contacts/{id}", path = {"id"} },
    ["resend.delete_domains_domain_id"] = { method = "DELETE", url = "https://api.resend.com/domains/{domain_id}", path = {"domain_id"} },
    ["resend.delete_events_identifier"] = { method = "DELETE", url = "https://api.resend.com/events/{identifier}", path = {"identifier"} },
    ["resend.delete_segments_id"] = { method = "DELETE", url = "https://api.resend.com/segments/{id}", path = {"id"} },
    ["resend.delete_templates_id"] = { method = "DELETE", url = "https://api.resend.com/templates/{id}", path = {"id"} },
    ["resend.delete_topics_id"] = { method = "DELETE", url = "https://api.resend.com/topics/{id}", path = {"id"} },
    ["resend.delete_webhooks_webhook_id"] = { method = "DELETE", url = "https://api.resend.com/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["resend.get_api_keys"] = { method = "GET", url = "https://api.resend.com/api-keys", query = {"limit", "after", "before"} },
    ["resend.get_automations"] = { method = "GET", url = "https://api.resend.com/automations", query = {"status", "limit", "after", "before"} },
    ["resend.get_automations_automation_id"] = { method = "GET", url = "https://api.resend.com/automations/{automation_id}", path = {"automation_id"} },
    ["resend.get_automations_automation_id_runs"] = { method = "GET", url = "https://api.resend.com/automations/{automation_id}/runs", path = {"automation_id"}, query = {"status", "limit", "after", "before"} },
    ["resend.get_automations_automation_id_runs_run_id"] = { method = "GET", url = "https://api.resend.com/automations/{automation_id}/runs/{run_id}", path = {"automation_id", "run_id"} },
    ["resend.get_broadcasts"] = { method = "GET", url = "https://api.resend.com/broadcasts", query = {"limit", "after", "before"} },
    ["resend.get_broadcasts_id"] = { method = "GET", url = "https://api.resend.com/broadcasts/{id}", path = {"id"} },
    ["resend.get_contact_properties"] = { method = "GET", url = "https://api.resend.com/contact-properties", query = {"limit", "after", "before"} },
    ["resend.get_contact_properties_id"] = { method = "GET", url = "https://api.resend.com/contact-properties/{id}", path = {"id"} },
    ["resend.get_contacts"] = { method = "GET", url = "https://api.resend.com/contacts", query = {"segment_id", "limit", "after", "before"} },
    ["resend.get_contacts_contact_id_segments"] = { method = "GET", url = "https://api.resend.com/contacts/{contact_id}/segments", path = {"contact_id"}, query = {"limit", "after", "before"} },
    ["resend.get_contacts_contact_id_topics"] = { method = "GET", url = "https://api.resend.com/contacts/{contact_id}/topics", path = {"contact_id"}, query = {"limit", "after", "before"} },
    ["resend.get_contacts_id"] = { method = "GET", url = "https://api.resend.com/contacts/{id}", path = {"id"} },
    ["resend.get_domains"] = { method = "GET", url = "https://api.resend.com/domains", query = {"limit", "after", "before"} },
    ["resend.get_domains_domain_id"] = { method = "GET", url = "https://api.resend.com/domains/{domain_id}", path = {"domain_id"} },
    ["resend.get_emails"] = { method = "GET", url = "https://api.resend.com/emails", query = {"limit", "after", "before"} },
    ["resend.get_emails_email_id"] = { method = "GET", url = "https://api.resend.com/emails/{email_id}", path = {"email_id"} },
    ["resend.get_emails_email_id_attachments"] = { method = "GET", url = "https://api.resend.com/emails/{email_id}/attachments", path = {"email_id"}, query = {"limit", "after", "before"} },
    ["resend.get_emails_email_id_attachments_attachment_id"] = { method = "GET", url = "https://api.resend.com/emails/{email_id}/attachments/{attachment_id}", path = {"email_id", "attachment_id"} },
    ["resend.get_emails_receiving"] = { method = "GET", url = "https://api.resend.com/emails/receiving", query = {"limit", "after", "before"} },
    ["resend.get_emails_receiving_email_id"] = { method = "GET", url = "https://api.resend.com/emails/receiving/{email_id}", path = {"email_id"} },
    ["resend.get_emails_receiving_email_id_attachments"] = { method = "GET", url = "https://api.resend.com/emails/receiving/{email_id}/attachments", path = {"email_id"}, query = {"limit", "after", "before"} },
    ["resend.get_emails_receiving_email_id_attachments_attachment_id"] = { method = "GET", url = "https://api.resend.com/emails/receiving/{email_id}/attachments/{attachment_id}", path = {"email_id", "attachment_id"} },
    ["resend.get_events"] = { method = "GET", url = "https://api.resend.com/events", query = {"limit", "after", "before"} },
    ["resend.get_events_identifier"] = { method = "GET", url = "https://api.resend.com/events/{identifier}", path = {"identifier"} },
    ["resend.get_logs"] = { method = "GET", url = "https://api.resend.com/logs", query = {"limit", "after", "before"} },
    ["resend.get_logs_log_id"] = { method = "GET", url = "https://api.resend.com/logs/{log_id}", path = {"log_id"} },
    ["resend.get_segments"] = { method = "GET", url = "https://api.resend.com/segments", query = {"limit", "after", "before"} },
    ["resend.get_segments_id"] = { method = "GET", url = "https://api.resend.com/segments/{id}", path = {"id"} },
    ["resend.get_templates"] = { method = "GET", url = "https://api.resend.com/templates", query = {"limit", "after", "before"} },
    ["resend.get_templates_id"] = { method = "GET", url = "https://api.resend.com/templates/{id}", path = {"id"} },
    ["resend.get_topics"] = { method = "GET", url = "https://api.resend.com/topics", query = {"limit", "after", "before"} },
    ["resend.get_topics_id"] = { method = "GET", url = "https://api.resend.com/topics/{id}", path = {"id"} },
    ["resend.get_webhooks"] = { method = "GET", url = "https://api.resend.com/webhooks", query = {"limit", "after", "before"} },
    ["resend.get_webhooks_webhook_id"] = { method = "GET", url = "https://api.resend.com/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["resend.patch_automations_automation_id"] = { method = "PATCH", url = "https://api.resend.com/automations/{automation_id}", path = {"automation_id"}, body = {"name", "status", "steps", "connections"} },
    ["resend.patch_broadcasts_id"] = { method = "PATCH", url = "https://api.resend.com/broadcasts/{id}", path = {"id"}, body = {"name", "audience_id", "segment_id", "from", "subject", "reply_to", "preview_text", "html", "text", "topic_id"} },
    ["resend.patch_contact_properties_id"] = { method = "PATCH", url = "https://api.resend.com/contact-properties/{id}", path = {"id"}, body = {"fallback_value"} },
    ["resend.patch_contacts_contact_id_topics"] = { method = "PATCH", url = "https://api.resend.com/contacts/{contact_id}/topics", path = {"contact_id"}, body = {"topics"} },
    ["resend.patch_contacts_id"] = { method = "PATCH", url = "https://api.resend.com/contacts/{id}", path = {"id"}, body = {"email", "first_name", "last_name", "unsubscribed", "properties"} },
    ["resend.patch_domains_domain_id"] = { method = "PATCH", url = "https://api.resend.com/domains/{domain_id}", path = {"domain_id"}, body = {"open_tracking", "click_tracking", "tls", "capabilities", "tracking_subdomain"} },
    ["resend.patch_emails_email_id"] = { method = "PATCH", url = "https://api.resend.com/emails/{email_id}", path = {"email_id"} },
    ["resend.patch_events_identifier"] = { method = "PATCH", url = "https://api.resend.com/events/{identifier}", path = {"identifier"}, body = {"schema"} },
    ["resend.patch_templates_id"] = { method = "PATCH", url = "https://api.resend.com/templates/{id}", path = {"id"}, body = {"name", "alias", "from", "subject", "reply_to", "html", "text", "variables"} },
    ["resend.patch_topics_id"] = { method = "PATCH", url = "https://api.resend.com/topics/{id}", path = {"id"}, body = {"name", "description", "visibility"} },
    ["resend.patch_webhooks_webhook_id"] = { method = "PATCH", url = "https://api.resend.com/webhooks/{webhook_id}", path = {"webhook_id"}, body = {"endpoint", "events", "status"} },
    ["resend.post_api_keys"] = { method = "POST", url = "https://api.resend.com/api-keys", body = {"name", "permission", "domain_id"} },
    ["resend.post_automations"] = { method = "POST", url = "https://api.resend.com/automations", body = {"name", "status", "steps", "connections"} },
    ["resend.post_automations_automation_id_stop"] = { method = "POST", url = "https://api.resend.com/automations/{automation_id}/stop", path = {"automation_id"} },
    ["resend.post_broadcasts"] = { method = "POST", url = "https://api.resend.com/broadcasts", body = {"name", "segment_id", "audience_id", "from", "subject", "reply_to", "preview_text", "html", "text", "topic_id", "send", "scheduled_at"} },
    ["resend.post_broadcasts_id_send"] = { method = "POST", url = "https://api.resend.com/broadcasts/{id}/send", path = {"id"}, body = {"scheduled_at"} },
    ["resend.post_contact_properties"] = { method = "POST", url = "https://api.resend.com/contact-properties", body = {"type", "fallback_value"} },
    ["resend.post_contacts"] = { method = "POST", url = "https://api.resend.com/contacts", body = {"email", "first_name", "last_name", "unsubscribed", "properties", "segments", "topics", "audience_id"} },
    ["resend.post_contacts_contact_id_segments_segment_id"] = { method = "POST", url = "https://api.resend.com/contacts/{contact_id}/segments/{segment_id}", path = {"contact_id", "segment_id"} },
    ["resend.post_domains"] = { method = "POST", url = "https://api.resend.com/domains", body = {"name", "region", "custom_return_path", "open_tracking", "click_tracking", "tls", "capabilities", "tracking_subdomain"} },
    ["resend.post_domains_domain_id_verify"] = { method = "POST", url = "https://api.resend.com/domains/{domain_id}/verify", path = {"domain_id"} },
    ["resend.post_emails"] = { method = "POST", url = "https://api.resend.com/emails", header = {"Idempotency-Key"}, body = {"from", "to", "subject", "bcc", "cc", "reply_to", "html", "text", "template", "headers", "scheduled_at", "attachments", "tags", "topic_id"} },
    ["resend.post_emails_batch"] = { method = "POST", url = "https://api.resend.com/emails/batch", header = {"Idempotency-Key"} },
    ["resend.post_emails_email_id_cancel"] = { method = "POST", url = "https://api.resend.com/emails/{email_id}/cancel", path = {"email_id"} },
    ["resend.post_events"] = { method = "POST", url = "https://api.resend.com/events", body = {"name", "schema"} },
    ["resend.post_events_send"] = { method = "POST", url = "https://api.resend.com/events/send", body = {"event", "contact_id", "email", "payload"} },
    ["resend.post_segments"] = { method = "POST", url = "https://api.resend.com/segments", body = {"name", "audience_id", "filter"} },
    ["resend.post_templates"] = { method = "POST", url = "https://api.resend.com/templates", body = {"name", "alias", "from", "subject", "reply_to", "html", "text", "variables"} },
    ["resend.post_templates_id_duplicate"] = { method = "POST", url = "https://api.resend.com/templates/{id}/duplicate", path = {"id"} },
    ["resend.post_templates_id_publish"] = { method = "POST", url = "https://api.resend.com/templates/{id}/publish", path = {"id"} },
    ["resend.post_topics"] = { method = "POST", url = "https://api.resend.com/topics", body = {"name", "default_subscription", "description", "visibility"} },
    ["resend.post_webhooks"] = { method = "POST", url = "https://api.resend.com/webhooks", body = {"endpoint", "events"} },
  },
}
