-- PagerDuty — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json
-- Published by PagerDuty, the vendor's own GitHub organisation.
-- 451 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "pagerduty",
  name = "PagerDuty",
  base = "https://api.pagerduty.com",
  docs = "https://nango.dev/docs/integrations/all/pagerduty",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "PAGERDUTY_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["pagerduty.accept_recommended_rule"] = { method = "POST", url = "https://api.pagerduty.com/recommendations/event_orchestrations/services/{service_id}/rules/{recommendation_id}/accept", path = {"service_id", "recommendation_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.add_event_enrichment_associations"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/event_enrichments/{id}/associations", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.add_service_now_table"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/{integration_id}/tables", path = {"integration_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.associate_service_to_incident_workflow_trigger"] = { method = "POST", url = "https://api.pagerduty.com/incident_workflows/triggers/{id}/services", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"service"} },
    ["pagerduty.cancel_incident_responder_request"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/{id}/responder_requests/cancel", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"requester_id", "responder_request_targets"} },
    ["pagerduty.convert_service_event_rules_to_event_orchestration"] = { method = "POST", url = "https://api.pagerduty.com/services/{id}/rules/convert", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.create_addon"] = { method = "POST", url = "https://api.pagerduty.com/addons", header = {"Accept", "Content-Type"}, body = {"addon"} },
    ["pagerduty.create_automation_action"] = { method = "POST", url = "https://api.pagerduty.com/automation_actions/actions", header = {"Accept", "Content-Type"}, body = {"action"} },
    ["pagerduty.create_automation_action_invocation"] = { method = "POST", url = "https://api.pagerduty.com/automation_actions/actions/{id}/invocations", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"invocation"} },
    ["pagerduty.create_automation_action_service_assocation"] = { method = "POST", url = "https://api.pagerduty.com/automation_actions/actions/{id}/services", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"service"} },
    ["pagerduty.create_automation_action_team_association"] = { method = "POST", url = "https://api.pagerduty.com/automation_actions/actions/{id}/teams", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"team"} },
    ["pagerduty.create_automation_actions_runner"] = { method = "POST", url = "https://api.pagerduty.com/automation_actions/runners", header = {"Accept", "Content-Type"}, body = {"runner"} },
    ["pagerduty.create_automation_actions_runner_team_association"] = { method = "POST", url = "https://api.pagerduty.com/automation_actions/runners/{id}/teams", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"team"} },
    ["pagerduty.create_business_service"] = { method = "POST", url = "https://api.pagerduty.com/business_services", header = {"Accept", "Content-Type"}, body = {"business_service"} },
    ["pagerduty.create_business_service_account_subscription"] = { method = "POST", url = "https://api.pagerduty.com/business_services/{id}/account_subscription", path = {"id"}, header = {"Accept"} },
    ["pagerduty.create_business_service_notification_subscribers"] = { method = "POST", url = "https://api.pagerduty.com/business_services/{id}/subscribers", path = {"id"}, header = {"Accept"}, body = {"subscribers"} },
    ["pagerduty.create_cache_var_on_global_orch"] = { method = "POST", url = "https://api.pagerduty.com/event_orchestrations/{id}/cache_variables", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.create_cache_var_on_service_orch"] = { method = "POST", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/cache_variables", path = {"service_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.create_change_event"] = { method = "POST", url = "https://api.pagerduty.com/change_events", header = {"Accept", "Content-Type"} },
    ["pagerduty.create_custom_shifts"] = { method = "POST", url = "https://api.pagerduty.com/v3/schedules/{id}/custom_shifts", path = {"id"}, body = {"custom_shifts"} },
    ["pagerduty.create_enrichment_schema"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/schemas", query = {"filename"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.create_entity_type_by_id_change_tags"] = { method = "POST", url = "https://api.pagerduty.com/{entity_type}/{id}/change_tags", path = {"entity_type", "id"}, header = {"Accept", "Content-Type"}, body = {"add", "remove"} },
    ["pagerduty.create_escalation_policy"] = { method = "POST", url = "https://api.pagerduty.com/escalation_policies", header = {"Accept", "Content-Type", "From"}, body = {"escalation_policy"} },
    ["pagerduty.create_event"] = { method = "POST", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations/{rotation_id}/events", path = {"id", "rotation_id"}, body = {"event"} },
    ["pagerduty.create_event_enrichment"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/event_enrichments", header = {"Accept", "Content-Type"} },
    ["pagerduty.create_extension"] = { method = "POST", url = "https://api.pagerduty.com/extensions", header = {"Accept", "Content-Type"}, body = {"extension"} },
    ["pagerduty.create_incident"] = { method = "POST", url = "https://api.pagerduty.com/incidents", header = {"Accept", "Content-Type", "From"}, body = {"incident"} },
    ["pagerduty.create_incident_note"] = { method = "POST", url = "https://api.pagerduty.com/incidents/{id}/notes", path = {"id"}, header = {"Accept", "Content-Type", "From"}, body = {"note"} },
    ["pagerduty.create_incident_notification_subscribers"] = { method = "POST", url = "https://api.pagerduty.com/incidents/{id}/status_updates/subscribers", path = {"id"}, header = {"Accept"}, body = {"subscribers"} },
    ["pagerduty.create_incident_responder_request"] = { method = "POST", url = "https://api.pagerduty.com/incidents/{id}/responder_requests", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"requester_id", "message", "responder_request_targets"} },
    ["pagerduty.create_incident_snooze"] = { method = "POST", url = "https://api.pagerduty.com/incidents/{id}/snooze", path = {"id"}, header = {"Accept", "Content-Type", "From"}, body = {"duration"} },
    ["pagerduty.create_incident_status_update"] = { method = "POST", url = "https://api.pagerduty.com/incidents/{id}/status_updates", path = {"id"}, header = {"Accept", "Content-Type", "From"}, body = {"message", "subject", "html_message"} },
    ["pagerduty.create_incident_type"] = { method = "POST", url = "https://api.pagerduty.com/incidents/types", header = {"Accept", "Content-Type"}, body = {"incident_type"} },
    ["pagerduty.create_incident_type_custom_field"] = { method = "POST", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields", path = {"type_id_or_name"}, header = {"Accept", "Content-Type"}, body = {"field"} },
    ["pagerduty.create_incident_type_custom_field_field_options"] = { method = "POST", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields/{field_id}/field_options", path = {"type_id_or_name", "field_id"}, header = {"Accept", "Content-Type"}, body = {"field_option"} },
    ["pagerduty.create_incident_workflow_instance"] = { method = "POST", url = "https://api.pagerduty.com/incident_workflows/{id}/instances", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"incident_workflow_instance"} },
    ["pagerduty.create_incident_workflow_trigger"] = { method = "POST", url = "https://api.pagerduty.com/incident_workflows/triggers", header = {"Accept", "Content-Type"}, body = {"trigger"} },
    ["pagerduty.create_ip_allow_list"] = { method = "POST", url = "https://api.pagerduty.com/ip_allow_lists", header = {"Accept", "Content-Type"}, body = {"ip_allow_list"} },
    ["pagerduty.create_maintenance_window"] = { method = "POST", url = "https://api.pagerduty.com/maintenance_windows", header = {"Accept", "Content-Type", "From"}, body = {"maintenance_window"} },
    ["pagerduty.create_oauth_client"] = { method = "POST", url = "https://api.pagerduty.com/webhook_subscriptions/oauth_clients", header = {"Accept", "Content-Type"}, body = {"oauth_client"} },
    ["pagerduty.create_or_update_status_page_postmortem"] = { method = "PUT", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}/postmortem", path = {"id", "post_id"}, header = {"Accept"}, body = {"postmortem"} },
    ["pagerduty.create_overrides"] = { method = "POST", url = "https://api.pagerduty.com/v3/schedules/{id}/overrides", path = {"id"}, body = {"overrides"} },
    ["pagerduty.create_rotation"] = { method = "POST", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations", path = {"id"} },
    ["pagerduty.create_ruleset"] = { method = "POST", url = "https://api.pagerduty.com/rulesets", header = {"Accept", "Content-Type"}, body = {"ruleset"} },
    ["pagerduty.create_ruleset_event_rule"] = { method = "POST", url = "https://api.pagerduty.com/rulesets/{id}/rules", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"rule"} },
    ["pagerduty.create_schedule"] = { method = "POST", url = "https://api.pagerduty.com/schedules", query = {"overflow"}, header = {"Accept", "Content-Type"}, body = {"schedule"} },
    ["pagerduty.create_schedule_override"] = { method = "POST", url = "https://api.pagerduty.com/schedules/{id}/overrides", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"overrides"} },
    ["pagerduty.create_schedule_preview"] = { method = "POST", url = "https://api.pagerduty.com/schedules/preview", query = {"since", "until", "overflow"}, header = {"Accept", "Content-Type"}, body = {"schedule"} },
    ["pagerduty.create_schedule_v3"] = { method = "POST", url = "https://api.pagerduty.com/v3/schedules", body = {"schedule"} },
    ["pagerduty.create_service"] = { method = "POST", url = "https://api.pagerduty.com/services", header = {"Accept", "Content-Type"}, body = {"service"} },
    ["pagerduty.create_service_custom_field"] = { method = "POST", url = "https://api.pagerduty.com/services/custom_fields", header = {"Accept", "Content-Type"}, body = {"field"} },
    ["pagerduty.create_service_custom_field_option"] = { method = "POST", url = "https://api.pagerduty.com/services/custom_fields/{field_id}/field_options", path = {"field_id"}, header = {"Accept", "Content-Type"}, body = {"field_option"} },
    ["pagerduty.create_service_dependency"] = { method = "POST", url = "https://api.pagerduty.com/service_dependencies/associate", header = {"Accept", "Content-Type"}, body = {"relationships"} },
    ["pagerduty.create_service_event_rule"] = { method = "POST", url = "https://api.pagerduty.com/services/{id}/rules", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"rule"} },
    ["pagerduty.create_service_integration"] = { method = "POST", url = "https://api.pagerduty.com/services/{id}/integrations", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"integration"} },
    ["pagerduty.create_service_now_credentials"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/credentials", header = {"Accept", "Content-Type"} },
    ["pagerduty.create_service_now_integration"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/integrations/servicenow", header = {"Accept", "Content-Type"} },
    ["pagerduty.create_status_page_post"] = { method = "POST", url = "https://api.pagerduty.com/status_pages/{id}/posts", path = {"id"}, header = {"Accept"}, body = {"post"} },
    ["pagerduty.create_status_page_post_update"] = { method = "POST", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}/post_updates", path = {"id", "post_id"}, header = {"Accept"}, body = {"post_update"} },
    ["pagerduty.create_status_page_subscription"] = { method = "POST", url = "https://api.pagerduty.com/status_pages/{id}/subscriptions", path = {"id"}, header = {"Accept"}, body = {"subscription"} },
    ["pagerduty.create_tags"] = { method = "POST", url = "https://api.pagerduty.com/tags", header = {"Accept", "Content-Type"}, body = {"tag"} },
    ["pagerduty.create_team"] = { method = "POST", url = "https://api.pagerduty.com/teams", header = {"Accept", "Content-Type"}, body = {"team"} },
    ["pagerduty.create_team_notification_subscriptions"] = { method = "POST", url = "https://api.pagerduty.com/teams/{id}/notification_subscriptions", path = {"id"}, header = {"Accept"}, body = {"subscribables"} },
    ["pagerduty.create_template"] = { method = "POST", url = "https://api.pagerduty.com/templates", body = {"template"} },
    ["pagerduty.create_user"] = { method = "POST", url = "https://api.pagerduty.com/users", header = {"Accept", "Content-Type", "From"}, body = {"user"} },
    ["pagerduty.create_user_contact_method"] = { method = "POST", url = "https://api.pagerduty.com/users/{id}/contact_methods", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"contact_method"} },
    ["pagerduty.create_user_handoff_notification_rule"] = { method = "POST", url = "https://api.pagerduty.com/users/{id}/oncall_handoff_notification_rules", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"oncall_handoff_notification_rule"} },
    ["pagerduty.create_user_notification_rule"] = { method = "POST", url = "https://api.pagerduty.com/users/{id}/notification_rules", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"notification_rule"} },
    ["pagerduty.create_user_notification_subscriptions"] = { method = "POST", url = "https://api.pagerduty.com/users/{id}/notification_subscriptions", path = {"id"}, header = {"Accept"}, body = {"subscribables"} },
    ["pagerduty.create_user_status_update_notification_rule"] = { method = "POST", url = "https://api.pagerduty.com/users/{id}/status_update_notification_rules", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"status_update_notification_rule"} },
    ["pagerduty.create_webhook_subscription"] = { method = "POST", url = "https://api.pagerduty.com/webhook_subscriptions", header = {"Accept", "Content-Type"}, body = {"webhook_subscription"} },
    ["pagerduty.create_workflow_integration_connection"] = { method = "POST", url = "https://api.pagerduty.com/workflows/integrations/{integration_id}/connections", path = {"integration_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_accepted_recommended_rule"] = { method = "DELETE", url = "https://api.pagerduty.com/recommendations/event_orchestrations/services/{service_id}/accepted_rules/{rule_id}", path = {"service_id", "rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_addon"] = { method = "DELETE", url = "https://api.pagerduty.com/addons/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_alert_grouping_setting"] = { method = "DELETE", url = "https://api.pagerduty.com/alert_grouping_settings/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_automation_action"] = { method = "DELETE", url = "https://api.pagerduty.com/automation_actions/actions/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_automation_action_service_association"] = { method = "DELETE", url = "https://api.pagerduty.com/automation_actions/actions/{id}/services/{service_id}", path = {"id", "service_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_automation_action_team_association"] = { method = "DELETE", url = "https://api.pagerduty.com/automation_actions/actions/{id}/teams/{team_id}", path = {"id", "team_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_automation_actions_runner"] = { method = "DELETE", url = "https://api.pagerduty.com/automation_actions/runners/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_automation_actions_runner_team_association"] = { method = "DELETE", url = "https://api.pagerduty.com/automation_actions/runners/{id}/teams/{team_id}", path = {"id", "team_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_business_service"] = { method = "DELETE", url = "https://api.pagerduty.com/business_services/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_business_service_priority_thresholds"] = { method = "DELETE", url = "https://api.pagerduty.com/business_services/priority_thresholds", header = {"Accept"} },
    ["pagerduty.delete_cache_var_on_global_orch"] = { method = "DELETE", url = "https://api.pagerduty.com/event_orchestrations/{id}/cache_variables/{cache_variable_id}", path = {"id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_cache_var_on_service_orch"] = { method = "DELETE", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/cache_variables/{cache_variable_id}", path = {"service_id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_custom_shift"] = { method = "DELETE", url = "https://api.pagerduty.com/v3/schedules/{id}/custom_shifts/{custom_shift_id}", path = {"id", "custom_shift_id"} },
    ["pagerduty.delete_enrichment_record"] = { method = "DELETE", url = "https://api.pagerduty.com/enrichment/schemas/{schema_id}/records/{record_id}", path = {"schema_id", "record_id"}, header = {"Accept"} },
    ["pagerduty.delete_enrichment_schema"] = { method = "DELETE", url = "https://api.pagerduty.com/enrichment/schemas/{schema_id}", path = {"schema_id"}, header = {"Accept"} },
    ["pagerduty.delete_escalation_policy"] = { method = "DELETE", url = "https://api.pagerduty.com/escalation_policies/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_event"] = { method = "DELETE", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations/{rotation_id}/events/{event_id}", path = {"id", "rotation_id", "event_id"} },
    ["pagerduty.delete_event_enrichment"] = { method = "DELETE", url = "https://api.pagerduty.com/enrichment/event_enrichments/{id}", path = {"id"}, header = {"Accept"} },
    ["pagerduty.delete_event_enrichment_associations"] = { method = "DELETE", url = "https://api.pagerduty.com/enrichment/event_enrichments/{id}/associations", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_extension"] = { method = "DELETE", url = "https://api.pagerduty.com/extensions/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_external_data_cache_var_data_on_global_orch"] = { method = "DELETE", url = "https://api.pagerduty.com/event_orchestrations/{id}/cache_variables/{cache_variable_id}/data", path = {"id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_external_data_cache_var_data_on_service_orch"] = { method = "DELETE", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/cache_variables/{cache_variable_id}/data", path = {"service_id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_incident_note"] = { method = "DELETE", url = "https://api.pagerduty.com/incidents/{id}/notes/{note_id}", path = {"id", "note_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_incident_type_custom_field"] = { method = "DELETE", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields/{field_id}", path = {"type_id_or_name", "field_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_incident_type_custom_field_field_option"] = { method = "DELETE", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields/{field_id}/field_options/{field_option_id}", path = {"type_id_or_name", "field_option_id", "field_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_incident_workflow"] = { method = "DELETE", url = "https://api.pagerduty.com/incident_workflows/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_incident_workflow_trigger"] = { method = "DELETE", url = "https://api.pagerduty.com/incident_workflows/triggers/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_ip_allow_list"] = { method = "DELETE", url = "https://api.pagerduty.com/ip_allow_lists/{id}", path = {"id"}, header = {"Accept"} },
    ["pagerduty.delete_maintenance_window"] = { method = "DELETE", url = "https://api.pagerduty.com/maintenance_windows/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_oauth_client"] = { method = "DELETE", url = "https://api.pagerduty.com/webhook_subscriptions/oauth_clients/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_oauth_delegations"] = { method = "DELETE", url = "https://api.pagerduty.com/oauth_delegations", query = {"user_id", "type"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_orchestration"] = { method = "DELETE", url = "https://api.pagerduty.com/event_orchestrations/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_orchestration_integration"] = { method = "DELETE", url = "https://api.pagerduty.com/event_orchestrations/{id}/integrations/{integration_id}", path = {"id", "integration_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_override"] = { method = "DELETE", url = "https://api.pagerduty.com/v3/schedules/{id}/overrides/{override_id}", path = {"id", "override_id"} },
    ["pagerduty.delete_rotation"] = { method = "DELETE", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations/{rotation_id}", path = {"id", "rotation_id"} },
    ["pagerduty.delete_ruleset"] = { method = "DELETE", url = "https://api.pagerduty.com/rulesets/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_ruleset_event_rule"] = { method = "DELETE", url = "https://api.pagerduty.com/rulesets/{id}/rules/{rule_id}", path = {"id", "rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_schedule"] = { method = "DELETE", url = "https://api.pagerduty.com/schedules/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_schedule_override"] = { method = "DELETE", url = "https://api.pagerduty.com/schedules/{id}/overrides/{override_id}", path = {"id", "override_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_schedule_v3"] = { method = "DELETE", url = "https://api.pagerduty.com/v3/schedules/{id}", path = {"id"} },
    ["pagerduty.delete_service"] = { method = "DELETE", url = "https://api.pagerduty.com/services/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_service_custom_field"] = { method = "DELETE", url = "https://api.pagerduty.com/services/custom_fields/{field_id}", path = {"field_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_service_custom_field_option"] = { method = "DELETE", url = "https://api.pagerduty.com/services/custom_fields/{field_id}/field_options/{field_option_id}", path = {"field_id", "field_option_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_service_dependency"] = { method = "POST", url = "https://api.pagerduty.com/service_dependencies/disassociate", header = {"Accept", "Content-Type"}, body = {"relationships"} },
    ["pagerduty.delete_service_event_rule"] = { method = "DELETE", url = "https://api.pagerduty.com/services/{id}/rules/{rule_id}", path = {"id", "rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_service_from_incident_workflow_trigger"] = { method = "DELETE", url = "https://api.pagerduty.com/incident_workflows/triggers/{trigger_id}/services/{service_id}", path = {"trigger_id", "service_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_service_now_credentials"] = { method = "DELETE", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/credentials/{credentials_id}", path = {"credentials_id"}, header = {"Accept"} },
    ["pagerduty.delete_service_now_integration"] = { method = "DELETE", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/{integration_id}", path = {"integration_id"}, header = {"Accept"} },
    ["pagerduty.delete_service_now_table"] = { method = "DELETE", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/{integration_id}/tables/{table_id}", path = {"integration_id", "table_id"}, header = {"Accept"} },
    ["pagerduty.delete_session_configurations"] = { method = "DELETE", url = "https://api.pagerduty.com/session_configurations", query = {"type"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_sre_memory"] = { method = "DELETE", url = "https://api.pagerduty.com/sre_agent/memories/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_status_page_post"] = { method = "DELETE", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}", path = {"id", "post_id"}, header = {"Accept"} },
    ["pagerduty.delete_status_page_post_update"] = { method = "DELETE", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}/post_updates/{post_update_id}", path = {"id", "post_id", "post_update_id"}, header = {"Accept"} },
    ["pagerduty.delete_status_page_postmortem"] = { method = "DELETE", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}/postmortem", path = {"id", "post_id"}, header = {"Accept"} },
    ["pagerduty.delete_status_page_subscription"] = { method = "DELETE", url = "https://api.pagerduty.com/status_pages/{id}/subscriptions/{subscription_id}", path = {"id", "subscription_id"}, header = {"Accept"} },
    ["pagerduty.delete_tag"] = { method = "DELETE", url = "https://api.pagerduty.com/tags/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_team"] = { method = "DELETE", url = "https://api.pagerduty.com/teams/{id}", path = {"id"}, query = {"reassignment_team"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_team_escalation_policy"] = { method = "DELETE", url = "https://api.pagerduty.com/teams/{id}/escalation_policies/{escalation_policy_id}", path = {"id", "escalation_policy_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_team_user"] = { method = "DELETE", url = "https://api.pagerduty.com/teams/{id}/users/{user_id}", path = {"id", "user_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_template"] = { method = "DELETE", url = "https://api.pagerduty.com/templates/{id}", path = {"id"} },
    ["pagerduty.delete_user"] = { method = "DELETE", url = "https://api.pagerduty.com/users/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_user_contact_method"] = { method = "DELETE", url = "https://api.pagerduty.com/users/{id}/contact_methods/{contact_method_id}", path = {"id", "contact_method_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_user_handoff_notification_rule"] = { method = "DELETE", url = "https://api.pagerduty.com/users/{id}/oncall_handoff_notification_rules/{oncall_handoff_notification_rule_id}", path = {"id", "oncall_handoff_notification_rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_user_notification_rule"] = { method = "DELETE", url = "https://api.pagerduty.com/users/{id}/notification_rules/{notification_rule_id}", path = {"id", "notification_rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_user_status_update_notification_rule"] = { method = "DELETE", url = "https://api.pagerduty.com/users/{id}/status_update_notification_rules/{status_update_notification_rule_id}", path = {"id", "status_update_notification_rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.delete_webhook_subscription"] = { method = "DELETE", url = "https://api.pagerduty.com/webhook_subscriptions/{id}", path = {"id"}, header = {"Accept"} },
    ["pagerduty.delete_workflow_integration_connection"] = { method = "DELETE", url = "https://api.pagerduty.com/workflows/integrations/{integration_id}/connections/{id}", path = {"integration_id", "id"}, header = {"Accept"} },
    ["pagerduty.dismiss_recommended_rule"] = { method = "POST", url = "https://api.pagerduty.com/recommendations/event_orchestrations/services/{service_id}/rules/{recommendation_id}/dismiss", path = {"service_id", "recommendation_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.enable_extension"] = { method = "POST", url = "https://api.pagerduty.com/extensions/{id}/enable", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.enable_service_now_table_sync"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/{integration_id}/tables/{table_id}/enable", path = {"integration_id", "table_id"}, header = {"Accept"} },
    ["pagerduty.enable_webhook_subscription"] = { method = "POST", url = "https://api.pagerduty.com/webhook_subscriptions/{id}/enable", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_ability"] = { method = "GET", url = "https://api.pagerduty.com/abilities/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_account_default_event_enrichment"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/event_enrichments/default", header = {"Accept"} },
    ["pagerduty.get_addon"] = { method = "GET", url = "https://api.pagerduty.com/addons/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_alert_grouping_setting"] = { method = "GET", url = "https://api.pagerduty.com/alert_grouping_settings/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_all_automation_actions"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/actions", query = {"limit", "cursor", "name", "runner_id", "classification", "team_id", "service_id", "action_type"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_analytics_incident_responses_by_id"] = { method = "GET", url = "https://api.pagerduty.com/analytics/raw/incidents/{id}/responses", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"limit", "order", "order_by", "time_zone"} },
    ["pagerduty.get_analytics_incidents"] = { method = "POST", url = "https://api.pagerduty.com/analytics/raw/incidents", header = {"Accept", "Content-Type"}, body = {"filters", "starting_after", "ending_before", "order", "order_by", "limit", "time_zone"} },
    ["pagerduty.get_analytics_incidents_by_id"] = { method = "GET", url = "https://api.pagerduty.com/analytics/raw/incidents/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_analytics_metrics_incidents_all"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/incidents/all", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit"} },
    ["pagerduty.get_analytics_metrics_incidents_escalation_policy"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/incidents/escalation_policies", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit"} },
    ["pagerduty.get_analytics_metrics_incidents_escalation_policy_all"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/incidents/escalation_policies/all", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit"} },
    ["pagerduty.get_analytics_metrics_incidents_service"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/incidents/services", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit"} },
    ["pagerduty.get_analytics_metrics_incidents_service_all"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/incidents/services/all", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit"} },
    ["pagerduty.get_analytics_metrics_incidents_team"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/incidents/teams", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit"} },
    ["pagerduty.get_analytics_metrics_incidents_team_all"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/incidents/teams/all", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit"} },
    ["pagerduty.get_analytics_metrics_pd_advance_usage_features"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/pd_advance_usage/features", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone"} },
    ["pagerduty.get_analytics_metrics_responders_all"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/responders/all", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by"} },
    ["pagerduty.get_analytics_metrics_responders_team"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/responders/teams", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by"} },
    ["pagerduty.get_analytics_metrics_users_all"] = { method = "POST", url = "https://api.pagerduty.com/analytics/metrics/users/all", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit", "limit", "starting_after", "ending_before"} },
    ["pagerduty.get_analytics_responder_incidents"] = { method = "POST", url = "https://api.pagerduty.com/analytics/raw/responders/{responder_id}/incidents", path = {"responder_id"}, header = {"Accept", "Content-Type"}, body = {"filters", "starting_after", "ending_before", "order", "order_by", "limit", "time_zone"} },
    ["pagerduty.get_analytics_users"] = { method = "POST", url = "https://api.pagerduty.com/analytics/raw/users", header = {"Accept", "Content-Type"}, body = {"filters", "time_zone", "order", "order_by", "aggregate_unit", "limit", "starting_after", "ending_before"} },
    ["pagerduty.get_automation_action"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/actions/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_action_service_association"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/actions/{id}/services/{service_id}", path = {"id", "service_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_action_service_associations"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/actions/{id}/services", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_action_team_association"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/actions/{id}/teams/{team_id}", path = {"id", "team_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_action_team_associations"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/actions/{id}/teams", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_invocation"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/invocations/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_runner"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/runners/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_runner_team_association"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/runners/{id}/teams/{team_id}", path = {"id", "team_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_runner_team_associations"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/runners/{id}/teams", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_automation_actions_runners"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/runners", query = {"limit", "cursor", "name", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_business_service"] = { method = "GET", url = "https://api.pagerduty.com/business_services/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_business_service_impacts"] = { method = "GET", url = "https://api.pagerduty.com/business_services/impacts", query = {"additional_fields[]", "ids[]"}, header = {"Accept"} },
    ["pagerduty.get_business_service_priority_thresholds"] = { method = "GET", url = "https://api.pagerduty.com/business_services/priority_thresholds", header = {"Accept"} },
    ["pagerduty.get_business_service_service_dependencies"] = { method = "GET", url = "https://api.pagerduty.com/service_dependencies/business_services/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_business_service_subscribers"] = { method = "GET", url = "https://api.pagerduty.com/business_services/{id}/subscribers", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_business_service_supporting_service_impacts"] = { method = "GET", url = "https://api.pagerduty.com/business_services/{id}/supporting_services/impacts", path = {"id"}, query = {"additional_fields[]", "ids[]"}, header = {"Accept"} },
    ["pagerduty.get_business_service_top_level_impactors"] = { method = "GET", url = "https://api.pagerduty.com/business_services/impactors", query = {"ids[]"}, header = {"Accept"} },
    ["pagerduty.get_cache_var_on_global_orch"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/cache_variables/{cache_variable_id}", path = {"id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_cache_var_on_service_orch"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/cache_variables/{cache_variable_id}", path = {"service_id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_change_event"] = { method = "GET", url = "https://api.pagerduty.com/change_events/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_current_user"] = { method = "GET", url = "https://api.pagerduty.com/users/me", query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_custom_shift"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/custom_shifts/{custom_shift_id}", path = {"id", "custom_shift_id"} },
    ["pagerduty.get_enrichment_schema"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/schemas/{schema_id}", path = {"schema_id"}, header = {"Accept"} },
    ["pagerduty.get_entity_type_by_id_tags"] = { method = "GET", url = "https://api.pagerduty.com/{entity_type}/{id}/tags", path = {"entity_type", "id"}, query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_escalation_policy"] = { method = "GET", url = "https://api.pagerduty.com/escalation_policies/{id}", path = {"id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_event"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations/{rotation_id}/events/{event_id}", path = {"id", "rotation_id", "event_id"}, query = {"since", "until"} },
    ["pagerduty.get_event_enrichment"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/event_enrichments/{id}", path = {"id"}, query = {"include[]"}, header = {"Accept"} },
    ["pagerduty.get_event_enrichment_rules"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/event_enrichments/{id}/rules", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_extension"] = { method = "GET", url = "https://api.pagerduty.com/extensions/{id}", path = {"id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_extension_schema"] = { method = "GET", url = "https://api.pagerduty.com/extension_schemas/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_external_data_cache_var_data_on_global_orch"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/cache_variables/{cache_variable_id}/data", path = {"id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_external_data_cache_var_data_on_service_orch"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/cache_variables/{cache_variable_id}/data", path = {"service_id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_incident"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}", path = {"id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_incident_alert"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/alerts/{alert_id}", path = {"id", "alert_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_incident_field_values"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/custom_fields/values", path = {"id"} },
    ["pagerduty.get_incident_impacted_business_services"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/business_services/impacts", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_incident_notification_subscribers"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/status_updates/subscribers", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_incident_type"] = { method = "GET", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}", path = {"type_id_or_name"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_incident_type_custom_field"] = { method = "GET", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields/{field_id}", path = {"type_id_or_name", "field_id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_incident_type_custom_field_field_options"] = { method = "GET", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields/{field_id}/field_options/{field_option_id}", path = {"type_id_or_name", "field_option_id", "field_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_incident_workflow"] = { method = "GET", url = "https://api.pagerduty.com/incident_workflows/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_incident_workflow_action"] = { method = "GET", url = "https://api.pagerduty.com/incident_workflows/actions/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_incident_workflow_trigger"] = { method = "GET", url = "https://api.pagerduty.com/incident_workflows/triggers/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_ip_allow_list"] = { method = "GET", url = "https://api.pagerduty.com/ip_allow_lists/{id}", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_log_entry"] = { method = "GET", url = "https://api.pagerduty.com/log_entries/{id}", path = {"id"}, query = {"time_zone", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_maintenance_window"] = { method = "GET", url = "https://api.pagerduty.com/maintenance_windows/{id}", path = {"id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_oauth_client"] = { method = "GET", url = "https://api.pagerduty.com/webhook_subscriptions/oauth_clients/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_orch_active_status"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/active", path = {"service_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_orch_path_global"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/global", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_orch_path_router"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/router", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_orch_path_service"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}", path = {"service_id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_orch_path_unrouted"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/unrouted", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_orchestration"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_orchestration_integration"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/integrations/{integration_id}", path = {"id", "integration_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_outlier_incident"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/outlier_incident", path = {"id"}, query = {"since", "additional_details[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_override"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/overrides/{override_id}", path = {"id", "override_id"} },
    ["pagerduty.get_past_incidents"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/past_incidents", path = {"id"}, query = {"limit", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_paused_incident_report_alerts"] = { method = "GET", url = "https://api.pagerduty.com/paused_incident_reports/alerts", query = {"since", "until", "service_id", "suspended_by"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_paused_incident_report_counts"] = { method = "GET", url = "https://api.pagerduty.com/paused_incident_reports/counts", query = {"since", "until", "service_id", "suspended_by"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_post_update"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}/post_updates/{post_update_id}", path = {"id", "post_id", "post_update_id"}, header = {"Accept"} },
    ["pagerduty.get_postmortem"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}/postmortem", path = {"id", "post_id"}, header = {"Accept"} },
    ["pagerduty.get_related_incidents"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/related_incidents", path = {"id"}, query = {"additional_details[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_rotation"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations/{rotation_id}", path = {"id", "rotation_id"}, query = {"since", "until"} },
    ["pagerduty.get_ruleset"] = { method = "GET", url = "https://api.pagerduty.com/rulesets/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_ruleset_event_rule"] = { method = "GET", url = "https://api.pagerduty.com/rulesets/{id}/rules/{rule_id}", path = {"id", "rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_schedule"] = { method = "GET", url = "https://api.pagerduty.com/schedules/{id}", path = {"id"}, query = {"time_zone", "since", "until", "overflow", "include_next_oncall_for_user"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_schedule_v3"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}", path = {"id"}, query = {"since", "until", "time_zone", "overflow", "include[]"} },
    ["pagerduty.get_service"] = { method = "GET", url = "https://api.pagerduty.com/services/{id}", path = {"id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_service_custom_field"] = { method = "GET", url = "https://api.pagerduty.com/services/custom_fields/{field_id}", path = {"field_id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_service_custom_field_option"] = { method = "GET", url = "https://api.pagerduty.com/services/custom_fields/{field_id}/field_options/{field_option_id}", path = {"field_id", "field_option_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_service_custom_field_values"] = { method = "GET", url = "https://api.pagerduty.com/services/{id}/custom_fields/values", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_service_event_rule"] = { method = "GET", url = "https://api.pagerduty.com/services/{id}/rules/{rule_id}", path = {"id", "rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_service_integration"] = { method = "GET", url = "https://api.pagerduty.com/services/{id}/integrations/{integration_id}", path = {"id", "integration_id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_service_now_credentials"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/credentials/{credentials_id}", path = {"credentials_id"}, header = {"Accept"} },
    ["pagerduty.get_service_now_integration"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/{integration_id}", path = {"integration_id"}, header = {"Accept"} },
    ["pagerduty.get_session_configurations"] = { method = "GET", url = "https://api.pagerduty.com/session_configurations", query = {"type"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_status_dashboard_by_id"] = { method = "GET", url = "https://api.pagerduty.com/status_dashboards/{id}", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_status_dashboard_by_url_slug"] = { method = "GET", url = "https://api.pagerduty.com/status_dashboards/url_slugs/{url_slug}", path = {"url_slug"}, header = {"Accept"} },
    ["pagerduty.get_status_dashboard_service_impacts_by_id"] = { method = "GET", url = "https://api.pagerduty.com/status_dashboards/{id}/service_impacts", path = {"id"}, query = {"additional_fields[]"}, header = {"Accept"} },
    ["pagerduty.get_status_dashboard_service_impacts_by_url_slug"] = { method = "GET", url = "https://api.pagerduty.com/status_dashboards/url_slugs/{url_slug}/service_impacts", path = {"url_slug"}, query = {"additional_fields[]"}, header = {"Accept"} },
    ["pagerduty.get_status_page_impact"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/impacts/{impact_id}", path = {"id", "impact_id"}, header = {"Accept"} },
    ["pagerduty.get_status_page_post"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}", path = {"id", "post_id"}, query = {"include[]"}, header = {"Accept"} },
    ["pagerduty.get_status_page_service"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/services/{service_id}", path = {"id", "service_id"}, header = {"Accept"} },
    ["pagerduty.get_status_page_severity"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/severities/{severity_id}", path = {"id", "severity_id"}, header = {"Accept"} },
    ["pagerduty.get_status_page_status"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/statuses/{status_id}", path = {"id", "status_id"}, header = {"Accept"} },
    ["pagerduty.get_status_page_subscription"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/subscriptions/{subscription_id}", path = {"id", "subscription_id"}, header = {"Accept"} },
    ["pagerduty.get_tag"] = { method = "GET", url = "https://api.pagerduty.com/tags/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_tags_by_entity_type"] = { method = "GET", url = "https://api.pagerduty.com/tags/{id}/{entity_type}", path = {"id", "entity_type"}, query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_team"] = { method = "GET", url = "https://api.pagerduty.com/teams/{id}", path = {"id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_team_notification_subscriptions"] = { method = "GET", url = "https://api.pagerduty.com/teams/{id}/notification_subscriptions", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_technical_service_service_dependencies"] = { method = "GET", url = "https://api.pagerduty.com/service_dependencies/technical_services/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_template"] = { method = "GET", url = "https://api.pagerduty.com/templates/{id}", path = {"id"} },
    ["pagerduty.get_template_fields"] = { method = "GET", url = "https://api.pagerduty.com/templates/fields", header = {"Accept", "Content-Type"} },
    ["pagerduty.get_templates"] = { method = "GET", url = "https://api.pagerduty.com/templates", query = {"limit", "offset", "total", "query", "template_type", "sort_by"} },
    ["pagerduty.get_user"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}", path = {"id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_contact_method"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/contact_methods/{contact_method_id}", path = {"id", "contact_method_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_contact_methods"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/contact_methods", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_delegation"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/oauth_delegations/{delegation_id}", path = {"id", "delegation_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_handoff_notifiaction_rule"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/oncall_handoff_notification_rules/{oncall_handoff_notification_rule_id}", path = {"id", "oncall_handoff_notification_rule_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_handoff_notification_rules"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/oncall_handoff_notification_rules", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_license"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/license", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_notification_rule"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/notification_rules/{notification_rule_id}", path = {"id", "notification_rule_id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_notification_rules"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/notification_rules", path = {"id"}, query = {"include[]", "urgency"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_notification_subscriptions"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/notification_subscriptions", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_user_status_update_notification_rule"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/status_update_notification_rules/{status_update_notification_rule_id}", path = {"id", "status_update_notification_rule_id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_user_status_update_notification_rules"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/status_update_notification_rules", path = {"id"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_vendor"] = { method = "GET", url = "https://api.pagerduty.com/vendors/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.get_webhook_subscription"] = { method = "GET", url = "https://api.pagerduty.com/webhook_subscriptions/{id}", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_workflow_integration"] = { method = "GET", url = "https://api.pagerduty.com/workflows/integrations/{id}", path = {"id"}, header = {"Accept"} },
    ["pagerduty.get_workflow_integration_connection"] = { method = "GET", url = "https://api.pagerduty.com/workflows/integrations/{integration_id}/connections/{id}", path = {"integration_id", "id"}, header = {"Accept"} },
    ["pagerduty.list_abilities"] = { method = "GET", url = "https://api.pagerduty.com/abilities", header = {"Accept", "Content-Type"} },
    ["pagerduty.list_addon"] = { method = "GET", url = "https://api.pagerduty.com/addons", query = {"limit", "offset", "total", "include[]", "service_ids[]", "filter"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_alert_grouping_settings"] = { method = "GET", url = "https://api.pagerduty.com/alert_grouping_settings", query = {"after", "before", "total", "limit", "service_ids[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_audit_records"] = { method = "GET", url = "https://api.pagerduty.com/audit/records", query = {"limit", "cursor", "since", "until", "root_resource_types[]", "actor_type", "actor_id", "method_type", "method_truncated_token", "actions[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_automation_action_invocations"] = { method = "GET", url = "https://api.pagerduty.com/automation_actions/invocations", query = {"invocation_state", "not_invocation_state", "incident_id", "action_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_business_services"] = { method = "GET", url = "https://api.pagerduty.com/business_services", query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_cache_var_on_global_orch"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/cache_variables", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_cache_var_on_service_orch"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/cache_variables", path = {"service_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_change_events"] = { method = "GET", url = "https://api.pagerduty.com/change_events", query = {"limit", "offset", "total", "team_ids[]", "integration_ids[]", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_custom_shifts"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/custom_shifts", path = {"id"}, query = {"since", "until", "time_zone", "overflow", "limit", "offset"} },
    ["pagerduty.list_enrichment_records"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/schemas/{schema_id}/records", path = {"schema_id"}, query = {"limit", "cursor"}, header = {"Accept"} },
    ["pagerduty.list_enrichment_schemas"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/schemas", header = {"Accept"} },
    ["pagerduty.list_escalation_policies"] = { method = "GET", url = "https://api.pagerduty.com/escalation_policies", query = {"limit", "offset", "total", "query", "user_ids[]", "team_ids[]", "include[]", "sort_by"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_escalation_policy_audit_records"] = { method = "GET", url = "https://api.pagerduty.com/escalation_policies/{id}/audit/records", path = {"id"}, query = {"limit", "cursor", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_event_enrichment_associations"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/event_enrichments/{id}/associations", path = {"id"}, query = {"association_type", "limit", "offset"}, header = {"Accept"} },
    ["pagerduty.list_event_enrichments"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/event_enrichments", query = {"limit", "offset", "include[]"}, header = {"Accept"} },
    ["pagerduty.list_event_orchestration_feature_enablements"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/enablements", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_event_orchestrations"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations", query = {"limit", "offset", "sort_by"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_events"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations/{rotation_id}/events", path = {"id", "rotation_id"}, query = {"limit", "offset"} },
    ["pagerduty.list_extension_schemas"] = { method = "GET", url = "https://api.pagerduty.com/extension_schemas", query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_extensions"] = { method = "GET", url = "https://api.pagerduty.com/extensions", query = {"limit", "offset", "total", "query", "extension_object_id", "extension_schema_id", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_alerts"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/alerts", path = {"id"}, query = {"limit", "offset", "total", "alert_key", "statuses[]", "sort_by", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_log_entries"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/log_entries", path = {"id"}, query = {"limit", "offset", "total", "time_zone", "since", "until", "is_overview", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_notes"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/notes", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_related_change_events"] = { method = "GET", url = "https://api.pagerduty.com/incidents/{id}/related_change_events", path = {"id"}, query = {"limit"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_type_custom_field"] = { method = "GET", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields/{field_id}/field_options", path = {"type_id_or_name", "field_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_type_custom_fields"] = { method = "GET", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields", path = {"type_id_or_name"}, query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_types"] = { method = "GET", url = "https://api.pagerduty.com/incidents/types", query = {"filter"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_workflow_actions"] = { method = "GET", url = "https://api.pagerduty.com/incident_workflows/actions", query = {"limit", "cursor", "keyword"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_workflow_triggers"] = { method = "GET", url = "https://api.pagerduty.com/incident_workflows/triggers", query = {"workflow_id", "incident_id", "service_id", "trigger_type", "workflow_name_contains", "is_disabled", "sort_by", "limit", "cursor"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incident_workflows"] = { method = "GET", url = "https://api.pagerduty.com/incident_workflows", query = {"limit", "offset", "total", "query", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_incidents"] = { method = "GET", url = "https://api.pagerduty.com/incidents", query = {"limit", "offset", "total", "date_range", "incident_key", "service_ids[]", "team_ids[]", "user_ids[]", "urgencies[]", "time_zone", "statuses[]", "sort_by", "include[]", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_ip_allow_list_audit_records"] = { method = "GET", url = "https://api.pagerduty.com/ip_allow_lists/{id}/audit/records", path = {"id"}, query = {"limit", "cursor", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_ip_allow_lists"] = { method = "GET", url = "https://api.pagerduty.com/ip_allow_lists", header = {"Accept"} },
    ["pagerduty.list_license_allocations"] = { method = "GET", url = "https://api.pagerduty.com/license_allocations", query = {"limit", "offset"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_licenses"] = { method = "GET", url = "https://api.pagerduty.com/licenses", header = {"Accept", "Content-Type"} },
    ["pagerduty.list_log_entries"] = { method = "GET", url = "https://api.pagerduty.com/log_entries", query = {"limit", "offset", "total", "time_zone", "since", "until", "is_overview", "include[]", "team_ids[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_maintenance_windows"] = { method = "GET", url = "https://api.pagerduty.com/maintenance_windows", query = {"query", "limit", "offset", "total", "team_ids[]", "service_ids[]", "include[]", "filter"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_notifications"] = { method = "GET", url = "https://api.pagerduty.com/notifications", query = {"limit", "offset", "total", "time_zone", "since", "until", "filter", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_oauth_clients"] = { method = "GET", url = "https://api.pagerduty.com/webhook_subscriptions/oauth_clients", header = {"Accept", "Content-Type"} },
    ["pagerduty.list_on_calls"] = { method = "GET", url = "https://api.pagerduty.com/oncalls", query = {"time_zone", "limit", "offset", "total", "include[]", "user_ids[]", "escalation_policy_ids[]", "schedule_ids[]", "since", "until", "earliest"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_orchestration_integrations"] = { method = "GET", url = "https://api.pagerduty.com/event_orchestrations/{id}/integrations", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_overrides"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/overrides", path = {"id"}, query = {"since", "until", "time_zone", "overflow", "limit", "offset"} },
    ["pagerduty.list_priorities"] = { method = "GET", url = "https://api.pagerduty.com/priorities", query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_recommended_rules"] = { method = "GET", url = "https://api.pagerduty.com/recommendations/event_orchestrations/rules", query = {"service_id", "service_ids[]", "team_ids[]", "actions[]", "limit", "cursor"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_resource_standards"] = { method = "GET", url = "https://api.pagerduty.com/standards/scores/{resource_type}/{id}", path = {"id", "resource_type"}, header = {"Accept"} },
    ["pagerduty.list_resource_standards_many_services"] = { method = "GET", url = "https://api.pagerduty.com/standards/scores/{resource_type}", path = {"resource_type"}, query = {"ids"}, header = {"Accept"} },
    ["pagerduty.list_rotations"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations", path = {"id"}, query = {"limit", "offset"} },
    ["pagerduty.list_ruleset_event_rules"] = { method = "GET", url = "https://api.pagerduty.com/rulesets/{id}/rules", path = {"id"}, query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_rulesets"] = { method = "GET", url = "https://api.pagerduty.com/rulesets", query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_schedule_overrides"] = { method = "GET", url = "https://api.pagerduty.com/schedules/{id}/overrides", path = {"id"}, query = {"since", "until", "editable", "overflow"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_schedule_users"] = { method = "GET", url = "https://api.pagerduty.com/schedules/{id}/users", path = {"id"}, query = {"since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_schedules"] = { method = "GET", url = "https://api.pagerduty.com/schedules", query = {"limit", "offset", "total", "query", "include[]", "time_zone", "include_next_oncall_for_user", "since", "until", "team_ids[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_schedules_audit_records"] = { method = "GET", url = "https://api.pagerduty.com/schedules/{id}/audit/records", path = {"id"}, query = {"limit", "cursor", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_schedules_audit_records_v3"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules/{id}/audit/records", path = {"id"}, query = {"limit", "cursor", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_schedules_v3"] = { method = "GET", url = "https://api.pagerduty.com/v3/schedules", query = {"limit", "offset", "query", "total", "team_ids[]"} },
    ["pagerduty.list_service_audit_records"] = { method = "GET", url = "https://api.pagerduty.com/services/{id}/audit/records", path = {"id"}, query = {"limit", "cursor", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_service_change_events"] = { method = "GET", url = "https://api.pagerduty.com/services/{id}/change_events", path = {"id"}, query = {"since", "until", "limit", "offset", "total", "team_ids[]", "integration_ids[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_service_custom_field_options"] = { method = "GET", url = "https://api.pagerduty.com/services/custom_fields/{field_id}/field_options", path = {"field_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_service_custom_fields"] = { method = "GET", url = "https://api.pagerduty.com/services/custom_fields", query = {"include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_service_event_rules"] = { method = "GET", url = "https://api.pagerduty.com/services/{id}/rules", path = {"id"}, query = {"limit", "offset", "total", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_service_feature_enablements"] = { method = "GET", url = "https://api.pagerduty.com/services/{id}/enablements", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_service_now_integrations"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/integrations/servicenow", header = {"Accept"} },
    ["pagerduty.list_services"] = { method = "GET", url = "https://api.pagerduty.com/services", query = {"query", "limit", "offset", "total", "team_ids[]", "time_zone", "sort_by", "include[]", "name"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_sre_memories"] = { method = "GET", url = "https://api.pagerduty.com/sre_agent/memories", query = {"limit", "service_id", "incident_id", "type"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_standards"] = { method = "GET", url = "https://api.pagerduty.com/standards", query = {"active", "resource_type"}, header = {"Accept"} },
    ["pagerduty.list_status_dashboards"] = { method = "GET", url = "https://api.pagerduty.com/status_dashboards", header = {"Accept"} },
    ["pagerduty.list_status_page_impacts"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/impacts", path = {"id"}, query = {"post_type"}, header = {"Accept"} },
    ["pagerduty.list_status_page_post_updates"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}/post_updates", path = {"id", "post_id"}, query = {"reviewed_status"}, header = {"Accept"} },
    ["pagerduty.list_status_page_posts"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/posts", path = {"id"}, query = {"post_type", "reviewed_status", "status[]"}, header = {"Accept"} },
    ["pagerduty.list_status_page_services"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/services", path = {"id"}, header = {"Accept"} },
    ["pagerduty.list_status_page_severities"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/severities", path = {"id"}, query = {"post_type"}, header = {"Accept"} },
    ["pagerduty.list_status_page_statuses"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/statuses", path = {"id"}, query = {"post_type"}, header = {"Accept"} },
    ["pagerduty.list_status_page_subscriptions"] = { method = "GET", url = "https://api.pagerduty.com/status_pages/{id}/subscriptions", path = {"id"}, query = {"status", "channel"}, header = {"Accept"} },
    ["pagerduty.list_status_pages"] = { method = "GET", url = "https://api.pagerduty.com/status_pages", query = {"status_page_type"}, header = {"Accept"} },
    ["pagerduty.list_tags"] = { method = "GET", url = "https://api.pagerduty.com/tags", query = {"limit", "offset", "total", "query"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_team_users"] = { method = "GET", url = "https://api.pagerduty.com/teams/{id}/members", path = {"id"}, query = {"limit", "offset", "total", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_teams"] = { method = "GET", url = "https://api.pagerduty.com/teams", query = {"limit", "offset", "total", "query"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_teams_audit_records"] = { method = "GET", url = "https://api.pagerduty.com/teams/{id}/audit/records", path = {"id"}, query = {"limit", "cursor", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_user_delegations"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/oauth_delegations", path = {"id"}, query = {"delegation_type", "status", "limit", "cursor"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_users"] = { method = "GET", url = "https://api.pagerduty.com/users", query = {"query", "team_ids[]", "limit", "offset", "total", "include[]"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_users_audit_records"] = { method = "GET", url = "https://api.pagerduty.com/users/{id}/audit/records", path = {"id"}, query = {"limit", "cursor", "since", "until"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_vendors"] = { method = "GET", url = "https://api.pagerduty.com/vendors", query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.list_webhook_subscriptions"] = { method = "GET", url = "https://api.pagerduty.com/webhook_subscriptions", query = {"limit", "offset", "total", "filter_type", "filter_id"}, header = {"Accept"} },
    ["pagerduty.list_workflow_integration_connections"] = { method = "GET", url = "https://api.pagerduty.com/workflows/integrations/connections", query = {"limit", "cursor", "name"}, header = {"Accept"} },
    ["pagerduty.list_workflow_integration_connections_by_integration"] = { method = "GET", url = "https://api.pagerduty.com/workflows/integrations/{integration_id}/connections", path = {"integration_id"}, query = {"limit", "cursor", "name"}, header = {"Accept"} },
    ["pagerduty.list_workflow_integrations"] = { method = "GET", url = "https://api.pagerduty.com/workflows/integrations", query = {"limit", "cursor", "include_deprecated"}, header = {"Accept"} },
    ["pagerduty.mark_event_enrichment_as_default"] = { method = "PUT", url = "https://api.pagerduty.com/enrichment/event_enrichments/default", header = {"Accept", "Content-Type"} },
    ["pagerduty.merge_incidents"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/{id}/merge", path = {"id"}, header = {"Accept", "Content-Type", "From"}, body = {"source_incidents"} },
    ["pagerduty.migrate_orchestration_integration"] = { method = "POST", url = "https://api.pagerduty.com/event_orchestrations/{id}/integrations/migration", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"source_id", "source_type", "integration_id"} },
    ["pagerduty.post_alert_grouping_settings"] = { method = "POST", url = "https://api.pagerduty.com/alert_grouping_settings", header = {"Accept", "Content-Type"}, body = {"alert_grouping_setting"} },
    ["pagerduty.post_incident_workflow"] = { method = "POST", url = "https://api.pagerduty.com/incident_workflows", header = {"Accept", "Content-Type"}, body = {"incident_workflow"} },
    ["pagerduty.post_orchestration"] = { method = "POST", url = "https://api.pagerduty.com/event_orchestrations", header = {"Accept", "Content-Type"}, body = {"orchestration"} },
    ["pagerduty.post_orchestration_integration"] = { method = "POST", url = "https://api.pagerduty.com/event_orchestrations/{id}/integrations", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"integration"} },
    ["pagerduty.put_alert_grouping_setting"] = { method = "PUT", url = "https://api.pagerduty.com/alert_grouping_settings/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"alert_grouping_setting"} },
    ["pagerduty.put_business_service_priority_thresholds"] = { method = "PUT", url = "https://api.pagerduty.com/business_services/priority_thresholds", header = {"Accept"}, body = {"global_threshold"} },
    ["pagerduty.put_incident_manual_business_service_association"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/{id}/business_services/{business_service_id}/impacts", path = {"id", "business_service_id"}, header = {"Accept"}, body = {"relation"} },
    ["pagerduty.put_incident_workflow"] = { method = "PUT", url = "https://api.pagerduty.com/incident_workflows/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"incident_workflow"} },
    ["pagerduty.query_enrichment_data"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/query", header = {"Accept", "Content-Type"} },
    ["pagerduty.regenerate_user_private_url_key"] = { method = "POST", url = "https://api.pagerduty.com/users/{id}/regenerate_private_url_key", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.remove_business_service_account_subscription"] = { method = "DELETE", url = "https://api.pagerduty.com/business_services/{id}/account_subscription", path = {"id"}, header = {"Accept"} },
    ["pagerduty.remove_business_service_notification_subscriber"] = { method = "POST", url = "https://api.pagerduty.com/business_services/{id}/unsubscribe", path = {"id"}, header = {"Accept"}, body = {"subscribers"} },
    ["pagerduty.remove_incident_notification_subscribers"] = { method = "POST", url = "https://api.pagerduty.com/incidents/{id}/status_updates/unsubscribe", path = {"id"}, header = {"Accept"}, body = {"subscribers"} },
    ["pagerduty.remove_team_notification_subscriptions"] = { method = "POST", url = "https://api.pagerduty.com/teams/{id}/notification_subscriptions/unsubscribe", path = {"id"}, header = {"Accept"}, body = {"subscribables"} },
    ["pagerduty.render_template"] = { method = "POST", url = "https://api.pagerduty.com/templates/{id}/render", path = {"id"} },
    ["pagerduty.set_incident_field_values"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/{id}/custom_fields/values", path = {"id"}, body = {"custom_fields"} },
    ["pagerduty.test_service_now_table"] = { method = "GET", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/{integration_id}/tables/{table_id}/test", path = {"integration_id", "table_id"}, header = {"Accept"} },
    ["pagerduty.test_webhook_subscription"] = { method = "POST", url = "https://api.pagerduty.com/webhook_subscriptions/{id}/ping", path = {"id"}, header = {"Accept"} },
    ["pagerduty.unsubscribe_user_notification_subscriptions"] = { method = "POST", url = "https://api.pagerduty.com/users/{id}/notification_subscriptions/unsubscribe", path = {"id"}, header = {"Accept"}, body = {"subscribables"} },
    ["pagerduty.update_addon"] = { method = "PUT", url = "https://api.pagerduty.com/addons/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"addon"} },
    ["pagerduty.update_automation_action"] = { method = "PUT", url = "https://api.pagerduty.com/automation_actions/actions/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"action"} },
    ["pagerduty.update_automation_actions_runner"] = { method = "PUT", url = "https://api.pagerduty.com/automation_actions/runners/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"runner"} },
    ["pagerduty.update_business_service"] = { method = "PUT", url = "https://api.pagerduty.com/business_services/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"business_service"} },
    ["pagerduty.update_cache_var_on_global_orch"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/{id}/cache_variables/{cache_variable_id}", path = {"id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_cache_var_on_service_orch"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/cache_variables/{cache_variable_id}", path = {"service_id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_change_event"] = { method = "PUT", url = "https://api.pagerduty.com/change_events/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"change_event"} },
    ["pagerduty.update_custom_shift"] = { method = "PUT", url = "https://api.pagerduty.com/v3/schedules/{id}/custom_shifts/{custom_shift_id}", path = {"id", "custom_shift_id"}, body = {"custom_shift"} },
    ["pagerduty.update_enrichment_schema"] = { method = "PUT", url = "https://api.pagerduty.com/enrichment/schemas/{schema_id}", path = {"schema_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_escalation_policy"] = { method = "PUT", url = "https://api.pagerduty.com/escalation_policies/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"escalation_policy"} },
    ["pagerduty.update_event"] = { method = "PUT", url = "https://api.pagerduty.com/v3/schedules/{id}/rotations/{rotation_id}/events/{event_id}", path = {"id", "rotation_id", "event_id"}, body = {"event"} },
    ["pagerduty.update_event_enrichment"] = { method = "PUT", url = "https://api.pagerduty.com/enrichment/event_enrichments/{id}", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_event_enrichment_rules"] = { method = "PUT", url = "https://api.pagerduty.com/enrichment/event_enrichments/{id}/rules", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_event_orchestration_feature_enablements"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/{id}/enablements/{feature_name}", path = {"id", "feature_name"}, header = {"Accept", "Content-Type"}, body = {"enablement"} },
    ["pagerduty.update_extension"] = { method = "PUT", url = "https://api.pagerduty.com/extensions/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"extension"} },
    ["pagerduty.update_external_data_cache_var_data_on_global_orch"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/{id}/cache_variables/{cache_variable_id}/data", path = {"id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_external_data_cache_var_data_on_service_orch"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/cache_variables/{cache_variable_id}/data", path = {"service_id", "cache_variable_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_incident"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/{id}", path = {"id"}, header = {"Accept", "Content-Type", "From"}, body = {"incident"} },
    ["pagerduty.update_incident_alert"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/{id}/alerts/{alert_id}", path = {"id", "alert_id"}, header = {"Accept", "Content-Type", "From"}, body = {"alert"} },
    ["pagerduty.update_incident_alerts"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/{id}/alerts", path = {"id"}, query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type", "From"}, body = {"alerts"} },
    ["pagerduty.update_incident_note"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/{id}/notes/{note_id}", path = {"id", "note_id"}, header = {"Accept", "Content-Type", "From"}, body = {"note"} },
    ["pagerduty.update_incident_type"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}", path = {"type_id_or_name"}, header = {"Accept", "Content-Type"}, body = {"incident_type"} },
    ["pagerduty.update_incident_type_custom_field"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields/{field_id}", path = {"type_id_or_name", "field_id"}, header = {"Accept", "Content-Type"}, body = {"field"} },
    ["pagerduty.update_incident_type_custom_field_field_option"] = { method = "PUT", url = "https://api.pagerduty.com/incidents/types/{type_id_or_name}/custom_fields/{field_id}/field_options/{field_option_id}", path = {"type_id_or_name", "field_option_id", "field_id"}, header = {"Accept", "Content-Type"}, body = {"field_option"} },
    ["pagerduty.update_incident_workflow_trigger"] = { method = "PUT", url = "https://api.pagerduty.com/incident_workflows/triggers/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"trigger"} },
    ["pagerduty.update_incidents"] = { method = "PUT", url = "https://api.pagerduty.com/incidents", query = {"limit", "offset", "total"}, header = {"Accept", "Content-Type", "From"}, body = {"incidents"} },
    ["pagerduty.update_ip_allow_list"] = { method = "PUT", url = "https://api.pagerduty.com/ip_allow_lists/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"ip_allow_list"} },
    ["pagerduty.update_log_entry_channel"] = { method = "PUT", url = "https://api.pagerduty.com/log_entries/{id}/channel", path = {"id"}, header = {"Accept", "Content-Type", "From"}, body = {"channel"} },
    ["pagerduty.update_maintenance_window"] = { method = "PUT", url = "https://api.pagerduty.com/maintenance_windows/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"maintenance_window"} },
    ["pagerduty.update_oauth_client"] = { method = "PUT", url = "https://api.pagerduty.com/webhook_subscriptions/oauth_clients/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"oauth_client"} },
    ["pagerduty.update_orch_active_status"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}/active", path = {"service_id"}, header = {"Accept", "Content-Type"}, body = {"active"} },
    ["pagerduty.update_orch_path_global"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/{id}/global", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"orchestration_path"} },
    ["pagerduty.update_orch_path_router"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/{id}/router", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_orch_path_service"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/services/{service_id}", path = {"service_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_orch_path_unrouted"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/{id}/unrouted", path = {"id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_orchestration"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"orchestration"} },
    ["pagerduty.update_orchestration_integration"] = { method = "PUT", url = "https://api.pagerduty.com/event_orchestrations/{id}/integrations/{integration_id}", path = {"id", "integration_id"}, header = {"Accept", "Content-Type"}, body = {"integration"} },
    ["pagerduty.update_override"] = { method = "PUT", url = "https://api.pagerduty.com/v3/schedules/{id}/overrides/{override_id}", path = {"id", "override_id"}, body = {"override"} },
    ["pagerduty.update_ruleset"] = { method = "PUT", url = "https://api.pagerduty.com/rulesets/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"ruleset"} },
    ["pagerduty.update_ruleset_event_rule"] = { method = "PUT", url = "https://api.pagerduty.com/rulesets/{id}/rules/{rule_id}", path = {"id", "rule_id"}, header = {"Accept", "Content-Type"}, body = {"rule", "rule_id"} },
    ["pagerduty.update_schedule"] = { method = "PUT", url = "https://api.pagerduty.com/schedules/{id}", path = {"id"}, query = {"overflow"}, header = {"Accept", "Content-Type"}, body = {"schedule"} },
    ["pagerduty.update_schedule_v3"] = { method = "PUT", url = "https://api.pagerduty.com/v3/schedules/{id}", path = {"id"}, body = {"schedule"} },
    ["pagerduty.update_service"] = { method = "PUT", url = "https://api.pagerduty.com/services/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"service"} },
    ["pagerduty.update_service_custom_field"] = { method = "PUT", url = "https://api.pagerduty.com/services/custom_fields/{field_id}", path = {"field_id"}, header = {"Accept", "Content-Type"}, body = {"field"} },
    ["pagerduty.update_service_custom_field_option"] = { method = "PUT", url = "https://api.pagerduty.com/services/custom_fields/{field_id}/field_options/{field_option_id}", path = {"field_id", "field_option_id"}, header = {"Accept", "Content-Type"}, body = {"field_option"} },
    ["pagerduty.update_service_custom_field_values"] = { method = "PUT", url = "https://api.pagerduty.com/services/{id}/custom_fields/values", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"custom_fields"} },
    ["pagerduty.update_service_event_rule"] = { method = "PUT", url = "https://api.pagerduty.com/services/{id}/rules/{rule_id}", path = {"id", "rule_id"}, header = {"Accept", "Content-Type"}, body = {"rule", "rule_id"} },
    ["pagerduty.update_service_feature_enablement"] = { method = "PUT", url = "https://api.pagerduty.com/services/{id}/enablements/{feature_name}", path = {"id", "feature_name"}, header = {"Accept", "Content-Type"}, body = {"enablement"} },
    ["pagerduty.update_service_integration"] = { method = "PUT", url = "https://api.pagerduty.com/services/{id}/integrations/{integration_id}", path = {"id", "integration_id"}, header = {"Accept", "Content-Type"}, body = {"integration"} },
    ["pagerduty.update_service_now_credentials"] = { method = "PUT", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/credentials/{credentials_id}", path = {"credentials_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_service_now_table"] = { method = "PUT", url = "https://api.pagerduty.com/enrichment/integrations/servicenow/{integration_id}/tables/{table_id}", path = {"integration_id", "table_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_session_configurations"] = { method = "PUT", url = "https://api.pagerduty.com/session_configurations", query = {"type"}, header = {"Accept", "Content-Type"}, body = {"session_configuration"} },
    ["pagerduty.update_sre_memory"] = { method = "PUT", url = "https://api.pagerduty.com/sre_agent/memories/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"memory"} },
    ["pagerduty.update_standard"] = { method = "PUT", url = "https://api.pagerduty.com/standards/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"active", "values", "description", "inclusions", "exclusions"} },
    ["pagerduty.update_status_page_post"] = { method = "PUT", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}", path = {"id", "post_id"}, header = {"Accept"}, body = {"post"} },
    ["pagerduty.update_status_page_post_update"] = { method = "PUT", url = "https://api.pagerduty.com/status_pages/{id}/posts/{post_id}/post_updates/{post_update_id}", path = {"id", "post_id", "post_update_id"}, header = {"Accept"}, body = {"post_update"} },
    ["pagerduty.update_team"] = { method = "PUT", url = "https://api.pagerduty.com/teams/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"team"} },
    ["pagerduty.update_team_escalation_policy"] = { method = "PUT", url = "https://api.pagerduty.com/teams/{id}/escalation_policies/{escalation_policy_id}", path = {"id", "escalation_policy_id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.update_team_user"] = { method = "PUT", url = "https://api.pagerduty.com/teams/{id}/users/{user_id}", path = {"id", "user_id"}, header = {"Accept", "Content-Type"}, body = {"role"} },
    ["pagerduty.update_template"] = { method = "PUT", url = "https://api.pagerduty.com/templates/{id}", path = {"id"}, body = {"template"} },
    ["pagerduty.update_user"] = { method = "PUT", url = "https://api.pagerduty.com/users/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"user"} },
    ["pagerduty.update_user_contact_method"] = { method = "PUT", url = "https://api.pagerduty.com/users/{id}/contact_methods/{contact_method_id}", path = {"id", "contact_method_id"}, header = {"Accept", "Content-Type"}, body = {"contact_method"} },
    ["pagerduty.update_user_handoff_notification"] = { method = "PUT", url = "https://api.pagerduty.com/users/{id}/oncall_handoff_notification_rules/{oncall_handoff_notification_rule_id}", path = {"id", "oncall_handoff_notification_rule_id"}, header = {"Accept", "Content-Type"}, body = {"oncall_handoff_notification_rule"} },
    ["pagerduty.update_user_notification_rule"] = { method = "PUT", url = "https://api.pagerduty.com/users/{id}/notification_rules/{notification_rule_id}", path = {"id", "notification_rule_id"}, header = {"Accept", "Content-Type"}, body = {"notification_rule"} },
    ["pagerduty.update_user_status_update_notification_rule"] = { method = "PUT", url = "https://api.pagerduty.com/users/{id}/status_update_notification_rules/{status_update_notification_rule_id}", path = {"id", "status_update_notification_rule_id"}, header = {"Accept", "Content-Type"}, body = {"status_update_notification_rule"} },
    ["pagerduty.update_webhook_subscription"] = { method = "PUT", url = "https://api.pagerduty.com/webhook_subscriptions/{id}", path = {"id"}, header = {"Accept", "Content-Type"}, body = {"webhook_subscription"} },
    ["pagerduty.update_workflow_integration_connection"] = { method = "PATCH", url = "https://api.pagerduty.com/workflows/integrations/{integration_id}/connections/{id}", path = {"integration_id", "id"}, header = {"Accept", "Content-Type"} },
    ["pagerduty.upload_enrichment_csv"] = { method = "POST", url = "https://api.pagerduty.com/enrichment/schemas/{schema_id}/records", path = {"schema_id"}, query = {"filename"}, header = {"Accept"} },
  },
}
