-- Open Hands — every call this API accepts, as data.
--
-- GENERATED from https://docs.all-hands.dev/openapi.json
-- Published on the vendor's own documentation site (https://docs.all-hands.dev).
-- 43 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "open-hands",
  name = "Open Hands",
  base = "https://app.all-hands.dev",
  docs = "https://nango.dev/docs/integrations/all/open-hands",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "OPEN_HANDS_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["open-hands.add_event_api_conversations_conversation_id_events_post"] = { method = "POST", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/events", path = {"conversation_id"} },
    ["open-hands.alive_alive_get"] = { method = "GET", url = "https://app.all-hands.dev/alive" },
    ["open-hands.create_custom_secret_api_secrets_post"] = { method = "POST", url = "https://app.all-hands.dev/api/secrets", body = {"name", "description", "value"} },
    ["open-hands.delete_conversation_api_conversations_conversation_id_delete"] = { method = "DELETE", url = "https://app.all-hands.dev/api/conversations/{conversation_id}", path = {"conversation_id"} },
    ["open-hands.delete_custom_secret_api_secrets_secret_id_delete"] = { method = "DELETE", url = "https://app.all-hands.dev/api/secrets/{secret_id}", path = {"secret_id"} },
    ["open-hands.get_agents_api_options_agents_get"] = { method = "GET", url = "https://app.all-hands.dev/api/options/agents" },
    ["open-hands.get_config_api_options_config_get"] = { method = "GET", url = "https://app.all-hands.dev/api/options/config" },
    ["open-hands.get_conversation_api_conversations_conversation_id_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}", path = {"conversation_id"} },
    ["open-hands.get_litellm_models_api_options_models_get"] = { method = "GET", url = "https://app.all-hands.dev/api/options/models" },
    ["open-hands.get_microagents_api_conversations_conversation_id_microagents_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/microagents", path = {"conversation_id"} },
    ["open-hands.get_prompt_api_conversations_conversation_id_remember_prompt_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/remember-prompt", path = {"conversation_id"}, query = {"event_id"} },
    ["open-hands.get_remote_runtime_config_api_conversations_conversation_id_config_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/config", path = {"conversation_id"} },
    ["open-hands.get_repository_branches_api_user_repository_branches_get"] = { method = "GET", url = "https://app.all-hands.dev/api/user/repository/branches", query = {"repository"} },
    ["open-hands.get_repository_microagent_content_api_user_repository_repository_name_microagents_content_get"] = { method = "GET", url = "https://app.all-hands.dev/api/user/repository/{repository_name}/microagents/content", path = {"repository_name"}, query = {"file_path"} },
    ["open-hands.get_repository_microagents_api_user_repository_repository_name_microagents_get"] = { method = "GET", url = "https://app.all-hands.dev/api/user/repository/{repository_name}/microagents", path = {"repository_name"} },
    ["open-hands.get_security_analyzers_api_options_security_analyzers_get"] = { method = "GET", url = "https://app.all-hands.dev/api/options/security-analyzers" },
    ["open-hands.get_suggested_tasks_api_user_suggested_tasks_get"] = { method = "GET", url = "https://app.all-hands.dev/api/user/suggested-tasks" },
    ["open-hands.get_trajectory_api_conversations_conversation_id_trajectory_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/trajectory", path = {"conversation_id"} },
    ["open-hands.get_user_api_user_info_get"] = { method = "GET", url = "https://app.all-hands.dev/api/user/info" },
    ["open-hands.get_user_installations_api_user_installations_get"] = { method = "GET", url = "https://app.all-hands.dev/api/user/installations", query = {"provider"} },
    ["open-hands.get_user_repositories_api_user_repositories_get"] = { method = "GET", url = "https://app.all-hands.dev/api/user/repositories", query = {"sort", "selected_provider", "page", "per_page", "installation_id"} },
    ["open-hands.git_changes_api_conversations_conversation_id_git_changes_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/git/changes", path = {"conversation_id"} },
    ["open-hands.git_diff_api_conversations_conversation_id_git_diff_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/git/diff", path = {"conversation_id"}, query = {"path"} },
    ["open-hands.health_health_get"] = { method = "GET", url = "https://app.all-hands.dev/health" },
    ["open-hands.list_files_api_conversations_conversation_id_list_files_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/list-files", path = {"conversation_id"}, query = {"path"} },
    ["open-hands.load_custom_secrets_names_api_secrets_get"] = { method = "GET", url = "https://app.all-hands.dev/api/secrets" },
    ["open-hands.load_settings_api_settings_get"] = { method = "GET", url = "https://app.all-hands.dev/api/settings" },
    ["open-hands.new_conversation_api_conversations_post"] = { method = "POST", url = "https://app.all-hands.dev/api/conversations", body = {"repository", "git_provider", "selected_branch", "initial_user_msg", "image_urls", "replay_json", "suggested_task", "create_microagent", "conversation_instructions", "mcp_config", "conversation_id"} },
    ["open-hands.reset_settings_api_reset_settings_post"] = { method = "POST", url = "https://app.all-hands.dev/api/reset-settings" },
    ["open-hands.search_conversations_api_conversations_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations", query = {"page_id", "limit", "selected_repository", "conversation_trigger"} },
    ["open-hands.search_events_api_conversations_conversation_id_events_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/events", path = {"conversation_id"}, query = {"start_id", "end_id", "reverse", "limit"} },
    ["open-hands.search_repositories_api_user_search_repositories_get"] = { method = "GET", url = "https://app.all-hands.dev/api/user/search/repositories", query = {"query", "per_page", "sort", "order", "selected_provider"} },
    ["open-hands.select_file_api_conversations_conversation_id_select_file_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/select-file", path = {"conversation_id"}, query = {"file"} },
    ["open-hands.start_conversation_api_conversations_conversation_id_start_post"] = { method = "POST", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/start", path = {"conversation_id"}, body = {"providers_set"} },
    ["open-hands.stop_conversation_api_conversations_conversation_id_stop_post"] = { method = "POST", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/stop", path = {"conversation_id"} },
    ["open-hands.store_provider_tokens_api_add_git_providers_post"] = { method = "POST", url = "https://app.all-hands.dev/api/add-git-providers", body = {"mcp_config", "provider_tokens"} },
    ["open-hands.store_settings_api_settings_post"] = { method = "POST", url = "https://app.all-hands.dev/api/settings", body = {"language", "agent", "max_iterations", "security_analyzer", "confirmation_mode", "llm_model", "llm_api_key", "llm_base_url", "remote_runtime_resource_factor", "secrets_store", "enable_default_condenser", "enable_sound_notifications", "enable_proactive_conversation_starters", "enable_solvability_analysis", "user_consents_to_analytics", "sandbox_base_container_image", "sandbox_runtime_container_image", "mcp_config", "search_api_key", "sandbox_api_key", "max_budget_per_task", "email", "email_verified", "git_user_name", "git_user_email"} },
    ["open-hands.submit_feedback_api_conversations_conversation_id_submit_feedback_post"] = { method = "POST", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/submit-feedback", path = {"conversation_id"} },
    ["open-hands.unset_provider_tokens_api_unset_provider_tokens_post"] = { method = "POST", url = "https://app.all-hands.dev/api/unset-provider-tokens" },
    ["open-hands.update_conversation_api_conversations_conversation_id_patch"] = { method = "PATCH", url = "https://app.all-hands.dev/api/conversations/{conversation_id}", path = {"conversation_id"}, body = {"title"} },
    ["open-hands.update_custom_secret_api_secrets_secret_id_put"] = { method = "PUT", url = "https://app.all-hands.dev/api/secrets/{secret_id}", path = {"secret_id"}, body = {"name", "description"} },
    ["open-hands.upload_files_api_conversations_conversation_id_upload_files_post"] = { method = "POST", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/upload-files", path = {"conversation_id"}, body = {"files"} },
    ["open-hands.zip_current_workspace_api_conversations_conversation_id_zip_directory_get"] = { method = "GET", url = "https://app.all-hands.dev/api/conversations/{conversation_id}/zip-directory", path = {"conversation_id"} },
  },
}
