-- Google Calendar — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/openapi.json
-- APIs.guru's mirror of googleapis.com:calendar, matched on googleapis.com. A mirror lags the vendor.
-- 37 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "google-calendar-mcp",
  name = "Google Calendar",
  base = "https://calendarmcp.googleapis.com/mcp",
  docs = "https://nango.dev/docs/api-integrations/google-calendar-mcp",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "GOOGLE_CALENDAR_MCP_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["google-calendar-mcp.calendar_acl_delete"] = { method = "DELETE", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/acl/{ruleId}", path = {"calendarId", "ruleId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_acl_get"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/acl/{ruleId}", path = {"calendarId", "ruleId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_acl_insert"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/acl", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "sendNotifications"}, body = {"etag", "id", "kind", "role", "scope"} },
    ["google-calendar-mcp.calendar_acl_list"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/acl", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "pageToken", "showDeleted", "syncToken"} },
    ["google-calendar-mcp.calendar_acl_patch"] = { method = "PATCH", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/acl/{ruleId}", path = {"calendarId", "ruleId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "sendNotifications"}, body = {"etag", "id", "kind", "role", "scope"} },
    ["google-calendar-mcp.calendar_acl_update"] = { method = "PUT", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/acl/{ruleId}", path = {"calendarId", "ruleId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "sendNotifications"}, body = {"etag", "id", "kind", "role", "scope"} },
    ["google-calendar-mcp.calendar_acl_watch"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/acl/watch", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "pageToken", "showDeleted", "syncToken"}, body = {"address", "expiration", "id", "kind", "params", "payload", "resourceId", "resourceUri", "type"} },
    ["google-calendar-mcp.calendar_calendar_list_delete"] = { method = "DELETE", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/calendarList/{calendarId}", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_calendar_list_get"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/calendarList/{calendarId}", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_calendar_list_insert"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/calendarList", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "colorRgbFormat"}, body = {"accessRole", "backgroundColor", "colorId", "conferenceProperties", "defaultReminders", "deleted", "description", "etag", "foregroundColor", "hidden", "id", "kind", "location", "notificationSettings", "primary", "selected", "summary", "summaryOverride", "timeZone"} },
    ["google-calendar-mcp.calendar_calendar_list_list"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/calendarList", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "minAccessRole", "pageToken", "showDeleted", "showHidden", "syncToken"} },
    ["google-calendar-mcp.calendar_calendar_list_patch"] = { method = "PATCH", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/calendarList/{calendarId}", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "colorRgbFormat"}, body = {"accessRole", "backgroundColor", "colorId", "conferenceProperties", "defaultReminders", "deleted", "description", "etag", "foregroundColor", "hidden", "id", "kind", "location", "notificationSettings", "primary", "selected", "summary", "summaryOverride", "timeZone"} },
    ["google-calendar-mcp.calendar_calendar_list_update"] = { method = "PUT", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/calendarList/{calendarId}", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "colorRgbFormat"}, body = {"accessRole", "backgroundColor", "colorId", "conferenceProperties", "defaultReminders", "deleted", "description", "etag", "foregroundColor", "hidden", "id", "kind", "location", "notificationSettings", "primary", "selected", "summary", "summaryOverride", "timeZone"} },
    ["google-calendar-mcp.calendar_calendar_list_watch"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/calendarList/watch", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "minAccessRole", "pageToken", "showDeleted", "showHidden", "syncToken"}, body = {"address", "expiration", "id", "kind", "params", "payload", "resourceId", "resourceUri", "type"} },
    ["google-calendar-mcp.calendar_calendars_clear"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/clear", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_calendars_delete"] = { method = "DELETE", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_calendars_get"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_calendars_insert"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"conferenceProperties", "description", "etag", "id", "kind", "location", "summary", "timeZone"} },
    ["google-calendar-mcp.calendar_calendars_patch"] = { method = "PATCH", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"conferenceProperties", "description", "etag", "id", "kind", "location", "summary", "timeZone"} },
    ["google-calendar-mcp.calendar_calendars_update"] = { method = "PUT", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"conferenceProperties", "description", "etag", "id", "kind", "location", "summary", "timeZone"} },
    ["google-calendar-mcp.calendar_channels_stop"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/channels/stop", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"address", "expiration", "id", "kind", "params", "payload", "resourceId", "resourceUri", "type"} },
    ["google-calendar-mcp.calendar_colors_get"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/colors", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_events_delete"] = { method = "DELETE", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/{eventId}", path = {"calendarId", "eventId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "sendNotifications", "sendUpdates"} },
    ["google-calendar-mcp.calendar_events_get"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/{eventId}", path = {"calendarId", "eventId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "alwaysIncludeEmail", "maxAttendees", "timeZone"} },
    ["google-calendar-mcp.calendar_events_import"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/import", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "conferenceDataVersion", "supportsAttachments"}, body = {"anyoneCanAddSelf", "attachments", "attendees", "attendeesOmitted", "colorId", "conferenceData", "created", "creator", "description", "end", "endTimeUnspecified", "etag", "eventType", "extendedProperties", "gadget", "guestsCanInviteOthers", "guestsCanModify", "guestsCanSeeOtherGuests", "hangoutLink", "htmlLink", "iCalUID", "id", "kind", "location", "locked", "organizer", "originalStartTime", "privateCopy", "recurrence", "recurringEventId", "reminders", "sequence", "source", "start", "status", "summary", "transparency", "updated", "visibility", "workingLocationProperties"} },
    ["google-calendar-mcp.calendar_events_insert"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "conferenceDataVersion", "maxAttendees", "sendNotifications", "sendUpdates", "supportsAttachments"}, body = {"anyoneCanAddSelf", "attachments", "attendees", "attendeesOmitted", "colorId", "conferenceData", "created", "creator", "description", "end", "endTimeUnspecified", "etag", "eventType", "extendedProperties", "gadget", "guestsCanInviteOthers", "guestsCanModify", "guestsCanSeeOtherGuests", "hangoutLink", "htmlLink", "iCalUID", "id", "kind", "location", "locked", "organizer", "originalStartTime", "privateCopy", "recurrence", "recurringEventId", "reminders", "sequence", "source", "start", "status", "summary", "transparency", "updated", "visibility", "workingLocationProperties"} },
    ["google-calendar-mcp.calendar_events_instances"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/{eventId}/instances", path = {"calendarId", "eventId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "alwaysIncludeEmail", "maxAttendees", "maxResults", "originalStart", "pageToken", "showDeleted", "timeMax", "timeMin", "timeZone"} },
    ["google-calendar-mcp.calendar_events_list"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "alwaysIncludeEmail", "eventTypes", "iCalUID", "maxAttendees", "maxResults", "orderBy", "pageToken", "privateExtendedProperty", "q", "sharedExtendedProperty", "showDeleted", "showHiddenInvitations", "singleEvents", "syncToken", "timeMax", "timeMin", "timeZone", "updatedMin"} },
    ["google-calendar-mcp.calendar_events_move"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/{eventId}/move", path = {"calendarId", "eventId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "destination", "sendNotifications", "sendUpdates"} },
    ["google-calendar-mcp.calendar_events_patch"] = { method = "PATCH", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/{eventId}", path = {"calendarId", "eventId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "alwaysIncludeEmail", "conferenceDataVersion", "maxAttendees", "sendNotifications", "sendUpdates", "supportsAttachments"}, body = {"anyoneCanAddSelf", "attachments", "attendees", "attendeesOmitted", "colorId", "conferenceData", "created", "creator", "description", "end", "endTimeUnspecified", "etag", "eventType", "extendedProperties", "gadget", "guestsCanInviteOthers", "guestsCanModify", "guestsCanSeeOtherGuests", "hangoutLink", "htmlLink", "iCalUID", "id", "kind", "location", "locked", "organizer", "originalStartTime", "privateCopy", "recurrence", "recurringEventId", "reminders", "sequence", "source", "start", "status", "summary", "transparency", "updated", "visibility", "workingLocationProperties"} },
    ["google-calendar-mcp.calendar_events_quick_add"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/quickAdd", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "text", "sendNotifications", "sendUpdates"} },
    ["google-calendar-mcp.calendar_events_update"] = { method = "PUT", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/{eventId}", path = {"calendarId", "eventId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "alwaysIncludeEmail", "conferenceDataVersion", "maxAttendees", "sendNotifications", "sendUpdates", "supportsAttachments"}, body = {"anyoneCanAddSelf", "attachments", "attendees", "attendeesOmitted", "colorId", "conferenceData", "created", "creator", "description", "end", "endTimeUnspecified", "etag", "eventType", "extendedProperties", "gadget", "guestsCanInviteOthers", "guestsCanModify", "guestsCanSeeOtherGuests", "hangoutLink", "htmlLink", "iCalUID", "id", "kind", "location", "locked", "organizer", "originalStartTime", "privateCopy", "recurrence", "recurringEventId", "reminders", "sequence", "source", "start", "status", "summary", "transparency", "updated", "visibility", "workingLocationProperties"} },
    ["google-calendar-mcp.calendar_events_watch"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/calendars/{calendarId}/events/watch", path = {"calendarId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "alwaysIncludeEmail", "eventTypes", "iCalUID", "maxAttendees", "maxResults", "orderBy", "pageToken", "privateExtendedProperty", "q", "sharedExtendedProperty", "showDeleted", "showHiddenInvitations", "singleEvents", "syncToken", "timeMax", "timeMin", "timeZone", "updatedMin"}, body = {"address", "expiration", "id", "kind", "params", "payload", "resourceId", "resourceUri", "type"} },
    ["google-calendar-mcp.calendar_freebusy_query"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/freeBusy", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"calendarExpansionMax", "groupExpansionMax", "items", "timeMax", "timeMin", "timeZone"} },
    ["google-calendar-mcp.calendar_settings_get"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/settings/{setting}", path = {"setting"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-calendar-mcp.calendar_settings_list"] = { method = "GET", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/settings", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "pageToken", "syncToken"} },
    ["google-calendar-mcp.calendar_settings_watch"] = { method = "POST", url = "https://calendarmcp.googleapis.com/mcp/calendar/v3/users/me/settings/watch", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "pageToken", "syncToken"}, body = {"address", "expiration", "id", "kind", "params", "payload", "resourceId", "resourceUri", "type"} },
  },
}
