-- WorkOS — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/workos/openapi-spec/main/spec/open-api-spec.yaml
-- Published by workos, the vendor's own GitHub organisation.
-- 261 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "workos",
  name = "WorkOS",
  base = "https://api.workos.com",
  docs = "https://nango.dev/docs/api-integrations/workos",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "WORKOS_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["workos.agent_admin_controller_get_registration"] = { method = "GET", url = "https://api.workos.com/agents/registrations/{id}", path = {"id"} },
    ["workos.agent_admin_controller_link_claim_attempt_to_external_user"] = { method = "PATCH", url = "https://api.workos.com/agents/claims/attempts", body = {"type", "claim_attempt_token", "user", "organization_id"} },
    ["workos.agent_admin_controller_validate_credential"] = { method = "POST", url = "https://api.workos.com/agents/credentials/validate" },
    ["workos.agent_blueprints_controller_create"] = { method = "POST", url = "https://api.workos.com/agents/blueprints", body = {"name", "description", "permissions", "invocable_by", "session_settings"} },
    ["workos.agent_blueprints_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/agents/blueprints/{agent_blueprint_id}", path = {"agent_blueprint_id"} },
    ["workos.agent_blueprints_controller_get"] = { method = "GET", url = "https://api.workos.com/agents/blueprints/{agent_blueprint_id}", path = {"agent_blueprint_id"} },
    ["workos.agent_blueprints_controller_list"] = { method = "GET", url = "https://api.workos.com/agents/blueprints", query = {"before", "after", "limit", "order"} },
    ["workos.agent_blueprints_controller_update"] = { method = "PATCH", url = "https://api.workos.com/agents/blueprints/{agent_blueprint_id}", path = {"agent_blueprint_id"}, body = {"name", "description", "permissions", "invocable_by", "session_settings"} },
    ["workos.agent_blueprints_token_controller_mint_token"] = { method = "POST", url = "https://api.workos.com/agents/blueprints/{agent_blueprint_id}/tokens", path = {"agent_blueprint_id"} },
    ["workos.agent_blueprints_token_controller_validate_token"] = { method = "POST", url = "https://api.workos.com/agents/blueprints/{agent_blueprint_id}/tokens/validate", path = {"agent_blueprint_id"}, body = {"agent_access_token"} },
    ["workos.agent_instance_sessions_controller_get"] = { method = "GET", url = "https://api.workos.com/agents/sessions/{agent_instance_session_id}", path = {"agent_instance_session_id"} },
    ["workos.agent_instance_sessions_controller_list"] = { method = "GET", url = "https://api.workos.com/agents/sessions", query = {"before", "after", "limit", "order", "organization_id", "agent_blueprint_id", "agent_instance_id"} },
    ["workos.agent_instance_sessions_controller_revoke"] = { method = "POST", url = "https://api.workos.com/agents/sessions/{agent_instance_session_id}/revoke", path = {"agent_instance_session_id"} },
    ["workos.agent_instances_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/agents/instances/{agent_instance_id}", path = {"agent_instance_id"} },
    ["workos.agent_instances_controller_get"] = { method = "GET", url = "https://api.workos.com/agents/instances/{agent_instance_id}", path = {"agent_instance_id"} },
    ["workos.agent_instances_controller_list"] = { method = "GET", url = "https://api.workos.com/agents/instances", query = {"before", "after", "limit", "order", "organization_id", "agent_blueprint_id"} },
    ["workos.api_keys_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/api_keys/{id}", path = {"id"} },
    ["workos.api_keys_controller_expire"] = { method = "POST", url = "https://api.workos.com/api_keys/{id}/expire", path = {"id"}, body = {"expires_at"} },
    ["workos.api_keys_controller_validate_api_key"] = { method = "POST", url = "https://api.workos.com/api_keys/validations", body = {"value"} },
    ["workos.application_credentials_controller_create"] = { method = "POST", url = "https://api.workos.com/connect/applications/{id}/client_secrets", path = {"id"} },
    ["workos.application_credentials_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/connect/client_secrets/{id}", path = {"id"} },
    ["workos.application_credentials_controller_list"] = { method = "GET", url = "https://api.workos.com/connect/applications/{id}/client_secrets", path = {"id"} },
    ["workos.applications_controller_create"] = { method = "POST", url = "https://api.workos.com/connect/applications" },
    ["workos.applications_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/connect/applications/{id}", path = {"id"} },
    ["workos.applications_controller_find"] = { method = "GET", url = "https://api.workos.com/connect/applications/{id}", path = {"id"} },
    ["workos.applications_controller_list"] = { method = "GET", url = "https://api.workos.com/connect/applications", query = {"before", "after", "limit", "order", "registration_types", "organization_id"} },
    ["workos.applications_controller_update"] = { method = "PUT", url = "https://api.workos.com/connect/applications/{id}", path = {"id"}, body = {"name", "description", "scopes", "redirect_uris"} },
    ["workos.audit_log_events_controller_create"] = { method = "POST", url = "https://api.workos.com/audit_logs/events", header = {"idempotency-key"}, body = {"organization_id", "event"} },
    ["workos.audit_log_exports_controller_export"] = { method = "GET", url = "https://api.workos.com/audit_logs/exports/{auditLogExportId}", path = {"auditLogExportId"} },
    ["workos.audit_log_exports_controller_exports"] = { method = "POST", url = "https://api.workos.com/audit_logs/exports", body = {"organization_id", "range_start", "range_end", "actions", "actors", "actor_names", "actor_ids", "targets"} },
    ["workos.audit_log_validator_versions_controller_create"] = { method = "POST", url = "https://api.workos.com/audit_logs/actions/{actionName}/schemas", path = {"actionName"}, body = {"actor", "targets", "metadata"} },
    ["workos.audit_log_validator_versions_controller_schemas"] = { method = "GET", url = "https://api.workos.com/audit_logs/actions/{actionName}/schemas", path = {"actionName"}, query = {"before", "after", "limit", "order"} },
    ["workos.audit_log_validators_controller_list"] = { method = "GET", url = "https://api.workos.com/audit_logs/actions", query = {"before", "after", "limit", "order"} },
    ["workos.audit_logs_retention_controller_audit_logs_retention"] = { method = "GET", url = "https://api.workos.com/organizations/{id}/audit_logs_retention", path = {"id"} },
    ["workos.audit_logs_retention_controller_update_audit_logs_retention"] = { method = "PUT", url = "https://api.workos.com/organizations/{id}/audit_logs_retention", path = {"id"} },
    ["workos.authentication_challenges_controller_verify"] = { method = "POST", url = "https://api.workos.com/auth/challenges/{id}/verify", path = {"id"}, body = {"code"} },
    ["workos.authentication_factors_controller_challenge"] = { method = "POST", url = "https://api.workos.com/auth/factors/{id}/challenge", path = {"id"}, body = {"sms_template"} },
    ["workos.authentication_factors_controller_create"] = { method = "POST", url = "https://api.workos.com/auth/factors/enroll", body = {"type", "phone_number", "totp_issuer", "totp_user", "user_id"} },
    ["workos.authentication_factors_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/auth/factors/{id}", path = {"id"} },
    ["workos.authentication_factors_controller_get"] = { method = "GET", url = "https://api.workos.com/auth/factors/{id}", path = {"id"} },
    ["workos.authkit_oauth_resources_controller_create"] = { method = "POST", url = "https://api.workos.com/user_management/authkit_oauth_resources", body = {"uri", "default"} },
    ["workos.authkit_oauth_resources_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/user_management/authkit_oauth_resources/{id}", path = {"id"} },
    ["workos.authkit_oauth_resources_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/authkit_oauth_resources", query = {"before", "after", "limit", "order"} },
    ["workos.authorization_controller_check"] = { method = "POST", url = "https://api.workos.com/authorization/organization_memberships/{organization_membership_id}/check", path = {"organization_membership_id"}, body = {"permission_slug"} },
    ["workos.authorization_controller_list_effective_permissions"] = { method = "GET", url = "https://api.workos.com/authorization/organization_memberships/{organization_membership_id}/resources/{resource_id}/permissions", path = {"organization_membership_id", "resource_id"}, query = {"before", "after", "limit", "order"} },
    ["workos.authorization_controller_list_effective_permissions_by_external_id"] = { method = "GET", url = "https://api.workos.com/authorization/organization_memberships/{organization_membership_id}/resources/{resource_type_slug}/{external_id}/permissions", path = {"organization_membership_id", "resource_type_slug", "external_id"}, query = {"before", "after", "limit", "order"} },
    ["workos.authorization_controller_list_resources_for_membership"] = { method = "GET", url = "https://api.workos.com/authorization/organization_memberships/{organization_membership_id}/resources", path = {"organization_membership_id"}, query = {"before", "after", "limit", "order", "permission_slug", "parent_resource_id", "parent_resource_type_slug", "parent_resource_external_id"} },
    ["workos.authorization_group_role_assignments_controller_create"] = { method = "POST", url = "https://api.workos.com/authorization/groups/{group_id}/role_assignments", path = {"group_id"}, body = {"role_slug", "resource_id", "resource_external_id", "resource_type_slug"} },
    ["workos.authorization_group_role_assignments_controller_get"] = { method = "GET", url = "https://api.workos.com/authorization/groups/{group_id}/role_assignments/{role_assignment_id}", path = {"group_id", "role_assignment_id"} },
    ["workos.authorization_group_role_assignments_controller_list"] = { method = "GET", url = "https://api.workos.com/authorization/groups/{group_id}/role_assignments", path = {"group_id"}, query = {"before", "after", "limit", "order"} },
    ["workos.authorization_group_role_assignments_controller_remove_group_role_assignment"] = { method = "DELETE", url = "https://api.workos.com/authorization/groups/{group_id}/role_assignments/{role_assignment_id}", path = {"group_id", "role_assignment_id"} },
    ["workos.authorization_group_role_assignments_controller_remove_group_role_assignments"] = { method = "DELETE", url = "https://api.workos.com/authorization/groups/{group_id}/role_assignments", path = {"group_id"}, body = {"role_slug", "resource_id", "resource_external_id", "resource_type_slug"} },
    ["workos.authorization_group_role_assignments_controller_replace_group_role_assignments"] = { method = "PUT", url = "https://api.workos.com/authorization/groups/{group_id}/role_assignments", path = {"group_id"}, body = {"role_assignments"} },
    ["workos.authorization_organization_role_permissions_controller_add_permission"] = { method = "POST", url = "https://api.workos.com/authorization/organizations/{organizationId}/roles/{slug}/permissions", path = {"organizationId", "slug"}, body = {"slug"} },
    ["workos.authorization_organization_role_permissions_controller_remove_permission"] = { method = "DELETE", url = "https://api.workos.com/authorization/organizations/{organizationId}/roles/{slug}/permissions/{permissionSlug}", path = {"organizationId", "slug", "permissionSlug"} },
    ["workos.authorization_organization_role_permissions_controller_set_permissions"] = { method = "PUT", url = "https://api.workos.com/authorization/organizations/{organizationId}/roles/{slug}/permissions", path = {"organizationId", "slug"}, body = {"permissions"} },
    ["workos.authorization_organization_roles_controller_create"] = { method = "POST", url = "https://api.workos.com/authorization/organizations/{organizationId}/roles", path = {"organizationId"}, body = {"slug", "name", "description", "resource_type_slug"} },
    ["workos.authorization_organization_roles_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/authorization/organizations/{organizationId}/roles/{slug}", path = {"organizationId", "slug"} },
    ["workos.authorization_organization_roles_controller_get"] = { method = "GET", url = "https://api.workos.com/authorization/organizations/{organizationId}/roles/{slug}", path = {"organizationId", "slug"} },
    ["workos.authorization_organization_roles_controller_list"] = { method = "GET", url = "https://api.workos.com/authorization/organizations/{organizationId}/roles", path = {"organizationId"} },
    ["workos.authorization_organization_roles_controller_update"] = { method = "PATCH", url = "https://api.workos.com/authorization/organizations/{organizationId}/roles/{slug}", path = {"organizationId", "slug"}, body = {"name", "description"} },
    ["workos.authorization_permissions_controller_create"] = { method = "POST", url = "https://api.workos.com/authorization/permissions", body = {"slug", "name", "description", "resource_type_slug"} },
    ["workos.authorization_permissions_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/authorization/permissions/{slug}", path = {"slug"} },
    ["workos.authorization_permissions_controller_find"] = { method = "GET", url = "https://api.workos.com/authorization/permissions/{slug}", path = {"slug"} },
    ["workos.authorization_permissions_controller_list"] = { method = "GET", url = "https://api.workos.com/authorization/permissions", query = {"before", "after", "limit", "order"} },
    ["workos.authorization_permissions_controller_update"] = { method = "PATCH", url = "https://api.workos.com/authorization/permissions/{slug}", path = {"slug"}, body = {"name", "description"} },
    ["workos.authorization_resources_by_external_id_controller_delete_by_external_id"] = { method = "DELETE", url = "https://api.workos.com/authorization/organizations/{organization_id}/resources/{resource_type_slug}/{external_id}", path = {"organization_id", "resource_type_slug", "external_id"}, query = {"cascade_delete"} },
    ["workos.authorization_resources_by_external_id_controller_get_by_external_id"] = { method = "GET", url = "https://api.workos.com/authorization/organizations/{organization_id}/resources/{resource_type_slug}/{external_id}", path = {"organization_id", "resource_type_slug", "external_id"} },
    ["workos.authorization_resources_by_external_id_controller_list_organization_memberships_for_resource_by_external_id"] = { method = "GET", url = "https://api.workos.com/authorization/organizations/{organization_id}/resources/{resource_type_slug}/{external_id}/organization_memberships", path = {"organization_id", "resource_type_slug", "external_id"}, query = {"before", "after", "limit", "order", "permission_slug", "assignment"} },
    ["workos.authorization_resources_by_external_id_controller_update_by_external_id"] = { method = "PATCH", url = "https://api.workos.com/authorization/organizations/{organization_id}/resources/{resource_type_slug}/{external_id}", path = {"organization_id", "resource_type_slug", "external_id"}, body = {"name", "description"} },
    ["workos.authorization_resources_controller_create"] = { method = "POST", url = "https://api.workos.com/authorization/resources", body = {"external_id", "name", "description", "resource_type_slug", "organization_id"} },
    ["workos.authorization_resources_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/authorization/resources/{resource_id}", path = {"resource_id"}, query = {"cascade_delete"} },
    ["workos.authorization_resources_controller_find_by_id"] = { method = "GET", url = "https://api.workos.com/authorization/resources/{resource_id}", path = {"resource_id"} },
    ["workos.authorization_resources_controller_list"] = { method = "GET", url = "https://api.workos.com/authorization/resources", query = {"before", "after", "limit", "order", "organization_id", "resource_type_slug", "resource_external_id", "parent_resource_id", "parent_resource_type_slug", "parent_external_id"} },
    ["workos.authorization_resources_controller_list_organization_memberships_for_resource"] = { method = "GET", url = "https://api.workos.com/authorization/resources/{resource_id}/organization_memberships", path = {"resource_id"}, query = {"before", "after", "limit", "order", "permission_slug", "assignment"} },
    ["workos.authorization_resources_controller_update"] = { method = "PATCH", url = "https://api.workos.com/authorization/resources/{resource_id}", path = {"resource_id"}, body = {"name", "description"} },
    ["workos.authorization_role_assignments_controller_assign_role"] = { method = "POST", url = "https://api.workos.com/authorization/organization_memberships/{organization_membership_id}/role_assignments", path = {"organization_membership_id"}, body = {"role_slug"} },
    ["workos.authorization_role_assignments_controller_list_role_assignments"] = { method = "GET", url = "https://api.workos.com/authorization/organization_memberships/{organization_membership_id}/role_assignments", path = {"organization_membership_id"}, query = {"before", "after", "limit", "order", "resource_id", "resource_external_id", "resource_type_slug"} },
    ["workos.authorization_role_assignments_controller_list_role_assignments_for_resource"] = { method = "GET", url = "https://api.workos.com/authorization/resources/{resource_id}/role_assignments", path = {"resource_id"}, query = {"before", "after", "limit", "order", "role_slug"} },
    ["workos.authorization_role_assignments_controller_list_role_assignments_for_resource_by_external_id"] = { method = "GET", url = "https://api.workos.com/authorization/organizations/{organization_id}/resources/{resource_type_slug}/{external_id}/role_assignments", path = {"organization_id", "resource_type_slug", "external_id"}, query = {"before", "after", "limit", "order", "role_slug"} },
    ["workos.authorization_role_assignments_controller_remove_role_by_criteria"] = { method = "DELETE", url = "https://api.workos.com/authorization/organization_memberships/{organization_membership_id}/role_assignments", path = {"organization_membership_id"}, body = {"role_slug"} },
    ["workos.authorization_role_assignments_controller_remove_role_by_id"] = { method = "DELETE", url = "https://api.workos.com/authorization/organization_memberships/{organization_membership_id}/role_assignments/{role_assignment_id}", path = {"organization_membership_id", "role_assignment_id"} },
    ["workos.authorization_role_permissions_controller_add_permission"] = { method = "POST", url = "https://api.workos.com/authorization/roles/{slug}/permissions", path = {"slug"}, body = {"slug"} },
    ["workos.authorization_role_permissions_controller_set_permissions"] = { method = "PUT", url = "https://api.workos.com/authorization/roles/{slug}/permissions", path = {"slug"}, body = {"permissions"} },
    ["workos.authorization_roles_controller_create"] = { method = "POST", url = "https://api.workos.com/authorization/roles", body = {"slug", "name", "description", "resource_type_slug"} },
    ["workos.authorization_roles_controller_get"] = { method = "GET", url = "https://api.workos.com/authorization/roles/{slug}", path = {"slug"} },
    ["workos.authorization_roles_controller_list"] = { method = "GET", url = "https://api.workos.com/authorization/roles" },
    ["workos.authorization_roles_controller_update"] = { method = "PATCH", url = "https://api.workos.com/authorization/roles/{slug}", path = {"slug"}, body = {"name", "description"} },
    ["workos.authorized_applications_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/user_management/users/{user_id}/authorized_applications/{application_id}", path = {"application_id", "user_id"} },
    ["workos.authorized_applications_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/users/{user_id}/authorized_applications", path = {"user_id"}, query = {"before", "after", "limit", "order"} },
    ["workos.client_api_token_controller_issue_client_api_token"] = { method = "POST", url = "https://api.workos.com/client/token", body = {"organization_id", "user_id"} },
    ["workos.connections_controller_create"] = { method = "POST", url = "https://api.workos.com/connections", body = {"organization_id", "name", "external_id", "connection_type", "attribute_maps"} },
    ["workos.connections_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/connections/{id}", path = {"id"} },
    ["workos.connections_controller_find"] = { method = "GET", url = "https://api.workos.com/connections/{id}", path = {"id"} },
    ["workos.connections_controller_list"] = { method = "GET", url = "https://api.workos.com/connections", query = {"before", "after", "limit", "order", "connection_type", "domain", "organization_id", "search"} },
    ["workos.connections_controller_patch"] = { method = "PATCH", url = "https://api.workos.com/connections/{id}", path = {"id"}, body = {"name", "external_id", "connection_type", "attribute_maps"} },
    ["workos.cors_origins_controller_create_cors_origin"] = { method = "POST", url = "https://api.workos.com/user_management/cors_origins", body = {"origin"} },
    ["workos.cors_origins_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/cors_origins", query = {"before", "after", "limit", "order"} },
    ["workos.data_integrations_controller_get_data_integration_authorize_url"] = { method = "POST", url = "https://api.workos.com/data-integrations/{slug}/authorize", path = {"slug"}, body = {"user_id", "organization_id", "connection_owner", "return_to", "config"} },
    ["workos.data_integrations_controller_get_userland_user_token"] = { method = "POST", url = "https://api.workos.com/data-integrations/{slug}/token", path = {"slug"}, body = {"user_id", "organization_id", "connected_account_id", "connection_owner", "supports_multiple_connections"} },
    ["workos.data_integrations_controller_upsert_api_key"] = { method = "PUT", url = "https://api.workos.com/data-integrations/{slug}/api-key", path = {"slug"}, body = {"user_id", "organization_id", "connected_account_id", "connection_owner"} },
    ["workos.data_integrations_controller_upsert_client_credentials"] = { method = "PUT", url = "https://api.workos.com/data-integrations/{slug}/client-credentials", path = {"slug"}, body = {"user_id", "organization_id", "connected_account_id", "connection_owner", "client_id", "client_secret", "config"} },
    ["workos.data_integrations_controller_vend_credentials"] = { method = "POST", url = "https://api.workos.com/data-integrations/{slug}/credentials", path = {"slug"}, body = {"user_id", "organization_id", "connected_account_id", "connection_owner", "supports_multiple_connections"} },
    ["workos.data_integrations_management_controller_create_data_integration"] = { method = "POST", url = "https://api.workos.com/data-integrations", body = {"provider", "ownership", "description", "enabled", "scopes", "auth_methods", "config", "credentials", "custom_provider"} },
    ["workos.data_integrations_management_controller_delete_data_integration"] = { method = "DELETE", url = "https://api.workos.com/data-integrations/{slug}", path = {"slug"} },
    ["workos.data_integrations_management_controller_delete_organization_data_integration"] = { method = "DELETE", url = "https://api.workos.com/data-integrations/{slug}/organization", path = {"slug"} },
    ["workos.data_integrations_management_controller_get_data_integration"] = { method = "GET", url = "https://api.workos.com/data-integrations/{slug}", path = {"slug"} },
    ["workos.data_integrations_management_controller_get_organization_data_integration"] = { method = "GET", url = "https://api.workos.com/data-integrations/{slug}/organization", path = {"slug"} },
    ["workos.data_integrations_management_controller_list_data_integrations"] = { method = "GET", url = "https://api.workos.com/data-integrations", query = {"before", "after", "limit", "order", "ownership"} },
    ["workos.data_integrations_management_controller_update_data_integration"] = { method = "PUT", url = "https://api.workos.com/data-integrations/{slug}", path = {"slug"}, body = {"description", "enabled", "scopes", "credentials", "custom_provider"} },
    ["workos.data_integrations_management_controller_update_organization_data_integration"] = { method = "PUT", url = "https://api.workos.com/data-integrations/{slug}/organization", path = {"slug"}, body = {"description", "enabled", "scopes", "credentials", "custom_provider"} },
    ["workos.data_integrations_organization_controller_create_organization_data_installation"] = { method = "POST", url = "https://api.workos.com/organizations/{organization_id}/connected_accounts/{slug}", path = {"organization_id", "slug"}, body = {"refresh_token", "expires_at", "scopes", "state"} },
    ["workos.data_integrations_organization_controller_delete_organization_data_installation"] = { method = "DELETE", url = "https://api.workos.com/organizations/{organization_id}/connected_accounts/{slug}", path = {"organization_id", "slug"}, query = {"supports_multiple_connections", "connected_account_id"} },
    ["workos.data_integrations_organization_controller_get_organization_data_installation"] = { method = "GET", url = "https://api.workos.com/organizations/{organization_id}/connected_accounts/{slug}", path = {"organization_id", "slug"}, query = {"supports_multiple_connections", "connected_account_id"} },
    ["workos.data_integrations_organization_controller_get_organization_data_integrations"] = { method = "GET", url = "https://api.workos.com/organizations/{organization_id}/data_providers", path = {"organization_id"}, query = {"supports_multiple_connections"} },
    ["workos.data_integrations_organization_controller_update_organization_data_installation"] = { method = "PUT", url = "https://api.workos.com/organizations/{organization_id}/connected_accounts/{slug}", path = {"organization_id", "slug"}, query = {"supports_multiple_connections", "connected_account_id"}, body = {"refresh_token", "expires_at", "scopes", "state"} },
    ["workos.data_integrations_user_management_controller_create_user_data_installation"] = { method = "POST", url = "https://api.workos.com/user_management/users/{user_id}/connected_accounts/{slug}", path = {"user_id", "slug"}, query = {"organization_id"}, body = {"refresh_token", "expires_at", "scopes", "state"} },
    ["workos.data_integrations_user_management_controller_delete_user_data_installation"] = { method = "DELETE", url = "https://api.workos.com/user_management/users/{user_id}/connected_accounts/{slug}", path = {"user_id", "slug"}, query = {"organization_id", "supports_multiple_connections", "connected_account_id"} },
    ["workos.data_integrations_user_management_controller_get_user_data_installation"] = { method = "GET", url = "https://api.workos.com/user_management/users/{user_id}/connected_accounts/{slug}", path = {"user_id", "slug"}, query = {"organization_id", "supports_multiple_connections", "connected_account_id"} },
    ["workos.data_integrations_user_management_controller_get_user_data_integrations"] = { method = "GET", url = "https://api.workos.com/user_management/users/{user_id}/data_providers", path = {"user_id"}, query = {"organization_id", "supports_multiple_connections"} },
    ["workos.data_integrations_user_management_controller_update_user_data_installation"] = { method = "PUT", url = "https://api.workos.com/user_management/users/{user_id}/connected_accounts/{slug}", path = {"user_id", "slug"}, query = {"organization_id", "supports_multiple_connections", "connected_account_id"}, body = {"refresh_token", "expires_at", "scopes", "state"} },
    ["workos.directories_controller_delete_directory"] = { method = "DELETE", url = "https://api.workos.com/directories/{id}", path = {"id"} },
    ["workos.directories_controller_find"] = { method = "GET", url = "https://api.workos.com/directories/{id}", path = {"id"} },
    ["workos.directories_controller_list"] = { method = "GET", url = "https://api.workos.com/directories", query = {"before", "after", "limit", "order", "organization_id", "search", "domain"} },
    ["workos.directory_groups_controller_find"] = { method = "GET", url = "https://api.workos.com/directory_groups/{id}", path = {"id"} },
    ["workos.directory_groups_controller_list"] = { method = "GET", url = "https://api.workos.com/directory_groups", query = {"before", "after", "limit", "order", "directory", "user"} },
    ["workos.directory_users_controller_find"] = { method = "GET", url = "https://api.workos.com/directory_users/{id}", path = {"id"} },
    ["workos.directory_users_controller_list"] = { method = "GET", url = "https://api.workos.com/directory_users", query = {"before", "after", "limit", "order", "directory", "group", "idp_id", "email"} },
    ["workos.events_controller_list"] = { method = "GET", url = "https://api.workos.com/events", query = {"before", "after", "limit", "order", "events", "range_start", "range_end", "organization_id"} },
    ["workos.external_auth_controller_complete_login"] = { method = "POST", url = "https://api.workos.com/authkit/oauth2/complete", body = {"external_auth_id", "user", "user_consent_options"} },
    ["workos.feature_flags_controller_disable_flag"] = { method = "PUT", url = "https://api.workos.com/feature-flags/{slug}/disable", path = {"slug"} },
    ["workos.feature_flags_controller_enable_flag"] = { method = "PUT", url = "https://api.workos.com/feature-flags/{slug}/enable", path = {"slug"} },
    ["workos.feature_flags_controller_find_by_slug"] = { method = "GET", url = "https://api.workos.com/feature-flags/{slug}", path = {"slug"} },
    ["workos.feature_flags_controller_list"] = { method = "GET", url = "https://api.workos.com/feature-flags", query = {"before", "after", "limit", "order"} },
    ["workos.flag_targets_controller_create_target"] = { method = "POST", url = "https://api.workos.com/feature-flags/{slug}/targets/{resourceId}", path = {"resourceId", "slug"} },
    ["workos.flag_targets_controller_delete_target"] = { method = "DELETE", url = "https://api.workos.com/feature-flags/{slug}/targets/{resourceId}", path = {"resourceId", "slug"} },
    ["workos.group_memberships_controller_add_member"] = { method = "POST", url = "https://api.workos.com/organizations/{organizationId}/groups/{groupId}/organization-memberships", path = {"organizationId", "groupId"}, body = {"organization_membership_id"} },
    ["workos.group_memberships_controller_list_members"] = { method = "GET", url = "https://api.workos.com/organizations/{organizationId}/groups/{groupId}/organization-memberships", path = {"organizationId", "groupId"}, query = {"before", "after", "limit", "order"} },
    ["workos.group_memberships_controller_remove_member"] = { method = "DELETE", url = "https://api.workos.com/organizations/{organizationId}/groups/{groupId}/organization-memberships/{omId}", path = {"organizationId", "groupId", "omId"} },
    ["workos.groups_controller_create"] = { method = "POST", url = "https://api.workos.com/organizations/{organizationId}/groups", path = {"organizationId"}, body = {"name", "description"} },
    ["workos.groups_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/organizations/{organizationId}/groups/{groupId}", path = {"organizationId", "groupId"} },
    ["workos.groups_controller_get"] = { method = "GET", url = "https://api.workos.com/organizations/{organizationId}/groups/{groupId}", path = {"organizationId", "groupId"} },
    ["workos.groups_controller_list"] = { method = "GET", url = "https://api.workos.com/organizations/{organizationId}/groups", path = {"organizationId"}, query = {"before", "after", "limit", "order", "search"} },
    ["workos.groups_controller_update"] = { method = "PATCH", url = "https://api.workos.com/organizations/{organizationId}/groups/{groupId}", path = {"organizationId", "groupId"}, body = {"name", "description"} },
    ["workos.it_contacts_controller_create"] = { method = "POST", url = "https://api.workos.com/organizations/{organization_id}/it_contacts", path = {"organization_id"}, body = {"email"} },
    ["workos.it_contacts_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/organizations/{organization_id}/it_contacts/{contact_id}", path = {"organization_id", "contact_id"} },
    ["workos.it_contacts_controller_invite"] = { method = "POST", url = "https://api.workos.com/organizations/{organization_id}/it_contacts/{contact_id}/invite", path = {"organization_id", "contact_id"}, body = {"intents"} },
    ["workos.it_contacts_controller_list"] = { method = "GET", url = "https://api.workos.com/organizations/{organization_id}/it_contacts", path = {"organization_id"} },
    ["workos.it_contacts_controller_revoke"] = { method = "POST", url = "https://api.workos.com/organizations/{organization_id}/it_contacts/{contact_id}/revoke", path = {"organization_id", "contact_id"} },
    ["workos.jump_wire_web_data_vault_controller_create"] = { method = "POST", url = "https://api.workos.com/vault/v1/kv", body = {"key_context", "name", "value"} },
    ["workos.jump_wire_web_data_vault_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/vault/v1/kv/{id}", path = {"id"}, query = {"version_check"} },
    ["workos.jump_wire_web_data_vault_controller_describe"] = { method = "GET", url = "https://api.workos.com/vault/v1/kv/{id}/metadata", path = {"id"} },
    ["workos.jump_wire_web_data_vault_controller_index"] = { method = "GET", url = "https://api.workos.com/vault/v1/kv", query = {"limit", "before", "after", "order", "search", "updatedAfter"} },
    ["workos.jump_wire_web_data_vault_controller_show_by_id"] = { method = "GET", url = "https://api.workos.com/vault/v1/kv/{id}", path = {"id"} },
    ["workos.jump_wire_web_data_vault_controller_show_by_name"] = { method = "GET", url = "https://api.workos.com/vault/v1/kv/name/{name}", path = {"name"} },
    ["workos.jump_wire_web_data_vault_controller_update"] = { method = "PUT", url = "https://api.workos.com/vault/v1/kv/{id}", path = {"id"}, body = {"value", "version_check"} },
    ["workos.jump_wire_web_data_vault_controller_versions"] = { method = "GET", url = "https://api.workos.com/vault/v1/kv/{id}/versions", path = {"id"} },
    ["workos.jump_wire_web_key_controller_create_data_key"] = { method = "POST", url = "https://api.workos.com/vault/v1/keys/data-key", body = {"context"} },
    ["workos.jump_wire_web_key_controller_decrypt"] = { method = "POST", url = "https://api.workos.com/vault/v1/keys/decrypt", body = {"keys"} },
    ["workos.jump_wire_web_key_controller_rekey"] = { method = "POST", url = "https://api.workos.com/vault/v1/keys/rekey", body = {"context", "encrypted_keys"} },
    ["workos.jwt_templates_controller_get_jwt_template"] = { method = "GET", url = "https://api.workos.com/user_management/jwt_template" },
    ["workos.jwt_templates_controller_update_jwt_template"] = { method = "PUT", url = "https://api.workos.com/user_management/jwt_template", body = {"content"} },
    ["workos.organization_api_keys_controller_create"] = { method = "POST", url = "https://api.workos.com/organizations/{organizationId}/api_keys", path = {"organizationId"}, body = {"name", "permissions", "expires_at"} },
    ["workos.organization_api_keys_controller_list"] = { method = "GET", url = "https://api.workos.com/organizations/{organizationId}/api_keys", path = {"organizationId"}, query = {"before", "after", "limit", "order"} },
    ["workos.organization_authorized_applications_controller_list"] = { method = "GET", url = "https://api.workos.com/organizations/{organization_id}/authorized_applications", path = {"organization_id"}, query = {"before", "after", "limit", "order"} },
    ["workos.organization_domains_controller_create"] = { method = "POST", url = "https://api.workos.com/organization_domains", body = {"domain", "organization_id"} },
    ["workos.organization_domains_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/organization_domains/{id}", path = {"id"} },
    ["workos.organization_domains_controller_get"] = { method = "GET", url = "https://api.workos.com/organization_domains/{id}", path = {"id"} },
    ["workos.organization_domains_controller_verify"] = { method = "POST", url = "https://api.workos.com/organization_domains/{id}/verify", path = {"id"} },
    ["workos.organization_feature_flags_controller_list"] = { method = "GET", url = "https://api.workos.com/organizations/{organizationId}/feature-flags", path = {"organizationId"}, query = {"before", "after", "limit", "order"} },
    ["workos.organization_membership_groups_controller_list_groups"] = { method = "GET", url = "https://api.workos.com/user_management/organization_memberships/{omId}/groups", path = {"omId"}, query = {"before", "after", "limit", "order"} },
    ["workos.organizations_controller_create"] = { method = "POST", url = "https://api.workos.com/organizations", body = {"name", "allow_profiles_outside_organization", "domains", "domain_data", "metadata", "external_id"} },
    ["workos.organizations_controller_delete_organization"] = { method = "DELETE", url = "https://api.workos.com/organizations/{id}", path = {"id"} },
    ["workos.organizations_controller_find"] = { method = "GET", url = "https://api.workos.com/organizations/{id}", path = {"id"} },
    ["workos.organizations_controller_get_audit_log_configuration"] = { method = "GET", url = "https://api.workos.com/organizations/{id}/audit_log_configuration", path = {"id"} },
    ["workos.organizations_controller_get_by_external_id"] = { method = "GET", url = "https://api.workos.com/organizations/external_id/{external_id}", path = {"external_id"} },
    ["workos.organizations_controller_list"] = { method = "GET", url = "https://api.workos.com/organizations", query = {"before", "after", "limit", "order", "domains", "search"} },
    ["workos.organizations_controller_update_organization"] = { method = "PUT", url = "https://api.workos.com/organizations/{id}", path = {"id"}, body = {"name", "allow_profiles_outside_organization", "domains", "domain_data", "stripe_customer_id", "metadata", "external_id"} },
    ["workos.portal_sessions_controller_create"] = { method = "POST", url = "https://api.workos.com/portal/generate_link", body = {"return_url", "success_url", "organization", "intent", "it_contact_emails"} },
    ["workos.provider_controller_configure"] = { method = "PUT", url = "https://api.workos.com/organizations/{organizationId}/data_integration_configurations/{slug}", path = {"organizationId", "slug"}, body = {"enabled", "scopes", "client_id", "client_secret", "config"} },
    ["workos.provider_controller_list_for_organization"] = { method = "GET", url = "https://api.workos.com/organizations/{organizationId}/data_integration_configurations", path = {"organizationId"} },
    ["workos.public_radar_challenges_controller_get"] = { method = "GET", url = "https://api.workos.com/user_management/radar_challenges/{id}", path = {"id"} },
    ["workos.public_radar_challenges_controller_send_radar_sms_challenge"] = { method = "POST", url = "https://api.workos.com/user_management/radar_challenges", body = {"user_id", "pending_authentication_token", "phone_number", "ip_address", "user_agent"} },
    ["workos.radar_standalone_controller_assess"] = { method = "POST", url = "https://api.workos.com/radar/attempts", body = {"ip_address", "user_agent", "email", "auth_method", "action", "signals_id"} },
    ["workos.radar_standalone_controller_delete_radar_list_entry"] = { method = "DELETE", url = "https://api.workos.com/radar/lists/{type}/{action}", path = {"type", "action"}, body = {"entry"} },
    ["workos.radar_standalone_controller_update_radar_attempt"] = { method = "PUT", url = "https://api.workos.com/radar/attempts/{id}", path = {"id"}, body = {"challenge_status", "attempt_status"} },
    ["workos.radar_standalone_controller_update_radar_list"] = { method = "POST", url = "https://api.workos.com/radar/lists/{type}/{action}", path = {"type", "action"}, body = {"entry"} },
    ["workos.redirect_uris_controller_create"] = { method = "POST", url = "https://api.workos.com/user_management/redirect_uris", body = {"uri"} },
    ["workos.redirect_uris_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/user_management/redirect_uris/{id}", path = {"id"} },
    ["workos.redirect_uris_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/redirect_uris", query = {"before", "after", "limit", "order"} },
    ["workos.saml_idp_signing_certificates_controller_create"] = { method = "POST", url = "https://api.workos.com/connections/{connectionId}/saml_idp_signing_certs", path = {"connectionId"}, body = {"value"} },
    ["workos.saml_idp_signing_certificates_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/connections/{connectionId}/saml_idp_signing_certs/{certificateId}", path = {"connectionId", "certificateId"} },
    ["workos.saml_idp_signing_certificates_controller_list"] = { method = "GET", url = "https://api.workos.com/connections/{connectionId}/saml_idp_signing_certs", path = {"connectionId"} },
    ["workos.saml_sp_encryption_certificates_controller_create"] = { method = "POST", url = "https://api.workos.com/connections/{connectionId}/saml_sp_encryption_certs", path = {"connectionId"} },
    ["workos.saml_sp_encryption_certificates_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/connections/{connectionId}/saml_sp_encryption_certs/{certificateId}", path = {"connectionId", "certificateId"} },
    ["workos.saml_sp_encryption_certificates_controller_list"] = { method = "GET", url = "https://api.workos.com/connections/{connectionId}/saml_sp_encryption_certs", path = {"connectionId"} },
    ["workos.saml_sp_signing_certificates_controller_create"] = { method = "POST", url = "https://api.workos.com/connections/{connectionId}/saml_sp_signing_cert", path = {"connectionId"} },
    ["workos.saml_sp_signing_certificates_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/connections/{connectionId}/saml_sp_signing_cert/{certificateId}", path = {"connectionId", "certificateId"} },
    ["workos.saml_sp_signing_certificates_controller_get"] = { method = "GET", url = "https://api.workos.com/connections/{connectionId}/saml_sp_signing_cert", path = {"connectionId"} },
    ["workos.sso_controller_authorize"] = { method = "GET", url = "https://api.workos.com/sso/authorize", query = {"provider_scopes", "provider_query_params", "client_id", "domain", "provider", "redirect_uri", "response_type", "state", "connection", "organization", "domain_hint", "login_hint", "nonce", "prompt"} },
    ["workos.sso_controller_get_profile"] = { method = "GET", url = "https://api.workos.com/sso/profile" },
    ["workos.sso_controller_json_web_key_set"] = { method = "GET", url = "https://api.workos.com/sso/jwks/{clientId}", path = {"clientId"} },
    ["workos.sso_controller_logout"] = { method = "GET", url = "https://api.workos.com/sso/logout" },
    ["workos.sso_controller_logout_authorize"] = { method = "POST", url = "https://api.workos.com/sso/logout/authorize", body = {"profile_id"} },
    ["workos.sso_controller_token"] = { method = "POST", url = "https://api.workos.com/sso/token", query = {"client_id", "client_secret", "code", "grant_type"}, body = {"client_id", "client_secret", "code", "grant_type", "subject_token", "subject_token_type", "organization_id"} },
    ["workos.teams_controller_create_team"] = { method = "POST", url = "https://api.workos.com/platform/teams", body = {"admin_email", "name"} },
    ["workos.teams_controller_get_team"] = { method = "GET", url = "https://api.workos.com/platform/teams/{team_id}", path = {"team_id"} },
    ["workos.user_api_keys_controller_create"] = { method = "POST", url = "https://api.workos.com/user_management/users/{userId}/api_keys", path = {"userId"}, body = {"name", "organization_id", "permissions", "expires_at"} },
    ["workos.user_api_keys_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/users/{userId}/api_keys", path = {"userId"}, query = {"before", "after", "limit", "order", "organization_id"} },
    ["workos.userland_magic_auth_controller_get"] = { method = "GET", url = "https://api.workos.com/user_management/magic_auth/{id}", path = {"id"} },
    ["workos.userland_magic_auth_controller_send_magic_auth_code_and_return"] = { method = "POST", url = "https://api.workos.com/user_management/magic_auth", body = {"email", "invitation_token", "ip_address", "user_agent", "radar_auth_attempt_id", "signals_id"} },
    ["workos.userland_sessions_controller_authenticate_0"] = { method = "POST", url = "https://api.workos.com/user_management/authenticate" },
    ["workos.userland_sessions_controller_logout"] = { method = "GET", url = "https://api.workos.com/user_management/sessions/logout", query = {"session_id", "return_to"} },
    ["workos.userland_sessions_controller_revoke_session"] = { method = "POST", url = "https://api.workos.com/user_management/sessions/revoke", body = {"session_id"} },
    ["workos.userland_sso_controller_authorize"] = { method = "GET", url = "https://api.workos.com/user_management/authorize", query = {"code_challenge_method", "code_challenge", "domain_hint", "connection_id", "provider_query_params", "provider_scopes", "invitation_token", "max_age", "screen_hint", "login_hint", "provider", "prompt", "state", "organization_id", "response_type", "redirect_uri", "client_id"} },
    ["workos.userland_sso_controller_device_authorization"] = { method = "POST", url = "https://api.workos.com/user_management/authorize/device", body = {"client_id"} },
    ["workos.userland_user_authentication_factors_controller_create_0"] = { method = "POST", url = "https://api.workos.com/user_management/users/{userlandUserId}/auth_factors", path = {"userlandUserId"}, body = {"type", "totp_issuer", "totp_user", "totp_secret"} },
    ["workos.userland_user_authentication_factors_controller_list_0"] = { method = "GET", url = "https://api.workos.com/user_management/users/{userlandUserId}/auth_factors", path = {"userlandUserId"}, query = {"before", "after", "limit", "order"} },
    ["workos.userland_user_feature_flags_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/users/{userId}/feature-flags", path = {"userId"}, query = {"before", "after", "limit", "order"} },
    ["workos.userland_user_identities_controller_get"] = { method = "GET", url = "https://api.workos.com/user_management/users/{id}/identities", path = {"id"} },
    ["workos.userland_user_invites_controller_accept"] = { method = "POST", url = "https://api.workos.com/user_management/invitations/{id}/accept", path = {"id"} },
    ["workos.userland_user_invites_controller_create"] = { method = "POST", url = "https://api.workos.com/user_management/invitations", body = {"email", "organization_id", "role_slug", "expires_in_days", "inviter_user_id", "locale"} },
    ["workos.userland_user_invites_controller_get"] = { method = "GET", url = "https://api.workos.com/user_management/invitations/{id}", path = {"id"} },
    ["workos.userland_user_invites_controller_get_by_token"] = { method = "GET", url = "https://api.workos.com/user_management/invitations/by_token/{token}" },
    ["workos.userland_user_invites_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/invitations", query = {"before", "after", "limit", "order", "organization_id", "email"} },
    ["workos.userland_user_invites_controller_resend"] = { method = "POST", url = "https://api.workos.com/user_management/invitations/{id}/resend", path = {"id"}, body = {"locale"} },
    ["workos.userland_user_invites_controller_revoke"] = { method = "POST", url = "https://api.workos.com/user_management/invitations/{id}/revoke", path = {"id"} },
    ["workos.userland_user_organization_memberships_controller_create"] = { method = "POST", url = "https://api.workos.com/user_management/organization_memberships", body = {"user_id", "organization_id"} },
    ["workos.userland_user_organization_memberships_controller_deactivate"] = { method = "PUT", url = "https://api.workos.com/user_management/organization_memberships/{id}/deactivate", path = {"id"} },
    ["workos.userland_user_organization_memberships_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/user_management/organization_memberships/{id}", path = {"id"} },
    ["workos.userland_user_organization_memberships_controller_get"] = { method = "GET", url = "https://api.workos.com/user_management/organization_memberships/{id}", path = {"id"} },
    ["workos.userland_user_organization_memberships_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/organization_memberships", query = {"before", "after", "limit", "order", "organization_id", "statuses", "user_id"} },
    ["workos.userland_user_organization_memberships_controller_reactivate"] = { method = "PUT", url = "https://api.workos.com/user_management/organization_memberships/{id}/reactivate", path = {"id"} },
    ["workos.userland_user_organization_memberships_controller_update"] = { method = "PUT", url = "https://api.workos.com/user_management/organization_memberships/{id}", path = {"id"} },
    ["workos.userland_user_sessions_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/users/{id}/sessions", path = {"id"}, query = {"before", "after", "limit", "order"} },
    ["workos.userland_users_controller_confirm_email_change"] = { method = "POST", url = "https://api.workos.com/user_management/users/{id}/email_change/confirm", path = {"id"}, body = {"code"} },
    ["workos.userland_users_controller_create_0"] = { method = "POST", url = "https://api.workos.com/user_management/users", body = {"email", "first_name", "last_name", "name", "email_verified", "metadata", "external_id", "ip_address", "user_agent", "signals_id"} },
    ["workos.userland_users_controller_create_password_reset_token"] = { method = "POST", url = "https://api.workos.com/user_management/password_reset", body = {"email"} },
    ["workos.userland_users_controller_delete_0"] = { method = "DELETE", url = "https://api.workos.com/user_management/users/{id}", path = {"id"} },
    ["workos.userland_users_controller_email_verification_0"] = { method = "POST", url = "https://api.workos.com/user_management/users/{id}/email_verification/confirm", path = {"id"}, body = {"code"} },
    ["workos.userland_users_controller_get_0"] = { method = "GET", url = "https://api.workos.com/user_management/users/{id}", path = {"id"} },
    ["workos.userland_users_controller_get_by_external_id"] = { method = "GET", url = "https://api.workos.com/user_management/users/external_id/{external_id}", path = {"external_id"} },
    ["workos.userland_users_controller_get_email_verification"] = { method = "GET", url = "https://api.workos.com/user_management/email_verification/{id}", path = {"id"} },
    ["workos.userland_users_controller_get_password_reset"] = { method = "GET", url = "https://api.workos.com/user_management/password_reset/{id}", path = {"id"} },
    ["workos.userland_users_controller_list_0"] = { method = "GET", url = "https://api.workos.com/user_management/users", query = {"before", "after", "limit", "order", "organization", "organization_id", "email"} },
    ["workos.userland_users_controller_reset_password_0"] = { method = "POST", url = "https://api.workos.com/user_management/password_reset/confirm", body = {"new_password"} },
    ["workos.userland_users_controller_send_email_change"] = { method = "POST", url = "https://api.workos.com/user_management/users/{id}/email_change/send", path = {"id"}, body = {"new_email"} },
    ["workos.userland_users_controller_send_verification_email_0"] = { method = "POST", url = "https://api.workos.com/user_management/users/{id}/email_verification/send", path = {"id"} },
    ["workos.userland_users_controller_update_0"] = { method = "PUT", url = "https://api.workos.com/user_management/users/{id}", path = {"id"}, body = {"email", "first_name", "last_name", "name", "email_verified", "metadata", "external_id", "locale"} },
    ["workos.waitlist_entries_controller_approve"] = { method = "POST", url = "https://api.workos.com/user_management/waitlist_entries/{id}/approve", path = {"id"} },
    ["workos.waitlist_entries_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/user_management/waitlist_entries/{id}", path = {"id"} },
    ["workos.waitlist_entries_controller_deny"] = { method = "POST", url = "https://api.workos.com/user_management/waitlist_entries/{id}/deny", path = {"id"} },
    ["workos.waitlists_controller_create_entry"] = { method = "POST", url = "https://api.workos.com/user_management/waitlists/{id}/entries", path = {"id"}, body = {"email", "additional_fields", "send_confirmation_email"} },
    ["workos.waitlists_controller_find"] = { method = "GET", url = "https://api.workos.com/user_management/waitlists/{id}", path = {"id"} },
    ["workos.waitlists_controller_list"] = { method = "GET", url = "https://api.workos.com/user_management/waitlists" },
    ["workos.waitlists_controller_list_entries"] = { method = "GET", url = "https://api.workos.com/user_management/waitlists/{id}/entries", path = {"id"}, query = {"before", "after", "limit", "order", "state", "email"} },
    ["workos.webhook_endpoints_controller_create"] = { method = "POST", url = "https://api.workos.com/webhook_endpoints", body = {"endpoint_url", "events"} },
    ["workos.webhook_endpoints_controller_delete"] = { method = "DELETE", url = "https://api.workos.com/webhook_endpoints/{id}", path = {"id"} },
    ["workos.webhook_endpoints_controller_list"] = { method = "GET", url = "https://api.workos.com/webhook_endpoints", query = {"before", "after", "limit", "order"} },
    ["workos.webhook_endpoints_controller_update"] = { method = "PATCH", url = "https://api.workos.com/webhook_endpoints/{id}", path = {"id"}, body = {"endpoint_url", "status", "events"} },
    ["workos.widgets_public_controller_issue_widget_session_token"] = { method = "POST", url = "https://api.workos.com/widgets/token", body = {"organization_id", "user_id", "scopes"} },
  },
}
