-- Azure Blob Storage — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/windows.net/graphrbac/1.6/openapi.json
-- APIs.guru's mirror, matched on windows.net. A mirror lags the vendor.
-- 56 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "azure-blob-storage",
  name = "Azure Blob Storage",
  base = "https://{accountName}.blob.core.windows.net",
  docs = "https://nango.dev/docs/integrations/all/azure-blob-storage",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "AZURE_BLOB_STORAGE_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = { ["accountName"] = "AZURE_BLOB_STORAGE_ACCOUNTNAME" },
  headers = {},
  operations = {
    ["azure-blob-storage.applications_add_owner"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}/$links/owners", path = {"applicationObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.applications_create"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications", path = {"tenantID"}, query = {"api-version"}, body = {"displayName", "identifierUris"} },
    ["azure-blob-storage.applications_delete"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}", path = {"applicationObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.applications_get"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}", path = {"applicationObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.applications_get_service_principals_id_by_app_id"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipalsByAppId/{applicationID}/objectId", path = {"tenantID", "applicationID"}, query = {"api-version"} },
    ["azure-blob-storage.applications_list"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications", path = {"tenantID"}, query = {"$filter", "api-version"} },
    ["azure-blob-storage.applications_list_key_credentials"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}/keyCredentials", path = {"applicationObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.applications_list_owners"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}/owners", path = {"applicationObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.applications_list_password_credentials"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}/passwordCredentials", path = {"applicationObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.applications_patch"] = { method = "PATCH", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}", path = {"applicationObjectId", "tenantID"}, query = {"api-version"}, body = {"displayName", "identifierUris"} },
    ["azure-blob-storage.applications_remove_owner"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}/$links/owners/{ownerObjectId}", path = {"applicationObjectId", "ownerObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.applications_update_key_credentials"] = { method = "PATCH", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}/keyCredentials", path = {"applicationObjectId", "tenantID"}, query = {"api-version"}, body = {"value"} },
    ["azure-blob-storage.applications_update_password_credentials"] = { method = "PATCH", url = "https://{accountName}.blob.core.windows.net/{tenantID}/applications/{applicationObjectId}/passwordCredentials", path = {"applicationObjectId", "tenantID"}, query = {"api-version"}, body = {"value"} },
    ["azure-blob-storage.deleted_applications_hard_delete"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/deletedApplications/{applicationObjectId}", path = {"applicationObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.deleted_applications_list"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/deletedApplications", path = {"tenantID"}, query = {"$filter", "api-version"} },
    ["azure-blob-storage.deleted_applications_restore"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/deletedApplications/{objectId}/restore", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.domains_get"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/domains/{domainName}", path = {"domainName", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.domains_list"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/domains", path = {"tenantID"}, query = {"$filter", "api-version"} },
    ["azure-blob-storage.groups_add_member"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{groupObjectId}/$links/members", path = {"groupObjectId", "tenantID"}, query = {"api-version"}, body = {"url"} },
    ["azure-blob-storage.groups_add_owner"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{objectId}/$links/owners", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.groups_create"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups", path = {"tenantID"}, query = {"api-version"}, body = {"displayName", "mailEnabled", "mailNickname", "securityEnabled"} },
    ["azure-blob-storage.groups_delete"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{objectId}", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.groups_get"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{objectId}", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.groups_get_group_members"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{objectId}/members", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.groups_get_member_groups"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{objectId}/getMemberGroups", path = {"objectId", "tenantID"}, query = {"api-version"}, body = {"securityEnabledOnly"} },
    ["azure-blob-storage.groups_is_member_of"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/isMemberOf", path = {"tenantID"}, query = {"api-version"}, body = {"groupId", "memberId"} },
    ["azure-blob-storage.groups_list"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups", path = {"tenantID"}, query = {"$filter", "api-version"} },
    ["azure-blob-storage.groups_list_owners"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{objectId}/owners", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.groups_remove_member"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{groupObjectId}/$links/members/{memberObjectId}", path = {"groupObjectId", "memberObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.groups_remove_owner"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/groups/{objectId}/$links/owners/{ownerObjectId}", path = {"objectId", "ownerObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.oauth2_permission_grant_create"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/oauth2PermissionGrants", path = {"tenantID"}, query = {"api-version"}, body = {"clientId", "consentType", "expiryTime", "objectId", "odata.type", "principalId", "resourceId", "scope", "startTime"} },
    ["azure-blob-storage.oauth2_permission_grant_delete"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/oauth2PermissionGrants/{objectId}", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.oauth2_permission_grant_list"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/oauth2PermissionGrants", path = {"tenantID"}, query = {"$filter", "api-version"} },
    ["azure-blob-storage.objects_get_objects_by_object_ids"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/getObjectsByObjectIds", path = {"tenantID"}, query = {"api-version"}, body = {"includeDirectoryObjectReferences", "objectIds", "types"} },
    ["azure-blob-storage.service_principals_add_owner"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/$links/owners", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_create"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals", path = {"tenantID"}, query = {"api-version"}, body = {"appId"} },
    ["azure-blob-storage.service_principals_delete"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_get"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_list"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals", path = {"tenantID"}, query = {"$filter", "api-version"} },
    ["azure-blob-storage.service_principals_list_app_role_assigned_to"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/appRoleAssignedTo", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_list_app_role_assignments"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/appRoleAssignments", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_list_key_credentials"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/keyCredentials", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_list_owners"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/owners", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_list_password_credentials"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/passwordCredentials", path = {"objectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_remove_owner"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/$links/owners/{ownerObjectId}", path = {"objectId", "ownerObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.service_principals_update"] = { method = "PATCH", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}", path = {"objectId", "tenantID"}, query = {"api-version"}, body = {"accountEnabled", "appRoleAssignmentRequired", "keyCredentials", "passwordCredentials", "servicePrincipalType", "tags"} },
    ["azure-blob-storage.service_principals_update_key_credentials"] = { method = "PATCH", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/keyCredentials", path = {"objectId", "tenantID"}, query = {"api-version"}, body = {"value"} },
    ["azure-blob-storage.service_principals_update_password_credentials"] = { method = "PATCH", url = "https://{accountName}.blob.core.windows.net/{tenantID}/servicePrincipals/{objectId}/passwordCredentials", path = {"objectId", "tenantID"}, query = {"api-version"}, body = {"value"} },
    ["azure-blob-storage.signed_in_user_get"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/me", path = {"tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.signed_in_user_list_owned_objects"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/me/ownedObjects", path = {"tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.users_create"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/users", path = {"tenantID"}, query = {"api-version"}, body = {"accountEnabled", "displayName", "mail", "mailNickname", "passwordProfile", "userPrincipalName"} },
    ["azure-blob-storage.users_delete"] = { method = "DELETE", url = "https://{accountName}.blob.core.windows.net/{tenantID}/users/{upnOrObjectId}", path = {"upnOrObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.users_get"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/users/{upnOrObjectId}", path = {"upnOrObjectId", "tenantID"}, query = {"api-version"} },
    ["azure-blob-storage.users_get_member_groups"] = { method = "POST", url = "https://{accountName}.blob.core.windows.net/{tenantID}/users/{objectId}/getMemberGroups", path = {"objectId", "tenantID"}, query = {"api-version"}, body = {"securityEnabledOnly"} },
    ["azure-blob-storage.users_list"] = { method = "GET", url = "https://{accountName}.blob.core.windows.net/{tenantID}/users", path = {"tenantID"}, query = {"$filter", "$expand", "$top", "api-version"} },
    ["azure-blob-storage.users_update"] = { method = "PATCH", url = "https://{accountName}.blob.core.windows.net/{tenantID}/users/{upnOrObjectId}", path = {"upnOrObjectId", "tenantID"}, query = {"api-version"}, body = {"accountEnabled", "displayName", "mail", "mailNickname", "passwordProfile", "userPrincipalName"} },
  },
}
