-- Squareup — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/squareup.com/2.0/openapi.json
-- APIs.guru's mirror, matched on squareup.com. A mirror lags the vendor.
-- 200 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "squareup",
  name = "Squareup",
  base = "https://connect.squareup.com",
  docs = "https://nango.dev/docs/api-integrations/squareup",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "SQUAREUP_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["squareup.accept_dispute"] = { method = "POST", url = "https://connect.squareup.com/v2/disputes/{dispute_id}/accept", path = {"dispute_id"} },
    ["squareup.accumulate_loyalty_points"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/accounts/{account_id}/accumulate", path = {"account_id"}, body = {"accumulate_points", "idempotency_key", "location_id"} },
    ["squareup.add_group_to_customer"] = { method = "PUT", url = "https://connect.squareup.com/v2/customers/{customer_id}/groups/{group_id}", path = {"customer_id", "group_id"} },
    ["squareup.adjust_loyalty_points"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/accounts/{account_id}/adjust", path = {"account_id"}, body = {"adjust_points", "idempotency_key"} },
    ["squareup.batch_change_inventory"] = { method = "POST", url = "https://connect.squareup.com/v2/inventory/changes/batch-create" },
    ["squareup.batch_delete_catalog_objects"] = { method = "POST", url = "https://connect.squareup.com/v2/catalog/batch-delete", body = {"object_ids"} },
    ["squareup.batch_retrieve_catalog_objects"] = { method = "POST", url = "https://connect.squareup.com/v2/catalog/batch-retrieve", body = {"catalog_version", "include_related_objects", "object_ids"} },
    ["squareup.batch_retrieve_inventory_changes"] = { method = "POST", url = "https://connect.squareup.com/v2/inventory/changes/batch-retrieve" },
    ["squareup.batch_retrieve_inventory_counts"] = { method = "POST", url = "https://connect.squareup.com/v2/inventory/counts/batch-retrieve" },
    ["squareup.batch_retrieve_orders"] = { method = "POST", url = "https://connect.squareup.com/v2/orders/batch-retrieve", body = {"location_id", "order_ids"} },
    ["squareup.batch_upsert_catalog_objects"] = { method = "POST", url = "https://connect.squareup.com/v2/catalog/batch-upsert", body = {"batches", "idempotency_key"} },
    ["squareup.bulk_create_team_members"] = { method = "POST", url = "https://connect.squareup.com/v2/team-members/bulk-create", body = {"team_members"} },
    ["squareup.bulk_update_team_members"] = { method = "POST", url = "https://connect.squareup.com/v2/team-members/bulk-update", body = {"team_members"} },
    ["squareup.calculate_loyalty_points"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/programs/{program_id}/calculate", path = {"program_id"}, body = {"order_id", "transaction_amount_money"} },
    ["squareup.calculate_order"] = { method = "POST", url = "https://connect.squareup.com/v2/orders/calculate", body = {"order", "proposed_rewards"} },
    ["squareup.cancel_booking"] = { method = "POST", url = "https://connect.squareup.com/v2/bookings/{booking_id}/cancel", path = {"booking_id"}, body = {"booking_version", "idempotency_key"} },
    ["squareup.cancel_invoice"] = { method = "POST", url = "https://connect.squareup.com/v2/invoices/{invoice_id}/cancel", path = {"invoice_id"}, body = {"version"} },
    ["squareup.cancel_payment"] = { method = "POST", url = "https://connect.squareup.com/v2/payments/{payment_id}/cancel", path = {"payment_id"} },
    ["squareup.cancel_payment_by_idempotency_key"] = { method = "POST", url = "https://connect.squareup.com/v2/payments/cancel", body = {"idempotency_key"} },
    ["squareup.cancel_subscription"] = { method = "POST", url = "https://connect.squareup.com/v2/subscriptions/{subscription_id}/cancel", path = {"subscription_id"} },
    ["squareup.cancel_terminal_checkout"] = { method = "POST", url = "https://connect.squareup.com/v2/terminals/checkouts/{checkout_id}/cancel", path = {"checkout_id"} },
    ["squareup.cancel_terminal_refund"] = { method = "POST", url = "https://connect.squareup.com/v2/terminals/refunds/{terminal_refund_id}/cancel", path = {"terminal_refund_id"} },
    ["squareup.capture_transaction"] = { method = "POST", url = "https://connect.squareup.com/v2/locations/{location_id}/transactions/{transaction_id}/capture", path = {"location_id", "transaction_id"} },
    ["squareup.catalog_info"] = { method = "GET", url = "https://connect.squareup.com/v2/catalog/info" },
    ["squareup.charge"] = { method = "POST", url = "https://connect.squareup.com/v2/locations/{location_id}/transactions", path = {"location_id"}, body = {"additional_recipients", "amount_money", "billing_address", "buyer_email_address", "card_nonce", "customer_card_id", "customer_id", "delay_capture", "idempotency_key", "note", "order_id", "reference_id", "shipping_address", "verification_token"} },
    ["squareup.complete_payment"] = { method = "POST", url = "https://connect.squareup.com/v2/payments/{payment_id}/complete", path = {"payment_id"} },
    ["squareup.create_booking"] = { method = "POST", url = "https://connect.squareup.com/v2/bookings", body = {"booking", "idempotency_key"} },
    ["squareup.create_break_type"] = { method = "POST", url = "https://connect.squareup.com/v2/labor/break-types", body = {"break_type", "idempotency_key"} },
    ["squareup.create_card"] = { method = "POST", url = "https://connect.squareup.com/v2/cards", body = {"card", "idempotency_key", "source_id", "verification_token"} },
    ["squareup.create_checkout"] = { method = "POST", url = "https://connect.squareup.com/v2/locations/{location_id}/checkouts", path = {"location_id"}, body = {"additional_recipients", "ask_for_shipping_address", "idempotency_key", "merchant_support_email", "note", "order", "pre_populate_buyer_email", "pre_populate_shipping_address", "redirect_url"} },
    ["squareup.create_customer"] = { method = "POST", url = "https://connect.squareup.com/v2/customers", body = {"address", "birthday", "company_name", "email_address", "family_name", "given_name", "idempotency_key", "nickname", "note", "phone_number", "reference_id"} },
    ["squareup.create_customer_card"] = { method = "POST", url = "https://connect.squareup.com/v2/customers/{customer_id}/cards", path = {"customer_id"}, body = {"billing_address", "card_nonce", "cardholder_name", "verification_token"} },
    ["squareup.create_customer_group"] = { method = "POST", url = "https://connect.squareup.com/v2/customers/groups", body = {"group", "idempotency_key"} },
    ["squareup.create_device_code"] = { method = "POST", url = "https://connect.squareup.com/v2/devices/codes", body = {"device_code", "idempotency_key"} },
    ["squareup.create_dispute_evidence_text"] = { method = "POST", url = "https://connect.squareup.com/v2/disputes/{dispute_id}/evidence-text", path = {"dispute_id"}, body = {"evidence_text", "evidence_type", "idempotency_key"} },
    ["squareup.create_employee"] = { method = "POST", url = "https://connect.squareup.com/v1/me/employees" },
    ["squareup.create_employee_role"] = { method = "POST", url = "https://connect.squareup.com/v1/me/roles", body = {"created_at", "id", "is_owner", "name", "permissions", "updated_at"} },
    ["squareup.create_gift_card"] = { method = "POST", url = "https://connect.squareup.com/v2/gift-cards", body = {"gift_card", "idempotency_key", "location_id"} },
    ["squareup.create_gift_card_activity"] = { method = "POST", url = "https://connect.squareup.com/v2/gift-cards/activities", body = {"gift_card_activity", "idempotency_key"} },
    ["squareup.create_invoice"] = { method = "POST", url = "https://connect.squareup.com/v2/invoices", body = {"idempotency_key", "invoice"} },
    ["squareup.create_location"] = { method = "POST", url = "https://connect.squareup.com/v2/locations", body = {"location"} },
    ["squareup.create_loyalty_account"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/accounts", body = {"idempotency_key", "loyalty_account"} },
    ["squareup.create_loyalty_reward"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/rewards", body = {"idempotency_key", "reward"} },
    ["squareup.create_mobile_authorization_code"] = { method = "POST", url = "https://connect.squareup.com/mobile/authorization-code", body = {"location_id"} },
    ["squareup.create_order"] = { method = "POST", url = "https://connect.squareup.com/v2/orders", body = {"idempotency_key", "order"} },
    ["squareup.create_payment"] = { method = "POST", url = "https://connect.squareup.com/v2/payments", body = {"accept_partial_authorization", "amount_money", "app_fee_money", "autocomplete", "billing_address", "buyer_email_address", "cash_details", "customer_id", "delay_duration", "external_details", "idempotency_key", "location_id", "note", "order_id", "reference_id", "shipping_address", "source_id", "statement_description_identifier", "tip_money", "verification_token"} },
    ["squareup.create_refund"] = { method = "POST", url = "https://connect.squareup.com/v1/{location_id}/refunds", path = {"location_id"}, body = {"payment_id", "reason", "refunded_money", "request_idempotence_key", "type"} },
    ["squareup.create_shift"] = { method = "POST", url = "https://connect.squareup.com/v2/labor/shifts", body = {"idempotency_key", "shift"} },
    ["squareup.create_subscription"] = { method = "POST", url = "https://connect.squareup.com/v2/subscriptions", body = {"canceled_date", "card_id", "customer_id", "idempotency_key", "location_id", "plan_id", "price_override_money", "start_date", "tax_percentage", "timezone"} },
    ["squareup.create_team_member"] = { method = "POST", url = "https://connect.squareup.com/v2/team-members", body = {"idempotency_key", "team_member"} },
    ["squareup.create_terminal_checkout"] = { method = "POST", url = "https://connect.squareup.com/v2/terminals/checkouts", body = {"checkout", "idempotency_key"} },
    ["squareup.create_terminal_refund"] = { method = "POST", url = "https://connect.squareup.com/v2/terminals/refunds", body = {"idempotency_key", "refund"} },
    ["squareup.delete_break_type"] = { method = "DELETE", url = "https://connect.squareup.com/v2/labor/break-types/{id}", path = {"id"} },
    ["squareup.delete_catalog_object"] = { method = "DELETE", url = "https://connect.squareup.com/v2/catalog/object/{object_id}", path = {"object_id"} },
    ["squareup.delete_customer"] = { method = "DELETE", url = "https://connect.squareup.com/v2/customers/{customer_id}", path = {"customer_id"}, query = {"version"} },
    ["squareup.delete_customer_card"] = { method = "DELETE", url = "https://connect.squareup.com/v2/customers/{customer_id}/cards/{card_id}", path = {"customer_id", "card_id"} },
    ["squareup.delete_customer_group"] = { method = "DELETE", url = "https://connect.squareup.com/v2/customers/groups/{group_id}", path = {"group_id"} },
    ["squareup.delete_dispute_evidence"] = { method = "DELETE", url = "https://connect.squareup.com/v2/disputes/{dispute_id}/evidence/{evidence_id}", path = {"dispute_id", "evidence_id"} },
    ["squareup.delete_invoice"] = { method = "DELETE", url = "https://connect.squareup.com/v2/invoices/{invoice_id}", path = {"invoice_id"}, query = {"version"} },
    ["squareup.delete_loyalty_reward"] = { method = "DELETE", url = "https://connect.squareup.com/v2/loyalty/rewards/{reward_id}", path = {"reward_id"} },
    ["squareup.delete_shift"] = { method = "DELETE", url = "https://connect.squareup.com/v2/labor/shifts/{id}", path = {"id"} },
    ["squareup.delete_snippet"] = { method = "DELETE", url = "https://connect.squareup.com/v2/sites/{site_id}/snippet", path = {"site_id"} },
    ["squareup.deprecated_batch_change_inventory"] = { method = "POST", url = "https://connect.squareup.com/v2/inventory/batch-change" },
    ["squareup.deprecated_batch_retrieve_inventory_changes"] = { method = "POST", url = "https://connect.squareup.com/v2/inventory/batch-retrieve-changes" },
    ["squareup.deprecated_batch_retrieve_inventory_counts"] = { method = "POST", url = "https://connect.squareup.com/v2/inventory/batch-retrieve-counts" },
    ["squareup.deprecated_retrieve_inventory_adjustment"] = { method = "GET", url = "https://connect.squareup.com/v2/inventory/adjustment/{adjustment_id}", path = {"adjustment_id"} },
    ["squareup.deprecated_retrieve_inventory_physical_count"] = { method = "GET", url = "https://connect.squareup.com/v2/inventory/physical-count/{physical_count_id}", path = {"physical_count_id"} },
    ["squareup.disable_card"] = { method = "POST", url = "https://connect.squareup.com/v2/cards/{card_id}/disable", path = {"card_id"} },
    ["squareup.get_bank_account"] = { method = "GET", url = "https://connect.squareup.com/v2/bank-accounts/{bank_account_id}", path = {"bank_account_id"} },
    ["squareup.get_bank_account_by_v1_id"] = { method = "GET", url = "https://connect.squareup.com/v2/bank-accounts/by-v1-id/{v1_bank_account_id}", path = {"v1_bank_account_id"} },
    ["squareup.get_break_type"] = { method = "GET", url = "https://connect.squareup.com/v2/labor/break-types/{id}", path = {"id"} },
    ["squareup.get_device_code"] = { method = "GET", url = "https://connect.squareup.com/v2/devices/codes/{id}", path = {"id"} },
    ["squareup.get_employee_wage"] = { method = "GET", url = "https://connect.squareup.com/v2/labor/employee-wages/{id}", path = {"id"} },
    ["squareup.get_invoice"] = { method = "GET", url = "https://connect.squareup.com/v2/invoices/{invoice_id}", path = {"invoice_id"} },
    ["squareup.get_payment"] = { method = "GET", url = "https://connect.squareup.com/v2/payments/{payment_id}", path = {"payment_id"} },
    ["squareup.get_payment_refund"] = { method = "GET", url = "https://connect.squareup.com/v2/refunds/{refund_id}", path = {"refund_id"} },
    ["squareup.get_shift"] = { method = "GET", url = "https://connect.squareup.com/v2/labor/shifts/{id}", path = {"id"} },
    ["squareup.get_team_member_wage"] = { method = "GET", url = "https://connect.squareup.com/v2/labor/team-member-wages/{id}", path = {"id"} },
    ["squareup.get_terminal_checkout"] = { method = "GET", url = "https://connect.squareup.com/v2/terminals/checkouts/{checkout_id}", path = {"checkout_id"} },
    ["squareup.get_terminal_refund"] = { method = "GET", url = "https://connect.squareup.com/v2/terminals/refunds/{terminal_refund_id}", path = {"terminal_refund_id"} },
    ["squareup.get_v2_employees"] = { method = "GET", url = "https://connect.squareup.com/v2/employees", query = {"location_id", "status", "limit", "cursor"} },
    ["squareup.get_v2_employees_id"] = { method = "GET", url = "https://connect.squareup.com/v2/employees/{id}", path = {"id"} },
    ["squareup.get_v2_locations_location_id_refunds"] = { method = "GET", url = "https://connect.squareup.com/v2/locations/{location_id}/refunds", path = {"location_id"}, query = {"begin_time", "end_time", "sort_order", "cursor"} },
    ["squareup.get_v2_orders_order_id"] = { method = "GET", url = "https://connect.squareup.com/v2/orders/{order_id}", path = {"order_id"} },
    ["squareup.get_v2_payments"] = { method = "GET", url = "https://connect.squareup.com/v2/payments", query = {"begin_time", "end_time", "sort_order", "cursor", "location_id", "total", "last_4", "card_brand", "limit"} },
    ["squareup.link_customer_to_gift_card"] = { method = "POST", url = "https://connect.squareup.com/v2/gift-cards/{gift_card_id}/link-customer", path = {"gift_card_id"}, body = {"customer_id"} },
    ["squareup.list_bank_accounts"] = { method = "GET", url = "https://connect.squareup.com/v2/bank-accounts", query = {"cursor", "limit", "location_id"} },
    ["squareup.list_break_types"] = { method = "GET", url = "https://connect.squareup.com/v2/labor/break-types", query = {"location_id", "limit", "cursor"} },
    ["squareup.list_cards"] = { method = "GET", url = "https://connect.squareup.com/v2/cards", query = {"cursor", "customer_id", "include_disabled", "reference_id", "sort_order"} },
    ["squareup.list_cash_drawer_shift_events"] = { method = "GET", url = "https://connect.squareup.com/v2/cash-drawers/shifts/{shift_id}/events", path = {"shift_id"}, query = {"location_id", "limit", "cursor"} },
    ["squareup.list_cash_drawer_shifts"] = { method = "GET", url = "https://connect.squareup.com/v2/cash-drawers/shifts", query = {"location_id", "sort_order", "begin_time", "end_time", "limit", "cursor"} },
    ["squareup.list_catalog"] = { method = "GET", url = "https://connect.squareup.com/v2/catalog/list", query = {"cursor", "types", "catalog_version"} },
    ["squareup.list_customer_groups"] = { method = "GET", url = "https://connect.squareup.com/v2/customers/groups", query = {"cursor", "limit"} },
    ["squareup.list_customer_segments"] = { method = "GET", url = "https://connect.squareup.com/v2/customers/segments", query = {"cursor", "limit"} },
    ["squareup.list_customers"] = { method = "GET", url = "https://connect.squareup.com/v2/customers", query = {"cursor", "limit", "sort_field", "sort_order"} },
    ["squareup.list_device_codes"] = { method = "GET", url = "https://connect.squareup.com/v2/devices/codes", query = {"cursor", "location_id", "product_type", "status"} },
    ["squareup.list_dispute_evidence"] = { method = "GET", url = "https://connect.squareup.com/v2/disputes/{dispute_id}/evidence", path = {"dispute_id"}, query = {"cursor"} },
    ["squareup.list_disputes"] = { method = "GET", url = "https://connect.squareup.com/v2/disputes", query = {"cursor", "states", "location_id"} },
    ["squareup.list_employee_roles"] = { method = "GET", url = "https://connect.squareup.com/v1/me/roles", query = {"order", "limit", "batch_token"} },
    ["squareup.list_employee_wages"] = { method = "GET", url = "https://connect.squareup.com/v2/labor/employee-wages", query = {"employee_id", "limit", "cursor"} },
    ["squareup.list_employees"] = { method = "GET", url = "https://connect.squareup.com/v1/me/employees", query = {"order", "begin_updated_at", "end_updated_at", "begin_created_at", "end_created_at", "status", "external_id", "limit", "batch_token"} },
    ["squareup.list_gift_card_activities"] = { method = "GET", url = "https://connect.squareup.com/v2/gift-cards/activities", query = {"gift_card_id", "type", "location_id", "begin_time", "end_time", "limit", "cursor", "sort_order"} },
    ["squareup.list_gift_cards"] = { method = "GET", url = "https://connect.squareup.com/v2/gift-cards", query = {"type", "state", "limit", "cursor", "customer_id"} },
    ["squareup.list_invoices"] = { method = "GET", url = "https://connect.squareup.com/v2/invoices", query = {"location_id", "cursor", "limit"} },
    ["squareup.list_locations"] = { method = "GET", url = "https://connect.squareup.com/v2/locations" },
    ["squareup.list_loyalty_programs"] = { method = "GET", url = "https://connect.squareup.com/v2/loyalty/programs" },
    ["squareup.list_merchants"] = { method = "GET", url = "https://connect.squareup.com/v2/merchants", query = {"cursor"} },
    ["squareup.list_orders"] = { method = "GET", url = "https://connect.squareup.com/v1/{location_id}/orders", path = {"location_id"}, query = {"order", "limit", "batch_token"} },
    ["squareup.list_payment_refunds"] = { method = "GET", url = "https://connect.squareup.com/v2/refunds", query = {"begin_time", "end_time", "sort_order", "cursor", "location_id", "status", "source_type", "limit"} },
    ["squareup.list_payments"] = { method = "GET", url = "https://connect.squareup.com/v1/{location_id}/payments", path = {"location_id"}, query = {"order", "begin_time", "end_time", "limit", "batch_token", "include_partial"} },
    ["squareup.list_refunds"] = { method = "GET", url = "https://connect.squareup.com/v1/{location_id}/refunds", path = {"location_id"}, query = {"order", "begin_time", "end_time", "limit", "batch_token"} },
    ["squareup.list_settlements"] = { method = "GET", url = "https://connect.squareup.com/v1/{location_id}/settlements", path = {"location_id"}, query = {"order", "begin_time", "end_time", "limit", "status", "batch_token"} },
    ["squareup.list_sites"] = { method = "GET", url = "https://connect.squareup.com/v2/sites" },
    ["squareup.list_subscription_events"] = { method = "GET", url = "https://connect.squareup.com/v2/subscriptions/{subscription_id}/events", path = {"subscription_id"}, query = {"cursor", "limit"} },
    ["squareup.list_team_member_booking_profiles"] = { method = "GET", url = "https://connect.squareup.com/v2/bookings/team-member-booking-profiles", query = {"bookable_only", "limit", "cursor", "location_id"} },
    ["squareup.list_team_member_wages"] = { method = "GET", url = "https://connect.squareup.com/v2/labor/team-member-wages", query = {"team_member_id", "limit", "cursor"} },
    ["squareup.list_transactions"] = { method = "GET", url = "https://connect.squareup.com/v2/locations/{location_id}/transactions", path = {"location_id"}, query = {"begin_time", "end_time", "sort_order", "cursor"} },
    ["squareup.list_workweek_configs"] = { method = "GET", url = "https://connect.squareup.com/v2/labor/workweek-configs", query = {"limit", "cursor"} },
    ["squareup.obtain_token"] = { method = "POST", url = "https://connect.squareup.com/oauth2/token", body = {"client_id", "client_secret", "code", "grant_type", "migration_token", "redirect_uri", "refresh_token", "scopes", "short_lived"} },
    ["squareup.pay_order"] = { method = "POST", url = "https://connect.squareup.com/v2/orders/{order_id}/pay", path = {"order_id"}, body = {"idempotency_key", "order_version", "payment_ids"} },
    ["squareup.post_v2_locations_location_id_transactions_transaction_id_refund"] = { method = "POST", url = "https://connect.squareup.com/v2/locations/{location_id}/transactions/{transaction_id}/refund", path = {"location_id", "transaction_id"}, body = {"amount_money", "idempotency_key", "reason", "tender_id"} },
    ["squareup.publish_invoice"] = { method = "POST", url = "https://connect.squareup.com/v2/invoices/{invoice_id}/publish", path = {"invoice_id"}, body = {"idempotency_key", "version"} },
    ["squareup.put_v2_orders_order_id"] = { method = "PUT", url = "https://connect.squareup.com/v2/orders/{order_id}", path = {"order_id"}, body = {"fields_to_clear", "idempotency_key", "order"} },
    ["squareup.redeem_loyalty_reward"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/rewards/{reward_id}/redeem", path = {"reward_id"}, body = {"idempotency_key", "location_id"} },
    ["squareup.refund_payment"] = { method = "POST", url = "https://connect.squareup.com/v2/refunds", body = {"amount_money", "app_fee_money", "idempotency_key", "payment_id", "reason"} },
    ["squareup.register_domain"] = { method = "POST", url = "https://connect.squareup.com/v2/apple-pay/domains", body = {"domain_name"} },
    ["squareup.remove_group_from_customer"] = { method = "DELETE", url = "https://connect.squareup.com/v2/customers/{customer_id}/groups/{group_id}", path = {"customer_id", "group_id"} },
    ["squareup.renew_token"] = { method = "POST", url = "https://connect.squareup.com/oauth2/clients/{client_id}/access-token/renew", path = {"client_id"} },
    ["squareup.resume_subscription"] = { method = "POST", url = "https://connect.squareup.com/v2/subscriptions/{subscription_id}/resume", path = {"subscription_id"} },
    ["squareup.retrieve_booking"] = { method = "GET", url = "https://connect.squareup.com/v2/bookings/{booking_id}", path = {"booking_id"} },
    ["squareup.retrieve_business_booking_profile"] = { method = "GET", url = "https://connect.squareup.com/v2/bookings/business-booking-profile" },
    ["squareup.retrieve_card"] = { method = "GET", url = "https://connect.squareup.com/v2/cards/{card_id}", path = {"card_id"} },
    ["squareup.retrieve_cash_drawer_shift"] = { method = "GET", url = "https://connect.squareup.com/v2/cash-drawers/shifts/{shift_id}", path = {"shift_id"}, query = {"location_id"} },
    ["squareup.retrieve_catalog_object"] = { method = "GET", url = "https://connect.squareup.com/v2/catalog/object/{object_id}", path = {"object_id"}, query = {"include_related_objects", "catalog_version"} },
    ["squareup.retrieve_customer"] = { method = "GET", url = "https://connect.squareup.com/v2/customers/{customer_id}", path = {"customer_id"} },
    ["squareup.retrieve_customer_group"] = { method = "GET", url = "https://connect.squareup.com/v2/customers/groups/{group_id}", path = {"group_id"} },
    ["squareup.retrieve_customer_segment"] = { method = "GET", url = "https://connect.squareup.com/v2/customers/segments/{segment_id}", path = {"segment_id"} },
    ["squareup.retrieve_dispute"] = { method = "GET", url = "https://connect.squareup.com/v2/disputes/{dispute_id}", path = {"dispute_id"} },
    ["squareup.retrieve_dispute_evidence"] = { method = "GET", url = "https://connect.squareup.com/v2/disputes/{dispute_id}/evidence/{evidence_id}", path = {"dispute_id", "evidence_id"} },
    ["squareup.retrieve_employee"] = { method = "GET", url = "https://connect.squareup.com/v1/me/employees/{employee_id}", path = {"employee_id"} },
    ["squareup.retrieve_employee_role"] = { method = "GET", url = "https://connect.squareup.com/v1/me/roles/{role_id}", path = {"role_id"} },
    ["squareup.retrieve_gift_card"] = { method = "GET", url = "https://connect.squareup.com/v2/gift-cards/{id}", path = {"id"} },
    ["squareup.retrieve_gift_card_from_gan"] = { method = "POST", url = "https://connect.squareup.com/v2/gift-cards/from-gan", body = {"gan"} },
    ["squareup.retrieve_gift_card_from_nonce"] = { method = "POST", url = "https://connect.squareup.com/v2/gift-cards/from-nonce", body = {"nonce"} },
    ["squareup.retrieve_inventory_adjustment"] = { method = "GET", url = "https://connect.squareup.com/v2/inventory/adjustments/{adjustment_id}", path = {"adjustment_id"} },
    ["squareup.retrieve_inventory_changes"] = { method = "GET", url = "https://connect.squareup.com/v2/inventory/{catalog_object_id}/changes", path = {"catalog_object_id"}, query = {"location_ids", "cursor"} },
    ["squareup.retrieve_inventory_count"] = { method = "GET", url = "https://connect.squareup.com/v2/inventory/{catalog_object_id}", path = {"catalog_object_id"}, query = {"location_ids", "cursor"} },
    ["squareup.retrieve_inventory_physical_count"] = { method = "GET", url = "https://connect.squareup.com/v2/inventory/physical-counts/{physical_count_id}", path = {"physical_count_id"} },
    ["squareup.retrieve_inventory_transfer"] = { method = "GET", url = "https://connect.squareup.com/v2/inventory/transfers/{transfer_id}", path = {"transfer_id"} },
    ["squareup.retrieve_location"] = { method = "GET", url = "https://connect.squareup.com/v2/locations/{location_id}", path = {"location_id"} },
    ["squareup.retrieve_loyalty_account"] = { method = "GET", url = "https://connect.squareup.com/v2/loyalty/accounts/{account_id}", path = {"account_id"} },
    ["squareup.retrieve_loyalty_program"] = { method = "GET", url = "https://connect.squareup.com/v2/loyalty/programs/{program_id}", path = {"program_id"} },
    ["squareup.retrieve_loyalty_reward"] = { method = "GET", url = "https://connect.squareup.com/v2/loyalty/rewards/{reward_id}", path = {"reward_id"} },
    ["squareup.retrieve_merchant"] = { method = "GET", url = "https://connect.squareup.com/v2/merchants/{merchant_id}", path = {"merchant_id"} },
    ["squareup.retrieve_order"] = { method = "GET", url = "https://connect.squareup.com/v1/{location_id}/orders/{order_id}", path = {"location_id", "order_id"} },
    ["squareup.retrieve_payment"] = { method = "GET", url = "https://connect.squareup.com/v1/{location_id}/payments/{payment_id}", path = {"location_id", "payment_id"} },
    ["squareup.retrieve_settlement"] = { method = "GET", url = "https://connect.squareup.com/v1/{location_id}/settlements/{settlement_id}", path = {"location_id", "settlement_id"} },
    ["squareup.retrieve_snippet"] = { method = "GET", url = "https://connect.squareup.com/v2/sites/{site_id}/snippet", path = {"site_id"} },
    ["squareup.retrieve_subscription"] = { method = "GET", url = "https://connect.squareup.com/v2/subscriptions/{subscription_id}", path = {"subscription_id"} },
    ["squareup.retrieve_team_member"] = { method = "GET", url = "https://connect.squareup.com/v2/team-members/{team_member_id}", path = {"team_member_id"} },
    ["squareup.retrieve_team_member_booking_profile"] = { method = "GET", url = "https://connect.squareup.com/v2/bookings/team-member-booking-profiles/{team_member_id}", path = {"team_member_id"} },
    ["squareup.retrieve_transaction"] = { method = "GET", url = "https://connect.squareup.com/v2/locations/{location_id}/transactions/{transaction_id}", path = {"location_id", "transaction_id"} },
    ["squareup.retrieve_wage_setting"] = { method = "GET", url = "https://connect.squareup.com/v2/team-members/{team_member_id}/wage-setting", path = {"team_member_id"} },
    ["squareup.revoke_token"] = { method = "POST", url = "https://connect.squareup.com/oauth2/revoke", body = {"client_id", "merchant_id", "revoke_only_access_token"} },
    ["squareup.search_availability"] = { method = "POST", url = "https://connect.squareup.com/v2/bookings/availability/search", body = {"query"} },
    ["squareup.search_catalog_items"] = { method = "POST", url = "https://connect.squareup.com/v2/catalog/search-catalog-items", body = {"category_ids", "cursor", "custom_attribute_filters", "enabled_location_ids", "limit", "product_types", "sort_order", "stock_levels", "text_filter"} },
    ["squareup.search_catalog_objects"] = { method = "POST", url = "https://connect.squareup.com/v2/catalog/search", body = {"begin_time", "cursor", "include_deleted_objects", "include_related_objects", "limit", "object_types", "query"} },
    ["squareup.search_customers"] = { method = "POST", url = "https://connect.squareup.com/v2/customers/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_invoices"] = { method = "POST", url = "https://connect.squareup.com/v2/invoices/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_loyalty_accounts"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/accounts/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_loyalty_events"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/events/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_loyalty_rewards"] = { method = "POST", url = "https://connect.squareup.com/v2/loyalty/rewards/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_orders"] = { method = "POST", url = "https://connect.squareup.com/v2/orders/search", body = {"cursor", "limit", "location_ids", "query", "return_entries"} },
    ["squareup.search_shifts"] = { method = "POST", url = "https://connect.squareup.com/v2/labor/shifts/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_subscriptions"] = { method = "POST", url = "https://connect.squareup.com/v2/subscriptions/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_team_members"] = { method = "POST", url = "https://connect.squareup.com/v2/team-members/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_terminal_checkouts"] = { method = "POST", url = "https://connect.squareup.com/v2/terminals/checkouts/search", body = {"cursor", "limit", "query"} },
    ["squareup.search_terminal_refunds"] = { method = "POST", url = "https://connect.squareup.com/v2/terminals/refunds/search", body = {"cursor", "limit", "query"} },
    ["squareup.submit_evidence"] = { method = "POST", url = "https://connect.squareup.com/v2/disputes/{dispute_id}/submit-evidence", path = {"dispute_id"} },
    ["squareup.unlink_customer_from_gift_card"] = { method = "POST", url = "https://connect.squareup.com/v2/gift-cards/{gift_card_id}/unlink-customer", path = {"gift_card_id"}, body = {"customer_id"} },
    ["squareup.update_booking"] = { method = "PUT", url = "https://connect.squareup.com/v2/bookings/{booking_id}", path = {"booking_id"}, body = {"booking", "idempotency_key"} },
    ["squareup.update_break_type"] = { method = "PUT", url = "https://connect.squareup.com/v2/labor/break-types/{id}", path = {"id"}, body = {"break_type"} },
    ["squareup.update_customer"] = { method = "PUT", url = "https://connect.squareup.com/v2/customers/{customer_id}", path = {"customer_id"}, body = {"address", "birthday", "company_name", "email_address", "family_name", "given_name", "nickname", "note", "phone_number", "reference_id", "version"} },
    ["squareup.update_customer_group"] = { method = "PUT", url = "https://connect.squareup.com/v2/customers/groups/{group_id}", path = {"group_id"}, body = {"group"} },
    ["squareup.update_employee"] = { method = "PUT", url = "https://connect.squareup.com/v1/me/employees/{employee_id}", path = {"employee_id"} },
    ["squareup.update_employee_role"] = { method = "PUT", url = "https://connect.squareup.com/v1/me/roles/{role_id}", path = {"role_id"}, body = {"created_at", "id", "is_owner", "name", "permissions", "updated_at"} },
    ["squareup.update_invoice"] = { method = "PUT", url = "https://connect.squareup.com/v2/invoices/{invoice_id}", path = {"invoice_id"}, body = {"fields_to_clear", "idempotency_key", "invoice"} },
    ["squareup.update_item_modifier_lists"] = { method = "POST", url = "https://connect.squareup.com/v2/catalog/update-item-modifier-lists", body = {"item_ids", "modifier_lists_to_disable", "modifier_lists_to_enable"} },
    ["squareup.update_item_taxes"] = { method = "POST", url = "https://connect.squareup.com/v2/catalog/update-item-taxes", body = {"item_ids", "taxes_to_disable", "taxes_to_enable"} },
    ["squareup.update_location"] = { method = "PUT", url = "https://connect.squareup.com/v2/locations/{location_id}", path = {"location_id"}, body = {"location"} },
    ["squareup.update_order"] = { method = "PUT", url = "https://connect.squareup.com/v1/{location_id}/orders/{order_id}", path = {"location_id", "order_id"}, body = {"action", "canceled_note", "completed_note", "refunded_note", "shipped_tracking_number"} },
    ["squareup.update_payment"] = { method = "PUT", url = "https://connect.squareup.com/v2/payments/{payment_id}", path = {"payment_id"}, body = {"idempotency_key", "payment"} },
    ["squareup.update_shift"] = { method = "PUT", url = "https://connect.squareup.com/v2/labor/shifts/{id}", path = {"id"}, body = {"shift"} },
    ["squareup.update_subscription"] = { method = "PUT", url = "https://connect.squareup.com/v2/subscriptions/{subscription_id}", path = {"subscription_id"}, body = {"subscription"} },
    ["squareup.update_team_member"] = { method = "PUT", url = "https://connect.squareup.com/v2/team-members/{team_member_id}", path = {"team_member_id"}, body = {"team_member"} },
    ["squareup.update_wage_setting"] = { method = "PUT", url = "https://connect.squareup.com/v2/team-members/{team_member_id}/wage-setting", path = {"team_member_id"}, body = {"wage_setting"} },
    ["squareup.update_workweek_config"] = { method = "PUT", url = "https://connect.squareup.com/v2/labor/workweek-configs/{id}", path = {"id"}, body = {"workweek_config"} },
    ["squareup.upsert_catalog_object"] = { method = "POST", url = "https://connect.squareup.com/v2/catalog/object", body = {"idempotency_key", "object"} },
    ["squareup.upsert_snippet"] = { method = "POST", url = "https://connect.squareup.com/v2/sites/{site_id}/snippet", path = {"site_id"}, body = {"snippet"} },
    ["squareup.void_transaction"] = { method = "POST", url = "https://connect.squareup.com/v2/locations/{location_id}/transactions/{transaction_id}/void", path = {"location_id", "transaction_id"} },
  },
}
