-- Live Tennis API — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/livetennisapi/openapi/main/openapi.yaml
-- Published by livetennisapi, the vendor's own GitHub organisation.
-- 43 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "livetennisapi",
  name = "Live Tennis API",
  base = "https://api.livetennisapi.com",
  docs = "https://nango.dev/docs/api-integrations/livetennisapi",
  auth = {
    kind = "key",
    header = "x-api-key",
    format = "{token}",
    env = "LIVETENNISAPI_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["livetennisapi.create_webhook"] = { method = "POST", url = "https://api.livetennisapi.com/webhooks", body = {"url", "events"} },
    ["livetennisapi.create_ws_token"] = { method = "GET", url = "https://api.livetennisapi.com/ws-token" },
    ["livetennisapi.delete_webhook"] = { method = "DELETE", url = "https://api.livetennisapi.com/webhooks/{webhookId}", path = {"webhookId"} },
    ["livetennisapi.get_archive_career"] = { method = "GET", url = "https://api.livetennisapi.com/history/archive/career", query = {"name"} },
    ["livetennisapi.get_archive_match"] = { method = "GET", url = "https://api.livetennisapi.com/history/archive/matches/{archiveId}", path = {"archiveId"} },
    ["livetennisapi.get_archive_tape"] = { method = "GET", url = "https://api.livetennisapi.com/history/archive/matches/{archiveId}/tape", path = {"archiveId"} },
    ["livetennisapi.get_charting_match"] = { method = "GET", url = "https://api.livetennisapi.com/charting/matches/{chartingMatchId}", path = {"chartingMatchId"} },
    ["livetennisapi.get_charting_player"] = { method = "GET", url = "https://api.livetennisapi.com/charting/players", query = {"name", "gender"} },
    ["livetennisapi.get_head_to_head"] = { method = "GET", url = "https://api.livetennisapi.com/h2h", query = {"p1", "p2"} },
    ["livetennisapi.get_history_coverage"] = { method = "GET", url = "https://api.livetennisapi.com/history/coverage" },
    ["livetennisapi.get_history_package"] = { method = "GET", url = "https://api.livetennisapi.com/history/packages/{period}", path = {"period"}, query = {"kind", "format"} },
    ["livetennisapi.get_market_prices"] = { method = "GET", url = "https://api.livetennisapi.com/markets/{matchId}/prices", path = {"matchId"}, query = {"limit"} },
    ["livetennisapi.get_match"] = { method = "GET", url = "https://api.livetennisapi.com/matches/{matchId}", path = {"matchId"} },
    ["livetennisapi.get_match_analysis"] = { method = "GET", url = "https://api.livetennisapi.com/matches/{matchId}/analysis", path = {"matchId"} },
    ["livetennisapi.get_match_points"] = { method = "GET", url = "https://api.livetennisapi.com/matches/{matchId}/points", path = {"matchId"}, query = {"after_seq"} },
    ["livetennisapi.get_match_rally"] = { method = "GET", url = "https://api.livetennisapi.com/history/matches/{matchId}/rally", path = {"matchId"}, query = {"limit", "offset"} },
    ["livetennisapi.get_match_score"] = { method = "GET", url = "https://api.livetennisapi.com/matches/{matchId}/score", path = {"matchId"} },
    ["livetennisapi.get_match_statistics"] = { method = "GET", url = "https://api.livetennisapi.com/matches/{matchId}/statistics", path = {"matchId"} },
    ["livetennisapi.get_match_status_history"] = { method = "GET", url = "https://api.livetennisapi.com/matches/{matchId}/status-history", path = {"matchId"}, query = {"limit", "offset"} },
    ["livetennisapi.get_match_tape"] = { method = "GET", url = "https://api.livetennisapi.com/history/matches/{matchId}", path = {"matchId"}, query = {"sequence", "points"} },
    ["livetennisapi.get_player"] = { method = "GET", url = "https://api.livetennisapi.com/players/{playerId}", path = {"playerId"} },
    ["livetennisapi.get_rally_match"] = { method = "GET", url = "https://api.livetennisapi.com/rally/matches/{rallyMatchId}", path = {"rallyMatchId"}, query = {"limit", "offset"} },
    ["livetennisapi.get_tournament"] = { method = "GET", url = "https://api.livetennisapi.com/tournaments/{tournamentId}", path = {"tournamentId"} },
    ["livetennisapi.get_usage"] = { method = "GET", url = "https://api.livetennisapi.com/usage" },
    ["livetennisapi.health_check"] = { method = "GET", url = "https://api.livetennisapi.com/health" },
    ["livetennisapi.list_archive_matches"] = { method = "GET", url = "https://api.livetennisapi.com/history/archive/matches", query = {"tour", "name", "from", "to", "round", "level", "limit", "offset"} },
    ["livetennisapi.list_archive_players"] = { method = "GET", url = "https://api.livetennisapi.com/history/archive/players", query = {"name", "tour", "limit", "offset"} },
    ["livetennisapi.list_completed_matches"] = { method = "GET", url = "https://api.livetennisapi.com/history/matches", query = {"has_market", "limit", "offset", "from", "to", "tour", "draw", "player", "country", "tournament_id", "coverage", "points_complete"} },
    ["livetennisapi.list_fixtures"] = { method = "GET", url = "https://api.livetennisapi.com/fixtures", query = {"tour", "draw", "limit", "offset"} },
    ["livetennisapi.list_history_match_prices"] = { method = "GET", url = "https://api.livetennisapi.com/history/matches/{matchId}/prices", path = {"matchId"}, query = {"after_seq", "limit"} },
    ["livetennisapi.list_history_packages"] = { method = "GET", url = "https://api.livetennisapi.com/history/packages", query = {"kind", "year"} },
    ["livetennisapi.list_markets"] = { method = "GET", url = "https://api.livetennisapi.com/markets", query = {"match_id"} },
    ["livetennisapi.list_match_events"] = { method = "GET", url = "https://api.livetennisapi.com/matches/{matchId}/events", path = {"matchId"}, query = {"limit", "offset"} },
    ["livetennisapi.list_match_prices"] = { method = "GET", url = "https://api.livetennisapi.com/matches/{matchId}/prices", path = {"matchId"}, query = {"limit", "minutes", "cursor"} },
    ["livetennisapi.list_matches"] = { method = "GET", url = "https://api.livetennisapi.com/matches", query = {"status", "tour", "draw", "player", "country", "tournament_id", "has_analysis", "has_market", "from", "to", "updated_since", "cursor", "limit", "offset"} },
    ["livetennisapi.list_player_injuries"] = { method = "GET", url = "https://api.livetennisapi.com/players/{playerId}/injuries", path = {"playerId"}, query = {"since", "until", "kind", "before", "limit"} },
    ["livetennisapi.list_player_stoppages"] = { method = "GET", url = "https://api.livetennisapi.com/players/{playerId}/stoppages", path = {"playerId"}, query = {"since", "until", "kind", "before", "limit"} },
    ["livetennisapi.list_rally_matches"] = { method = "GET", url = "https://api.livetennisapi.com/rally/matches", query = {"player", "from", "to", "surface", "gender", "limit", "offset"} },
    ["livetennisapi.list_rankings"] = { method = "GET", url = "https://api.livetennisapi.com/rankings", query = {"player", "archive_player", "tour", "surface", "min_matches", "activity_weeks", "as_of", "system", "limit", "offset"} },
    ["livetennisapi.list_slate_events"] = { method = "GET", url = "https://api.livetennisapi.com/events", query = {"type", "after_id", "since", "limit"} },
    ["livetennisapi.list_tournaments"] = { method = "GET", url = "https://api.livetennisapi.com/tournaments", query = {"search", "tour", "draw", "limit", "offset"} },
    ["livetennisapi.list_webhooks"] = { method = "GET", url = "https://api.livetennisapi.com/webhooks" },
    ["livetennisapi.search_players"] = { method = "GET", url = "https://api.livetennisapi.com/players", query = {"search", "limit", "offset"} },
  },
}
