-- Google BigQuery — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/googleapis.com/bigquery/v2/openapi.json
-- APIs.guru's mirror of googleapis.com:bigquery, matched on googleapis.com. A mirror lags the vendor.
-- 36 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "google-bigquery",
  name = "Google BigQuery",
  base = "https://bigquery.googleapis.com",
  docs = "https://nango.dev/docs/api-integrations/google-bigquery",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "GOOGLE_BIGQUERY_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["google-bigquery.bigquery_datasets_delete"] = { method = "DELETE", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "deleteContents"} },
    ["google-bigquery.bigquery_datasets_get"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-bigquery.bigquery_datasets_insert"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets", path = {"projectId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"access", "creationTime", "datasetReference", "defaultCollation", "defaultEncryptionConfiguration", "defaultPartitionExpirationMs", "defaultRoundingMode", "defaultTableExpirationMs", "description", "etag", "friendlyName", "id", "isCaseInsensitive", "kind", "labels", "lastModifiedTime", "location", "maxTimeTravelHours", "satisfiesPzs", "selfLink", "storageBillingModel", "tags"} },
    ["google-bigquery.bigquery_datasets_list"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets", path = {"projectId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "all", "filter", "maxResults", "pageToken"} },
    ["google-bigquery.bigquery_datasets_patch"] = { method = "PATCH", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"access", "creationTime", "datasetReference", "defaultCollation", "defaultEncryptionConfiguration", "defaultPartitionExpirationMs", "defaultRoundingMode", "defaultTableExpirationMs", "description", "etag", "friendlyName", "id", "isCaseInsensitive", "kind", "labels", "lastModifiedTime", "location", "maxTimeTravelHours", "satisfiesPzs", "selfLink", "storageBillingModel", "tags"} },
    ["google-bigquery.bigquery_datasets_update"] = { method = "PUT", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"access", "creationTime", "datasetReference", "defaultCollation", "defaultEncryptionConfiguration", "defaultPartitionExpirationMs", "defaultRoundingMode", "defaultTableExpirationMs", "description", "etag", "friendlyName", "id", "isCaseInsensitive", "kind", "labels", "lastModifiedTime", "location", "maxTimeTravelHours", "satisfiesPzs", "selfLink", "storageBillingModel", "tags"} },
    ["google-bigquery.bigquery_jobs_cancel"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/jobs/{jobId}/cancel", path = {"projectId", "jobId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "location"} },
    ["google-bigquery.bigquery_jobs_delete"] = { method = "DELETE", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/jobs/{jobId}/delete", path = {"projectId", "jobId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "location"} },
    ["google-bigquery.bigquery_jobs_get"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/jobs/{jobId}", path = {"projectId", "jobId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "location"} },
    ["google-bigquery.bigquery_jobs_get_query_results"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/queries/{jobId}", path = {"projectId", "jobId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "location", "maxResults", "pageToken", "startIndex", "timeoutMs"} },
    ["google-bigquery.bigquery_jobs_insert"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/jobs", path = {"projectId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-bigquery.bigquery_jobs_list"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/jobs", path = {"projectId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "allUsers", "maxCreationTime", "maxResults", "minCreationTime", "pageToken", "parentJobId", "projection", "stateFilter"} },
    ["google-bigquery.bigquery_jobs_query"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/queries", path = {"projectId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"connectionProperties", "continuous", "createSession", "defaultDataset", "dryRun", "kind", "labels", "location", "maxResults", "maximumBytesBilled", "parameterMode", "preserveNulls", "query", "queryParameters", "requestId", "timeoutMs", "useLegacySql", "useQueryCache"} },
    ["google-bigquery.bigquery_models_delete"] = { method = "DELETE", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/models/{modelId}", path = {"projectId", "datasetId", "modelId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-bigquery.bigquery_models_get"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/models/{modelId}", path = {"projectId", "datasetId", "modelId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-bigquery.bigquery_models_list"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/models", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "pageToken"} },
    ["google-bigquery.bigquery_models_patch"] = { method = "PATCH", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/models/{modelId}", path = {"projectId", "datasetId", "modelId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"bestTrialId", "creationTime", "defaultTrialId", "description", "encryptionConfiguration", "etag", "expirationTime", "featureColumns", "friendlyName", "hparamSearchSpaces", "hparamTrials", "labelColumns", "labels", "lastModifiedTime", "location", "modelReference", "modelType", "optimalTrialIds", "trainingRuns"} },
    ["google-bigquery.bigquery_projects_get_service_account"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/serviceAccount", path = {"projectId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-bigquery.bigquery_projects_list"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects", query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "pageToken"} },
    ["google-bigquery.bigquery_routines_delete"] = { method = "DELETE", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/routines/{routineId}", path = {"projectId", "datasetId", "routineId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-bigquery.bigquery_routines_get"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/routines/{routineId}", path = {"projectId", "datasetId", "routineId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "readMask"} },
    ["google-bigquery.bigquery_routines_insert"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/routines", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"arguments", "creationTime", "definitionBody", "description", "determinismLevel", "etag", "importedLibraries", "language", "lastModifiedTime", "remoteFunctionOptions", "returnTableType", "returnType", "routineReference", "routineType", "sparkOptions", "strictMode"} },
    ["google-bigquery.bigquery_routines_list"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/routines", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "filter", "maxResults", "pageToken", "readMask"} },
    ["google-bigquery.bigquery_routines_update"] = { method = "PUT", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/routines/{routineId}", path = {"projectId", "datasetId", "routineId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"arguments", "creationTime", "definitionBody", "description", "determinismLevel", "etag", "importedLibraries", "language", "lastModifiedTime", "remoteFunctionOptions", "returnTableType", "returnType", "routineReference", "routineType", "sparkOptions", "strictMode"} },
    ["google-bigquery.bigquery_row_access_policies_list"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}/rowAccessPolicies", path = {"projectId", "datasetId", "tableId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "pageSize", "pageToken"} },
    ["google-bigquery.bigquery_tabledata_insert_all"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}/insertAll", path = {"projectId", "datasetId", "tableId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"ignoreUnknownValues", "kind", "rows", "skipInvalidRows", "templateSuffix"} },
    ["google-bigquery.bigquery_tabledata_list"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}/data", path = {"projectId", "datasetId", "tableId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "pageToken", "selectedFields", "startIndex"} },
    ["google-bigquery.bigquery_tables_delete"] = { method = "DELETE", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}", path = {"projectId", "datasetId", "tableId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"} },
    ["google-bigquery.bigquery_tables_get"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}", path = {"projectId", "datasetId", "tableId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "selectedFields", "view"} },
    ["google-bigquery.bigquery_tables_get_iam_policy"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/{resource}:getIamPolicy", path = {"resource"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"options"} },
    ["google-bigquery.bigquery_tables_insert"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"cloneDefinition", "clustering", "creationTime", "defaultCollation", "defaultRoundingMode", "description", "encryptionConfiguration", "etag", "expirationTime", "externalDataConfiguration", "friendlyName", "id", "kind", "labels", "lastModifiedTime", "location", "materializedView", "maxStaleness", "model", "numBytes", "numLongTermBytes", "numPhysicalBytes", "numRows", "num_active_logical_bytes", "num_active_physical_bytes", "num_long_term_logical_bytes", "num_long_term_physical_bytes", "num_partitions", "num_time_travel_physical_bytes", "num_total_logical_bytes", "num_total_physical_bytes", "rangePartitioning", "requirePartitionFilter", "schema", "selfLink", "snapshotDefinition", "streamingBuffer", "tableReference", "timePartitioning", "type", "view"} },
    ["google-bigquery.bigquery_tables_list"] = { method = "GET", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables", path = {"projectId", "datasetId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "maxResults", "pageToken"} },
    ["google-bigquery.bigquery_tables_patch"] = { method = "PATCH", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}", path = {"projectId", "datasetId", "tableId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "autodetect_schema"}, body = {"cloneDefinition", "clustering", "creationTime", "defaultCollation", "defaultRoundingMode", "description", "encryptionConfiguration", "etag", "expirationTime", "externalDataConfiguration", "friendlyName", "id", "kind", "labels", "lastModifiedTime", "location", "materializedView", "maxStaleness", "model", "numBytes", "numLongTermBytes", "numPhysicalBytes", "numRows", "num_active_logical_bytes", "num_active_physical_bytes", "num_long_term_logical_bytes", "num_long_term_physical_bytes", "num_partitions", "num_time_travel_physical_bytes", "num_total_logical_bytes", "num_total_physical_bytes", "rangePartitioning", "requirePartitionFilter", "schema", "selfLink", "snapshotDefinition", "streamingBuffer", "tableReference", "timePartitioning", "type", "view"} },
    ["google-bigquery.bigquery_tables_set_iam_policy"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/{resource}:setIamPolicy", path = {"resource"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"policy", "updateMask"} },
    ["google-bigquery.bigquery_tables_test_iam_permissions"] = { method = "POST", url = "https://bigquery.googleapis.com/bigquery/v2/{resource}:testIamPermissions", path = {"resource"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp"}, body = {"permissions"} },
    ["google-bigquery.bigquery_tables_update"] = { method = "PUT", url = "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}", path = {"projectId", "datasetId", "tableId"}, query = {"alt", "fields", "oauth_token", "prettyPrint", "quotaUser", "userIp", "autodetect_schema"}, body = {"cloneDefinition", "clustering", "creationTime", "defaultCollation", "defaultRoundingMode", "description", "encryptionConfiguration", "etag", "expirationTime", "externalDataConfiguration", "friendlyName", "id", "kind", "labels", "lastModifiedTime", "location", "materializedView", "maxStaleness", "model", "numBytes", "numLongTermBytes", "numPhysicalBytes", "numRows", "num_active_logical_bytes", "num_active_physical_bytes", "num_long_term_logical_bytes", "num_long_term_physical_bytes", "num_partitions", "num_time_travel_physical_bytes", "num_total_logical_bytes", "num_total_physical_bytes", "rangePartitioning", "requirePartitionFilter", "schema", "selfLink", "snapshotDefinition", "streamingBuffer", "tableReference", "timePartitioning", "type", "view"} },
  },
}
