-- Pandadoc — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/PandaDoc/pandadoc-openapi-specification/main/openapi.json
-- Published by PandaDoc, the vendor's own GitHub organisation.
-- 128 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "pandadoc-mcp-eu",
  name = "Pandadoc",
  base = "https://mcp.pandadoc.eu",
  docs = "https://nango.dev/docs/api-integrations/pandadoc-mcp-eu",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "PANDADOC_MCP_EU_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["pandadoc-mcp-eu.access_token"] = { method = "POST", url = "https://mcp.pandadoc.eu/oauth2/access_token" },
    ["pandadoc-mcp-eu.add_document_recipient"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/recipients", path = {"id"}, body = {"id", "kind"} },
    ["pandadoc-mcp-eu.add_dsv_named_items"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v2/dsv/{document_id}/add-named-items", path = {"document_id"}, body = {"items"} },
    ["pandadoc-mcp-eu.add_member"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/workspaces/{workspace_id}/members", path = {"workspace_id"}, query = {"notify_user", "notify_ws_admins"}, body = {"user_id", "role"} },
    ["pandadoc-mcp-eu.append_content_library_item_to_document"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/append-content-library-item", path = {"id"}, body = {"cli"} },
    ["pandadoc-mcp-eu.batch_get_document_ai_metadata"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/beta/documents/ai-metadata", body = {"document_ids", "field_keys"} },
    ["pandadoc-mcp-eu.bulk_delete_documents"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/documents" },
    ["pandadoc-mcp-eu.change_document_status"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/status", path = {"id"}, body = {"status", "note", "notify_recipients"} },
    ["pandadoc-mcp-eu.change_document_status_with_upload"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/status?upload", path = {"id"}, body = {"file", "data"} },
    ["pandadoc-mcp-eu.change_member_role"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/workspaces/{workspace_id}/members/{member_id}/role", path = {"workspace_id", "member_id"}, body = {"role"} },
    ["pandadoc-mcp-eu.create_api_key"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/workspaces/{workspace_id}/api-keys", path = {"workspace_id"}, body = {"user_id", "type"} },
    ["pandadoc-mcp-eu.create_catalog_item"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v2/product-catalog/items", body = {"title", "category_id", "sku", "description", "type", "bundle_items", "images", "custom_fields", "price_configuration"} },
    ["pandadoc-mcp-eu.create_contact"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/contacts", body = {"email", "first_name", "last_name", "company", "job_title", "phone", "country", "state", "street_address", "city", "postal_code"} },
    ["pandadoc-mcp-eu.create_content_library_item"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/content-library-items", body = {"url"} },
    ["pandadoc-mcp-eu.create_content_library_item_from_upload"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/content-library-items?upload", body = {"file", "data"} },
    ["pandadoc-mcp-eu.create_document"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents", query = {"editor_ver", "use_form_field_properties"} },
    ["pandadoc-mcp-eu.create_document_attachment"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/attachments", path = {"id"}, body = {"source"} },
    ["pandadoc-mcp-eu.create_document_attachment_from_file_upload"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/attachments?upload", path = {"id"}, body = {"file"} },
    ["pandadoc-mcp-eu.create_document_editing_session"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/editing-sessions", path = {"id"}, body = {"email", "lifetime"} },
    ["pandadoc-mcp-eu.create_document_fields"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/fields", path = {"id"}, body = {"fields"} },
    ["pandadoc-mcp-eu.create_document_folder"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/folders", body = {"name", "parent_uuid"} },
    ["pandadoc-mcp-eu.create_document_from_markdown_upload"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents?upload-markdown", body = {"file", "data"} },
    ["pandadoc-mcp-eu.create_document_from_upload"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents?upload", query = {"editor_ver", "use_form_field_properties"}, body = {"file", "data"} },
    ["pandadoc-mcp-eu.create_document_link"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/session", path = {"id"}, body = {"recipient", "lifetime"} },
    ["pandadoc-mcp-eu.create_export_docx_task"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/beta/documents/{document_id}/docx-export-tasks", path = {"document_id"} },
    ["pandadoc-mcp-eu.create_linked_object"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/linked-objects", path = {"id"}, body = {"provider", "entity_type", "entity_id"} },
    ["pandadoc-mcp-eu.create_manual_reminder"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/send-reminder", path = {"document_id"}, body = {"reminders"} },
    ["pandadoc-mcp-eu.create_member_token"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/members/{member_id}/token", path = {"member_id"}, body = {"lifetime"} },
    ["pandadoc-mcp-eu.create_notarization_request"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v2/notary/notarization-requests", body = {"document_id", "disable_invitees_notifications", "invitation", "notary"} },
    ["pandadoc-mcp-eu.create_template"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/templates", query = {"fields"}, body = {"url"} },
    ["pandadoc-mcp-eu.create_template_editing_session"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/templates/{id}/editing-sessions", path = {"id"}, body = {"email", "lifetime"} },
    ["pandadoc-mcp-eu.create_template_folder"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/templates/folders", body = {"name", "parent_uuid"} },
    ["pandadoc-mcp-eu.create_template_with_upload"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/templates?upload", query = {"fields"}, body = {"file", "data"} },
    ["pandadoc-mcp-eu.create_user"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/users", query = {"notify_user", "notify_ws_admins"}, body = {"user", "workspaces", "license"} },
    ["pandadoc-mcp-eu.create_webhook_subscription"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/webhook-subscriptions", body = {"name", "url", "active", "payload", "triggers"} },
    ["pandadoc-mcp-eu.create_workspace"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/workspaces", body = {"name", "icon_url", "settings"} },
    ["pandadoc-mcp-eu.deactivate_workspace"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/workspaces/{workspace_id}/deactivate", path = {"workspace_id"} },
    ["pandadoc-mcp-eu.delete_catalog_item"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v2/product-catalog/items/{item_uuid}", path = {"item_uuid", "item_uuid"} },
    ["pandadoc-mcp-eu.delete_contact"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/contacts/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.delete_document"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.delete_document_attachment"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/attachments/{attachment_id}", path = {"id", "attachment_id"} },
    ["pandadoc-mcp-eu.delete_document_recipient"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/recipients/{recipient_id}", path = {"id", "recipient_id"} },
    ["pandadoc-mcp-eu.delete_linked_object"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/linked-objects/{linked_object_id}", path = {"id", "linked_object_id"} },
    ["pandadoc-mcp-eu.delete_notarization_request"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v2/notary/notarization-requests/{session_request_id}", path = {"session_request_id"} },
    ["pandadoc-mcp-eu.delete_section"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/sections/{section_id}", path = {"document_id", "section_id"} },
    ["pandadoc-mcp-eu.delete_template"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/templates/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.delete_webhook_subscription"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/webhook-subscriptions/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.details_contact"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/contacts/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.details_content_library_item"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/content-library-items/{id}/details", path = {"id"} },
    ["pandadoc-mcp-eu.details_current_member"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/members/current" },
    ["pandadoc-mcp-eu.details_document"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/details", path = {"id"} },
    ["pandadoc-mcp-eu.details_document_attachment"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/attachments/{attachment_id}", path = {"id", "attachment_id"} },
    ["pandadoc-mcp-eu.details_log_v2"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/logs/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.details_member"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/members/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.details_template"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/templates/{id}/details", path = {"id"} },
    ["pandadoc-mcp-eu.details_user"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/users/{user_id}", path = {"user_id"} },
    ["pandadoc-mcp-eu.details_webhook_event"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/webhook-events/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.details_webhook_subscription"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/webhook-subscriptions/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.document_esign_disclosure"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/esign-disclosure", path = {"document_id"} },
    ["pandadoc-mcp-eu.document_move_to_folder"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/move-to-folder/{folder_id}", path = {"id", "folder_id"} },
    ["pandadoc-mcp-eu.document_revert_to_draft"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/draft", path = {"id"} },
    ["pandadoc-mcp-eu.document_settings_get"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/documents/{document_id}/settings", path = {"document_id"} },
    ["pandadoc-mcp-eu.document_settings_update"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v2/documents/{document_id}/settings", path = {"document_id"}, body = {"language", "qualified_electronic_signature", "expires_in", "suggest_edits"} },
    ["pandadoc-mcp-eu.download_document"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/download", path = {"id"}, query = {"watermark_color", "watermark_font_size", "watermark_opacity", "watermark_text", "separate_files"} },
    ["pandadoc-mcp-eu.download_document_attachment"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/attachments/{attachment_id}/download", path = {"id", "attachment_id"} },
    ["pandadoc-mcp-eu.download_protected_document"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/download-protected", path = {"id"}, query = {"separate_files"} },
    ["pandadoc-mcp-eu.duplicate_template"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/templates/{id}/duplicate", path = {"id"}, body = {"name"} },
    ["pandadoc-mcp-eu.edit_document_recipient"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/recipients/recipient/{recipient_id}", path = {"id", "recipient_id"} },
    ["pandadoc-mcp-eu.get_catalog_item"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/product-catalog/items/{item_uuid}", path = {"item_uuid", "item_uuid"} },
    ["pandadoc-mcp-eu.get_document_ai_metadata"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/beta/documents/{document_id}/ai-metadata", path = {"document_id"}, query = {"limit", "offset"} },
    ["pandadoc-mcp-eu.get_document_auto_reminder_settings"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/auto-reminders", path = {"document_id"} },
    ["pandadoc-mcp-eu.get_document_content"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/beta/documents/{document_id}/content", path = {"document_id"}, query = {"format"} },
    ["pandadoc-mcp-eu.get_document_summary"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/beta/documents/{document_id}/summary", path = {"document_id"}, query = {"type"} },
    ["pandadoc-mcp-eu.get_docx_export_task"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/beta/documents/{document_id}/docx-export-tasks/{task_id}", path = {"document_id", "task_id"} },
    ["pandadoc-mcp-eu.get_template_shares"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/templates/{template_id}/shares", path = {"template_id"} },
    ["pandadoc-mcp-eu.get_workspaces_list"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/workspaces", query = {"q", "count", "page"} },
    ["pandadoc-mcp-eu.list_contacts"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/contacts", query = {"email"} },
    ["pandadoc-mcp-eu.list_content_library_items"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/content-library-items", query = {"q", "id", "deleted", "folder_uuid", "count", "page", "tag"} },
    ["pandadoc-mcp-eu.list_document_attachments"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/attachments", path = {"id"} },
    ["pandadoc-mcp-eu.list_document_audit_trail"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/documents/{document_id}/audit-trail", path = {"document_id"}, query = {"limit", "offset"} },
    ["pandadoc-mcp-eu.list_document_fields"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/fields", path = {"id"} },
    ["pandadoc-mcp-eu.list_document_folders"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/folders", query = {"parent_uuid", "count", "page"} },
    ["pandadoc-mcp-eu.list_documents"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents", query = {"template_id", "form_id", "folder_uuid", "contact_id", "count", "page", "order_by", "created_from", "created_to", "deleted", "id", "completed_from", "completed_to", "membership_id", "metadata", "modified_from", "modified_to", "q", "status", "status__ne", "tag"} },
    ["pandadoc-mcp-eu.list_documents_by_linked_object"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/linked-objects", query = {"entity_id", "entity_type", "provider", "order_by", "owner_ids"} },
    ["pandadoc-mcp-eu.list_form"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/forms", query = {"count", "page", "status", "order_by", "asc", "name"} },
    ["pandadoc-mcp-eu.list_linked_objects"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/linked-objects", path = {"id"} },
    ["pandadoc-mcp-eu.list_logs_v2"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/logs", query = {"since", "to", "count", "page", "statuses", "methods", "search", "environment_type"} },
    ["pandadoc-mcp-eu.list_members"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/members" },
    ["pandadoc-mcp-eu.list_notaries"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/notary/notaries", query = {"status", "commission_state", "offset", "limit", "order_by"} },
    ["pandadoc-mcp-eu.list_notarization_requests"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/notary/notarization-requests", query = {"status", "created_by_user_id", "document_id", "offset", "limit", "order_by"} },
    ["pandadoc-mcp-eu.list_recent_sms_opt_outs"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/sms-opt-outs", query = {"timestamp_from", "timestamp_to"} },
    ["pandadoc-mcp-eu.list_sections"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/sections", path = {"document_id"} },
    ["pandadoc-mcp-eu.list_template_folders"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/templates/folders", query = {"parent_uuid", "count", "page"} },
    ["pandadoc-mcp-eu.list_templates"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/templates", query = {"q", "shared", "deleted", "count", "page", "id", "folder_uuid", "tag", "fields"} },
    ["pandadoc-mcp-eu.list_users"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/users", query = {"count", "page", "show_removed"} },
    ["pandadoc-mcp-eu.list_webhook_event"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/webhook-events", query = {"count", "page", "since", "to", "type", "http_status_code", "error"} },
    ["pandadoc-mcp-eu.list_webhook_subscriptions"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/webhook-subscriptions" },
    ["pandadoc-mcp-eu.notarization_request_details"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/notary/notarization-requests/{session_request_id}", path = {"session_request_id"} },
    ["pandadoc-mcp-eu.quote_update"] = { method = "PUT", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/quotes/{quote_id}", path = {"document_id", "quote_id"}, body = {"currency", "summary", "sections", "settings"} },
    ["pandadoc-mcp-eu.reassign_document_recipient"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/recipients/{recipient_id}/reassign", path = {"id", "recipient_id"}, body = {"id", "kind"} },
    ["pandadoc-mcp-eu.remove_member"] = { method = "DELETE", url = "https://mcp.pandadoc.eu/public/v1/workspaces/{workspace_id}/members/{member_id}", path = {"workspace_id", "member_id"} },
    ["pandadoc-mcp-eu.rename_document_folder"] = { method = "PUT", url = "https://mcp.pandadoc.eu/public/v1/documents/folders/{id}", path = {"id"}, body = {"name"} },
    ["pandadoc-mcp-eu.rename_template_folder"] = { method = "PUT", url = "https://mcp.pandadoc.eu/public/v1/templates/folders/{id}", path = {"id"}, body = {"name"} },
    ["pandadoc-mcp-eu.search_catalog_items"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/product-catalog/items/search", query = {"page", "per_page", "query", "order_by", "types", "billing_types", "exclude_uuids", "category_id", "no_category"} },
    ["pandadoc-mcp-eu.search_documents_ai"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/beta/documents/search", query = {"q"} },
    ["pandadoc-mcp-eu.section_details"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/sections/uploads/{upload_id}", path = {"document_id", "upload_id"} },
    ["pandadoc-mcp-eu.section_info"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/sections/{section_id}", path = {"document_id", "section_id"} },
    ["pandadoc-mcp-eu.send_document"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/send", path = {"id"}, body = {"message", "subject", "silent", "sender", "forwarding_settings", "reply_to", "selected_approvers"} },
    ["pandadoc-mcp-eu.status_content_library_item"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/content-library-items/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.status_document"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.status_document_auto_reminder"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/auto-reminders/status", path = {"document_id"} },
    ["pandadoc-mcp-eu.status_template"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v1/templates/{id}", path = {"id"} },
    ["pandadoc-mcp-eu.template_settings_get"] = { method = "GET", url = "https://mcp.pandadoc.eu/public/v2/templates/{template_id}/settings", path = {"template_id"} },
    ["pandadoc-mcp-eu.template_settings_update"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v2/templates/{template_id}/settings", path = {"template_id"}, body = {"language"} },
    ["pandadoc-mcp-eu.transfer_all_documents_ownership"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/documents/ownership", body = {"from_membership_id", "to_membership_id"} },
    ["pandadoc-mcp-eu.transfer_document_ownership"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/ownership", path = {"id"}, body = {"membership_id"} },
    ["pandadoc-mcp-eu.update_catalog_item"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v2/product-catalog/items/{item_uuid}", path = {"item_uuid", "item_uuid"}, body = {"title", "category_id", "type", "bundle_items", "product_variant"} },
    ["pandadoc-mcp-eu.update_contact"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/contacts/{id}", path = {"id"}, body = {"first_name", "last_name", "company", "job_title", "phone", "state", "street_address", "city", "postal_code"} },
    ["pandadoc-mcp-eu.update_document"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}", path = {"id"}, body = {"name", "recipients", "fields", "tokens", "tags", "metadata", "pricing_tables", "tables", "images", "texts"} },
    ["pandadoc-mcp-eu.update_document_auto_reminder_settings"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/auto-reminders", path = {"document_id"}, body = {"enabled", "delivery_method", "initial_delay_days", "is_recurring", "recurrence_frequency_days"} },
    ["pandadoc-mcp-eu.update_document_fields_assignment"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/documents/{id}/fields", path = {"id"}, body = {"fields"} },
    ["pandadoc-mcp-eu.update_template"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/templates/{id}", path = {"id"}, body = {"tokens", "roles"} },
    ["pandadoc-mcp-eu.update_template_sharing_settings"] = { method = "PUT", url = "https://mcp.pandadoc.eu/public/v1/templates/{template_id}/shares", path = {"template_id"}, body = {"workspace_ids"} },
    ["pandadoc-mcp-eu.update_webhook_subscription"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/webhook-subscriptions/{id}", path = {"id"}, body = {"name", "url", "active", "payload", "triggers"} },
    ["pandadoc-mcp-eu.update_webhook_subscription_shared_key"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/v1/webhook-subscriptions/{id}/shared-key", path = {"id"} },
    ["pandadoc-mcp-eu.update_workspace"] = { method = "PATCH", url = "https://mcp.pandadoc.eu/public/beta/workspaces/{workspace_id}", path = {"workspace_id"}, body = {"name", "icon_url", "branding"} },
    ["pandadoc-mcp-eu.upload_section"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/sections/uploads", path = {"document_id"}, query = {"merge_field_scope"} },
    ["pandadoc-mcp-eu.upload_section_with_upload"] = { method = "POST", url = "https://mcp.pandadoc.eu/public/v1/documents/{document_id}/sections/uploads?upload", path = {"document_id"}, query = {"merge_field_scope"}, body = {"file", "data"} },
  },
}
