-- Dropbox Sign — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/hellosign/hellosign-openapi/main/openapi-fern.yaml
-- Published by hellosign, the vendor's own GitHub organisation.
-- 73 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "dropbox-sign",
  name = "Dropbox Sign",
  base = "https://api.hellosign.com",
  docs = "https://nango.dev/docs/integrations/all/dropbox-sign",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "DROPBOX_SIGN_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["dropbox-sign.account_create"] = { method = "POST", url = "https://api.hellosign.com/v3/account/create", body = {"client_id", "client_secret", "email_address", "locale"} },
    ["dropbox-sign.account_get"] = { method = "GET", url = "https://api.hellosign.com/v3/account", query = {"account_id", "email_address"} },
    ["dropbox-sign.account_update"] = { method = "PUT", url = "https://api.hellosign.com/v3/account", body = {"account_id", "callback_url", "locale"} },
    ["dropbox-sign.account_verify"] = { method = "POST", url = "https://api.hellosign.com/v3/account/verify", body = {"email_address"} },
    ["dropbox-sign.api_app_create"] = { method = "POST", url = "https://api.hellosign.com/v3/api_app", body = {"callback_url", "custom_logo_file", "domains", "name", "oauth", "options", "white_labeling_options"} },
    ["dropbox-sign.api_app_delete"] = { method = "DELETE", url = "https://api.hellosign.com/v3/api_app/{client_id}", path = {"client_id"} },
    ["dropbox-sign.api_app_get"] = { method = "GET", url = "https://api.hellosign.com/v3/api_app/{client_id}", path = {"client_id"} },
    ["dropbox-sign.api_app_list"] = { method = "GET", url = "https://api.hellosign.com/v3/api_app/list", query = {"page", "page_size"} },
    ["dropbox-sign.api_app_update"] = { method = "PUT", url = "https://api.hellosign.com/v3/api_app/{client_id}", path = {"client_id"}, body = {"callback_url", "custom_logo_file", "domains", "name", "oauth", "options", "white_labeling_options"} },
    ["dropbox-sign.bulk_send_job_get"] = { method = "GET", url = "https://api.hellosign.com/v3/bulk_send_job/{bulk_send_job_id}", path = {"bulk_send_job_id"}, query = {"page", "page_size"} },
    ["dropbox-sign.bulk_send_job_list"] = { method = "GET", url = "https://api.hellosign.com/v3/bulk_send_job/list", query = {"page", "page_size"} },
    ["dropbox-sign.embedded_edit_url"] = { method = "POST", url = "https://api.hellosign.com/v3/embedded/edit_url/{template_id}", path = {"template_id"}, body = {"allow_edit_ccs", "cc_roles", "editor_options", "force_signer_roles", "force_subject_message", "merge_fields", "preview_only", "show_preview", "show_progress_stepper", "test_mode"} },
    ["dropbox-sign.embedded_sign_url"] = { method = "GET", url = "https://api.hellosign.com/v3/embedded/sign_url/{signature_id}", path = {"signature_id"} },
    ["dropbox-sign.fax_delete"] = { method = "DELETE", url = "https://api.hellosign.com/v3/fax/{fax_id}", path = {"fax_id"} },
    ["dropbox-sign.fax_files"] = { method = "GET", url = "https://api.hellosign.com/v3/fax/files/{fax_id}", path = {"fax_id"} },
    ["dropbox-sign.fax_get"] = { method = "GET", url = "https://api.hellosign.com/v3/fax/{fax_id}", path = {"fax_id"} },
    ["dropbox-sign.fax_line_add_user"] = { method = "PUT", url = "https://api.hellosign.com/v3/fax_line/add_user", body = {"number", "account_id", "email_address"} },
    ["dropbox-sign.fax_line_area_code_get"] = { method = "GET", url = "https://api.hellosign.com/v3/fax_line/area_codes", query = {"country", "state", "province", "city"} },
    ["dropbox-sign.fax_line_create"] = { method = "POST", url = "https://api.hellosign.com/v3/fax_line/create", body = {"area_code", "country", "city", "account_id"} },
    ["dropbox-sign.fax_line_delete"] = { method = "DELETE", url = "https://api.hellosign.com/v3/fax_line", body = {"number"} },
    ["dropbox-sign.fax_line_get"] = { method = "GET", url = "https://api.hellosign.com/v3/fax_line", query = {"number"} },
    ["dropbox-sign.fax_line_list"] = { method = "GET", url = "https://api.hellosign.com/v3/fax_line/list", query = {"account_id", "page", "page_size", "show_team_lines"} },
    ["dropbox-sign.fax_line_remove_user"] = { method = "PUT", url = "https://api.hellosign.com/v3/fax_line/remove_user", body = {"number", "account_id", "email_address"} },
    ["dropbox-sign.fax_list"] = { method = "GET", url = "https://api.hellosign.com/v3/fax/list", query = {"page", "page_size"} },
    ["dropbox-sign.fax_send"] = { method = "POST", url = "https://api.hellosign.com/v3/fax/send", body = {"recipient", "sender", "files", "file_urls", "test_mode", "cover_page_to", "cover_page_from", "cover_page_message", "title"} },
    ["dropbox-sign.oauth_token_generate"] = { method = "POST", url = "https://api.hellosign.com/v3/oauth/token", body = {"client_id", "client_secret", "code", "grant_type", "state"} },
    ["dropbox-sign.oauth_token_refresh"] = { method = "POST", url = "https://api.hellosign.com/v3/oauth/token?refresh", body = {"grant_type", "refresh_token", "client_id", "client_secret"} },
    ["dropbox-sign.report_create"] = { method = "POST", url = "https://api.hellosign.com/v3/report/create", body = {"end_date", "report_type", "start_date"} },
    ["dropbox-sign.signature_request_bulk_create_embedded_with_template"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/bulk_create_embedded_with_template", body = {"template_ids", "signer_file", "signer_list", "allow_decline", "ccs", "client_id", "custom_fields", "message", "metadata", "signing_redirect_url", "subject", "test_mode", "title"} },
    ["dropbox-sign.signature_request_bulk_send_with_template"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/bulk_send_with_template", body = {"template_ids", "signer_file", "signer_list", "allow_decline", "ccs", "client_id", "custom_fields", "message", "metadata", "signing_redirect_url", "subject", "test_mode", "title"} },
    ["dropbox-sign.signature_request_cancel"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/cancel/{signature_request_id}", path = {"signature_request_id"} },
    ["dropbox-sign.signature_request_create_embedded"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/create_embedded", body = {"files", "file_urls", "signers", "grouped_signers", "allow_decline", "allow_reassign", "attachments", "cc_email_addresses", "client_id", "custom_fields", "field_options", "form_field_groups", "form_field_rules", "form_fields_per_document", "hide_text_tags", "message", "metadata", "signing_options", "subject", "test_mode", "title", "use_text_tags", "ignore_text_tags_extraction_errors", "populate_auto_fill_fields", "expires_at"} },
    ["dropbox-sign.signature_request_create_embedded_with_template"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/create_embedded_with_template", body = {"template_ids", "allow_decline", "ccs", "client_id", "custom_fields", "files", "file_urls", "message", "metadata", "signers", "signing_options", "subject", "test_mode", "title", "populate_auto_fill_fields"} },
    ["dropbox-sign.signature_request_edit"] = { method = "PUT", url = "https://api.hellosign.com/v3/signature_request/edit/{signature_request_id}", path = {"signature_request_id"}, body = {"files", "file_urls", "signers", "grouped_signers", "allow_decline", "allow_reassign", "attachments", "cc_email_addresses", "client_id", "custom_fields", "field_options", "form_field_groups", "form_field_rules", "form_fields_per_document", "hide_text_tags", "is_eid", "message", "metadata", "signing_options", "signing_redirect_url", "subject", "test_mode", "title", "use_text_tags", "ignore_text_tags_extraction_errors", "expires_at"} },
    ["dropbox-sign.signature_request_edit_embedded"] = { method = "PUT", url = "https://api.hellosign.com/v3/signature_request/edit_embedded/{signature_request_id}", path = {"signature_request_id"}, body = {"files", "file_urls", "signers", "grouped_signers", "allow_decline", "allow_reassign", "attachments", "cc_email_addresses", "client_id", "custom_fields", "field_options", "form_field_groups", "form_field_rules", "form_fields_per_document", "hide_text_tags", "message", "metadata", "signing_options", "subject", "test_mode", "title", "use_text_tags", "ignore_text_tags_extraction_errors", "populate_auto_fill_fields", "expires_at"} },
    ["dropbox-sign.signature_request_edit_embedded_with_template"] = { method = "PUT", url = "https://api.hellosign.com/v3/signature_request/edit_embedded_with_template/{signature_request_id}", path = {"signature_request_id"}, body = {"template_ids", "allow_decline", "ccs", "client_id", "custom_fields", "files", "file_urls", "message", "metadata", "signers", "signing_options", "subject", "test_mode", "title", "populate_auto_fill_fields"} },
    ["dropbox-sign.signature_request_edit_with_template"] = { method = "PUT", url = "https://api.hellosign.com/v3/signature_request/edit_with_template/{signature_request_id}", path = {"signature_request_id"}, body = {"template_ids", "allow_decline", "ccs", "client_id", "custom_fields", "files", "file_urls", "is_eid", "message", "metadata", "signers", "signing_options", "signing_redirect_url", "subject", "test_mode", "title"} },
    ["dropbox-sign.signature_request_files"] = { method = "GET", url = "https://api.hellosign.com/v3/signature_request/files/{signature_request_id}", path = {"signature_request_id"}, query = {"file_type"} },
    ["dropbox-sign.signature_request_files_as_data_uri"] = { method = "GET", url = "https://api.hellosign.com/v3/signature_request/files_as_data_uri/{signature_request_id}", path = {"signature_request_id"} },
    ["dropbox-sign.signature_request_files_as_file_url"] = { method = "GET", url = "https://api.hellosign.com/v3/signature_request/files_as_file_url/{signature_request_id}", path = {"signature_request_id"}, query = {"force_download"} },
    ["dropbox-sign.signature_request_get"] = { method = "GET", url = "https://api.hellosign.com/v3/signature_request/{signature_request_id}", path = {"signature_request_id"} },
    ["dropbox-sign.signature_request_list"] = { method = "GET", url = "https://api.hellosign.com/v3/signature_request/list", query = {"account_id", "page", "page_size", "query"} },
    ["dropbox-sign.signature_request_release_hold"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/release_hold/{signature_request_id}", path = {"signature_request_id"} },
    ["dropbox-sign.signature_request_remind"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/remind/{signature_request_id}", path = {"signature_request_id"}, body = {"email_address", "name"} },
    ["dropbox-sign.signature_request_remove"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/remove/{signature_request_id}", path = {"signature_request_id"} },
    ["dropbox-sign.signature_request_send"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/send", body = {"files", "file_urls", "signers", "grouped_signers", "allow_decline", "allow_reassign", "attachments", "cc_email_addresses", "client_id", "custom_fields", "field_options", "form_field_groups", "form_field_rules", "form_fields_per_document", "hide_text_tags", "is_eid", "message", "metadata", "signing_options", "signing_redirect_url", "subject", "test_mode", "title", "use_text_tags", "ignore_text_tags_extraction_errors", "expires_at"} },
    ["dropbox-sign.signature_request_send_with_template"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/send_with_template", body = {"template_ids", "allow_decline", "ccs", "client_id", "custom_fields", "files", "file_urls", "is_eid", "message", "metadata", "signers", "signing_options", "signing_redirect_url", "subject", "test_mode", "title"} },
    ["dropbox-sign.signature_request_update"] = { method = "POST", url = "https://api.hellosign.com/v3/signature_request/update/{signature_request_id}", path = {"signature_request_id"}, body = {"email_address", "name", "signature_id", "expires_at"} },
    ["dropbox-sign.team_add_member"] = { method = "PUT", url = "https://api.hellosign.com/v3/team/add_member", query = {"team_id"}, body = {"account_id", "email_address", "role"} },
    ["dropbox-sign.team_create"] = { method = "POST", url = "https://api.hellosign.com/v3/team/create", body = {"name"} },
    ["dropbox-sign.team_delete"] = { method = "DELETE", url = "https://api.hellosign.com/v3/team/destroy" },
    ["dropbox-sign.team_get"] = { method = "GET", url = "https://api.hellosign.com/v3/team" },
    ["dropbox-sign.team_info"] = { method = "GET", url = "https://api.hellosign.com/v3/team/info", query = {"team_id"} },
    ["dropbox-sign.team_invites"] = { method = "GET", url = "https://api.hellosign.com/v3/team/invites", query = {"email_address"} },
    ["dropbox-sign.team_members"] = { method = "GET", url = "https://api.hellosign.com/v3/team/members/{team_id}", path = {"team_id"}, query = {"page", "page_size"} },
    ["dropbox-sign.team_remove_member"] = { method = "POST", url = "https://api.hellosign.com/v3/team/remove_member", body = {"account_id", "email_address", "new_owner_email_address", "new_team_id", "new_role"} },
    ["dropbox-sign.team_sub_teams"] = { method = "GET", url = "https://api.hellosign.com/v3/team/sub_teams/{team_id}", path = {"team_id"}, query = {"page", "page_size"} },
    ["dropbox-sign.team_update"] = { method = "PUT", url = "https://api.hellosign.com/v3/team", body = {"name"} },
    ["dropbox-sign.template_add_user"] = { method = "POST", url = "https://api.hellosign.com/v3/template/add_user/{template_id}", path = {"template_id"}, body = {"account_id", "email_address", "skip_notification"} },
    ["dropbox-sign.template_create"] = { method = "POST", url = "https://api.hellosign.com/v3/template/create", body = {"files", "file_urls", "allow_reassign", "attachments", "cc_roles", "client_id", "field_options", "form_field_groups", "form_field_rules", "form_fields_per_document", "merge_fields", "message", "metadata", "signer_roles", "subject", "test_mode", "title", "use_preexisting_fields", "ignore_text_tags_extraction_errors"} },
    ["dropbox-sign.template_create_embedded_draft"] = { method = "POST", url = "https://api.hellosign.com/v3/template/create_embedded_draft", body = {"files", "file_urls", "allow_ccs", "allow_reassign", "attachments", "cc_roles", "client_id", "editor_options", "field_options", "force_signer_roles", "force_subject_message", "form_field_groups", "form_field_rules", "form_fields_per_document", "merge_fields", "message", "metadata", "show_preview", "show_progress_stepper", "signer_roles", "skip_me_now", "subject", "test_mode", "title", "use_preexisting_fields", "ignore_text_tags_extraction_errors"} },
    ["dropbox-sign.template_delete"] = { method = "POST", url = "https://api.hellosign.com/v3/template/delete/{template_id}", path = {"template_id"} },
    ["dropbox-sign.template_files"] = { method = "GET", url = "https://api.hellosign.com/v3/template/files/{template_id}", path = {"template_id"}, query = {"file_type"} },
    ["dropbox-sign.template_files_as_data_uri"] = { method = "GET", url = "https://api.hellosign.com/v3/template/files_as_data_uri/{template_id}", path = {"template_id"} },
    ["dropbox-sign.template_files_as_file_url"] = { method = "GET", url = "https://api.hellosign.com/v3/template/files_as_file_url/{template_id}", path = {"template_id"}, query = {"force_download"} },
    ["dropbox-sign.template_get"] = { method = "GET", url = "https://api.hellosign.com/v3/template/{template_id}", path = {"template_id"} },
    ["dropbox-sign.template_list"] = { method = "GET", url = "https://api.hellosign.com/v3/template/list", query = {"account_id", "page", "page_size", "query"} },
    ["dropbox-sign.template_remove_user"] = { method = "POST", url = "https://api.hellosign.com/v3/template/remove_user/{template_id}", path = {"template_id"}, body = {"account_id", "email_address"} },
    ["dropbox-sign.template_update_files"] = { method = "POST", url = "https://api.hellosign.com/v3/template/update_files/{template_id}", path = {"template_id"}, body = {"client_id", "files", "file_urls", "message", "subject", "test_mode"} },
    ["dropbox-sign.unclaimed_draft_create"] = { method = "POST", url = "https://api.hellosign.com/v3/unclaimed_draft/create", body = {"files", "file_urls", "allow_decline", "attachments", "cc_email_addresses", "client_id", "custom_fields", "field_options", "form_field_groups", "form_field_rules", "form_fields_per_document", "hide_text_tags", "message", "metadata", "show_progress_stepper", "signers", "signing_options", "signing_redirect_url", "subject", "test_mode", "type", "use_preexisting_fields", "use_text_tags", "ignore_text_tags_extraction_errors", "expires_at"} },
    ["dropbox-sign.unclaimed_draft_create_embedded"] = { method = "POST", url = "https://api.hellosign.com/v3/unclaimed_draft/create_embedded", body = {"files", "file_urls", "allow_ccs", "allow_decline", "allow_reassign", "attachments", "cc_email_addresses", "client_id", "custom_fields", "editor_options", "field_options", "force_signer_page", "force_subject_message", "form_field_groups", "form_field_rules", "form_fields_per_document", "hide_text_tags", "hold_request", "is_for_embedded_signing", "message", "metadata", "requester_email_address", "requesting_redirect_url", "show_preview", "show_progress_stepper", "signers", "signing_options", "signing_redirect_url", "skip_me_now", "subject", "test_mode", "type", "use_preexisting_fields", "use_text_tags", "ignore_text_tags_extraction_errors", "populate_auto_fill_fields", "expires_at"} },
    ["dropbox-sign.unclaimed_draft_create_embedded_with_template"] = { method = "POST", url = "https://api.hellosign.com/v3/unclaimed_draft/create_embedded_with_template", body = {"allow_decline", "allow_reassign", "ccs", "client_id", "custom_fields", "editor_options", "field_options", "files", "file_urls", "force_signer_roles", "force_subject_message", "hold_request", "is_for_embedded_signing", "message", "metadata", "preview_only", "requester_email_address", "requesting_redirect_url", "show_preview", "show_progress_stepper", "signers", "signing_options", "signing_redirect_url", "skip_me_now", "subject", "template_ids", "test_mode", "title", "populate_auto_fill_fields", "allow_ccs"} },
    ["dropbox-sign.unclaimed_draft_edit_and_resend"] = { method = "POST", url = "https://api.hellosign.com/v3/unclaimed_draft/edit_and_resend/{signature_request_id}", path = {"signature_request_id"}, body = {"client_id", "editor_options", "is_for_embedded_signing", "requester_email_address", "requesting_redirect_url", "show_progress_stepper", "signing_redirect_url", "test_mode"} },
  },
}
