-- Ahrefs — every call this API accepts, as data.
--
-- GENERATED from https://docs.ahrefs.com/openapi.json
-- Published on the vendor's own documentation site (https://docs.ahrefs.com).
-- 151 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "ahrefs",
  name = "Ahrefs",
  base = "https://api.ahrefs.com",
  docs = "https://nango.dev/docs/api-integrations/ahrefs",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "AHREFS_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["ahrefs.batch_analysis_batch_analysis"] = { method = "POST", url = "https://api.ahrefs.com/v3/batch-analysis/batch-analysis", body = {"select", "order_by", "targets", "volume_mode", "country", "top_countries", "output"} },
    ["ahrefs.brand_radar_ai_responses"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/ai-responses", query = {"select", "where", "report_id", "brand", "competitors", "data_source", "country", "prompts", "limit", "date", "date_compared", "search_volume_type", "order_by", "output"} },
    ["ahrefs.brand_radar_ai_responses_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/ai-responses", body = {"select", "where", "report_id", "brands", "competitors", "data_source", "country", "prompts", "limit", "date", "date_compared", "search_volume_type", "order_by", "tags_filter", "brand_filter", "volume_range", "changes", "output"} },
    ["ahrefs.brand_radar_citations_history"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/citations-history", body = {"where", "report_id", "brands", "data_source", "country", "prompts", "date_from", "date_to", "search_volume_type", "tags_filter", "output"} },
    ["ahrefs.brand_radar_citations_overview"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/citations-overview", body = {"select", "where", "report_id", "brands", "competitors", "data_source", "country", "prompts", "search_volume_type", "tags_filter", "output"} },
    ["ahrefs.brand_radar_cited_domains"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/cited-domains", query = {"select", "where", "report_id", "brand", "competitors", "data_source", "country", "prompts", "limit", "date", "search_volume_type", "output"} },
    ["ahrefs.brand_radar_cited_domains_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/cited-domains", body = {"select", "where", "report_id", "brands", "competitors", "data_source", "country", "prompts", "limit", "date", "search_volume_type", "tags_filter", "brand_filter", "volume_range", "output"} },
    ["ahrefs.brand_radar_cited_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/cited-pages", query = {"select", "where", "report_id", "brand", "competitors", "data_source", "country", "prompts", "limit", "date", "search_volume_type", "tracked_urls", "output"} },
    ["ahrefs.brand_radar_cited_pages_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/cited-pages", body = {"select", "where", "report_id", "brands", "competitors", "data_source", "country", "prompts", "limit", "date", "search_volume_type", "tracked_urls", "tags_filter", "brand_filter", "volume_range", "output"} },
    ["ahrefs.brand_radar_impressions_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/impressions-history", query = {"where", "report_id", "brand", "data_source", "country", "prompts", "date_from", "date_to", "search_volume_type", "output"} },
    ["ahrefs.brand_radar_impressions_history_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/impressions-history", body = {"where", "report_id", "brands", "data_source", "country", "prompts", "date_from", "date_to", "search_volume_type", "tags_filter", "output"} },
    ["ahrefs.brand_radar_impressions_overview"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/impressions-overview", query = {"select", "where", "report_id", "brand", "competitors", "data_source", "country", "prompts", "search_volume_type", "output"} },
    ["ahrefs.brand_radar_impressions_overview_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/impressions-overview", body = {"select", "where", "report_id", "brands", "competitors", "data_source", "country", "prompts", "search_volume_type", "tags_filter", "output"} },
    ["ahrefs.brand_radar_mentions_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/mentions-history", query = {"where", "report_id", "brand", "data_source", "country", "prompts", "date_from", "date_to", "search_volume_type", "output"} },
    ["ahrefs.brand_radar_mentions_history_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/mentions-history", body = {"where", "report_id", "brands", "data_source", "country", "prompts", "date_from", "date_to", "search_volume_type", "tags_filter", "output"} },
    ["ahrefs.brand_radar_mentions_overview"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/mentions-overview", query = {"select", "where", "report_id", "brand", "competitors", "data_source", "country", "prompts", "search_volume_type", "output"} },
    ["ahrefs.brand_radar_mentions_overview_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/mentions-overview", body = {"select", "where", "report_id", "brands", "competitors", "data_source", "country", "prompts", "search_volume_type", "tags_filter", "output"} },
    ["ahrefs.brand_radar_sov_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/sov-history", query = {"where", "report_id", "brand", "competitors", "data_source", "country", "prompts", "date_from", "date_to", "search_volume_type", "output"} },
    ["ahrefs.brand_radar_sov_history_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/sov-history", body = {"where", "report_id", "brands", "competitors", "data_source", "country", "prompts", "date_from", "date_to", "search_volume_type", "tags_filter", "output"} },
    ["ahrefs.brand_radar_sov_overview"] = { method = "GET", url = "https://api.ahrefs.com/v3/brand-radar/sov-overview", query = {"where", "report_id", "brand", "competitors", "data_source", "country", "prompts", "search_volume_type", "output"} },
    ["ahrefs.brand_radar_sov_overview_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/brand-radar/sov-overview", body = {"where", "report_id", "brands", "competitors", "data_source", "country", "prompts", "search_volume_type", "tags_filter", "output"} },
    ["ahrefs.content_helper_topics"] = { method = "GET", url = "https://api.ahrefs.com/v3/content-helper/topics", query = {"keyword", "country", "top_competitors", "target_url", "output"} },
    ["ahrefs.gsc_anonymous_queries"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/anonymous-queries", query = {"select", "where", "order_by", "limit", "timeout", "project_id", "date_from", "country", "output"} },
    ["ahrefs.gsc_ctr_by_position"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/ctr-by-position", query = {"project_id", "portfolio_id", "date_from", "date_to", "country", "device", "output"} },
    ["ahrefs.gsc_keyword_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/keyword-history", query = {"project_id", "portfolio_id", "date_from", "date_to", "history_grouping", "country", "device", "keywords", "where", "output"} },
    ["ahrefs.gsc_keywords"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/keywords", query = {"project_id", "portfolio_id", "date_from", "date_to", "search_type", "country", "device", "limit", "where", "keyword_list_id", "keyword_lists", "output"} },
    ["ahrefs.gsc_metrics_by_country"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/metrics-by-country", query = {"project_id", "portfolio_id", "date_from", "date_to", "history_grouping", "search_type", "device", "where", "output"} },
    ["ahrefs.gsc_page_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/page-history", query = {"project_id", "portfolio_id", "date_from", "date_to", "history_grouping", "country", "device", "pages", "output"} },
    ["ahrefs.gsc_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/pages", query = {"project_id", "portfolio_id", "date_from", "date_to", "search_type", "country", "device", "limit", "where", "output"} },
    ["ahrefs.gsc_pages_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/pages-history", query = {"project_id", "portfolio_id", "date_from", "date_to", "history_grouping", "search_type", "country", "device", "where", "output"} },
    ["ahrefs.gsc_performance_by_device"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/performance-by-device", query = {"project_id", "portfolio_id", "date_from", "date_to", "search_type", "country", "where", "output"} },
    ["ahrefs.gsc_performance_by_position"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/performance-by-position", query = {"project_id", "portfolio_id", "date_from", "date_to", "search_type", "country", "device", "where", "output"} },
    ["ahrefs.gsc_performance_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/performance-history", query = {"project_id", "portfolio_id", "date_from", "date_to", "history_grouping", "search_type", "country", "device", "where", "output"} },
    ["ahrefs.gsc_positions_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/gsc/positions-history", query = {"project_id", "portfolio_id", "date_from", "date_to", "history_grouping", "search_type", "country", "device", "where", "output"} },
    ["ahrefs.keywords_explorer_matching_terms"] = { method = "GET", url = "https://api.ahrefs.com/v3/keywords-explorer/matching-terms", query = {"select", "where", "order_by", "limit", "timeout", "keyword_list_id", "keywords", "country", "terms", "match_mode", "output"} },
    ["ahrefs.keywords_explorer_overview"] = { method = "GET", url = "https://api.ahrefs.com/v3/keywords-explorer/overview", query = {"select", "where", "order_by", "limit", "timeout", "keyword_list_id", "keywords", "country", "target_position", "target", "mode", "volume_monthly_date_from", "volume_monthly_date_to", "output"} },
    ["ahrefs.keywords_explorer_related_terms"] = { method = "GET", url = "https://api.ahrefs.com/v3/keywords-explorer/related-terms", query = {"select", "where", "order_by", "limit", "timeout", "keyword_list_id", "keywords", "country", "terms", "view_for", "output"} },
    ["ahrefs.keywords_explorer_search_suggestions"] = { method = "GET", url = "https://api.ahrefs.com/v3/keywords-explorer/search-suggestions", query = {"select", "where", "order_by", "limit", "timeout", "keyword_list_id", "keywords", "country", "output"} },
    ["ahrefs.keywords_explorer_volume_by_country"] = { method = "GET", url = "https://api.ahrefs.com/v3/keywords-explorer/volume-by-country", query = {"keyword", "limit", "output"} },
    ["ahrefs.keywords_explorer_volume_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/keywords-explorer/volume-history", query = {"keyword", "country", "date_from", "date_to", "output"} },
    ["ahrefs.management_brand_radar_prompts"] = { method = "GET", url = "https://api.ahrefs.com/v3/management/brand-radar-prompts", query = {"report_id", "output"} },
    ["ahrefs.management_brand_radar_prompts_delete"] = { method = "PUT", url = "https://api.ahrefs.com/v3/management/brand-radar-prompts-delete", query = {"report_id", "output"}, body = {"prompts", "countries"} },
    ["ahrefs.management_brand_radar_prompts_patch"] = { method = "PATCH", url = "https://api.ahrefs.com/v3/management/brand-radar-prompts", query = {"report_id", "output"}, body = {"prompts", "countries", "tags"} },
    ["ahrefs.management_brand_radar_prompts_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/management/brand-radar-prompts", query = {"report_id", "output"}, body = {"prompts", "countries", "tags"} },
    ["ahrefs.management_brand_radar_reports"] = { method = "GET", url = "https://api.ahrefs.com/v3/management/brand-radar-reports", query = {"output"} },
    ["ahrefs.management_brand_radar_reports_patch"] = { method = "PATCH", url = "https://api.ahrefs.com/v3/management/brand-radar-reports", query = {"output"}, body = {"report_id", "prompts_frequency"} },
    ["ahrefs.management_brand_radar_reports_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/management/brand-radar-reports", query = {"output"}, body = {"brand", "competitors", "name", "project_id", "prompts_frequency"} },
    ["ahrefs.management_keyword_list_keywords"] = { method = "GET", url = "https://api.ahrefs.com/v3/management/keyword-list-keywords", query = {"keyword_list_id", "output"} },
    ["ahrefs.management_keyword_list_keywords_delete"] = { method = "PUT", url = "https://api.ahrefs.com/v3/management/keyword-list-keywords-delete", query = {"keyword_list_id", "output"}, body = {"keywords"} },
    ["ahrefs.management_keyword_list_keywords_put"] = { method = "PUT", url = "https://api.ahrefs.com/v3/management/keyword-list-keywords", query = {"keyword_list_id", "output"}, body = {"keywords"} },
    ["ahrefs.management_locations"] = { method = "GET", url = "https://api.ahrefs.com/v3/management/locations", query = {"country_code", "us_state", "output"} },
    ["ahrefs.management_project_competitors"] = { method = "GET", url = "https://api.ahrefs.com/v3/management/project-competitors", query = {"project_id", "output"} },
    ["ahrefs.management_project_competitors_delete"] = { method = "POST", url = "https://api.ahrefs.com/v3/management/project-competitors-delete", query = {"project_id", "output"}, body = {"competitors"} },
    ["ahrefs.management_project_competitors_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/management/project-competitors", query = {"project_id", "output"}, body = {"competitors"} },
    ["ahrefs.management_project_keywords"] = { method = "GET", url = "https://api.ahrefs.com/v3/management/project-keywords", query = {"project_id", "output"} },
    ["ahrefs.management_project_keywords_delete"] = { method = "PUT", url = "https://api.ahrefs.com/v3/management/project-keywords-delete", query = {"project_id", "output"}, body = {"keywords"} },
    ["ahrefs.management_project_keywords_put"] = { method = "PUT", url = "https://api.ahrefs.com/v3/management/project-keywords", query = {"project_id", "output"}, body = {"keywords", "locations"} },
    ["ahrefs.management_project_keywords_tags"] = { method = "PUT", url = "https://api.ahrefs.com/v3/management/project-keywords-tags", body = {"project_id", "keywords", "tags", "update_mode", "output"} },
    ["ahrefs.management_project_keywords_tags_delete"] = { method = "PUT", url = "https://api.ahrefs.com/v3/management/project-keywords-tags-delete", body = {"project_id", "keywords", "tags", "output"} },
    ["ahrefs.management_projects"] = { method = "GET", url = "https://api.ahrefs.com/v3/management/projects", query = {"access", "owned_by", "project_id", "has_keywords", "output"} },
    ["ahrefs.management_projects_delete"] = { method = "DELETE", url = "https://api.ahrefs.com/v3/management/projects", query = {"project_ids", "output"} },
    ["ahrefs.management_projects_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/management/projects", query = {"output"}, body = {"access", "owned_by", "project_name", "mode", "url", "protocol", "folder_id"} },
    ["ahrefs.management_update_project"] = { method = "PATCH", url = "https://api.ahrefs.com/v3/management/update-project", query = {"output"}, body = {"project_id", "folder", "access"} },
    ["ahrefs.public_crawler_ip_ranges"] = { method = "GET", url = "https://api.ahrefs.com/v3/public/crawler-ip-ranges", query = {"output"} },
    ["ahrefs.public_crawler_ips"] = { method = "GET", url = "https://api.ahrefs.com/v3/public/crawler-ips", query = {"output"} },
    ["ahrefs.public_domain_rating_free"] = { method = "GET", url = "https://api.ahrefs.com/v3/public/domain-rating-free", query = {"target", "output"} },
    ["ahrefs.public_domain_rating_free_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/public/domain-rating-free", query = {"output"}, body = {"targets"} },
    ["ahrefs.public_domain_rating_top_domains"] = { method = "GET", url = "https://api.ahrefs.com/v3/public/domain-rating-top-domains", query = {"from", "to", "output"} },
    ["ahrefs.rank_tracker_competitors_domains"] = { method = "GET", url = "https://api.ahrefs.com/v3/rank-tracker/competitors-domains", query = {"select", "where", "order_by", "limit", "timeout", "volume_mode", "project_id", "device", "date", "date_compared", "target_and_tracked_competitors_only", "output"} },
    ["ahrefs.rank_tracker_competitors_overview"] = { method = "GET", url = "https://api.ahrefs.com/v3/rank-tracker/competitors-overview", query = {"select", "where", "order_by", "limit", "timeout", "volume_mode", "project_id", "device", "date", "date_compared", "output"} },
    ["ahrefs.rank_tracker_competitors_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/rank-tracker/competitors-pages", query = {"select", "where", "order_by", "limit", "timeout", "volume_mode", "project_id", "device", "date", "date_compared", "target_and_tracked_competitors_only", "output"} },
    ["ahrefs.rank_tracker_competitors_stats"] = { method = "GET", url = "https://api.ahrefs.com/v3/rank-tracker/competitors-stats", query = {"select", "volume_mode", "project_id", "device", "date", "output"} },
    ["ahrefs.rank_tracker_overview"] = { method = "GET", url = "https://api.ahrefs.com/v3/rank-tracker/overview", query = {"select", "where", "order_by", "limit", "timeout", "volume_mode", "project_id", "device", "date", "date_compared", "output"} },
    ["ahrefs.rank_tracker_serp_overview"] = { method = "GET", url = "https://api.ahrefs.com/v3/rank-tracker/serp-overview", query = {"project_id", "keyword", "language_code", "country", "location_id", "date", "device", "top_positions", "output"} },
    ["ahrefs.serp_overview_serp_overview"] = { method = "GET", url = "https://api.ahrefs.com/v3/serp-overview/serp-overview", query = {"select", "keyword", "country", "date", "top_positions", "type", "output"} },
    ["ahrefs.site_audit_issues"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-audit/issues", query = {"project_id", "date", "date_compared", "output"} },
    ["ahrefs.site_audit_page_content"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-audit/page-content", query = {"select", "project_id", "target_url", "date", "output"} },
    ["ahrefs.site_audit_page_explorer"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-audit/page-explorer", query = {"select", "where", "order_by", "project_id", "date", "date_compared", "issue_id", "filter_mode", "offset", "limit", "timeout", "output"} },
    ["ahrefs.site_audit_projects"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-audit/projects", query = {"project_id", "date", "project_name", "project_url", "output"} },
    ["ahrefs.site_explorer_ai_responses_count"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/ai-responses-count", query = {"select", "date", "mode", "target", "protocol", "country", "output"} },
    ["ahrefs.site_explorer_all_backlinks"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/all-backlinks", query = {"select", "where", "order_by", "limit", "timeout", "aggregation", "history", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_anchors"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/anchors", query = {"select", "where", "order_by", "limit", "timeout", "history", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_backlinks_stats"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/backlinks-stats", query = {"date", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_broken_backlinks"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/broken-backlinks", query = {"select", "where", "order_by", "limit", "timeout", "aggregation", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_crawled_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/crawled-pages", query = {"select", "order_by", "where", "target", "mode", "protocol", "limit", "output"} },
    ["ahrefs.site_explorer_domain_rating"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/domain-rating", query = {"date", "target", "output"} },
    ["ahrefs.site_explorer_domain_rating_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/domain-rating-history", query = {"target", "date_from", "date_to", "history_grouping", "output"} },
    ["ahrefs.site_explorer_keywords_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/keywords-history", query = {"select", "mode", "target", "protocol", "country", "date_from", "date_to", "history_grouping", "output"} },
    ["ahrefs.site_explorer_linked_anchors_external"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/linked-anchors-external", query = {"select", "where", "order_by", "limit", "timeout", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_linked_anchors_internal"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/linked-anchors-internal", query = {"select", "where", "order_by", "limit", "timeout", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_linkeddomains"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/linkeddomains", query = {"select", "where", "order_by", "limit", "timeout", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_metrics"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/metrics", query = {"date", "mode", "target", "protocol", "country", "volume_mode", "traffic_mode", "output"} },
    ["ahrefs.site_explorer_metrics_by_country"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/metrics-by-country", query = {"select", "limit", "date", "mode", "target", "protocol", "volume_mode", "traffic_mode", "output"} },
    ["ahrefs.site_explorer_metrics_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/metrics-history", query = {"select", "mode", "target", "protocol", "country", "date_from", "date_to", "history_grouping", "volume_mode", "traffic_mode", "output"} },
    ["ahrefs.site_explorer_organic_competitors"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/organic-competitors", query = {"select", "where", "order_by", "limit", "timeout", "volume_mode", "traffic_mode", "date", "date_compared", "country", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_organic_keywords"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/organic-keywords", query = {"select", "where", "order_by", "limit", "timeout", "volume_mode", "traffic_mode", "date", "date_compared", "country", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_outlinks_stats"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/outlinks-stats", query = {"target", "mode", "protocol", "output"} },
    ["ahrefs.site_explorer_pages_by_backlinks"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/pages-by-backlinks", query = {"select", "where", "order_by", "limit", "timeout", "history", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_pages_by_internal_links"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/pages-by-internal-links", query = {"select", "where", "order_by", "limit", "timeout", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_pages_by_traffic"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/pages-by-traffic", query = {"target", "protocol", "mode", "volume_mode", "traffic_mode", "country", "output"} },
    ["ahrefs.site_explorer_pages_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/pages-history", query = {"mode", "target", "protocol", "country", "date_from", "date_to", "history_grouping", "page_positions", "output"} },
    ["ahrefs.site_explorer_paid_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/paid-pages", query = {"select", "where", "order_by", "limit", "timeout", "volume_mode", "date", "date_compared", "country", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_refdomains"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/refdomains", query = {"select", "where", "order_by", "limit", "timeout", "history", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_refdomains_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/refdomains-history", query = {"mode", "target", "protocol", "date_from", "date_to", "history_grouping", "output"} },
    ["ahrefs.site_explorer_top_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/top-pages", query = {"select", "where", "order_by", "limit", "timeout", "volume_mode", "traffic_mode", "date", "date_compared", "country", "mode", "target", "protocol", "output"} },
    ["ahrefs.site_explorer_total_search_volume_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/total-search-volume-history", query = {"mode", "target", "protocol", "country", "date_from", "date_to", "history_grouping", "top_positions", "volume_mode", "output"} },
    ["ahrefs.site_explorer_url_rating_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/site-explorer/url-rating-history", query = {"target", "date_from", "date_to", "history_grouping", "output"} },
    ["ahrefs.social_media_activity_history"] = { method = "GET", url = "https://api.ahrefs.com/v3/social-media/activity-history", query = {"post_id", "output"} },
    ["ahrefs.social_media_authors"] = { method = "GET", url = "https://api.ahrefs.com/v3/social-media/authors", query = {"output"} },
    ["ahrefs.social_media_channel_metrics"] = { method = "GET", url = "https://api.ahrefs.com/v3/social-media/channel-metrics", query = {"channel_id", "date_from", "date_to", "output"} },
    ["ahrefs.social_media_channels"] = { method = "GET", url = "https://api.ahrefs.com/v3/social-media/channels", query = {"output"} },
    ["ahrefs.social_media_post"] = { method = "POST", url = "https://api.ahrefs.com/v3/social-media/post", query = {"output"}, body = {"channel_ids", "text_content", "timing", "scheduled_at", "auto_comment"} },
    ["ahrefs.social_media_post_delete"] = { method = "DELETE", url = "https://api.ahrefs.com/v3/social-media/post", query = {"output"}, body = {"post_id"} },
    ["ahrefs.social_media_post_metrics"] = { method = "GET", url = "https://api.ahrefs.com/v3/social-media/post-metrics", query = {"external_post_id", "channel_id", "date_from", "date_to", "output"} },
    ["ahrefs.social_media_post_patch"] = { method = "PATCH", url = "https://api.ahrefs.com/v3/social-media/post", query = {"output"}, body = {"post_id", "channel_ids", "text_content", "timing", "scheduled_at", "auto_comment"} },
    ["ahrefs.social_media_posts"] = { method = "GET", url = "https://api.ahrefs.com/v3/social-media/posts", query = {"status", "channel_ids", "author_ids", "search_query", "date_from", "date_to", "order_by", "order_direction", "limit", "offset", "output"} },
    ["ahrefs.subscription_info_limits_and_usage"] = { method = "GET", url = "https://api.ahrefs.com/v3/subscription-info/limits-and-usage", query = {"output"} },
    ["ahrefs.web_analytics_browser_versions"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/browser-versions", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_browser_versions_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/browser-versions-chart", query = {"browser_version_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_browsers"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/browsers", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_browsers_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/browsers-chart", query = {"browser_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/chart", query = {"where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_cities"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/cities", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_cities_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/cities-chart", query = {"cities_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_continents"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/continents", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_continents_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/continents-chart", query = {"continents_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_countries"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/countries", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_countries_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/countries-chart", query = {"countries_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_devices"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/devices", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_devices_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/devices-chart", query = {"devices_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_entry_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/entry-pages", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_entry_pages_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/entry-pages-chart", query = {"entry_pages_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_exit_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/exit-pages", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_exit_pages_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/exit-pages-chart", query = {"exit_pages_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_languages"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/languages", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_languages_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/languages-chart", query = {"browser_language_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_operating_systems"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/operating-systems", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_operating_systems_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/operating-systems-chart", query = {"os_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_operating_systems_versions"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/operating-systems-versions", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_operating_systems_versions_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/operating-systems-versions-chart", query = {"os_versions_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_referrers"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/referrers", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_referrers_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/referrers-chart", query = {"source_referers_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_source_channels"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/source-channels", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_source_channels_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/source-channels-chart", query = {"source_channels_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_sources"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/sources", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_sources_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/sources-chart", query = {"sources_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_stats"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/stats", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_top_pages"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/top-pages", query = {"limit", "order_by", "where", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_top_pages_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/top-pages-chart", query = {"pages_to_chart", "where", "granularity", "to", "from", "project_id", "output"} },
    ["ahrefs.web_analytics_utm_params"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/utm-params", query = {"limit", "order_by", "where", "to", "from", "utm_param", "project_id", "output"} },
    ["ahrefs.web_analytics_utm_params_chart"] = { method = "GET", url = "https://api.ahrefs.com/v3/web-analytics/utm-params-chart", query = {"utm_params_to_chart", "where", "granularity", "to", "from", "utm_param", "project_id", "output"} },
  },
}
