-- Hail — every call this API accepts, as data.
--
-- GENERATED from https://api.hail.so/openapi.json
-- Published on the vendor's own documentation site (https://api.hail.so).
-- 54 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "hail-mcp",
  name = "Hail",
  base = "https://mcp.hail.so",
  docs = "https://nango.dev/docs/api-integrations/hail-mcp",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "HAIL_MCP_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["hail-mcp.acquire_number_v1_numbers_post"] = { method = "POST", url = "https://mcp.hail.so/v1/numbers", header = {"Idempotency-Key"}, body = {"country_code", "number_type"} },
    ["hail-mcp.activate_provider"] = { method = "POST", url = "https://mcp.hail.so/v1/providers/{layer}/activate", path = {"layer"}, body = {"provider"} },
    ["hail-mcp.check_domain_v1_email_domains_check_domain_get"] = { method = "GET", url = "https://mcp.hail.so/v1/email-domains/check-domain", query = {"domain"} },
    ["hail-mcp.create_call_v1_calls_post"] = { method = "POST", url = "https://mcp.hail.so/v1/calls", header = {"Idempotency-Key"}, body = {"recipient_consent", "consent_source", "consent_obtained_at", "message_type", "to", "from", "system_prompt", "llm", "first_message", "ai_disclosure", "voice_config", "conversation_id", "metadata", "tools"} },
    ["hail-mcp.create_contact_v1_contacts_post"] = { method = "POST", url = "https://mcp.hail.so/v1/contacts", body = {"name", "phone_e164", "email"} },
    ["hail-mcp.create_email_domain_v1_email_domains_post"] = { method = "POST", url = "https://mcp.hail.so/v1/email-domains", body = {"kind", "domain", "local_prefix_user", "local_prefix_org"} },
    ["hail-mcp.create_email_v1_emails_post"] = { method = "POST", url = "https://mcp.hail.so/v1/emails", header = {"Idempotency-Key"}, body = {"recipient_consent", "consent_source", "consent_obtained_at", "message_type", "from", "from_name", "to", "cc", "bcc", "reply_to", "subject", "body_text", "body_html", "conversation_id", "metadata", "attachment_ids"} },
    ["hail-mcp.create_sms_v1_sms_post"] = { method = "POST", url = "https://mcp.hail.so/v1/sms", header = {"Idempotency-Key"}, body = {"recipient_consent", "consent_source", "consent_obtained_at", "message_type", "to", "from", "body", "metadata"} },
    ["hail-mcp.create_subscription_v1_webhooks_post"] = { method = "POST", url = "https://mcp.hail.so/v1/webhooks", body = {"target_url", "event_types"} },
    ["hail-mcp.delete_contact_v1_contacts_contact_id_delete"] = { method = "DELETE", url = "https://mcp.hail.so/v1/contacts/{contact_id}", path = {"contact_id"} },
    ["hail-mcp.delete_email_domain_v1_email_domains_domain_id_delete"] = { method = "DELETE", url = "https://mcp.hail.so/v1/email-domains/{domain_id}", path = {"domain_id"} },
    ["hail-mcp.delete_member_phone_v1_members_user_id_phone_delete"] = { method = "DELETE", url = "https://mcp.hail.so/v1/members/{user_id}/phone", path = {"user_id"} },
    ["hail-mcp.delete_provider"] = { method = "DELETE", url = "https://mcp.hail.so/v1/providers/{layer}/{provider}", path = {"layer", "provider"} },
    ["hail-mcp.delete_sms_suppression_v1_sms_suppressions_number_delete"] = { method = "DELETE", url = "https://mcp.hail.so/v1/sms/suppressions/{number}", path = {"number"} },
    ["hail-mcp.delete_subscription_v1_webhooks_sub_id_delete"] = { method = "DELETE", url = "https://mcp.hail.so/v1/webhooks/{sub_id}", path = {"sub_id"} },
    ["hail-mcp.dns_check_email_domain_v1_email_domains_domain_id_dns_check_get"] = { method = "GET", url = "https://mcp.hail.so/v1/email-domains/{domain_id}/dns-check", path = {"domain_id"} },
    ["hail-mcp.enable_sms_v1_numbers_number_id_enable_sms_post"] = { method = "POST", url = "https://mcp.hail.so/v1/numbers/{number_id}/enable-sms", path = {"number_id"} },
    ["hail-mcp.get_call_v1_calls_call_id_get"] = { method = "GET", url = "https://mcp.hail.so/v1/calls/{call_id}", path = {"call_id"} },
    ["hail-mcp.get_email_attachment_v1_emails_email_id_attachments_attachment_id_get"] = { method = "GET", url = "https://mcp.hail.so/v1/emails/{email_id}/attachments/{attachment_id}", path = {"email_id", "attachment_id"} },
    ["hail-mcp.get_email_domain_v1_email_domains_domain_id_get"] = { method = "GET", url = "https://mcp.hail.so/v1/email-domains/{domain_id}", path = {"domain_id"} },
    ["hail-mcp.get_email_raw_v1_emails_email_id_raw_get"] = { method = "GET", url = "https://mcp.hail.so/v1/emails/{email_id}/raw", path = {"email_id"} },
    ["hail-mcp.get_email_stats_v1_emails_stats_get"] = { method = "GET", url = "https://mcp.hail.so/v1/emails/stats", query = {"from", "to", "bucket"} },
    ["hail-mcp.get_email_v1_emails_email_id_get"] = { method = "GET", url = "https://mcp.hail.so/v1/emails/{email_id}", path = {"email_id"} },
    ["hail-mcp.get_number_v1_numbers_number_id_get"] = { method = "GET", url = "https://mcp.hail.so/v1/numbers/{number_id}", path = {"number_id"} },
    ["hail-mcp.get_sender_id_v1_sms_sender_id_get"] = { method = "GET", url = "https://mcp.hail.so/v1/sms/sender-id" },
    ["hail-mcp.get_sms_v1_sms_sms_id_get"] = { method = "GET", url = "https://mcp.hail.so/v1/sms/{sms_id}", path = {"sms_id"} },
    ["hail-mcp.get_subscription_v1_webhooks_sub_id_get"] = { method = "GET", url = "https://mcp.hail.so/v1/webhooks/{sub_id}", path = {"sub_id"} },
    ["hail-mcp.get_whoami_v1_whoami_get"] = { method = "GET", url = "https://mcp.hail.so/v1/whoami" },
    ["hail-mcp.healthz_healthz_get"] = { method = "GET", url = "https://mcp.hail.so/healthz" },
    ["hail-mcp.list_calls_v1_calls_get"] = { method = "GET", url = "https://mcp.hail.so/v1/calls", query = {"cursor", "limit", "status", "to"} },
    ["hail-mcp.list_contacts_v1_contacts_get"] = { method = "GET", url = "https://mcp.hail.so/v1/contacts", query = {"q", "cursor", "limit"} },
    ["hail-mcp.list_deliveries_v1_webhooks_sub_id_deliveries_get"] = { method = "GET", url = "https://mcp.hail.so/v1/webhooks/{sub_id}/deliveries", path = {"sub_id"}, query = {"cursor", "limit"} },
    ["hail-mcp.list_email_domains_v1_email_domains_get"] = { method = "GET", url = "https://mcp.hail.so/v1/email-domains", query = {"cursor", "limit"} },
    ["hail-mcp.list_email_events_v1_emails_email_id_events_get"] = { method = "GET", url = "https://mcp.hail.so/v1/emails/{email_id}/events", path = {"email_id"}, query = {"cursor", "limit"} },
    ["hail-mcp.list_emails_v1_emails_get"] = { method = "GET", url = "https://mcp.hail.so/v1/emails", query = {"cursor", "limit", "status", "direction"} },
    ["hail-mcp.list_events_v1_events_get"] = { method = "GET", url = "https://mcp.hail.so/v1/events", query = {"cursor", "limit", "id", "kind"} },
    ["hail-mcp.list_numbers_v1_numbers_get"] = { method = "GET", url = "https://mcp.hail.so/v1/numbers", query = {"cursor", "limit"} },
    ["hail-mcp.list_providers"] = { method = "GET", url = "https://mcp.hail.so/v1/providers" },
    ["hail-mcp.list_sms_suppressions_v1_sms_suppressions_get"] = { method = "GET", url = "https://mcp.hail.so/v1/sms/suppressions", query = {"cursor", "limit"} },
    ["hail-mcp.list_sms_v1_sms_get"] = { method = "GET", url = "https://mcp.hail.so/v1/sms", query = {"cursor", "limit", "status", "to"} },
    ["hail-mcp.list_subscriptions_v1_webhooks_get"] = { method = "GET", url = "https://mcp.hail.so/v1/webhooks", query = {"cursor", "limit"} },
    ["hail-mcp.patch_contact_v1_contacts_contact_id_patch"] = { method = "PATCH", url = "https://mcp.hail.so/v1/contacts/{contact_id}", path = {"contact_id"}, body = {"name", "phone_e164", "email"} },
    ["hail-mcp.patch_email_domain_v1_email_domains_domain_id_patch"] = { method = "PATCH", url = "https://mcp.hail.so/v1/email-domains/{domain_id}", path = {"domain_id"}, body = {"local_prefix_user", "local_prefix_org", "inbound_enabled", "forward_to", "forward_rate_per_hour"} },
    ["hail-mcp.patch_sender_id_v1_sms_sender_id_patch"] = { method = "PATCH", url = "https://mcp.hail.so/v1/sms/sender-id", body = {"custom_sender_id"} },
    ["hail-mcp.patch_subscription_v1_webhooks_sub_id_patch"] = { method = "PATCH", url = "https://mcp.hail.so/v1/webhooks/{sub_id}", path = {"sub_id"}, body = {"target_url", "event_types", "status"} },
    ["hail-mcp.put_member_phone_v1_members_user_id_phone_put"] = { method = "PUT", url = "https://mcp.hail.so/v1/members/{user_id}/phone", path = {"user_id"}, body = {"phone_e164"} },
    ["hail-mcp.redeliver_v1_webhooks_sub_id_deliveries_delivery_id_redeliver_post"] = { method = "POST", url = "https://mcp.hail.so/v1/webhooks/{sub_id}/deliveries/{delivery_id}/redeliver", path = {"sub_id", "delivery_id"} },
    ["hail-mcp.release_number_v1_numbers_number_id_delete"] = { method = "DELETE", url = "https://mcp.hail.so/v1/numbers/{number_id}", path = {"number_id"} },
    ["hail-mcp.rotate_secret_v1_webhooks_sub_id_rotate_secret_post"] = { method = "POST", url = "https://mcp.hail.so/v1/webhooks/{sub_id}/rotate-secret", path = {"sub_id"} },
    ["hail-mcp.unsubscribe_v1_unsubscribe_get"] = { method = "GET", url = "https://mcp.hail.so/v1/unsubscribe" },
    ["hail-mcp.upload_email_attachment"] = { method = "POST", url = "https://mcp.hail.so/v1/email-attachments", body = {"file"} },
    ["hail-mcp.upsert_provider"] = { method = "PUT", url = "https://mcp.hail.so/v1/providers/{layer}", path = {"layer"}, body = {"provider", "params", "fallback_enabled"} },
    ["hail-mcp.validate_provider"] = { method = "POST", url = "https://mcp.hail.so/v1/providers/{layer}/validate", path = {"layer"}, body = {"provider", "params"} },
    ["hail-mcp.verify_email_domain_v1_email_domains_domain_id_verify_post"] = { method = "POST", url = "https://mcp.hail.so/v1/email-domains/{domain_id}/verify", path = {"domain_id"} },
  },
}
