-- Clerk — every call this API accepts, as data.
--
-- GENERATED from https://clerk.com/openapi.json
-- Published on the vendor's own documentation site (https://clerk.com).
-- 236 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "clerk",
  name = "Clerk",
  base = "https://api.clerk.com",
  docs = "https://nango.dev/docs/integrations/all/clerk",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "CLERK_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["clerk.add_domain"] = { method = "POST", url = "https://api.clerk.com/v1/domains", body = {"name", "is_satellite", "proxy_url"} },
    ["clerk.add_roles_to_role_set"] = { method = "POST", url = "https://api.clerk.com/v1/role_sets/{role_set_key_or_id}/roles", path = {"role_set_key_or_id"}, body = {"role_keys", "default_role_key", "creator_role_key"} },
    ["clerk.adjust_organization_billing_credit_balance"] = { method = "POST", url = "https://api.clerk.com/v1/organizations/{organization_id}/billing/credits", path = {"organization_id"}, body = {"amount", "action", "currency", "idempotency_key", "note"} },
    ["clerk.adjust_user_billing_credit_balance"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/billing/credits", path = {"user_id"}, body = {"amount", "action", "currency", "idempotency_key", "note"} },
    ["clerk.apply_billing_subscription_item_discount"] = { method = "POST", url = "https://api.clerk.com/v1/billing/subscription_items/{subscription_item_id}/discounts", path = {"subscription_item_id"}, body = {"discount_id"} },
    ["clerk.assign_permission_to_organization_role"] = { method = "POST", url = "https://api.clerk.com/v1/organization_roles/{organization_role_id}/permissions/{permission_id}", path = {"organization_role_id", "permission_id"} },
    ["clerk.attempt_email_address_verification"] = { method = "POST", url = "https://api.clerk.com/v1/email_addresses/{email_address_id}/attempt_verification", path = {"email_address_id"}, body = {"verification_id", "code"} },
    ["clerk.attempt_phone_number_verification"] = { method = "POST", url = "https://api.clerk.com/v1/phone_numbers/{phone_number_id}/attempt_verification", path = {"phone_number_id"}, body = {"verification_id", "code"} },
    ["clerk.ban_user"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/ban", path = {"user_id"} },
    ["clerk.cancel_commerce_subscription_item"] = { method = "DELETE", url = "https://api.clerk.com/v1/billing/subscription_items/{subscription_item_id}", path = {"subscription_item_id"}, query = {"end_now"} },
    ["clerk.change_production_instance_domain"] = { method = "POST", url = "https://api.clerk.com/v1/instance/change_domain", body = {"home_url", "is_secondary"} },
    ["clerk.create_actor_token"] = { method = "POST", url = "https://api.clerk.com/v1/actor_tokens", body = {"user_id", "actor", "expires_in_seconds", "session_max_duration_in_seconds"} },
    ["clerk.create_admin_portal_link_token"] = { method = "POST", url = "https://api.clerk.com/v1/admin_portal_link_tokens", body = {"organization_id", "it_contact_id", "scopes", "seconds_until_expiration"} },
    ["clerk.create_agent_task"] = { method = "POST", url = "https://api.clerk.com/v1/agents/tasks", body = {"on_behalf_of", "permissions", "agent_name", "task_description", "redirect_url", "session_max_duration_in_seconds"} },
    ["clerk.create_allowlist_identifier"] = { method = "POST", url = "https://api.clerk.com/v1/allowlist_identifiers", body = {"identifier", "notify"} },
    ["clerk.create_api_key"] = { method = "POST", url = "https://api.clerk.com/v1/api_keys", body = {"type", "name", "description", "subject", "claims", "scopes", "created_by", "seconds_until_expiration"} },
    ["clerk.create_billing_price"] = { method = "POST", url = "https://api.clerk.com/v1/billing/prices", body = {"plan_id", "currency", "amount", "annual_monthly_amount", "description", "supported_billing_periods"} },
    ["clerk.create_billing_price_transition"] = { method = "POST", url = "https://api.clerk.com/v1/billing/subscription_items/{subscription_item_id}/price_transition", path = {"subscription_item_id"}, body = {"from_price_id", "to_price_id"} },
    ["clerk.create_blocklist_identifier"] = { method = "POST", url = "https://api.clerk.com/v1/blocklist_identifiers", body = {"identifier"} },
    ["clerk.create_bulk_invitations"] = { method = "POST", url = "https://api.clerk.com/v1/invitations/bulk" },
    ["clerk.create_bulk_waitlist_entries"] = { method = "POST", url = "https://api.clerk.com/v1/waitlist_entries/bulk" },
    ["clerk.create_directory"] = { method = "POST", url = "https://api.clerk.com/v1/directories", body = {"enterprise_connection_id", "name", "provider", "group_role_mappings"} },
    ["clerk.create_directory_group_role_mapping"] = { method = "POST", url = "https://api.clerk.com/v1/directories/{directory_id}/group_role_mappings", path = {"directory_id"}, body = {"directory_group_id", "scim_group_id", "role_id", "precedence"} },
    ["clerk.create_email_address"] = { method = "POST", url = "https://api.clerk.com/v1/email_addresses", body = {"user_id", "email_address", "verified", "primary", "notify_primary_email_address_changed"} },
    ["clerk.create_enterprise_connection"] = { method = "POST", url = "https://api.clerk.com/v1/enterprise_connections", body = {"name", "provider", "domains", "organization_id", "allow_organization_account_linking", "active", "saml", "oidc", "custom_attributes"} },
    ["clerk.create_enterprise_connection_test_run"] = { method = "POST", url = "https://api.clerk.com/v1/enterprise_connections/{enterprise_connection_id}/test_runs", path = {"enterprise_connection_id"} },
    ["clerk.create_invitation"] = { method = "POST", url = "https://api.clerk.com/v1/invitations", body = {"email_address", "public_metadata", "redirect_url", "notify", "ignore_existing", "expires_in_days", "template_slug"} },
    ["clerk.create_jwttemplate"] = { method = "POST", url = "https://api.clerk.com/v1/jwt_templates", body = {"name", "claims", "lifetime", "allowed_clock_skew", "custom_signing_key", "signing_algorithm", "signing_key"} },
    ["clerk.create_m2_mtoken"] = { method = "POST", url = "https://api.clerk.com/v1/m2m_tokens", body = {"token_format", "seconds_until_expiration", "claims", "min_remaining_ttl_seconds"} },
    ["clerk.create_machine"] = { method = "POST", url = "https://api.clerk.com/v1/machines", body = {"name", "scoped_machines", "default_token_ttl"} },
    ["clerk.create_machine_scope"] = { method = "POST", url = "https://api.clerk.com/v1/machines/{machine_id}/scopes", path = {"machine_id"}, body = {"to_machine_id"} },
    ["clerk.create_oauth_application"] = { method = "POST", url = "https://api.clerk.com/v1/oauth_applications", body = {"name", "redirect_uris", "callback_url", "scopes", "consent_screen_enabled", "pkce_required", "device_authorization_grant_enabled", "public"} },
    ["clerk.create_organization"] = { method = "POST", url = "https://api.clerk.com/v1/organizations", body = {"name", "created_by", "private_metadata", "public_metadata", "slug", "max_allowed_memberships", "created_at", "role_set_key"} },
    ["clerk.create_organization_domain"] = { method = "POST", url = "https://api.clerk.com/v1/organizations/{organization_id}/domains", path = {"organization_id"}, body = {"name", "enrollment_mode", "verified"} },
    ["clerk.create_organization_invitation"] = { method = "POST", url = "https://api.clerk.com/v1/organizations/{organization_id}/invitations", path = {"organization_id"}, body = {"email_address", "inviter_user_id", "role", "public_metadata", "private_metadata", "redirect_url", "expires_in_days", "notify"} },
    ["clerk.create_organization_invitation_bulk"] = { method = "POST", url = "https://api.clerk.com/v1/organizations/{organization_id}/invitations/bulk", path = {"organization_id"} },
    ["clerk.create_organization_membership"] = { method = "POST", url = "https://api.clerk.com/v1/organizations/{organization_id}/memberships", path = {"organization_id"}, body = {"user_id", "role", "public_metadata", "private_metadata"} },
    ["clerk.create_organization_permission"] = { method = "POST", url = "https://api.clerk.com/v1/organization_permissions", body = {"name", "description"} },
    ["clerk.create_organization_role"] = { method = "POST", url = "https://api.clerk.com/v1/organization_roles", body = {"name", "description", "permissions", "include_in_initial_role_set"} },
    ["clerk.create_phone_number"] = { method = "POST", url = "https://api.clerk.com/v1/phone_numbers", body = {"user_id", "phone_number", "verified", "primary", "reserved_for_second_factor"} },
    ["clerk.create_redirect_url"] = { method = "POST", url = "https://api.clerk.com/v1/redirect_urls", body = {"url"} },
    ["clerk.create_role_set"] = { method = "POST", url = "https://api.clerk.com/v1/role_sets", body = {"name", "description", "default_role_key", "creator_role_key", "type", "roles"} },
    ["clerk.create_scimdirectory"] = { method = "POST", url = "https://api.clerk.com/v1/scim_directories", body = {"enterprise_connection_id", "name", "provider", "group_role_mappings"} },
    ["clerk.create_scimgroup_role_mapping"] = { method = "POST", url = "https://api.clerk.com/v1/scim_directories/{scim_directory_id}/group_role_mappings", path = {"scim_directory_id"}, body = {"scim_group_id", "role_id", "precedence"} },
    ["clerk.create_session"] = { method = "POST", url = "https://api.clerk.com/v1/sessions", body = {"user_id", "active_organization_id"} },
    ["clerk.create_session_token"] = { method = "POST", url = "https://api.clerk.com/v1/sessions/{session_id}/tokens", path = {"session_id"}, body = {"expires_in_seconds"} },
    ["clerk.create_session_token_from_template"] = { method = "POST", url = "https://api.clerk.com/v1/sessions/{session_id}/tokens/{template_name}", path = {"session_id", "template_name"}, body = {"expires_in_seconds"} },
    ["clerk.create_sign_in_token"] = { method = "POST", url = "https://api.clerk.com/v1/sign_in_tokens", body = {"user_id", "org_id", "expires_in_seconds"} },
    ["clerk.create_svix_app"] = { method = "POST", url = "https://api.clerk.com/v1/webhooks/svix" },
    ["clerk.create_testing_token"] = { method = "POST", url = "https://api.clerk.com/v1/testing_tokens" },
    ["clerk.create_user"] = { method = "POST", url = "https://api.clerk.com/v1/users", body = {"external_id", "first_name", "last_name", "locale", "email_address", "email_address_identification_status", "phone_number", "phone_number_identification_status", "web3_wallet", "username", "password", "password_digest", "password_hasher", "skip_password_checks", "skip_password_requirement", "skip_restriction_checks", "totp_secret", "backup_codes", "public_metadata", "private_metadata", "unsafe_metadata", "delete_self_enabled", "legal_accepted_at", "skip_legal_checks", "skip_user_requirement", "create_organization_enabled", "create_organizations_limit", "created_at", "bypass_client_trust", "banned", "locked"} },
    ["clerk.create_waitlist_entry"] = { method = "POST", url = "https://api.clerk.com/v1/waitlist_entries", body = {"email_address", "notify"} },
    ["clerk.delete_allowlist_identifier"] = { method = "DELETE", url = "https://api.clerk.com/v1/allowlist_identifiers/{identifier_id}", path = {"identifier_id"} },
    ["clerk.delete_api_key"] = { method = "DELETE", url = "https://api.clerk.com/v1/api_keys/{apiKeyID}", path = {"apiKeyID"} },
    ["clerk.delete_backup_code"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}/backup_code", path = {"user_id"} },
    ["clerk.delete_blocklist_identifier"] = { method = "DELETE", url = "https://api.clerk.com/v1/blocklist_identifiers/{identifier_id}", path = {"identifier_id"} },
    ["clerk.delete_directory"] = { method = "DELETE", url = "https://api.clerk.com/v1/directories/{directory_id}", path = {"directory_id"} },
    ["clerk.delete_directory_group_role_mapping"] = { method = "DELETE", url = "https://api.clerk.com/v1/directories/{directory_id}/group_role_mappings/{mapping_id}", path = {"directory_id", "mapping_id"} },
    ["clerk.delete_domain"] = { method = "DELETE", url = "https://api.clerk.com/v1/domains/{domain_id}", path = {"domain_id"} },
    ["clerk.delete_email_address"] = { method = "DELETE", url = "https://api.clerk.com/v1/email_addresses/{email_address_id}", path = {"email_address_id"} },
    ["clerk.delete_enterprise_connection"] = { method = "DELETE", url = "https://api.clerk.com/v1/enterprise_connections/{enterprise_connection_id}", path = {"enterprise_connection_id"} },
    ["clerk.delete_external_account"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}/external_accounts/{external_account_id}", path = {"user_id", "external_account_id"} },
    ["clerk.delete_jwttemplate"] = { method = "DELETE", url = "https://api.clerk.com/v1/jwt_templates/{template_id}", path = {"template_id"} },
    ["clerk.delete_machine"] = { method = "DELETE", url = "https://api.clerk.com/v1/machines/{machine_id}", path = {"machine_id"} },
    ["clerk.delete_machine_scope"] = { method = "DELETE", url = "https://api.clerk.com/v1/machines/{machine_id}/scopes/{other_machine_id}", path = {"machine_id", "other_machine_id"} },
    ["clerk.delete_oauth_application"] = { method = "DELETE", url = "https://api.clerk.com/v1/oauth_applications/{oauth_application_id}", path = {"oauth_application_id"} },
    ["clerk.delete_organization"] = { method = "DELETE", url = "https://api.clerk.com/v1/organizations/{organization_id}", path = {"organization_id"} },
    ["clerk.delete_organization_domain"] = { method = "DELETE", url = "https://api.clerk.com/v1/organizations/{organization_id}/domains/{domain_id}", path = {"organization_id", "domain_id"} },
    ["clerk.delete_organization_logo"] = { method = "DELETE", url = "https://api.clerk.com/v1/organizations/{organization_id}/logo", path = {"organization_id"} },
    ["clerk.delete_organization_membership"] = { method = "DELETE", url = "https://api.clerk.com/v1/organizations/{organization_id}/memberships/{user_id}", path = {"organization_id", "user_id"} },
    ["clerk.delete_organization_permission"] = { method = "DELETE", url = "https://api.clerk.com/v1/organization_permissions/{permission_id}", path = {"permission_id"} },
    ["clerk.delete_organization_role"] = { method = "DELETE", url = "https://api.clerk.com/v1/organization_roles/{organization_role_id}", path = {"organization_role_id"} },
    ["clerk.delete_phone_number"] = { method = "DELETE", url = "https://api.clerk.com/v1/phone_numbers/{phone_number_id}", path = {"phone_number_id"} },
    ["clerk.delete_redirect_url"] = { method = "DELETE", url = "https://api.clerk.com/v1/redirect_urls/{id}", path = {"id"} },
    ["clerk.delete_scimdirectory"] = { method = "DELETE", url = "https://api.clerk.com/v1/scim_directories/{scim_directory_id}", path = {"scim_directory_id"} },
    ["clerk.delete_scimgroup_role_mapping"] = { method = "DELETE", url = "https://api.clerk.com/v1/scim_directories/{scim_directory_id}/group_role_mappings/{mapping_id}", path = {"scim_directory_id", "mapping_id"} },
    ["clerk.delete_svix_app"] = { method = "DELETE", url = "https://api.clerk.com/v1/webhooks/svix" },
    ["clerk.delete_totp"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}/totp", path = {"user_id"} },
    ["clerk.delete_user"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}", path = {"user_id"} },
    ["clerk.delete_user_profile_image"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}/profile_image", path = {"user_id"} },
    ["clerk.delete_waitlist_entry"] = { method = "DELETE", url = "https://api.clerk.com/v1/waitlist_entries/{waitlist_entry_id}", path = {"waitlist_entry_id"} },
    ["clerk.disable_mfa"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}/mfa", path = {"user_id"} },
    ["clerk.extend_billing_subscription_item_free_trial"] = { method = "POST", url = "https://api.clerk.com/v1/billing/subscription_items/{subscription_item_id}/extend_free_trial", path = {"subscription_item_id"}, body = {"extend_to"} },
    ["clerk.generate_svix_auth_url"] = { method = "POST", url = "https://api.clerk.com/v1/webhooks/svix_url" },
    ["clerk.get_api_key"] = { method = "GET", url = "https://api.clerk.com/v1/api_keys/{apiKeyID}", path = {"apiKeyID"} },
    ["clerk.get_api_key_secret"] = { method = "GET", url = "https://api.clerk.com/v1/api_keys/{apiKeyID}/secret", path = {"apiKeyID"} },
    ["clerk.get_api_keys"] = { method = "GET", url = "https://api.clerk.com/v1/api_keys", query = {"type", "subject", "include_invalid", "limit", "offset", "query"} },
    ["clerk.get_billing_price_list"] = { method = "GET", url = "https://api.clerk.com/v1/billing/prices", query = {"paginated", "limit", "offset", "plan_id"} },
    ["clerk.get_billing_statement"] = { method = "GET", url = "https://api.clerk.com/v1/billing/statements/{statementID}", path = {"statementID"} },
    ["clerk.get_billing_statement_list"] = { method = "GET", url = "https://api.clerk.com/v1/billing/statements", query = {"paginated", "limit", "offset"} },
    ["clerk.get_billing_statement_payment_attempts"] = { method = "GET", url = "https://api.clerk.com/v1/billing/statements/{statementID}/payment_attempts", path = {"statementID"}, query = {"paginated", "limit", "offset"} },
    ["clerk.get_client"] = { method = "GET", url = "https://api.clerk.com/v1/clients/{client_id}", path = {"client_id"} },
    ["clerk.get_commerce_plan_list"] = { method = "GET", url = "https://api.clerk.com/v1/billing/plans", query = {"paginated", "limit", "offset", "payer_type"} },
    ["clerk.get_commerce_subscription_item_list"] = { method = "GET", url = "https://api.clerk.com/v1/billing/subscription_items", query = {"paginated", "limit", "offset", "status", "payer_type", "plan_id", "include_free", "query"} },
    ["clerk.get_directory"] = { method = "GET", url = "https://api.clerk.com/v1/directories/{directory_id}", path = {"directory_id"} },
    ["clerk.get_email_address"] = { method = "GET", url = "https://api.clerk.com/v1/email_addresses/{email_address_id}", path = {"email_address_id"} },
    ["clerk.get_enterprise_connection"] = { method = "GET", url = "https://api.clerk.com/v1/enterprise_connections/{enterprise_connection_id}", path = {"enterprise_connection_id"} },
    ["clerk.get_instance"] = { method = "GET", url = "https://api.clerk.com/v1/instance" },
    ["clerk.get_instance_communication"] = { method = "GET", url = "https://api.clerk.com/v1/instance/communication" },
    ["clerk.get_instance_oauth_application_settings"] = { method = "GET", url = "https://api.clerk.com/v1/instance/oauth_application_settings" },
    ["clerk.get_instance_organization_settings"] = { method = "GET", url = "https://api.clerk.com/v1/instance/organization_settings" },
    ["clerk.get_instance_protect"] = { method = "GET", url = "https://api.clerk.com/v1/instance/protect" },
    ["clerk.get_jwks"] = { method = "GET", url = "https://api.clerk.com/v1/jwks" },
    ["clerk.get_jwttemplate"] = { method = "GET", url = "https://api.clerk.com/v1/jwt_templates/{template_id}", path = {"template_id"} },
    ["clerk.get_m2_mtokens"] = { method = "GET", url = "https://api.clerk.com/v1/m2m_tokens", query = {"subject", "revoked", "expired", "limit", "offset"} },
    ["clerk.get_machine"] = { method = "GET", url = "https://api.clerk.com/v1/machines/{machine_id}", path = {"machine_id"} },
    ["clerk.get_machine_secret_key"] = { method = "GET", url = "https://api.clerk.com/v1/machines/{machine_id}/secret_key", path = {"machine_id"} },
    ["clerk.get_oauth_access_token"] = { method = "GET", url = "https://api.clerk.com/v1/users/{user_id}/oauth_access_tokens/{provider}", path = {"user_id", "provider"}, query = {"paginated", "limit", "offset"} },
    ["clerk.get_oauth_application"] = { method = "GET", url = "https://api.clerk.com/v1/oauth_applications/{oauth_application_id}", path = {"oauth_application_id"} },
    ["clerk.get_organization"] = { method = "GET", url = "https://api.clerk.com/v1/organizations/{organization_id}", path = {"organization_id"}, query = {"include_members_count", "include_missing_member_with_elevated_permissions"} },
    ["clerk.get_organization_billing_credit_balance"] = { method = "GET", url = "https://api.clerk.com/v1/organizations/{organization_id}/billing/credits", path = {"organization_id"} },
    ["clerk.get_organization_billing_subscription"] = { method = "GET", url = "https://api.clerk.com/v1/organizations/{organization_id}/billing/subscription", path = {"organization_id"} },
    ["clerk.get_organization_invitation"] = { method = "GET", url = "https://api.clerk.com/v1/organizations/{organization_id}/invitations/{invitation_id}", path = {"organization_id", "invitation_id"} },
    ["clerk.get_organization_permission"] = { method = "GET", url = "https://api.clerk.com/v1/organization_permissions/{permission_id}", path = {"permission_id"} },
    ["clerk.get_organization_role"] = { method = "GET", url = "https://api.clerk.com/v1/organization_roles/{organization_role_id}", path = {"organization_role_id"} },
    ["clerk.get_phone_number"] = { method = "GET", url = "https://api.clerk.com/v1/phone_numbers/{phone_number_id}", path = {"phone_number_id"} },
    ["clerk.get_public_interstitial"] = { method = "GET", url = "https://api.clerk.com/v1/public/interstitial", query = {"frontendApi", "frontend_api", "publishable_key", "proxy_url", "domain", "sign_in_url", "use_domain_for_script"} },
    ["clerk.get_redirect_url"] = { method = "GET", url = "https://api.clerk.com/v1/redirect_urls/{id}", path = {"id"} },
    ["clerk.get_reverification"] = { method = "GET", url = "https://api.clerk.com/v1/sessions/{session_id}/reverifications/{reverification_id}", path = {"session_id", "reverification_id"} },
    ["clerk.get_role_set"] = { method = "GET", url = "https://api.clerk.com/v1/role_sets/{role_set_key_or_id}", path = {"role_set_key_or_id"} },
    ["clerk.get_scimdirectory"] = { method = "GET", url = "https://api.clerk.com/v1/scim_directories/{scim_directory_id}", path = {"scim_directory_id"} },
    ["clerk.get_session"] = { method = "GET", url = "https://api.clerk.com/v1/sessions/{session_id}", path = {"session_id"} },
    ["clerk.get_session_list"] = { method = "GET", url = "https://api.clerk.com/v1/sessions", query = {"client_id", "user_id", "status", "paginated", "limit", "offset"} },
    ["clerk.get_sign_up"] = { method = "GET", url = "https://api.clerk.com/v1/sign_ups/{id}", path = {"id"} },
    ["clerk.get_user"] = { method = "GET", url = "https://api.clerk.com/v1/users/{user_id}", path = {"user_id"} },
    ["clerk.get_user_billing_credit_balance"] = { method = "GET", url = "https://api.clerk.com/v1/users/{user_id}/billing/credits", path = {"user_id"} },
    ["clerk.get_user_billing_subscription"] = { method = "GET", url = "https://api.clerk.com/v1/users/{user_id}/billing/subscription", path = {"user_id"} },
    ["clerk.get_user_list"] = { method = "GET", url = "https://api.clerk.com/v1/users", query = {"email_address", "phone_number", "external_id", "username", "web3_wallet", "user_id", "organization_id", "query", "email_address_query", "phone_number_query", "username_query", "name_query", "banned", "last_active_at_before", "last_active_at_after", "last_active_at_since", "created_at_before", "created_at_after", "last_sign_in_at_before", "last_sign_in_at_after", "provider", "provider_user_id", "limit", "offset", "starting_after", "order_by"} },
    ["clerk.get_users_count"] = { method = "GET", url = "https://api.clerk.com/v1/users/count", query = {"email_address", "phone_number", "external_id", "username", "web3_wallet", "user_id", "organization_id", "query", "email_address_query", "phone_number_query", "username_query", "name_query", "banned", "last_active_at_before", "last_active_at_after", "last_active_at_since", "created_at_before", "created_at_after", "last_sign_in_at_before", "last_sign_in_at_after", "provider", "provider_user_id"} },
    ["clerk.instance_get_organization_memberships"] = { method = "GET", url = "https://api.clerk.com/v1/organization_memberships", query = {"order_by", "limit", "offset"} },
    ["clerk.invite_waitlist_entry"] = { method = "POST", url = "https://api.clerk.com/v1/waitlist_entries/{waitlist_entry_id}/invite", path = {"waitlist_entry_id"}, body = {"ignore_existing"} },
    ["clerk.list_all_organization_domains"] = { method = "GET", url = "https://api.clerk.com/v1/organization_domains", query = {"organization_id", "verified", "enrollment_mode", "query", "domains", "order_by", "offset", "limit"} },
    ["clerk.list_allowlist_identifiers"] = { method = "GET", url = "https://api.clerk.com/v1/allowlist_identifiers", query = {"paginated", "limit", "offset"} },
    ["clerk.list_blocklist_identifiers"] = { method = "GET", url = "https://api.clerk.com/v1/blocklist_identifiers" },
    ["clerk.list_directories"] = { method = "GET", url = "https://api.clerk.com/v1/directories", query = {"limit", "offset"} },
    ["clerk.list_directory_group_role_mappings"] = { method = "GET", url = "https://api.clerk.com/v1/directories/{directory_id}/group_role_mappings", path = {"directory_id"} },
    ["clerk.list_domains"] = { method = "GET", url = "https://api.clerk.com/v1/domains" },
    ["clerk.list_enterprise_connection_test_runs"] = { method = "GET", url = "https://api.clerk.com/v1/enterprise_connections/{enterprise_connection_id}/test_runs", path = {"enterprise_connection_id"}, query = {"status", "limit", "offset"} },
    ["clerk.list_enterprise_connections"] = { method = "GET", url = "https://api.clerk.com/v1/enterprise_connections", query = {"limit", "offset", "organization_id", "active"} },
    ["clerk.list_instance_organization_invitations"] = { method = "GET", url = "https://api.clerk.com/v1/organization_invitations", query = {"order_by", "status", "query", "limit", "offset"} },
    ["clerk.list_invitations"] = { method = "GET", url = "https://api.clerk.com/v1/invitations", query = {"status", "query", "order_by", "paginated", "limit", "offset"} },
    ["clerk.list_jwttemplates"] = { method = "GET", url = "https://api.clerk.com/v1/jwt_templates", query = {"paginated", "limit", "offset"} },
    ["clerk.list_machines"] = { method = "GET", url = "https://api.clerk.com/v1/machines", query = {"limit", "offset", "query", "order_by"} },
    ["clerk.list_oauth_applications"] = { method = "GET", url = "https://api.clerk.com/v1/oauth_applications", query = {"limit", "offset", "order_by", "name_query"} },
    ["clerk.list_organization_domains"] = { method = "GET", url = "https://api.clerk.com/v1/organizations/{organization_id}/domains", path = {"organization_id"}, query = {"verified", "enrollment_mode", "limit", "offset"} },
    ["clerk.list_organization_invitations"] = { method = "GET", url = "https://api.clerk.com/v1/organizations/{organization_id}/invitations", path = {"organization_id"}, query = {"status", "email_address", "order_by", "limit", "offset"} },
    ["clerk.list_organization_memberships"] = { method = "GET", url = "https://api.clerk.com/v1/organizations/{organization_id}/memberships", path = {"organization_id"}, query = {"order_by", "user_id", "email_address", "phone_number", "username", "web3_wallet", "role", "query", "email_address_query", "phone_number_query", "username_query", "name_query", "last_active_at_before", "last_active_at_after", "created_at_before", "created_at_after", "limit", "offset"} },
    ["clerk.list_organization_permissions"] = { method = "GET", url = "https://api.clerk.com/v1/organization_permissions", query = {"query", "order_by", "limit", "offset"} },
    ["clerk.list_organization_roles"] = { method = "GET", url = "https://api.clerk.com/v1/organization_roles", query = {"query", "order_by", "limit", "offset"} },
    ["clerk.list_organizations"] = { method = "GET", url = "https://api.clerk.com/v1/organizations", query = {"include_members_count", "include_missing_member_with_elevated_permissions", "query", "user_id", "organization_id", "order_by", "limit", "offset"} },
    ["clerk.list_redirect_urls"] = { method = "GET", url = "https://api.clerk.com/v1/redirect_urls", query = {"paginated", "limit", "offset"} },
    ["clerk.list_role_sets"] = { method = "GET", url = "https://api.clerk.com/v1/role_sets", query = {"query", "order_by", "limit", "offset"} },
    ["clerk.list_scimdirectories"] = { method = "GET", url = "https://api.clerk.com/v1/scim_directories", query = {"limit", "offset"} },
    ["clerk.list_scimgroup_role_mappings"] = { method = "GET", url = "https://api.clerk.com/v1/scim_directories/{scim_directory_id}/group_role_mappings", path = {"scim_directory_id"} },
    ["clerk.list_user_biometric_credentials"] = { method = "GET", url = "https://api.clerk.com/v1/users/{user_id}/biometric_credentials", path = {"user_id"} },
    ["clerk.list_waitlist_entries"] = { method = "GET", url = "https://api.clerk.com/v1/waitlist_entries", query = {"limit", "offset", "query", "status", "order_by"} },
    ["clerk.lock_user"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/lock", path = {"user_id"} },
    ["clerk.merge_organization_metadata"] = { method = "PATCH", url = "https://api.clerk.com/v1/organizations/{organization_id}/metadata", path = {"organization_id"}, body = {"public_metadata", "private_metadata"} },
    ["clerk.prepare_email_address_verification"] = { method = "POST", url = "https://api.clerk.com/v1/email_addresses/{email_address_id}/prepare_verification", path = {"email_address_id"} },
    ["clerk.prepare_phone_number_verification"] = { method = "POST", url = "https://api.clerk.com/v1/phone_numbers/{phone_number_id}/prepare_verification", path = {"phone_number_id"} },
    ["clerk.refresh_session"] = { method = "POST", url = "https://api.clerk.com/v1/sessions/{session_id}/refresh", path = {"session_id"}, body = {"expired_token", "refresh_token", "request_origin", "request_headers", "format", "request_originating_ip"} },
    ["clerk.reject_waitlist_entry"] = { method = "POST", url = "https://api.clerk.com/v1/waitlist_entries/{waitlist_entry_id}/reject", path = {"waitlist_entry_id"} },
    ["clerk.remove_billing_subscription_item_discount"] = { method = "DELETE", url = "https://api.clerk.com/v1/billing/subscription_items/{subscription_item_id}/discounts/{discount_id}", path = {"subscription_item_id", "discount_id"} },
    ["clerk.remove_permission_from_organization_role"] = { method = "DELETE", url = "https://api.clerk.com/v1/organization_roles/{organization_role_id}/permissions/{permission_id}", path = {"organization_role_id", "permission_id"} },
    ["clerk.remove_user_password"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/remove_password", path = {"user_id"}, body = {"sign_out_of_other_sessions"} },
    ["clerk.replace_directory_group_role_mappings"] = { method = "PUT", url = "https://api.clerk.com/v1/directories/{directory_id}/group_role_mappings", path = {"directory_id"}, body = {"mappings"} },
    ["clerk.replace_organization_metadata"] = { method = "PUT", url = "https://api.clerk.com/v1/organizations/{organization_id}/metadata", path = {"organization_id"}, body = {"public_metadata", "private_metadata"} },
    ["clerk.replace_role_in_role_set"] = { method = "POST", url = "https://api.clerk.com/v1/role_sets/{role_set_key_or_id}/roles/replace", path = {"role_set_key_or_id"}, body = {"role_key", "to_role_key"} },
    ["clerk.replace_role_set"] = { method = "POST", url = "https://api.clerk.com/v1/role_sets/{role_set_key_or_id}/replace", path = {"role_set_key_or_id"}, body = {"dest_role_set_key", "reassignment_mappings"} },
    ["clerk.replace_scimgroup_role_mappings"] = { method = "PUT", url = "https://api.clerk.com/v1/scim_directories/{scim_directory_id}/group_role_mappings", path = {"scim_directory_id"}, body = {"mappings"} },
    ["clerk.replace_user_email_address"] = { method = "PUT", url = "https://api.clerk.com/v1/users/{user_id}/email_address", path = {"user_id"}, body = {"email_address", "identification_status", "notify_primary_email_address_changed"} },
    ["clerk.replace_user_metadata"] = { method = "PUT", url = "https://api.clerk.com/v1/users/{user_id}/metadata", path = {"user_id"}, body = {"public_metadata", "private_metadata", "unsafe_metadata"} },
    ["clerk.replace_user_phone_number"] = { method = "PUT", url = "https://api.clerk.com/v1/users/{user_id}/phone_number", path = {"user_id"}, body = {"phone_number", "identification_status"} },
    ["clerk.revoke_actor_token"] = { method = "POST", url = "https://api.clerk.com/v1/actor_tokens/{actor_token_id}/revoke", path = {"actor_token_id"} },
    ["clerk.revoke_admin_portal_link_token"] = { method = "POST", url = "https://api.clerk.com/v1/admin_portal_link_tokens/{adminPortalLinkTokenID}/revoke", path = {"adminPortalLinkTokenID"}, body = {"revocation_reason"} },
    ["clerk.revoke_agent_task"] = { method = "POST", url = "https://api.clerk.com/v1/agents/tasks/{agent_task_id}/revoke", path = {"agent_task_id"} },
    ["clerk.revoke_api_key"] = { method = "POST", url = "https://api.clerk.com/v1/api_keys/{apiKeyID}/revoke", path = {"apiKeyID"}, body = {"revocation_reason"} },
    ["clerk.revoke_invitation"] = { method = "POST", url = "https://api.clerk.com/v1/invitations/{invitation_id}/revoke", path = {"invitation_id"} },
    ["clerk.revoke_m2_mtoken"] = { method = "POST", url = "https://api.clerk.com/v1/m2m_tokens/{m2m_token_id}/revoke", path = {"m2m_token_id"}, body = {"revocation_reason"} },
    ["clerk.revoke_oauth_application_token"] = { method = "POST", url = "https://api.clerk.com/v1/oauth_applications/{oauth_application_id}/revoke_token", path = {"oauth_application_id"} },
    ["clerk.revoke_organization_invitation"] = { method = "POST", url = "https://api.clerk.com/v1/organizations/{organization_id}/invitations/{invitation_id}/revoke", path = {"organization_id", "invitation_id"}, body = {"requesting_user_id"} },
    ["clerk.revoke_session"] = { method = "POST", url = "https://api.clerk.com/v1/sessions/{session_id}/revoke", path = {"session_id"} },
    ["clerk.revoke_sign_in_token"] = { method = "POST", url = "https://api.clerk.com/v1/sign_in_tokens/{sign_in_token_id}/revoke", path = {"sign_in_token_id"} },
    ["clerk.revoke_user_biometric_credential"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}/biometric_credentials/{biometric_credential_id}", path = {"user_id", "biometric_credential_id"} },
    ["clerk.rotate_directory_apikey"] = { method = "POST", url = "https://api.clerk.com/v1/directories/{directory_id}/rotate_api_key", path = {"directory_id"} },
    ["clerk.rotate_machine_secret_key"] = { method = "POST", url = "https://api.clerk.com/v1/machines/{machine_id}/secret_key/rotate", path = {"machine_id"}, body = {"previous_token_ttl"} },
    ["clerk.rotate_oauth_application_secret"] = { method = "POST", url = "https://api.clerk.com/v1/oauth_applications/{oauth_application_id}/rotate_secret", path = {"oauth_application_id"} },
    ["clerk.rotate_scimdirectory_apikey"] = { method = "POST", url = "https://api.clerk.com/v1/scim_directories/{scim_directory_id}/rotate_api_key", path = {"scim_directory_id"} },
    ["clerk.set_user_password_compromised"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/password/set_compromised", path = {"user_id"}, body = {"revoke_all_sessions"} },
    ["clerk.set_user_profile_image"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/profile_image", path = {"user_id"}, body = {"file"} },
    ["clerk.unban_user"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/unban", path = {"user_id"} },
    ["clerk.unlock_user"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/unlock", path = {"user_id"} },
    ["clerk.unset_user_password_compromised"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/password/unset_compromised", path = {"user_id"} },
    ["clerk.update_api_key"] = { method = "PATCH", url = "https://api.clerk.com/v1/api_keys/{apiKeyID}", path = {"apiKeyID"}, body = {"claims", "scopes", "description", "subject", "seconds_until_expiration"} },
    ["clerk.update_directory"] = { method = "PATCH", url = "https://api.clerk.com/v1/directories/{directory_id}", path = {"directory_id"}, body = {"name", "enabled", "provider", "attribute_mapping", "group_role_mapping_enabled"} },
    ["clerk.update_domain"] = { method = "PATCH", url = "https://api.clerk.com/v1/domains/{domain_id}", path = {"domain_id"}, body = {"name", "proxy_url", "is_secondary"} },
    ["clerk.update_email_address"] = { method = "PATCH", url = "https://api.clerk.com/v1/email_addresses/{email_address_id}", path = {"email_address_id"}, body = {"verified", "primary", "notify_primary_email_address_changed"} },
    ["clerk.update_enterprise_connection"] = { method = "PATCH", url = "https://api.clerk.com/v1/enterprise_connections/{enterprise_connection_id}", path = {"enterprise_connection_id"}, body = {"name", "domains", "active", "sync_user_attributes", "disable_additional_identifications", "allow_organization_account_linking", "organization_id", "saml", "oidc", "custom_attributes"} },
    ["clerk.update_instance"] = { method = "PATCH", url = "https://api.clerk.com/v1/instance", body = {"test_mode", "hibp", "support_email", "clerk_js_version", "development_origin", "allowed_origins", "allowed_subdomains", "subdomain_allowlist_enabled", "cookieless_dev", "url_based_session_syncing", "preferred_sign_in_strategy_when_password_required"} },
    ["clerk.update_instance_auth_config"] = { method = "PATCH", url = "https://api.clerk.com/v1/beta_features/instance_settings", body = {"restricted_to_allowlist", "from_email_address", "progressive_sign_up", "test_mode"} },
    ["clerk.update_instance_communication"] = { method = "PATCH", url = "https://api.clerk.com/v1/instance/communication", body = {"blocked_country_codes"} },
    ["clerk.update_instance_oauth_application_settings"] = { method = "PATCH", url = "https://api.clerk.com/v1/instance/oauth_application_settings", body = {"dynamic_oauth_client_registration", "default_scopes", "oauth_jwt_access_tokens", "aud_claim_enabled", "pkce_required", "client_id_metadata_documents_advertised", "client_id_metadata_documents_only_allow_pre_registered_clients", "client_id_metadata_documents_block_implicitly_allowed_clients"} },
    ["clerk.update_instance_organization_settings"] = { method = "PATCH", url = "https://api.clerk.com/v1/instance/organization_settings", body = {"enabled", "max_allowed_memberships", "admin_delete_enabled", "domains_enabled", "slug_disabled", "domains_enrollment_modes", "creator_role_id", "domains_default_role_id"} },
    ["clerk.update_instance_protect"] = { method = "PATCH", url = "https://api.clerk.com/v1/instance/protect", body = {"rules_enabled", "specter_enabled"} },
    ["clerk.update_instance_restrictions"] = { method = "PATCH", url = "https://api.clerk.com/v1/instance/restrictions", body = {"allowlist", "blocklist", "allowlist_blocklist_disabled_on_sign_in", "block_email_subaddresses", "block_disposable_email_domains"} },
    ["clerk.update_jwttemplate"] = { method = "PATCH", url = "https://api.clerk.com/v1/jwt_templates/{template_id}", path = {"template_id"}, body = {"name", "claims", "lifetime", "allowed_clock_skew", "custom_signing_key", "signing_algorithm", "signing_key"} },
    ["clerk.update_machine"] = { method = "PATCH", url = "https://api.clerk.com/v1/machines/{machine_id}", path = {"machine_id"}, body = {"name", "default_token_ttl"} },
    ["clerk.update_oauth_application"] = { method = "PATCH", url = "https://api.clerk.com/v1/oauth_applications/{oauth_application_id}", path = {"oauth_application_id"}, body = {"name", "redirect_uris", "callback_url", "scopes", "consent_screen_enabled", "pkce_required", "device_authorization_grant_enabled", "public"} },
    ["clerk.update_organization"] = { method = "PATCH", url = "https://api.clerk.com/v1/organizations/{organization_id}", path = {"organization_id"}, body = {"name", "slug", "max_allowed_memberships", "admin_delete_enabled", "self_serve_sso_enabled", "created_at", "role_set_key"} },
    ["clerk.update_organization_domain"] = { method = "PATCH", url = "https://api.clerk.com/v1/organizations/{organization_id}/domains/{domain_id}", path = {"organization_id", "domain_id"}, body = {"enrollment_mode", "verified"} },
    ["clerk.update_organization_membership"] = { method = "PATCH", url = "https://api.clerk.com/v1/organizations/{organization_id}/memberships/{user_id}", path = {"organization_id", "user_id"}, body = {"role"} },
    ["clerk.update_organization_membership_metadata"] = { method = "PATCH", url = "https://api.clerk.com/v1/organizations/{organization_id}/memberships/{user_id}/metadata", path = {"organization_id", "user_id"}, body = {"public_metadata", "private_metadata"} },
    ["clerk.update_organization_permission"] = { method = "PATCH", url = "https://api.clerk.com/v1/organization_permissions/{permission_id}", path = {"permission_id"}, body = {"name", "description"} },
    ["clerk.update_organization_role"] = { method = "PATCH", url = "https://api.clerk.com/v1/organization_roles/{organization_role_id}", path = {"organization_role_id"}, body = {"name", "description", "permissions"} },
    ["clerk.update_phone_number"] = { method = "PATCH", url = "https://api.clerk.com/v1/phone_numbers/{phone_number_id}", path = {"phone_number_id"}, body = {"verified", "primary", "reserved_for_second_factor"} },
    ["clerk.update_role_set"] = { method = "PATCH", url = "https://api.clerk.com/v1/role_sets/{role_set_key_or_id}", path = {"role_set_key_or_id"}, body = {"name", "description", "type", "default_role_key", "creator_role_key"} },
    ["clerk.update_scimdirectory"] = { method = "PATCH", url = "https://api.clerk.com/v1/scim_directories/{scim_directory_id}", path = {"scim_directory_id"}, body = {"name", "enabled", "provider", "attribute_mapping", "group_role_mapping_enabled"} },
    ["clerk.update_sign_up"] = { method = "PATCH", url = "https://api.clerk.com/v1/sign_ups/{id}", path = {"id"}, body = {"external_id", "custom_action"} },
    ["clerk.update_user"] = { method = "PATCH", url = "https://api.clerk.com/v1/users/{user_id}", path = {"user_id"}, body = {"external_id", "first_name", "last_name", "locale", "primary_email_address_id", "notify_primary_email_address_changed", "primary_phone_number_id", "primary_web3_wallet_id", "username", "profile_image_id", "password", "password_digest", "password_hasher", "skip_password_checks", "sign_out_of_other_sessions", "totp_secret", "backup_codes", "delete_self_enabled", "create_organization_enabled", "legal_accepted_at", "skip_legal_checks", "create_organizations_limit", "created_at", "bypass_client_trust"} },
    ["clerk.update_user_metadata"] = { method = "PATCH", url = "https://api.clerk.com/v1/users/{user_id}/metadata", path = {"user_id"}, body = {"public_metadata", "private_metadata", "unsafe_metadata"} },
    ["clerk.upload_oauth_application_logo"] = { method = "PUT", url = "https://api.clerk.com/v1/oauth_applications/{oauth_application_id}/logo", path = {"oauth_application_id"}, body = {"uploader_user_id", "file"} },
    ["clerk.upload_organization_logo"] = { method = "PUT", url = "https://api.clerk.com/v1/organizations/{organization_id}/logo", path = {"organization_id"}, body = {"uploader_user_id", "file"} },
    ["clerk.user_passkey_delete"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}/passkeys/{passkey_identification_id}", path = {"user_id", "passkey_identification_id"} },
    ["clerk.user_web3_wallet_delete"] = { method = "DELETE", url = "https://api.clerk.com/v1/users/{user_id}/web3_wallets/{web3_wallet_identification_id}", path = {"user_id", "web3_wallet_identification_id"} },
    ["clerk.users_ban"] = { method = "POST", url = "https://api.clerk.com/v1/users/ban", body = {"user_ids"} },
    ["clerk.users_get_organization_invitations"] = { method = "GET", url = "https://api.clerk.com/v1/users/{user_id}/organization_invitations", path = {"user_id"}, query = {"limit", "offset", "status"} },
    ["clerk.users_get_organization_memberships"] = { method = "GET", url = "https://api.clerk.com/v1/users/{user_id}/organization_memberships", path = {"user_id"}, query = {"limit", "offset"} },
    ["clerk.users_unban"] = { method = "POST", url = "https://api.clerk.com/v1/users/unban", body = {"user_ids"} },
    ["clerk.verify_api_key"] = { method = "POST", url = "https://api.clerk.com/v1/api_keys/verify" },
    ["clerk.verify_client"] = { method = "POST", url = "https://api.clerk.com/v1/clients/verify" },
    ["clerk.verify_domain_proxy"] = { method = "POST", url = "https://api.clerk.com/v1/proxy_checks", body = {"domain_id", "proxy_url"} },
    ["clerk.verify_m2_mtoken"] = { method = "POST", url = "https://api.clerk.com/v1/m2m_tokens/verify" },
    ["clerk.verify_oauth_access_token"] = { method = "POST", url = "https://api.clerk.com/v1/oauth_applications/access_tokens/verify" },
    ["clerk.verify_organization_domain_ownership"] = { method = "POST", url = "https://api.clerk.com/v1/organizations/{organization_id}/domains/{domain_id}/verify_ownership", path = {"organization_id", "domain_id"} },
    ["clerk.verify_password"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/verify_password", path = {"user_id"}, body = {"password"} },
    ["clerk.verify_totp"] = { method = "POST", url = "https://api.clerk.com/v1/users/{user_id}/verify_totp", path = {"user_id"}, body = {"code"} },
  },
}
