-- Mandrill — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/mandrillapp.com/1.0/swagger.json
-- APIs.guru's mirror, matched on mandrillapp.com. A mirror lags the vendor.
-- 90 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "mandrill",
  name = "Mandrill",
  base = "https://mandrillapp.com/api",
  docs = "https://nango.dev/docs/api-integrations/mandrill",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "MANDRILL_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["mandrill.post_exports_activity_json"] = { method = "POST", url = "https://mandrillapp.com/api/exports/activity.json", body = {"api_keys", "date_from", "date_to", "notify_email", "senders", "states", "tags", "body"} },
    ["mandrill.post_exports_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/exports/info.json", body = {"id", "body"} },
    ["mandrill.post_exports_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/exports/list.json", body = {"body"} },
    ["mandrill.post_exports_rejects_json"] = { method = "POST", url = "https://mandrillapp.com/api/exports/rejects.json", body = {"notify_email", "body"} },
    ["mandrill.post_exports_whitelist_json"] = { method = "POST", url = "https://mandrillapp.com/api/exports/whitelist.json", body = {"notify_email", "body"} },
    ["mandrill.post_inbound_add_domain_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/add-domain.json", body = {"domain", "body"} },
    ["mandrill.post_inbound_add_route_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/add-route.json", body = {"domain", "pattern", "url", "body"} },
    ["mandrill.post_inbound_check_domain_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/check-domain.json", body = {"domain", "body"} },
    ["mandrill.post_inbound_delete_domain_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/delete-domain.json", body = {"domain", "body"} },
    ["mandrill.post_inbound_delete_route_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/delete-route.json", body = {"id", "body"} },
    ["mandrill.post_inbound_domains_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/domains.json", body = {"body"} },
    ["mandrill.post_inbound_routes_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/routes.json", body = {"domain", "body"} },
    ["mandrill.post_inbound_send_raw_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/send-raw.json", body = {"client_address", "helo", "mail_from", "raw_message", "to", "body"} },
    ["mandrill.post_inbound_update_route_json"] = { method = "POST", url = "https://mandrillapp.com/api/inbound/update-route.json", body = {"id", "pattern", "url", "body"} },
    ["mandrill.post_ips_cancel_warmup_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/cancel-warmup.json", body = {"ip", "body"} },
    ["mandrill.post_ips_check_custom_dns_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/check-custom-dns.json", body = {"domain", "ip", "body"} },
    ["mandrill.post_ips_create_pool_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/create-pool.json", body = {"pool", "body"} },
    ["mandrill.post_ips_delete_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/delete.json", body = {"ip", "body"} },
    ["mandrill.post_ips_delete_pool_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/delete-pool.json", body = {"pool", "body"} },
    ["mandrill.post_ips_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/info.json", body = {"ip", "body"} },
    ["mandrill.post_ips_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/list.json", body = {"body"} },
    ["mandrill.post_ips_list_pools_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/list-pools.json", body = {"body"} },
    ["mandrill.post_ips_pool_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/pool-info.json", body = {"pool", "body"} },
    ["mandrill.post_ips_provision_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/provision.json", body = {"pool", "warmup", "body"} },
    ["mandrill.post_ips_set_custom_dns_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/set-custom-dns.json", body = {"domain", "ip", "body"} },
    ["mandrill.post_ips_set_pool_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/set-pool.json", body = {"create_pool", "ip", "pool", "body"} },
    ["mandrill.post_ips_start_warmup_json"] = { method = "POST", url = "https://mandrillapp.com/api/ips/start-warmup.json", body = {"ip", "body"} },
    ["mandrill.post_messages_cancel_scheduled_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/cancel-scheduled.json", body = {"id", "body"} },
    ["mandrill.post_messages_content_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/content.json", body = {"id", "body"} },
    ["mandrill.post_messages_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/info.json", body = {"id", "body"} },
    ["mandrill.post_messages_list_scheduled_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/list-scheduled.json", body = {"to", "body"} },
    ["mandrill.post_messages_parse_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/parse.json", body = {"raw_message", "body"} },
    ["mandrill.post_messages_reschedule_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/reschedule.json", body = {"id", "send_at", "body"} },
    ["mandrill.post_messages_search_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/search.json", body = {"api_keys", "date_from", "date_to", "limit", "query", "senders", "tags", "body"} },
    ["mandrill.post_messages_search_time_series_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/search-time-series.json", body = {"date_from", "date_to", "query", "senders", "tags", "body"} },
    ["mandrill.post_messages_send_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/send.json", body = {"async", "ip_pool", "message", "send_at", "body"} },
    ["mandrill.post_messages_send_raw_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/send-raw.json", body = {"async", "from_email", "from_name", "ip_pool", "raw_message", "return_path_domain", "send_at", "to", "body"} },
    ["mandrill.post_messages_send_template_json"] = { method = "POST", url = "https://mandrillapp.com/api/messages/send-template.json", body = {"async", "ip_pool", "message", "send_at", "template_content", "template_name", "body"} },
    ["mandrill.post_metadata_add_json"] = { method = "POST", url = "https://mandrillapp.com/api/metadata/add.json", body = {"name", "view_template", "body"} },
    ["mandrill.post_metadata_delete_json"] = { method = "POST", url = "https://mandrillapp.com/api/metadata/delete.json", body = {"name", "body"} },
    ["mandrill.post_metadata_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/metadata/list.json", body = {"body"} },
    ["mandrill.post_metadata_update_json"] = { method = "POST", url = "https://mandrillapp.com/api/metadata/update.json", body = {"name", "view_template", "body"} },
    ["mandrill.post_rejects_add_json"] = { method = "POST", url = "https://mandrillapp.com/api/rejects/add.json", body = {"comment", "email", "subaccount", "body"} },
    ["mandrill.post_rejects_delete_json"] = { method = "POST", url = "https://mandrillapp.com/api/rejects/delete.json", body = {"email", "subaccount", "body"} },
    ["mandrill.post_rejects_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/rejects/list.json", body = {"email", "include_expired", "subaccount", "body"} },
    ["mandrill.post_senders_add_domain_json"] = { method = "POST", url = "https://mandrillapp.com/api/senders/add-domain.json", body = {"domain", "body"} },
    ["mandrill.post_senders_check_domain_json"] = { method = "POST", url = "https://mandrillapp.com/api/senders/check-domain.json", body = {"domain", "body"} },
    ["mandrill.post_senders_domains_json"] = { method = "POST", url = "https://mandrillapp.com/api/senders/domains.json", body = {"body"} },
    ["mandrill.post_senders_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/senders/info.json", body = {"address", "body"} },
    ["mandrill.post_senders_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/senders/list.json", body = {"body"} },
    ["mandrill.post_senders_time_series_json"] = { method = "POST", url = "https://mandrillapp.com/api/senders/time-series.json", body = {"address", "body"} },
    ["mandrill.post_senders_verify_domain_json"] = { method = "POST", url = "https://mandrillapp.com/api/senders/verify-domain.json", body = {"domain", "mailbox", "body"} },
    ["mandrill.post_subaccounts_add_json"] = { method = "POST", url = "https://mandrillapp.com/api/subaccounts/add.json", body = {"custom_quota", "id", "name", "notes", "body"} },
    ["mandrill.post_subaccounts_delete_json"] = { method = "POST", url = "https://mandrillapp.com/api/subaccounts/delete.json", body = {"id", "body"} },
    ["mandrill.post_subaccounts_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/subaccounts/info.json", body = {"id", "body"} },
    ["mandrill.post_subaccounts_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/subaccounts/list.json", body = {"q", "body"} },
    ["mandrill.post_subaccounts_pause_json"] = { method = "POST", url = "https://mandrillapp.com/api/subaccounts/pause.json", body = {"id", "body"} },
    ["mandrill.post_subaccounts_resume_json"] = { method = "POST", url = "https://mandrillapp.com/api/subaccounts/resume.json", body = {"id", "body"} },
    ["mandrill.post_subaccounts_update_json"] = { method = "POST", url = "https://mandrillapp.com/api/subaccounts/update.json", body = {"custom_quota", "id", "name", "notes", "body"} },
    ["mandrill.post_tags_all_time_series_json"] = { method = "POST", url = "https://mandrillapp.com/api/tags/all-time-series.json", body = {"body"} },
    ["mandrill.post_tags_delete_json"] = { method = "POST", url = "https://mandrillapp.com/api/tags/delete.json", body = {"tag", "body"} },
    ["mandrill.post_tags_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/tags/info.json", body = {"tag", "body"} },
    ["mandrill.post_tags_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/tags/list.json", body = {"body"} },
    ["mandrill.post_tags_time_series_json"] = { method = "POST", url = "https://mandrillapp.com/api/tags/time-series.json", body = {"tag", "body"} },
    ["mandrill.post_templates_add_json"] = { method = "POST", url = "https://mandrillapp.com/api/templates/add.json", body = {"code", "from_email", "from_name", "labels", "name", "publish", "subject", "text", "body"} },
    ["mandrill.post_templates_delete_json"] = { method = "POST", url = "https://mandrillapp.com/api/templates/delete.json", body = {"name", "body"} },
    ["mandrill.post_templates_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/templates/info.json", body = {"name", "body"} },
    ["mandrill.post_templates_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/templates/list.json", body = {"label", "body"} },
    ["mandrill.post_templates_publish_json"] = { method = "POST", url = "https://mandrillapp.com/api/templates/publish.json", body = {"name", "body"} },
    ["mandrill.post_templates_render_json"] = { method = "POST", url = "https://mandrillapp.com/api/templates/render.json", body = {"merge_vars", "template_content", "template_name", "body"} },
    ["mandrill.post_templates_time_series_json"] = { method = "POST", url = "https://mandrillapp.com/api/templates/time-series.json", body = {"name", "body"} },
    ["mandrill.post_templates_update_json"] = { method = "POST", url = "https://mandrillapp.com/api/templates/update.json", body = {"code", "from_email", "from_name", "labels", "name", "publish", "subject", "text", "body"} },
    ["mandrill.post_urls_add_tracking_domain_json"] = { method = "POST", url = "https://mandrillapp.com/api/urls/add-tracking-domain.json", body = {"domain", "body"} },
    ["mandrill.post_urls_check_tracking_domain_json"] = { method = "POST", url = "https://mandrillapp.com/api/urls/check-tracking-domain.json", body = {"domain", "body"} },
    ["mandrill.post_urls_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/urls/list.json", body = {"body"} },
    ["mandrill.post_urls_search_json"] = { method = "POST", url = "https://mandrillapp.com/api/urls/search.json", body = {"q", "body"} },
    ["mandrill.post_urls_time_series_json"] = { method = "POST", url = "https://mandrillapp.com/api/urls/time-series.json", body = {"url", "body"} },
    ["mandrill.post_urls_tracking_domains_json"] = { method = "POST", url = "https://mandrillapp.com/api/urls/tracking-domains.json", body = {"body"} },
    ["mandrill.post_users_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/users/info.json", body = {"body"} },
    ["mandrill.post_users_ping2_json"] = { method = "POST", url = "https://mandrillapp.com/api/users/ping2.json", body = {"body"} },
    ["mandrill.post_users_ping_json"] = { method = "POST", url = "https://mandrillapp.com/api/users/ping.json", body = {"body"} },
    ["mandrill.post_users_senders_json"] = { method = "POST", url = "https://mandrillapp.com/api/users/senders.json", body = {"body"} },
    ["mandrill.post_webhooks_add_json"] = { method = "POST", url = "https://mandrillapp.com/api/webhooks/add.json", body = {"description", "events", "url", "body"} },
    ["mandrill.post_webhooks_delete_json"] = { method = "POST", url = "https://mandrillapp.com/api/webhooks/delete.json", body = {"id", "body"} },
    ["mandrill.post_webhooks_info_json"] = { method = "POST", url = "https://mandrillapp.com/api/webhooks/info.json", body = {"id", "body"} },
    ["mandrill.post_webhooks_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/webhooks/list.json", body = {"body"} },
    ["mandrill.post_webhooks_update_json"] = { method = "POST", url = "https://mandrillapp.com/api/webhooks/update.json", body = {"description", "events", "id", "url", "body"} },
    ["mandrill.post_whitelists_add_json"] = { method = "POST", url = "https://mandrillapp.com/api/whitelists/add.json", body = {"email", "body"} },
    ["mandrill.post_whitelists_delete_json"] = { method = "POST", url = "https://mandrillapp.com/api/whitelists/delete.json", body = {"email", "body"} },
    ["mandrill.post_whitelists_list_json"] = { method = "POST", url = "https://mandrillapp.com/api/whitelists/list.json", body = {"email", "body"} },
  },
}
