-- Trello — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/trello.com/1.0/openapi.json
-- APIs.guru's mirror, matched on trello.com. A mirror lags the vendor.
-- 324 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "trello",
  name = "Trello",
  base = "https://api.trello.com",
  docs = "https://nango.dev/docs/integrations/all/trello",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "TRELLO_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["trello.add_boards"] = { method = "POST", url = "https://api.trello.com/boards", body = {"closed", "desc", "idBoardSource", "idOrganization", "keepFromSource", "labelNames/blue", "labelNames/green", "labelNames/orange", "labelNames/purple", "labelNames/red", "labelNames/yellow", "name", "powerUps", "prefs/background", "prefs/calendarFeedEnabled", "prefs/cardAging", "prefs/cardCovers", "prefs/comments", "prefs/invitations", "prefs/permissionLevel", "prefs/selfJoin", "prefs/voting", "prefs_background", "prefs_cardAging", "prefs_cardCovers", "prefs_comments", "prefs_invitations", "prefs_permissionLevel", "prefs_selfJoin", "prefs_voting", "subscribed"} },
    ["trello.add_boards_calendar_key_generate_by_id_board"] = { method = "POST", url = "https://api.trello.com/boards/{idBoard}/calendarKey/generate", path = {"idBoard"} },
    ["trello.add_boards_checklists_by_id_board"] = { method = "POST", url = "https://api.trello.com/boards/{idBoard}/checklists", path = {"idBoard"}, body = {"name"} },
    ["trello.add_boards_email_key_generate_by_id_board"] = { method = "POST", url = "https://api.trello.com/boards/{idBoard}/emailKey/generate", path = {"idBoard"} },
    ["trello.add_boards_labels_by_id_board"] = { method = "POST", url = "https://api.trello.com/boards/{idBoard}/labels", path = {"idBoard"}, body = {"color", "name"} },
    ["trello.add_boards_lists_by_id_board"] = { method = "POST", url = "https://api.trello.com/boards/{idBoard}/lists", path = {"idBoard"}, body = {"name", "pos"} },
    ["trello.add_boards_mark_as_viewed_by_id_board"] = { method = "POST", url = "https://api.trello.com/boards/{idBoard}/markAsViewed", path = {"idBoard"} },
    ["trello.add_boards_power_ups_by_id_board"] = { method = "POST", url = "https://api.trello.com/boards/{idBoard}/powerUps", path = {"idBoard"}, body = {"value"} },
    ["trello.add_cards"] = { method = "POST", url = "https://api.trello.com/cards", body = {"closed", "desc", "due", "fileSource", "idAttachmentCover", "idBoard", "idCardSource", "idLabels", "idList", "idMembers", "keepFromSource", "labels", "name", "pos", "subscribed", "urlSource"} },
    ["trello.add_cards_actions_comments_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/actions/comments", path = {"idCard"}, body = {"text"} },
    ["trello.add_cards_attachments_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/attachments", path = {"idCard"}, body = {"file", "mimeType", "name", "url"} },
    ["trello.add_cards_checklist_check_item_by_id_card_by_id_checklist"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/checklist/{idChecklist}/checkItem", path = {"idCard", "idChecklist"}, body = {"name", "pos"} },
    ["trello.add_cards_checklist_check_item_convert_to_card_by_id_card_by_id_checklist_by_id_check_item"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/checklist/{idChecklist}/checkItem/{idCheckItem}/convertToCard", path = {"idCard", "idChecklist", "idCheckItem"} },
    ["trello.add_cards_checklists_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/checklists", path = {"idCard"}, body = {"idChecklistSource", "name", "value"} },
    ["trello.add_cards_id_labels_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/idLabels", path = {"idCard"}, body = {"value"} },
    ["trello.add_cards_id_members_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/idMembers", path = {"idCard"}, body = {"value"} },
    ["trello.add_cards_labels_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/labels", path = {"idCard"}, body = {"color", "name", "value"} },
    ["trello.add_cards_mark_associated_notifications_read_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/markAssociatedNotificationsRead", path = {"idCard"} },
    ["trello.add_cards_members_voted_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/membersVoted", path = {"idCard"}, body = {"value"} },
    ["trello.add_cards_stickers_by_id_card"] = { method = "POST", url = "https://api.trello.com/cards/{idCard}/stickers", path = {"idCard"}, body = {"image", "left", "rotate", "top", "zIndex"} },
    ["trello.add_checklists"] = { method = "POST", url = "https://api.trello.com/checklists", body = {"idBoard", "idCard", "idChecklistSource", "name", "pos"} },
    ["trello.add_checklists_check_items_by_id_checklist"] = { method = "POST", url = "https://api.trello.com/checklists/{idChecklist}/checkItems", path = {"idChecklist"}, body = {"checked", "name", "pos"} },
    ["trello.add_labels"] = { method = "POST", url = "https://api.trello.com/labels", body = {"color", "idBoard", "name"} },
    ["trello.add_lists"] = { method = "POST", url = "https://api.trello.com/lists", body = {"closed", "idBoard", "idListSource", "name", "pos", "subscribed"} },
    ["trello.add_lists_archive_all_cards_by_id_list"] = { method = "POST", url = "https://api.trello.com/lists/{idList}/archiveAllCards", path = {"idList"} },
    ["trello.add_lists_cards_by_id_list"] = { method = "POST", url = "https://api.trello.com/lists/{idList}/cards", path = {"idList"}, body = {"desc", "due", "idMembers", "labels", "name"} },
    ["trello.add_lists_move_all_cards_by_id_list"] = { method = "POST", url = "https://api.trello.com/lists/{idList}/moveAllCards", path = {"idList"}, body = {"idBoard"} },
    ["trello.add_members_avatar_by_id_member"] = { method = "POST", url = "https://api.trello.com/members/{idMember}/avatar", path = {"idMember"}, body = {"file"} },
    ["trello.add_members_board_backgrounds_by_id_member"] = { method = "POST", url = "https://api.trello.com/members/{idMember}/boardBackgrounds", path = {"idMember"}, body = {"brightness", "file", "tile"} },
    ["trello.add_members_board_stars_by_id_member"] = { method = "POST", url = "https://api.trello.com/members/{idMember}/boardStars", path = {"idMember"}, body = {"idBoard", "pos"} },
    ["trello.add_members_custom_board_backgrounds_by_id_member"] = { method = "POST", url = "https://api.trello.com/members/{idMember}/customBoardBackgrounds", path = {"idMember"}, body = {"brightness", "file", "tile"} },
    ["trello.add_members_custom_emoji_by_id_member"] = { method = "POST", url = "https://api.trello.com/members/{idMember}/customEmoji", path = {"idMember"}, body = {"file", "name"} },
    ["trello.add_members_custom_stickers_by_id_member"] = { method = "POST", url = "https://api.trello.com/members/{idMember}/customStickers", path = {"idMember"}, body = {"file"} },
    ["trello.add_members_one_time_messages_dismissed_by_id_member"] = { method = "POST", url = "https://api.trello.com/members/{idMember}/oneTimeMessagesDismissed", path = {"idMember"}, body = {"value"} },
    ["trello.add_members_saved_searches_by_id_member"] = { method = "POST", url = "https://api.trello.com/members/{idMember}/savedSearches", path = {"idMember"}, body = {"name", "pos", "query"} },
    ["trello.add_notifications_all_read"] = { method = "POST", url = "https://api.trello.com/notifications/all/read" },
    ["trello.add_organizations"] = { method = "POST", url = "https://api.trello.com/organizations", body = {"desc", "displayName", "name", "prefs/associatedDomain", "prefs/boardVisibilityRestrict/org", "prefs/boardVisibilityRestrict/private", "prefs/boardVisibilityRestrict/public", "prefs/externalMembersDisabled", "prefs/googleAppsVersion", "prefs/orgInviteRestrict", "prefs/permissionLevel", "website"} },
    ["trello.add_organizations_logo_by_id_org"] = { method = "POST", url = "https://api.trello.com/organizations/{idOrg}/logo", path = {"idOrg"}, body = {"file"} },
    ["trello.add_sessions"] = { method = "POST", url = "https://api.trello.com/sessions", body = {"idBoard", "status"} },
    ["trello.add_tokens_webhooks_by_token"] = { method = "POST", url = "https://api.trello.com/tokens/{token}/webhooks", body = {"callbackURL", "description", "idModel"} },
    ["trello.add_webhooks"] = { method = "POST", url = "https://api.trello.com/webhooks", body = {"active", "callbackURL", "description", "idModel"} },
    ["trello.delete_actions_by_id_action"] = { method = "DELETE", url = "https://api.trello.com/actions/{idAction}", path = {"idAction"} },
    ["trello.delete_boards_members_by_id_board_by_id_member"] = { method = "DELETE", url = "https://api.trello.com/boards/{idBoard}/members/{idMember}", path = {"idBoard", "idMember"} },
    ["trello.delete_boards_power_ups_by_id_board_by_power_up"] = { method = "DELETE", url = "https://api.trello.com/boards/{idBoard}/powerUps/{powerUp}", path = {"idBoard", "powerUp"} },
    ["trello.delete_cards_actions_comments_by_id_card_by_id_action"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/actions/{idAction}/comments", path = {"idCard", "idAction"} },
    ["trello.delete_cards_attachments_by_id_card_by_id_attachment"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/attachments/{idAttachment}", path = {"idCard", "idAttachment"} },
    ["trello.delete_cards_by_id_card"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}", path = {"idCard"} },
    ["trello.delete_cards_checklist_check_item_by_id_card_by_id_checklist_by_id_check_item"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/checklist/{idChecklist}/checkItem/{idCheckItem}", path = {"idCard", "idChecklist", "idCheckItem"} },
    ["trello.delete_cards_checklists_by_id_card_by_id_checklist"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/checklists/{idChecklist}", path = {"idCard", "idChecklist"} },
    ["trello.delete_cards_id_labels_by_id_card_by_id_label"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/idLabels/{idLabel}", path = {"idCard", "idLabel"} },
    ["trello.delete_cards_id_members_by_id_card_by_id_member"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/idMembers/{idMember}", path = {"idCard", "idMember"} },
    ["trello.delete_cards_labels_by_id_card_by_color"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/labels/{color}", path = {"idCard", "color"} },
    ["trello.delete_cards_members_voted_by_id_card_by_id_member"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/membersVoted/{idMember}", path = {"idCard", "idMember"} },
    ["trello.delete_cards_stickers_by_id_card_by_id_sticker"] = { method = "DELETE", url = "https://api.trello.com/cards/{idCard}/stickers/{idSticker}", path = {"idCard", "idSticker"} },
    ["trello.delete_checklists_by_id_checklist"] = { method = "DELETE", url = "https://api.trello.com/checklists/{idChecklist}", path = {"idChecklist"} },
    ["trello.delete_checklists_check_items_by_id_checklist_by_id_check_item"] = { method = "DELETE", url = "https://api.trello.com/checklists/{idChecklist}/checkItems/{idCheckItem}", path = {"idChecklist", "idCheckItem"} },
    ["trello.delete_labels_by_id_label"] = { method = "DELETE", url = "https://api.trello.com/labels/{idLabel}", path = {"idLabel"} },
    ["trello.delete_members_board_backgrounds_by_id_member_by_id_board_background"] = { method = "DELETE", url = "https://api.trello.com/members/{idMember}/boardBackgrounds/{idBoardBackground}", path = {"idMember", "idBoardBackground"} },
    ["trello.delete_members_board_stars_by_id_member_by_id_board_star"] = { method = "DELETE", url = "https://api.trello.com/members/{idMember}/boardStars/{idBoardStar}", path = {"idMember", "idBoardStar"} },
    ["trello.delete_members_custom_board_backgrounds_by_id_member_by_id_board_background"] = { method = "DELETE", url = "https://api.trello.com/members/{idMember}/customBoardBackgrounds/{idBoardBackground}", path = {"idMember", "idBoardBackground"} },
    ["trello.delete_members_custom_stickers_by_id_member_by_id_custom_sticker"] = { method = "DELETE", url = "https://api.trello.com/members/{idMember}/customStickers/{idCustomSticker}", path = {"idMember", "idCustomSticker"} },
    ["trello.delete_members_saved_searches_by_id_member_by_id_saved_search"] = { method = "DELETE", url = "https://api.trello.com/members/{idMember}/savedSearches/{idSavedSearch}", path = {"idMember", "idSavedSearch"} },
    ["trello.delete_organizations_by_id_org"] = { method = "DELETE", url = "https://api.trello.com/organizations/{idOrg}", path = {"idOrg"} },
    ["trello.delete_organizations_logo_by_id_org"] = { method = "DELETE", url = "https://api.trello.com/organizations/{idOrg}/logo", path = {"idOrg"} },
    ["trello.delete_organizations_members_all_by_id_org_by_id_member"] = { method = "DELETE", url = "https://api.trello.com/organizations/{idOrg}/members/{idMember}/all", path = {"idOrg", "idMember"} },
    ["trello.delete_organizations_members_by_id_org_by_id_member"] = { method = "DELETE", url = "https://api.trello.com/organizations/{idOrg}/members/{idMember}", path = {"idOrg", "idMember"} },
    ["trello.delete_organizations_prefs_associated_domain_by_id_org"] = { method = "DELETE", url = "https://api.trello.com/organizations/{idOrg}/prefs/associatedDomain", path = {"idOrg"} },
    ["trello.delete_organizations_prefs_org_invite_restrict_by_id_org"] = { method = "DELETE", url = "https://api.trello.com/organizations/{idOrg}/prefs/orgInviteRestrict", path = {"idOrg"}, query = {"value"} },
    ["trello.delete_tokens_by_token"] = { method = "DELETE", url = "https://api.trello.com/tokens/{token}" },
    ["trello.delete_tokens_webhooks_by_token_by_id_webhook"] = { method = "DELETE", url = "https://api.trello.com/tokens/{token}/webhooks/{idWebhook}", path = {"idWebhook"} },
    ["trello.delete_webhooks_by_id_webhook"] = { method = "DELETE", url = "https://api.trello.com/webhooks/{idWebhook}", path = {"idWebhook"} },
    ["trello.get_actions_board_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/board", path = {"idAction"}, query = {"fields"} },
    ["trello.get_actions_board_by_id_action_by_field"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/board/{field}", path = {"idAction", "field"} },
    ["trello.get_actions_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}", path = {"idAction"}, query = {"display", "entities", "fields", "member", "member_fields", "memberCreator", "memberCreator_fields"} },
    ["trello.get_actions_by_id_action_by_field"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/{field}", path = {"idAction", "field"} },
    ["trello.get_actions_card_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/card", path = {"idAction"}, query = {"fields"} },
    ["trello.get_actions_card_by_id_action_by_field"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/card/{field}", path = {"idAction", "field"} },
    ["trello.get_actions_display_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/display", path = {"idAction"} },
    ["trello.get_actions_entities_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/entities", path = {"idAction"} },
    ["trello.get_actions_list_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/list", path = {"idAction"}, query = {"fields"} },
    ["trello.get_actions_list_by_id_action_by_field"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/list/{field}", path = {"idAction", "field"} },
    ["trello.get_actions_member_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/member", path = {"idAction"}, query = {"fields"} },
    ["trello.get_actions_member_by_id_action_by_field"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/member/{field}", path = {"idAction", "field"} },
    ["trello.get_actions_member_creator_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/memberCreator", path = {"idAction"}, query = {"fields"} },
    ["trello.get_actions_member_creator_by_id_action_by_field"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/memberCreator/{field}", path = {"idAction", "field"} },
    ["trello.get_actions_organization_by_id_action"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/organization", path = {"idAction"}, query = {"fields"} },
    ["trello.get_actions_organization_by_id_action_by_field"] = { method = "GET", url = "https://api.trello.com/actions/{idAction}/organization/{field}", path = {"idAction", "field"} },
    ["trello.get_batch"] = { method = "GET", url = "https://api.trello.com/batch", query = {"urls"} },
    ["trello.get_boards_actions_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/actions", path = {"idBoard"}, query = {"entities", "display", "filter", "fields", "limit", "format", "since", "before", "page", "idModels", "member", "member_fields", "memberCreator", "memberCreator_fields"} },
    ["trello.get_boards_board_stars_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/boardStars", path = {"idBoard"}, query = {"filter"} },
    ["trello.get_boards_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}", path = {"idBoard"}, query = {"actions", "actions_entities", "actions_display", "actions_format", "actions_since", "actions_limit", "action_fields", "action_member", "action_member_fields", "action_memberCreator", "action_memberCreator_fields", "cards", "card_fields", "card_attachments", "card_attachment_fields", "card_checklists", "card_stickers", "boardStars", "labels", "label_fields", "labels_limit", "lists", "list_fields", "memberships", "memberships_member", "memberships_member_fields", "members", "member_fields", "membersInvited", "membersInvited_fields", "checklists", "checklist_fields", "organization", "organization_fields", "organization_memberships", "myPrefs", "fields"} },
    ["trello.get_boards_by_id_board_by_field"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/{field}", path = {"idBoard", "field"} },
    ["trello.get_boards_cards_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/cards", path = {"idBoard"}, query = {"actions", "attachments", "attachment_fields", "stickers", "members", "member_fields", "checkItemStates", "checklists", "limit", "since", "before", "filter", "fields"} },
    ["trello.get_boards_cards_by_id_board_by_filter"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/cards/{filter}", path = {"idBoard", "filter"} },
    ["trello.get_boards_cards_by_id_board_by_id_card"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/cards/{idCard}", path = {"idBoard", "idCard"}, query = {"attachments", "attachment_fields", "actions", "actions_entities", "actions_display", "actions_limit", "action_fields", "action_memberCreator_fields", "members", "member_fields", "checkItemStates", "checkItemState_fields", "labels", "checklists", "checklist_fields", "fields"} },
    ["trello.get_boards_checklists_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/checklists", path = {"idBoard"}, query = {"cards", "card_fields", "checkItems", "checkItem_fields", "filter", "fields"} },
    ["trello.get_boards_deltas_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/deltas", path = {"idBoard"}, query = {"tags", "ixLastUpdate"} },
    ["trello.get_boards_labels_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/labels", path = {"idBoard"}, query = {"fields", "limit"} },
    ["trello.get_boards_labels_by_id_board_by_id_label"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/labels/{idLabel}", path = {"idBoard", "idLabel"}, query = {"fields"} },
    ["trello.get_boards_lists_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/lists", path = {"idBoard"}, query = {"cards", "card_fields", "filter", "fields"} },
    ["trello.get_boards_lists_by_id_board_by_filter"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/lists/{filter}", path = {"idBoard", "filter"} },
    ["trello.get_boards_members_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/members", path = {"idBoard"}, query = {"filter", "fields", "activity"} },
    ["trello.get_boards_members_by_id_board_by_filter"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/members/{filter}", path = {"idBoard", "filter"} },
    ["trello.get_boards_members_cards_by_id_board_by_id_member"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/members/{idMember}/cards", path = {"idBoard", "idMember"}, query = {"actions", "attachments", "attachment_fields", "members", "member_fields", "checkItemStates", "checklists", "board", "board_fields", "list", "list_fields", "filter", "fields"} },
    ["trello.get_boards_members_invited_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/membersInvited", path = {"idBoard"}, query = {"fields"} },
    ["trello.get_boards_members_invited_by_id_board_by_field"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/membersInvited/{field}", path = {"idBoard", "field"} },
    ["trello.get_boards_memberships_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/memberships", path = {"idBoard"}, query = {"filter", "member", "member_fields"} },
    ["trello.get_boards_memberships_by_id_board_by_id_membership"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/memberships/{idMembership}", path = {"idBoard", "idMembership"}, query = {"member", "member_fields"} },
    ["trello.get_boards_my_prefs_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/myPrefs", path = {"idBoard"} },
    ["trello.get_boards_organization_by_id_board"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/organization", path = {"idBoard"}, query = {"fields"} },
    ["trello.get_boards_organization_by_id_board_by_field"] = { method = "GET", url = "https://api.trello.com/boards/{idBoard}/organization/{field}", path = {"idBoard", "field"} },
    ["trello.get_cards_actions_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/actions", path = {"idCard"}, query = {"entities", "display", "filter", "fields", "limit", "format", "since", "before", "page", "idModels", "member", "member_fields", "memberCreator", "memberCreator_fields"} },
    ["trello.get_cards_attachments_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/attachments", path = {"idCard"}, query = {"fields", "filter"} },
    ["trello.get_cards_attachments_by_id_card_by_id_attachment"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/attachments/{idAttachment}", path = {"idCard", "idAttachment"}, query = {"fields"} },
    ["trello.get_cards_board_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/board", path = {"idCard"}, query = {"fields"} },
    ["trello.get_cards_board_by_id_card_by_field"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/board/{field}", path = {"idCard", "field"} },
    ["trello.get_cards_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}", path = {"idCard"}, query = {"actions", "actions_entities", "actions_display", "actions_limit", "action_fields", "action_memberCreator_fields", "attachments", "attachment_fields", "members", "member_fields", "membersVoted", "memberVoted_fields", "checkItemStates", "checkItemState_fields", "checklists", "checklist_fields", "board", "board_fields", "list", "list_fields", "stickers", "sticker_fields", "fields"} },
    ["trello.get_cards_by_id_card_by_field"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/{field}", path = {"idCard", "field"} },
    ["trello.get_cards_check_item_states_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/checkItemStates", path = {"idCard"}, query = {"fields"} },
    ["trello.get_cards_checklists_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/checklists", path = {"idCard"}, query = {"cards", "card_fields", "checkItems", "checkItem_fields", "filter", "fields"} },
    ["trello.get_cards_list_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/list", path = {"idCard"}, query = {"fields"} },
    ["trello.get_cards_list_by_id_card_by_field"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/list/{field}", path = {"idCard", "field"} },
    ["trello.get_cards_members_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/members", path = {"idCard"}, query = {"fields"} },
    ["trello.get_cards_members_voted_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/membersVoted", path = {"idCard"}, query = {"fields"} },
    ["trello.get_cards_stickers_by_id_card"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/stickers", path = {"idCard"}, query = {"fields"} },
    ["trello.get_cards_stickers_by_id_card_by_id_sticker"] = { method = "GET", url = "https://api.trello.com/cards/{idCard}/stickers/{idSticker}", path = {"idCard", "idSticker"}, query = {"fields"} },
    ["trello.get_checklists_board_by_id_checklist"] = { method = "GET", url = "https://api.trello.com/checklists/{idChecklist}/board", path = {"idChecklist"}, query = {"fields"} },
    ["trello.get_checklists_board_by_id_checklist_by_field"] = { method = "GET", url = "https://api.trello.com/checklists/{idChecklist}/board/{field}", path = {"idChecklist", "field"} },
    ["trello.get_checklists_by_id_checklist"] = { method = "GET", url = "https://api.trello.com/checklists/{idChecklist}", path = {"idChecklist"}, query = {"cards", "card_fields", "checkItems", "checkItem_fields", "fields"} },
    ["trello.get_checklists_by_id_checklist_by_field"] = { method = "GET", url = "https://api.trello.com/checklists/{idChecklist}/{field}", path = {"idChecklist", "field"} },
    ["trello.get_checklists_cards_by_id_checklist"] = { method = "GET", url = "https://api.trello.com/checklists/{idChecklist}/cards", path = {"idChecklist"}, query = {"actions", "attachments", "attachment_fields", "stickers", "members", "member_fields", "checkItemStates", "checklists", "limit", "since", "before", "filter", "fields"} },
    ["trello.get_checklists_cards_by_id_checklist_by_filter"] = { method = "GET", url = "https://api.trello.com/checklists/{idChecklist}/cards/{filter}", path = {"idChecklist", "filter"} },
    ["trello.get_checklists_check_items_by_id_checklist"] = { method = "GET", url = "https://api.trello.com/checklists/{idChecklist}/checkItems", path = {"idChecklist"}, query = {"filter", "fields"} },
    ["trello.get_checklists_check_items_by_id_checklist_by_id_check_item"] = { method = "GET", url = "https://api.trello.com/checklists/{idChecklist}/checkItems/{idCheckItem}", path = {"idChecklist", "idCheckItem"}, query = {"fields"} },
    ["trello.get_labels_board_by_id_label"] = { method = "GET", url = "https://api.trello.com/labels/{idLabel}/board", path = {"idLabel"}, query = {"fields"} },
    ["trello.get_labels_board_by_id_label_by_field"] = { method = "GET", url = "https://api.trello.com/labels/{idLabel}/board/{field}", path = {"idLabel", "field"} },
    ["trello.get_labels_by_id_label"] = { method = "GET", url = "https://api.trello.com/labels/{idLabel}", path = {"idLabel"}, query = {"fields"} },
    ["trello.get_lists_actions_by_id_list"] = { method = "GET", url = "https://api.trello.com/lists/{idList}/actions", path = {"idList"}, query = {"entities", "display", "filter", "fields", "limit", "format", "since", "before", "page", "idModels", "member", "member_fields", "memberCreator", "memberCreator_fields"} },
    ["trello.get_lists_board_by_id_list"] = { method = "GET", url = "https://api.trello.com/lists/{idList}/board", path = {"idList"}, query = {"fields"} },
    ["trello.get_lists_board_by_id_list_by_field"] = { method = "GET", url = "https://api.trello.com/lists/{idList}/board/{field}", path = {"idList", "field"} },
    ["trello.get_lists_by_id_list"] = { method = "GET", url = "https://api.trello.com/lists/{idList}", path = {"idList"}, query = {"cards", "card_fields", "board", "board_fields", "fields"} },
    ["trello.get_lists_by_id_list_by_field"] = { method = "GET", url = "https://api.trello.com/lists/{idList}/{field}", path = {"idList", "field"} },
    ["trello.get_lists_cards_by_id_list"] = { method = "GET", url = "https://api.trello.com/lists/{idList}/cards", path = {"idList"}, query = {"actions", "attachments", "attachment_fields", "stickers", "members", "member_fields", "checkItemStates", "checklists", "limit", "since", "before", "filter", "fields"} },
    ["trello.get_lists_cards_by_id_list_by_filter"] = { method = "GET", url = "https://api.trello.com/lists/{idList}/cards/{filter}", path = {"idList", "filter"} },
    ["trello.get_members_actions_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/actions", path = {"idMember"}, query = {"entities", "display", "filter", "fields", "limit", "format", "since", "before", "page", "idModels", "member", "member_fields", "memberCreator", "memberCreator_fields"} },
    ["trello.get_members_board_backgrounds_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/boardBackgrounds", path = {"idMember"}, query = {"filter"} },
    ["trello.get_members_board_backgrounds_by_id_member_by_id_board_background"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/boardBackgrounds/{idBoardBackground}", path = {"idMember", "idBoardBackground"}, query = {"fields"} },
    ["trello.get_members_board_stars_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/boardStars", path = {"idMember"} },
    ["trello.get_members_board_stars_by_id_member_by_id_board_star"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/boardStars/{idBoardStar}", path = {"idMember", "idBoardStar"} },
    ["trello.get_members_boards_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/boards", path = {"idMember"}, query = {"filter", "fields", "actions", "actions_entities", "actions_limit", "actions_format", "actions_since", "action_fields", "memberships", "organization", "organization_fields", "lists"} },
    ["trello.get_members_boards_by_id_member_by_filter"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/boards/{filter}", path = {"idMember", "filter"} },
    ["trello.get_members_boards_invited_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/boardsInvited", path = {"idMember"}, query = {"fields"} },
    ["trello.get_members_boards_invited_by_id_member_by_field"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/boardsInvited/{field}", path = {"idMember", "field"} },
    ["trello.get_members_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}", path = {"idMember"}, query = {"actions", "actions_entities", "actions_display", "actions_limit", "action_fields", "action_since", "action_before", "cards", "card_fields", "card_members", "card_member_fields", "card_attachments", "card_attachment_fields", "card_stickers", "boards", "board_fields", "board_actions", "board_actions_entities", "board_actions_display", "board_actions_format", "board_actions_since", "board_actions_limit", "board_action_fields", "board_lists", "board_memberships", "board_organization", "board_organization_fields", "boardsInvited", "boardsInvited_fields", "boardStars", "savedSearches", "organizations", "organization_fields", "organization_paid_account", "organizationsInvited", "organizationsInvited_fields", "notifications", "notifications_entities", "notifications_display", "notifications_limit", "notification_fields", "notification_memberCreator", "notification_memberCreator_fields", "notification_before", "notification_since", "tokens", "paid_account", "boardBackgrounds", "customBoardBackgrounds", "customStickers", "customEmoji", "fields"} },
    ["trello.get_members_by_id_member_by_field"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/{field}", path = {"idMember", "field"} },
    ["trello.get_members_cards_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/cards", path = {"idMember"}, query = {"actions", "attachments", "attachment_fields", "stickers", "members", "member_fields", "checkItemStates", "checklists", "limit", "since", "before", "filter", "fields"} },
    ["trello.get_members_cards_by_id_member_by_filter"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/cards/{filter}", path = {"idMember", "filter"} },
    ["trello.get_members_custom_board_backgrounds_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/customBoardBackgrounds", path = {"idMember"}, query = {"filter"} },
    ["trello.get_members_custom_board_backgrounds_by_id_member_by_id_board_background"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/customBoardBackgrounds/{idBoardBackground}", path = {"idMember", "idBoardBackground"}, query = {"fields"} },
    ["trello.get_members_custom_emoji_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/customEmoji", path = {"idMember"}, query = {"filter"} },
    ["trello.get_members_custom_emoji_by_id_member_by_id_custom_emoji"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/customEmoji/{idCustomEmoji}", path = {"idMember", "idCustomEmoji"}, query = {"fields"} },
    ["trello.get_members_custom_stickers_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/customStickers", path = {"idMember"}, query = {"filter"} },
    ["trello.get_members_custom_stickers_by_id_member_by_id_custom_sticker"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/customStickers/{idCustomSticker}", path = {"idMember", "idCustomSticker"}, query = {"fields"} },
    ["trello.get_members_deltas_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/deltas", path = {"idMember"}, query = {"tags", "ixLastUpdate"} },
    ["trello.get_members_notifications_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/notifications", path = {"idMember"}, query = {"entities", "display", "filter", "read_filter", "fields", "limit", "page", "before", "since", "memberCreator", "memberCreator_fields"} },
    ["trello.get_members_notifications_by_id_member_by_filter"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/notifications/{filter}", path = {"idMember", "filter"} },
    ["trello.get_members_organizations_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/organizations", path = {"idMember"}, query = {"filter", "fields", "paid_account"} },
    ["trello.get_members_organizations_by_id_member_by_filter"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/organizations/{filter}", path = {"idMember", "filter"} },
    ["trello.get_members_organizations_invited_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/organizationsInvited", path = {"idMember"}, query = {"fields"} },
    ["trello.get_members_organizations_invited_by_id_member_by_field"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/organizationsInvited/{field}", path = {"idMember", "field"} },
    ["trello.get_members_saved_searches_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/savedSearches", path = {"idMember"} },
    ["trello.get_members_saved_searches_by_id_member_by_id_saved_search"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/savedSearches/{idSavedSearch}", path = {"idMember", "idSavedSearch"} },
    ["trello.get_members_tokens_by_id_member"] = { method = "GET", url = "https://api.trello.com/members/{idMember}/tokens", path = {"idMember"}, query = {"filter"} },
    ["trello.get_notifications_board_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/board", path = {"idNotification"}, query = {"fields"} },
    ["trello.get_notifications_board_by_id_notification_by_field"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/board/{field}", path = {"idNotification", "field"} },
    ["trello.get_notifications_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}", path = {"idNotification"}, query = {"display", "entities", "fields", "memberCreator", "memberCreator_fields", "board", "board_fields", "list", "card", "card_fields", "organization", "organization_fields", "member", "member_fields"} },
    ["trello.get_notifications_by_id_notification_by_field"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/{field}", path = {"idNotification", "field"} },
    ["trello.get_notifications_card_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/card", path = {"idNotification"}, query = {"fields"} },
    ["trello.get_notifications_card_by_id_notification_by_field"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/card/{field}", path = {"idNotification", "field"} },
    ["trello.get_notifications_display_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/display", path = {"idNotification"} },
    ["trello.get_notifications_entities_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/entities", path = {"idNotification"} },
    ["trello.get_notifications_list_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/list", path = {"idNotification"}, query = {"fields"} },
    ["trello.get_notifications_list_by_id_notification_by_field"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/list/{field}", path = {"idNotification", "field"} },
    ["trello.get_notifications_member_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/member", path = {"idNotification"}, query = {"fields"} },
    ["trello.get_notifications_member_by_id_notification_by_field"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/member/{field}", path = {"idNotification", "field"} },
    ["trello.get_notifications_member_creator_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/memberCreator", path = {"idNotification"}, query = {"fields"} },
    ["trello.get_notifications_member_creator_by_id_notification_by_field"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/memberCreator/{field}", path = {"idNotification", "field"} },
    ["trello.get_notifications_organization_by_id_notification"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/organization", path = {"idNotification"}, query = {"fields"} },
    ["trello.get_notifications_organization_by_id_notification_by_field"] = { method = "GET", url = "https://api.trello.com/notifications/{idNotification}/organization/{field}", path = {"idNotification", "field"} },
    ["trello.get_organizations_actions_by_id_org"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/actions", path = {"idOrg"}, query = {"entities", "display", "filter", "fields", "limit", "format", "since", "before", "page", "idModels", "member", "member_fields", "memberCreator", "memberCreator_fields"} },
    ["trello.get_organizations_boards_by_id_org"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/boards", path = {"idOrg"}, query = {"filter", "fields", "actions", "actions_entities", "actions_limit", "actions_format", "actions_since", "action_fields", "memberships", "organization", "organization_fields", "lists"} },
    ["trello.get_organizations_boards_by_id_org_by_filter"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/boards/{filter}", path = {"idOrg", "filter"} },
    ["trello.get_organizations_by_id_org"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}", path = {"idOrg"}, query = {"actions", "actions_entities", "actions_display", "actions_limit", "action_fields", "memberships", "memberships_member", "memberships_member_fields", "members", "member_fields", "member_activity", "membersInvited", "membersInvited_fields", "boards", "board_fields", "board_actions", "board_actions_entities", "board_actions_display", "board_actions_format", "board_actions_since", "board_actions_limit", "board_action_fields", "board_lists", "paid_account", "fields"} },
    ["trello.get_organizations_by_id_org_by_field"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/{field}", path = {"idOrg", "field"} },
    ["trello.get_organizations_deltas_by_id_org"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/deltas", path = {"idOrg"}, query = {"tags", "ixLastUpdate"} },
    ["trello.get_organizations_members_by_id_org"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/members", path = {"idOrg"}, query = {"filter", "fields", "activity"} },
    ["trello.get_organizations_members_by_id_org_by_filter"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/members/{filter}", path = {"idOrg", "filter"} },
    ["trello.get_organizations_members_cards_by_id_org_by_id_member"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/members/{idMember}/cards", path = {"idOrg", "idMember"}, query = {"actions", "attachments", "attachment_fields", "members", "member_fields", "checkItemStates", "checklists", "board", "board_fields", "list", "list_fields", "filter", "fields"} },
    ["trello.get_organizations_members_invited_by_id_org"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/membersInvited", path = {"idOrg"}, query = {"fields"} },
    ["trello.get_organizations_members_invited_by_id_org_by_field"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/membersInvited/{field}", path = {"idOrg", "field"} },
    ["trello.get_organizations_memberships_by_id_org"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/memberships", path = {"idOrg"}, query = {"filter", "member", "member_fields"} },
    ["trello.get_organizations_memberships_by_id_org_by_id_membership"] = { method = "GET", url = "https://api.trello.com/organizations/{idOrg}/memberships/{idMembership}", path = {"idOrg", "idMembership"}, query = {"member", "member_fields"} },
    ["trello.get_search"] = { method = "GET", url = "https://api.trello.com/search", query = {"query", "idBoards", "idOrganizations", "idCards", "modelTypes", "board_fields", "boards_limit", "card_fields", "cards_limit", "cards_page", "card_board", "card_list", "card_members", "card_stickers", "card_attachments", "organization_fields", "organizations_limit", "member_fields", "members_limit", "partial"} },
    ["trello.get_search_members"] = { method = "GET", url = "https://api.trello.com/search/members", query = {"query", "limit", "idBoard", "idOrganization", "onlyOrgMembers"} },
    ["trello.get_sessions_socket"] = { method = "GET", url = "https://api.trello.com/sessions/socket" },
    ["trello.get_tokens_by_token"] = { method = "GET", url = "https://api.trello.com/tokens/{token}", query = {"fields", "webhooks"} },
    ["trello.get_tokens_by_token_by_field"] = { method = "GET", url = "https://api.trello.com/tokens/{token}/{field}", path = {"field"} },
    ["trello.get_tokens_member_by_token"] = { method = "GET", url = "https://api.trello.com/tokens/{token}/member", query = {"fields"} },
    ["trello.get_tokens_member_by_token_by_field"] = { method = "GET", url = "https://api.trello.com/tokens/{token}/member/{field}", path = {"field"} },
    ["trello.get_tokens_webhooks_by_token"] = { method = "GET", url = "https://api.trello.com/tokens/{token}/webhooks" },
    ["trello.get_tokens_webhooks_by_token_by_id_webhook"] = { method = "GET", url = "https://api.trello.com/tokens/{token}/webhooks/{idWebhook}", path = {"idWebhook"} },
    ["trello.get_types_by_id"] = { method = "GET", url = "https://api.trello.com/types/{id}", path = {"id"} },
    ["trello.get_webhooks_by_id_webhook"] = { method = "GET", url = "https://api.trello.com/webhooks/{idWebhook}", path = {"idWebhook"} },
    ["trello.get_webhooks_by_id_webhook_by_field"] = { method = "GET", url = "https://api.trello.com/webhooks/{idWebhook}/{field}", path = {"idWebhook", "field"} },
    ["trello.update_actions_by_id_action"] = { method = "PUT", url = "https://api.trello.com/actions/{idAction}", path = {"idAction"}, body = {"text"} },
    ["trello.update_actions_text_by_id_action"] = { method = "PUT", url = "https://api.trello.com/actions/{idAction}/text", path = {"idAction"}, body = {"value"} },
    ["trello.update_boards_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}", path = {"idBoard"}, body = {"closed", "desc", "idBoardSource", "idOrganization", "keepFromSource", "labelNames/blue", "labelNames/green", "labelNames/orange", "labelNames/purple", "labelNames/red", "labelNames/yellow", "name", "powerUps", "prefs/background", "prefs/calendarFeedEnabled", "prefs/cardAging", "prefs/cardCovers", "prefs/comments", "prefs/invitations", "prefs/permissionLevel", "prefs/selfJoin", "prefs/voting", "prefs_background", "prefs_cardAging", "prefs_cardCovers", "prefs_comments", "prefs_invitations", "prefs_permissionLevel", "prefs_selfJoin", "prefs_voting", "subscribed"} },
    ["trello.update_boards_closed_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/closed", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_desc_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/desc", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_id_organization_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/idOrganization", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_label_names_blue_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/labelNames/blue", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_label_names_green_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/labelNames/green", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_label_names_orange_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/labelNames/orange", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_label_names_purple_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/labelNames/purple", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_label_names_red_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/labelNames/red", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_label_names_yellow_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/labelNames/yellow", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_members_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/members", path = {"idBoard"} },
    ["trello.update_boards_members_by_id_board_by_id_member"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/members/{idMember}", path = {"idBoard", "idMember"} },
    ["trello.update_boards_memberships_by_id_board_by_id_membership"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/memberships/{idMembership}", path = {"idBoard", "idMembership"}, body = {"member_fields", "type"} },
    ["trello.update_boards_my_prefs_email_position_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/myPrefs/emailPosition", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_my_prefs_id_email_list_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/myPrefs/idEmailList", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_my_prefs_show_list_guide_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/myPrefs/showListGuide", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_my_prefs_show_sidebar_activity_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/myPrefs/showSidebarActivity", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_my_prefs_show_sidebar_board_actions_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/myPrefs/showSidebarBoardActions", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_my_prefs_show_sidebar_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/myPrefs/showSidebar", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_my_prefs_show_sidebar_members_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/myPrefs/showSidebarMembers", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_name_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/name", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_prefs_background_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/background", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_prefs_calendar_feed_enabled_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/calendarFeedEnabled", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_prefs_card_aging_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/cardAging", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_prefs_card_covers_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/cardCovers", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_prefs_comments_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/comments", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_prefs_invitations_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/invitations", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_prefs_permission_level_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/permissionLevel", path = {"idBoard"} },
    ["trello.update_boards_prefs_self_join_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/selfJoin", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_prefs_voting_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/prefs/voting", path = {"idBoard"}, body = {"value"} },
    ["trello.update_boards_subscribed_by_id_board"] = { method = "PUT", url = "https://api.trello.com/boards/{idBoard}/subscribed", path = {"idBoard"}, body = {"value"} },
    ["trello.update_cards_actions_comments_by_id_card_by_id_action"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/actions/{idAction}/comments", path = {"idCard", "idAction"}, body = {"text"} },
    ["trello.update_cards_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}", path = {"idCard"}, body = {"closed", "desc", "due", "fileSource", "idAttachmentCover", "idBoard", "idCardSource", "idLabels", "idList", "idMembers", "keepFromSource", "labels", "name", "pos", "subscribed", "urlSource"} },
    ["trello.update_cards_checklist_check_item_by_id_card_by_id_checklist_current_by_id_check_item"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/checklist/{idChecklistCurrent}/checkItem/{idCheckItem}", path = {"idCard", "idChecklistCurrent", "idCheckItem"}, body = {"idChecklist", "name", "pos", "state"} },
    ["trello.update_cards_checklist_check_item_name_by_id_card_by_id_checklist_by_id_check_item"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/checklist/{idChecklist}/checkItem/{idCheckItem}/name", path = {"idCard", "idChecklist", "idCheckItem"}, body = {"value"} },
    ["trello.update_cards_checklist_check_item_pos_by_id_card_by_id_checklist_by_id_check_item"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/checklist/{idChecklist}/checkItem/{idCheckItem}/pos", path = {"idCard", "idChecklist", "idCheckItem"}, body = {"value"} },
    ["trello.update_cards_checklist_check_item_state_by_id_card_by_id_checklist_by_id_check_item"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/checklist/{idChecklist}/checkItem/{idCheckItem}/state", path = {"idCard", "idChecklist", "idCheckItem"}, body = {"value"} },
    ["trello.update_cards_closed_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/closed", path = {"idCard"}, body = {"value"} },
    ["trello.update_cards_desc_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/desc", path = {"idCard"}, body = {"value"} },
    ["trello.update_cards_due_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/due", path = {"idCard"}, body = {"value"} },
    ["trello.update_cards_id_attachment_cover_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/idAttachmentCover", path = {"idCard"}, body = {"value"} },
    ["trello.update_cards_id_board_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/idBoard", path = {"idCard"}, body = {"idList", "value"} },
    ["trello.update_cards_id_list_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/idList", path = {"idCard"}, body = {"value"} },
    ["trello.update_cards_id_members_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/idMembers", path = {"idCard"}, body = {"value"} },
    ["trello.update_cards_labels_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/labels", path = {"idCard"}, body = {"color", "name", "value"} },
    ["trello.update_cards_name_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/name", path = {"idCard"}, body = {"value"} },
    ["trello.update_cards_pos_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/pos", path = {"idCard"}, body = {"value"} },
    ["trello.update_cards_stickers_by_id_card_by_id_sticker"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/stickers/{idSticker}", path = {"idCard", "idSticker"}, body = {"image", "left", "rotate", "top", "zIndex"} },
    ["trello.update_cards_subscribed_by_id_card"] = { method = "PUT", url = "https://api.trello.com/cards/{idCard}/subscribed", path = {"idCard"}, body = {"value"} },
    ["trello.update_checklists_by_id_checklist"] = { method = "PUT", url = "https://api.trello.com/checklists/{idChecklist}", path = {"idChecklist"}, body = {"idBoard", "idCard", "idChecklistSource", "name", "pos"} },
    ["trello.update_checklists_id_card_by_id_checklist"] = { method = "PUT", url = "https://api.trello.com/checklists/{idChecklist}/idCard", path = {"idChecklist"}, body = {"value"} },
    ["trello.update_checklists_name_by_id_checklist"] = { method = "PUT", url = "https://api.trello.com/checklists/{idChecklist}/name", path = {"idChecklist"}, body = {"value"} },
    ["trello.update_checklists_pos_by_id_checklist"] = { method = "PUT", url = "https://api.trello.com/checklists/{idChecklist}/pos", path = {"idChecklist"}, body = {"value"} },
    ["trello.update_labels_by_id_label"] = { method = "PUT", url = "https://api.trello.com/labels/{idLabel}", path = {"idLabel"}, body = {"color", "idBoard", "name"} },
    ["trello.update_labels_color_by_id_label"] = { method = "PUT", url = "https://api.trello.com/labels/{idLabel}/color", path = {"idLabel"}, body = {"value"} },
    ["trello.update_labels_name_by_id_label"] = { method = "PUT", url = "https://api.trello.com/labels/{idLabel}/name", path = {"idLabel"}, body = {"value"} },
    ["trello.update_lists_by_id_list"] = { method = "PUT", url = "https://api.trello.com/lists/{idList}", path = {"idList"}, body = {"closed", "idBoard", "idListSource", "name", "pos", "subscribed"} },
    ["trello.update_lists_closed_by_id_list"] = { method = "PUT", url = "https://api.trello.com/lists/{idList}/closed", path = {"idList"}, body = {"value"} },
    ["trello.update_lists_id_board_by_id_list"] = { method = "PUT", url = "https://api.trello.com/lists/{idList}/idBoard", path = {"idList"}, body = {"pos", "value"} },
    ["trello.update_lists_name_by_id_list"] = { method = "PUT", url = "https://api.trello.com/lists/{idList}/name", path = {"idList"}, body = {"value"} },
    ["trello.update_lists_pos_by_id_list"] = { method = "PUT", url = "https://api.trello.com/lists/{idList}/pos", path = {"idList"}, body = {"value"} },
    ["trello.update_lists_subscribed_by_id_list"] = { method = "PUT", url = "https://api.trello.com/lists/{idList}/subscribed", path = {"idList"}, body = {"value"} },
    ["trello.update_members_avatar_source_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/avatarSource", path = {"idMember"}, body = {"value"} },
    ["trello.update_members_bio_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/bio", path = {"idMember"}, body = {"value"} },
    ["trello.update_members_board_backgrounds_by_id_member_by_id_board_background"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/boardBackgrounds/{idBoardBackground}", path = {"idMember", "idBoardBackground"}, body = {"brightness", "file", "tile"} },
    ["trello.update_members_board_stars_by_id_member_by_id_board_star"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/boardStars/{idBoardStar}", path = {"idMember", "idBoardStar"}, body = {"idBoard", "pos"} },
    ["trello.update_members_board_stars_id_board_by_id_member_by_id_board_star"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/boardStars/{idBoardStar}/idBoard", path = {"idMember", "idBoardStar"}, body = {"value"} },
    ["trello.update_members_board_stars_pos_by_id_member_by_id_board_star"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/boardStars/{idBoardStar}/pos", path = {"idMember", "idBoardStar"}, body = {"value"} },
    ["trello.update_members_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}", path = {"idMember"}, body = {"avatarSource", "bio", "fullName", "initials", "prefs/colorBlind", "prefs/locale", "prefs/minutesBetweenSummaries", "username"} },
    ["trello.update_members_custom_board_backgrounds_by_id_member_by_id_board_background"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/customBoardBackgrounds/{idBoardBackground}", path = {"idMember", "idBoardBackground"}, body = {"brightness", "file", "tile"} },
    ["trello.update_members_full_name_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/fullName", path = {"idMember"}, body = {"value"} },
    ["trello.update_members_initials_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/initials", path = {"idMember"}, body = {"value"} },
    ["trello.update_members_prefs_color_blind_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/prefs/colorBlind", path = {"idMember"}, body = {"value"} },
    ["trello.update_members_prefs_locale_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/prefs/locale", path = {"idMember"}, body = {"value"} },
    ["trello.update_members_prefs_minutes_between_summaries_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/prefs/minutesBetweenSummaries", path = {"idMember"}, body = {"value"} },
    ["trello.update_members_saved_searches_by_id_member_by_id_saved_search"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/savedSearches/{idSavedSearch}", path = {"idMember", "idSavedSearch"}, body = {"name", "pos", "query"} },
    ["trello.update_members_saved_searches_name_by_id_member_by_id_saved_search"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/savedSearches/{idSavedSearch}/name", path = {"idMember", "idSavedSearch"}, body = {"value"} },
    ["trello.update_members_saved_searches_pos_by_id_member_by_id_saved_search"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/savedSearches/{idSavedSearch}/pos", path = {"idMember", "idSavedSearch"}, body = {"value"} },
    ["trello.update_members_saved_searches_query_by_id_member_by_id_saved_search"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/savedSearches/{idSavedSearch}/query", path = {"idMember", "idSavedSearch"}, body = {"value"} },
    ["trello.update_members_username_by_id_member"] = { method = "PUT", url = "https://api.trello.com/members/{idMember}/username", path = {"idMember"}, body = {"value"} },
    ["trello.update_notifications_by_id_notification"] = { method = "PUT", url = "https://api.trello.com/notifications/{idNotification}", path = {"idNotification"}, body = {"unread"} },
    ["trello.update_notifications_unread_by_id_notification"] = { method = "PUT", url = "https://api.trello.com/notifications/{idNotification}/unread", path = {"idNotification"}, body = {"value"} },
    ["trello.update_organizations_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}", path = {"idOrg"}, body = {"desc", "displayName", "name", "prefs/associatedDomain", "prefs/boardVisibilityRestrict/org", "prefs/boardVisibilityRestrict/private", "prefs/boardVisibilityRestrict/public", "prefs/externalMembersDisabled", "prefs/googleAppsVersion", "prefs/orgInviteRestrict", "prefs/permissionLevel", "website"} },
    ["trello.update_organizations_desc_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/desc", path = {"idOrg"}, body = {"value"} },
    ["trello.update_organizations_display_name_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/displayName", path = {"idOrg"}, body = {"value"} },
    ["trello.update_organizations_members_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/members", path = {"idOrg"} },
    ["trello.update_organizations_members_by_id_org_by_id_member"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/members/{idMember}", path = {"idOrg", "idMember"} },
    ["trello.update_organizations_members_deactivated_by_id_org_by_id_member"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/members/{idMember}/deactivated", path = {"idOrg", "idMember"}, body = {"value"} },
    ["trello.update_organizations_memberships_by_id_org_by_id_membership"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/memberships/{idMembership}", path = {"idOrg", "idMembership"}, body = {"member_fields", "type"} },
    ["trello.update_organizations_name_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/name", path = {"idOrg"}, body = {"value"} },
    ["trello.update_organizations_prefs_associated_domain_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/prefs/associatedDomain", path = {"idOrg"}, body = {"value"} },
    ["trello.update_organizations_prefs_board_visibility_restrict_org_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/prefs/boardVisibilityRestrict/org", path = {"idOrg"} },
    ["trello.update_organizations_prefs_board_visibility_restrict_private_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/prefs/boardVisibilityRestrict/private", path = {"idOrg"} },
    ["trello.update_organizations_prefs_board_visibility_restrict_public_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/prefs/boardVisibilityRestrict/public", path = {"idOrg"} },
    ["trello.update_organizations_prefs_external_members_disabled_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/prefs/externalMembersDisabled", path = {"idOrg"}, body = {"value"} },
    ["trello.update_organizations_prefs_google_apps_version_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/prefs/googleAppsVersion", path = {"idOrg"}, body = {"value"} },
    ["trello.update_organizations_prefs_org_invite_restrict_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/prefs/orgInviteRestrict", path = {"idOrg"}, body = {"value"} },
    ["trello.update_organizations_prefs_permission_level_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/prefs/permissionLevel", path = {"idOrg"} },
    ["trello.update_organizations_website_by_id_org"] = { method = "PUT", url = "https://api.trello.com/organizations/{idOrg}/website", path = {"idOrg"}, body = {"value"} },
    ["trello.update_sessions_by_id_session"] = { method = "PUT", url = "https://api.trello.com/sessions/{idSession}", path = {"idSession"}, body = {"idBoard", "status"} },
    ["trello.update_sessions_status_by_id_session"] = { method = "PUT", url = "https://api.trello.com/sessions/{idSession}/status", path = {"idSession"}, body = {"value"} },
    ["trello.update_tokens_webhooks_by_token"] = { method = "PUT", url = "https://api.trello.com/tokens/{token}/webhooks", body = {"callbackURL", "description", "idModel"} },
    ["trello.update_webhooks"] = { method = "PUT", url = "https://api.trello.com/webhooks/" },
    ["trello.update_webhooks_active_by_id_webhook"] = { method = "PUT", url = "https://api.trello.com/webhooks/{idWebhook}/active", path = {"idWebhook"}, body = {"value"} },
    ["trello.update_webhooks_by_id_webhook"] = { method = "PUT", url = "https://api.trello.com/webhooks/{idWebhook}", path = {"idWebhook"} },
    ["trello.update_webhooks_callback_urlby_id_webhook"] = { method = "PUT", url = "https://api.trello.com/webhooks/{idWebhook}/callbackURL", path = {"idWebhook"}, body = {"value"} },
    ["trello.update_webhooks_description_by_id_webhook"] = { method = "PUT", url = "https://api.trello.com/webhooks/{idWebhook}/description", path = {"idWebhook"}, body = {"value"} },
    ["trello.update_webhooks_id_model_by_id_webhook"] = { method = "PUT", url = "https://api.trello.com/webhooks/{idWebhook}/idModel", path = {"idWebhook"}, body = {"value"} },
  },
}
