-- Exa — every call this API accepts, as data.
--
-- GENERATED from https://api.exa.ai/openapi.json
-- Published on the vendor's own documentation site (https://api.exa.ai).
-- 63 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "exa",
  name = "Exa",
  base = "https://api.exa.ai",
  docs = "https://nango.dev/docs/integrations/all/exa",
  auth = {
    kind = "key",
    header = "x-api-key",
    format = "{token}",
    env = "EXA_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["exa.answer"] = { method = "POST", url = "https://api.exa.ai/answer", body = {"query", "stream", "text", "model", "systemPrompt", "userLocation", "outputSchema"} },
    ["exa.batch_monitors"] = { method = "POST", url = "https://api.exa.ai/monitors/batch", body = {"action", "filter", "dry_run", "limit"} },
    ["exa.cancel_agent_run"] = { method = "POST", url = "https://api.exa.ai/agent/runs/{id}/cancel", path = {"id"} },
    ["exa.cancel_batch"] = { method = "POST", url = "https://api.exa.ai/batches/{id}/cancel", path = {"id"}, header = {"Exa-Beta"} },
    ["exa.create_agent_run"] = { method = "POST", url = "https://api.exa.ai/agent/runs", header = {"Accept", "Exa-Beta"}, body = {"query", "systemPrompt", "effort", "input", "outputSchema", "previousRunId", "metadata", "dataSources", "budget"} },
    ["exa.create_batch"] = { method = "POST", url = "https://api.exa.ai/batches", header = {"Exa-Beta"}, body = {"requests", "metadata"} },
    ["exa.create_monitor"] = { method = "POST", url = "https://api.exa.ai/monitors", body = {"name", "search", "trigger", "outputSchema", "metadata", "webhook"} },
    ["exa.delete_agent_run"] = { method = "DELETE", url = "https://api.exa.ai/agent/runs/{id}", path = {"id"} },
    ["exa.delete_batch"] = { method = "DELETE", url = "https://api.exa.ai/batches/{id}", path = {"id"}, header = {"Exa-Beta"} },
    ["exa.delete_monitor"] = { method = "DELETE", url = "https://api.exa.ai/monitors/{id}", path = {"id"} },
    ["exa.events_get"] = { method = "GET", url = "https://api.exa.ai/v0/events/{id}", path = {"id"} },
    ["exa.events_list"] = { method = "GET", url = "https://api.exa.ai/v0/events", query = {"cursor", "limit", "types", "createdBefore", "createdAfter"} },
    ["exa.get_agent_run"] = { method = "GET", url = "https://api.exa.ai/agent/runs/{id}", path = {"id"} },
    ["exa.get_batch"] = { method = "GET", url = "https://api.exa.ai/batches/{id}", path = {"id"}, header = {"Exa-Beta"} },
    ["exa.get_contents"] = { method = "POST", url = "https://api.exa.ai/contents", body = {"ids", "urls", "compliance", "text", "highlights", "summary", "extras", "context", "livecrawl", "livecrawlTimeout", "maxAgeHours", "snapshotAsOf", "subpages", "subpageTarget"} },
    ["exa.get_monitor"] = { method = "GET", url = "https://api.exa.ai/monitors/{id}", path = {"id"} },
    ["exa.get_run"] = { method = "GET", url = "https://api.exa.ai/monitors/{id}/runs/{runId}", path = {"id", "runId"} },
    ["exa.imports_create"] = { method = "POST", url = "https://api.exa.ai/v0/imports" },
    ["exa.imports_delete"] = { method = "DELETE", url = "https://api.exa.ai/v0/imports/{id}", path = {"id"} },
    ["exa.imports_get"] = { method = "GET", url = "https://api.exa.ai/v0/imports/{id}", path = {"id"} },
    ["exa.imports_list"] = { method = "GET", url = "https://api.exa.ai/v0/imports", query = {"cursor", "limit"} },
    ["exa.imports_update"] = { method = "PATCH", url = "https://api.exa.ai/v0/imports/{id}", path = {"id"}, body = {"metadata", "title"} },
    ["exa.list_agent_run_events"] = { method = "GET", url = "https://api.exa.ai/agent/runs/{id}/events", path = {"id"}, query = {"limit", "cursor"}, header = {"Accept", "Last-Event-ID"} },
    ["exa.list_agent_runs"] = { method = "GET", url = "https://api.exa.ai/agent/runs", query = {"limit", "cursor"} },
    ["exa.list_batches"] = { method = "GET", url = "https://api.exa.ai/batches", query = {"cursor", "limit", "status"}, header = {"Exa-Beta"} },
    ["exa.list_monitors"] = { method = "GET", url = "https://api.exa.ai/monitors", query = {"status", "cursor", "limit", "name", "metadata"} },
    ["exa.list_runs"] = { method = "GET", url = "https://api.exa.ai/monitors/{id}/runs", path = {"id"}, query = {"cursor", "limit"} },
    ["exa.monitors_create"] = { method = "POST", url = "https://api.exa.ai/v0/monitors", body = {"websetId", "cadence", "behavior", "metadata"} },
    ["exa.monitors_delete"] = { method = "DELETE", url = "https://api.exa.ai/v0/monitors/{id}", path = {"id"} },
    ["exa.monitors_get"] = { method = "GET", url = "https://api.exa.ai/v0/monitors/{id}", path = {"id"} },
    ["exa.monitors_list"] = { method = "GET", url = "https://api.exa.ai/v0/monitors", query = {"cursor", "limit", "websetId"} },
    ["exa.monitors_runs_get"] = { method = "GET", url = "https://api.exa.ai/v0/monitors/{monitor}/runs/{id}", path = {"monitor", "id"} },
    ["exa.monitors_runs_list"] = { method = "GET", url = "https://api.exa.ai/v0/monitors/{monitor}/runs", path = {"monitor"} },
    ["exa.monitors_update"] = { method = "PATCH", url = "https://api.exa.ai/v0/monitors/{id}", path = {"id"}, body = {"metadata", "status", "cadence", "behavior"} },
    ["exa.search"] = { method = "POST", url = "https://api.exa.ai/search", body = {"includeDomains", "excludeDomains", "startCrawlDate", "endCrawlDate", "startPublishedDate", "endPublishedDate", "numResults", "context", "moderation", "contents", "query", "additionalQueries", "type", "category", "userLocation", "compliance", "outputSchema", "systemPrompt", "stream"} },
    ["exa.stop_agent_run"] = { method = "POST", url = "https://api.exa.ai/agent/runs/{id}/stop", path = {"id"}, header = {"Exa-Beta"} },
    ["exa.teams_me_get"] = { method = "GET", url = "https://api.exa.ai/v0/teams/me" },
    ["exa.trigger_monitor"] = { method = "POST", url = "https://api.exa.ai/monitors/{id}/trigger", path = {"id"} },
    ["exa.update_monitor"] = { method = "PATCH", url = "https://api.exa.ai/monitors/{id}", path = {"id"}, body = {"name", "status", "search", "trigger", "outputSchema", "metadata", "webhook"} },
    ["exa.webhooks_attempts_list"] = { method = "GET", url = "https://api.exa.ai/v0/webhooks/{id}/attempts", path = {"id"}, query = {"cursor", "limit", "eventType", "successful"} },
    ["exa.webhooks_create"] = { method = "POST", url = "https://api.exa.ai/v0/webhooks", body = {"events", "url", "metadata"} },
    ["exa.webhooks_delete"] = { method = "DELETE", url = "https://api.exa.ai/v0/webhooks/{id}", path = {"id"} },
    ["exa.webhooks_get"] = { method = "GET", url = "https://api.exa.ai/v0/webhooks/{id}", path = {"id"} },
    ["exa.webhooks_list"] = { method = "GET", url = "https://api.exa.ai/v0/webhooks", query = {"cursor", "limit"} },
    ["exa.webhooks_update"] = { method = "PATCH", url = "https://api.exa.ai/v0/webhooks/{id}", path = {"id"}, body = {"events", "url", "metadata"} },
    ["exa.websets_cancel"] = { method = "POST", url = "https://api.exa.ai/v0/websets/{id}/cancel", path = {"id"} },
    ["exa.websets_create"] = { method = "POST", url = "https://api.exa.ai/v0/websets", body = {"title", "search", "import", "enrichments", "exclude", "externalId", "metadata"} },
    ["exa.websets_delete"] = { method = "DELETE", url = "https://api.exa.ai/v0/websets/{id}", path = {"id"} },
    ["exa.websets_enrichments_cancel"] = { method = "POST", url = "https://api.exa.ai/v0/websets/{webset}/enrichments/{id}/cancel", path = {"webset", "id"} },
    ["exa.websets_enrichments_create"] = { method = "POST", url = "https://api.exa.ai/v0/websets/{webset}/enrichments", path = {"webset"}, body = {"description", "format", "options", "metadata"} },
    ["exa.websets_enrichments_delete"] = { method = "DELETE", url = "https://api.exa.ai/v0/websets/{webset}/enrichments/{id}", path = {"webset", "id"} },
    ["exa.websets_enrichments_get"] = { method = "GET", url = "https://api.exa.ai/v0/websets/{webset}/enrichments/{id}", path = {"webset", "id"} },
    ["exa.websets_enrichments_update"] = { method = "PATCH", url = "https://api.exa.ai/v0/websets/{webset}/enrichments/{id}", path = {"webset", "id"}, body = {"description", "format", "options", "metadata"} },
    ["exa.websets_get"] = { method = "GET", url = "https://api.exa.ai/v0/websets/{id}", path = {"id"}, query = {"expand"} },
    ["exa.websets_items_delete"] = { method = "DELETE", url = "https://api.exa.ai/v0/websets/{webset}/items/{id}", path = {"webset", "id"} },
    ["exa.websets_items_get"] = { method = "GET", url = "https://api.exa.ai/v0/websets/{webset}/items/{id}", path = {"webset", "id"} },
    ["exa.websets_items_list"] = { method = "GET", url = "https://api.exa.ai/v0/websets/{webset}/items", path = {"webset"}, query = {"cursor", "limit", "sourceId"} },
    ["exa.websets_list"] = { method = "GET", url = "https://api.exa.ai/v0/websets", query = {"cursor", "limit", "search"} },
    ["exa.websets_preview"] = { method = "POST", url = "https://api.exa.ai/v0/websets/preview", query = {"search"}, body = {"search"} },
    ["exa.websets_searches_cancel"] = { method = "POST", url = "https://api.exa.ai/v0/websets/{webset}/searches/{id}/cancel", path = {"webset", "id"} },
    ["exa.websets_searches_create"] = { method = "POST", url = "https://api.exa.ai/v0/websets/{webset}/searches", path = {"webset"}, body = {"count", "query", "entity", "criteria", "maxPeoplePerCompany", "exclude", "scope", "recall", "behavior", "metadata"} },
    ["exa.websets_searches_get"] = { method = "GET", url = "https://api.exa.ai/v0/websets/{webset}/searches/{id}", path = {"webset", "id"} },
    ["exa.websets_update"] = { method = "POST", url = "https://api.exa.ai/v0/websets/{id}", path = {"id"}, body = {"metadata", "title"} },
  },
}
