-- Vercel — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/vercel.com/0.0.1/openapi.json
-- APIs.guru's mirror of vercel.com, matched on vercel.com. A mirror lags the vendor.
-- 112 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "vercel-mcp",
  name = "Vercel",
  base = "https://mcp.vercel.com",
  docs = "https://nango.dev/docs/api-integrations/vercel-mcp",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "VERCEL_MCP_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["vercel-mcp.add_project_domain"] = { method = "POST", url = "https://mcp.vercel.com/v9/projects/{idOrName}/domains", path = {"idOrName"}, query = {"teamId"}, body = {"gitBranch", "name", "redirect", "redirectStatusCode"} },
    ["vercel-mcp.artifact_query"] = { method = "POST", url = "https://mcp.vercel.com/v8/artifacts", query = {"teamId"}, body = {"hashes"} },
    ["vercel-mcp.assign_alias"] = { method = "POST", url = "https://mcp.vercel.com/v2/deployments/{id}/aliases", path = {"id"}, query = {"teamId"}, body = {"alias", "redirect"} },
    ["vercel-mcp.buy_domain"] = { method = "POST", url = "https://mcp.vercel.com/v4/domains/buy", query = {"teamId"}, body = {"expectedPrice", "name", "renew"} },
    ["vercel-mcp.cancel_deployment"] = { method = "PATCH", url = "https://mcp.vercel.com/v12/deployments/{id}/cancel", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.check_domain_price"] = { method = "GET", url = "https://mcp.vercel.com/v4/domains/price", query = {"name", "type", "teamId"} },
    ["vercel-mcp.check_domain_status"] = { method = "GET", url = "https://mcp.vercel.com/v4/domains/status", query = {"name", "teamId"} },
    ["vercel-mcp.create_auth_token"] = { method = "POST", url = "https://mcp.vercel.com/v3/user/tokens", query = {"teamId"} },
    ["vercel-mcp.create_check"] = { method = "POST", url = "https://mcp.vercel.com/v1/deployments/{deploymentId}/checks", path = {"deploymentId"}, query = {"teamId"}, body = {"blocking", "detailsUrl", "externalId", "name", "path", "rerequestable"} },
    ["vercel-mcp.create_configurable_log_drain"] = { method = "POST", url = "https://mcp.vercel.com/v1/log-drains", query = {"teamId"}, body = {"branch", "deliveryFormat", "environment", "headers", "projectIds", "sources", "url"} },
    ["vercel-mcp.create_deployment"] = { method = "POST", url = "https://mcp.vercel.com/v13/deployments", query = {"forceNew", "skipAutoDetectionConfirmation", "teamId"}, body = {"$schema", "alias", "build", "buildCommand", "builds", "cleanUrls", "crons", "deploymentId", "devCommand", "env", "files", "framework", "functions", "git", "gitMetadata", "gitSource", "headers", "ignoreCommand", "installCommand", "meta", "monorepoManager", "name", "outputDirectory", "project", "projectSettings", "public", "redirects", "regions", "rewrites", "routes", "target", "trailingSlash", "withLatestCommit"} },
    ["vercel-mcp.create_edge_config"] = { method = "POST", url = "https://mcp.vercel.com/edge-config", query = {"teamId"}, body = {"items", "slug"} },
    ["vercel-mcp.create_edge_config_token"] = { method = "POST", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}/token", path = {"edgeConfigId"}, query = {"teamId"}, body = {"label"} },
    ["vercel-mcp.create_log_drain"] = { method = "POST", url = "https://mcp.vercel.com/v2/integrations/log-drains", query = {"teamId"}, body = {"branch", "deliveryFormat", "environment", "headers", "name", "projectIds", "sources", "url"} },
    ["vercel-mcp.create_or_transfer_domain"] = { method = "POST", url = "https://mcp.vercel.com/v4/domains", query = {"teamId"}, body = {"method"} },
    ["vercel-mcp.create_project"] = { method = "POST", url = "https://mcp.vercel.com/v9/projects", query = {"teamId"}, body = {"buildCommand", "commandForIgnoringBuildStep", "devCommand", "environmentVariables", "framework", "gitRepository", "installCommand", "name", "outputDirectory", "publicSource", "rootDirectory", "serverlessFunctionRegion", "skipGitConnectDuringLink"} },
    ["vercel-mcp.create_project_env"] = { method = "POST", url = "https://mcp.vercel.com/v10/projects/{idOrName}/env", path = {"idOrName"}, query = {"teamId"} },
    ["vercel-mcp.create_record"] = { method = "POST", url = "https://mcp.vercel.com/v2/domains/{domain}/records", path = {"domain"}, query = {"teamId"}, body = {"type"} },
    ["vercel-mcp.create_secret"] = { method = "POST", url = "https://mcp.vercel.com/v2/secrets/{name}", path = {"name"}, query = {"teamId"}, body = {"decryptable", "name", "projectId", "value"} },
    ["vercel-mcp.create_team"] = { method = "POST", url = "https://mcp.vercel.com/v1/teams", body = {"name", "slug"} },
    ["vercel-mcp.create_webhook"] = { method = "POST", url = "https://mcp.vercel.com/v1/webhooks", query = {"teamId"}, body = {"events", "projectIds", "url"} },
    ["vercel-mcp.delete_alias"] = { method = "DELETE", url = "https://mcp.vercel.com/v2/aliases/{aliasId}", path = {"aliasId"}, query = {"teamId"} },
    ["vercel-mcp.delete_auth_token"] = { method = "DELETE", url = "https://mcp.vercel.com/v3/user/tokens/{tokenId}", path = {"tokenId"} },
    ["vercel-mcp.delete_configurable_log_drain"] = { method = "DELETE", url = "https://mcp.vercel.com/v1/log-drains/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.delete_configuration"] = { method = "DELETE", url = "https://mcp.vercel.com/v1/integrations/configuration/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.delete_deployment"] = { method = "DELETE", url = "https://mcp.vercel.com/v13/deployments/{id}", path = {"id"}, query = {"url", "teamId"} },
    ["vercel-mcp.delete_domain"] = { method = "DELETE", url = "https://mcp.vercel.com/v6/domains/{domain}", path = {"domain"}, query = {"teamId"} },
    ["vercel-mcp.delete_edge_config"] = { method = "DELETE", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}", path = {"edgeConfigId"}, query = {"teamId"} },
    ["vercel-mcp.delete_edge_config_tokens"] = { method = "DELETE", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}/tokens", path = {"edgeConfigId"}, query = {"teamId"}, body = {"tokens"} },
    ["vercel-mcp.delete_integration_log_drain"] = { method = "DELETE", url = "https://mcp.vercel.com/v1/integrations/log-drains/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.delete_project"] = { method = "DELETE", url = "https://mcp.vercel.com/v9/projects/{idOrName}", path = {"idOrName"}, query = {"teamId"} },
    ["vercel-mcp.delete_secret"] = { method = "DELETE", url = "https://mcp.vercel.com/v2/secrets/{idOrName}", path = {"idOrName"}, query = {"teamId"} },
    ["vercel-mcp.delete_team"] = { method = "DELETE", url = "https://mcp.vercel.com/v1/teams/{teamId}", path = {"teamId"}, body = {"reasons"} },
    ["vercel-mcp.delete_team_invite_code"] = { method = "DELETE", url = "https://mcp.vercel.com/v1/teams/{teamId}/invites/{inviteId}", path = {"inviteId", "teamId"} },
    ["vercel-mcp.delete_webhook"] = { method = "DELETE", url = "https://mcp.vercel.com/v1/webhooks/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.download_artifact"] = { method = "GET", url = "https://mcp.vercel.com/v8/artifacts/{hash}", path = {"hash"}, query = {"teamId"}, header = {"x-artifact-client-ci", "x-artifact-client-interactive"} },
    ["vercel-mcp.edit_project_env"] = { method = "PATCH", url = "https://mcp.vercel.com/v9/projects/{idOrName}/env/{id}", path = {"idOrName", "id"}, query = {"teamId"}, body = {"gitBranch", "target", "type", "value"} },
    ["vercel-mcp.email_login"] = { method = "POST", url = "https://mcp.vercel.com/registration", body = {"email", "tokenName"} },
    ["vercel-mcp.filter_project_envs"] = { method = "GET", url = "https://mcp.vercel.com/v9/projects/{idOrName}/env", path = {"idOrName"}, query = {"gitBranch", "decrypt", "source", "teamId"} },
    ["vercel-mcp.get_alias"] = { method = "GET", url = "https://mcp.vercel.com/v4/aliases/{idOrAlias}", path = {"idOrAlias"}, query = {"from", "projectId", "since", "until", "teamId"} },
    ["vercel-mcp.get_all_checks"] = { method = "GET", url = "https://mcp.vercel.com/v1/deployments/{deploymentId}/checks", path = {"deploymentId"}, query = {"teamId"} },
    ["vercel-mcp.get_auth_token"] = { method = "GET", url = "https://mcp.vercel.com/v5/user/tokens/{tokenId}", path = {"tokenId"} },
    ["vercel-mcp.get_auth_user"] = { method = "GET", url = "https://mcp.vercel.com/v2/user" },
    ["vercel-mcp.get_cert_by_id"] = { method = "GET", url = "https://mcp.vercel.com/v7/certs/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.get_check"] = { method = "GET", url = "https://mcp.vercel.com/v1/deployments/{deploymentId}/checks/{checkId}", path = {"deploymentId", "checkId"}, query = {"teamId"} },
    ["vercel-mcp.get_configurable_log_drain"] = { method = "GET", url = "https://mcp.vercel.com/v1/log-drains/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.get_configurable_log_drains"] = { method = "GET", url = "https://mcp.vercel.com/v1/log-drains", query = {"projectId", "teamId"} },
    ["vercel-mcp.get_configuration"] = { method = "GET", url = "https://mcp.vercel.com/v1/integrations/configuration/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.get_configurations"] = { method = "GET", url = "https://mcp.vercel.com/v1/integrations/configurations", query = {"view", "teamId"} },
    ["vercel-mcp.get_deployment"] = { method = "GET", url = "https://mcp.vercel.com/v13/deployments/{idOrUrl}", path = {"idOrUrl"}, query = {"withGitRepoInfo", "teamId"} },
    ["vercel-mcp.get_deployment_events"] = { method = "GET", url = "https://mcp.vercel.com/v2/deployments/{idOrUrl}/events", path = {"idOrUrl"}, query = {"direction", "follow", "limit", "name", "since", "until", "statusCode", "delimiter", "builds", "teamId"} },
    ["vercel-mcp.get_deployment_file_contents"] = { method = "GET", url = "https://mcp.vercel.com/v6/deployments/{id}/files/{fileId}", path = {"id", "fileId"}, query = {"teamId"} },
    ["vercel-mcp.get_deployments"] = { method = "GET", url = "https://mcp.vercel.com/v6/deployments", query = {"app", "from", "limit", "projectId", "target", "to", "users", "since", "until", "state", "rollbackCandidate", "teamId"} },
    ["vercel-mcp.get_domain"] = { method = "GET", url = "https://mcp.vercel.com/v5/domains/{domain}", path = {"domain"}, query = {"teamId"} },
    ["vercel-mcp.get_domain_config"] = { method = "GET", url = "https://mcp.vercel.com/v6/domains/{domain}/config", path = {"domain"}, query = {"teamId"} },
    ["vercel-mcp.get_domains"] = { method = "GET", url = "https://mcp.vercel.com/v5/domains", query = {"limit", "since", "until", "teamId"} },
    ["vercel-mcp.get_edge_config"] = { method = "GET", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}", path = {"edgeConfigId"}, query = {"teamId"} },
    ["vercel-mcp.get_edge_config_item"] = { method = "GET", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}/item/{edgeConfigItemKey}", path = {"edgeConfigId", "edgeConfigItemKey"}, query = {"teamId"} },
    ["vercel-mcp.get_edge_config_items"] = { method = "GET", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}/items", path = {"edgeConfigId"}, query = {"teamId"} },
    ["vercel-mcp.get_edge_config_token"] = { method = "GET", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}/token/{token}", path = {"edgeConfigId"}, query = {"teamId"} },
    ["vercel-mcp.get_edge_config_tokens"] = { method = "GET", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}/tokens", path = {"edgeConfigId"}, query = {"teamId"} },
    ["vercel-mcp.get_edge_configs"] = { method = "GET", url = "https://mcp.vercel.com/edge-config", query = {"teamId"} },
    ["vercel-mcp.get_integration_log_drains"] = { method = "GET", url = "https://mcp.vercel.com/v2/integrations/log-drains", query = {"teamId"} },
    ["vercel-mcp.get_project"] = { method = "GET", url = "https://mcp.vercel.com/v9/projects/{idOrName}", path = {"idOrName"}, query = {"teamId"} },
    ["vercel-mcp.get_project_domain"] = { method = "GET", url = "https://mcp.vercel.com/v9/projects/{idOrName}/domains/{domain}", path = {"idOrName", "domain"}, query = {"teamId"} },
    ["vercel-mcp.get_project_domains"] = { method = "GET", url = "https://mcp.vercel.com/v9/projects/{idOrName}/domains", path = {"idOrName"}, query = {"production", "gitBranch", "redirects", "redirect", "verified", "limit", "since", "until", "order", "teamId"} },
    ["vercel-mcp.get_project_env"] = { method = "GET", url = "https://mcp.vercel.com/v1/projects/{idOrName}/env/{id}", path = {"idOrName", "id"}, query = {"teamId"} },
    ["vercel-mcp.get_projects"] = { method = "GET", url = "https://mcp.vercel.com/v9/projects", query = {"from", "gitForkProtection", "limit", "search", "repo", "repoId", "repoUrl", "excludeRepos", "edgeConfigId", "edgeConfigTokenId", "connectConfigurationId", "teamId"} },
    ["vercel-mcp.get_records"] = { method = "GET", url = "https://mcp.vercel.com/v4/domains/{domain}/records", path = {"domain"}, query = {"limit", "since", "until", "teamId"} },
    ["vercel-mcp.get_secret"] = { method = "GET", url = "https://mcp.vercel.com/v3/secrets/{idOrName}", path = {"idOrName"}, query = {"decrypt", "teamId"} },
    ["vercel-mcp.get_secrets"] = { method = "GET", url = "https://mcp.vercel.com/v3/secrets", query = {"id", "projectId", "teamId"} },
    ["vercel-mcp.get_team"] = { method = "GET", url = "https://mcp.vercel.com/v2/teams/{teamId}", path = {"teamId"}, query = {"slug"} },
    ["vercel-mcp.get_team_access_request"] = { method = "GET", url = "https://mcp.vercel.com/v1/teams/{teamId}/request/{userId}", path = {"userId", "teamId"} },
    ["vercel-mcp.get_team_members"] = { method = "GET", url = "https://mcp.vercel.com/v2/teams/{teamId}/members", path = {"teamId"}, query = {"limit", "since", "until", "search", "role", "excludeProject"} },
    ["vercel-mcp.get_teams"] = { method = "GET", url = "https://mcp.vercel.com/v2/teams", query = {"limit", "since", "until"} },
    ["vercel-mcp.get_v1_integrations_search_repo"] = { method = "GET", url = "https://mcp.vercel.com/v1/integrations/search-repo", query = {"query", "namespaceId", "provider", "installationId", "teamId"} },
    ["vercel-mcp.get_webhook"] = { method = "GET", url = "https://mcp.vercel.com/v1/webhooks/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.get_webhooks"] = { method = "GET", url = "https://mcp.vercel.com/v1/webhooks", query = {"projectId", "teamId"} },
    ["vercel-mcp.git_namespaces"] = { method = "GET", url = "https://mcp.vercel.com/v1/integrations/git-namespaces", query = {"provider", "teamId"} },
    ["vercel-mcp.invite_user_to_team"] = { method = "POST", url = "https://mcp.vercel.com/v1/teams/{teamId}/members", path = {"teamId"}, body = {"email", "role", "uid"} },
    ["vercel-mcp.issue_cert"] = { method = "POST", url = "https://mcp.vercel.com/v7/certs", query = {"teamId"}, body = {"cns"} },
    ["vercel-mcp.join_team"] = { method = "POST", url = "https://mcp.vercel.com/v1/teams/{teamId}/members/teams/join", path = {"teamId"}, body = {"inviteCode", "teamId"} },
    ["vercel-mcp.list_aliases"] = { method = "GET", url = "https://mcp.vercel.com/v4/aliases", query = {"domain", "from", "limit", "projectId", "since", "until", "rollbackDeploymentId", "teamId"} },
    ["vercel-mcp.list_auth_tokens"] = { method = "GET", url = "https://mcp.vercel.com/v5/user/tokens" },
    ["vercel-mcp.list_deployment_aliases"] = { method = "GET", url = "https://mcp.vercel.com/v2/deployments/{id}/aliases", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.list_deployment_builds"] = { method = "GET", url = "https://mcp.vercel.com/v11/deployments/{deploymentId}/builds", path = {"deploymentId"}, query = {"teamId"} },
    ["vercel-mcp.list_deployment_files"] = { method = "GET", url = "https://mcp.vercel.com/v6/deployments/{id}/files", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.list_user_events"] = { method = "GET", url = "https://mcp.vercel.com/v3/events", query = {"limit", "since", "until", "types", "userId", "teamId"} },
    ["vercel-mcp.patch_team"] = { method = "PATCH", url = "https://mcp.vercel.com/v2/teams/{teamId}", path = {"teamId"}, body = {"avatar", "description", "emailDomain", "enablePreviewFeedback", "migrateExistingEnvVariablesToSensitive", "name", "previewDeploymentSuffix", "regenerateInviteCode", "remoteCaching", "saml", "sensitiveEnvironmentVariablePolicy", "slug"} },
    ["vercel-mcp.patcht_edge_config_items"] = { method = "PATCH", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}/items", path = {"edgeConfigId"}, query = {"teamId"}, body = {"items"} },
    ["vercel-mcp.record_events"] = { method = "POST", url = "https://mcp.vercel.com/v8/artifacts/events", query = {"teamId"}, header = {"x-artifact-client-ci", "x-artifact-client-interactive"} },
    ["vercel-mcp.remove_cert"] = { method = "DELETE", url = "https://mcp.vercel.com/v7/certs/{id}", path = {"id"}, query = {"teamId"} },
    ["vercel-mcp.remove_project_domain"] = { method = "DELETE", url = "https://mcp.vercel.com/v9/projects/{idOrName}/domains/{domain}", path = {"idOrName", "domain"}, query = {"teamId"} },
    ["vercel-mcp.remove_project_env"] = { method = "DELETE", url = "https://mcp.vercel.com/v9/projects/{idOrName}/env/{id}", path = {"idOrName", "id"}, query = {"teamId"} },
    ["vercel-mcp.remove_record"] = { method = "DELETE", url = "https://mcp.vercel.com/v2/domains/{domain}/records/{recordId}", path = {"domain", "recordId"}, query = {"teamId"} },
    ["vercel-mcp.remove_team_member"] = { method = "DELETE", url = "https://mcp.vercel.com/v1/teams/{teamId}/members/{uid}", path = {"uid", "teamId"} },
    ["vercel-mcp.rename_secret"] = { method = "PATCH", url = "https://mcp.vercel.com/v2/secrets/{name}", path = {"name"}, query = {"teamId"}, body = {"name"} },
    ["vercel-mcp.request_access_to_team"] = { method = "POST", url = "https://mcp.vercel.com/v1/teams/{teamId}/request", path = {"teamId"}, body = {"joinedFrom"} },
    ["vercel-mcp.request_delete"] = { method = "DELETE", url = "https://mcp.vercel.com/v1/user", body = {"reasons"} },
    ["vercel-mcp.rerequest_check"] = { method = "POST", url = "https://mcp.vercel.com/v1/deployments/{deploymentId}/checks/{checkId}/rerequest", path = {"deploymentId", "checkId"}, query = {"teamId"} },
    ["vercel-mcp.status"] = { method = "GET", url = "https://mcp.vercel.com/v8/artifacts/status", query = {"teamId"} },
    ["vercel-mcp.update_check"] = { method = "PATCH", url = "https://mcp.vercel.com/v1/deployments/{deploymentId}/checks/{checkId}", path = {"deploymentId", "checkId"}, query = {"teamId"}, body = {"conclusion", "detailsUrl", "externalId", "name", "output", "path", "status"} },
    ["vercel-mcp.update_edge_config"] = { method = "PUT", url = "https://mcp.vercel.com/edge-config/{edgeConfigId}", path = {"edgeConfigId"}, query = {"teamId"}, body = {"slug"} },
    ["vercel-mcp.update_project"] = { method = "PATCH", url = "https://mcp.vercel.com/v9/projects/{idOrName}", path = {"idOrName"}, query = {"teamId"}, body = {"autoExposeSystemEnvs", "buildCommand", "commandForIgnoringBuildStep", "devCommand", "directoryListing", "enablePreviewFeedback", "framework", "gitForkProtection", "installCommand", "name", "nodeVersion", "outputDirectory", "passwordProtection", "publicSource", "rootDirectory", "serverlessFunctionRegion", "skipGitConnectDuringLink", "sourceFilesOutsideRootDirectory", "ssoProtection"} },
    ["vercel-mcp.update_project_domain"] = { method = "PATCH", url = "https://mcp.vercel.com/v9/projects/{idOrName}/domains/{domain}", path = {"idOrName", "domain"}, query = {"teamId"}, body = {"gitBranch", "redirect", "redirectStatusCode"} },
    ["vercel-mcp.update_record"] = { method = "PATCH", url = "https://mcp.vercel.com/v1/domains/records/{recordId}", path = {"recordId"}, query = {"teamId"}, body = {"mxPriority", "name", "srv", "ttl", "type", "value"} },
    ["vercel-mcp.update_team_member"] = { method = "PATCH", url = "https://mcp.vercel.com/v1/teams/{teamId}/members/{uid}", path = {"uid", "teamId"}, body = {"confirmed", "joinedFrom", "role"} },
    ["vercel-mcp.upload_artifact"] = { method = "PUT", url = "https://mcp.vercel.com/v8/artifacts/{hash}", path = {"hash"}, query = {"teamId"}, header = {"Content-Length", "x-artifact-duration", "x-artifact-client-ci", "x-artifact-client-interactive", "x-artifact-tag"} },
    ["vercel-mcp.upload_cert"] = { method = "PUT", url = "https://mcp.vercel.com/v7/certs", query = {"teamId"}, body = {"ca", "cert", "skipValidation"} },
    ["vercel-mcp.upload_file"] = { method = "POST", url = "https://mcp.vercel.com/v2/files", query = {"teamId"}, header = {"Content-Length", "x-vercel-digest", "x-now-digest", "x-now-size"} },
    ["vercel-mcp.verify_project_domain"] = { method = "POST", url = "https://mcp.vercel.com/v9/projects/{idOrName}/domains/{domain}/verify", path = {"idOrName", "domain"}, query = {"teamId"} },
    ["vercel-mcp.verify_token"] = { method = "GET", url = "https://mcp.vercel.com/registration/verify", query = {"email", "tokenName", "ssoUserId"} },
  },
}
