-- Agentcard — every call this API accepts, as data.
--
-- GENERATED from https://docs.agentcard.sh/openapi.json
-- Published on the vendor's own documentation site (https://docs.agentcard.sh).
-- 43 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "agentcard",
  name = "Agentcard",
  base = "https://api.agentcard.sh",
  docs = "https://nango.dev/docs/api-integrations/agentcard",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "AGENTCARD_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["agentcard.attach_cancel"] = { method = "DELETE", url = "https://api.agentcard.sh/api/v2/cards/add/{attachment_id}", path = {"attachment_id"} },
    ["agentcard.attach_start"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/cards/add", body = {"user_id", "display", "email"} },
    ["agentcard.attach_status"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/cards/add", query = {"user_id"} },
    ["agentcard.buy"] = { method = "POST", url = "https://api.agentcard.sh/buy", body = {"ask", "conversation_id", "confirm", "payment_source", "delivery_address"} },
    ["agentcard.connect_consent"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/connect/consent", body = {"user_id", "terms_version"} },
    ["agentcard.connect_refresh"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/connect/refresh", body = {"refresh_token"} },
    ["agentcard.connect_start"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/connect/start", body = {"email", "phone", "external_user_id"} },
    ["agentcard.connect_verify"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/connect/verify", body = {"connect_id", "code"} },
    ["agentcard.create_access_token"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/oauth/token", body = {"grant_type", "client_id", "client_secret"} },
    ["agentcard.exchange_platform_connect_code"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/platform_connect_sessions/exchange", body = {"code"} },
    ["agentcard.get_api_v2_onboarding_attempts_id"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/onboarding_attempts/{id}", path = {"id"} },
    ["agentcard.get_buy_conversation"] = { method = "GET", url = "https://api.agentcard.sh/buy/conversations/{id}", path = {"id"} },
    ["agentcard.introspect_credential"] = { method = "GET", url = "https://api.agentcard.sh/api/v2" },
    ["agentcard.kyc_get_status"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/kyc", query = {"user_id"} },
    ["agentcard.kyc_import"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/kyc/import", body = {"user_id", "share_token", "user_ip"} },
    ["agentcard.kyc_simulate"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/kyc/simulate", body = {"user_id", "outcome", "reason"} },
    ["agentcard.kyc_submit_information"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/kyc/information", body = {"user_id", "first_name", "last_name", "date_of_birth", "national_id_number", "phone_number", "address_line1", "address_line2", "address_city", "address_region", "address_postal_code", "address_country", "user_ip"} },
    ["agentcard.kyc_upload_back"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/kyc/documents/back" },
    ["agentcard.kyc_upload_front"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/kyc/documents/front" },
    ["agentcard.list_buy_merchants"] = { method = "GET", url = "https://api.agentcard.sh/buy/merchants" },
    ["agentcard.member_attach_cancel"] = { method = "DELETE", url = "https://api.agentcard.sh/api/v2/attach/{attachment_id}", path = {"attachment_id"} },
    ["agentcard.member_attach_start"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/attach" },
    ["agentcard.member_attach_status"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/attach" },
    ["agentcard.member_card_close"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/cards/{card_id}/close", path = {"card_id"} },
    ["agentcard.member_card_create"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/cards", header = {"Idempotency-Key"}, body = {"amount_cents", "currency", "connected_card_id", "merchant", "description", "metadata"} },
    ["agentcard.member_card_get"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/cards/{card_id}", path = {"card_id"} },
    ["agentcard.member_cards_list"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/cards" },
    ["agentcard.member_flow_status"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/flow_status" },
    ["agentcard.platform_connect_create"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/platform_connect_sessions", body = {"return_url", "state"} },
    ["agentcard.platform_connect_exchange"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/platform_connect_sessions/{session_id}/exchange", path = {"session_id"}, body = {"code"} },
    ["agentcard.platform_connect_get"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/platform_connect_sessions/{session_id}", path = {"session_id"} },
    ["agentcard.post_api_v2_onboarding_attempts"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/onboarding_attempts", body = {"phone", "external_user_id"} },
    ["agentcard.post_api_v2_onboarding_attempts_id_exchange"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/onboarding_attempts/{id}/exchange", path = {"id"} },
    ["agentcard.wallet_fund"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/wallet/fund", body = {"user_id", "amount_cents", "payment_method", "link_type"} },
    ["agentcard.wallet_fund_status"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/wallet/fund/{session_id}", path = {"session_id"} },
    ["agentcard.wallet_get"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/wallet", query = {"user_id"} },
    ["agentcard.wallet_phone_start"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/wallet/phone/start", body = {"user_id", "phone_number"} },
    ["agentcard.wallet_phone_verify"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/wallet/phone/verify", body = {"user_id", "code", "phone_number"} },
    ["agentcard.wallet_withdraw"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/wallet/withdrawals", body = {"user_id", "amount_cents", "rail", "recipient_id", "destination_address"} },
    ["agentcard.wallet_withdrawal_recipient_create"] = { method = "POST", url = "https://api.agentcard.sh/api/v2/wallet/withdrawal-recipients", body = {"user_id", "type", "beneficiary_name", "country_code", "nickname", "email", "routing_number", "account_number", "account_type", "iban", "swift_code", "bank_name", "address_line1", "address_line2", "city", "region", "postal_code", "country_specific"} },
    ["agentcard.wallet_withdrawal_recipient_remove"] = { method = "DELETE", url = "https://api.agentcard.sh/api/v2/wallet/withdrawal-recipients/{recipient_id}", path = {"recipient_id"}, query = {"user_id"} },
    ["agentcard.wallet_withdrawal_recipients_list"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/wallet/withdrawal-recipients", query = {"user_id"} },
    ["agentcard.wallet_withdrawals_list"] = { method = "GET", url = "https://api.agentcard.sh/api/v2/wallet/withdrawals", query = {"user_id"} },
  },
}
