-- Stack Exchange — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/stackexchange.com/2.0/openapi.json
-- APIs.guru's mirror, matched on stackexchange.com. A mirror lags the vendor.
-- 124 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "stackexchange",
  name = "Stack Exchange",
  base = "https://api.stackexchange.com",
  docs = "https://nango.dev/docs/integrations/all/stackexchange",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "STACKEXCHANGE_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["stackexchange.get_access_tokens_accessTokens"] = { method = "GET", url = "https://api.stackexchange.com/access-tokens/{accessTokens}", path = {"accessTokens"}, query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_access_tokens_accessTokens_invalidate"] = { method = "GET", url = "https://api.stackexchange.com/access-tokens/{accessTokens}/invalidate", path = {"accessTokens"}, query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_answers"] = { method = "GET", url = "https://api.stackexchange.com/answers", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_answers_ids"] = { method = "GET", url = "https://api.stackexchange.com/answers/{ids}", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_answers_ids_comments"] = { method = "GET", url = "https://api.stackexchange.com/answers/{ids}/comments", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_apps_accessTokens_de_authenticate"] = { method = "GET", url = "https://api.stackexchange.com/apps/{accessTokens}/de-authenticate", path = {"accessTokens"}, query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_badges"] = { method = "GET", url = "https://api.stackexchange.com/badges", query = {"inname", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_badges_ids"] = { method = "GET", url = "https://api.stackexchange.com/badges/{ids}", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_badges_ids_recipients"] = { method = "GET", url = "https://api.stackexchange.com/badges/{ids}/recipients", path = {"ids"}, query = {"fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_badges_name"] = { method = "GET", url = "https://api.stackexchange.com/badges/name", query = {"inname", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_badges_recipients"] = { method = "GET", url = "https://api.stackexchange.com/badges/recipients", query = {"fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_badges_tags"] = { method = "GET", url = "https://api.stackexchange.com/badges/tags", query = {"inname", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_comments"] = { method = "GET", url = "https://api.stackexchange.com/comments", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_comments_ids"] = { method = "GET", url = "https://api.stackexchange.com/comments/{ids}", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_errors"] = { method = "GET", url = "https://api.stackexchange.com/errors", query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_errors_id"] = { method = "GET", url = "https://api.stackexchange.com/errors/{id}", path = {"id"} },
    ["stackexchange.get_events"] = { method = "GET", url = "https://api.stackexchange.com/events", query = {"pagesize", "page", "filter", "callback", "site", "since"} },
    ["stackexchange.get_filters_create"] = { method = "GET", url = "https://api.stackexchange.com/filters/create", query = {"base", "exclude", "include", "unsafe"} },
    ["stackexchange.get_filters_filters"] = { method = "GET", url = "https://api.stackexchange.com/filters/{filters}", path = {"filters"} },
    ["stackexchange.get_inbox"] = { method = "GET", url = "https://api.stackexchange.com/inbox", query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_inbox_unread"] = { method = "GET", url = "https://api.stackexchange.com/inbox/unread", query = {"pagesize", "page", "filter", "callback", "since"} },
    ["stackexchange.get_info"] = { method = "GET", url = "https://api.stackexchange.com/info", query = {"site"} },
    ["stackexchange.get_me"] = { method = "GET", url = "https://api.stackexchange.com/me", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_answers"] = { method = "GET", url = "https://api.stackexchange.com/me/answers", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_associated"] = { method = "GET", url = "https://api.stackexchange.com/me/associated", query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_me_badges"] = { method = "GET", url = "https://api.stackexchange.com/me/badges", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_comments"] = { method = "GET", url = "https://api.stackexchange.com/me/comments", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_comments_toId"] = { method = "GET", url = "https://api.stackexchange.com/me/comments/{toId}", path = {"toId"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_favorites"] = { method = "GET", url = "https://api.stackexchange.com/me/favorites", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_inbox"] = { method = "GET", url = "https://api.stackexchange.com/me/inbox", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_inbox_unread"] = { method = "GET", url = "https://api.stackexchange.com/me/inbox/unread", query = {"pagesize", "page", "filter", "callback", "site", "since"} },
    ["stackexchange.get_me_mentioned"] = { method = "GET", url = "https://api.stackexchange.com/me/mentioned", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_merges"] = { method = "GET", url = "https://api.stackexchange.com/me/merges", query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_me_notifications"] = { method = "GET", url = "https://api.stackexchange.com/me/notifications", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_notifications_unread"] = { method = "GET", url = "https://api.stackexchange.com/me/notifications/unread", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_privileges"] = { method = "GET", url = "https://api.stackexchange.com/me/privileges", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_questions"] = { method = "GET", url = "https://api.stackexchange.com/me/questions", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_questions_featured"] = { method = "GET", url = "https://api.stackexchange.com/me/questions/featured", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_questions_no_answers"] = { method = "GET", url = "https://api.stackexchange.com/me/questions/no-answers", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_questions_unaccepted"] = { method = "GET", url = "https://api.stackexchange.com/me/questions/unaccepted", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_questions_unanswered"] = { method = "GET", url = "https://api.stackexchange.com/me/questions/unanswered", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_reputation"] = { method = "GET", url = "https://api.stackexchange.com/me/reputation", query = {"filter", "callback", "site"} },
    ["stackexchange.get_me_reputation_history"] = { method = "GET", url = "https://api.stackexchange.com/me/reputation-history", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_reputation_history_full"] = { method = "GET", url = "https://api.stackexchange.com/me/reputation-history/full", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_suggested_edits"] = { method = "GET", url = "https://api.stackexchange.com/me/suggested-edits", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_tags"] = { method = "GET", url = "https://api.stackexchange.com/me/tags", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_tags_tags_top_answers"] = { method = "GET", url = "https://api.stackexchange.com/me/tags/{tags}/top-answers", path = {"tags"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_tags_tags_top_questions"] = { method = "GET", url = "https://api.stackexchange.com/me/tags/{tags}/top-questions", path = {"tags"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_timeline"] = { method = "GET", url = "https://api.stackexchange.com/me/timeline", query = {"fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_top_answer_tags"] = { method = "GET", url = "https://api.stackexchange.com/me/top-answer-tags", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_top_question_tags"] = { method = "GET", url = "https://api.stackexchange.com/me/top-question-tags", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_me_write_permissions"] = { method = "GET", url = "https://api.stackexchange.com/me/write-permissions", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_notifications"] = { method = "GET", url = "https://api.stackexchange.com/notifications", query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_notifications_unread"] = { method = "GET", url = "https://api.stackexchange.com/notifications/unread", query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_posts"] = { method = "GET", url = "https://api.stackexchange.com/posts", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_posts_ids"] = { method = "GET", url = "https://api.stackexchange.com/posts/{ids}", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_posts_ids_comments"] = { method = "GET", url = "https://api.stackexchange.com/posts/{ids}/comments", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_posts_ids_revisions"] = { method = "GET", url = "https://api.stackexchange.com/posts/{ids}/revisions", path = {"ids"}, query = {"fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_posts_ids_suggested_edits"] = { method = "GET", url = "https://api.stackexchange.com/posts/{ids}/suggested-edits", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_privileges"] = { method = "GET", url = "https://api.stackexchange.com/privileges", query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions"] = { method = "GET", url = "https://api.stackexchange.com/questions", query = {"tagged", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_featured"] = { method = "GET", url = "https://api.stackexchange.com/questions/featured", query = {"tagged", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_ids"] = { method = "GET", url = "https://api.stackexchange.com/questions/{ids}", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_ids_answers"] = { method = "GET", url = "https://api.stackexchange.com/questions/{ids}/answers", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_ids_comments"] = { method = "GET", url = "https://api.stackexchange.com/questions/{ids}/comments", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_ids_linked"] = { method = "GET", url = "https://api.stackexchange.com/questions/{ids}/linked", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_ids_related"] = { method = "GET", url = "https://api.stackexchange.com/questions/{ids}/related", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_ids_timeline"] = { method = "GET", url = "https://api.stackexchange.com/questions/{ids}/timeline", path = {"ids"}, query = {"fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_no_answers"] = { method = "GET", url = "https://api.stackexchange.com/questions/no-answers", query = {"tagged", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_questions_unanswered"] = { method = "GET", url = "https://api.stackexchange.com/questions/unanswered", query = {"tagged", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_revisions_ids"] = { method = "GET", url = "https://api.stackexchange.com/revisions/{ids}", path = {"ids"}, query = {"fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_search"] = { method = "GET", url = "https://api.stackexchange.com/search", query = {"tagged", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site", "intitle", "nottagged"} },
    ["stackexchange.get_search_advanced"] = { method = "GET", url = "https://api.stackexchange.com/search/advanced", query = {"tagged", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site", "accepted", "answers", "body", "closed", "migrated", "notice", "nottagged", "q", "title", "url", "user", "views", "wiki"} },
    ["stackexchange.get_similar"] = { method = "GET", url = "https://api.stackexchange.com/similar", query = {"tagged", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site", "nottagged", "title"} },
    ["stackexchange.get_sites"] = { method = "GET", url = "https://api.stackexchange.com/sites", query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_suggested_edits"] = { method = "GET", url = "https://api.stackexchange.com/suggested-edits", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_suggested_edits_ids"] = { method = "GET", url = "https://api.stackexchange.com/suggested-edits/{ids}", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags"] = { method = "GET", url = "https://api.stackexchange.com/tags", query = {"inname", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_moderator_only"] = { method = "GET", url = "https://api.stackexchange.com/tags/moderator-only", query = {"inname", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_required"] = { method = "GET", url = "https://api.stackexchange.com/tags/required", query = {"inname", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_synonyms"] = { method = "GET", url = "https://api.stackexchange.com/tags/synonyms", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_tag_top_answerers_period"] = { method = "GET", url = "https://api.stackexchange.com/tags/{tag}/top-answerers/{period}", path = {"tag", "period"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_tag_top_askers_period"] = { method = "GET", url = "https://api.stackexchange.com/tags/{tag}/top-askers/{period}", path = {"tag", "period"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_tags_faq"] = { method = "GET", url = "https://api.stackexchange.com/tags/{tags}/faq", path = {"tags"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_tags_info"] = { method = "GET", url = "https://api.stackexchange.com/tags/{tags}/info", path = {"tags"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_tags_related"] = { method = "GET", url = "https://api.stackexchange.com/tags/{tags}/related", path = {"tags"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_tags_synonyms"] = { method = "GET", url = "https://api.stackexchange.com/tags/{tags}/synonyms", path = {"tags"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_tags_tags_wikis"] = { method = "GET", url = "https://api.stackexchange.com/tags/{tags}/wikis", path = {"tags"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users"] = { method = "GET", url = "https://api.stackexchange.com/users", query = {"inname", "order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_inbox"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/inbox", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_inbox_unread"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/inbox/unread", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site", "since"} },
    ["stackexchange.get_users_id_notifications"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/notifications", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_notifications_unread"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/notifications/unread", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_privileges"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/privileges", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_reputation_history_full"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/reputation-history/full", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_tags_tags_top_answers"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/tags/{tags}/top-answers", path = {"id", "tags"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_tags_tags_top_questions"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/tags/{tags}/top-questions", path = {"id", "tags"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_top_answer_tags"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/top-answer-tags", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_top_question_tags"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/top-question-tags", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_id_write_permissions"] = { method = "GET", url = "https://api.stackexchange.com/users/{id}/write-permissions", path = {"id"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_answers"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/answers", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_associated"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/associated", path = {"ids"}, query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_users_ids_badges"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/badges", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_comments"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/comments", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_comments_toid"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/comments/{toid}", path = {"ids", "toid"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_favorites"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/favorites", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_mentioned"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/mentioned", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_merges"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/merges", path = {"ids"}, query = {"pagesize", "page", "filter", "callback"} },
    ["stackexchange.get_users_ids_questions"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/questions", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_questions_featured"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/questions/featured", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_questions_no_answers"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/questions/no-answers", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_questions_unaccepted"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/questions/unaccepted", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_questions_unanswered"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/questions/unanswered", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_reputation"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/reputation", path = {"ids"}, query = {"fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_reputation_history"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/reputation-history", path = {"ids"}, query = {"pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_suggested_edits"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/suggested-edits", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_tags"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/tags", path = {"ids"}, query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_ids_timeline"] = { method = "GET", url = "https://api.stackexchange.com/users/{ids}/timeline", path = {"ids"}, query = {"fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_moderators"] = { method = "GET", url = "https://api.stackexchange.com/users/moderators", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.get_users_moderators_elected"] = { method = "GET", url = "https://api.stackexchange.com/users/moderators/elected", query = {"order", "max", "min", "sort", "fromdate", "todate", "pagesize", "page", "filter", "callback", "site"} },
    ["stackexchange.post_comments_id_delete"] = { method = "POST", url = "https://api.stackexchange.com/comments/{id}/delete", path = {"id"}, query = {"filter", "callback", "site", "preview"} },
    ["stackexchange.post_comments_id_edit"] = { method = "POST", url = "https://api.stackexchange.com/comments/{id}/edit", path = {"id"}, query = {"filter", "callback", "site", "body", "preview"} },
    ["stackexchange.post_posts_id_comments_add"] = { method = "POST", url = "https://api.stackexchange.com/posts/{id}/comments/add", path = {"id"}, query = {"filter", "callback", "site", "body", "preview"} },
  },
}
