-- Retell AI — every call this API accepts, as data.
--
-- GENERATED from https://docs.retellai.com/openapi.yaml
-- Published on the vendor's own documentation site (https://docs.retellai.com).
-- 108 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "retell-ai",
  name = "Retell AI",
  base = "https://api.retellai.com",
  docs = "https://nango.dev/docs/integrations/all/retell-ai",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "RETELL_AI_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["retell-ai.add_community_voice"] = { method = "POST", url = "https://api.retellai.com/add-community-voice", body = {"voice_provider", "provider_voice_id", "voice_name", "public_user_id"} },
    ["retell-ai.add_knowledge_base_sources"] = { method = "POST", url = "https://api.retellai.com/add-knowledge-base-sources/{knowledge_base_id}", path = {"knowledge_base_id"}, body = {"knowledge_base_texts", "knowledge_base_files", "knowledge_base_urls"} },
    ["retell-ai.agent_playground_completion"] = { method = "POST", url = "https://api.retellai.com/agent-playground-completion/{agent_id}", path = {"agent_id"}, query = {"version"}, body = {"messages", "dynamic_variables", "tool_mocks", "current_state", "current_node_id", "component_id"} },
    ["retell-ai.backfill_contact_analysis_data"] = { method = "POST", url = "https://api.retellai.com/backfill-contact-analysis-data", body = {"backfill_call_filter", "backfill_attributes"} },
    ["retell-ai.clone_voice"] = { method = "POST", url = "https://api.retellai.com/clone-voice", body = {"files", "voice_name", "voice_provider"} },
    ["retell-ai.create_agent"] = { method = "POST", url = "https://api.retellai.com/create-agent", body = {"response_engine", "agent_name", "version_description", "version_title", "voice_id", "voice_model", "fallback_voice_ids", "voice_temperature", "voice_speed", "enable_dynamic_voice_speed", "enable_dynamic_responsiveness", "volume", "voice_emotion", "enable_expressive_mode", "expressive_emotion_tags", "expressive_mode_prompt", "responsiveness", "interruption_sensitivity", "enable_backchannel", "backchannel_frequency", "backchannel_words", "reminder_trigger_ms", "reminder_max_count", "ambient_sound", "ambient_sound_volume", "language", "webhook_url", "webhook_events", "webhook_timeout_ms", "boosted_keywords", "data_storage_setting", "data_storage_retention_days", "opt_in_signed_url", "signed_url_expiration_ms", "pronunciation_dictionary", "end_call_after_silence_ms", "max_call_duration_ms", "voicemail_option", "ivr_option", "call_screening_option", "post_call_analysis_data", "post_call_analysis_model", "begin_message_delay_ms", "ring_duration_ms", "stt_mode", "custom_stt_config", "vocab_specialization", "allow_user_dtmf", "allow_dtmf_interruption", "user_dtmf_options", "denoising_mode", "pii_config", "guardrail_config", "handbook_config", "timezone"} },
    ["retell-ai.create_agent_version"] = { method = "POST", url = "https://api.retellai.com/create-agent-version/{agent_id}", path = {"agent_id"}, body = {"base_version"} },
    ["retell-ai.create_app"] = { method = "POST", url = "https://api.retellai.com/create-app", body = {"type", "provider", "name", "tenant_url", "tenant_id", "auth_config", "crm_config"} },
    ["retell-ai.create_asset"] = { method = "POST", url = "https://api.retellai.com/create-asset", body = {"file"} },
    ["retell-ai.create_batch_call"] = { method = "POST", url = "https://api.retellai.com/create-batch-call", body = {"name", "trigger_timestamp", "from_number", "reserved_concurrency", "tasks", "call_time_window"} },
    ["retell-ai.create_batch_test"] = { method = "POST", url = "https://api.retellai.com/create-batch-test", body = {"test_case_definition_ids", "response_engine"} },
    ["retell-ai.create_chat"] = { method = "POST", url = "https://api.retellai.com/create-chat", body = {"agent_id", "agent_version", "metadata", "retell_llm_dynamic_variables"} },
    ["retell-ai.create_chat_agent"] = { method = "POST", url = "https://api.retellai.com/create-chat-agent", body = {"response_engine", "agent_name", "version_title", "auto_close_message", "end_chat_after_silence_ms", "language", "webhook_url", "webhook_events", "webhook_timeout_ms", "data_storage_setting", "data_storage_retention_days", "opt_in_signed_url", "signed_url_expiration_ms", "post_chat_analysis_data", "post_chat_analysis_model", "pii_config", "guardrail_config", "handbook_config", "timezone"} },
    ["retell-ai.create_chat_completion"] = { method = "POST", url = "https://api.retellai.com/create-chat-completion", body = {"chat_id", "content"} },
    ["retell-ai.create_contact"] = { method = "POST", url = "https://api.retellai.com/create-contact", body = {"phone_number", "first_name", "last_name", "do_not_call", "contact_tags", "custom_fields"} },
    ["retell-ai.create_contact_import"] = { method = "POST", url = "https://api.retellai.com/create-contact-import", body = {"upload_id", "column_mapping", "default_country", "contact_tags"} },
    ["retell-ai.create_conversation_flow"] = { method = "POST", url = "https://api.retellai.com/create-conversation-flow" },
    ["retell-ai.create_conversation_flow_component"] = { method = "POST", url = "https://api.retellai.com/create-conversation-flow-component", body = {"name", "flex_mode", "tools", "mcps", "nodes", "start_node_id", "begin_tag_display_position", "notes"} },
    ["retell-ai.create_knowledge_base"] = { method = "POST", url = "https://api.retellai.com/create-knowledge-base", body = {"knowledge_base_name", "knowledge_base_texts", "knowledge_base_files", "knowledge_base_urls", "enable_auto_refresh", "max_chunk_size", "min_chunk_size"} },
    ["retell-ai.create_phone_call"] = { method = "POST", url = "https://api.retellai.com/v2/create-phone-call", body = {"from_number", "to_number", "override_agent_id", "override_agent_version", "agent_override", "metadata", "retell_llm_dynamic_variables", "custom_sip_headers", "ignore_e164_validation"} },
    ["retell-ai.create_phone_number"] = { method = "POST", url = "https://api.retellai.com/create-phone-number", body = {"inbound_agents", "outbound_agents", "area_code", "nickname", "inbound_webhook_url", "allowed_inbound_country_list", "allowed_outbound_country_list", "number_provider", "country_code", "toll_free", "phone_number", "transport", "fallback_number"} },
    ["retell-ai.create_retell_llm"] = { method = "POST", url = "https://api.retellai.com/create-retell-llm", body = {"model", "s2s_model", "model_temperature", "model_high_priority", "tool_call_strict_mode", "knowledge_base_ids", "kb_config", "start_speaker", "begin_after_user_silence_ms", "begin_message"} },
    ["retell-ai.create_sms_chat"] = { method = "POST", url = "https://api.retellai.com/create-sms-chat", body = {"from_number", "to_number", "override_agent_id", "override_agent_version", "metadata", "retell_llm_dynamic_variables"} },
    ["retell-ai.create_test_case_definition"] = { method = "POST", url = "https://api.retellai.com/create-test-case-definition", body = {"name", "response_engine", "user_prompt", "metrics", "dynamic_variables", "tool_mocks", "llm_model"} },
    ["retell-ai.create_web_call"] = { method = "POST", url = "https://api.retellai.com/v3/create-web-call", body = {"agent_id", "agent_version", "agent_override", "metadata", "retell_llm_dynamic_variables", "current_node_id", "current_state"} },
    ["retell-ai.delete_agent"] = { method = "DELETE", url = "https://api.retellai.com/delete-agent/{agent_id}", path = {"agent_id"} },
    ["retell-ai.delete_agent_version"] = { method = "DELETE", url = "https://api.retellai.com/delete-agent-version/{agent_id}", path = {"agent_id"}, query = {"version"} },
    ["retell-ai.delete_app"] = { method = "DELETE", url = "https://api.retellai.com/delete-app/{app_id}", path = {"app_id"}, query = {"force_delete"} },
    ["retell-ai.delete_call"] = { method = "DELETE", url = "https://api.retellai.com/v2/delete-call/{call_id}", path = {"call_id"} },
    ["retell-ai.delete_chat"] = { method = "DELETE", url = "https://api.retellai.com/delete-chat/{chat_id}", path = {"chat_id"} },
    ["retell-ai.delete_chat_agent"] = { method = "DELETE", url = "https://api.retellai.com/delete-chat-agent/{agent_id}", path = {"agent_id"} },
    ["retell-ai.delete_contact"] = { method = "DELETE", url = "https://api.retellai.com/delete-contact/{contact_id}", path = {"contact_id"} },
    ["retell-ai.delete_conversation_flow"] = { method = "DELETE", url = "https://api.retellai.com/delete-conversation-flow/{conversation_flow_id}", path = {"conversation_flow_id"}, query = {"force_delete"} },
    ["retell-ai.delete_conversation_flow_component"] = { method = "DELETE", url = "https://api.retellai.com/delete-conversation-flow-component/{conversation_flow_component_id}", path = {"conversation_flow_component_id"} },
    ["retell-ai.delete_knowledge_base"] = { method = "DELETE", url = "https://api.retellai.com/delete-knowledge-base/{knowledge_base_id}", path = {"knowledge_base_id"} },
    ["retell-ai.delete_knowledge_base_source"] = { method = "DELETE", url = "https://api.retellai.com/delete-knowledge-base-source/{knowledge_base_id}/source/{source_id}", path = {"knowledge_base_id", "source_id"} },
    ["retell-ai.delete_phone_number"] = { method = "DELETE", url = "https://api.retellai.com/delete-phone-number/{phone_number}", path = {"phone_number"} },
    ["retell-ai.delete_retell_llm"] = { method = "DELETE", url = "https://api.retellai.com/delete-retell-llm/{llm_id}", path = {"llm_id"}, query = {"force_delete"} },
    ["retell-ai.delete_test_case_definition"] = { method = "DELETE", url = "https://api.retellai.com/delete-test-case-definition/{test_case_definition_id}", path = {"test_case_definition_id"} },
    ["retell-ai.end_chat"] = { method = "PATCH", url = "https://api.retellai.com/end-chat/{chat_id}", path = {"chat_id"} },
    ["retell-ai.get_agent"] = { method = "GET", url = "https://api.retellai.com/get-agent/{agent_id}", path = {"agent_id"}, query = {"version"} },
    ["retell-ai.get_api_key_info"] = { method = "GET", url = "https://api.retellai.com/get-api-key-info" },
    ["retell-ai.get_app"] = { method = "GET", url = "https://api.retellai.com/get-app/{app_id}", path = {"app_id"} },
    ["retell-ai.get_backfill_contact_job_status"] = { method = "GET", url = "https://api.retellai.com/get-backfill-contact-job-status" },
    ["retell-ai.get_batch_test"] = { method = "GET", url = "https://api.retellai.com/get-batch-test/{test_case_batch_job_id}", path = {"test_case_batch_job_id"} },
    ["retell-ai.get_call"] = { method = "GET", url = "https://api.retellai.com/v2/get-call/{call_id}", path = {"call_id"} },
    ["retell-ai.get_chat"] = { method = "GET", url = "https://api.retellai.com/get-chat/{chat_id}", path = {"chat_id"} },
    ["retell-ai.get_chat_agent"] = { method = "GET", url = "https://api.retellai.com/get-chat-agent/{agent_id}", path = {"agent_id"}, query = {"version"} },
    ["retell-ai.get_concurrency"] = { method = "GET", url = "https://api.retellai.com/get-concurrency" },
    ["retell-ai.get_contact"] = { method = "GET", url = "https://api.retellai.com/get-contact/{contact_id}", path = {"contact_id"} },
    ["retell-ai.get_contact_by_phone"] = { method = "GET", url = "https://api.retellai.com/get-contact-by-phone/{phone_number}", path = {"phone_number"} },
    ["retell-ai.get_contact_import"] = { method = "GET", url = "https://api.retellai.com/get-contact-import" },
    ["retell-ai.get_conversation_flow"] = { method = "GET", url = "https://api.retellai.com/get-conversation-flow/{conversation_flow_id}", path = {"conversation_flow_id"}, query = {"version"} },
    ["retell-ai.get_conversation_flow_component"] = { method = "GET", url = "https://api.retellai.com/get-conversation-flow-component/{conversation_flow_component_id}", path = {"conversation_flow_component_id"} },
    ["retell-ai.get_crm_config"] = { method = "GET", url = "https://api.retellai.com/get-crm-config" },
    ["retell-ai.get_crm_schema"] = { method = "GET", url = "https://api.retellai.com/get-crm-schema", query = {"app_id"} },
    ["retell-ai.get_knowledge_base"] = { method = "GET", url = "https://api.retellai.com/get-knowledge-base/{knowledge_base_id}", path = {"knowledge_base_id"} },
    ["retell-ai.get_mcptools"] = { method = "GET", url = "https://api.retellai.com/get-mcp-tools/{agent_id}", path = {"agent_id"}, query = {"version", "mcp_id", "component_id"} },
    ["retell-ai.get_phone_number"] = { method = "GET", url = "https://api.retellai.com/get-phone-number/{phone_number}", path = {"phone_number"} },
    ["retell-ai.get_retell_llm"] = { method = "GET", url = "https://api.retellai.com/get-retell-llm/{llm_id}", path = {"llm_id"}, query = {"version"} },
    ["retell-ai.get_sync_job_status"] = { method = "GET", url = "https://api.retellai.com/get-sync-job-status" },
    ["retell-ai.get_test_case_definition"] = { method = "GET", url = "https://api.retellai.com/get-test-case-definition/{test_case_definition_id}", path = {"test_case_definition_id"} },
    ["retell-ai.get_test_run"] = { method = "GET", url = "https://api.retellai.com/get-test-run/{test_case_job_id}", path = {"test_case_job_id"} },
    ["retell-ai.get_voice"] = { method = "GET", url = "https://api.retellai.com/get-voice/{voice_id}", path = {"voice_id"} },
    ["retell-ai.import_phone_number"] = { method = "POST", url = "https://api.retellai.com/import-phone-number", body = {"phone_number", "ignore_e164_validation", "termination_uri", "sip_trunk_auth_username", "sip_trunk_auth_password", "inbound_agents", "outbound_agents", "nickname", "inbound_webhook_url", "allowed_inbound_country_list", "allowed_outbound_country_list", "transport"} },
    ["retell-ai.list_agent_versions"] = { method = "GET", url = "https://api.retellai.com/list-agent-versions/{agent_id}", path = {"agent_id"}, query = {"limit", "sort_order", "pagination_key"} },
    ["retell-ai.list_agents"] = { method = "POST", url = "https://api.retellai.com/v2/list-agents", query = {"limit", "sort_order", "pagination_key"}, body = {"filter_criteria"} },
    ["retell-ai.list_app_usages"] = { method = "GET", url = "https://api.retellai.com/list-app-usages/{app_id}", path = {"app_id"}, query = {"limit", "sort_order", "pagination_key"} },
    ["retell-ai.list_apps"] = { method = "GET", url = "https://api.retellai.com/list-apps", query = {"limit", "sort_order", "pagination_key"} },
    ["retell-ai.list_batch_tests"] = { method = "GET", url = "https://api.retellai.com/v2/list-batch-tests", query = {"type", "llm_id", "conversation_flow_id", "version", "limit", "pagination_key"} },
    ["retell-ai.list_calls"] = { method = "POST", url = "https://api.retellai.com/v3/list-calls", body = {"filter_criteria", "sort_order", "limit", "skip", "pagination_key", "include_total"} },
    ["retell-ai.list_chats"] = { method = "POST", url = "https://api.retellai.com/v3/list-chats", body = {"filter_criteria", "sort_order", "limit", "skip", "pagination_key", "include_total"} },
    ["retell-ai.list_contact_conversations"] = { method = "GET", url = "https://api.retellai.com/list-contact-conversations/{contact_id}", path = {"contact_id"}, query = {"limit", "pagination_key"} },
    ["retell-ai.list_contacts"] = { method = "POST", url = "https://api.retellai.com/list-contacts", body = {"limit", "skip", "sort_order", "pagination_key", "filter_criteria", "search_query"} },
    ["retell-ai.list_conversation_flow_components"] = { method = "GET", url = "https://api.retellai.com/v2/list-conversation-flow-components", query = {"limit", "sort_order", "pagination_key"} },
    ["retell-ai.list_conversation_flows"] = { method = "GET", url = "https://api.retellai.com/v2/list-conversation-flows", query = {"limit", "sort_order", "pagination_key"} },
    ["retell-ai.list_export_requests"] = { method = "GET", url = "https://api.retellai.com/v2/list-export-requests", query = {"limit", "sort_order", "pagination_key"} },
    ["retell-ai.list_knowledge_bases"] = { method = "GET", url = "https://api.retellai.com/list-knowledge-bases" },
    ["retell-ai.list_phone_numbers"] = { method = "GET", url = "https://api.retellai.com/v2/list-phone-numbers", query = {"limit", "sort_order", "pagination_key"} },
    ["retell-ai.list_retell_llm"] = { method = "GET", url = "https://api.retellai.com/v2/list-retell-llms", query = {"limit", "sort_order", "pagination_key"} },
    ["retell-ai.list_test_case_definitions"] = { method = "GET", url = "https://api.retellai.com/v2/list-test-case-definitions", query = {"type", "llm_id", "conversation_flow_id", "limit", "pagination_key"} },
    ["retell-ai.list_test_runs"] = { method = "GET", url = "https://api.retellai.com/v2/list-test-runs/{test_case_batch_job_id}", path = {"test_case_batch_job_id"}, query = {"limit", "pagination_key"} },
    ["retell-ai.list_voices"] = { method = "GET", url = "https://api.retellai.com/list-voices" },
    ["retell-ai.listen_live_call"] = { method = "POST", url = "https://api.retellai.com/v2/listen-live-call/{call_id}", path = {"call_id"} },
    ["retell-ai.publish_agent_version"] = { method = "POST", url = "https://api.retellai.com/publish-agent-version/{agent_id}", path = {"agent_id"}, body = {"version", "version_description", "version_title"} },
    ["retell-ai.register_phone_call"] = { method = "POST", url = "https://api.retellai.com/v2/register-phone-call", body = {"agent_id", "agent_version", "agent_override", "from_number", "to_number", "direction", "metadata", "retell_llm_dynamic_variables"} },
    ["retell-ai.repair_agent"] = { method = "POST", url = "https://api.retellai.com/repair-agent/{agent_id}", path = {"agent_id"}, query = {"version"} },
    ["retell-ai.rerun_call_analysis"] = { method = "PUT", url = "https://api.retellai.com/rerun-call-analysis/{call_id}", path = {"call_id"} },
    ["retell-ai.rerun_chat_analysis"] = { method = "PUT", url = "https://api.retellai.com/rerun-chat-analysis/{chat_id}", path = {"chat_id"} },
    ["retell-ai.run_sync_job"] = { method = "POST", url = "https://api.retellai.com/run-sync-job" },
    ["retell-ai.search_community_voice"] = { method = "POST", url = "https://api.retellai.com/search-community-voice", body = {"voice_provider", "search_query"} },
    ["retell-ai.stop_call"] = { method = "POST", url = "https://api.retellai.com/v2/stop-call/{call_id}", path = {"call_id"} },
    ["retell-ai.take_over_live_call"] = { method = "POST", url = "https://api.retellai.com/v2/take-over-live-call/{call_id}", path = {"call_id"}, body = {"participant_id"} },
    ["retell-ai.test_app_auth"] = { method = "POST", url = "https://api.retellai.com/test-app-auth/{app_id}", path = {"app_id"} },
    ["retell-ai.update_agent"] = { method = "PATCH", url = "https://api.retellai.com/update-agent/{agent_id}", path = {"agent_id"}, query = {"version"}, body = {"response_engine", "agent_name", "version_description", "version_title", "voice_id", "voice_model", "fallback_voice_ids", "voice_temperature", "voice_speed", "enable_dynamic_voice_speed", "enable_dynamic_responsiveness", "volume", "voice_emotion", "enable_expressive_mode", "expressive_emotion_tags", "expressive_mode_prompt", "responsiveness", "interruption_sensitivity", "enable_backchannel", "backchannel_frequency", "backchannel_words", "reminder_trigger_ms", "reminder_max_count", "ambient_sound", "ambient_sound_volume", "language", "webhook_url", "webhook_events", "webhook_timeout_ms", "boosted_keywords", "data_storage_setting", "data_storage_retention_days", "opt_in_signed_url", "signed_url_expiration_ms", "pronunciation_dictionary", "end_call_after_silence_ms", "max_call_duration_ms", "voicemail_option", "ivr_option", "call_screening_option", "post_call_analysis_data", "post_call_analysis_model", "begin_message_delay_ms", "ring_duration_ms", "stt_mode", "custom_stt_config", "vocab_specialization", "allow_user_dtmf", "allow_dtmf_interruption", "user_dtmf_options", "denoising_mode", "pii_config", "guardrail_config", "handbook_config", "timezone"} },
    ["retell-ai.update_app"] = { method = "PATCH", url = "https://api.retellai.com/update-app/{app_id}", path = {"app_id"}, body = {"name", "tenant_url", "tenant_id", "auth_config", "crm_config"} },
    ["retell-ai.update_call_metadata"] = { method = "PATCH", url = "https://api.retellai.com/v2/update-call/{call_id}", path = {"call_id"}, body = {"metadata", "data_storage_setting", "custom_attributes"} },
    ["retell-ai.update_chat_agent"] = { method = "PATCH", url = "https://api.retellai.com/update-chat-agent/{agent_id}", path = {"agent_id"}, query = {"version"}, body = {"response_engine", "agent_name", "version_title", "auto_close_message", "end_chat_after_silence_ms", "language", "webhook_url", "webhook_events", "webhook_timeout_ms", "data_storage_setting", "data_storage_retention_days", "opt_in_signed_url", "signed_url_expiration_ms", "post_chat_analysis_data", "post_chat_analysis_model", "pii_config", "guardrail_config", "handbook_config", "timezone"} },
    ["retell-ai.update_chat_metadata"] = { method = "PATCH", url = "https://api.retellai.com/update-chat/{chat_id}", path = {"chat_id"}, body = {"metadata", "data_storage_setting", "override_dynamic_variables", "custom_attributes"} },
    ["retell-ai.update_contact"] = { method = "PATCH", url = "https://api.retellai.com/update-contact/{contact_id}", path = {"contact_id"}, body = {"first_name", "last_name", "do_not_call", "contact_tags", "custom_fields"} },
    ["retell-ai.update_conversation_flow"] = { method = "PATCH", url = "https://api.retellai.com/update-conversation-flow/{conversation_flow_id}", path = {"conversation_flow_id"}, query = {"version"}, body = {"model_choice", "model_temperature", "tool_call_strict_mode", "knowledge_base_ids", "kb_config", "start_speaker", "begin_after_user_silence_ms"} },
    ["retell-ai.update_conversation_flow_component"] = { method = "PATCH", url = "https://api.retellai.com/update-conversation-flow-component/{conversation_flow_component_id}", path = {"conversation_flow_component_id"}, body = {"name", "flex_mode", "tools", "mcps", "nodes", "start_node_id", "begin_tag_display_position", "notes"} },
    ["retell-ai.update_crm_config"] = { method = "POST", url = "https://api.retellai.com/update-crm-config", body = {"app_id", "custom_fields", "crm_analysis_data_mappings", "contact_tags", "contact_columns_order"} },
    ["retell-ai.update_live_call"] = { method = "PATCH", url = "https://api.retellai.com/v2/update-live-call/{call_id}", path = {"call_id"}, body = {"fields_to_override", "call_control"} },
    ["retell-ai.update_phone_number"] = { method = "PATCH", url = "https://api.retellai.com/update-phone-number/{phone_number}", path = {"phone_number"}, body = {"inbound_agents", "outbound_agents", "inbound_sms_agents", "outbound_sms_agents", "nickname", "inbound_webhook_url", "inbound_sms_webhook_url", "allowed_inbound_country_list", "allowed_outbound_country_list", "termination_uri", "auth_username", "auth_password", "transport", "fallback_number"} },
    ["retell-ai.update_retell_llm"] = { method = "PATCH", url = "https://api.retellai.com/update-retell-llm/{llm_id}", path = {"llm_id"}, query = {"version"}, body = {"model", "s2s_model", "model_temperature", "model_high_priority", "tool_call_strict_mode", "knowledge_base_ids", "kb_config", "start_speaker", "begin_after_user_silence_ms", "begin_message"} },
    ["retell-ai.update_test_case_definition"] = { method = "PUT", url = "https://api.retellai.com/update-test-case-definition/{test_case_definition_id}", path = {"test_case_definition_id"}, body = {"name", "response_engine", "user_prompt", "metrics", "dynamic_variables", "tool_mocks", "llm_model"} },
    ["retell-ai.upload_contact_import_file"] = { method = "POST", url = "https://api.retellai.com/upload-contact-import-file", body = {"file"} },
  },
}
