-- Zoom — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/zoom.us/2.0.0/openapi.json
-- APIs.guru's mirror of zoom.us, matched on zoom.us. A mirror lags the vendor.
-- 369 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "zoom",
  name = "Zoom",
  base = "https://api.zoom.us/v2",
  docs = "https://nango.dev/docs/api-integrations/zoom",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "ZOOM_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["zoom.account"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}", path = {"accountId"} },
    ["zoom.account_billing"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/billing", path = {"accountId"} },
    ["zoom.account_billing_invoices"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/billing/invoices", path = {"accountId"}, query = {"from", "to"} },
    ["zoom.account_billing_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/billing", path = {"accountId"}, body = {"address", "apt", "city", "country", "email", "first_name", "last_name", "phone_number", "state", "zip"} },
    ["zoom.account_call_logs"] = { method = "GET", url = "https://api.zoom.us/v2/phone/call_logs", query = {"page_size", "from", "to", "type", "next_page_token", "path", "time_type", "site_id"} },
    ["zoom.account_create"] = { method = "POST", url = "https://api.zoom.us/v2/accounts", body = {"account_name", "email", "first_name", "last_name", "options", "password"} },
    ["zoom.account_disassociate"] = { method = "DELETE", url = "https://api.zoom.us/v2/accounts/{accountId}", path = {"accountId"} },
    ["zoom.account_managed_domain"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/managed_domains", path = {"accountId"} },
    ["zoom.account_options_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/options", path = {"accountId"}, body = {"billing_auto_renew", "meeting_connector_list", "pay_mode", "room_connector_list", "share_mc", "share_rc"} },
    ["zoom.account_plan_addon_cancel"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/plans/addons/status", path = {"accountId"}, body = {"action", "comment", "reason", "type"} },
    ["zoom.account_plan_addon_create"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/plans/addons", path = {"accountId"} },
    ["zoom.account_plan_addon_update"] = { method = "PUT", url = "https://api.zoom.us/v2/accounts/{accountId}/plans/addons", path = {"accountId"}, body = {"hosts", "type"} },
    ["zoom.account_plan_base_delete"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/plans/base/status", path = {"accountId"}, body = {"action", "comment", "reason"} },
    ["zoom.account_plan_base_update"] = { method = "PUT", url = "https://api.zoom.us/v2/accounts/{accountId}/plans/base", path = {"accountId"}, body = {"hosts", "type"} },
    ["zoom.account_plan_create"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/plans", path = {"accountId"}, body = {"contact"} },
    ["zoom.account_plans"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/plans", path = {"accountId"} },
    ["zoom.account_settings"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/settings", path = {"accountId"}, query = {"option", "custom_query_fields"} },
    ["zoom.account_settings_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/settings", path = {"accountId"}, query = {"option"} },
    ["zoom.account_trusted_domain"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/trusted_domains", path = {"accountId"} },
    ["zoom.accounts"] = { method = "GET", url = "https://api.zoom.us/v2/accounts", query = {"page_size", "page_number", "next_page_token"} },
    ["zoom.add_anumber_to_blocked_list"] = { method = "POST", url = "https://api.zoom.us/v2/phone/blocked_list", body = {"block_type", "comment", "match_type", "phone_number", "status"} },
    ["zoom.add_aroom"] = { method = "POST", url = "https://api.zoom.us/v2/rooms", body = {"location_id", "name", "type"} },
    ["zoom.add_auto_receptionist"] = { method = "POST", url = "https://api.zoom.us/v2/phone/auto_receptionists", body = {"name", "site_id"} },
    ["zoom.add_azrlocation"] = { method = "POST", url = "https://api.zoom.us/v2/rooms/locations", body = {"name", "parent_location_id"} },
    ["zoom.add_batch_webinar_registrants"] = { method = "POST", url = "https://api.zoom.us/v2/webinars/{webinarId}/batch_registrants", path = {"webinarId", "webinarId"}, body = {"auto_approve", "registrants"} },
    ["zoom.add_byocnumber"] = { method = "POST", url = "https://api.zoom.us/v2/phone/byoc_numbers", body = {"carrier", "phone_numbers", "site_id"} },
    ["zoom.add_callout_countries"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/callout_countries", path = {"accountId", "accountId"}, body = {"callout_countries"} },
    ["zoom.add_common_area_phone"] = { method = "POST", url = "https://api.zoom.us/v2/phone/common_area_phones", body = {"description", "display_name", "extension_number", "mac_address", "model", "site_id", "time_zone", "type"} },
    ["zoom.add_internal_numbers"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/internal_numbers", path = {"accountId", "accountId"}, body = {"internal_numbers"} },
    ["zoom.add_members_to_call_queue"] = { method = "POST", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}/members", path = {"callQueueId", "callQueueId"}, body = {"members"} },
    ["zoom.add_members_to_shared_line_group"] = { method = "POST", url = "https://api.zoom.us/v2/phone/shared_line_groups/{sharedLineGroupId}/members", path = {"sharedLineGroupId", "sharedLineGroupId"}, body = {"members"} },
    ["zoom.add_phone_device"] = { method = "POST", url = "https://api.zoom.us/v2/phone/devices", body = {"assigned_to", "display_name", "mac_address", "model", "type"} },
    ["zoom.add_role_members"] = { method = "POST", url = "https://api.zoom.us/v2/roles/{roleId}/members", path = {"roleId"}, body = {"members"} },
    ["zoom.add_setting_template"] = { method = "POST", url = "https://api.zoom.us/v2/phone/setting_templates", body = {"description", "name", "site_id", "type"} },
    ["zoom.add_user_setting"] = { method = "POST", url = "https://api.zoom.us/v2/phone/users/{userId}/settings/{settingType}", path = {"userId", "settingType"}, body = {"voice_mail"} },
    ["zoom.assign_calling_plan"] = { method = "POST", url = "https://api.zoom.us/v2/phone/users/{userId}/calling_plans", path = {"userId"}, body = {"calling_plans"} },
    ["zoom.assign_phone_number"] = { method = "POST", url = "https://api.zoom.us/v2/phone/users/{userId}/phone_numbers", path = {"userId"}, body = {"phone_numbers"} },
    ["zoom.assign_phone_numbers_auto_receptionist"] = { method = "POST", url = "https://api.zoom.us/v2/phone/auto_receptionists/{autoReceptionistId}/phone_numbers", path = {"autoReceptionistId", "autoReceptionistId"}, body = {"phone_numbers"} },
    ["zoom.assign_phone_numbers_slg"] = { method = "POST", url = "https://api.zoom.us/v2/phone/shared_line_groups/{sharedLineGroupId}/phone_numbers", path = {"sharedLineGroupId", "sharedLineGroupId"}, body = {"phone_numbers"} },
    ["zoom.assign_phone_to_call_queue"] = { method = "POST", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}/phone_numbers", path = {"callQueueId", "callQueueId"}, body = {"phone_numbers"} },
    ["zoom.assign_sip_trunk_numbers"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/numbers", path = {"accountId", "accountId"}, body = {"phone_numbers"} },
    ["zoom.assign_sipconfig"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/settings", path = {"accountId"}, body = {"enable", "show_callout_internal_number", "show_zoom_provided_callout_countries", "show_zoom_provided_numbers"} },
    ["zoom.assign_siptrunks"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/trunks", path = {"accountId", "accountId"}, body = {"sip_trunks"} },
    ["zoom.change_call_queue_manager"] = { method = "PUT", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}/manager", path = {"callQueueId", "callQueueId"}, body = {"member_id"} },
    ["zoom.change_main_company_number"] = { method = "PUT", url = "https://api.zoom.us/v2/phone/company_number", body = {"phone_number"} },
    ["zoom.change_parent_location"] = { method = "PUT", url = "https://api.zoom.us/v2/rooms/locations/{locationId}/location", path = {"locationId", "locationId"}, body = {"parent_location_id"} },
    ["zoom.change_zoom_rooms_app_version"] = { method = "PUT", url = "https://api.zoom.us/v2/rooms/{roomId}/devices/{deviceId}/app_version", path = {"roomId", "deviceId", "roomId", "deviceId"}, body = {"action"} },
    ["zoom.change_zrlocation"] = { method = "PUT", url = "https://api.zoom.us/v2/rooms/{roomId}/location", path = {"roomId", "roomId"}, body = {"location_id"} },
    ["zoom.check_in_rooms"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/{id}/events", path = {"id", "id"}, body = {"method", "params"} },
    ["zoom.create_ashared_line_group"] = { method = "POST", url = "https://api.zoom.us/v2/phone/shared_line_groups", body = {"description", "display_name", "extension_number", "site_id"} },
    ["zoom.create_batch_polls"] = { method = "POST", url = "https://api.zoom.us/v2/meetings/{meetingId}/batch_polls", path = {"meetingId", "meetingId"}, body = {"questions", "title"} },
    ["zoom.create_call_queue"] = { method = "POST", url = "https://api.zoom.us/v2/phone/call_queues", body = {"description", "extension_number", "members", "name", "site_id"} },
    ["zoom.create_channel"] = { method = "POST", url = "https://api.zoom.us/v2/chat/users/{userId}/channels", path = {"userId", "userId"}, body = {"members", "name", "type"} },
    ["zoom.create_phone_site"] = { method = "POST", url = "https://api.zoom.us/v2/phone/sites", body = {"auto_receptionist_name", "default_emergency_address", "name", "short_extension", "site_code"} },
    ["zoom.create_role"] = { method = "POST", url = "https://api.zoom.us/v2/roles", body = {"description", "name", "privileges"} },
    ["zoom.create_sipphone"] = { method = "POST", url = "https://api.zoom.us/v2/sip_phones", body = {"authorization_name", "domain", "password", "proxy_server", "proxy_server2", "proxy_server3", "register_server", "register_server2", "register_server3", "registration_expire_time", "transport_protocol", "transport_protocol2", "transport_protocol3", "user_email", "user_name", "voice_mail"} },
    ["zoom.dashboard_client_feedback"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/client/feedback", query = {"from", "to"} },
    ["zoom.dashboard_client_feedback_detail"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/client/feedback/{feedbackId}", path = {"feedbackId"}, query = {"from", "to", "page_size", "next_page_token"} },
    ["zoom.dashboard_crc"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/crc", query = {"from", "to"} },
    ["zoom.dashboard_im"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/im", query = {"from", "to", "page_size", "next_page_token"} },
    ["zoom.dashboard_issue_detail_zoom_room"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/issues/zoomrooms/{zoomroomId}", path = {"zoomroomId"}, query = {"from", "to", "page_size", "next_page_token"} },
    ["zoom.dashboard_issue_zoom_room"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/issues/zoomrooms", query = {"from", "to"} },
    ["zoom.dashboard_meeting_detail"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/meetings/{meetingId}", path = {"meetingId"}, query = {"type"} },
    ["zoom.dashboard_meeting_participant_qos"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/meetings/{meetingId}/participants/{participantId}/qos", path = {"meetingId", "participantId"}, query = {"type"} },
    ["zoom.dashboard_meeting_participant_share"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/meetings/{meetingId}/participants/sharing", path = {"meetingId"}, query = {"type", "page_size", "next_page_token"} },
    ["zoom.dashboard_meeting_participants"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/meetings/{meetingId}/participants", path = {"meetingId"}, query = {"type", "page_size", "next_page_token", "include_fields"} },
    ["zoom.dashboard_meeting_participants_qos"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/meetings/{meetingId}/participants/qos", path = {"meetingId"}, query = {"type", "page_size", "next_page_token"} },
    ["zoom.dashboard_meetings"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/meetings", query = {"type", "from", "to", "page_size", "next_page_token", "include_fields"} },
    ["zoom.dashboard_webinar_detail"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/webinars/{webinarId}", path = {"webinarId"}, query = {"type"} },
    ["zoom.dashboard_webinar_participant_qos"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/webinars/{webinarId}/participants/{participantId}/qos", path = {"webinarId", "participantId"}, query = {"type"} },
    ["zoom.dashboard_webinar_participant_share"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/webinars/{webinarId}/participants/sharing", path = {"webinarId"}, query = {"type", "page_size", "next_page_token"} },
    ["zoom.dashboard_webinar_participants"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/webinars/{webinarId}/participants", path = {"webinarId"}, query = {"type", "page_size", "next_page_token", "include_fields"} },
    ["zoom.dashboard_webinar_participants_qos"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/webinars/{webinarId}/participants/qos", path = {"webinarId"}, query = {"type", "page_size", "next_page_token"} },
    ["zoom.dashboard_webinars"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/webinars", query = {"type", "from", "to", "page_size", "next_page_token"} },
    ["zoom.dashboard_zoom_room"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/zoomrooms/{zoomroomId}", path = {"zoomroomId"}, query = {"from", "to", "page_size", "next_page_token"} },
    ["zoom.dashboard_zoom_room_issue"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/zoomrooms/issues", query = {"from", "to"} },
    ["zoom.dashboard_zoom_rooms"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/zoomrooms", query = {"page_size", "page_number", "next_page_token"} },
    ["zoom.del_group_vb"] = { method = "DELETE", url = "https://api.zoom.us/v2/groups/{groupId}/settings/virtual_backgrounds", path = {"groupId", "groupId"}, query = {"file_ids", "file_ids"} },
    ["zoom.del_user_vb"] = { method = "DELETE", url = "https://api.zoom.us/v2/users/{userId}/settings/virtual_backgrounds", path = {"userId", "userId"}, query = {"file_ids"} },
    ["zoom.del_vb"] = { method = "DELETE", url = "https://api.zoom.us/v2/accounts/{accountId}/settings/virtual_backgrounds", path = {"accountId"}, query = {"file_ids"} },
    ["zoom.delete_ablocked_list"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/blocked_list/{blockedListId}", path = {"blockedListId", "blockedListId"} },
    ["zoom.delete_acall_queue"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}", path = {"callQueueId", "callQueueId"} },
    ["zoom.delete_achatbot_message"] = { method = "DELETE", url = "https://api.zoom.us/v2/im/chat/messages/{message_id}", path = {"message_id"}, body = {"account_id", "robot_jid", "user_jid"} },
    ["zoom.delete_adevice"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/devices/{deviceId}", path = {"deviceId", "deviceId"} },
    ["zoom.delete_all_sip_numbers"] = { method = "DELETE", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/numbers", path = {"accountId", "accountId"} },
    ["zoom.delete_amember_slg"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/shared_line_groups/{sharedLineGroupId}/members/{memberId}", path = {"sharedLineGroupId", "memberId", "sharedLineGroupId", "memberId"} },
    ["zoom.delete_aphone_number_slg"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/shared_line_groups/{sharedLineGroupId}/phone_numbers/{phoneNumberId}", path = {"sharedLineGroupId", "phoneNumberId", "sharedLineGroupId", "phoneNumberId"} },
    ["zoom.delete_ashared_line_group"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/shared_line_groups/{sharedLineGroupId}", path = {"sharedLineGroupId", "sharedLineGroupId"} },
    ["zoom.delete_azoom_room"] = { method = "DELETE", url = "https://api.zoom.us/v2/rooms/{roomId}", path = {"roomId", "roomId"} },
    ["zoom.delete_call_log"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/users/{userId}/call_logs/{callLogId}", path = {"userId", "callLogId", "userId", "callLogId"} },
    ["zoom.delete_channel"] = { method = "DELETE", url = "https://api.zoom.us/v2/chat/users/{userId}/channels/{channelId}", path = {"userId", "channelId", "channelId"} },
    ["zoom.delete_chat_message"] = { method = "DELETE", url = "https://api.zoom.us/v2/chat/users/{userId}/messages/{messageId}", path = {"userId", "messageId", "messageId"}, query = {"to_contact", "to_channel"} },
    ["zoom.delete_common_area_phone"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/common_area_phones/{commonAreaPhoneId}", path = {"commonAreaPhoneId", "commonAreaPhoneId"} },
    ["zoom.delete_internal_call_out_country"] = { method = "DELETE", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/callout_countries/{countryId}", path = {"accountId", "countryId", "accountId", "countryId"} },
    ["zoom.delete_internal_number"] = { method = "DELETE", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/internal_numbers/{numberId}", path = {"accountId", "numberId", "accountId", "numberId"} },
    ["zoom.delete_members_of_slg"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/shared_line_groups/{sharedLineGroupId}/members", path = {"sharedLineGroupId", "sharedLineGroupId"} },
    ["zoom.delete_phone_site"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/sites/{siteId}", path = {"siteId", "siteId"}, query = {"transfer_site_id"} },
    ["zoom.delete_role"] = { method = "DELETE", url = "https://api.zoom.us/v2/roles/{roleId}", path = {"roleId", "roleId"} },
    ["zoom.delete_sipphone"] = { method = "DELETE", url = "https://api.zoom.us/v2/sip_phones/{phoneId}", path = {"phoneId", "phoneId"} },
    ["zoom.delete_siptrunk"] = { method = "DELETE", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/trunks/{trunkId}", path = {"accountId", "trunkId", "accountId", "trunkId"} },
    ["zoom.delete_user_level_channel"] = { method = "DELETE", url = "https://api.zoom.us/v2/chat/channels/{channelId}", path = {"channelId", "channelId"} },
    ["zoom.delete_user_setting"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/users/{userId}/settings/{settingType}", path = {"userId", "settingType"}, query = {"shared_id"} },
    ["zoom.delete_voicemail"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/voice_mails/{voicemailId}", path = {"voicemailId", "voicemailId"} },
    ["zoom.delete_webinar_registrant"] = { method = "DELETE", url = "https://api.zoom.us/v2/webinars/{webinarId}/registrants/{registrantId}", path = {"webinarId", "registrantId", "webinarId", "registrantId"}, query = {"occurrence_id"} },
    ["zoom.device_create"] = { method = "POST", url = "https://api.zoom.us/v2/h323/devices", body = {"encryption", "ip", "name", "protocol"} },
    ["zoom.device_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/h323/devices/{deviceId}", path = {"deviceId"} },
    ["zoom.device_list"] = { method = "GET", url = "https://api.zoom.us/v2/h323/devices", query = {"page_size", "page_number", "next_page_token"} },
    ["zoom.device_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/h323/devices/{deviceId}", path = {"deviceId"}, body = {"encryption", "ip", "name", "protocol"} },
    ["zoom.download_invoice_pdf"] = { method = "GET", url = "https://api.zoom.us/v2/api/download/billing/invoices/{invoiceId}", path = {"invoiceId"} },
    ["zoom.edit_chatbot_message"] = { method = "PUT", url = "https://api.zoom.us/v2/im/chat/messages/{message_id}", path = {"message_id", "message_id"}, body = {"account_id", "content", "is_markdown_support", "robot_jid", "user_jid"} },
    ["zoom.edit_message"] = { method = "PUT", url = "https://api.zoom.us/v2/chat/users/{userId}/messages/{messageId}", path = {"userId", "messageId", "messageId"}, body = {"message", "to_channel", "to_contact"} },
    ["zoom.get_ablocked_list"] = { method = "GET", url = "https://api.zoom.us/v2/phone/blocked_list/{blockedListId}", path = {"blockedListId", "blockedListId"} },
    ["zoom.get_acall_queue"] = { method = "GET", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}", path = {"callQueueId", "callQueueId"} },
    ["zoom.get_account_billing_invoice"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/billing/invoices/{invoiceId}", path = {"accountId", "invoiceId"} },
    ["zoom.get_account_cloud_recording"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/recordings", path = {"accountId", "accountId"}, query = {"page_size", "next_page_token", "from", "to"} },
    ["zoom.get_account_lock_settings"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/lock_settings", path = {"accountId", "accountId"}, query = {"option", "custom_query_fields"} },
    ["zoom.get_acommon_area_phone"] = { method = "GET", url = "https://api.zoom.us/v2/phone/common_area_phones/{commonAreaPhoneId}", path = {"commonAreaPhoneId", "commonAreaPhoneId"} },
    ["zoom.get_adevice"] = { method = "GET", url = "https://api.zoom.us/v2/phone/devices/{deviceId}", path = {"deviceId", "deviceId"} },
    ["zoom.get_ashared_line_group"] = { method = "GET", url = "https://api.zoom.us/v2/phone/shared_line_groups/{sharedLineGroupId}", path = {"sharedLineGroupId", "sharedLineGroupId"} },
    ["zoom.get_asite"] = { method = "GET", url = "https://api.zoom.us/v2/phone/sites/{siteId}", path = {"siteId", "siteId"} },
    ["zoom.get_call_log_metrics_details"] = { method = "GET", url = "https://api.zoom.us/v2/phone/metrics/call_logs/{call_id}", path = {"call_id", "call_id"} },
    ["zoom.get_call_qo_s"] = { method = "GET", url = "https://api.zoom.us/v2/phone/metrics/call_logs/{callId}/qos", path = {"callId", "callId"} },
    ["zoom.get_call_queue_recordings"] = { method = "GET", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}/recordings", path = {"callQueueId", "callQueueId"}, query = {"page_size", "next_page_token", "from", "to"} },
    ["zoom.get_channel"] = { method = "GET", url = "https://api.zoom.us/v2/chat/users/{userId}/channels/{channelId}", path = {"userId", "channelId", "channelId", "userId"} },
    ["zoom.get_channels"] = { method = "GET", url = "https://api.zoom.us/v2/chat/users/{userId}/channels", path = {"userId", "userId"}, query = {"page_size", "next_page_token"} },
    ["zoom.get_chat_messages"] = { method = "GET", url = "https://api.zoom.us/v2/chat/users/{userId}/messages", path = {"userId"}, query = {"to_contact", "to_channel", "date", "page_size", "next_page_token", "include_deleted_and_edited_message"} },
    ["zoom.get_group_lock_settings"] = { method = "GET", url = "https://api.zoom.us/v2/groups/{groupId}/lock_settings", path = {"groupId", "groupId"}, query = {"custom_query_fields", "option"} },
    ["zoom.get_group_settings"] = { method = "GET", url = "https://api.zoom.us/v2/groups/{groupId}/settings", path = {"groupId"}, query = {"custom_query_fields", "option"} },
    ["zoom.get_live_stream_details"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/livestream", path = {"meetingId", "meetingId"} },
    ["zoom.get_phone_number_details"] = { method = "GET", url = "https://api.zoom.us/v2/phone/numbers/{numberId}", path = {"numberId", "numberId"} },
    ["zoom.get_phone_recordings"] = { method = "GET", url = "https://api.zoom.us/v2/phone/recordings", query = {"page_size", "next_page_token", "from", "to", "owner_type", "recording_type", "site_id"} },
    ["zoom.get_plan_usage"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/plans/usage", path = {"accountId"} },
    ["zoom.get_psoperation_logs"] = { method = "GET", url = "https://api.zoom.us/v2/phone/reports/operationlogs", query = {"from", "to", "category_type", "page_size", "next_page_token"} },
    ["zoom.get_role_information"] = { method = "GET", url = "https://api.zoom.us/v2/roles/{roleId}", path = {"roleId", "roleId"} },
    ["zoom.get_setting_template"] = { method = "GET", url = "https://api.zoom.us/v2/phone/setting_templates/{templateId}", path = {"templateId", "templateId"}, query = {"custom_query_fields"} },
    ["zoom.get_tracking_sources"] = { method = "GET", url = "https://api.zoom.us/v2/webinars/{webinarId}/tracking_sources", path = {"webinarId", "webinarId"} },
    ["zoom.get_user_contact"] = { method = "GET", url = "https://api.zoom.us/v2/chat/users/me/contacts/{contactId}", path = {"contactId", "contactId"}, query = {"query_presence_status"} },
    ["zoom.get_user_contacts"] = { method = "GET", url = "https://api.zoom.us/v2/chat/users/me/contacts", query = {"type", "page_size", "next_page_token"} },
    ["zoom.get_user_level_channel"] = { method = "GET", url = "https://api.zoom.us/v2/chat/channels/{channelId}", path = {"channelId", "channelId"} },
    ["zoom.get_zraccount_profile"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/account_profile" },
    ["zoom.get_zraccount_settings"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/account_settings", query = {"setting_type"} },
    ["zoom.get_zrlocation_profile"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/locations/{locationId}", path = {"locationId", "locationId"} },
    ["zoom.get_zrlocation_settings"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/locations/{locationId}/settings", path = {"locationId", "locationId"}, query = {"setting_type"} },
    ["zoom.get_zrlocation_structure"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/locations/structure" },
    ["zoom.get_zrprofile"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/{roomId}", path = {"roomId", "roomId"} },
    ["zoom.get_zrsettings"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/{roomId}/settings", path = {"roomId", "roomId"}, query = {"setting_type"} },
    ["zoom.group"] = { method = "GET", url = "https://api.zoom.us/v2/groups/{groupId}", path = {"groupId"} },
    ["zoom.group_create"] = { method = "POST", url = "https://api.zoom.us/v2/groups", body = {"name"} },
    ["zoom.group_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/groups/{groupId}", path = {"groupId"} },
    ["zoom.group_locked_settings"] = { method = "PATCH", url = "https://api.zoom.us/v2/groups/{groupId}/lock_settings", path = {"groupId", "groupId"}, query = {"custom_query_fields", "option"} },
    ["zoom.group_members"] = { method = "GET", url = "https://api.zoom.us/v2/groups/{groupId}/members", path = {"groupId"}, query = {"page_size", "page_number", "next_page_token"} },
    ["zoom.group_members_create"] = { method = "POST", url = "https://api.zoom.us/v2/groups/{groupId}/members", path = {"groupId"}, body = {"members"} },
    ["zoom.group_members_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/groups/{groupId}/members/{memberId}", path = {"groupId", "memberId", "groupId", "memberId"} },
    ["zoom.group_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/groups/{groupId}", path = {"groupId"}, body = {"name"} },
    ["zoom.groups"] = { method = "GET", url = "https://api.zoom.us/v2/groups" },
    ["zoom.im_group"] = { method = "GET", url = "https://api.zoom.us/v2/im/groups/{groupId}", path = {"groupId"} },
    ["zoom.im_group_create"] = { method = "POST", url = "https://api.zoom.us/v2/im/groups", body = {"name", "search_by_account", "search_by_domain", "search_by_ma_account", "type"} },
    ["zoom.im_group_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/im/groups/{groupId}", path = {"groupId"} },
    ["zoom.im_group_members"] = { method = "GET", url = "https://api.zoom.us/v2/im/groups/{groupId}/members", path = {"groupId"}, query = {"page_size", "page_number", "next_page_token"} },
    ["zoom.im_group_members_create"] = { method = "POST", url = "https://api.zoom.us/v2/im/groups/{groupId}/members", path = {"groupId"}, body = {"members"} },
    ["zoom.im_group_members_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/im/groups/{groupId}/members/{memberId}", path = {"groupId", "memberId"} },
    ["zoom.im_group_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/im/groups/{groupId}", path = {"groupId"}, body = {"name", "search_by_account", "search_by_domain", "search_by_ma_account", "type"} },
    ["zoom.im_groups"] = { method = "GET", url = "https://api.zoom.us/v2/im/groups" },
    ["zoom.in_meeting_recording_control"] = { method = "PATCH", url = "https://api.zoom.us/v2/live_meetings/{meetingId}/events", path = {"meetingId", "meetingId"}, body = {"method"} },
    ["zoom.invite_channel_members"] = { method = "POST", url = "https://api.zoom.us/v2/chat/users/{userId}/channels/{channelId}/members", path = {"userId", "channelId", "channelId", "userId"}, body = {"members"} },
    ["zoom.join_channel"] = { method = "POST", url = "https://api.zoom.us/v2/chat/channels/{channelId}/members/me", path = {"channelId", "channelId"} },
    ["zoom.leave_channel"] = { method = "DELETE", url = "https://api.zoom.us/v2/chat/channels/{channelId}/members/me", path = {"channelId", "channelId"} },
    ["zoom.list_account_phone_numbers"] = { method = "GET", url = "https://api.zoom.us/v2/phone/numbers", query = {"next_page_token", "type", "extension_type", "page_size", "number_type", "pending_numbers", "site_id"} },
    ["zoom.list_archived_files"] = { method = "GET", url = "https://api.zoom.us/v2/archive_files", query = {"page_size", "next_page_token", "from", "to", "query_data_type"} },
    ["zoom.list_blocked_list"] = { method = "GET", url = "https://api.zoom.us/v2/phone/blocked_list", query = {"next_page_token", "page_size"} },
    ["zoom.list_byocsiptrunk"] = { method = "GET", url = "https://api.zoom.us/v2/phone/sip_trunk/trunks", query = {"next_page_token", "page_size"} },
    ["zoom.list_call_logs_metrics"] = { method = "GET", url = "https://api.zoom.us/v2/phone/metrics/call_logs", query = {"from", "to", "site_id", "quality_type", "page_size", "next_page_token"} },
    ["zoom.list_call_queues"] = { method = "GET", url = "https://api.zoom.us/v2/phone/call_queues", query = {"next_page_token", "page_size"} },
    ["zoom.list_calling_plans"] = { method = "GET", url = "https://api.zoom.us/v2/phone/calling_plans" },
    ["zoom.list_channel_members"] = { method = "GET", url = "https://api.zoom.us/v2/chat/users/{userId}/channels/{channelId}/members", path = {"userId", "channelId", "channelId", "userId"}, query = {"page_size", "next_page_token"} },
    ["zoom.list_common_area_phones"] = { method = "GET", url = "https://api.zoom.us/v2/phone/common_area_phones", query = {"page_size", "next_page_token"} },
    ["zoom.list_digital_signage_content"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/digital_signage", query = {"type", "folder_id", "page_size", "next_page_token"} },
    ["zoom.list_internal_callout_countries"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/callout_countries", path = {"accountId", "accountId"} },
    ["zoom.list_internal_numbers"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/internal_numbers", path = {"accountId", "accountId"}, query = {"page_size", "next_page_token"} },
    ["zoom.list_meeting_satisfaction"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/client/satisfaction", query = {"from", "to"} },
    ["zoom.list_meeting_templates"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/meeting_templates", path = {"userId", "userId"} },
    ["zoom.list_past_meeting_files"] = { method = "GET", url = "https://api.zoom.us/v2/past_meetings/{meetingId}/files", path = {"meetingId", "meetingId"} },
    ["zoom.list_past_meeting_polls"] = { method = "GET", url = "https://api.zoom.us/v2/past_meetings/{meetingId}/polls", path = {"meetingId", "meetingId"} },
    ["zoom.list_past_webinar_files"] = { method = "GET", url = "https://api.zoom.us/v2/past_webinars/{webinarId}/files", path = {"webinarId", "webinarId"} },
    ["zoom.list_past_webinar_poll_results"] = { method = "GET", url = "https://api.zoom.us/v2/past_webinars/{webinarId}/polls", path = {"webinarId", "webinarId"} },
    ["zoom.list_past_webinar_qa"] = { method = "GET", url = "https://api.zoom.us/v2/past_webinars/{webinarId}/qa", path = {"webinarId", "webinarId"} },
    ["zoom.list_phone_devices"] = { method = "GET", url = "https://api.zoom.us/v2/phone/devices", query = {"type", "next_page_token", "page_size"} },
    ["zoom.list_phone_sites"] = { method = "GET", url = "https://api.zoom.us/v2/phone/sites", query = {"page_size", "next_page_token"} },
    ["zoom.list_phone_users"] = { method = "GET", url = "https://api.zoom.us/v2/phone/users", query = {"page_size", "next_page_token", "site_id"} },
    ["zoom.list_setting_templates"] = { method = "GET", url = "https://api.zoom.us/v2/phone/setting_templates", query = {"page_size", "next_page_token", "site_id"} },
    ["zoom.list_shared_line_groups"] = { method = "GET", url = "https://api.zoom.us/v2/phone/shared_line_groups", query = {"page_size", "next_page_token"} },
    ["zoom.list_sip_phones"] = { method = "GET", url = "https://api.zoom.us/v2/sip_phones", query = {"page_number", "search_key", "page_size", "next_page_token"} },
    ["zoom.list_sip_trunk_numbers"] = { method = "GET", url = "https://api.zoom.us/v2/sip_trunk/numbers" },
    ["zoom.list_siptrunks"] = { method = "GET", url = "https://api.zoom.us/v2/accounts/{accountId}/sip_trunk/trunks", path = {"accountId", "accountId"} },
    ["zoom.list_webinar_participants"] = { method = "GET", url = "https://api.zoom.us/v2/past_webinars/{webinarId}/participants", path = {"webinarId", "webinarId"}, query = {"page_size", "next_page_token"} },
    ["zoom.list_webinar_templates"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/webinar_templates", path = {"userId"} },
    ["zoom.list_zoom_rooms"] = { method = "GET", url = "https://api.zoom.us/v2/rooms", query = {"status", "type", "unassigned_rooms", "page_size", "next_page_token", "location_id"} },
    ["zoom.list_zrdevices"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/{roomId}/devices", path = {"roomId", "roomId"} },
    ["zoom.list_zrlocations"] = { method = "GET", url = "https://api.zoom.us/v2/rooms/locations", query = {"parent_location_id", "type", "page_size", "next_page_token"} },
    ["zoom.manage_e911signage"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/events" },
    ["zoom.meeting"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}", path = {"meetingId"}, query = {"occurrence_id", "show_previous_occurrences"} },
    ["zoom.meeting_create"] = { method = "POST", url = "https://api.zoom.us/v2/users/{userId}/meetings", path = {"userId"}, body = {"agenda", "duration", "password", "recurrence", "schedule_for", "settings", "start_time", "template_id", "timezone", "topic", "tracking_fields", "type"} },
    ["zoom.meeting_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/meetings/{meetingId}", path = {"meetingId"}, query = {"occurrence_id", "schedule_for_reminder", "cancel_meeting_reminder"} },
    ["zoom.meeting_invitation"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/invitation", path = {"meetingId"} },
    ["zoom.meeting_live_stream_status_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/meetings/{meetingId}/livestream/status", path = {"meetingId"}, body = {"action", "settings"} },
    ["zoom.meeting_live_stream_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/meetings/{meetingId}/livestream", path = {"meetingId", "meetingId"}, body = {"page_url", "stream_key", "stream_url"} },
    ["zoom.meeting_poll_create"] = { method = "POST", url = "https://api.zoom.us/v2/meetings/{meetingId}/polls", path = {"meetingId"}, body = {"questions", "title"} },
    ["zoom.meeting_poll_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/meetings/{meetingId}/polls/{pollId}", path = {"meetingId", "pollId"} },
    ["zoom.meeting_poll_get"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/polls/{pollId}", path = {"meetingId", "pollId"} },
    ["zoom.meeting_poll_update"] = { method = "PUT", url = "https://api.zoom.us/v2/meetings/{meetingId}/polls/{pollId}", path = {"meetingId", "pollId"}, body = {"questions", "title"} },
    ["zoom.meeting_polls"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/polls", path = {"meetingId"} },
    ["zoom.meeting_recording_registrant_create"] = { method = "POST", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/registrants", path = {"meetingId"}, body = {"address", "city", "comments", "country", "custom_questions", "email", "first_name", "industry", "job_title", "last_name", "no_of_employees", "org", "phone", "purchasing_time_frame", "role_in_purchase_process", "state", "zip"} },
    ["zoom.meeting_recording_registrant_status"] = { method = "PUT", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/registrants/status", path = {"meetingId"}, body = {"action", "registrants"} },
    ["zoom.meeting_recording_registrants"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/registrants", path = {"meetingId"}, query = {"status", "page_size", "page_number", "next_page_token"} },
    ["zoom.meeting_registrant_create"] = { method = "POST", url = "https://api.zoom.us/v2/meetings/{meetingId}/registrants", path = {"meetingId"}, query = {"occurrence_ids"}, body = {"address", "city", "comments", "country", "custom_questions", "email", "first_name", "industry", "job_title", "last_name", "no_of_employees", "org", "phone", "purchasing_time_frame", "role_in_purchase_process", "state", "zip"} },
    ["zoom.meeting_registrant_question_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/meetings/{meetingId}/registrants/questions", path = {"meetingId"}, body = {"custom_questions", "questions"} },
    ["zoom.meeting_registrant_status"] = { method = "PUT", url = "https://api.zoom.us/v2/meetings/{meetingId}/registrants/status", path = {"meetingId"}, query = {"occurrence_id"}, body = {"action", "registrants"} },
    ["zoom.meeting_registrants"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/registrants", path = {"meetingId"}, query = {"occurrence_id", "status", "page_size", "page_number", "next_page_token"} },
    ["zoom.meeting_registrants_questions_get"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/registrants/questions", path = {"meetingId"} },
    ["zoom.meeting_status"] = { method = "PUT", url = "https://api.zoom.us/v2/meetings/{meetingId}/status", path = {"meetingId"}, body = {"action"} },
    ["zoom.meeting_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/meetings/{meetingId}", path = {"meetingId"}, query = {"occurrence_id"}, body = {"schedule_for"} },
    ["zoom.meetingregistrantdelete"] = { method = "DELETE", url = "https://api.zoom.us/v2/meetings/{meetingId}/registrants/{registrantId}", path = {"meetingId", "registrantId"}, query = {"occurrence_id"} },
    ["zoom.meetings"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/meetings", path = {"userId"}, query = {"type", "page_size", "next_page_token", "page_number"} },
    ["zoom.participant_feedback"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/meetings/{meetingId}/participants/satisfaction", path = {"meetingId", "meetingId"}, query = {"type", "next_page_token", "page_size"} },
    ["zoom.participant_webinar_feedback"] = { method = "GET", url = "https://api.zoom.us/v2/metrics/webinars/{webinarId}/participants/satisfaction", path = {"webinarId"}, query = {"type", "page_size", "next_page_token"} },
    ["zoom.past_meeting_details"] = { method = "GET", url = "https://api.zoom.us/v2/past_meetings/{meetingUUID}", path = {"meetingUUID"} },
    ["zoom.past_meeting_participants"] = { method = "GET", url = "https://api.zoom.us/v2/past_meetings/{meetingUUID}/participants", path = {"meetingUUID"}, query = {"page_size", "next_page_token"} },
    ["zoom.past_meetings"] = { method = "GET", url = "https://api.zoom.us/v2/past_meetings/{meetingId}/instances", path = {"meetingId"} },
    ["zoom.past_webinars"] = { method = "GET", url = "https://api.zoom.us/v2/past_webinars/{webinarId}/instances", path = {"webinarId"} },
    ["zoom.phone_user"] = { method = "GET", url = "https://api.zoom.us/v2/phone/users/{userId}", path = {"userId", "userId"} },
    ["zoom.phone_user_call_logs"] = { method = "GET", url = "https://api.zoom.us/v2/phone/users/{userId}/call_logs", path = {"userId"}, query = {"page_size", "from", "to", "type", "next_page_token", "phone_number", "time_type"} },
    ["zoom.phone_user_recordings"] = { method = "GET", url = "https://api.zoom.us/v2/phone/users/{userId}/recordings", path = {"userId"}, query = {"page_size", "next_page_token", "from", "to"} },
    ["zoom.phone_user_settings"] = { method = "GET", url = "https://api.zoom.us/v2/phone/users/{userId}/settings", path = {"userId"} },
    ["zoom.phone_user_voice_mails"] = { method = "GET", url = "https://api.zoom.us/v2/phone/users/{userId}/voice_mails", path = {"userId"}, query = {"page_size", "status", "next_page_token", "from", "to"} },
    ["zoom.post_phone_siptrunk"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/phone/sip_trunk/trunks", path = {"accountId"}, body = {"sip_trunks"} },
    ["zoom.recording_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings", path = {"meetingId"}, query = {"action"} },
    ["zoom.recording_delete_one"] = { method = "DELETE", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/{recordingId}", path = {"meetingId", "recordingId"}, query = {"action"} },
    ["zoom.recording_get"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings", path = {"meetingId"}, query = {"include_fields", "ttl"} },
    ["zoom.recording_registrant_question_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/registrants/questions", path = {"meetingId"}, body = {"custom_questions", "questions"} },
    ["zoom.recording_registrants_questions_get"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/registrants/questions", path = {"meetingId"} },
    ["zoom.recording_setting_update"] = { method = "GET", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/settings", path = {"meetingId"} },
    ["zoom.recording_settings_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/settings", path = {"meetingId"}, body = {"approval_type", "authentication_domains", "authentication_option", "on_demand", "password", "recording_authentication", "send_email_to_host", "share_recording", "show_social_share_buttons", "topic", "viewer_download"} },
    ["zoom.recording_status_update"] = { method = "PUT", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/status", path = {"meetingId"} },
    ["zoom.recording_status_update_one"] = { method = "PUT", url = "https://api.zoom.us/v2/meetings/{meetingId}/recordings/{recordingId}/status", path = {"meetingId", "recordingId"} },
    ["zoom.recordings_list"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/recordings", path = {"userId"}, query = {"page_size", "next_page_token", "mc", "trash", "from", "to", "trash_type"} },
    ["zoom.remove_achannel_member"] = { method = "DELETE", url = "https://api.zoom.us/v2/chat/users/{userId}/channels/{channelId}/members/{memberId}", path = {"userId", "channelId", "memberId", "channelId", "memberId", "userId"} },
    ["zoom.remove_auser_level_channel_member"] = { method = "DELETE", url = "https://api.zoom.us/v2/chat/channels/{channelId}/members/{memberId}", path = {"channelId", "memberId", "channelId", "memberId"} },
    ["zoom.report_cloud_recording"] = { method = "GET", url = "https://api.zoom.us/v2/report/cloud_recording", query = {"from", "to"} },
    ["zoom.report_daily"] = { method = "GET", url = "https://api.zoom.us/v2/report/daily", query = {"year", "month"} },
    ["zoom.report_meeting_details"] = { method = "GET", url = "https://api.zoom.us/v2/report/meetings/{meetingId}", path = {"meetingId"} },
    ["zoom.report_meeting_participants"] = { method = "GET", url = "https://api.zoom.us/v2/report/meetings/{meetingId}/participants", path = {"meetingId"}, query = {"page_size", "next_page_token", "include_fields"} },
    ["zoom.report_meeting_polls"] = { method = "GET", url = "https://api.zoom.us/v2/report/meetings/{meetingId}/polls", path = {"meetingId"} },
    ["zoom.report_meetings"] = { method = "GET", url = "https://api.zoom.us/v2/report/users/{userId}/meetings", path = {"userId"}, query = {"from", "to", "page_size", "next_page_token", "type"} },
    ["zoom.report_operation_logs"] = { method = "GET", url = "https://api.zoom.us/v2/report/operationlogs", query = {"from", "to", "page_size", "next_page_token", "category_type"} },
    ["zoom.report_sign_in_sign_out_activities"] = { method = "GET", url = "https://api.zoom.us/v2/report/activities", query = {"from", "to", "page_size", "next_page_token"} },
    ["zoom.report_telephone"] = { method = "GET", url = "https://api.zoom.us/v2/report/telephone", query = {"type", "from", "to", "page_size", "page_number", "next_page_token"} },
    ["zoom.report_users"] = { method = "GET", url = "https://api.zoom.us/v2/report/users", query = {"type", "from", "to", "page_size", "page_number", "next_page_token"} },
    ["zoom.report_webinar_details"] = { method = "GET", url = "https://api.zoom.us/v2/report/webinars/{webinarId}", path = {"webinarId"} },
    ["zoom.report_webinar_participants"] = { method = "GET", url = "https://api.zoom.us/v2/report/webinars/{webinarId}/participants", path = {"webinarId"}, query = {"page_size", "next_page_token", "include_fields"} },
    ["zoom.report_webinar_polls"] = { method = "GET", url = "https://api.zoom.us/v2/report/webinars/{webinarId}/polls", path = {"webinarId"} },
    ["zoom.report_webinar_qa"] = { method = "GET", url = "https://api.zoom.us/v2/report/webinars/{webinarId}/qa", path = {"webinarId"} },
    ["zoom.role_member_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/roles/{roleId}/members/{memberId}", path = {"roleId", "memberId"} },
    ["zoom.role_members"] = { method = "GET", url = "https://api.zoom.us/v2/roles/{roleId}/members", path = {"roleId"}, query = {"page_count", "page_number", "next_page_token", "page_size"} },
    ["zoom.roles"] = { method = "GET", url = "https://api.zoom.us/v2/roles" },
    ["zoom.search_company_contacts"] = { method = "GET", url = "https://api.zoom.us/v2/contacts", query = {"search_key", "query_presence_status", "page_size", "next_page_token"} },
    ["zoom.senda_chat_message"] = { method = "POST", url = "https://api.zoom.us/v2/chat/users/{userId}/messages", path = {"userId"}, body = {"at_items", "message", "to_channel", "to_contact"} },
    ["zoom.sendchatbot"] = { method = "POST", url = "https://api.zoom.us/v2/im/chat/messages", body = {"account_id", "content", "is_markdown_support", "robot_jid", "to_jid", "user_jid", "visible_to_user"} },
    ["zoom.set_up_account"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/phone/setup", path = {"accountId"}, body = {"emergency_address", "extension_number"} },
    ["zoom.switch_user_account"] = { method = "PUT", url = "https://api.zoom.us/v2/accounts/{accountId}/users/{userId}/account", path = {"accountId", "userId", "accountId"}, body = {"account_id"} },
    ["zoom.trackingfield_create"] = { method = "POST", url = "https://api.zoom.us/v2/tracking_fields", body = {"field", "recommended_values", "required", "visible"} },
    ["zoom.trackingfield_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/tracking_fields/{fieldId}", path = {"fieldId"} },
    ["zoom.trackingfield_get"] = { method = "GET", url = "https://api.zoom.us/v2/tracking_fields/{fieldId}", path = {"fieldId"} },
    ["zoom.trackingfield_list"] = { method = "GET", url = "https://api.zoom.us/v2/tracking_fields" },
    ["zoom.trackingfield_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/tracking_fields/{fieldId}", path = {"fieldId"}, body = {"field", "recommended_values", "required", "visible"} },
    ["zoom.tsp"] = { method = "GET", url = "https://api.zoom.us/v2/tsp" },
    ["zoom.tsp_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/tsp", body = {"dial_in_number_unrestricted", "enable", "master_account_setting_extended", "modify_credential_forbidden", "tsp_bridge", "tsp_enabled", "tsp_provider"} },
    ["zoom.tsp_url_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/users/{userId}/tsp/settings", path = {"userId"}, body = {"audio_url"} },
    ["zoom.un_assign_phone_num_call_queue"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}/phone_numbers/{phoneNumberId}", path = {"callQueueId", "phoneNumberId", "callQueueId", "phoneNumberId"} },
    ["zoom.unassign_all_members"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}/members", path = {"callQueueId", "callQueueId"} },
    ["zoom.unassign_all_phone_nums_auto_receptionist"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/auto_receptionists/{autoReceptionistId}/phone_numbers", path = {"autoReceptionistId"} },
    ["zoom.unassign_aphone_num_auto_receptionist"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/auto_receptionists/{autoReceptionistId}/phone_numbers/{phoneNumberId}", path = {"autoReceptionistId", "phoneNumberId", "autoReceptionistId", "phoneNumberId"} },
    ["zoom.unassign_aphone_num_call_queue"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}/phone_numbers", path = {"callQueueId", "callQueueId"} },
    ["zoom.unassign_calling_plan"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/users/{userId}/calling_plans/{type}", path = {"userId", "type", "type"} },
    ["zoom.unassign_member_from_call_queue"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}/members/{memberId}", path = {"callQueueId", "memberId", "callQueueId", "memberId"} },
    ["zoom.unassign_phone_number"] = { method = "DELETE", url = "https://api.zoom.us/v2/phone/users/{userId}/phone_numbers/{phoneNumberId}", path = {"userId", "phoneNumberId", "userId", "phoneNumberId"} },
    ["zoom.update_account_lock_settings"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/lock_settings", path = {"accountId", "accountId"} },
    ["zoom.update_account_owner"] = { method = "PUT", url = "https://api.zoom.us/v2/accounts/{accountId}/owner", path = {"accountId", "accountId"}, body = {"email"} },
    ["zoom.update_adevice"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/devices/{deviceId}", path = {"deviceId", "deviceId"}, body = {"assigned_to", "display_name", "mac_address"} },
    ["zoom.update_agroup_member"] = { method = "PATCH", url = "https://api.zoom.us/v2/groups/{groupId}/members/{memberId}", path = {"groupId", "memberId", "groupId", "memberId"}, body = {"action", "target_group_id"} },
    ["zoom.update_ashared_line_group"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/shared_line_groups/{sharedLineGroupId}", path = {"sharedLineGroupId", "sharedLineGroupId"}, body = {"display_name", "extension_number", "primary_number", "status", "timezone"} },
    ["zoom.update_auto_receptionist"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/auto_receptionists/{autoReceptionistId}", path = {"autoReceptionistId", "autoReceptionistId"}, body = {"extension_number", "name"} },
    ["zoom.update_blocked_list"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/blocked_list/{blockedListId}", path = {"blockedListId", "blockedListId"}, body = {"block_type", "comment", "match_type", "phone_number", "status"} },
    ["zoom.update_call_queue"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/call_queues/{callQueueId}", path = {"callQueueId", "callQueueId"}, body = {"description", "extension_number", "name", "site_id", "status", "timezone"} },
    ["zoom.update_channel"] = { method = "PATCH", url = "https://api.zoom.us/v2/chat/users/{userId}/channels/{channelId}", path = {"userId", "channelId", "channelId", "userId"} },
    ["zoom.update_common_area_phone"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/common_area_phones/{commonAreaPhoneId}", path = {"commonAreaPhoneId"}, body = {"display_name", "extension_number", "mac_address", "site_id"} },
    ["zoom.update_group_settings"] = { method = "PATCH", url = "https://api.zoom.us/v2/groups/{groupId}/settings", path = {"groupId", "groupId"}, query = {"custom_query_fields", "option"} },
    ["zoom.update_phone_number_details"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/numbers/{numberId}", path = {"numberId", "numberId"}, body = {"capability", "display_name"} },
    ["zoom.update_phone_settings"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/phone/settings", path = {"accountId", "accountId"}, body = {"byoc"} },
    ["zoom.update_phone_siptrunk"] = { method = "PATCH", url = "https://api.zoom.us/v2/accounts/{accountId}/phone/sip_trunk/trunks/{sipTrunkId}", path = {"sipTrunkId", "accountId"}, body = {"carrier_account", "name"} },
    ["zoom.update_presence_status"] = { method = "PUT", url = "https://api.zoom.us/v2/users/{userId}/presence_status", path = {"userId"}, body = {"duration", "status"} },
    ["zoom.update_role"] = { method = "PATCH", url = "https://api.zoom.us/v2/roles/{roleId}", path = {"roleId", "roleId"}, body = {"description", "id", "name", "privileges", "sub_account_privileges", "total_members"} },
    ["zoom.update_room_profile"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/{roomId}", path = {"roomId", "roomId"}, body = {"basic"} },
    ["zoom.update_setting_template"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/setting_templates/{templateId}", path = {"templateId", "templateId"}, body = {"description", "name", "policy", "profile", "user_settings"} },
    ["zoom.update_sipphone"] = { method = "PATCH", url = "https://api.zoom.us/v2/sip_phones/{phoneId}", path = {"phoneId", "phoneId"}, body = {"authorization_name", "domain", "password", "proxy_server", "proxy_server2", "proxy_server3", "register_server", "register_server2", "register_server3", "registration_expire_time", "transport_protocol", "transport_protocol2", "transport_protocol3", "user_name", "voice_mail"} },
    ["zoom.update_site_details"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/sites/{siteId}", path = {"siteId", "siteId"}, body = {"name", "site_code"} },
    ["zoom.update_user_level_channel"] = { method = "PATCH", url = "https://api.zoom.us/v2/chat/channels/{channelId}", path = {"channelId", "channelId"} },
    ["zoom.update_user_profile"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/users/{userId}", path = {"userId"}, body = {"extension_number", "site_id"} },
    ["zoom.update_user_setting"] = { method = "PATCH", url = "https://api.zoom.us/v2/phone/users/{userId}/settings/{settingType}", path = {"settingType", "userId"}, body = {"voice_mail"} },
    ["zoom.update_zoom_room_acc_settings"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/account_settings", query = {"setting_type"} },
    ["zoom.update_zoom_rooms_location_structure"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/locations/structure", body = {"structures"} },
    ["zoom.update_zracc_profile"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/account_profile", body = {"basic"} },
    ["zoom.update_zrlocation_profile"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/locations/{locationId}", path = {"locationId", "locationId"}, body = {"basic"} },
    ["zoom.update_zrlocation_settings"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/locations/{locationId}/settings", path = {"locationId", "locationId"}, query = {"setting_type"} },
    ["zoom.update_zrsettings"] = { method = "PATCH", url = "https://api.zoom.us/v2/rooms/{roomId}/settings", path = {"roomId", "roomId"}, query = {"setting_type"} },
    ["zoom.upload_group_vb"] = { method = "POST", url = "https://api.zoom.us/v2/groups/{groupId}/settings/virtual_backgrounds", path = {"groupId", "groupId"}, query = {"file_ids"} },
    ["zoom.upload_vb"] = { method = "POST", url = "https://api.zoom.us/v2/accounts/{accountId}/settings/virtual_backgrounds", path = {"accountId", "accountId"} },
    ["zoom.upload_vbuser"] = { method = "POST", url = "https://api.zoom.us/v2/users/{userId}/settings/virtual_backgrounds", path = {"userId", "userId"} },
    ["zoom.user"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}", path = {"userId"}, query = {"login_type"} },
    ["zoom.user_assistant_create"] = { method = "POST", url = "https://api.zoom.us/v2/users/{userId}/assistants", path = {"userId"}, body = {"assistants"} },
    ["zoom.user_assistant_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/users/{userId}/assistants/{assistantId}", path = {"userId", "assistantId"} },
    ["zoom.user_assistants"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/assistants", path = {"userId"} },
    ["zoom.user_assistants_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/users/{userId}/assistants", path = {"userId"} },
    ["zoom.user_create"] = { method = "POST", url = "https://api.zoom.us/v2/users", body = {"action", "user_info"} },
    ["zoom.user_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/users/{userId}", path = {"userId"}, query = {"action", "transfer_email", "transfer_meeting", "transfer_webinar", "transfer_recording"} },
    ["zoom.user_email"] = { method = "GET", url = "https://api.zoom.us/v2/users/email", query = {"email"} },
    ["zoom.user_email_update"] = { method = "PUT", url = "https://api.zoom.us/v2/users/{userId}/email", path = {"userId"}, body = {"email"} },
    ["zoom.user_pacs"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/pac", path = {"userId"} },
    ["zoom.user_password"] = { method = "PUT", url = "https://api.zoom.us/v2/users/{userId}/password", path = {"userId"}, body = {"password"} },
    ["zoom.user_permission"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/permissions", path = {"userId"} },
    ["zoom.user_picture"] = { method = "POST", url = "https://api.zoom.us/v2/users/{userId}/picture", path = {"userId"}, body = {"pic_file"} },
    ["zoom.user_scheduler_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/users/{userId}/schedulers/{schedulerId}", path = {"userId", "schedulerId"} },
    ["zoom.user_schedulers"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/schedulers", path = {"userId"} },
    ["zoom.user_schedulers_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/users/{userId}/schedulers", path = {"userId"} },
    ["zoom.user_settings"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/settings", path = {"userId"}, query = {"login_type", "option", "custom_query_fields"} },
    ["zoom.user_settings_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/users/{userId}/settings", path = {"userId"}, query = {"option"} },
    ["zoom.user_ssotoken_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/users/{userId}/token", path = {"userId"} },
    ["zoom.user_status"] = { method = "PUT", url = "https://api.zoom.us/v2/users/{userId}/status", path = {"userId"}, body = {"action"} },
    ["zoom.user_token"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/token", path = {"userId"}, query = {"type", "ttl"} },
    ["zoom.user_tsp"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/tsp/{tspId}", path = {"userId", "tspId"} },
    ["zoom.user_tspcreate"] = { method = "POST", url = "https://api.zoom.us/v2/users/{userId}/tsp", path = {"userId"}, body = {"conference_code", "dial_in_numbers", "leader_pin", "tsp_bridge"} },
    ["zoom.user_tspdelete"] = { method = "DELETE", url = "https://api.zoom.us/v2/users/{userId}/tsp/{tspId}", path = {"userId", "tspId"} },
    ["zoom.user_tsps"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/tsp", path = {"userId"} },
    ["zoom.user_tspupdate"] = { method = "PATCH", url = "https://api.zoom.us/v2/users/{userId}/tsp/{tspId}", path = {"userId", "tspId"}, body = {"conference_code", "dial_in_numbers", "leader_pin", "tsp_bridge"} },
    ["zoom.user_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/users/{userId}", path = {"userId"}, query = {"login_type"}, body = {"cms_user_id", "company", "custom_attributes", "dept", "first_name", "group_id", "host_key", "job_title", "language", "last_name", "location", "manager", "phone_country", "phone_number", "phone_numbers", "pmi", "timezone", "type", "use_pmi", "vanity_name"} },
    ["zoom.user_vanity_name"] = { method = "GET", url = "https://api.zoom.us/v2/users/vanity_name", query = {"vanity_name"} },
    ["zoom.user_zak"] = { method = "GET", url = "https://api.zoom.us/v2/users/me/zak" },
    ["zoom.users"] = { method = "GET", url = "https://api.zoom.us/v2/users", query = {"status", "page_size", "role_id", "page_number", "include_fields", "next_page_token"} },
    ["zoom.webinar"] = { method = "GET", url = "https://api.zoom.us/v2/webinars/{webinarId}", path = {"webinarId"}, query = {"occurrence_id", "show_previous_occurrences"} },
    ["zoom.webinar_absentees"] = { method = "GET", url = "https://api.zoom.us/v2/past_webinars/{WebinarUUID}/absentees", path = {"WebinarUUID"}, query = {"occurrence_id", "page_size", "next_page_token"} },
    ["zoom.webinar_create"] = { method = "POST", url = "https://api.zoom.us/v2/users/{userId}/webinars", path = {"userId"}, body = {"agenda", "duration", "password", "recurrence", "settings", "start_time", "timezone", "topic", "tracking_fields", "type"} },
    ["zoom.webinar_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/webinars/{webinarId}", path = {"webinarId"}, query = {"occurrence_id", "cancel_webinar_reminder"} },
    ["zoom.webinar_panelist_create"] = { method = "POST", url = "https://api.zoom.us/v2/webinars/{webinarId}/panelists", path = {"webinarId"}, body = {"panelists"} },
    ["zoom.webinar_panelist_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/webinars/{webinarId}/panelists/{panelistId}", path = {"webinarId", "panelistId"} },
    ["zoom.webinar_panelists"] = { method = "GET", url = "https://api.zoom.us/v2/webinars/{webinarId}/panelists", path = {"webinarId"} },
    ["zoom.webinar_panelists_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/webinars/{webinarId}/panelists", path = {"webinarId"} },
    ["zoom.webinar_poll_create"] = { method = "POST", url = "https://api.zoom.us/v2/webinars/{webinarId}/polls", path = {"webinarId"}, body = {"questions", "title"} },
    ["zoom.webinar_poll_delete"] = { method = "DELETE", url = "https://api.zoom.us/v2/webinars/{webinarId}/polls/{pollId}", path = {"webinarId", "pollId"} },
    ["zoom.webinar_poll_get"] = { method = "GET", url = "https://api.zoom.us/v2/webinars/{webinarId}/polls/{pollId}", path = {"webinarId", "pollId"} },
    ["zoom.webinar_poll_update"] = { method = "PUT", url = "https://api.zoom.us/v2/webinars/{webinarId}/polls/{pollId}", path = {"webinarId", "pollId"}, body = {"questions", "title"} },
    ["zoom.webinar_polls"] = { method = "GET", url = "https://api.zoom.us/v2/webinars/{webinarId}/polls", path = {"webinarId"} },
    ["zoom.webinar_registrant_create"] = { method = "POST", url = "https://api.zoom.us/v2/webinars/{webinarId}/registrants", path = {"webinarId", "webinarId"}, query = {"occurrence_ids"}, body = {"address", "city", "comments", "country", "custom_questions", "email", "first_name", "industry", "job_title", "last_name", "no_of_employees", "org", "phone", "purchasing_time_frame", "role_in_purchase_process", "state", "zip"} },
    ["zoom.webinar_registrant_get"] = { method = "GET", url = "https://api.zoom.us/v2/webinars/{webinarId}/registrants/{registrantId}", path = {"webinarId", "registrantId", "webinarId", "registrantId"}, query = {"occurrence_id"} },
    ["zoom.webinar_registrant_question_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/webinars/{webinarId}/registrants/questions", path = {"webinarId"}, body = {"custom_questions", "questions"} },
    ["zoom.webinar_registrant_status"] = { method = "PUT", url = "https://api.zoom.us/v2/webinars/{webinarId}/registrants/status", path = {"webinarId"}, query = {"occurrence_id"}, body = {"action", "registrants"} },
    ["zoom.webinar_registrants"] = { method = "GET", url = "https://api.zoom.us/v2/webinars/{webinarId}/registrants", path = {"webinarId", "webinarId"}, query = {"occurrence_id", "status", "tracking_source_id", "page_size", "page_number", "next_page_token"} },
    ["zoom.webinar_registrants_questions_get"] = { method = "GET", url = "https://api.zoom.us/v2/webinars/{webinarId}/registrants/questions", path = {"webinarId"} },
    ["zoom.webinar_status"] = { method = "PUT", url = "https://api.zoom.us/v2/webinars/{webinarId}/status", path = {"webinarId"}, body = {"action"} },
    ["zoom.webinar_update"] = { method = "PATCH", url = "https://api.zoom.us/v2/webinars/{webinarId}", path = {"webinarId"}, query = {"occurrence_id"}, body = {"agenda", "duration", "password", "recurrence", "settings", "start_time", "timezone", "topic", "tracking_fields", "type"} },
    ["zoom.webinars"] = { method = "GET", url = "https://api.zoom.us/v2/users/{userId}/webinars", path = {"userId"}, query = {"page_size", "page_number"} },
  },
}
