-- Affinity — every call this API accepts, as data.
--
-- GENERATED from https://developer.affinity.co/api-reference/openapi.json
-- Published on the vendor's own documentation site (https://developer.affinity.co).
-- 103 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "affinity-v2",
  name = "Affinity",
  base = "https://api.affinity.co",
  docs = "https://nango.dev/docs/integrations/all/affinity-v2",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "AFFINITY_V2_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["affinity-v2.v2_auth_whoami_get"] = { method = "GET", url = "https://api.affinity.co/v2/auth/whoami" },
    ["affinity-v2.v2_calls_get"] = { method = "GET", url = "https://api.affinity.co/v2/calls", query = {"cursor", "limit", "filter"} },
    ["affinity-v2.v2_chat_messages_get"] = { method = "GET", url = "https://api.affinity.co/v2/chat-messages", query = {"cursor", "limit", "filter"} },
    ["affinity-v2.v2_companies_company_id_fields_field_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/{companyId}/fields/{fieldId}", path = {"companyId", "fieldId"} },
    ["affinity-v2.v2_companies_company_id_fields_field_id_post"] = { method = "POST", url = "https://api.affinity.co/v2/companies/{companyId}/fields/{fieldId}", path = {"companyId", "fieldId"}, body = {"value"} },
    ["affinity-v2.v2_companies_company_id_fields_field_id_values_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/{companyId}/fields/{fieldId}/values", path = {"companyId", "fieldId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_companies_company_id_fields_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/{companyId}/fields", path = {"companyId"}, query = {"ids", "types", "cursor", "limit"} },
    ["affinity-v2.v2_companies_company_id_fields_patch"] = { method = "PATCH", url = "https://api.affinity.co/v2/companies/{companyId}/fields", path = {"companyId"} },
    ["affinity-v2.v2_companies_company_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/{companyId}", path = {"companyId"}, query = {"fieldIds", "fieldTypes"} },
    ["affinity-v2.v2_companies_company_id_list_entries_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/{companyId}/list-entries", path = {"companyId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_companies_company_id_lists_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/{companyId}/lists", path = {"companyId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_companies_company_id_notes_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/{companyId}/notes", path = {"companyId"}, query = {"filter", "cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_companies_company_id_relationships_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/{companyId}/relationships", path = {"companyId"}, query = {"filter", "orderBy", "cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_companies_fields_field_id_dropdown_options_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/fields/{fieldId}/dropdown-options", path = {"fieldId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_companies_fields_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies/fields", query = {"cursor", "limit", "filter", "includes"} },
    ["affinity-v2.v2_companies_get"] = { method = "GET", url = "https://api.affinity.co/v2/companies", query = {"cursor", "limit", "ids", "fieldIds", "fieldTypes"} },
    ["affinity-v2.v2_companies_search_post"] = { method = "POST", url = "https://api.affinity.co/v2/companies/search", query = {"fieldIds", "fieldTypes", "cursor", "limit", "totalCount"}, body = {"filters", "sorts", "search"} },
    ["affinity-v2.v2_company_merges_get"] = { method = "GET", url = "https://api.affinity.co/v2/company-merges", query = {"cursor", "limit", "filter"} },
    ["affinity-v2.v2_company_merges_merge_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/company-merges/{mergeId}", path = {"mergeId"} },
    ["affinity-v2.v2_company_merges_post"] = { method = "POST", url = "https://api.affinity.co/v2/company-merges", body = {"primaryCompanyId", "duplicateCompanyId"} },
    ["affinity-v2.v2_duplicates_company_suggestions_get"] = { method = "GET", url = "https://api.affinity.co/v2/duplicates/company-suggestions", query = {"cursor", "limit", "totalCount", "term", "filter", "orderBy"} },
    ["affinity-v2.v2_duplicates_person_suggestions_get"] = { method = "GET", url = "https://api.affinity.co/v2/duplicates/person-suggestions", query = {"cursor", "limit", "totalCount", "term", "filter", "orderBy"} },
    ["affinity-v2.v2_emails_get"] = { method = "GET", url = "https://api.affinity.co/v2/emails", query = {"cursor", "limit", "filter"} },
    ["affinity-v2.v2_feedback_post"] = { method = "POST", url = "https://api.affinity.co/v2/feedback", body = {"type", "subject", "body"} },
    ["affinity-v2.v2_field_value_changes_get"] = { method = "GET", url = "https://api.affinity.co/v2/field-value-changes", query = {"filter", "orderBy", "cursor", "limit"} },
    ["affinity-v2.v2_files_search_post"] = { method = "POST", url = "https://api.affinity.co/v2/files/search" },
    ["affinity-v2.v2_inferred_connections_coworkers_get"] = { method = "GET", url = "https://api.affinity.co/v2/inferred-connections/coworkers", query = {"filter", "cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_inferred_connections_investor_executive_connections_get"] = { method = "GET", url = "https://api.affinity.co/v2/inferred-connections/investor-executive-connections", query = {"filter", "cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_lists_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists", query = {"term", "cursor", "limit"} },
    ["affinity-v2.v2_lists_list_id_fields_field_id_dropdown_options_dropdown_option_id_delete"] = { method = "DELETE", url = "https://api.affinity.co/v2/lists/{listId}/fields/{fieldId}/dropdown-options/{dropdownOptionId}", path = {"listId", "fieldId", "dropdownOptionId"} },
    ["affinity-v2.v2_lists_list_id_fields_field_id_dropdown_options_dropdown_option_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/fields/{fieldId}/dropdown-options/{dropdownOptionId}", path = {"listId", "fieldId", "dropdownOptionId"} },
    ["affinity-v2.v2_lists_list_id_fields_field_id_dropdown_options_dropdown_option_id_post"] = { method = "POST", url = "https://api.affinity.co/v2/lists/{listId}/fields/{fieldId}/dropdown-options/{dropdownOptionId}", path = {"listId", "fieldId", "dropdownOptionId"} },
    ["affinity-v2.v2_lists_list_id_fields_field_id_dropdown_options_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/fields/{fieldId}/dropdown-options", path = {"listId", "fieldId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_lists_list_id_fields_field_id_dropdown_options_post"] = { method = "POST", url = "https://api.affinity.co/v2/lists/{listId}/fields/{fieldId}/dropdown-options", path = {"listId", "fieldId"} },
    ["affinity-v2.v2_lists_list_id_fields_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/fields", path = {"listId"}, query = {"cursor", "limit", "filter", "includes"} },
    ["affinity-v2.v2_lists_list_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}", path = {"listId"} },
    ["affinity-v2.v2_lists_list_id_list_entries_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/list-entries", path = {"listId"}, query = {"cursor", "limit", "fieldIds", "fieldTypes"} },
    ["affinity-v2.v2_lists_list_id_list_entries_list_entry_id_field_value_changes_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/list-entries/{listEntryId}/field-value-changes", path = {"listId", "listEntryId"}, query = {"filter", "cursor", "limit"} },
    ["affinity-v2.v2_lists_list_id_list_entries_list_entry_id_fields_field_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/list-entries/{listEntryId}/fields/{fieldId}", path = {"listId", "listEntryId", "fieldId"} },
    ["affinity-v2.v2_lists_list_id_list_entries_list_entry_id_fields_field_id_post"] = { method = "POST", url = "https://api.affinity.co/v2/lists/{listId}/list-entries/{listEntryId}/fields/{fieldId}", path = {"listId", "listEntryId", "fieldId"}, body = {"value"} },
    ["affinity-v2.v2_lists_list_id_list_entries_list_entry_id_fields_field_id_values_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/list-entries/{listEntryId}/fields/{fieldId}/values", path = {"listId", "listEntryId", "fieldId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_lists_list_id_list_entries_list_entry_id_fields_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/list-entries/{listEntryId}/fields", path = {"listId", "listEntryId"}, query = {"ids", "types", "cursor", "limit"} },
    ["affinity-v2.v2_lists_list_id_list_entries_list_entry_id_fields_patch"] = { method = "PATCH", url = "https://api.affinity.co/v2/lists/{listId}/list-entries/{listEntryId}/fields", path = {"listId", "listEntryId"} },
    ["affinity-v2.v2_lists_list_id_list_entries_list_entry_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/list-entries/{listEntryId}", path = {"listId", "listEntryId"}, query = {"fieldIds", "fieldTypes"} },
    ["affinity-v2.v2_lists_list_id_list_entries_search_post"] = { method = "POST", url = "https://api.affinity.co/v2/lists/{listId}/list-entries/search", path = {"listId"}, query = {"fieldIds", "fieldTypes", "cursor", "limit", "totalCount"}, body = {"filters", "sorts", "search"} },
    ["affinity-v2.v2_lists_list_id_saved_views_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/saved-views", path = {"listId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_lists_list_id_saved_views_view_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/saved-views/{viewId}", path = {"listId", "viewId"} },
    ["affinity-v2.v2_lists_list_id_saved_views_view_id_list_entries_get"] = { method = "GET", url = "https://api.affinity.co/v2/lists/{listId}/saved-views/{viewId}/list-entries", path = {"listId", "viewId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_lists_post"] = { method = "POST", url = "https://api.affinity.co/v2/lists", body = {"name", "type", "isPublic"} },
    ["affinity-v2.v2_meetings_get"] = { method = "GET", url = "https://api.affinity.co/v2/meetings", query = {"cursor", "limit", "filter"} },
    ["affinity-v2.v2_meetings_meeting_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/meetings/{meetingId}", path = {"meetingId"} },
    ["affinity-v2.v2_notes_get"] = { method = "GET", url = "https://api.affinity.co/v2/notes", query = {"totalCount", "cursor", "limit", "filter", "includes"} },
    ["affinity-v2.v2_notes_note_id_attached_companies_get"] = { method = "GET", url = "https://api.affinity.co/v2/notes/{noteId}/attached-companies", path = {"noteId"}, query = {"totalCount", "cursor", "limit"} },
    ["affinity-v2.v2_notes_note_id_attached_opportunities_get"] = { method = "GET", url = "https://api.affinity.co/v2/notes/{noteId}/attached-opportunities", path = {"noteId"}, query = {"totalCount", "cursor", "limit"} },
    ["affinity-v2.v2_notes_note_id_attached_persons_get"] = { method = "GET", url = "https://api.affinity.co/v2/notes/{noteId}/attached-persons", path = {"noteId"}, query = {"totalCount", "cursor", "limit"} },
    ["affinity-v2.v2_notes_note_id_delete"] = { method = "DELETE", url = "https://api.affinity.co/v2/notes/{noteId}", path = {"noteId"} },
    ["affinity-v2.v2_notes_note_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/notes/{noteId}", path = {"noteId"}, query = {"includes"} },
    ["affinity-v2.v2_notes_note_id_post"] = { method = "POST", url = "https://api.affinity.co/v2/notes/{noteId}", path = {"noteId"}, body = {"content", "persons", "companies", "opportunities"} },
    ["affinity-v2.v2_notes_note_id_replies_get"] = { method = "GET", url = "https://api.affinity.co/v2/notes/{noteId}/replies", path = {"noteId"}, query = {"filter", "cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_notes_post"] = { method = "POST", url = "https://api.affinity.co/v2/notes" },
    ["affinity-v2.v2_notes_search_post"] = { method = "POST", url = "https://api.affinity.co/v2/notes/search" },
    ["affinity-v2.v2_opportunities_get"] = { method = "GET", url = "https://api.affinity.co/v2/opportunities", query = {"cursor", "limit", "ids"} },
    ["affinity-v2.v2_opportunities_opportunity_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/opportunities/{opportunityId}", path = {"opportunityId"} },
    ["affinity-v2.v2_opportunities_opportunity_id_notes_get"] = { method = "GET", url = "https://api.affinity.co/v2/opportunities/{opportunityId}/notes", path = {"opportunityId"}, query = {"filter", "cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_person_merges_get"] = { method = "GET", url = "https://api.affinity.co/v2/person-merges", query = {"cursor", "limit", "filter"} },
    ["affinity-v2.v2_person_merges_merge_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/person-merges/{mergeId}", path = {"mergeId"} },
    ["affinity-v2.v2_person_merges_post"] = { method = "POST", url = "https://api.affinity.co/v2/person-merges", body = {"primaryPersonId", "duplicatePersonId"} },
    ["affinity-v2.v2_persons_fields_field_id_dropdown_options_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/fields/{fieldId}/dropdown-options", path = {"fieldId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_persons_fields_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/fields", query = {"cursor", "limit", "filter", "includes"} },
    ["affinity-v2.v2_persons_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons", query = {"cursor", "limit", "ids", "fieldIds", "fieldTypes"} },
    ["affinity-v2.v2_persons_person_id_delete"] = { method = "DELETE", url = "https://api.affinity.co/v2/persons/{personId}", path = {"personId"} },
    ["affinity-v2.v2_persons_person_id_fields_field_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/{personId}/fields/{fieldId}", path = {"personId", "fieldId"} },
    ["affinity-v2.v2_persons_person_id_fields_field_id_post"] = { method = "POST", url = "https://api.affinity.co/v2/persons/{personId}/fields/{fieldId}", path = {"personId", "fieldId"}, body = {"value"} },
    ["affinity-v2.v2_persons_person_id_fields_field_id_values_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/{personId}/fields/{fieldId}/values", path = {"personId", "fieldId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_persons_person_id_fields_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/{personId}/fields", path = {"personId"}, query = {"ids", "types", "cursor", "limit"} },
    ["affinity-v2.v2_persons_person_id_fields_patch"] = { method = "PATCH", url = "https://api.affinity.co/v2/persons/{personId}/fields", path = {"personId"} },
    ["affinity-v2.v2_persons_person_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/{personId}", path = {"personId"}, query = {"fieldIds", "fieldTypes"} },
    ["affinity-v2.v2_persons_person_id_list_entries_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/{personId}/list-entries", path = {"personId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_persons_person_id_lists_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/{personId}/lists", path = {"personId"}, query = {"cursor", "limit"} },
    ["affinity-v2.v2_persons_person_id_notes_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/{personId}/notes", path = {"personId"}, query = {"filter", "cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_persons_person_id_relationships_get"] = { method = "GET", url = "https://api.affinity.co/v2/persons/{personId}/relationships", path = {"personId"}, query = {"filter", "orderBy", "cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_persons_post"] = { method = "POST", url = "https://api.affinity.co/v2/persons", body = {"firstName", "lastName", "primaryEmailAddress", "emailAddresses", "fields"} },
    ["affinity-v2.v2_persons_search_post"] = { method = "POST", url = "https://api.affinity.co/v2/persons/search", query = {"fieldIds", "fieldTypes", "cursor", "limit", "totalCount"}, body = {"filters", "sorts", "search"} },
    ["affinity-v2.v2_rate_limit_get"] = { method = "GET", url = "https://api.affinity.co/v2/rate-limit" },
    ["affinity-v2.v2_reminders_get"] = { method = "GET", url = "https://api.affinity.co/v2/reminders", query = {"totalCount", "cursor", "limit", "filter"} },
    ["affinity-v2.v2_reminders_post"] = { method = "POST", url = "https://api.affinity.co/v2/reminders" },
    ["affinity-v2.v2_reminders_reminder_id_delete"] = { method = "DELETE", url = "https://api.affinity.co/v2/reminders/{reminderId}", path = {"reminderId"} },
    ["affinity-v2.v2_reminders_reminder_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/reminders/{reminderId}", path = {"reminderId"} },
    ["affinity-v2.v2_semantic_search_post"] = { method = "POST", url = "https://api.affinity.co/v2/semantic-search", body = {"prompt", "limit", "entityType", "listIds"} },
    ["affinity-v2.v2_tasks_company_merges_get"] = { method = "GET", url = "https://api.affinity.co/v2/tasks/company-merges", query = {"cursor", "limit", "filter"} },
    ["affinity-v2.v2_tasks_company_merges_task_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/tasks/company-merges/{taskId}", path = {"taskId"} },
    ["affinity-v2.v2_tasks_person_merges_get"] = { method = "GET", url = "https://api.affinity.co/v2/tasks/person-merges", query = {"cursor", "limit", "filter"} },
    ["affinity-v2.v2_tasks_person_merges_task_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/tasks/person-merges/{taskId}", path = {"taskId"} },
    ["affinity-v2.v2_transcripts_get"] = { method = "GET", url = "https://api.affinity.co/v2/transcripts", query = {"totalCount", "cursor", "limit", "filter"} },
    ["affinity-v2.v2_transcripts_transcript_id_fragments_get"] = { method = "GET", url = "https://api.affinity.co/v2/transcripts/{transcriptId}/fragments", path = {"transcriptId"}, query = {"cursor", "limit", "totalCount"} },
    ["affinity-v2.v2_transcripts_transcript_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/transcripts/{transcriptId}", path = {"transcriptId"} },
    ["affinity-v2.v2_users_get"] = { method = "GET", url = "https://api.affinity.co/v2/users", query = {"cursor", "limit", "term", "filter"} },
    ["affinity-v2.v2_users_user_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/users/{userId}", path = {"userId"} },
    ["affinity-v2.v2_webhooks_get"] = { method = "GET", url = "https://api.affinity.co/v2/webhooks", query = {"totalCount", "cursor", "limit", "filter"} },
    ["affinity-v2.v2_webhooks_post"] = { method = "POST", url = "https://api.affinity.co/v2/webhooks", body = {"url", "subscriptions"} },
    ["affinity-v2.v2_webhooks_webhook_id_delete"] = { method = "DELETE", url = "https://api.affinity.co/v2/webhooks/{webhookId}", path = {"webhookId"} },
    ["affinity-v2.v2_webhooks_webhook_id_get"] = { method = "GET", url = "https://api.affinity.co/v2/webhooks/{webhookId}", path = {"webhookId"} },
    ["affinity-v2.v2_webhooks_webhook_id_post"] = { method = "POST", url = "https://api.affinity.co/v2/webhooks/{webhookId}", path = {"webhookId"}, body = {"url", "subscriptions", "status"} },
  },
}
