-- Spotify — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/spotify.com/1.0.0/openapi.json
-- APIs.guru's mirror, matched on spotify.com. A mirror lags the vendor.
-- 88 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "spotify",
  name = "Spotify",
  base = "https://api.spotify.com",
  docs = "https://nango.dev/docs/integrations/all/spotify",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "SPOTIFY_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["spotify.add_to_queue"] = { method = "POST", url = "https://api.spotify.com/v1/me/player/queue", query = {"uri", "device_id"} },
    ["spotify.add_tracks_to_playlist"] = { method = "POST", url = "https://api.spotify.com/v1/playlists/{playlist_id}/tracks", path = {"playlist_id"}, query = {"position", "uris"}, body = {"position", "uris"} },
    ["spotify.change_playlist_details"] = { method = "PUT", url = "https://api.spotify.com/v1/playlists/{playlist_id}", path = {"playlist_id"}, body = {"collaborative", "description", "name", "public"} },
    ["spotify.check_current_user_follows"] = { method = "GET", url = "https://api.spotify.com/v1/me/following/contains", query = {"type", "ids"} },
    ["spotify.check_if_user_follows_playlist"] = { method = "GET", url = "https://api.spotify.com/v1/playlists/{playlist_id}/followers/contains", path = {"playlist_id"}, query = {"ids"} },
    ["spotify.check_users_saved_albums"] = { method = "GET", url = "https://api.spotify.com/v1/me/albums/contains", query = {"ids"} },
    ["spotify.check_users_saved_audiobooks"] = { method = "GET", url = "https://api.spotify.com/v1/me/audiobooks/contains", query = {"ids"} },
    ["spotify.check_users_saved_episodes"] = { method = "GET", url = "https://api.spotify.com/v1/me/episodes/contains", query = {"ids"} },
    ["spotify.check_users_saved_shows"] = { method = "GET", url = "https://api.spotify.com/v1/me/shows/contains", query = {"ids"} },
    ["spotify.check_users_saved_tracks"] = { method = "GET", url = "https://api.spotify.com/v1/me/tracks/contains", query = {"ids"} },
    ["spotify.create_playlist"] = { method = "POST", url = "https://api.spotify.com/v1/users/{user_id}/playlists", path = {"user_id"}, body = {"collaborative", "description", "name", "public"} },
    ["spotify.follow_artists_users"] = { method = "PUT", url = "https://api.spotify.com/v1/me/following", query = {"type", "ids"}, body = {"ids"} },
    ["spotify.follow_playlist"] = { method = "PUT", url = "https://api.spotify.com/v1/playlists/{playlist_id}/followers", path = {"playlist_id"}, body = {"public"} },
    ["spotify.get_a_categories_playlists"] = { method = "GET", url = "https://api.spotify.com/v1/browse/categories/{category_id}/playlists", path = {"category_id"}, query = {"country", "limit", "offset"} },
    ["spotify.get_a_category"] = { method = "GET", url = "https://api.spotify.com/v1/browse/categories/{category_id}", path = {"category_id"}, query = {"country", "locale"} },
    ["spotify.get_a_chapter"] = { method = "GET", url = "https://api.spotify.com/v1/chapters/{id}", path = {"id"}, query = {"market"} },
    ["spotify.get_a_list_of_current_users_playlists"] = { method = "GET", url = "https://api.spotify.com/v1/me/playlists", query = {"limit", "offset"} },
    ["spotify.get_a_show"] = { method = "GET", url = "https://api.spotify.com/v1/shows/{id}", path = {"id"}, query = {"market"} },
    ["spotify.get_a_shows_episodes"] = { method = "GET", url = "https://api.spotify.com/v1/shows/{id}/episodes", path = {"id"}, query = {"market", "limit", "offset"} },
    ["spotify.get_a_users_available_devices"] = { method = "GET", url = "https://api.spotify.com/v1/me/player/devices" },
    ["spotify.get_an_album"] = { method = "GET", url = "https://api.spotify.com/v1/albums/{id}", path = {"id"}, query = {"market"} },
    ["spotify.get_an_albums_tracks"] = { method = "GET", url = "https://api.spotify.com/v1/albums/{id}/tracks", path = {"id"}, query = {"market", "limit", "offset"} },
    ["spotify.get_an_artist"] = { method = "GET", url = "https://api.spotify.com/v1/artists/{id}", path = {"id"} },
    ["spotify.get_an_artists_albums"] = { method = "GET", url = "https://api.spotify.com/v1/artists/{id}/albums", path = {"id"}, query = {"include_groups", "market", "limit", "offset"} },
    ["spotify.get_an_artists_related_artists"] = { method = "GET", url = "https://api.spotify.com/v1/artists/{id}/related-artists", path = {"id"} },
    ["spotify.get_an_artists_top_tracks"] = { method = "GET", url = "https://api.spotify.com/v1/artists/{id}/top-tracks", path = {"id"}, query = {"market"} },
    ["spotify.get_an_audiobook"] = { method = "GET", url = "https://api.spotify.com/v1/audiobooks/{id}", path = {"id"}, query = {"market"} },
    ["spotify.get_an_episode"] = { method = "GET", url = "https://api.spotify.com/v1/episodes/{id}", path = {"id"}, query = {"market"} },
    ["spotify.get_audio_analysis"] = { method = "GET", url = "https://api.spotify.com/v1/audio-analysis/{id}", path = {"id"} },
    ["spotify.get_audio_features"] = { method = "GET", url = "https://api.spotify.com/v1/audio-features/{id}", path = {"id"} },
    ["spotify.get_audiobook_chapters"] = { method = "GET", url = "https://api.spotify.com/v1/audiobooks/{id}/chapters", path = {"id"}, query = {"market", "limit", "offset"} },
    ["spotify.get_available_markets"] = { method = "GET", url = "https://api.spotify.com/v1/markets" },
    ["spotify.get_categories"] = { method = "GET", url = "https://api.spotify.com/v1/browse/categories", query = {"country", "locale", "limit", "offset"} },
    ["spotify.get_current_users_profile"] = { method = "GET", url = "https://api.spotify.com/v1/me" },
    ["spotify.get_featured_playlists"] = { method = "GET", url = "https://api.spotify.com/v1/browse/featured-playlists", query = {"country", "locale", "timestamp", "limit", "offset"} },
    ["spotify.get_followed"] = { method = "GET", url = "https://api.spotify.com/v1/me/following", query = {"type", "after", "limit"} },
    ["spotify.get_information_about_the_users_current_playback"] = { method = "GET", url = "https://api.spotify.com/v1/me/player", query = {"market", "additional_types"} },
    ["spotify.get_list_users_playlists"] = { method = "GET", url = "https://api.spotify.com/v1/users/{user_id}/playlists", path = {"user_id"}, query = {"limit", "offset"} },
    ["spotify.get_multiple_albums"] = { method = "GET", url = "https://api.spotify.com/v1/albums", query = {"ids", "market"} },
    ["spotify.get_multiple_artists"] = { method = "GET", url = "https://api.spotify.com/v1/artists", query = {"ids"} },
    ["spotify.get_multiple_audiobooks"] = { method = "GET", url = "https://api.spotify.com/v1/audiobooks", query = {"ids", "market"} },
    ["spotify.get_multiple_episodes"] = { method = "GET", url = "https://api.spotify.com/v1/episodes", query = {"ids", "market"} },
    ["spotify.get_multiple_shows"] = { method = "GET", url = "https://api.spotify.com/v1/shows", query = {"market", "ids"} },
    ["spotify.get_new_releases"] = { method = "GET", url = "https://api.spotify.com/v1/browse/new-releases", query = {"country", "limit", "offset"} },
    ["spotify.get_playlist"] = { method = "GET", url = "https://api.spotify.com/v1/playlists/{playlist_id}", path = {"playlist_id"}, query = {"market", "fields", "additional_types"} },
    ["spotify.get_playlist_cover"] = { method = "GET", url = "https://api.spotify.com/v1/playlists/{playlist_id}/images", path = {"playlist_id"} },
    ["spotify.get_playlists_tracks"] = { method = "GET", url = "https://api.spotify.com/v1/playlists/{playlist_id}/tracks", path = {"playlist_id"}, query = {"market", "fields", "limit", "offset", "additional_types"} },
    ["spotify.get_queue"] = { method = "GET", url = "https://api.spotify.com/v1/me/player/queue" },
    ["spotify.get_recently_played"] = { method = "GET", url = "https://api.spotify.com/v1/me/player/recently-played", query = {"limit", "after", "before"} },
    ["spotify.get_recommendation_genres"] = { method = "GET", url = "https://api.spotify.com/v1/recommendations/available-genre-seeds" },
    ["spotify.get_recommendations"] = { method = "GET", url = "https://api.spotify.com/v1/recommendations", query = {"limit", "market", "seed_artists", "seed_genres", "seed_tracks", "min_acousticness", "max_acousticness", "target_acousticness", "min_danceability", "max_danceability", "target_danceability", "min_duration_ms", "max_duration_ms", "target_duration_ms", "min_energy", "max_energy", "target_energy", "min_instrumentalness", "max_instrumentalness", "target_instrumentalness", "min_key", "max_key", "target_key", "min_liveness", "max_liveness", "target_liveness", "min_loudness", "max_loudness", "target_loudness", "min_mode", "max_mode", "target_mode", "min_popularity", "max_popularity", "target_popularity", "min_speechiness", "max_speechiness", "target_speechiness", "min_tempo", "max_tempo", "target_tempo", "min_time_signature", "max_time_signature", "target_time_signature", "min_valence", "max_valence", "target_valence"} },
    ["spotify.get_several_audio_features"] = { method = "GET", url = "https://api.spotify.com/v1/audio-features", query = {"ids"} },
    ["spotify.get_several_chapters"] = { method = "GET", url = "https://api.spotify.com/v1/chapters", query = {"ids", "market"} },
    ["spotify.get_several_tracks"] = { method = "GET", url = "https://api.spotify.com/v1/tracks", query = {"market", "ids"} },
    ["spotify.get_the_users_currently_playing_track"] = { method = "GET", url = "https://api.spotify.com/v1/me/player/currently-playing", query = {"market", "additional_types"} },
    ["spotify.get_track"] = { method = "GET", url = "https://api.spotify.com/v1/tracks/{id}", path = {"id"}, query = {"market"} },
    ["spotify.get_users_profile"] = { method = "GET", url = "https://api.spotify.com/v1/users/{user_id}", path = {"user_id"} },
    ["spotify.get_users_saved_albums"] = { method = "GET", url = "https://api.spotify.com/v1/me/albums", query = {"limit", "offset", "market"} },
    ["spotify.get_users_saved_audiobooks"] = { method = "GET", url = "https://api.spotify.com/v1/me/audiobooks", query = {"limit", "offset"} },
    ["spotify.get_users_saved_episodes"] = { method = "GET", url = "https://api.spotify.com/v1/me/episodes", query = {"market", "limit", "offset"} },
    ["spotify.get_users_saved_shows"] = { method = "GET", url = "https://api.spotify.com/v1/me/shows", query = {"limit", "offset"} },
    ["spotify.get_users_saved_tracks"] = { method = "GET", url = "https://api.spotify.com/v1/me/tracks", query = {"market", "limit", "offset"} },
    ["spotify.get_users_top_artists_and_tracks"] = { method = "GET", url = "https://api.spotify.com/v1/me/top/{type}", path = {"type"}, query = {"time_range", "limit", "offset"} },
    ["spotify.pause_a_users_playback"] = { method = "PUT", url = "https://api.spotify.com/v1/me/player/pause", query = {"device_id"} },
    ["spotify.remove_albums_user"] = { method = "DELETE", url = "https://api.spotify.com/v1/me/albums", query = {"ids"}, body = {"ids"} },
    ["spotify.remove_audiobooks_user"] = { method = "DELETE", url = "https://api.spotify.com/v1/me/audiobooks", query = {"ids"} },
    ["spotify.remove_episodes_user"] = { method = "DELETE", url = "https://api.spotify.com/v1/me/episodes", query = {"ids"}, body = {"ids"} },
    ["spotify.remove_shows_user"] = { method = "DELETE", url = "https://api.spotify.com/v1/me/shows", query = {"ids", "market"} },
    ["spotify.remove_tracks_playlist"] = { method = "DELETE", url = "https://api.spotify.com/v1/playlists/{playlist_id}/tracks", path = {"playlist_id"}, body = {"snapshot_id", "tracks"} },
    ["spotify.remove_tracks_user"] = { method = "DELETE", url = "https://api.spotify.com/v1/me/tracks", query = {"ids"}, body = {"ids"} },
    ["spotify.reorder_or_replace_playlists_tracks"] = { method = "PUT", url = "https://api.spotify.com/v1/playlists/{playlist_id}/tracks", path = {"playlist_id"}, query = {"uris"}, body = {"insert_before", "range_length", "range_start", "snapshot_id", "uris"} },
    ["spotify.save_albums_user"] = { method = "PUT", url = "https://api.spotify.com/v1/me/albums", query = {"ids"}, body = {"ids"} },
    ["spotify.save_audiobooks_user"] = { method = "PUT", url = "https://api.spotify.com/v1/me/audiobooks", query = {"ids"} },
    ["spotify.save_episodes_user"] = { method = "PUT", url = "https://api.spotify.com/v1/me/episodes", query = {"ids"}, body = {"ids"} },
    ["spotify.save_shows_user"] = { method = "PUT", url = "https://api.spotify.com/v1/me/shows", query = {"ids"} },
    ["spotify.save_tracks_user"] = { method = "PUT", url = "https://api.spotify.com/v1/me/tracks", query = {"ids"}, body = {"ids"} },
    ["spotify.search"] = { method = "GET", url = "https://api.spotify.com/v1/search", query = {"q", "type", "market", "limit", "offset", "include_external"} },
    ["spotify.seek_to_position_in_currently_playing_track"] = { method = "PUT", url = "https://api.spotify.com/v1/me/player/seek", query = {"position_ms", "device_id"} },
    ["spotify.set_repeat_mode_on_users_playback"] = { method = "PUT", url = "https://api.spotify.com/v1/me/player/repeat", query = {"state", "device_id"} },
    ["spotify.set_volume_for_users_playback"] = { method = "PUT", url = "https://api.spotify.com/v1/me/player/volume", query = {"volume_percent", "device_id"} },
    ["spotify.skip_users_playback_to_next_track"] = { method = "POST", url = "https://api.spotify.com/v1/me/player/next", query = {"device_id"} },
    ["spotify.skip_users_playback_to_previous_track"] = { method = "POST", url = "https://api.spotify.com/v1/me/player/previous", query = {"device_id"} },
    ["spotify.start_a_users_playback"] = { method = "PUT", url = "https://api.spotify.com/v1/me/player/play", query = {"device_id"}, body = {"context_uri", "offset", "position_ms", "uris"} },
    ["spotify.toggle_shuffle_for_users_playback"] = { method = "PUT", url = "https://api.spotify.com/v1/me/player/shuffle", query = {"state", "device_id"} },
    ["spotify.transfer_a_users_playback"] = { method = "PUT", url = "https://api.spotify.com/v1/me/player", body = {"device_ids", "play"} },
    ["spotify.unfollow_artists_users"] = { method = "DELETE", url = "https://api.spotify.com/v1/me/following", query = {"type", "ids"}, body = {"ids"} },
    ["spotify.unfollow_playlist"] = { method = "DELETE", url = "https://api.spotify.com/v1/playlists/{playlist_id}/followers", path = {"playlist_id"} },
    ["spotify.upload_custom_playlist_cover"] = { method = "PUT", url = "https://api.spotify.com/v1/playlists/{playlist_id}/images", path = {"playlist_id"} },
  },
}
