-- Ordinal — every call this API accepts, as data.
--
-- GENERATED from https://docs.tryordinal.com/api/openapi.json
-- Published on the vendor's own documentation site (https://docs.tryordinal.com).
-- 67 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "ordinal",
  name = "Ordinal",
  base = "https://app.tryordinal.com/api",
  docs = "https://nango.dev/docs/api-integrations/ordinal",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "ORDINAL_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["ordinal.analytics_cpm_get"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/analytics/cpm" },
    ["ordinal.analytics_cpm_update"] = { method = "PUT", url = "https://app.tryordinal.com/api/v1/analytics/cpm", body = {"linkedIn", "x", "instagram", "facebook", "threads"} },
    ["ordinal.analytics_linkedin_followers"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/analytics/linkedin/{profileId}/followers", path = {"profileId"}, query = {"startDate", "endDate"} },
    ["ordinal.analytics_linkedin_posts"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/analytics/linkedin/{profileId}/posts", path = {"profileId"}, query = {"startDate", "endDate"} },
    ["ordinal.analytics_x_followers"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/analytics/x/{profileId}/followers", path = {"profileId"}, query = {"startDate", "endDate"} },
    ["ordinal.analytics_x_posts"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/analytics/x/{profileId}/posts", path = {"profileId"}, query = {"startDate", "endDate"} },
    ["ordinal.approvals_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/approvals", body = {"postId", "approvals"} },
    ["ordinal.approvals_delete"] = { method = "DELETE", url = "https://app.tryordinal.com/api/v1/approvals/{id}", path = {"id"} },
    ["ordinal.approvals_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{postId}/approvals", path = {"postId"} },
    ["ordinal.approvals_list_workspace"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/approvals", query = {"limit", "cursor", "sortBy", "sortOrder", "updatedAtMin", "updatedAtMax", "createdAtMin", "createdAtMax", "statuses", "postIds", "approverIds", "requestedByIds"} },
    ["ordinal.comments_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/posts/{postId}/comments", path = {"postId"}, body = {"message"} },
    ["ordinal.comments_delete"] = { method = "DELETE", url = "https://app.tryordinal.com/api/v1/comments/{commentId}", path = {"commentId"} },
    ["ordinal.comments_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{postId}/comments", path = {"postId"} },
    ["ordinal.engagements_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/posts/{postId}/engagements", path = {"postId"}, body = {"channel", "engagements"} },
    ["ordinal.engagements_delete"] = { method = "DELETE", url = "https://app.tryordinal.com/api/v1/engagements/{id}", path = {"id"} },
    ["ordinal.engagements_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{postId}/engagements", path = {"postId"} },
    ["ordinal.engagements_update"] = { method = "PATCH", url = "https://app.tryordinal.com/api/v1/engagements/{id}", path = {"id"}, body = {"copy", "delaySeconds", "profileId", "reactionType"} },
    ["ordinal.ideas_add_to_calendar"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/ideas/{id}/add-to-calendar", path = {"id"}, body = {"publishDate"} },
    ["ordinal.ideas_archive"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/ideas/{id}/archive", path = {"id"} },
    ["ordinal.ideas_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/ideas", body = {"title", "labelIds", "campaignId", "linkedIn", "x", "tikTok", "youTubeShorts", "notes"} },
    ["ordinal.ideas_get"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/ideas/{id}", path = {"id"} },
    ["ordinal.ideas_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/ideas", query = {"limit", "cursor", "ids", "channel", "linkedInProfileId", "xProfileId", "tikTokProfileId", "youTubeProfileId", "labelIds", "createdAtMin", "createdAtMax", "sortBy", "sortOrder"} },
    ["ordinal.ideas_unarchive"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/ideas/{id}/unarchive", path = {"id"} },
    ["ordinal.ideas_update"] = { method = "PATCH", url = "https://app.tryordinal.com/api/v1/ideas/{id}", path = {"id"}, body = {"title", "labelIds", "campaignId", "linkedIn", "x", "tikTok", "youTubeShorts", "notes"} },
    ["ordinal.inline_comments_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{postId}/inline-comments", path = {"postId"}, query = {"channel", "resolved"} },
    ["ordinal.instagram_search_locations"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/instagram/locations", query = {"query"} },
    ["ordinal.invites_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/invites", body = {"email"} },
    ["ordinal.invites_delete"] = { method = "DELETE", url = "https://app.tryordinal.com/api/v1/invites/{id}", path = {"id"} },
    ["ordinal.invites_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/invites" },
    ["ordinal.labels_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/labels", body = {"name", "color"} },
    ["ordinal.labels_delete"] = { method = "DELETE", url = "https://app.tryordinal.com/api/v1/labels/{id}", path = {"id"} },
    ["ordinal.labels_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/labels" },
    ["ordinal.linkedin_get_mention"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/linkedin/{username}/mentions", path = {"username"} },
    ["ordinal.linkedin_get_profile"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/linkedin/profile/{urn}", path = {"urn"} },
    ["ordinal.linkedin_leads_get_leads_by_post"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/linkedin/leads/{profileId}/posts/{postId}", path = {"profileId", "postId"}, query = {"types", "minFollowerCount", "limit", "cursor"} },
    ["ordinal.linkedin_leads_list_posts"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/linkedin/leads/{profileId}/posts", path = {"profileId"}, query = {"startDate", "endDate", "limit", "cursor"} },
    ["ordinal.posts_archive"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/posts/{id}/archive", path = {"id"} },
    ["ordinal.posts_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/posts", body = {"title", "publishAt", "status", "labelIds", "campaignId", "notes", "linkedIn", "x", "instagram", "tikTok", "youTubeShorts"} },
    ["ordinal.posts_get"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{id}", path = {"id"} },
    ["ordinal.posts_get_version_content"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{id}/channels/{channel}/versions/{versionId}", path = {"id", "channel", "versionId"} },
    ["ordinal.posts_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts", query = {"limit", "cursor", "ids", "status", "channel", "linkedInProfileId", "xProfileId", "instagramProfileId", "tikTokProfileId", "youTubeProfileId", "labelIds", "publishDateMin", "publishDateMax", "createdAtMin", "createdAtMax", "sortBy", "sortOrder"} },
    ["ordinal.posts_list_versions"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{id}/versions", path = {"id"}, query = {"channel", "limit", "cursor"} },
    ["ordinal.posts_schedule"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/posts/{id}/schedule", path = {"id"}, body = {"publishAt"} },
    ["ordinal.posts_unarchive"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/posts/{id}/unarchive", path = {"id"} },
    ["ordinal.posts_unschedule"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/posts/{id}/unschedule", path = {"id"} },
    ["ordinal.posts_update"] = { method = "PATCH", url = "https://app.tryordinal.com/api/v1/posts/{id}", path = {"id"}, body = {"title", "publishAt", "status", "labelIds", "campaignId", "notes", "linkedIn", "x", "instagram", "tikTok", "youTubeShorts"} },
    ["ordinal.profiles_list_engagement"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/profiles/engagement" },
    ["ordinal.profiles_list_scheduling"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/profiles/scheduling" },
    ["ordinal.slack_boosts_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/slack-boosts", body = {"postId", "slackWebhookId", "copy"} },
    ["ordinal.slack_boosts_delete"] = { method = "DELETE", url = "https://app.tryordinal.com/api/v1/slack-boosts/{id}", path = {"id"} },
    ["ordinal.slack_boosts_get"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/slack-boosts/{id}", path = {"id"} },
    ["ordinal.slack_boosts_list_by_post"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{postId}/slack-boosts", path = {"postId"} },
    ["ordinal.slack_boosts_update"] = { method = "PATCH", url = "https://app.tryordinal.com/api/v1/slack-boosts/{id}", path = {"id"}, body = {"copy", "slackWebhookId"} },
    ["ordinal.slack_webhooks_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/slack-webhooks" },
    ["ordinal.subscribers_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/subscribers", body = {"postId", "userIds"} },
    ["ordinal.subscribers_delete"] = { method = "DELETE", url = "https://app.tryordinal.com/api/v1/subscribers/{id}", path = {"id"} },
    ["ordinal.subscribers_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/posts/{postId}/subscribers", path = {"postId"} },
    ["ordinal.uploads_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/uploads", body = {"url"} },
    ["ordinal.uploads_get"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/uploads/{id}", path = {"id"} },
    ["ordinal.uploads_prepare"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/uploads/prepare", body = {"filename", "mimetype", "size"} },
    ["ordinal.users_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/users" },
    ["ordinal.webhooks_create"] = { method = "POST", url = "https://app.tryordinal.com/api/v1/webhooks", body = {"name", "url", "description", "topics", "headers"} },
    ["ordinal.webhooks_delete"] = { method = "DELETE", url = "https://app.tryordinal.com/api/v1/webhooks/{id}", path = {"id"} },
    ["ordinal.webhooks_get"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/webhooks/{id}", path = {"id"} },
    ["ordinal.webhooks_list"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/webhooks" },
    ["ordinal.webhooks_update"] = { method = "PATCH", url = "https://app.tryordinal.com/api/v1/webhooks/{id}", path = {"id"}, body = {"name", "url", "description", "topics", "headers"} },
    ["ordinal.workspace_get"] = { method = "GET", url = "https://app.tryordinal.com/api/v1/workspace" },
  },
}
