-- Salesloft — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/salesloft.com/v2/openapi.json
-- APIs.guru's mirror, matched on salesloft.com. A mirror lags the vendor.
-- 118 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "salesloft",
  name = "Salesloft",
  base = "https://api.salesloft.com",
  docs = "https://nango.dev/docs/integrations/all/salesloft",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "SALESLOFT_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["salesloft.delete_v2_accounts_id_json"] = { method = "DELETE", url = "https://api.salesloft.com/v2/accounts/{id}.json", path = {"id"} },
    ["salesloft.delete_v2_cadence_memberships_id_json"] = { method = "DELETE", url = "https://api.salesloft.com/v2/cadence_memberships/{id}.json", path = {"id"} },
    ["salesloft.delete_v2_custom_fields_id_json"] = { method = "DELETE", url = "https://api.salesloft.com/v2/custom_fields/{id}.json", path = {"id"} },
    ["salesloft.delete_v2_imports_id_json"] = { method = "DELETE", url = "https://api.salesloft.com/v2/imports/{id}.json", path = {"id"}, query = {"undo"} },
    ["salesloft.delete_v2_notes_id_json"] = { method = "DELETE", url = "https://api.salesloft.com/v2/notes/{id}.json", path = {"id"} },
    ["salesloft.delete_v2_people_id_json"] = { method = "DELETE", url = "https://api.salesloft.com/v2/people/{id}.json", path = {"id"} },
    ["salesloft.delete_v2_person_stages_id_json"] = { method = "DELETE", url = "https://api.salesloft.com/v2/person_stages/{id}.json", path = {"id"} },
    ["salesloft.delete_v2_saved_list_views_id_json"] = { method = "DELETE", url = "https://api.salesloft.com/v2/saved_list_views/{id}.json", path = {"id"} },
    ["salesloft.delete_v2_webhook_subscriptions_id"] = { method = "DELETE", url = "https://api.salesloft.com/v2/webhook_subscriptions/{id}", path = {"id"} },
    ["salesloft.get_v2_account_stages_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/account_stages/{id}.json", path = {"id"} },
    ["salesloft.get_v2_account_stages_json"] = { method = "GET", url = "https://api.salesloft.com/v2/account_stages.json", query = {"ids", "updated_at", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_account_tiers_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/account_tiers/{id}.json", path = {"id"} },
    ["salesloft.get_v2_account_tiers_json"] = { method = "GET", url = "https://api.salesloft.com/v2/account_tiers.json", query = {"ids", "name", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_accounts_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/accounts/{id}.json", path = {"id"} },
    ["salesloft.get_v2_accounts_json"] = { method = "GET", url = "https://api.salesloft.com/v2/accounts.json", query = {"ids", "crm_id", "tag", "tag_id", "created_at", "updated_at", "domain", "website", "archived", "name", "account_stage_id", "account_tier_id", "owner_id", "owner_is_active", "last_contacted", "custom_fields", "industry", "country", "state", "city", "owner_crm_id", "locales", "user_relationships", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_action_details_call_instructions_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/action_details/call_instructions/{id}.json", path = {"id"} },
    ["salesloft.get_v2_action_details_call_instructions_json"] = { method = "GET", url = "https://api.salesloft.com/v2/action_details/call_instructions.json", query = {"ids", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_actions_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/actions/{id}.json", path = {"id"} },
    ["salesloft.get_v2_actions_json"] = { method = "GET", url = "https://api.salesloft.com/v2/actions.json", query = {"ids", "step_id", "type", "due_on", "user_guid", "person_id", "cadence_id", "multitouch_group_id", "updated_at", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_activities_calls_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/activities/calls/{id}.json", path = {"id"} },
    ["salesloft.get_v2_activities_calls_json"] = { method = "GET", url = "https://api.salesloft.com/v2/activities/calls.json", query = {"ids", "created_at", "updated_at", "user_guid", "person_id", "sentiment", "disposition", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_activities_emails_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/activities/emails/{id}.json", path = {"id"} },
    ["salesloft.get_v2_activities_emails_json"] = { method = "GET", url = "https://api.salesloft.com/v2/activities/emails.json", query = {"ids", "updated_at", "bounced", "crm_activity_id", "action_id", "user_id", "status", "cadence_id", "step_id", "one_off", "scoped_fields", "person_id", "email_addresses", "personalization", "sent_at", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_activity_histories"] = { method = "GET", url = "https://api.salesloft.com/v2/activity_histories", query = {"per_page", "page", "include_paging_counts", "sort_by", "sort_direction", "type", "_resource", "occurred_at", "pinned", "resource_type", "resource_id", "updated_at", "user_guid"} },
    ["salesloft.get_v2_bulk_jobs"] = { method = "GET", url = "https://api.salesloft.com/v2/bulk_jobs", query = {"state", "id", "per_page"} },
    ["salesloft.get_v2_bulk_jobs_bulk_jobs_id_job_data"] = { method = "GET", url = "https://api.salesloft.com/v2/bulk_jobs/{bulk_jobs_id}/job_data", path = {"bulk_jobs_id"}, query = {"status", "id", "per_page"} },
    ["salesloft.get_v2_bulk_jobs_bulk_jobs_id_results"] = { method = "GET", url = "https://api.salesloft.com/v2/bulk_jobs/{bulk_jobs_id}/results", path = {"bulk_jobs_id"}, query = {"status", "id", "per_page"} },
    ["salesloft.get_v2_bulk_jobs_id"] = { method = "GET", url = "https://api.salesloft.com/v2/bulk_jobs/{id}", path = {"id"} },
    ["salesloft.get_v2_cadence_exports_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/cadence_exports/{id}.json", path = {"id"} },
    ["salesloft.get_v2_cadence_memberships_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/cadence_memberships/{id}.json", path = {"id"} },
    ["salesloft.get_v2_cadence_memberships_json"] = { method = "GET", url = "https://api.salesloft.com/v2/cadence_memberships.json", query = {"ids", "person_id", "cadence_id", "updated_at", "currently_on_cadence", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_cadences_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/cadences/{id}.json", path = {"id"} },
    ["salesloft.get_v2_cadences_json"] = { method = "GET", url = "https://api.salesloft.com/v2/cadences.json", query = {"ids", "updated_at", "team_cadence", "shared", "owned_by_guid", "people_addable", "name", "group_ids", "archived", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_calendar_events"] = { method = "GET", url = "https://api.salesloft.com/v2/calendar/events", query = {"per_page", "page", "include_paging_counts", "sort_by", "sort_direction", "start_time", "end_time", "user_guid"} },
    ["salesloft.get_v2_call_data_records_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/call_data_records/{id}.json", path = {"id"} },
    ["salesloft.get_v2_call_data_records_json"] = { method = "GET", url = "https://api.salesloft.com/v2/call_data_records.json", query = {"ids", "has_call", "created_at", "updated_at", "user_guid", "person_id", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_call_dispositions_json"] = { method = "GET", url = "https://api.salesloft.com/v2/call_dispositions.json", query = {"sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_call_sentiments_json"] = { method = "GET", url = "https://api.salesloft.com/v2/call_sentiments.json", query = {"name", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_crm_activities_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/crm_activities/{id}.json", path = {"id"} },
    ["salesloft.get_v2_crm_activities_json"] = { method = "GET", url = "https://api.salesloft.com/v2/crm_activities.json", query = {"ids", "updated_at", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_crm_activity_fields_json"] = { method = "GET", url = "https://api.salesloft.com/v2/crm_activity_fields.json", query = {"source", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_crm_users_json"] = { method = "GET", url = "https://api.salesloft.com/v2/crm_users.json", query = {"ids", "crm_id", "user_id", "user_guid", "per_page", "page", "include_paging_counts", "limit_paging_counts", "sort_by", "sort_direction"} },
    ["salesloft.get_v2_custom_fields_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/custom_fields/{id}.json", path = {"id"} },
    ["salesloft.get_v2_custom_fields_json"] = { method = "GET", url = "https://api.salesloft.com/v2/custom_fields.json", query = {"ids", "field_type", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_email_template_attachments_json"] = { method = "GET", url = "https://api.salesloft.com/v2/email_template_attachments.json", query = {"ids", "email_template_id", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_email_templates_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/email_templates/{id}.json", path = {"id"}, query = {"include_signature"} },
    ["salesloft.get_v2_email_templates_json"] = { method = "GET", url = "https://api.salesloft.com/v2/email_templates.json", query = {"ids", "updated_at", "linked_to_team_template", "search", "tag_ids", "tag", "filter_by_owner", "group_id", "include_cadence_templates", "include_archived_templates", "cadence_id", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_groups_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/groups/{id}.json", path = {"id"} },
    ["salesloft.get_v2_groups_json"] = { method = "GET", url = "https://api.salesloft.com/v2/groups.json", query = {"ids", "sort_by", "sort_direction"} },
    ["salesloft.get_v2_imports_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/imports/{id}.json", path = {"id"} },
    ["salesloft.get_v2_imports_json"] = { method = "GET", url = "https://api.salesloft.com/v2/imports.json", query = {"ids", "user_ids", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_me_json"] = { method = "GET", url = "https://api.salesloft.com/v2/me.json" },
    ["salesloft.get_v2_meetings_json"] = { method = "GET", url = "https://api.salesloft.com/v2/meetings.json", query = {"ids", "status", "person_id", "account_id", "person_ids", "event_ids", "i_cal_uids", "task_ids", "include_meetings_settings", "start_time", "user_guids", "show_deleted", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_mime_email_payloads_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/mime_email_payloads/{id}.json", path = {"id"} },
    ["salesloft.get_v2_notes_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/notes/{id}.json", path = {"id"} },
    ["salesloft.get_v2_notes_json"] = { method = "GET", url = "https://api.salesloft.com/v2/notes.json", query = {"associated_with_type", "associated_with_id", "updated_at", "ids", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_pending_emails_json"] = { method = "GET", url = "https://api.salesloft.com/v2/pending_emails.json", query = {"per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_people_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/people/{id}.json", path = {"id"} },
    ["salesloft.get_v2_people_json"] = { method = "GET", url = "https://api.salesloft.com/v2/people.json", query = {"ids", "updated_at", "email_addresses", "owned_by_guid", "person_stage_id", "crm_id", "owner_crm_id", "do_not_contact", "can_email", "can_call", "can_text", "account_id", "custom_fields", "import_id", "job_seniority", "tag_id", "owner_is_active", "cadence_id", "starred_by_guid", "replied", "bounced", "success", "eu_resident", "title", "country", "state", "city", "last_contacted", "created_at", "new", "phone_number", "locales", "owner_id", "_query", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_person_stages_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/person_stages/{id}.json", path = {"id"} },
    ["salesloft.get_v2_person_stages_json"] = { method = "GET", url = "https://api.salesloft.com/v2/person_stages.json", query = {"ids", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_phone_number_assignments_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/phone_number_assignments/{id}.json", path = {"id"} },
    ["salesloft.get_v2_phone_number_assignments_json"] = { method = "GET", url = "https://api.salesloft.com/v2/phone_number_assignments.json", query = {"ids", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_phone_numbers_caller_ids_json"] = { method = "GET", url = "https://api.salesloft.com/v2/phone_numbers/caller_ids.json", query = {"phone_number"} },
    ["salesloft.get_v2_phone_numbers_recording_settings_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/phone_numbers/recording_settings/{id}.json", path = {"id"} },
    ["salesloft.get_v2_saved_list_views_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/saved_list_views/{id}.json", path = {"id"} },
    ["salesloft.get_v2_saved_list_views_json"] = { method = "GET", url = "https://api.salesloft.com/v2/saved_list_views.json", query = {"ids", "view", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_steps_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/steps/{id}.json", path = {"id"} },
    ["salesloft.get_v2_steps_json"] = { method = "GET", url = "https://api.salesloft.com/v2/steps.json", query = {"ids", "cadence_id", "type", "has_due_actions", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_successes_json"] = { method = "GET", url = "https://api.salesloft.com/v2/successes.json", query = {"ids", "person_id", "updated_at", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_tags_json"] = { method = "GET", url = "https://api.salesloft.com/v2/tags.json", query = {"search", "ids", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_tasks_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/tasks/{id}.json", path = {"id"} },
    ["salesloft.get_v2_tasks_json"] = { method = "GET", url = "https://api.salesloft.com/v2/tasks.json", query = {"ids", "user_id", "person_id", "account_id", "current_state", "task_type", "time_interval_filter", "idempotency_key", "locale", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_team_json"] = { method = "GET", url = "https://api.salesloft.com/v2/team.json" },
    ["salesloft.get_v2_team_template_attachments_json"] = { method = "GET", url = "https://api.salesloft.com/v2/team_template_attachments.json", query = {"ids", "team_template_id", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_team_templates_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/team_templates/{id}.json", path = {"id"}, query = {"include_signature"} },
    ["salesloft.get_v2_team_templates_json"] = { method = "GET", url = "https://api.salesloft.com/v2/team_templates.json", query = {"ids", "updated_at", "search", "tag_ids", "tag", "include_archived_templates", "sort_by", "sort_direction", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.get_v2_users_id_json"] = { method = "GET", url = "https://api.salesloft.com/v2/users/{id}.json", path = {"id"} },
    ["salesloft.get_v2_users_json"] = { method = "GET", url = "https://api.salesloft.com/v2/users.json", query = {"ids", "guid", "group_id", "role_id", "search", "active", "visible_only", "per_page", "page", "include_paging_counts", "has_crm_user", "work_country", "sort_by", "sort_direction"} },
    ["salesloft.get_v2_webhook_subscriptions"] = { method = "GET", url = "https://api.salesloft.com/v2/webhook_subscriptions", query = {"enabled"} },
    ["salesloft.get_v2_webhook_subscriptions_id"] = { method = "GET", url = "https://api.salesloft.com/v2/webhook_subscriptions/{id}", path = {"id"} },
    ["salesloft.post_v2_account_upserts_json"] = { method = "POST", url = "https://api.salesloft.com/v2/account_upserts.json", body = {"account_tier_id", "city", "company_stage_id", "company_type", "conversational_name", "country", "crm_id", "crm_id_type", "custom_fields", "description", "do_not_contact", "domain", "founded", "id", "industry", "linkedin_url", "locale", "name", "owner_id", "phone", "postal_code", "revenue_range", "size", "state", "street", "tags", "twitter_handle", "upsert_key", "website"} },
    ["salesloft.post_v2_accounts_json"] = { method = "POST", url = "https://api.salesloft.com/v2/accounts.json", body = {"account_tier_id", "city", "company_stage_id", "company_type", "conversational_name", "country", "crm_id", "crm_id_type", "custom_fields", "description", "do_not_contact", "domain", "founded", "industry", "linkedin_url", "locale", "name", "owner_id", "phone", "postal_code", "revenue_range", "size", "state", "street", "tags", "twitter_handle", "website"} },
    ["salesloft.post_v2_activities_calls_json"] = { method = "POST", url = "https://api.salesloft.com/v2/activities/calls.json", body = {"action_id", "crm_params", "disposition", "duration", "linked_call_data_record_ids", "notes", "person_id", "sentiment", "to", "user_guid"} },
    ["salesloft.post_v2_activities_json"] = { method = "POST", url = "https://api.salesloft.com/v2/activities.json", body = {"action_id", "task_id"} },
    ["salesloft.post_v2_bulk_jobs"] = { method = "POST", url = "https://api.salesloft.com/v2/bulk_jobs", body = {"name", "type"} },
    ["salesloft.post_v2_bulk_jobs_bulk_jobs_id_job_data"] = { method = "POST", url = "https://api.salesloft.com/v2/bulk_jobs/{bulk_jobs_id}/job_data", path = {"bulk_jobs_id"}, body = {"data"} },
    ["salesloft.post_v2_cadence_imports_json"] = { method = "POST", url = "https://api.salesloft.com/v2/cadence_imports.json", body = {"cadence_content", "settings", "sharing_settings"} },
    ["salesloft.post_v2_cadence_memberships_json"] = { method = "POST", url = "https://api.salesloft.com/v2/cadence_memberships.json", query = {"person_id", "cadence_id", "user_id", "step_id"} },
    ["salesloft.post_v2_calendar_events_upsert"] = { method = "POST", url = "https://api.salesloft.com/v2/calendar/events/upsert", body = {"all_day", "attendees", "calendar_id", "canceled_at", "description", "end_time", "i_cal_uid", "id", "location", "organizer", "recurring", "start_time", "status", "title"} },
    ["salesloft.post_v2_conversations_calls"] = { method = "POST", url = "https://api.salesloft.com/v2/conversations/calls", body = {"call_created_at", "direction", "duration", "from", "recording", "to", "user_guid"} },
    ["salesloft.post_v2_custom_fields_json"] = { method = "POST", url = "https://api.salesloft.com/v2/custom_fields.json", body = {"field_type", "name"} },
    ["salesloft.post_v2_external_emails_json"] = { method = "POST", url = "https://api.salesloft.com/v2/external_emails.json", body = {"mailbox", "raw"} },
    ["salesloft.post_v2_imports_json"] = { method = "POST", url = "https://api.salesloft.com/v2/imports.json" },
    ["salesloft.post_v2_live_website_tracking_parameters_json"] = { method = "POST", url = "https://api.salesloft.com/v2/live_website_tracking_parameters.json", body = {"person_id"} },
    ["salesloft.post_v2_meetings_settings_searches_json"] = { method = "POST", url = "https://api.salesloft.com/v2/meetings/settings/searches.json", query = {"user_guids", "updated_at", "calendar_type", "per_page", "page", "include_paging_counts", "limit_paging_counts"} },
    ["salesloft.post_v2_notes_json"] = { method = "POST", url = "https://api.salesloft.com/v2/notes.json", body = {"associated_with_id", "associated_with_type", "call_id", "content", "skip_crm_sync", "subject", "user_guid"} },
    ["salesloft.post_v2_ongoing_actions_json"] = { method = "POST", url = "https://api.salesloft.com/v2/ongoing_actions.json", body = {"action_id"} },
    ["salesloft.post_v2_people_json"] = { method = "POST", url = "https://api.salesloft.com/v2/people.json", body = {"account_id", "autotag_date", "city", "contact_restrictions", "country", "crm_id", "crm_id_type", "custom_fields", "do_not_contact", "email_address", "first_name", "home_phone", "import_id", "job_seniority", "last_name", "linkedin_url", "locale", "mobile_phone", "owner_id", "person_company_industry", "person_company_name", "person_company_website", "person_stage_id", "personal_email_address", "personal_website", "phone", "phone_extension", "secondary_email_address", "state", "tags", "title", "twitter_handle", "work_city", "work_country", "work_state"} },
    ["salesloft.post_v2_person_stages_json"] = { method = "POST", url = "https://api.salesloft.com/v2/person_stages.json", body = {"name"} },
    ["salesloft.post_v2_person_upserts_json"] = { method = "POST", url = "https://api.salesloft.com/v2/person_upserts.json", body = {"account_id", "city", "contact_restrictions", "country", "crm_id", "crm_id_type", "custom_fields", "do_not_contact", "email_address", "first_name", "home_phone", "id", "import_id", "job_seniority", "last_name", "linkedin_url", "locale", "mobile_phone", "owner_id", "person_company_industry", "person_company_name", "person_company_website", "person_stage_id", "personal_email_address", "personal_website", "phone", "phone_extension", "secondary_email_address", "state", "tags", "title", "twitter_handle", "upsert_key", "work_city", "work_country", "work_state"} },
    ["salesloft.post_v2_saved_list_views_json"] = { method = "POST", url = "https://api.salesloft.com/v2/saved_list_views.json", body = {"is_default", "name", "view", "view_params"} },
    ["salesloft.post_v2_tasks_json"] = { method = "POST", url = "https://api.salesloft.com/v2/tasks.json", body = {"current_state", "description", "due_date", "idempotency_key", "person_id", "remind_at", "subject", "task_type", "user_id"} },
    ["salesloft.post_v2_third_party_live_feed_items"] = { method = "POST", url = "https://api.salesloft.com/v2/third_party_live_feed_items", body = {"event_occurred_at", "idempotency_key", "message", "subject_id", "subject_type", "user_guid"} },
    ["salesloft.post_v2_webhook_subscriptions"] = { method = "POST", url = "https://api.salesloft.com/v2/webhook_subscriptions", body = {"callback_token", "callback_url", "event_type"} },
    ["salesloft.put_v2_accounts_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/accounts/{id}.json", path = {"id"}, body = {"account_tier_id", "archived", "city", "company_stage_id", "company_type", "conversational_name", "country", "crm_id", "crm_id_type", "custom_fields", "description", "do_not_contact", "domain", "founded", "industry", "linkedin_url", "locale", "name", "owner_id", "phone", "postal_code", "revenue_range", "size", "state", "street", "tags", "twitter_handle", "website"} },
    ["salesloft.put_v2_bulk_jobs_id"] = { method = "PUT", url = "https://api.salesloft.com/v2/bulk_jobs/{id}", path = {"id"}, body = {"name", "ready_to_execute"} },
    ["salesloft.put_v2_custom_fields_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/custom_fields/{id}.json", path = {"id"}, body = {"field_type", "name"} },
    ["salesloft.put_v2_imports_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/imports/{id}.json", path = {"id"} },
    ["salesloft.put_v2_meetings_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/meetings/{id}.json", path = {"id"}, body = {"event_id", "i_cal_uid", "no_show", "status"} },
    ["salesloft.put_v2_meetings_settings_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/meetings/settings/{id}.json", path = {"id"}, body = {"allow_booking_on_behalf", "allow_booking_overtime", "allow_event_overlap", "availability_limit", "availability_limit_enabled", "buffer_time_duration", "calendar_type", "default_meeting_length", "description", "enable_calendar_sync", "enable_dynamic_location", "location", "primary_calendar_connection_failed", "primary_calendar_id", "primary_calendar_name", "schedule_buffer_enabled", "schedule_delay", "share_event_detail", "time_zone", "times_available", "title"} },
    ["salesloft.put_v2_notes_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/notes/{id}.json", path = {"id"}, body = {"call_id", "content"} },
    ["salesloft.put_v2_pending_emails_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/pending_emails/{id}.json", path = {"id"}, body = {"error_message", "message_id", "sent_at", "status"} },
    ["salesloft.put_v2_people_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/people/{id}.json", path = {"id"}, body = {"account_id", "city", "contact_restrictions", "country", "crm_id", "crm_id_type", "custom_fields", "do_not_contact", "email_address", "first_name", "home_phone", "import_id", "job_seniority", "last_name", "linkedin_url", "locale", "mobile_phone", "owner_id", "person_company_industry", "person_company_name", "person_company_website", "person_stage_id", "personal_email_address", "personal_website", "phone", "phone_extension", "secondary_email_address", "state", "tags", "title", "twitter_handle", "work_city", "work_country", "work_state"} },
    ["salesloft.put_v2_person_stages_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/person_stages/{id}.json", path = {"id"}, body = {"name"} },
    ["salesloft.put_v2_saved_list_views_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/saved_list_views/{id}.json", path = {"id"}, body = {"is_default", "name", "view_params"} },
    ["salesloft.put_v2_tasks_id_json"] = { method = "PUT", url = "https://api.salesloft.com/v2/tasks/{id}.json", path = {"id"}, body = {"current_state", "description", "due_date", "is_logged", "remind_at", "subject"} },
    ["salesloft.put_v2_webhook_subscriptions_id"] = { method = "PUT", url = "https://api.salesloft.com/v2/webhook_subscriptions/{id}", path = {"id"}, body = {"enabled"} },
  },
}
