-- Bird — every call this API accepts, as data.
--
-- GENERATED from https://bird.com/openapi.json
-- Published on the vendor's own documentation site (https://bird.com).
-- 282 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "bird",
  name = "Bird",
  base = "https://{subdomain}.bird.com",
  docs = "https://nango.dev/docs/api-integrations/bird",
  auth = {
    kind = "key",
    header = "authorization",
    format = "AccessKey {token}",
    env = "BIRD_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = { ["subdomain"] = "BIRD_SUBDOMAIN" },
  headers = {},
  operations = {
    ["bird.archive_contact_property"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/contact-properties/{property_id}/archive", path = {"property_id"}, header = {"Idempotency-Key"} },
    ["bird.assign_audience_contacts"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/audiences/{audience_id}/contacts", path = {"audience_id"}, header = {"Idempotency-Key"}, body = {"contact_ids"} },
    ["bird.cancel_email_broadcast"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}/cancel", path = {"broadcast_id"}, header = {"Idempotency-Key"} },
    ["bird.cancel_email_message"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/messages/{message_id}/cancel", path = {"message_id"}, header = {"Idempotency-Key"} },
    ["bird.create_audience"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/audiences", header = {"Idempotency-Key"}, body = {"name", "description", "type"} },
    ["bird.create_contact"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/contacts", header = {"Idempotency-Key"}, body = {"email", "phone_number", "first_name", "last_name", "external_id", "data"} },
    ["bird.create_contact_batch"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/contacts/batch", header = {"Idempotency-Key"}, body = {"contacts", "audience_ids", "match_on", "data_mode"} },
    ["bird.create_contact_property"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/contact-properties", header = {"Idempotency-Key"}, body = {"type", "fallback_value"} },
    ["bird.create_domain"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/domains", header = {"Idempotency-Key"}, body = {"domain", "return_path", "tracking", "dkim", "settings"} },
    ["bird.create_email_broadcast"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/broadcasts", header = {"Idempotency-Key"}, body = {"from", "audience_id", "template", "reply_to", "headers", "tags", "metadata", "track_opens", "track_clicks", "ip_pool_id", "category", "send", "scheduled_at"} },
    ["bird.create_email_competitive_watchlist_brand"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/competitive/watchlist/brands", header = {"Idempotency-Key"}, body = {"brand_id"} },
    ["bird.create_email_lookup"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/lookup/email", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"email"} },
    ["bird.create_email_message"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/messages", header = {"Idempotency-Key"}, body = {"from", "to", "cc", "bcc", "subject", "html", "text", "reply_to", "headers", "tags", "metadata", "parameters", "template", "track_opens", "track_clicks", "ip_pool_id", "category", "attachments", "scheduled_at"} },
    ["bird.create_email_message_batch"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/batches", header = {"Idempotency-Key"}, body = {"messages"} },
    ["bird.create_email_template"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/templates", header = {"Idempotency-Key"}, body = {"slug", "name", "description", "category", "source", "languages", "default_language", "on_missing_language", "language_source_required"} },
    ["bird.create_inbound_address"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/inbound-addresses", header = {"Idempotency-Key"}, body = {"label"} },
    ["bird.create_inbound_route"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/inbound-routes", header = {"Idempotency-Key"}, body = {"domain", "match_type", "match_value", "action", "target_mailbox_id", "priority", "enabled"} },
    ["bird.create_mailbox"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/mailboxes", header = {"Idempotency-Key"}, body = {"local_part", "domain", "display_name", "default_reply_to", "receive_policy", "retention_tier", "metadata"} },
    ["bird.create_mailbox_message"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/messages", path = {"mailbox_id"}, header = {"Idempotency-Key"}, body = {"to", "cc", "bcc", "subject", "html", "text", "reply_to", "attachments", "tags", "metadata", "category"} },
    ["bird.create_mailbox_receive_rule"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/receive-rules", path = {"mailbox_id"}, header = {"Idempotency-Key"}, body = {"action", "entry", "note"} },
    ["bird.create_numbers_order"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/numbers/orders", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"number"} },
    ["bird.create_phone_number_lookup"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/lookup/phone-number", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"phone_number", "type"} },
    ["bird.create_preference"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/preferences", header = {"Idempotency-Key"}, body = {"handle"} },
    ["bird.create_realtime_app"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/realtime/apps", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"client_events", "connection_counting", "connection_count_events", "watchlist_events", "authorized_connections"} },
    ["bird.create_realtime_app_key"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/keys", path = {"realtime_app_id"}, header = {"X-Workspace-Id", "Idempotency-Key"} },
    ["bird.create_smskeyword_rule"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/sms/keyword-rules", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"operation", "country", "language", "number", "keywords", "reply", "confirmed_self_managed"} },
    ["bird.create_smsmessage"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/sms/messages", header = {"Idempotency-Key"}, body = {"to", "from", "text", "category", "validity_period", "tags", "metadata", "options", "media_urls", "messaging_profile_id", "scheduled_at", "template", "broadcast_id", "campaign_id", "audience_id", "contact_id", "topic_id", "personalization"} },
    ["bird.create_smsmessage_batch"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/sms/batches", header = {"Idempotency-Key"}, body = {"messages"} },
    ["bird.create_smssuppression"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/sms/suppressions", header = {"Idempotency-Key"}, body = {"destination", "originator"} },
    ["bird.create_suppression"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/suppressions", header = {"Idempotency-Key"}, body = {"email"} },
    ["bird.create_verification"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/verify/verifications", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"to", "options", "metadata"} },
    ["bird.create_verification_check"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/verify/verifications/check", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"to", "code"} },
    ["bird.create_verification_next_channel"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/verify/verifications/next-channel", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"to"} },
    ["bird.create_webhook"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/webhooks", header = {"Idempotency-Key"}, body = {"url", "events", "description"} },
    ["bird.create_webhook_replay"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/webhooks/{webhook_id}/replay", path = {"webhook_id"}, header = {"Idempotency-Key"}, body = {"since", "until"} },
    ["bird.create_whats_app_keyword_rule"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/whatsapp/keyword-rules", header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"operation", "country", "waba", "keywords", "reply"} },
    ["bird.create_whats_app_message"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/whatsapp/messages", header = {"Idempotency-Key"}, body = {"to", "from", "template", "text", "image", "video", "audio", "sticker", "document", "location", "interactive", "contact_cards", "in_reply_to_message_id", "tags", "metadata"} },
    ["bird.delete_audience"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/audiences/{audience_id}", path = {"audience_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_contact"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/contacts/{contact_id}", path = {"contact_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_domain"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/domains/{domain_id}", path = {"domain_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_email_broadcast"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}", path = {"broadcast_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_email_competitive_watchlist_brand"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/competitive/watchlist/brands/{watchlist_brand_id}", path = {"watchlist_brand_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_email_template"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}", path = {"template_ref"}, header = {"Idempotency-Key"} },
    ["bird.delete_email_template_language"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}/languages/{language}", path = {"template_ref", "version_id", "language"}, header = {"Idempotency-Key"} },
    ["bird.delete_email_template_version"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}", path = {"template_ref", "version_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_email_thread"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}", path = {"thread_id"}, query = {"permanent"}, header = {"Idempotency-Key"} },
    ["bird.delete_email_thread_message"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages/{message_id}", path = {"thread_id", "message_id"}, query = {"permanent"}, header = {"Idempotency-Key"} },
    ["bird.delete_inbound_address"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/inbound-addresses/{inbound_address_id}", path = {"inbound_address_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_inbound_route"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/inbound-routes/{route_id}", path = {"route_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_mailbox"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}", path = {"mailbox_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_mailbox_receive_rule"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/receive-rules/{rule_id}", path = {"mailbox_id", "rule_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_preference"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/preferences/{preference_id}", path = {"preference_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_realtime_app"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}", path = {"realtime_app_id"}, header = {"X-Workspace-Id", "Idempotency-Key"} },
    ["bird.delete_smskeyword_rule"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/sms/keyword-rules/{id}", path = {"id"}, header = {"X-Workspace-Id", "Idempotency-Key"} },
    ["bird.delete_smssuppression"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/sms/suppressions/{suppression_id}", path = {"suppression_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_suppression"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/email/suppressions/{suppression_id}", path = {"suppression_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_webhook"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/webhooks/{webhook_id}", path = {"webhook_id"}, header = {"Idempotency-Key"} },
    ["bird.delete_whats_app_keyword_rule"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/whatsapp/keyword-rules/{id}", path = {"id"}, header = {"X-Workspace-Id", "Idempotency-Key"} },
    ["bird.delete_whats_app_message_reaction"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/whatsapp/messages/{message_id}/reaction", path = {"message_id"}, header = {"Idempotency-Key"} },
    ["bird.disconnect_realtime_app_member"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/members/{member_id}/disconnect", path = {"realtime_app_id", "member_id"}, header = {"X-Workspace-Id", "Idempotency-Key"} },
    ["bird.duplicate_email_template"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/duplicate", path = {"template_ref"}, header = {"Idempotency-Key"}, body = {"slug"} },
    ["bird.get_audience"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/audiences/{audience_id}", path = {"audience_id"} },
    ["bird.get_available_number"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/numbers/available/{number}", path = {"number"}, header = {"X-Workspace-Id"} },
    ["bird.get_contact"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/contacts/{contact_id}", path = {"contact_id"} },
    ["bird.get_contact_property"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/contact-properties/{property_id}", path = {"property_id"} },
    ["bird.get_current_workspace"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/workspace" },
    ["bird.get_docs_page"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/docs/pages", query = {"slug", "locale"} },
    ["bird.get_docs_search"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/docs/search", query = {"q", "locale", "limit", "contents"} },
    ["bird.get_domain"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/domains/{domain_id}", path = {"domain_id"} },
    ["bird.get_email_broadcast"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}", path = {"broadcast_id"} },
    ["bird.get_email_broadcast_counts"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}/counts", path = {"broadcast_id"} },
    ["bird.get_email_broadcast_recipients_export"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}/recipients/export", path = {"broadcast_id"}, query = {"to"} },
    ["bird.get_email_broadcast_send_quota"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}/send-quota", path = {"broadcast_id"} },
    ["bird.get_email_broadcasts_export"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts/export", query = {"status", "audience_id", "tag", "q", "created_after", "created_before"} },
    ["bird.get_email_competitive_brand"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/competitive/watchlist/brands/{watchlist_brand_id}", path = {"watchlist_brand_id"}, query = {"range"} },
    ["bird.get_email_competitive_brand_campaign"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/competitive/watchlist/brands/{watchlist_brand_id}/campaigns/{campaign_id}", path = {"watchlist_brand_id", "campaign_id"} },
    ["bird.get_email_competitive_brand_campaigns"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/competitive/watchlist/brands/{watchlist_brand_id}/campaigns", path = {"watchlist_brand_id"}, query = {"range", "sort", "order", "limit", "starting_after", "ending_before"} },
    ["bird.get_email_competitive_brand_send_time"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/competitive/watchlist/brands/{watchlist_brand_id}/send-time", path = {"watchlist_brand_id"}, query = {"timezone"} },
    ["bird.get_email_competitive_notable_campaigns"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/competitive/watchlist/notable", query = {"range"} },
    ["bird.get_email_competitive_volume_series"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/competitive/volume-series", query = {"range", "brand_ids"} },
    ["bird.get_email_competitive_watchlist"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/competitive/watchlist", query = {"range"} },
    ["bird.get_email_health"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/health", query = {"from", "to"} },
    ["bird.get_email_inbox_insights_authentication"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/authentication", query = {"sending_domain", "from", "to", "compare"} },
    ["bird.get_email_inbox_insights_blocklists"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/blocklists", query = {"sending_domain"} },
    ["bird.get_email_inbox_insights_complaints"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/complaints", query = {"sending_domain", "from", "to", "group_by", "compare"} },
    ["bird.get_email_inbox_insights_domains"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/domains", query = {"sending_domain", "search", "sort", "order", "limit", "starting_after", "ending_before"} },
    ["bird.get_email_inbox_insights_industry_benchmark"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/benchmarks/industry", query = {"sending_domain"} },
    ["bird.get_email_inbox_insights_placement"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/placement", query = {"sending_domain", "from", "to", "group_by", "compare", "series_providers", "include_ip_details"} },
    ["bird.get_email_inbox_insights_spam_traps"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/spam-traps", query = {"sending_domain", "from", "to", "compare"} },
    ["bird.get_email_lookup"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/lookup/email/{address}", path = {"address"}, header = {"X-Workspace-Id"} },
    ["bird.get_email_message"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/messages/{message_id}", path = {"message_id"} },
    ["bird.get_email_message_attachment"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/messages/{message_id}/attachments/{attachment_id}", path = {"message_id", "attachment_id"} },
    ["bird.get_email_message_content"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/messages/{message_id}/content", path = {"message_id"} },
    ["bird.get_email_smtp_config"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/smtp/configs/{api_key_id}", path = {"api_key_id"} },
    ["bird.get_email_stats_by_bounce_code"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/bounce-codes", query = {"from", "to", "timezone", "category", "sort", "limit"} },
    ["bird.get_email_stats_by_broadcast"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/broadcasts", query = {"from", "to", "category", "sort", "limit"} },
    ["bird.get_email_stats_by_category"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/categories", query = {"from", "to", "timezone", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_email_stats_by_client"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/clients", query = {"from", "to", "timezone", "category", "group_by", "sort", "limit"} },
    ["bird.get_email_stats_by_complaint_type"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/complaint-types", query = {"from", "to", "timezone", "category", "sort", "limit"} },
    ["bird.get_email_stats_by_location"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/locations", query = {"from", "to", "timezone", "category", "group_by", "sort", "limit"} },
    ["bird.get_email_stats_by_mailbox_provider"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/mailbox-providers", query = {"from", "to", "timezone", "category", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_email_stats_by_mailbox_provider_region"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/mailbox-provider-regions", query = {"from", "to", "timezone", "category", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_email_stats_by_recipient_domain"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/recipient-domains", query = {"from", "to", "timezone", "category", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_email_stats_by_sending_domain"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/sending-domains", query = {"from", "to", "timezone", "category", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_email_stats_by_sending_ip"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/sending-ips", query = {"from", "to", "timezone", "category", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_email_stats_by_tag"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/tags", query = {"from", "to", "timezone", "category", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_email_stats_by_template"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/templates", query = {"from", "to", "timezone", "category", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_email_stats_daily"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/daily", query = {"from", "to", "timezone", "category", "sending_domain", "tag", "sending_ip", "recipient_domain", "template"} },
    ["bird.get_email_stats_hourly"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/hourly", query = {"from", "to", "timezone", "category", "sending_domain", "tag", "sending_ip", "recipient_domain", "template"} },
    ["bird.get_email_stats_summary"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/stats/summary", query = {"from", "to", "timezone", "category", "sending_domain", "tag", "sending_ip", "recipient_domain", "template", "compare"} },
    ["bird.get_email_template"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}", path = {"template_ref"} },
    ["bird.get_email_template_language"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}/languages/{language}", path = {"template_ref", "version_id", "language"} },
    ["bird.get_email_template_preview"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/preview", path = {"template_ref"}, header = {"Idempotency-Key"}, body = {"content", "parameters", "contact", "language", "version"} },
    ["bird.get_email_template_version"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}", path = {"template_ref", "version_id"} },
    ["bird.get_email_thread"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}", path = {"thread_id"} },
    ["bird.get_email_thread_message"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages/{message_id}", path = {"thread_id", "message_id"} },
    ["bird.get_email_thread_message_attachment"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages/{message_id}/attachments/{attachment_id}", path = {"thread_id", "message_id", "attachment_id"} },
    ["bird.get_email_thread_message_body"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages/{message_id}/body", path = {"thread_id", "message_id"} },
    ["bird.get_email_thread_message_raw"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages/{message_id}/raw", path = {"thread_id", "message_id"} },
    ["bird.get_inbound_address"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-addresses/{inbound_address_id}", path = {"inbound_address_id"} },
    ["bird.get_inbound_message"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-messages/{inbound_message_id}", path = {"inbound_message_id"} },
    ["bird.get_inbound_message_attachment"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-messages/{inbound_message_id}/attachments/{attachment_id}", path = {"inbound_message_id", "attachment_id"} },
    ["bird.get_inbound_message_body"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-messages/{inbound_message_id}/body", path = {"inbound_message_id"} },
    ["bird.get_inbound_message_raw"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-messages/{inbound_message_id}/raw", path = {"inbound_message_id"} },
    ["bird.get_inbound_route"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-routes/{route_id}", path = {"route_id"} },
    ["bird.get_mailbox"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}", path = {"mailbox_id"} },
    ["bird.get_mailbox_stats"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/stats", path = {"mailbox_id"}, query = {"from", "to", "timezone", "granularity"} },
    ["bird.get_numbers_order"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/numbers/orders/{order_id}", path = {"order_id"}, header = {"X-Workspace-Id"} },
    ["bird.get_phone_number_lookup"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/lookup/phone-number/{number}", path = {"number"}, query = {"type"}, header = {"X-Workspace-Id"} },
    ["bird.get_preference"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/preferences/{preference_id}", path = {"preference_id"} },
    ["bird.get_realtime_app"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}", path = {"realtime_app_id"}, header = {"X-Workspace-Id"} },
    ["bird.get_realtime_app_channel"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/channels/{channel_name}", path = {"realtime_app_id", "channel_name"}, query = {"include"}, header = {"X-Workspace-Id"} },
    ["bird.get_smsinbound_stats_by_country"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/inbound/countries", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_smsinbound_stats_by_number"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/inbound/numbers", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_smsinbound_stats_by_operator"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/inbound/operators", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_smsinbound_stats_daily"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/inbound/daily", query = {"from", "to", "timezone"} },
    ["bird.get_smsinbound_stats_hourly"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/inbound/hourly", query = {"from", "to", "timezone"} },
    ["bird.get_smsinbound_stats_summary"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/inbound/summary", query = {"from", "to", "timezone", "compare"} },
    ["bird.get_smskeyword_rule"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/keyword-rules/{id}", path = {"id"}, header = {"X-Workspace-Id"} },
    ["bird.get_smsmessage"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/messages/{message_id}", path = {"message_id"} },
    ["bird.get_smsstats_by_carrier"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/carriers", query = {"from", "to", "timezone", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_smsstats_by_category"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/categories", query = {"from", "to", "timezone", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_smsstats_by_country"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/countries", query = {"from", "to", "timezone", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_smsstats_by_error_code"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/error-codes", query = {"from", "to", "timezone", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_smsstats_by_originator"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/originators", query = {"from", "to", "timezone", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_smsstats_by_status"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/statuses", query = {"from", "to", "timezone"} },
    ["bird.get_smsstats_by_tag"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/tags", query = {"from", "to", "timezone", "sort", "limit", "include_trend", "trend_grain"} },
    ["bird.get_smsstats_daily"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/daily", query = {"from", "to", "timezone", "originator", "country", "category", "carrier"} },
    ["bird.get_smsstats_hourly"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/hourly", query = {"from", "to", "timezone", "originator", "country", "category", "carrier"} },
    ["bird.get_smsstats_summary"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/stats/summary", query = {"from", "to", "timezone", "originator", "country", "category", "carrier", "compare"} },
    ["bird.get_smssuppression"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/suppressions/{suppression_id}", path = {"suppression_id"} },
    ["bird.get_smstemplate"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/templates/{template_ref}", path = {"template_ref"} },
    ["bird.get_smstemplate_version"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/templates/{template_ref}/versions/{version_id}", path = {"template_ref", "version_id"} },
    ["bird.get_smstemplate_version_language"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/templates/{template_ref}/versions/{version_id}/languages/{language}", path = {"template_ref", "version_id", "language"} },
    ["bird.get_suppression"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/suppressions/{suppression_id}", path = {"suppression_id"} },
    ["bird.get_voice_call"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/voice/calls/{call_id}", path = {"call_id"} },
    ["bird.get_webhook"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["bird.get_whats_app_business_account"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/business-accounts/{business_account_ref}", path = {"business_account_ref"} },
    ["bird.get_whats_app_inbound_stats_by_phone_number"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/inbound/phone-numbers", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_whats_app_inbound_stats_daily"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/inbound/daily", query = {"from", "to", "timezone"} },
    ["bird.get_whats_app_inbound_stats_hourly"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/inbound/hourly", query = {"from", "to", "timezone"} },
    ["bird.get_whats_app_inbound_stats_summary"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/inbound/summary", query = {"from", "to", "timezone", "compare"} },
    ["bird.get_whats_app_keyword_rule"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/keyword-rules/{id}", path = {"id"}, header = {"X-Workspace-Id"} },
    ["bird.get_whats_app_message"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/messages/{message_id}", path = {"message_id"} },
    ["bird.get_whats_app_message_media"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/messages/{message_id}/media/{media_id}", path = {"message_id", "media_id"} },
    ["bird.get_whats_app_number"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/numbers/{number_id}", path = {"number_id"} },
    ["bird.get_whats_app_number_profile"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/numbers/{number_id}/profile", path = {"number_id"} },
    ["bird.get_whats_app_stats_by_country"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/countries", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_whats_app_stats_by_error_code"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/error-codes", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_whats_app_stats_by_phone_number"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/phone-numbers", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_whats_app_stats_by_tag"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/tags", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_whats_app_stats_by_template"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/templates", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_whats_app_stats_by_template_category"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/template-categories", query = {"from", "to", "timezone", "limit"} },
    ["bird.get_whats_app_stats_daily"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/daily", query = {"from", "to", "timezone", "template", "category", "phone_number", "tag"} },
    ["bird.get_whats_app_stats_hourly"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/hourly", query = {"from", "to", "timezone", "template", "category", "phone_number", "tag"} },
    ["bird.get_whats_app_stats_summary"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/stats/summary", query = {"from", "to", "timezone", "template", "category", "phone_number", "tag", "compare"} },
    ["bird.get_whats_app_template"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/templates/{template_ref}", path = {"template_ref"} },
    ["bird.get_whats_app_template_version"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/templates/{template_ref}/versions/{version_id}", path = {"template_ref", "version_id"} },
    ["bird.get_whats_app_template_version_language"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/templates/{template_ref}/versions/{version_id}/languages/{language}", path = {"template_ref", "version_id", "language"} },
    ["bird.get_workspace_number"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/numbers/{number_id}", path = {"number_id"}, header = {"X-Workspace-Id"} },
    ["bird.list_audience_contacts"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/audiences/{audience_id}/contacts", path = {"audience_id"}, query = {"q", "limit", "starting_after", "ending_before"} },
    ["bird.list_audiences"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/audiences", query = {"q", "limit", "starting_after", "ending_before"} },
    ["bird.list_available_numbers"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/numbers/available", query = {"country_code", "number_type", "prefix", "capabilities", "limit", "starting_after", "ending_before"}, header = {"X-Workspace-Id"} },
    ["bird.list_contact_preferences"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/contacts/{contact_id}/preferences", path = {"contact_id"}, query = {"limit", "starting_after", "ending_before"} },
    ["bird.list_contact_properties"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/contact-properties", query = {"limit", "starting_after", "ending_before"} },
    ["bird.list_contacts"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/contacts", query = {"email", "phone_number", "external_id", "q", "identifier", "limit", "starting_after", "ending_before", "include_total"} },
    ["bird.list_domain_events"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/domains/{domain_id}/events", path = {"domain_id"}, query = {"sort", "order", "limit", "starting_after", "ending_before"} },
    ["bird.list_domains"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/domains", query = {"name", "sort", "order", "limit", "starting_after", "ending_before", "include_total"} },
    ["bird.list_email_broadcast_clicked_links"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}/clicked-links", path = {"broadcast_id"} },
    ["bird.list_email_broadcast_events"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}/events", path = {"broadcast_id"}, query = {"limit", "starting_after", "ending_before", "type"} },
    ["bird.list_email_broadcast_recipients"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}/recipients", path = {"broadcast_id"}, query = {"limit", "starting_after", "ending_before", "to"} },
    ["bird.list_email_broadcasts"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/broadcasts", query = {"limit", "starting_after", "ending_before", "status", "audience_id", "tag", "q", "created_after", "created_before"} },
    ["bird.list_email_message_events"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/messages/{message_id}/events", path = {"message_id"}, query = {"limit", "starting_after", "ending_before", "type"} },
    ["bird.list_email_message_recipients"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/messages/{message_id}/recipients", path = {"message_id"}, query = {"limit", "starting_after", "ending_before"} },
    ["bird.list_email_messages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/messages", query = {"limit", "starting_after", "ending_before", "created_after", "created_before", "status", "tag", "category", "to", "from"} },
    ["bird.list_email_smtp_configs"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/smtp/configs", query = {"sort", "order", "limit", "starting_after", "ending_before", "include_total"} },
    ["bird.list_email_template_broadcasts"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/broadcasts", path = {"template_ref"}, query = {"limit", "starting_after", "ending_before"} },
    ["bird.list_email_template_version_languages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}/languages", path = {"template_ref", "version_id"} },
    ["bird.list_email_template_versions"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions", path = {"template_ref"}, query = {"limit", "starting_after", "ending_before"} },
    ["bird.list_email_templates"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/templates", query = {"scope", "category", "source", "theme", "q", "limit", "starting_after", "ending_before"} },
    ["bird.list_email_thread_message_attachments"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages/{message_id}/attachments", path = {"thread_id", "message_id"} },
    ["bird.list_email_thread_messages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages", path = {"thread_id"}, query = {"direction", "label", "include", "limit", "starting_after", "ending_before"} },
    ["bird.list_email_threads"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/threads", query = {"mailbox_id", "contact_id", "label", "has_unread", "participant", "subject", "after", "before", "limit", "starting_after", "ending_before"} },
    ["bird.list_inbound_addresses"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-addresses", query = {"limit", "starting_after", "ending_before"} },
    ["bird.list_inbound_message_attachments"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-messages/{inbound_message_id}/attachments", path = {"inbound_message_id"} },
    ["bird.list_inbound_messages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-messages", query = {"from", "inbound_address_id", "received_after", "received_before", "limit", "starting_after", "ending_before"} },
    ["bird.list_inbound_routes"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/inbound-routes", query = {"domain", "enabled", "limit", "starting_after", "ending_before"} },
    ["bird.list_mailbox_labels"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/labels", path = {"mailbox_id"} },
    ["bird.list_mailbox_messages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/messages", path = {"mailbox_id"}, query = {"label", "direction", "status", "after", "before", "include", "limit", "starting_after", "ending_before"} },
    ["bird.list_mailbox_receive_rules"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/receive-rules", path = {"mailbox_id"}, query = {"action", "limit", "starting_after", "ending_before"} },
    ["bird.list_mailboxes"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/mailboxes", query = {"address", "q", "state", "domain", "include_deleted", "limit", "starting_after", "ending_before"} },
    ["bird.list_numbers_orders"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/numbers/orders", query = {"status", "limit", "starting_after", "ending_before"}, header = {"X-Workspace-Id"} },
    ["bird.list_preferences"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/preferences", query = {"channel", "handle", "limit", "starting_after", "ending_before"} },
    ["bird.list_realtime_app_channel_members"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/channels/{channel_name}/members", path = {"realtime_app_id", "channel_name"}, header = {"X-Workspace-Id"} },
    ["bird.list_realtime_app_channels"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/channels", path = {"realtime_app_id"}, query = {"prefix", "include"}, header = {"X-Workspace-Id"} },
    ["bird.list_realtime_app_keys"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/keys", path = {"realtime_app_id"}, query = {"include_revoked"}, header = {"X-Workspace-Id"} },
    ["bird.list_realtime_apps"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/realtime/apps", query = {"name", "sort", "order", "limit", "starting_after", "ending_before", "include_total"}, header = {"X-Workspace-Id"} },
    ["bird.list_realtime_regions"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/realtime/regions", header = {"X-Workspace-Id"} },
    ["bird.list_smskeyword_rules"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/keyword-rules", query = {"country", "number", "from_country", "operation", "scope"}, header = {"X-Workspace-Id"} },
    ["bird.list_smsmessage_events"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/messages/{message_id}/events", path = {"message_id"}, query = {"type"} },
    ["bird.list_smsmessages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/messages", query = {"limit", "starting_after", "ending_before", "created_after", "created_before", "direction", "status", "error_code", "category", "to", "from", "tag"} },
    ["bird.list_smssuppressions"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/suppressions", query = {"destination", "originator", "reason", "limit", "starting_after", "ending_before"} },
    ["bird.list_smstemplate_version_languages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/templates/{template_ref}/versions/{version_id}/languages", path = {"template_ref", "version_id"} },
    ["bird.list_smstemplate_versions"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/templates/{template_ref}/versions", path = {"template_ref"}, query = {"sort", "order", "limit", "starting_after", "ending_before"} },
    ["bird.list_smstemplates"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/sms/templates", query = {"scope", "category", "status", "language", "q", "sort", "order", "limit", "starting_after", "ending_before"} },
    ["bird.list_suppressions"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/suppressions", query = {"email", "reason", "scope_type", "limit", "starting_after", "ending_before"} },
    ["bird.list_voice_calls"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/voice/calls", query = {"direction", "status", "session_id", "sip_trunk_id", "from", "to", "number", "tag", "started_after", "started_before", "limit", "starting_after", "ending_before"} },
    ["bird.list_webhook_attempts"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/webhooks/{webhook_id}/attempts", path = {"webhook_id"}, query = {"limit", "before", "after"} },
    ["bird.list_webhooks"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/webhooks", query = {"sort", "order", "limit", "starting_after", "ending_before", "include_total"} },
    ["bird.list_whats_app_business_accounts"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/business-accounts", query = {"sort", "order", "limit", "starting_after", "ending_before"} },
    ["bird.list_whats_app_keyword_rules"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/keyword-rules", query = {"country", "waba", "operation", "scope"}, header = {"X-Workspace-Id"} },
    ["bird.list_whats_app_message_events"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/messages/{message_id}/events", path = {"message_id"}, query = {"type"} },
    ["bird.list_whats_app_message_reaction_events"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/messages/{message_id}/reaction-events", path = {"message_id"}, query = {"limit", "starting_after", "ending_before"} },
    ["bird.list_whats_app_messages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/messages", query = {"limit", "starting_after", "ending_before", "created_after", "created_before", "status", "direction", "to", "from", "phone_number", "bsuid", "category", "group_id", "tag"} },
    ["bird.list_whats_app_number_events"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/numbers/{number_id}/events", path = {"number_id"}, query = {"sort", "order", "limit", "starting_after", "ending_before"} },
    ["bird.list_whats_app_numbers"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/numbers", query = {"waba", "phone_number", "status", "scope", "sort", "order", "limit", "starting_after", "ending_before"} },
    ["bird.list_whats_app_template_version_languages"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/templates/{template_ref}/versions/{version_id}/languages", path = {"template_ref", "version_id"} },
    ["bird.list_whats_app_template_versions"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/templates/{template_ref}/versions", path = {"template_ref"}, query = {"limit", "starting_after", "ending_before"} },
    ["bird.list_whats_app_templates"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/whatsapp/templates", query = {"waba", "status", "scope", "category", "q", "limit", "starting_after", "ending_before"} },
    ["bird.list_workspace_numbers"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/numbers", query = {"number", "country_code", "number_type", "prefix", "capabilities", "limit", "starting_after", "ending_before"}, header = {"X-Workspace-Id"} },
    ["bird.publish_realtime_app_batch"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/batch-events", path = {"realtime_app_id"}, header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"events"} },
    ["bird.publish_realtime_app_event"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/events", path = {"realtime_app_id"}, header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"event", "channels", "data", "exclude_connection_id", "include"} },
    ["bird.release_tracking_domain"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/domains/{domain_id}/tracking/release", path = {"domain_id"}, header = {"Idempotency-Key"} },
    ["bird.release_workspace_number"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/numbers/{number_id}", path = {"number_id"}, header = {"X-Workspace-Id", "Idempotency-Key"} },
    ["bird.reply_email_thread_message"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages/{message_id}/reply", path = {"thread_id", "message_id"}, header = {"Idempotency-Key"}, body = {"html", "text", "reply_all", "tags", "metadata", "category", "attachments"} },
    ["bird.restore_mailbox"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/restore", path = {"mailbox_id"}, header = {"Idempotency-Key"} },
    ["bird.resume_mailbox"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}/resume", path = {"mailbox_id"}, header = {"Idempotency-Key"} },
    ["bird.revoke_realtime_app_key"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/keys/{realtime_app_key_id}/revoke", path = {"realtime_app_id", "realtime_app_key_id"}, header = {"X-Workspace-Id", "Idempotency-Key"} },
    ["bird.rollback_email_template"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}/rollback", path = {"template_ref", "version_id"}, header = {"Idempotency-Key"}, body = {"revision"} },
    ["bird.rotate_webhook_secret"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/webhooks/{webhook_id}/rotate-secret", path = {"webhook_id"}, header = {"Idempotency-Key"} },
    ["bird.search_email_competitive_brands"] = { method = "GET", url = "https://{subdomain}.bird.com/v1/email/competitive/brands/search", query = {"q"} },
    ["bird.send_email_broadcast"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}/send", path = {"broadcast_id"}, header = {"Idempotency-Key"}, body = {"scheduled_at"} },
    ["bird.send_realtime_app_member_event"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}/members/{member_id}/events", path = {"realtime_app_id", "member_id"}, header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"event", "data"} },
    ["bird.send_whats_app_read_receipt"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/whatsapp/messages/{message_id}/read", path = {"message_id"}, header = {"Idempotency-Key"}, body = {"typing_indicator"} },
    ["bird.share_domain_dns_records"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/domains/{domain_id}/dns-records/share", path = {"domain_id"}, header = {"Idempotency-Key"}, body = {"emails"} },
    ["bird.submit_email_template_version"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}/submit", path = {"template_ref", "version_id"}, header = {"Idempotency-Key"}, body = {"validate_only", "expected_revision", "languages"} },
    ["bird.test_webhook"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/webhooks/{webhook_id}/test", path = {"webhook_id"}, header = {"Idempotency-Key"}, body = {"event_type"} },
    ["bird.unarchive_contact_property"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/contact-properties/{property_id}/unarchive", path = {"property_id"}, header = {"Idempotency-Key"} },
    ["bird.unassign_audience_contact"] = { method = "DELETE", url = "https://{subdomain}.bird.com/v1/audiences/{audience_id}/contacts/{contact_id}", path = {"audience_id", "contact_id"}, header = {"Idempotency-Key"} },
    ["bird.unassign_audience_contacts"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/audiences/{audience_id}/contacts/remove", path = {"audience_id"}, header = {"Idempotency-Key"}, body = {"contact_ids"} },
    ["bird.update_audience"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/audiences/{audience_id}", path = {"audience_id"}, header = {"Idempotency-Key"}, body = {"name", "description"} },
    ["bird.update_contact"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/contacts/{contact_id}", path = {"contact_id"}, header = {"Idempotency-Key"}, body = {"email", "phone_number", "first_name", "last_name", "external_id", "data"} },
    ["bird.update_contact_property"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/contact-properties/{property_id}", path = {"property_id"}, header = {"Idempotency-Key"}, body = {"fallback_value"} },
    ["bird.update_domain"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/domains/{domain_id}", path = {"domain_id"}, header = {"Idempotency-Key"}, body = {"settings", "return_path", "tracking", "dkim", "inbound"} },
    ["bird.update_email_broadcast"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/broadcasts/{broadcast_id}", path = {"broadcast_id"}, header = {"Idempotency-Key"}, body = {"from", "audience_id", "template", "reply_to", "headers", "tags", "metadata", "track_opens", "track_clicks", "ip_pool_id", "category"} },
    ["bird.update_email_inbox_insights_domain"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/domains/{sending_domain}", path = {"sending_domain"}, header = {"Idempotency-Key"}, body = {"monitored"} },
    ["bird.update_email_smtp_config"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/smtp/configs/{api_key_id}", path = {"api_key_id"}, header = {"Idempotency-Key"}, body = {"ip_pool_id", "category", "tags", "track_opens", "track_clicks"} },
    ["bird.update_email_template"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}", path = {"template_ref"}, header = {"Idempotency-Key"}, body = {"revision", "name", "description", "default_language", "on_missing_language", "language_source_required"} },
    ["bird.update_email_template_language"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}/languages/{language}", path = {"template_ref", "version_id", "language"}, header = {"Idempotency-Key"}, body = {"subject", "preview_text", "html", "text", "revision"} },
    ["bird.update_email_thread"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}", path = {"thread_id"}, header = {"Idempotency-Key"}, body = {"labels", "contact_id"} },
    ["bird.update_email_thread_message"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/threads/{thread_id}/messages/{message_id}", path = {"thread_id", "message_id"}, header = {"Idempotency-Key"}, body = {"labels", "contact_id"} },
    ["bird.update_inbound_address"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/inbound-addresses/{inbound_address_id}", path = {"inbound_address_id"}, header = {"Idempotency-Key"}, body = {"label"} },
    ["bird.update_inbound_route"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/inbound-routes/{route_id}", path = {"route_id"}, header = {"Idempotency-Key"}, body = {"match_type", "match_value", "action", "target_mailbox_id", "priority", "enabled"} },
    ["bird.update_mailbox"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/email/mailboxes/{mailbox_id}", path = {"mailbox_id"}, query = {"confirm"}, header = {"Idempotency-Key"}, body = {"display_name", "default_reply_to", "receive_policy", "retention_tier", "metadata"} },
    ["bird.update_realtime_app"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/realtime/apps/{realtime_app_id}", path = {"realtime_app_id"}, header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"name", "client_events", "connection_counting", "connection_count_events", "watchlist_events", "authorized_connections"} },
    ["bird.update_smskeyword_rule"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/sms/keyword-rules/{id}", path = {"id"}, header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"keywords", "reply", "confirmed_self_managed"} },
    ["bird.update_webhook"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/webhooks/{webhook_id}", path = {"webhook_id"}, header = {"Idempotency-Key"}, body = {"url", "description", "events", "status"} },
    ["bird.update_whats_app_keyword_rule"] = { method = "PATCH", url = "https://{subdomain}.bird.com/v1/whatsapp/keyword-rules/{id}", path = {"id"}, header = {"X-Workspace-Id", "Idempotency-Key"}, body = {"keywords", "reply"} },
    ["bird.upsert_email_inbox_insights_domain_monitoring"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/inbox-insights/domain-monitoring", header = {"Idempotency-Key"} },
    ["bird.upsert_email_template_language"] = { method = "PUT", url = "https://{subdomain}.bird.com/v1/email/templates/{template_ref}/versions/{version_id}/languages/{language}", path = {"template_ref", "version_id", "language"}, header = {"Idempotency-Key"}, body = {"subject", "preview_text", "html", "text", "revision"} },
    ["bird.upsert_whats_app_message_reaction"] = { method = "PUT", url = "https://{subdomain}.bird.com/v1/whatsapp/messages/{message_id}/reaction", path = {"message_id"}, header = {"Idempotency-Key"}, body = {"emoji"} },
    ["bird.verify_domain"] = { method = "POST", url = "https://{subdomain}.bird.com/v1/email/domains/{domain_id}/verify", path = {"domain_id"}, header = {"Idempotency-Key"} },
  },
}
