-- Telegram — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/telegram.org/5.0.0/openapi.json
-- APIs.guru's mirror, matched on telegram.org. A mirror lags the vendor.
-- 74 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "telegram",
  name = "Telegram",
  base = "https://api.telegram.org/bot{apiKey}",
  docs = "https://nango.dev/docs/api-integrations/telegram",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "TELEGRAM_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = { ["apiKey"] = "TELEGRAM_APIKEY" },
  headers = {},
  operations = {
    ["telegram.post_addStickerToSet"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/addStickerToSet", body = {"emojis", "mask_position", "name", "png_sticker", "tgs_sticker", "user_id"} },
    ["telegram.post_answerCallbackQuery"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/answerCallbackQuery", body = {"cache_time", "callback_query_id", "show_alert", "text", "url"} },
    ["telegram.post_answerInlineQuery"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/answerInlineQuery", body = {"cache_time", "inline_query_id", "is_personal", "next_offset", "results", "switch_pm_parameter", "switch_pm_text"} },
    ["telegram.post_answerPreCheckoutQuery"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/answerPreCheckoutQuery", body = {"error_message", "ok", "pre_checkout_query_id"} },
    ["telegram.post_answerShippingQuery"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/answerShippingQuery", body = {"error_message", "ok", "shipping_options", "shipping_query_id"} },
    ["telegram.post_close"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/close" },
    ["telegram.post_copyMessage"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/copyMessage", body = {"allow_sending_without_reply", "caption", "caption_entities", "chat_id", "disable_notification", "from_chat_id", "message_id", "parse_mode", "reply_markup", "reply_to_message_id"} },
    ["telegram.post_createNewStickerSet"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/createNewStickerSet", body = {"contains_masks", "emojis", "mask_position", "name", "png_sticker", "tgs_sticker", "title", "user_id"} },
    ["telegram.post_deleteChatPhoto"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/deleteChatPhoto", body = {"chat_id"} },
    ["telegram.post_deleteChatStickerSet"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/deleteChatStickerSet", body = {"chat_id"} },
    ["telegram.post_deleteMessage"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/deleteMessage", body = {"chat_id", "message_id"} },
    ["telegram.post_deleteStickerFromSet"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/deleteStickerFromSet", body = {"sticker"} },
    ["telegram.post_deleteWebhook"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/deleteWebhook", body = {"drop_pending_updates"} },
    ["telegram.post_editMessageCaption"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/editMessageCaption", body = {"caption", "caption_entities", "chat_id", "inline_message_id", "message_id", "parse_mode", "reply_markup"} },
    ["telegram.post_editMessageLiveLocation"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/editMessageLiveLocation", body = {"chat_id", "heading", "horizontal_accuracy", "inline_message_id", "latitude", "longitude", "message_id", "proximity_alert_radius", "reply_markup"} },
    ["telegram.post_editMessageMedia"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/editMessageMedia", body = {"chat_id", "inline_message_id", "media", "message_id", "reply_markup"} },
    ["telegram.post_editMessageReplyMarkup"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/editMessageReplyMarkup", body = {"chat_id", "inline_message_id", "message_id", "reply_markup"} },
    ["telegram.post_editMessageText"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/editMessageText", body = {"chat_id", "disable_web_page_preview", "entities", "inline_message_id", "message_id", "parse_mode", "reply_markup", "text"} },
    ["telegram.post_exportChatInviteLink"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/exportChatInviteLink", body = {"chat_id"} },
    ["telegram.post_forwardMessage"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/forwardMessage", body = {"chat_id", "disable_notification", "from_chat_id", "message_id"} },
    ["telegram.post_getChat"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getChat", body = {"chat_id"} },
    ["telegram.post_getChatAdministrators"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getChatAdministrators", body = {"chat_id"} },
    ["telegram.post_getChatMember"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getChatMember", body = {"chat_id", "user_id"} },
    ["telegram.post_getChatMembersCount"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getChatMembersCount", body = {"chat_id"} },
    ["telegram.post_getFile"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getFile", body = {"file_id"} },
    ["telegram.post_getGameHighScores"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getGameHighScores", body = {"chat_id", "inline_message_id", "message_id", "user_id"} },
    ["telegram.post_getMe"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getMe" },
    ["telegram.post_getMyCommands"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getMyCommands" },
    ["telegram.post_getStickerSet"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getStickerSet", body = {"name"} },
    ["telegram.post_getUpdates"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getUpdates", body = {"allowed_updates", "limit", "offset", "timeout"} },
    ["telegram.post_getUserProfilePhotos"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getUserProfilePhotos", body = {"limit", "offset", "user_id"} },
    ["telegram.post_getWebhookInfo"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/getWebhookInfo" },
    ["telegram.post_kickChatMember"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/kickChatMember", body = {"chat_id", "until_date", "user_id"} },
    ["telegram.post_leaveChat"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/leaveChat", body = {"chat_id"} },
    ["telegram.post_logOut"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/logOut" },
    ["telegram.post_pinChatMessage"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/pinChatMessage", body = {"chat_id", "disable_notification", "message_id"} },
    ["telegram.post_promoteChatMember"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/promoteChatMember", body = {"can_change_info", "can_delete_messages", "can_edit_messages", "can_invite_users", "can_pin_messages", "can_post_messages", "can_promote_members", "can_restrict_members", "chat_id", "is_anonymous", "user_id"} },
    ["telegram.post_restrictChatMember"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/restrictChatMember", body = {"chat_id", "permissions", "until_date", "user_id"} },
    ["telegram.post_sendAnimation"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendAnimation", body = {"allow_sending_without_reply", "animation", "caption", "caption_entities", "chat_id", "disable_notification", "duration", "height", "parse_mode", "reply_markup", "reply_to_message_id", "thumb", "width"} },
    ["telegram.post_sendAudio"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendAudio", body = {"allow_sending_without_reply", "audio", "caption", "caption_entities", "chat_id", "disable_notification", "duration", "parse_mode", "performer", "reply_markup", "reply_to_message_id", "thumb", "title"} },
    ["telegram.post_sendChatAction"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendChatAction", body = {"action", "chat_id"} },
    ["telegram.post_sendContact"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendContact", body = {"allow_sending_without_reply", "chat_id", "disable_notification", "first_name", "last_name", "phone_number", "reply_markup", "reply_to_message_id", "vcard"} },
    ["telegram.post_sendDice"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendDice", body = {"allow_sending_without_reply", "chat_id", "disable_notification", "emoji", "reply_markup", "reply_to_message_id"} },
    ["telegram.post_sendDocument"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendDocument", body = {"allow_sending_without_reply", "caption", "caption_entities", "chat_id", "disable_content_type_detection", "disable_notification", "document", "parse_mode", "reply_markup", "reply_to_message_id", "thumb"} },
    ["telegram.post_sendGame"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendGame", body = {"allow_sending_without_reply", "chat_id", "disable_notification", "game_short_name", "reply_markup", "reply_to_message_id"} },
    ["telegram.post_sendInvoice"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendInvoice", body = {"allow_sending_without_reply", "chat_id", "currency", "description", "disable_notification", "is_flexible", "need_email", "need_name", "need_phone_number", "need_shipping_address", "payload", "photo_height", "photo_size", "photo_url", "photo_width", "prices", "provider_data", "provider_token", "reply_markup", "reply_to_message_id", "send_email_to_provider", "send_phone_number_to_provider", "start_parameter", "title"} },
    ["telegram.post_sendLocation"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendLocation", body = {"allow_sending_without_reply", "chat_id", "disable_notification", "heading", "horizontal_accuracy", "latitude", "live_period", "longitude", "proximity_alert_radius", "reply_markup", "reply_to_message_id"} },
    ["telegram.post_sendMediaGroup"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendMediaGroup", body = {"allow_sending_without_reply", "chat_id", "disable_notification", "media", "reply_to_message_id"} },
    ["telegram.post_sendMessage"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendMessage", body = {"allow_sending_without_reply", "chat_id", "disable_notification", "disable_web_page_preview", "entities", "parse_mode", "reply_markup", "reply_to_message_id", "text"} },
    ["telegram.post_sendPhoto"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendPhoto", body = {"allow_sending_without_reply", "caption", "caption_entities", "chat_id", "disable_notification", "parse_mode", "photo", "reply_markup", "reply_to_message_id"} },
    ["telegram.post_sendPoll"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendPoll", body = {"allow_sending_without_reply", "allows_multiple_answers", "chat_id", "close_date", "correct_option_id", "disable_notification", "explanation", "explanation_entities", "explanation_parse_mode", "is_anonymous", "is_closed", "open_period", "options", "question", "reply_markup", "reply_to_message_id", "type"} },
    ["telegram.post_sendSticker"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendSticker", body = {"allow_sending_without_reply", "chat_id", "disable_notification", "reply_markup", "reply_to_message_id", "sticker"} },
    ["telegram.post_sendVenue"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendVenue", body = {"address", "allow_sending_without_reply", "chat_id", "disable_notification", "foursquare_id", "foursquare_type", "google_place_id", "google_place_type", "latitude", "longitude", "reply_markup", "reply_to_message_id", "title"} },
    ["telegram.post_sendVideo"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendVideo", body = {"allow_sending_without_reply", "caption", "caption_entities", "chat_id", "disable_notification", "duration", "height", "parse_mode", "reply_markup", "reply_to_message_id", "supports_streaming", "thumb", "video", "width"} },
    ["telegram.post_sendVideoNote"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendVideoNote", body = {"allow_sending_without_reply", "chat_id", "disable_notification", "duration", "length", "reply_markup", "reply_to_message_id", "thumb", "video_note"} },
    ["telegram.post_sendVoice"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/sendVoice", body = {"allow_sending_without_reply", "caption", "caption_entities", "chat_id", "disable_notification", "duration", "parse_mode", "reply_markup", "reply_to_message_id", "voice"} },
    ["telegram.post_setChatAdministratorCustomTitle"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setChatAdministratorCustomTitle", body = {"chat_id", "custom_title", "user_id"} },
    ["telegram.post_setChatDescription"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setChatDescription", body = {"chat_id", "description"} },
    ["telegram.post_setChatPermissions"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setChatPermissions", body = {"chat_id", "permissions"} },
    ["telegram.post_setChatPhoto"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setChatPhoto", body = {"chat_id", "photo"} },
    ["telegram.post_setChatStickerSet"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setChatStickerSet", body = {"chat_id", "sticker_set_name"} },
    ["telegram.post_setChatTitle"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setChatTitle", body = {"chat_id", "title"} },
    ["telegram.post_setGameScore"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setGameScore", body = {"chat_id", "disable_edit_message", "force", "inline_message_id", "message_id", "score", "user_id"} },
    ["telegram.post_setMyCommands"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setMyCommands", body = {"commands"} },
    ["telegram.post_setPassportDataErrors"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setPassportDataErrors", body = {"errors", "user_id"} },
    ["telegram.post_setStickerPositionInSet"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setStickerPositionInSet", body = {"position", "sticker"} },
    ["telegram.post_setStickerSetThumb"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setStickerSetThumb", body = {"name", "thumb", "user_id"} },
    ["telegram.post_setWebhook"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/setWebhook", body = {"allowed_updates", "certificate", "drop_pending_updates", "ip_address", "max_connections", "url"} },
    ["telegram.post_stopMessageLiveLocation"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/stopMessageLiveLocation", body = {"chat_id", "inline_message_id", "message_id", "reply_markup"} },
    ["telegram.post_stopPoll"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/stopPoll", body = {"chat_id", "message_id", "reply_markup"} },
    ["telegram.post_unbanChatMember"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/unbanChatMember", body = {"chat_id", "only_if_banned", "user_id"} },
    ["telegram.post_unpinAllChatMessages"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/unpinAllChatMessages", body = {"chat_id"} },
    ["telegram.post_unpinChatMessage"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/unpinChatMessage", body = {"chat_id", "message_id"} },
    ["telegram.post_uploadStickerFile"] = { method = "POST", url = "https://api.telegram.org/bot{apiKey}/uploadStickerFile", body = {"png_sticker", "user_id"} },
  },
}
