-- Twitter — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/twitter.com/legacy/1.1/swagger.json
-- APIs.guru's mirror, matched on twitter.com. A mirror lags the vendor.
-- 83 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "twitter",
  name = "Twitter",
  base = "https://api.twitter.com",
  docs = "https://nango.dev/docs/integrations/all/twitter",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "TWITTER_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["twitter.account_settings_get"] = { method = "GET", url = "https://api.twitter.com/account/settings.json", query = {"trend_location_woeid", "sleep_time_enabled", "start_sleep_time", "end_sleep_time", "time_zone", "lang"} },
    ["twitter.account_settings_post"] = { method = "POST", url = "https://api.twitter.com/account/settings.json", query = {"trend_location_woeid", "sleep_time_enabled", "start_sleep_time", "end_sleep_time", "time_zone", "lang"} },
    ["twitter.account_update_delivery_device"] = { method = "POST", url = "https://api.twitter.com/account/update_delivery_device.json", query = {"device", "include_entities"} },
    ["twitter.account_update_profile"] = { method = "POST", url = "https://api.twitter.com/account/update_profile.json", query = {"name", "url", "location", "description", "include_entities", "skip_status"} },
    ["twitter.accounts_update_profile_background_image"] = { method = "POST", url = "https://api.twitter.com/account/update_profile_background_image.json", query = {"tile", "use", "include_entities", "skip_status"}, header = {"Content-Type"} },
    ["twitter.accounts_update_profile_colors"] = { method = "POST", url = "https://api.twitter.com/account/update_profile_colors.json", query = {"profile_background_color", "profile_link_color", "profile_sidebar_border_color", "profile_sidebar_fill_color", "profile_text_color", "include_entities", "skip_status"} },
    ["twitter.accounts_update_profile_image"] = { method = "POST", url = "https://api.twitter.com/account/update_profile_image.json", query = {"skip_status"}, header = {"Content-Type"} },
    ["twitter.application_rate_limit_status"] = { method = "GET", url = "https://api.twitter.com/application/rate_limit_status.json", query = {"resources"} },
    ["twitter.blocks_create"] = { method = "POST", url = "https://api.twitter.com/blocks/create.json", query = {"include_entities", "skip_status"} },
    ["twitter.blocks_destroy"] = { method = "POST", url = "https://api.twitter.com/blocks/destroy.json", query = {"include_entities", "skip_status"} },
    ["twitter.blocks_ids"] = { method = "GET", url = "https://api.twitter.com/blocks/ids.json", query = {"stringify_ids", "cursor"} },
    ["twitter.blocks_list"] = { method = "GET", url = "https://api.twitter.com/blocks/list.json", query = {"include_entities", "skip_status", "cursor"} },
    ["twitter.direct_messages"] = { method = "GET", url = "https://api.twitter.com/direct_messages.json", query = {"count", "since_id", "max_id", "include_entities", "page", "skip_status"} },
    ["twitter.direct_messages_destroy"] = { method = "POST", url = "https://api.twitter.com/direct_messages/destroy.json", query = {"id", "include_entities"} },
    ["twitter.direct_messages_new"] = { method = "POST", url = "https://api.twitter.com/direct_messages/new.json", query = {"text"} },
    ["twitter.direct_messages_sent"] = { method = "GET", url = "https://api.twitter.com/direct_messages/sent.json", query = {"count", "since_id", "max_id", "include_entities", "page"} },
    ["twitter.direct_messages_show"] = { method = "GET", url = "https://api.twitter.com/direct_messages/show.json", query = {"id"} },
    ["twitter.favorites_create"] = { method = "POST", url = "https://api.twitter.com/favorites/create.json", query = {"id", "include_entities"} },
    ["twitter.favorites_destroy"] = { method = "POST", url = "https://api.twitter.com/favorites/destroy.json", query = {"id", "include_entities"} },
    ["twitter.favorites_list"] = { method = "GET", url = "https://api.twitter.com/favorites/list.json", query = {"count", "since_id", "max_id", "include_entities"} },
    ["twitter.followers_ids"] = { method = "GET", url = "https://api.twitter.com/followers/ids.json", query = {"stringify_ids", "cursor"} },
    ["twitter.friends_ids"] = { method = "GET", url = "https://api.twitter.com/friends/ids.json", query = {"stringify_ids", "cursor"} },
    ["twitter.friendships_create"] = { method = "POST", url = "https://api.twitter.com/friendships/create.json", query = {"follow"} },
    ["twitter.friendships_destroy"] = { method = "POST", url = "https://api.twitter.com/friendships/destroy.json" },
    ["twitter.friendships_incoming"] = { method = "GET", url = "https://api.twitter.com/friendships/incoming.json", query = {"stringify_ids", "cursor"} },
    ["twitter.friendships_lookup"] = { method = "GET", url = "https://api.twitter.com/friendships/lookup.json" },
    ["twitter.friendships_outgoing"] = { method = "GET", url = "https://api.twitter.com/friendships/outgoing.json", query = {"stringify_ids", "cursor"} },
    ["twitter.friendships_show"] = { method = "GET", url = "https://api.twitter.com/friendships/show.json", query = {"source_id", "source_screen_name", "target_id", "target_screen_name"} },
    ["twitter.friendships_update"] = { method = "POST", url = "https://api.twitter.com/friendships/update.json", query = {"device", "retweets"} },
    ["twitter.geo_place_id"] = { method = "GET", url = "https://api.twitter.com/geo/id/{place_id}.json", path = {"place_id"} },
    ["twitter.geo_places"] = { method = "POST", url = "https://api.twitter.com/geo/places.json", query = {"attribute:street_address", "callback"} },
    ["twitter.geo_reverse_geocode"] = { method = "GET", url = "https://api.twitter.com/geo/reverse_geocode.json", query = {"lat", "long", "accuracy", "granularity", "max_results", "callback"} },
    ["twitter.geo_search"] = { method = "GET", url = "https://api.twitter.com/geo/search.json", query = {"accuracy", "granularity", "contained_within", "attribute:street_address", "callback"} },
    ["twitter.geo_similar_places"] = { method = "GET", url = "https://api.twitter.com/geo/similar_places.json", query = {"contained_within", "attribute:street_address", "callback"} },
    ["twitter.help_configurations"] = { method = "GET", url = "https://api.twitter.com/help/configuration.json" },
    ["twitter.help_languages"] = { method = "GET", url = "https://api.twitter.com/help/languages.json" },
    ["twitter.help_privacy"] = { method = "GET", url = "https://api.twitter.com/help/privacy.json" },
    ["twitter.help_tos"] = { method = "GET", url = "https://api.twitter.com/help/tos.json" },
    ["twitter.lists_create"] = { method = "POST", url = "https://api.twitter.com/lists/create.json", query = {"name", "mode", "description"} },
    ["twitter.lists_destroy"] = { method = "POST", url = "https://api.twitter.com/lists/destroy.json", query = {"owner_screen_name", "owner_id"} },
    ["twitter.lists_list"] = { method = "GET", url = "https://api.twitter.com/lists/list.json", query = {"screen_name", "user_id"} },
    ["twitter.lists_members"] = { method = "GET", url = "https://api.twitter.com/lists/members.json", query = {"owner_screen_name", "owner_id", "include_entities", "skip_status", "cursor"} },
    ["twitter.lists_members_create"] = { method = "POST", url = "https://api.twitter.com/lists/members/create.json", query = {"owner_screen_name", "owner_id"} },
    ["twitter.lists_members_create_all"] = { method = "POST", url = "https://api.twitter.com/lists/members/create_all.json", query = {"owner_screen_name", "owner_id", "user_id", "screen_name"} },
    ["twitter.lists_members_destroy"] = { method = "POST", url = "https://api.twitter.com/lists/members/destroy.json", query = {"list_id", "slug", "owner_screen_name", "owner_id", "user_id", "screen_name"} },
    ["twitter.lists_members_destroy_all"] = { method = "POST", url = "https://api.twitter.com/lists/members/destroy_all.json", query = {"owner_screen_name", "owner_id", "screen_name", "user_id"} },
    ["twitter.lists_members_show"] = { method = "GET", url = "https://api.twitter.com/lists/members/show.json", query = {"owner_screen_name", "owner_id", "include_entities", "skip_status"} },
    ["twitter.lists_memberships"] = { method = "GET", url = "https://api.twitter.com/lists/memberships.json", query = {"user_id", "screen_name", "cursor", "filter_to_owned_lists"} },
    ["twitter.lists_show"] = { method = "GET", url = "https://api.twitter.com/lists/show.json", query = {"owner_screen_name", "owner_id"} },
    ["twitter.lists_statuses"] = { method = "GET", url = "https://api.twitter.com/lists/statuses.json", query = {"owner_screen_name", "owner_id", "since_id", "max_id", "count", "include_entities", "include_rts"} },
    ["twitter.lists_subscribers"] = { method = "GET", url = "https://api.twitter.com/lists/subscribers.json", query = {"owner_screen_name", "owner_id", "cursor", "include_entities", "skip_status"} },
    ["twitter.lists_subscribers_create"] = { method = "POST", url = "https://api.twitter.com/lists/subscribers/create.json", query = {"owner_screen_name", "owner_id"} },
    ["twitter.lists_subscribers_destroy"] = { method = "POST", url = "https://api.twitter.com/lists/subscribers/destroy.json", query = {"owner_screen_name", "owner_id"} },
    ["twitter.lists_subscribers_show"] = { method = "GET", url = "https://api.twitter.com/lists/subscribers/show.json", query = {"owner_screen_name", "owner_id", "include_entities", "skip_status"} },
    ["twitter.lists_subscriptions"] = { method = "GET", url = "https://api.twitter.com/lists/subscriptions.json", query = {"count", "cursor"} },
    ["twitter.lists_update"] = { method = "POST", url = "https://api.twitter.com/lists/update.json", query = {"owner_screen_name", "owner_id", "name", "mode", "description"} },
    ["twitter.saved_searches_create"] = { method = "POST", url = "https://api.twitter.com/saved_searches/create.json", query = {"query"} },
    ["twitter.saved_searches_destroy"] = { method = "POST", url = "https://api.twitter.com/saved_searches/destroy/{id}.json", path = {"id"} },
    ["twitter.saved_searches_list"] = { method = "GET", url = "https://api.twitter.com/saved_searches/list.json" },
    ["twitter.savedsearchesid"] = { method = "GET", url = "https://api.twitter.com/saved_searches/show/{id}.json", path = {"id"} },
    ["twitter.search_tweets"] = { method = "GET", url = "https://api.twitter.com/search/tweets.json", query = {"q", "geocode", "lang", "locale", "result_type", "count", "until", "since_id", "max_id", "include_entities", "callback"} },
    ["twitter.statuses_destroy"] = { method = "POST", url = "https://api.twitter.com/statuses/destroy/{id}.json", path = {"id"}, query = {"trim_user"} },
    ["twitter.statuses_home_timeline"] = { method = "GET", url = "https://api.twitter.com/statuses/home_timeline.json", query = {"count", "max_id", "since_id", "trim_user", "exclude_replies", "contributor_details"} },
    ["twitter.statuses_mentions_timeline"] = { method = "GET", url = "https://api.twitter.com/statuses/mentions_timeline.json", query = {"count", "since_id", "max_id", "trim_user", "contributor_details", "include_entities"} },
    ["twitter.statuses_oembed"] = { method = "GET", url = "https://api.twitter.com/statuses/oembed.json", query = {"maxwidth", "hide_media", "hide_thread", "omit_script", "align", "related", "lang"} },
    ["twitter.statuses_retweets"] = { method = "GET", url = "https://api.twitter.com/statuses/retweets/{id}.json", path = {"id"}, query = {"count", "trim_user"} },
    ["twitter.statuses_show"] = { method = "GET", url = "https://api.twitter.com/statuses/show/{id}.json", path = {"id"}, query = {"trim_user", "include_my_retweet", "include_entities"} },
    ["twitter.statuses_update"] = { method = "POST", url = "https://api.twitter.com/statuses/update.json", query = {"status", "in_reply_to_status_id", "lat", "long", "place_id", "display_coordinates", "trim_user"} },
    ["twitter.statuses_update_with_media"] = { method = "POST", url = "https://api.twitter.com/statuses/update_with_media.json", query = {"status", "media", "possibly_sensitive", "in_reply_to_status_id", "lat", "long", "place_id", "display_coordinates"}, header = {"Content-Type"} },
    ["twitter.statuses_user_timeline"] = { method = "GET", url = "https://api.twitter.com/statuses/user_timeline.json", query = {"count", "since_id", "max_id", "trim_user", "exclude_replies", "contributor_details", "include_rts"} },
    ["twitter.statusesretweetid"] = { method = "POST", url = "https://api.twitter.com/statuses/retweet/{id}.json", path = {"id"}, query = {"trim_user"} },
    ["twitter.trends_available"] = { method = "GET", url = "https://api.twitter.com/trends/available.json" },
    ["twitter.trends_closest"] = { method = "GET", url = "https://api.twitter.com/trends/closest.json", query = {"lat", "long"} },
    ["twitter.trends_place"] = { method = "GET", url = "https://api.twitter.com/trends/place.json", query = {"id", "exclude"} },
    ["twitter.users_contributees"] = { method = "GET", url = "https://api.twitter.com/users/contributees.json", query = {"include_entities", "skip_status"} },
    ["twitter.users_contributors"] = { method = "GET", url = "https://api.twitter.com/users/contributors.json", query = {"include_entities", "skip_status"} },
    ["twitter.users_lookup"] = { method = "GET", url = "https://api.twitter.com/users/lookup.json", query = {"screen_name", "user_id", "include_entities"} },
    ["twitter.users_report_spam"] = { method = "POST", url = "https://api.twitter.com/users/report_spam.json" },
    ["twitter.users_search"] = { method = "GET", url = "https://api.twitter.com/users/search.json", query = {"q", "page", "count", "include_entities"} },
    ["twitter.users_show"] = { method = "GET", url = "https://api.twitter.com/users/show.json", query = {"screen_name", "user_id", "include_entities"} },
    ["twitter.users_suggestions"] = { method = "GET", url = "https://api.twitter.com/users/suggestions.json", query = {"lang"} },
    ["twitter.users_suggestions_slug"] = { method = "GET", url = "https://api.twitter.com/users/suggestions/{slug}.json", path = {"slug"}, query = {"lang"} },
    ["twitter.users_suggestionsslugmembers"] = { method = "GET", url = "https://api.twitter.com/users/suggestions/{slug}/members.json", path = {"slug"} },
  },
}
