-- Slack — every call this API accepts, as data.
--
-- GENERATED from https://api.slack.com/specs/openapi/v2/slack_web.json
-- Slack's own Web API description
-- 170 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "slack",
  name = "Slack",
  base = "https://slack.com/api",
  docs = "https://api.slack.com/methods",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "SLACK_BOT_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["slack.admin_apps_approve"] = { method = "POST", url = "https://slack.com/api/admin.apps.approve", body = {"app_id", "request_id", "team_id"}, body_format = "form" },
    ["slack.admin_apps_approved_list"] = { method = "GET", url = "https://slack.com/api/admin.apps.approved.list", query = {"limit", "cursor", "team_id", "enterprise_id"}, body_format = "form" },
    ["slack.admin_apps_requests_list"] = { method = "GET", url = "https://slack.com/api/admin.apps.requests.list", query = {"limit", "cursor", "team_id"}, body_format = "form" },
    ["slack.admin_apps_restrict"] = { method = "POST", url = "https://slack.com/api/admin.apps.restrict", body = {"app_id", "request_id", "team_id"}, body_format = "form" },
    ["slack.admin_apps_restricted_list"] = { method = "GET", url = "https://slack.com/api/admin.apps.restricted.list", query = {"limit", "cursor", "team_id", "enterprise_id"}, body_format = "form" },
    ["slack.admin_conversations_archive"] = { method = "POST", url = "https://slack.com/api/admin.conversations.archive", body = {"channel_id"}, body_format = "form" },
    ["slack.admin_conversations_convert_to_private"] = { method = "POST", url = "https://slack.com/api/admin.conversations.convertToPrivate", body = {"channel_id"}, body_format = "form" },
    ["slack.admin_conversations_create"] = { method = "POST", url = "https://slack.com/api/admin.conversations.create", body = {"name", "description", "is_private", "org_wide", "team_id"}, body_format = "form" },
    ["slack.admin_conversations_delete"] = { method = "POST", url = "https://slack.com/api/admin.conversations.delete", body = {"channel_id"}, body_format = "form" },
    ["slack.admin_conversations_disconnect_shared"] = { method = "POST", url = "https://slack.com/api/admin.conversations.disconnectShared", body = {"channel_id", "leaving_team_ids"}, body_format = "form" },
    ["slack.admin_conversations_ekm_list_original_connected_channel_info"] = { method = "GET", url = "https://slack.com/api/admin.conversations.ekm.listOriginalConnectedChannelInfo", query = {"channel_ids", "team_ids", "limit", "cursor"}, body_format = "form" },
    ["slack.admin_conversations_get_conversation_prefs"] = { method = "GET", url = "https://slack.com/api/admin.conversations.getConversationPrefs", query = {"channel_id"}, body_format = "form" },
    ["slack.admin_conversations_get_teams"] = { method = "GET", url = "https://slack.com/api/admin.conversations.getTeams", query = {"channel_id", "cursor", "limit"}, body_format = "form" },
    ["slack.admin_conversations_invite"] = { method = "POST", url = "https://slack.com/api/admin.conversations.invite", body = {"user_ids", "channel_id"}, body_format = "form" },
    ["slack.admin_conversations_rename"] = { method = "POST", url = "https://slack.com/api/admin.conversations.rename", body = {"channel_id", "name"}, body_format = "form" },
    ["slack.admin_conversations_restrict_access_add_group"] = { method = "POST", url = "https://slack.com/api/admin.conversations.restrictAccess.addGroup", body = {"team_id", "group_id", "channel_id"}, body_format = "form" },
    ["slack.admin_conversations_restrict_access_list_groups"] = { method = "GET", url = "https://slack.com/api/admin.conversations.restrictAccess.listGroups", query = {"channel_id", "team_id"}, body_format = "form" },
    ["slack.admin_conversations_restrict_access_remove_group"] = { method = "POST", url = "https://slack.com/api/admin.conversations.restrictAccess.removeGroup", body = {"team_id", "group_id", "channel_id"}, body_format = "form" },
    ["slack.admin_conversations_search"] = { method = "GET", url = "https://slack.com/api/admin.conversations.search", query = {"team_ids", "query", "limit", "cursor", "search_channel_types", "sort", "sort_dir"}, body_format = "form" },
    ["slack.admin_conversations_set_conversation_prefs"] = { method = "POST", url = "https://slack.com/api/admin.conversations.setConversationPrefs", body = {"channel_id", "prefs"}, body_format = "form" },
    ["slack.admin_conversations_set_teams"] = { method = "POST", url = "https://slack.com/api/admin.conversations.setTeams", body = {"channel_id", "team_id", "target_team_ids", "org_channel"}, body_format = "form" },
    ["slack.admin_conversations_unarchive"] = { method = "POST", url = "https://slack.com/api/admin.conversations.unarchive", body = {"channel_id"}, body_format = "form" },
    ["slack.admin_emoji_add"] = { method = "POST", url = "https://slack.com/api/admin.emoji.add", body = {"name", "url"}, body_format = "form" },
    ["slack.admin_emoji_add_alias"] = { method = "POST", url = "https://slack.com/api/admin.emoji.addAlias", body = {"name", "alias_for"}, body_format = "form" },
    ["slack.admin_emoji_list"] = { method = "GET", url = "https://slack.com/api/admin.emoji.list", query = {"cursor", "limit"}, body_format = "form" },
    ["slack.admin_emoji_remove"] = { method = "POST", url = "https://slack.com/api/admin.emoji.remove", body = {"name"}, body_format = "form" },
    ["slack.admin_emoji_rename"] = { method = "POST", url = "https://slack.com/api/admin.emoji.rename", body = {"name", "new_name"}, body_format = "form" },
    ["slack.admin_invite_requests_approve"] = { method = "POST", url = "https://slack.com/api/admin.inviteRequests.approve", body = {"team_id", "invite_request_id"}, body_format = "form" },
    ["slack.admin_invite_requests_approved_list"] = { method = "GET", url = "https://slack.com/api/admin.inviteRequests.approved.list", query = {"team_id", "cursor", "limit"}, body_format = "form" },
    ["slack.admin_invite_requests_denied_list"] = { method = "GET", url = "https://slack.com/api/admin.inviteRequests.denied.list", query = {"team_id", "cursor", "limit"}, body_format = "form" },
    ["slack.admin_invite_requests_deny"] = { method = "POST", url = "https://slack.com/api/admin.inviteRequests.deny", body = {"team_id", "invite_request_id"}, body_format = "form" },
    ["slack.admin_invite_requests_list"] = { method = "GET", url = "https://slack.com/api/admin.inviteRequests.list", query = {"team_id", "cursor", "limit"}, body_format = "form" },
    ["slack.admin_teams_admins_list"] = { method = "GET", url = "https://slack.com/api/admin.teams.admins.list", query = {"limit", "cursor", "team_id"}, body_format = "form" },
    ["slack.admin_teams_create"] = { method = "POST", url = "https://slack.com/api/admin.teams.create", body = {"team_domain", "team_name", "team_description", "team_discoverability"}, body_format = "form" },
    ["slack.admin_teams_list"] = { method = "GET", url = "https://slack.com/api/admin.teams.list", query = {"limit", "cursor"}, body_format = "form" },
    ["slack.admin_teams_owners_list"] = { method = "GET", url = "https://slack.com/api/admin.teams.owners.list", query = {"team_id", "limit", "cursor"}, body_format = "form" },
    ["slack.admin_teams_settings_info"] = { method = "GET", url = "https://slack.com/api/admin.teams.settings.info", query = {"team_id"}, body_format = "form" },
    ["slack.admin_teams_settings_set_default_channels"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setDefaultChannels", body = {"team_id", "channel_ids"}, body_format = "form" },
    ["slack.admin_teams_settings_set_description"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setDescription", body = {"team_id", "description"}, body_format = "form" },
    ["slack.admin_teams_settings_set_discoverability"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setDiscoverability", body = {"team_id", "discoverability"}, body_format = "form" },
    ["slack.admin_teams_settings_set_icon"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setIcon", body = {"image_url", "team_id"}, body_format = "form" },
    ["slack.admin_teams_settings_set_name"] = { method = "POST", url = "https://slack.com/api/admin.teams.settings.setName", body = {"team_id", "name"}, body_format = "form" },
    ["slack.admin_usergroups_add_channels"] = { method = "POST", url = "https://slack.com/api/admin.usergroups.addChannels", body = {"usergroup_id", "team_id", "channel_ids"}, body_format = "form" },
    ["slack.admin_usergroups_add_teams"] = { method = "POST", url = "https://slack.com/api/admin.usergroups.addTeams", body = {"usergroup_id", "team_ids", "auto_provision"}, body_format = "form" },
    ["slack.admin_usergroups_list_channels"] = { method = "GET", url = "https://slack.com/api/admin.usergroups.listChannels", query = {"usergroup_id", "team_id", "include_num_members"}, body_format = "form" },
    ["slack.admin_usergroups_remove_channels"] = { method = "POST", url = "https://slack.com/api/admin.usergroups.removeChannels", body = {"usergroup_id", "channel_ids"}, body_format = "form" },
    ["slack.admin_users_assign"] = { method = "POST", url = "https://slack.com/api/admin.users.assign", body = {"team_id", "user_id", "is_restricted", "is_ultra_restricted", "channel_ids"}, body_format = "form" },
    ["slack.admin_users_invite"] = { method = "POST", url = "https://slack.com/api/admin.users.invite", body = {"team_id", "email", "channel_ids", "custom_message", "real_name", "resend", "is_restricted", "is_ultra_restricted", "guest_expiration_ts"}, body_format = "form" },
    ["slack.admin_users_list"] = { method = "GET", url = "https://slack.com/api/admin.users.list", query = {"team_id", "cursor", "limit"}, body_format = "form" },
    ["slack.admin_users_remove"] = { method = "POST", url = "https://slack.com/api/admin.users.remove", body = {"team_id", "user_id"}, body_format = "form" },
    ["slack.admin_users_session_invalidate"] = { method = "POST", url = "https://slack.com/api/admin.users.session.invalidate", body = {"team_id", "session_id"}, body_format = "form" },
    ["slack.admin_users_session_reset"] = { method = "POST", url = "https://slack.com/api/admin.users.session.reset", body = {"user_id", "mobile_only", "web_only"}, body_format = "form" },
    ["slack.admin_users_set_admin"] = { method = "POST", url = "https://slack.com/api/admin.users.setAdmin", body = {"team_id", "user_id"}, body_format = "form" },
    ["slack.admin_users_set_expiration"] = { method = "POST", url = "https://slack.com/api/admin.users.setExpiration", body = {"team_id", "user_id", "expiration_ts"}, body_format = "form" },
    ["slack.admin_users_set_owner"] = { method = "POST", url = "https://slack.com/api/admin.users.setOwner", body = {"team_id", "user_id"}, body_format = "form" },
    ["slack.admin_users_set_regular"] = { method = "POST", url = "https://slack.com/api/admin.users.setRegular", body = {"team_id", "user_id"}, body_format = "form" },
    ["slack.api_test"] = { method = "GET", url = "https://slack.com/api/api.test", query = {"error", "foo"}, body_format = "form" },
    ["slack.apps_event_authorizations_list"] = { method = "GET", url = "https://slack.com/api/apps.event.authorizations.list", query = {"event_context", "cursor", "limit"}, body_format = "form" },
    ["slack.apps_permissions_info"] = { method = "GET", url = "https://slack.com/api/apps.permissions.info", body_format = "form" },
    ["slack.apps_permissions_request"] = { method = "GET", url = "https://slack.com/api/apps.permissions.request", query = {"scopes", "trigger_id"}, body_format = "form" },
    ["slack.apps_permissions_resources_list"] = { method = "GET", url = "https://slack.com/api/apps.permissions.resources.list", query = {"cursor", "limit"}, body_format = "form" },
    ["slack.apps_permissions_scopes_list"] = { method = "GET", url = "https://slack.com/api/apps.permissions.scopes.list", body_format = "form" },
    ["slack.apps_uninstall"] = { method = "GET", url = "https://slack.com/api/apps.uninstall", query = {"client_id", "client_secret"}, body_format = "form" },
    ["slack.auth_revoke"] = { method = "GET", url = "https://slack.com/api/auth.revoke", query = {"test"}, body_format = "form" },
    ["slack.auth_test"] = { method = "GET", url = "https://slack.com/api/auth.test", body_format = "form" },
    ["slack.bots_info"] = { method = "GET", url = "https://slack.com/api/bots.info", query = {"bot"}, body_format = "form" },
    ["slack.calls_add"] = { method = "POST", url = "https://slack.com/api/calls.add", body = {"external_unique_id", "external_display_id", "join_url", "desktop_app_join_url", "date_start", "title", "created_by", "users"}, body_format = "form" },
    ["slack.calls_end"] = { method = "POST", url = "https://slack.com/api/calls.end", body = {"id", "duration"}, body_format = "form" },
    ["slack.calls_info"] = { method = "GET", url = "https://slack.com/api/calls.info", query = {"id"}, body_format = "form" },
    ["slack.calls_participants_add"] = { method = "POST", url = "https://slack.com/api/calls.participants.add", body = {"id", "users"}, body_format = "form" },
    ["slack.calls_participants_remove"] = { method = "POST", url = "https://slack.com/api/calls.participants.remove", body = {"id", "users"}, body_format = "form" },
    ["slack.calls_update"] = { method = "POST", url = "https://slack.com/api/calls.update", body = {"id", "title", "join_url", "desktop_app_join_url"}, body_format = "form" },
    ["slack.chat_delete"] = { method = "POST", url = "https://slack.com/api/chat.delete", body = {"ts", "channel", "as_user"}, body_format = "form" },
    ["slack.chat_delete_scheduled_message"] = { method = "POST", url = "https://slack.com/api/chat.deleteScheduledMessage", body = {"as_user", "channel", "scheduled_message_id"}, body_format = "form" },
    ["slack.chat_get_permalink"] = { method = "GET", url = "https://slack.com/api/chat.getPermalink", query = {"channel", "message_ts"}, body_format = "form" },
    ["slack.chat_me_message"] = { method = "POST", url = "https://slack.com/api/chat.meMessage", body = {"channel", "text"}, body_format = "form" },
    ["slack.chat_post_ephemeral"] = { method = "POST", url = "https://slack.com/api/chat.postEphemeral", body = {"as_user", "attachments", "blocks", "channel", "icon_emoji", "icon_url", "link_names", "parse", "text", "thread_ts", "user", "username"}, body_format = "form" },
    ["slack.chat_post_message"] = { method = "POST", url = "https://slack.com/api/chat.postMessage", body = {"as_user", "attachments", "blocks", "channel", "icon_emoji", "icon_url", "link_names", "mrkdwn", "parse", "reply_broadcast", "text", "thread_ts", "unfurl_links", "unfurl_media", "username"}, body_format = "form" },
    ["slack.chat_schedule_message"] = { method = "POST", url = "https://slack.com/api/chat.scheduleMessage", body = {"channel", "text", "post_at", "parse", "as_user", "link_names", "attachments", "blocks", "unfurl_links", "unfurl_media", "thread_ts", "reply_broadcast"}, body_format = "form" },
    ["slack.chat_scheduled_messages_list"] = { method = "GET", url = "https://slack.com/api/chat.scheduledMessages.list", query = {"channel", "latest", "oldest", "limit", "cursor"}, body_format = "form" },
    ["slack.chat_unfurl"] = { method = "POST", url = "https://slack.com/api/chat.unfurl", body = {"channel", "ts", "unfurls", "user_auth_message", "user_auth_required", "user_auth_url"}, body_format = "form" },
    ["slack.chat_update"] = { method = "POST", url = "https://slack.com/api/chat.update", body = {"as_user", "attachments", "blocks", "channel", "link_names", "parse", "text", "ts"}, body_format = "form" },
    ["slack.conversations_archive"] = { method = "POST", url = "https://slack.com/api/conversations.archive", body = {"channel"}, body_format = "form" },
    ["slack.conversations_close"] = { method = "POST", url = "https://slack.com/api/conversations.close", body = {"channel"}, body_format = "form" },
    ["slack.conversations_create"] = { method = "POST", url = "https://slack.com/api/conversations.create", body = {"name", "is_private"}, body_format = "form" },
    ["slack.conversations_history"] = { method = "GET", url = "https://slack.com/api/conversations.history", query = {"channel", "latest", "oldest", "inclusive", "limit", "cursor"}, body_format = "form" },
    ["slack.conversations_info"] = { method = "GET", url = "https://slack.com/api/conversations.info", query = {"channel", "include_locale", "include_num_members"}, body_format = "form" },
    ["slack.conversations_invite"] = { method = "POST", url = "https://slack.com/api/conversations.invite", body = {"channel", "users"}, body_format = "form" },
    ["slack.conversations_join"] = { method = "POST", url = "https://slack.com/api/conversations.join", body = {"channel"}, body_format = "form" },
    ["slack.conversations_kick"] = { method = "POST", url = "https://slack.com/api/conversations.kick", body = {"channel", "user"}, body_format = "form" },
    ["slack.conversations_leave"] = { method = "POST", url = "https://slack.com/api/conversations.leave", body = {"channel"}, body_format = "form" },
    ["slack.conversations_list"] = { method = "GET", url = "https://slack.com/api/conversations.list", query = {"exclude_archived", "types", "limit", "cursor"}, body_format = "form" },
    ["slack.conversations_mark"] = { method = "POST", url = "https://slack.com/api/conversations.mark", body = {"channel", "ts"}, body_format = "form" },
    ["slack.conversations_members"] = { method = "GET", url = "https://slack.com/api/conversations.members", query = {"channel", "limit", "cursor"}, body_format = "form" },
    ["slack.conversations_open"] = { method = "POST", url = "https://slack.com/api/conversations.open", body = {"channel", "users", "return_im"}, body_format = "form" },
    ["slack.conversations_rename"] = { method = "POST", url = "https://slack.com/api/conversations.rename", body = {"channel", "name"}, body_format = "form" },
    ["slack.conversations_replies"] = { method = "GET", url = "https://slack.com/api/conversations.replies", query = {"channel", "ts", "latest", "oldest", "inclusive", "limit", "cursor"}, body_format = "form" },
    ["slack.conversations_set_purpose"] = { method = "POST", url = "https://slack.com/api/conversations.setPurpose", body = {"channel", "purpose"}, body_format = "form" },
    ["slack.conversations_set_topic"] = { method = "POST", url = "https://slack.com/api/conversations.setTopic", body = {"channel", "topic"}, body_format = "form" },
    ["slack.conversations_unarchive"] = { method = "POST", url = "https://slack.com/api/conversations.unarchive", body = {"channel"}, body_format = "form" },
    ["slack.dialog_open"] = { method = "GET", url = "https://slack.com/api/dialog.open", query = {"dialog", "trigger_id"}, body_format = "form" },
    ["slack.dnd_end_dnd"] = { method = "POST", url = "https://slack.com/api/dnd.endDnd", body_format = "form" },
    ["slack.dnd_end_snooze"] = { method = "POST", url = "https://slack.com/api/dnd.endSnooze", body_format = "form" },
    ["slack.dnd_info"] = { method = "GET", url = "https://slack.com/api/dnd.info", query = {"user"}, body_format = "form" },
    ["slack.dnd_set_snooze"] = { method = "POST", url = "https://slack.com/api/dnd.setSnooze", body = {"num_minutes"}, body_format = "form" },
    ["slack.dnd_team_info"] = { method = "GET", url = "https://slack.com/api/dnd.teamInfo", query = {"users"}, body_format = "form" },
    ["slack.emoji_list"] = { method = "GET", url = "https://slack.com/api/emoji.list", body_format = "form" },
    ["slack.files_comments_delete"] = { method = "POST", url = "https://slack.com/api/files.comments.delete", body = {"file", "id"}, body_format = "form" },
    ["slack.files_delete"] = { method = "POST", url = "https://slack.com/api/files.delete", body = {"file"}, body_format = "form" },
    ["slack.files_info"] = { method = "GET", url = "https://slack.com/api/files.info", query = {"file", "count", "page", "limit", "cursor"}, body_format = "form" },
    ["slack.files_list"] = { method = "GET", url = "https://slack.com/api/files.list", query = {"user", "channel", "ts_from", "ts_to", "types", "count", "page", "show_files_hidden_by_limit"}, body_format = "form" },
    ["slack.files_remote_add"] = { method = "POST", url = "https://slack.com/api/files.remote.add", body = {"external_id", "title", "filetype", "external_url", "preview_image", "indexable_file_contents"}, body_format = "form" },
    ["slack.files_remote_info"] = { method = "GET", url = "https://slack.com/api/files.remote.info", query = {"file", "external_id"}, body_format = "form" },
    ["slack.files_remote_list"] = { method = "GET", url = "https://slack.com/api/files.remote.list", query = {"channel", "ts_from", "ts_to", "limit", "cursor"}, body_format = "form" },
    ["slack.files_remote_remove"] = { method = "POST", url = "https://slack.com/api/files.remote.remove", body = {"file", "external_id"}, body_format = "form" },
    ["slack.files_remote_share"] = { method = "GET", url = "https://slack.com/api/files.remote.share", query = {"file", "external_id", "channels"}, body_format = "form" },
    ["slack.files_remote_update"] = { method = "POST", url = "https://slack.com/api/files.remote.update", body = {"file", "external_id", "title", "filetype", "external_url", "preview_image", "indexable_file_contents"}, body_format = "form" },
    ["slack.files_revoke_public_url"] = { method = "POST", url = "https://slack.com/api/files.revokePublicURL", body = {"file"}, body_format = "form" },
    ["slack.files_shared_public_url"] = { method = "POST", url = "https://slack.com/api/files.sharedPublicURL", body = {"file"}, body_format = "form" },
    ["slack.files_upload"] = { method = "POST", url = "https://slack.com/api/files.upload", body = {"file", "content", "filetype", "filename", "title", "initial_comment", "channels", "thread_ts"}, body_format = "form" },
    ["slack.migration_exchange"] = { method = "GET", url = "https://slack.com/api/migration.exchange", query = {"users", "team_id", "to_old"}, body_format = "form" },
    ["slack.oauth_access"] = { method = "GET", url = "https://slack.com/api/oauth.access", query = {"client_id", "client_secret", "code", "redirect_uri", "single_channel"}, body_format = "form" },
    ["slack.oauth_token"] = { method = "GET", url = "https://slack.com/api/oauth.token", query = {"client_id", "client_secret", "code", "redirect_uri", "single_channel"}, body_format = "form" },
    ["slack.oauth_v2_access"] = { method = "GET", url = "https://slack.com/api/oauth.v2.access", query = {"client_id", "client_secret", "code", "redirect_uri"}, body_format = "form" },
    ["slack.pins_add"] = { method = "POST", url = "https://slack.com/api/pins.add", body = {"channel", "timestamp"}, body_format = "form" },
    ["slack.pins_list"] = { method = "GET", url = "https://slack.com/api/pins.list", query = {"channel"}, body_format = "form" },
    ["slack.pins_remove"] = { method = "POST", url = "https://slack.com/api/pins.remove", body = {"channel", "timestamp"}, body_format = "form" },
    ["slack.reactions_add"] = { method = "POST", url = "https://slack.com/api/reactions.add", body = {"channel", "name", "timestamp"}, body_format = "form" },
    ["slack.reactions_get"] = { method = "GET", url = "https://slack.com/api/reactions.get", query = {"channel", "file", "file_comment", "full", "timestamp"}, body_format = "form" },
    ["slack.reactions_list"] = { method = "GET", url = "https://slack.com/api/reactions.list", query = {"user", "full", "count", "page", "cursor", "limit"}, body_format = "form" },
    ["slack.reactions_remove"] = { method = "POST", url = "https://slack.com/api/reactions.remove", body = {"name", "file", "file_comment", "channel", "timestamp"}, body_format = "form" },
    ["slack.reminders_add"] = { method = "POST", url = "https://slack.com/api/reminders.add", body = {"text", "time", "user"}, body_format = "form" },
    ["slack.reminders_complete"] = { method = "POST", url = "https://slack.com/api/reminders.complete", body = {"reminder"}, body_format = "form" },
    ["slack.reminders_delete"] = { method = "POST", url = "https://slack.com/api/reminders.delete", body = {"reminder"}, body_format = "form" },
    ["slack.reminders_info"] = { method = "GET", url = "https://slack.com/api/reminders.info", query = {"reminder"}, body_format = "form" },
    ["slack.reminders_list"] = { method = "GET", url = "https://slack.com/api/reminders.list", body_format = "form" },
    ["slack.rtm_connect"] = { method = "GET", url = "https://slack.com/api/rtm.connect", query = {"batch_presence_aware", "presence_sub"}, body_format = "form" },
    ["slack.search_messages"] = { method = "GET", url = "https://slack.com/api/search.messages", query = {"count", "highlight", "page", "query", "sort", "sort_dir"}, body_format = "form" },
    ["slack.stars_add"] = { method = "POST", url = "https://slack.com/api/stars.add", body = {"channel", "file", "file_comment", "timestamp"}, body_format = "form" },
    ["slack.stars_list"] = { method = "GET", url = "https://slack.com/api/stars.list", query = {"count", "page", "cursor", "limit"}, body_format = "form" },
    ["slack.stars_remove"] = { method = "POST", url = "https://slack.com/api/stars.remove", body = {"channel", "file", "file_comment", "timestamp"}, body_format = "form" },
    ["slack.team_access_logs"] = { method = "GET", url = "https://slack.com/api/team.accessLogs", query = {"before", "count", "page"}, body_format = "form" },
    ["slack.team_billable_info"] = { method = "GET", url = "https://slack.com/api/team.billableInfo", query = {"user"}, body_format = "form" },
    ["slack.team_info"] = { method = "GET", url = "https://slack.com/api/team.info", query = {"team"}, body_format = "form" },
    ["slack.team_integration_logs"] = { method = "GET", url = "https://slack.com/api/team.integrationLogs", query = {"app_id", "change_type", "count", "page", "service_id", "user"}, body_format = "form" },
    ["slack.team_profile_get"] = { method = "GET", url = "https://slack.com/api/team.profile.get", query = {"visibility"}, body_format = "form" },
    ["slack.usergroups_create"] = { method = "POST", url = "https://slack.com/api/usergroups.create", body = {"channels", "description", "handle", "include_count", "name"}, body_format = "form" },
    ["slack.usergroups_disable"] = { method = "POST", url = "https://slack.com/api/usergroups.disable", body = {"include_count", "usergroup"}, body_format = "form" },
    ["slack.usergroups_enable"] = { method = "POST", url = "https://slack.com/api/usergroups.enable", body = {"include_count", "usergroup"}, body_format = "form" },
    ["slack.usergroups_list"] = { method = "GET", url = "https://slack.com/api/usergroups.list", query = {"include_users", "include_count", "include_disabled"}, body_format = "form" },
    ["slack.usergroups_update"] = { method = "POST", url = "https://slack.com/api/usergroups.update", body = {"handle", "description", "channels", "include_count", "usergroup", "name"}, body_format = "form" },
    ["slack.usergroups_users_list"] = { method = "GET", url = "https://slack.com/api/usergroups.users.list", query = {"include_disabled", "usergroup"}, body_format = "form" },
    ["slack.usergroups_users_update"] = { method = "POST", url = "https://slack.com/api/usergroups.users.update", body = {"include_count", "usergroup", "users"}, body_format = "form" },
    ["slack.users_conversations"] = { method = "GET", url = "https://slack.com/api/users.conversations", query = {"user", "types", "exclude_archived", "limit", "cursor"}, body_format = "form" },
    ["slack.users_delete_photo"] = { method = "POST", url = "https://slack.com/api/users.deletePhoto", body_format = "form" },
    ["slack.users_get_presence"] = { method = "GET", url = "https://slack.com/api/users.getPresence", query = {"user"}, body_format = "form" },
    ["slack.users_identity"] = { method = "GET", url = "https://slack.com/api/users.identity", body_format = "form" },
    ["slack.users_info"] = { method = "GET", url = "https://slack.com/api/users.info", query = {"include_locale", "user"}, body_format = "form" },
    ["slack.users_list"] = { method = "GET", url = "https://slack.com/api/users.list", query = {"limit", "cursor", "include_locale"}, body_format = "form" },
    ["slack.users_lookup_by_email"] = { method = "GET", url = "https://slack.com/api/users.lookupByEmail", query = {"email"}, body_format = "form" },
    ["slack.users_profile_get"] = { method = "GET", url = "https://slack.com/api/users.profile.get", query = {"include_labels", "user"}, body_format = "form" },
    ["slack.users_profile_set"] = { method = "POST", url = "https://slack.com/api/users.profile.set", body = {"name", "profile", "user", "value"}, body_format = "form" },
    ["slack.users_set_active"] = { method = "POST", url = "https://slack.com/api/users.setActive", body_format = "form" },
    ["slack.users_set_photo"] = { method = "POST", url = "https://slack.com/api/users.setPhoto", body = {"crop_w", "crop_x", "crop_y", "image"}, body_format = "form" },
    ["slack.users_set_presence"] = { method = "POST", url = "https://slack.com/api/users.setPresence", body = {"presence"}, body_format = "form" },
    ["slack.views_open"] = { method = "GET", url = "https://slack.com/api/views.open", query = {"trigger_id", "view"}, body_format = "form" },
    ["slack.views_publish"] = { method = "GET", url = "https://slack.com/api/views.publish", query = {"user_id", "view", "hash"}, body_format = "form" },
    ["slack.views_push"] = { method = "GET", url = "https://slack.com/api/views.push", query = {"trigger_id", "view"}, body_format = "form" },
    ["slack.views_update"] = { method = "GET", url = "https://slack.com/api/views.update", query = {"view_id", "external_id", "view", "hash"}, body_format = "form" },
    ["slack.workflows_step_failed"] = { method = "GET", url = "https://slack.com/api/workflows.stepFailed", query = {"workflow_step_execute_id", "error"}, body_format = "form" },
  },
}
