-- Jira — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/atlassian.com/jira/1001.0.0-SNAPSHOT/openapi.json
-- APIs.guru's mirror, matched on atlassian.com. A mirror lags the vendor.
-- 474 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "jira",
  name = "Jira",
  base = "https://api.atlassian.com",
  docs = "https://nango.dev/docs/api-integrations/jira",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "JIRA_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["jira.add_actor_users"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/role/{id}", path = {"projectIdOrKey", "id"}, body = {"group", "groupId", "user"} },
    ["jira.add_attachment"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/attachments", path = {"issueIdOrKey"} },
    ["jira.add_comment"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/comment", path = {"issueIdOrKey"}, query = {"expand"}, body = {"author", "body", "created", "id", "jsdAuthorCanSeeRequest", "jsdPublic", "properties", "renderedBody", "self", "updateAuthor", "updated", "visibility"} },
    ["jira.add_field_to_default_screen"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/screens/addToDefault/{fieldId}", path = {"fieldId"} },
    ["jira.add_gadget"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/dashboard/{dashboardId}/gadget", path = {"dashboardId"}, body = {"color", "ignoreUriAndModuleKeyValidation", "moduleKey", "position", "title", "uri"} },
    ["jira.add_issue_types_to_context"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/issuetype", path = {"fieldId", "contextId"}, body = {"issueTypeIds"} },
    ["jira.add_issue_types_to_issue_type_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetypescheme/{issueTypeSchemeId}/issuetype", path = {"issueTypeSchemeId"}, body = {"issueTypeIds"} },
    ["jira.add_notifications"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/notificationscheme/{id}/notification", path = {"id"}, body = {"notificationSchemeEvents"} },
    ["jira.add_project_role_actors_to_role"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/role/{id}/actors", path = {"id"}, body = {"group", "groupId", "user"} },
    ["jira.add_screen_tab"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs", path = {"screenId"}, body = {"id", "name"} },
    ["jira.add_screen_tab_field"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs/{tabId}/fields", path = {"screenId", "tabId"}, body = {"fieldId"} },
    ["jira.add_share_permission"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/filter/{id}/permission", path = {"id"}, body = {"accountId", "groupId", "groupname", "projectId", "projectRoleId", "rights", "type"} },
    ["jira.add_user_to_group"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/group/user", query = {"groupname", "groupId"}, body = {"accountId", "name"} },
    ["jira.add_vote"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/votes", path = {"issueIdOrKey"} },
    ["jira.add_watcher"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/watchers", path = {"issueIdOrKey"} },
    ["jira.add_worklog"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog", path = {"issueIdOrKey"}, query = {"notifyUsers", "adjustEstimate", "newEstimate", "reduceBy", "expand", "overrideEditableFlag"}, body = {"author", "comment", "created", "id", "issueId", "properties", "self", "started", "timeSpent", "timeSpentSeconds", "updateAuthor", "updated", "visibility"} },
    ["jira.addon_properties_resource_delete_addon_property_delete"] = { method = "DELETE", url = "https://api.atlassian.com/rest/atlassian-connect/1/addons/{addonKey}/properties/{propertyKey}", path = {"addonKey", "propertyKey"} },
    ["jira.addon_properties_resource_get_addon_properties_get"] = { method = "GET", url = "https://api.atlassian.com/rest/atlassian-connect/1/addons/{addonKey}/properties", path = {"addonKey"} },
    ["jira.addon_properties_resource_get_addon_property_get"] = { method = "GET", url = "https://api.atlassian.com/rest/atlassian-connect/1/addons/{addonKey}/properties/{propertyKey}", path = {"addonKey", "propertyKey"} },
    ["jira.addon_properties_resource_put_addon_property_put"] = { method = "PUT", url = "https://api.atlassian.com/rest/atlassian-connect/1/addons/{addonKey}/properties/{propertyKey}", path = {"addonKey", "propertyKey"} },
    ["jira.analyse_expression"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/expression/analyse", query = {"check"}, body = {"contextVariables", "expressions"} },
    ["jira.app_issue_field_value_update_resource_update_issue_fields_put"] = { method = "PUT", url = "https://api.atlassian.com/rest/atlassian-connect/1/migration/field", header = {"Atlassian-Transfer-Id"}, body = {"updateValueList"} },
    ["jira.append_mappings_for_issue_type_screen_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping", path = {"issueTypeScreenSchemeId"}, body = {"issueTypeMappings"} },
    ["jira.archive_project"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/archive", path = {"projectIdOrKey"} },
    ["jira.assign_field_configuration_scheme_to_project"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme/project", body = {"fieldConfigurationSchemeId", "projectId"} },
    ["jira.assign_issue"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/assignee", path = {"issueIdOrKey"}, body = {"accountId", "accountType", "active", "applicationRoles", "avatarUrls", "displayName", "emailAddress", "expand", "groups", "locale", "name", "self", "timeZone"} },
    ["jira.assign_issue_type_scheme_to_project"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetypescheme/project", body = {"issueTypeSchemeId", "projectId"} },
    ["jira.assign_issue_type_screen_scheme_to_project"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/project", body = {"issueTypeScreenSchemeId", "projectId"} },
    ["jira.assign_permission_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/project/{projectKeyOrId}/permissionscheme", path = {"projectKeyOrId"}, query = {"expand"}, body = {"id"} },
    ["jira.assign_projects_to_custom_field_context"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/project", path = {"fieldId", "contextId"}, body = {"projectIds"} },
    ["jira.assign_scheme_to_project"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/project", body = {"projectId", "workflowSchemeId"} },
    ["jira.bulk_delete_issue_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/properties/{propertyKey}", path = {"propertyKey"}, body = {"currentValue", "entityIds"} },
    ["jira.bulk_get_groups"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/group/bulk", query = {"startAt", "maxResults", "groupId", "groupName", "accessType", "applicationKey"} },
    ["jira.bulk_get_users"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/bulk", query = {"startAt", "maxResults", "username", "accountId"} },
    ["jira.bulk_get_users_migration"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/bulk/migration", query = {"startAt", "maxResults", "username"} },
    ["jira.bulk_set_issue_properties_by_issue"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/properties/multi", body = {"issues"} },
    ["jira.bulk_set_issue_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issue/properties/{propertyKey}", path = {"propertyKey"}, body = {"expression", "filter", "value"} },
    ["jira.bulk_set_issues_properties_list"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/properties", body = {"entitiesIds", "properties"} },
    ["jira.cancel_task"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/task/{taskId}/cancel", path = {"taskId"} },
    ["jira.change_filter_owner"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/filter/{id}/owner", path = {"id"}, body = {"accountId"} },
    ["jira.copy_dashboard"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/dashboard/{id}/copy", path = {"id"}, body = {"description", "editPermissions", "name", "sharePermissions"} },
    ["jira.create_component"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/component", body = {"assignee", "assigneeType", "description", "id", "isAssigneeTypeValid", "lead", "leadAccountId", "leadUserName", "name", "project", "projectId", "realAssignee", "realAssigneeType", "self"} },
    ["jira.create_custom_field"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field", body = {"description", "name", "searcherKey", "type"} },
    ["jira.create_custom_field_context"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context", path = {"fieldId"}, body = {"description", "id", "issueTypeIds", "name", "projectIds"} },
    ["jira.create_custom_field_option"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/option", path = {"fieldId", "contextId"}, body = {"options"} },
    ["jira.create_dashboard"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/dashboard", body = {"description", "editPermissions", "name", "sharePermissions"} },
    ["jira.create_field_configuration"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/fieldconfiguration", body = {"description", "name"} },
    ["jira.create_field_configuration_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme", body = {"description", "name"} },
    ["jira.create_filter"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/filter", query = {"expand", "overrideSharePermissions"}, body = {"description", "editPermissions", "favourite", "favouritedCount", "id", "jql", "name", "owner", "searchUrl", "self", "sharePermissions", "sharedUsers", "subscriptions", "viewUrl"} },
    ["jira.create_group"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/group", body = {"name"} },
    ["jira.create_issue"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue", query = {"updateHistory"}, body = {"fields", "historyMetadata", "properties", "transition", "update"} },
    ["jira.create_issue_field_option"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field/{fieldKey}/option", path = {"fieldKey"}, body = {"config", "properties", "value"} },
    ["jira.create_issue_link_type"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issueLinkType", body = {"id", "inward", "name", "outward", "self"} },
    ["jira.create_issue_type"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issuetype", body = {"description", "hierarchyLevel", "name", "type"} },
    ["jira.create_issue_type_avatar"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issuetype/{id}/avatar2", path = {"id"}, query = {"x", "y", "size"} },
    ["jira.create_issue_type_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issuetypescheme", body = {"defaultIssueTypeId", "description", "issueTypeIds", "name"} },
    ["jira.create_issue_type_screen_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme", body = {"description", "issueTypeMappings", "name"} },
    ["jira.create_issues"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/bulk", body = {"issueUpdates"} },
    ["jira.create_notification_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/notificationscheme", body = {"description", "name", "notificationSchemeEvents"} },
    ["jira.create_or_update_remote_issue_link"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/remotelink", path = {"issueIdOrKey"}, body = {"application", "globalId", "object", "relationship"} },
    ["jira.create_permission_grant"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/permissionscheme/{schemeId}/permission", path = {"schemeId"}, query = {"expand"}, body = {"holder", "id", "permission", "self"} },
    ["jira.create_permission_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/permissionscheme", query = {"expand"}, body = {"description", "expand", "id", "name", "permissions", "scope", "self"} },
    ["jira.create_priority"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/priority", body = {"description", "iconUrl", "name", "statusColor"} },
    ["jira.create_project"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/project", body = {"assigneeType", "avatarId", "categoryId", "description", "fieldConfigurationScheme", "issueSecurityScheme", "issueTypeScheme", "issueTypeScreenScheme", "lead", "leadAccountId", "name", "notificationScheme", "permissionScheme", "projectTemplateKey", "projectTypeKey", "url", "workflowScheme"} },
    ["jira.create_project_avatar"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/avatar2", path = {"projectIdOrKey"}, query = {"x", "y", "size"} },
    ["jira.create_project_category"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/projectCategory", body = {"description", "id", "name", "self"} },
    ["jira.create_project_role"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/role", body = {"description", "name"} },
    ["jira.create_resolution"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/resolution", body = {"description", "name"} },
    ["jira.create_screen"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/screens", body = {"description", "name"} },
    ["jira.create_screen_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/screenscheme", body = {"description", "name", "screens"} },
    ["jira.create_statuses"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/statuses", body = {"scope", "statuses"} },
    ["jira.create_ui_modification"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/uiModifications", body = {"contexts", "data", "description", "name"} },
    ["jira.create_user"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/user", body = {"applicationKeys", "displayName", "emailAddress", "name", "password", "self"} },
    ["jira.create_version"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/version", body = {"archived", "description", "expand", "id", "issuesStatusForFixVersion", "moveUnfixedIssuesTo", "name", "operations", "overdue", "project", "projectId", "releaseDate", "released", "self", "startDate", "userReleaseDate", "userStartDate"} },
    ["jira.create_workflow"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/workflow", body = {"description", "name", "statuses", "transitions"} },
    ["jira.create_workflow_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/workflowscheme", body = {"defaultWorkflow", "description", "draft", "id", "issueTypeMappings", "issueTypes", "lastModified", "lastModifiedUser", "name", "originalDefaultWorkflow", "originalIssueTypeMappings", "self", "updateDraftIfNeeded"} },
    ["jira.create_workflow_scheme_draft_from_parent"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/createdraft", path = {"id"} },
    ["jira.create_workflow_transition_property"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/workflow/transitions/{transitionId}/properties", path = {"transitionId"}, query = {"workflowName", "workflowMode"}, body = {"id", "value"} },
    ["jira.delete_actor"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/role/{id}", path = {"projectIdOrKey", "id"}, query = {"user", "group", "groupId"} },
    ["jira.delete_and_replace_version"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/version/{id}/removeAndSwap", path = {"id"}, body = {"customFieldReplacementList", "moveAffectedIssuesTo", "moveFixIssuesTo"} },
    ["jira.delete_avatar"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/universal_avatar/type/{type}/owner/{owningObjectId}/avatar/{id}", path = {"type", "owningObjectId", "id"} },
    ["jira.delete_comment"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/comment/{id}", path = {"issueIdOrKey", "id"} },
    ["jira.delete_comment_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/comment/{commentId}/properties/{propertyKey}", path = {"commentId", "propertyKey"} },
    ["jira.delete_component"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/component/{id}", path = {"id"}, query = {"moveIssuesTo"} },
    ["jira.delete_custom_field"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/field/{id}", path = {"id"} },
    ["jira.delete_custom_field_context"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}", path = {"fieldId", "contextId"} },
    ["jira.delete_custom_field_option"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/option/{optionId}", path = {"fieldId", "contextId", "optionId"} },
    ["jira.delete_dashboard"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/dashboard/{id}", path = {"id"} },
    ["jira.delete_dashboard_item_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}", path = {"dashboardId", "itemId", "propertyKey"} },
    ["jira.delete_default_workflow"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/default", path = {"id"}, query = {"updateDraftIfNeeded"} },
    ["jira.delete_draft_default_workflow"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/default", path = {"id"} },
    ["jira.delete_draft_workflow_mapping"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/workflow", path = {"id"}, query = {"workflowName"} },
    ["jira.delete_favourite_for_filter"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/filter/{id}/favourite", path = {"id"}, query = {"expand"} },
    ["jira.delete_field_configuration"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/fieldconfiguration/{id}", path = {"id"} },
    ["jira.delete_field_configuration_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme/{id}", path = {"id"} },
    ["jira.delete_filter"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/filter/{id}", path = {"id"} },
    ["jira.delete_inactive_workflow"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflow/{entityId}", path = {"entityId"} },
    ["jira.delete_issue"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}", path = {"issueIdOrKey"}, query = {"deleteSubtasks"} },
    ["jira.delete_issue_field_option"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/field/{fieldKey}/option/{optionId}", path = {"fieldKey", "optionId"} },
    ["jira.delete_issue_link"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issueLink/{linkId}", path = {"linkId"} },
    ["jira.delete_issue_link_type"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issueLinkType/{issueLinkTypeId}", path = {"issueLinkTypeId"} },
    ["jira.delete_issue_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/properties/{propertyKey}", path = {"issueIdOrKey", "propertyKey"} },
    ["jira.delete_issue_type"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issuetype/{id}", path = {"id"}, query = {"alternativeIssueTypeId"} },
    ["jira.delete_issue_type_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issuetype/{issueTypeId}/properties/{propertyKey}", path = {"issueTypeId", "propertyKey"} },
    ["jira.delete_issue_type_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issuetypescheme/{issueTypeSchemeId}", path = {"issueTypeSchemeId"} },
    ["jira.delete_issue_type_screen_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}", path = {"issueTypeScreenSchemeId"} },
    ["jira.delete_notification_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/notificationscheme/{notificationSchemeId}", path = {"notificationSchemeId"} },
    ["jira.delete_permission_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/permissionscheme/{schemeId}", path = {"schemeId"} },
    ["jira.delete_permission_scheme_entity"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/permissionscheme/{schemeId}/permission/{permissionId}", path = {"schemeId", "permissionId"} },
    ["jira.delete_priority"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/priority/{id}", path = {"id"}, query = {"replaceWith"} },
    ["jira.delete_project"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}", path = {"projectIdOrKey"}, query = {"enableUndo"} },
    ["jira.delete_project_asynchronously"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/delete", path = {"projectIdOrKey"} },
    ["jira.delete_project_avatar"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/avatar/{id}", path = {"projectIdOrKey", "id"} },
    ["jira.delete_project_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/properties/{propertyKey}", path = {"projectIdOrKey", "propertyKey"} },
    ["jira.delete_project_role"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/role/{id}", path = {"id"}, query = {"swap"} },
    ["jira.delete_project_role_actors_from_role"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/role/{id}/actors", path = {"id"}, query = {"user", "groupId", "group"} },
    ["jira.delete_remote_issue_link_by_global_id"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/remotelink", path = {"issueIdOrKey"}, query = {"globalId"} },
    ["jira.delete_remote_issue_link_by_id"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/remotelink/{linkId}", path = {"issueIdOrKey", "linkId"} },
    ["jira.delete_resolution"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/resolution/{id}", path = {"id"}, query = {"replaceWith"} },
    ["jira.delete_screen"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}", path = {"screenId"} },
    ["jira.delete_screen_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/screenscheme/{screenSchemeId}", path = {"screenSchemeId"} },
    ["jira.delete_screen_tab"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs/{tabId}", path = {"screenId", "tabId"} },
    ["jira.delete_share_permission"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/filter/{id}/permission/{permissionId}", path = {"id", "permissionId"} },
    ["jira.delete_statuses_by_id"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/statuses", query = {"id"} },
    ["jira.delete_ui_modification"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/uiModifications/{uiModificationId}", path = {"uiModificationId"} },
    ["jira.delete_user_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/user/properties/{propertyKey}", path = {"propertyKey"}, query = {"accountId", "userKey", "username"} },
    ["jira.delete_webhook_by_id"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/webhook", body = {"webhookIds"} },
    ["jira.delete_workflow_mapping"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/workflow", path = {"id"}, query = {"workflowName", "updateDraftIfNeeded"} },
    ["jira.delete_workflow_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}", path = {"id"} },
    ["jira.delete_workflow_scheme_draft"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft", path = {"id"} },
    ["jira.delete_workflow_scheme_draft_issue_type"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/issuetype/{issueType}", path = {"id", "issueType"} },
    ["jira.delete_workflow_scheme_issue_type"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/issuetype/{issueType}", path = {"id", "issueType"}, query = {"updateDraftIfNeeded"} },
    ["jira.delete_workflow_transition_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/workflow/transitions/{transitionId}/properties", path = {"transitionId"}, query = {"workflowName", "workflowMode"} },
    ["jira.delete_workflow_transition_rule_configurations"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflow/rule/config/delete", body = {"workflows"} },
    ["jira.delete_worklog"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog/{id}", path = {"issueIdOrKey", "id"}, query = {"notifyUsers", "adjustEstimate", "newEstimate", "increaseBy", "overrideEditableFlag"} },
    ["jira.delete_worklog_property"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}", path = {"issueIdOrKey", "worklogId", "propertyKey"} },
    ["jira.do_transition"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/transitions", path = {"issueIdOrKey"}, body = {"fields", "historyMetadata", "properties", "transition", "update"} },
    ["jira.dynamic_modules_resource_get_modules_get"] = { method = "GET", url = "https://api.atlassian.com/rest/atlassian-connect/1/app/module/dynamic" },
    ["jira.dynamic_modules_resource_register_modules_post"] = { method = "POST", url = "https://api.atlassian.com/rest/atlassian-connect/1/app/module/dynamic", body = {"modules"} },
    ["jira.dynamic_modules_resource_remove_modules_delete"] = { method = "DELETE", url = "https://api.atlassian.com/rest/atlassian-connect/1/app/module/dynamic", query = {"moduleKey"} },
    ["jira.edit_issue"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}", path = {"issueIdOrKey"}, query = {"notifyUsers", "overrideScreenSecurity", "overrideEditableFlag"}, body = {"fields", "historyMetadata", "properties", "transition", "update"} },
    ["jira.evaluate_jira_expression"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/expression/eval", query = {"expand"}, body = {"context", "expression"} },
    ["jira.expand_attachment_for_humans"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/attachment/{id}/expand/human", path = {"id"} },
    ["jira.expand_attachment_for_machines"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/attachment/{id}/expand/raw", path = {"id"} },
    ["jira.find_assignable_users"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/assignable/search", query = {"query", "sessionId", "username", "accountId", "project", "issueKey", "startAt", "maxResults", "actionDescriptorId", "recommend"} },
    ["jira.find_bulk_assignable_users"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/assignable/multiProjectSearch", query = {"query", "username", "accountId", "projectKeys", "startAt", "maxResults"} },
    ["jira.find_groups"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/groups/picker", query = {"accountId", "query", "exclude", "excludeId", "maxResults", "caseInsensitive", "userName"} },
    ["jira.find_user_keys_by_query"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/search/query/key", query = {"query", "startAt", "maxResults"} },
    ["jira.find_users"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/search", query = {"query", "username", "accountId", "startAt", "maxResults", "property"} },
    ["jira.find_users_and_groups"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/groupuserpicker", query = {"query", "maxResults", "showAvatar", "fieldId", "projectId", "issueTypeId", "avatarSize", "caseInsensitive", "excludeConnectAddons"} },
    ["jira.find_users_by_query"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/search/query", query = {"query", "startAt", "maxResults"} },
    ["jira.find_users_for_picker"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/picker", query = {"query", "maxResults", "showAvatar", "exclude", "excludeAccountIds", "avatarSize", "excludeConnectUsers"} },
    ["jira.find_users_with_all_permissions"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/permission/search", query = {"query", "username", "accountId", "permissions", "issueKey", "projectKey", "startAt", "maxResults"} },
    ["jira.find_users_with_browse_permission"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/viewissue/search", query = {"query", "username", "accountId", "issueKey", "projectKey", "startAt", "maxResults"} },
    ["jira.fully_update_project_role"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/role/{id}", path = {"id"}, body = {"description", "name"} },
    ["jira.get_accessible_project_type_by_key"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/type/{projectTypeKey}/accessible", path = {"projectTypeKey"} },
    ["jira.get_advanced_settings"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/application-properties/advanced-settings" },
    ["jira.get_all_accessible_project_types"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/type/accessible" },
    ["jira.get_all_application_roles"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/applicationrole" },
    ["jira.get_all_available_dashboard_gadgets"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/dashboard/gadgets" },
    ["jira.get_all_dashboards"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/dashboard", query = {"filter", "startAt", "maxResults"} },
    ["jira.get_all_field_configuration_schemes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme", query = {"startAt", "maxResults", "id"} },
    ["jira.get_all_field_configurations"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/fieldconfiguration", query = {"startAt", "maxResults", "id", "isDefault", "query"} },
    ["jira.get_all_gadgets"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/dashboard/{dashboardId}/gadget", path = {"dashboardId"}, query = {"moduleKey", "uri", "gadgetId"} },
    ["jira.get_all_issue_field_options"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldKey}/option", path = {"fieldKey"}, query = {"startAt", "maxResults"} },
    ["jira.get_all_issue_type_schemes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetypescheme", query = {"startAt", "maxResults", "id", "orderBy", "expand", "queryString"} },
    ["jira.get_all_labels"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/label", query = {"startAt", "maxResults"} },
    ["jira.get_all_permission_schemes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/permissionscheme", query = {"expand"} },
    ["jira.get_all_permissions"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/permissions" },
    ["jira.get_all_project_avatars"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/avatars", path = {"projectIdOrKey"} },
    ["jira.get_all_project_categories"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/projectCategory" },
    ["jira.get_all_project_roles"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/role" },
    ["jira.get_all_project_types"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/type" },
    ["jira.get_all_screen_tab_fields"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs/{tabId}/fields", path = {"screenId", "tabId"}, query = {"projectKey"} },
    ["jira.get_all_screen_tabs"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs", path = {"screenId"}, query = {"projectKey"} },
    ["jira.get_all_statuses"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/statuses", path = {"projectIdOrKey"} },
    ["jira.get_all_system_avatars"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/avatar/{type}/system", path = {"type"} },
    ["jira.get_all_users"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/users/search", query = {"startAt", "maxResults"} },
    ["jira.get_all_users_default"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/users", query = {"startAt", "maxResults"} },
    ["jira.get_all_workflow_schemes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme", query = {"startAt", "maxResults"} },
    ["jira.get_alternative_issue_types"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetype/{id}/alternatives", path = {"id"} },
    ["jira.get_application_property"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/application-properties", query = {"permissionLevel", "keyFilter"} },
    ["jira.get_application_role"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/applicationrole/{key}" },
    ["jira.get_approximate_application_license_count"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/license/approximateLicenseCount/product/{applicationKey}", path = {"applicationKey"} },
    ["jira.get_approximate_license_count"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/license/approximateLicenseCount" },
    ["jira.get_assigned_permission_scheme"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectKeyOrId}/permissionscheme", path = {"projectKeyOrId"}, query = {"expand"} },
    ["jira.get_attachment"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/attachment/{id}", path = {"id"} },
    ["jira.get_attachment_content"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/attachment/content/{id}", path = {"id"}, query = {"redirect"} },
    ["jira.get_attachment_meta"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/attachment/meta" },
    ["jira.get_attachment_thumbnail"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/attachment/thumbnail/{id}", path = {"id"}, query = {"redirect", "fallbackToDefault", "width", "height"} },
    ["jira.get_audit_records"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/auditing/record", query = {"offset", "limit", "filter", "from", "to"} },
    ["jira.get_auto_complete"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/jql/autocompletedata" },
    ["jira.get_auto_complete_post"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/jql/autocompletedata", body = {"includeCollapsedFields", "projectIds"} },
    ["jira.get_available_screen_fields"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/availableFields", path = {"screenId"} },
    ["jira.get_available_time_tracking_implementations"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/configuration/timetracking/list" },
    ["jira.get_avatar_image_by_id"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/universal_avatar/view/type/{type}/avatar/{id}", path = {"type", "id"}, query = {"size", "format"} },
    ["jira.get_avatar_image_by_owner"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/universal_avatar/view/type/{type}/owner/{entityId}", path = {"type", "entityId"}, query = {"size", "format"} },
    ["jira.get_avatar_image_by_type"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/universal_avatar/view/type/{type}", path = {"type"}, query = {"size", "format"} },
    ["jira.get_avatars"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/universal_avatar/type/{type}/owner/{entityId}", path = {"type", "entityId"} },
    ["jira.get_banner"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/announcementBanner" },
    ["jira.get_bulk_permissions"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/permissions/check", body = {"accountId", "globalPermissions", "projectPermissions"} },
    ["jira.get_change_logs"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/changelog", path = {"issueIdOrKey"}, query = {"startAt", "maxResults"} },
    ["jira.get_change_logs_by_ids"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/changelog/list", path = {"issueIdOrKey"}, body = {"changelogIds"} },
    ["jira.get_columns"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/filter/{id}/columns", path = {"id"} },
    ["jira.get_comment"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/comment/{id}", path = {"issueIdOrKey", "id"}, query = {"expand"} },
    ["jira.get_comment_property"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/comment/{commentId}/properties/{propertyKey}", path = {"commentId", "propertyKey"} },
    ["jira.get_comment_property_keys"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/comment/{commentId}/properties", path = {"commentId"} },
    ["jira.get_comments"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/comment", path = {"issueIdOrKey"}, query = {"startAt", "maxResults", "orderBy", "expand"} },
    ["jira.get_comments_by_ids"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/comment/list", query = {"expand"}, body = {"ids"} },
    ["jira.get_component"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/component/{id}", path = {"id"} },
    ["jira.get_component_related_issues"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/component/{id}/relatedIssueCounts", path = {"id"} },
    ["jira.get_configuration"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/configuration" },
    ["jira.get_contexts_for_field"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context", path = {"fieldId"}, query = {"isAnyIssueType", "isGlobalContext", "contextId", "startAt", "maxResults"} },
    ["jira.get_create_issue_meta"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/createmeta", query = {"projectIds", "projectKeys", "issuetypeIds", "issuetypeNames", "expand"} },
    ["jira.get_current_user"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/myself", query = {"expand"} },
    ["jira.get_custom_field_configuration"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/app/field/{fieldIdOrKey}/context/configuration", path = {"fieldIdOrKey"}, query = {"id", "fieldContextId", "issueId", "projectKeyOrId", "issueTypeId", "startAt", "maxResults"} },
    ["jira.get_custom_field_contexts_for_projects_and_issue_types"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/mapping", path = {"fieldId"}, query = {"startAt", "maxResults"}, body = {"mappings"} },
    ["jira.get_custom_field_option"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/customFieldOption/{id}", path = {"id"} },
    ["jira.get_dashboard"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/dashboard/{id}", path = {"id"} },
    ["jira.get_dashboard_item_property"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}", path = {"dashboardId", "itemId", "propertyKey"} },
    ["jira.get_dashboard_item_property_keys"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties", path = {"dashboardId", "itemId"} },
    ["jira.get_dashboards_paginated"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/dashboard/search", query = {"dashboardName", "accountId", "owner", "groupname", "groupId", "projectId", "orderBy", "startAt", "maxResults", "status", "expand"} },
    ["jira.get_default_share_scope"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/filter/defaultShareScope" },
    ["jira.get_default_values"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/defaultValue", path = {"fieldId"}, query = {"contextId", "startAt", "maxResults"} },
    ["jira.get_default_workflow"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/default", path = {"id"}, query = {"returnDraftIfExists"} },
    ["jira.get_draft_default_workflow"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/default", path = {"id"} },
    ["jira.get_draft_workflow"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/workflow", path = {"id"}, query = {"workflowName"} },
    ["jira.get_dynamic_webhooks_for_app"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/webhook", query = {"startAt", "maxResults"} },
    ["jira.get_edit_issue_meta"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/editmeta", path = {"issueIdOrKey"}, query = {"overrideScreenSecurity", "overrideEditableFlag"} },
    ["jira.get_events"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/events" },
    ["jira.get_failed_webhooks"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/webhook/failed", query = {"maxResults", "after"} },
    ["jira.get_favourite_filters"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/filter/favourite", query = {"expand"} },
    ["jira.get_features_for_project"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/features", path = {"projectIdOrKey"} },
    ["jira.get_field_auto_complete_for_query_string"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/jql/autocompletedata/suggestions", query = {"fieldName", "fieldValue", "predicateName", "predicateValue"} },
    ["jira.get_field_configuration_items"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/fieldconfiguration/{id}/fields", path = {"id"}, query = {"startAt", "maxResults"} },
    ["jira.get_field_configuration_scheme_mappings"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme/mapping", query = {"startAt", "maxResults", "fieldConfigurationSchemeId"} },
    ["jira.get_field_configuration_scheme_project_mapping"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme/project", query = {"startAt", "maxResults", "projectId"} },
    ["jira.get_fields"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field" },
    ["jira.get_fields_paginated"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/search", query = {"startAt", "maxResults", "type", "id", "query", "orderBy", "expand"} },
    ["jira.get_filter"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/filter/{id}", path = {"id"}, query = {"expand", "overrideSharePermissions"} },
    ["jira.get_filters_paginated"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/filter/search", query = {"filterName", "accountId", "owner", "groupname", "groupId", "projectId", "id", "orderBy", "startAt", "maxResults", "expand", "overrideSharePermissions"} },
    ["jira.get_ids_of_worklogs_deleted_since"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/worklog/deleted", query = {"since"} },
    ["jira.get_ids_of_worklogs_modified_since"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/worklog/updated", query = {"since", "expand"} },
    ["jira.get_is_watching_issue_bulk"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/watching", body = {"issueIds"} },
    ["jira.get_issue"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}", path = {"issueIdOrKey"}, query = {"fields", "fieldsByKeys", "expand", "properties", "updateHistory"} },
    ["jira.get_issue_all_types"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetype" },
    ["jira.get_issue_field_option"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldKey}/option/{optionId}", path = {"fieldKey", "optionId"} },
    ["jira.get_issue_link"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issueLink/{linkId}", path = {"linkId"} },
    ["jira.get_issue_link_type"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issueLinkType/{issueLinkTypeId}", path = {"issueLinkTypeId"} },
    ["jira.get_issue_link_types"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issueLinkType" },
    ["jira.get_issue_navigator_default_columns"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/settings/columns" },
    ["jira.get_issue_picker_resource"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/picker", query = {"query", "currentJQL", "currentIssueKey", "currentProjectId", "showSubTasks", "showSubTaskParent"} },
    ["jira.get_issue_property"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/properties/{propertyKey}", path = {"issueIdOrKey", "propertyKey"} },
    ["jira.get_issue_property_keys"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/properties", path = {"issueIdOrKey"} },
    ["jira.get_issue_security_level"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/securitylevel/{id}", path = {"id"} },
    ["jira.get_issue_security_level_members"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuesecurityschemes/{issueSecuritySchemeId}/members", path = {"issueSecuritySchemeId"}, query = {"startAt", "maxResults", "issueSecurityLevelId", "expand"} },
    ["jira.get_issue_security_scheme"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuesecurityschemes/{id}", path = {"id"} },
    ["jira.get_issue_security_schemes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuesecurityschemes" },
    ["jira.get_issue_type"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetype/{id}", path = {"id"} },
    ["jira.get_issue_type_mappings_for_contexts"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/issuetypemapping", path = {"fieldId"}, query = {"contextId", "startAt", "maxResults"} },
    ["jira.get_issue_type_property"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetype/{issueTypeId}/properties/{propertyKey}", path = {"issueTypeId", "propertyKey"} },
    ["jira.get_issue_type_property_keys"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetype/{issueTypeId}/properties", path = {"issueTypeId"} },
    ["jira.get_issue_type_scheme_for_projects"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetypescheme/project", query = {"startAt", "maxResults", "projectId"} },
    ["jira.get_issue_type_schemes_mapping"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetypescheme/mapping", query = {"startAt", "maxResults", "issueTypeSchemeId"} },
    ["jira.get_issue_type_screen_scheme_mappings"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/mapping", query = {"startAt", "maxResults", "issueTypeScreenSchemeId"} },
    ["jira.get_issue_type_screen_scheme_project_associations"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/project", query = {"startAt", "maxResults", "projectId"} },
    ["jira.get_issue_type_screen_schemes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme", query = {"startAt", "maxResults", "id", "queryString", "orderBy", "expand"} },
    ["jira.get_issue_types_for_project"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetype/project", query = {"projectId", "level"} },
    ["jira.get_issue_watchers"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/watchers", path = {"issueIdOrKey"} },
    ["jira.get_issue_worklog"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog", path = {"issueIdOrKey"}, query = {"startAt", "maxResults", "startedAfter", "startedBefore", "expand"} },
    ["jira.get_license"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/instance/license" },
    ["jira.get_locale"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/mypreferences/locale" },
    ["jira.get_my_filters"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/filter/my", query = {"expand", "includeFavourites"} },
    ["jira.get_my_permissions"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/mypermissions", query = {"projectKey", "projectId", "issueKey", "issueId", "permissions", "projectUuid", "projectConfigurationUuid", "commentId"} },
    ["jira.get_notification_scheme"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/notificationscheme/{id}", path = {"id"}, query = {"expand"} },
    ["jira.get_notification_scheme_to_project_mappings"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/notificationscheme/project", query = {"startAt", "maxResults", "notificationSchemeId", "projectId"} },
    ["jira.get_notification_schemes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/notificationscheme", query = {"startAt", "maxResults", "id", "projectId", "onlyDefault", "expand"} },
    ["jira.get_options_for_context"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/option", path = {"fieldId", "contextId"}, query = {"optionId", "onlyOptions", "startAt", "maxResults"} },
    ["jira.get_permission_scheme"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/permissionscheme/{schemeId}", path = {"schemeId"}, query = {"expand"} },
    ["jira.get_permission_scheme_grant"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/permissionscheme/{schemeId}/permission/{permissionId}", path = {"schemeId", "permissionId"}, query = {"expand"} },
    ["jira.get_permission_scheme_grants"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/permissionscheme/{schemeId}/permission", path = {"schemeId"}, query = {"expand"} },
    ["jira.get_permitted_projects"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/permissions/project", body = {"permissions"} },
    ["jira.get_precomputations"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/jql/function/computation", query = {"functionKey", "startAt", "maxResults", "orderBy", "filter"} },
    ["jira.get_preference"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/mypreferences" },
    ["jira.get_priority"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/priority/{id}", path = {"id"} },
    ["jira.get_project"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}", path = {"projectIdOrKey"}, query = {"expand", "properties"} },
    ["jira.get_project_category_by_id"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/projectCategory/{id}", path = {"id"} },
    ["jira.get_project_components"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/components", path = {"projectIdOrKey"} },
    ["jira.get_project_components_paginated"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/component", path = {"projectIdOrKey"}, query = {"startAt", "maxResults", "orderBy", "query"} },
    ["jira.get_project_context_mapping"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/projectmapping", path = {"fieldId"}, query = {"contextId", "startAt", "maxResults"} },
    ["jira.get_project_email"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectId}/email", path = {"projectId"} },
    ["jira.get_project_issue_security_scheme"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectKeyOrId}/issuesecuritylevelscheme", path = {"projectKeyOrId"} },
    ["jira.get_project_property"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/properties/{propertyKey}", path = {"projectIdOrKey", "propertyKey"} },
    ["jira.get_project_property_keys"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/properties", path = {"projectIdOrKey"} },
    ["jira.get_project_role"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/role/{id}", path = {"projectIdOrKey", "id"}, query = {"excludeInactiveUsers"} },
    ["jira.get_project_role_actors_for_role"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/role/{id}/actors", path = {"id"} },
    ["jira.get_project_role_by_id"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/role/{id}", path = {"id"} },
    ["jira.get_project_role_details"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/roledetails", path = {"projectIdOrKey"}, query = {"currentMember", "excludeConnectAddons"} },
    ["jira.get_project_roles"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/role", path = {"projectIdOrKey"} },
    ["jira.get_project_type_by_key"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/type/{projectTypeKey}", path = {"projectTypeKey"} },
    ["jira.get_project_versions"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/versions", path = {"projectIdOrKey"}, query = {"expand"} },
    ["jira.get_project_versions_paginated"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/version", path = {"projectIdOrKey"}, query = {"startAt", "maxResults", "orderBy", "query", "status", "expand"} },
    ["jira.get_projects_for_issue_type_screen_scheme"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}/project", path = {"issueTypeScreenSchemeId"}, query = {"startAt", "maxResults", "query"} },
    ["jira.get_recent"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/recent", query = {"expand", "properties"} },
    ["jira.get_remote_issue_link_by_id"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/remotelink/{linkId}", path = {"issueIdOrKey", "linkId"} },
    ["jira.get_remote_issue_links"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/remotelink", path = {"issueIdOrKey"}, query = {"globalId"} },
    ["jira.get_resolution"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/resolution/{id}", path = {"id"} },
    ["jira.get_screen_schemes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/screenscheme", query = {"startAt", "maxResults", "id", "expand", "queryString", "orderBy"} },
    ["jira.get_screens"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/screens", query = {"startAt", "maxResults", "id", "queryString", "scope", "orderBy"} },
    ["jira.get_screens_for_field"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/screens", path = {"fieldId"}, query = {"startAt", "maxResults", "expand"} },
    ["jira.get_security_levels_for_project"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/{projectKeyOrId}/securitylevel", path = {"projectKeyOrId"} },
    ["jira.get_selectable_issue_field_options"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldKey}/option/suggestions/edit", path = {"fieldKey"}, query = {"startAt", "maxResults", "projectId"} },
    ["jira.get_selected_time_tracking_implementation"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/configuration/timetracking" },
    ["jira.get_server_info"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/serverInfo" },
    ["jira.get_share_permission"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/filter/{id}/permission/{permissionId}", path = {"id", "permissionId"} },
    ["jira.get_share_permissions"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/filter/{id}/permission", path = {"id"} },
    ["jira.get_shared_time_tracking_configuration"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/configuration/timetracking/options" },
    ["jira.get_status"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/status/{idOrName}", path = {"idOrName"} },
    ["jira.get_status_categories"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/statuscategory" },
    ["jira.get_status_category"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/statuscategory/{idOrKey}", path = {"idOrKey"} },
    ["jira.get_statuses"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/status" },
    ["jira.get_statuses_by_id"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/statuses", query = {"expand", "id"} },
    ["jira.get_task"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/task/{taskId}", path = {"taskId"} },
    ["jira.get_transitions"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/transitions", path = {"issueIdOrKey"}, query = {"expand", "transitionId", "skipRemoteOnlyCondition", "includeUnavailableTransitions", "sortByOpsBarAndStatus"} },
    ["jira.get_trashed_fields_paginated"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/search/trashed", query = {"startAt", "maxResults", "id", "query", "expand", "orderBy"} },
    ["jira.get_ui_modifications"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/uiModifications", query = {"startAt", "maxResults", "expand"} },
    ["jira.get_user"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user", query = {"accountId", "username", "expand"} },
    ["jira.get_user_default_columns"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/columns", query = {"accountId", "username"} },
    ["jira.get_user_email"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/email", query = {"accountId"} },
    ["jira.get_user_email_bulk"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/email/bulk", query = {"accountId"} },
    ["jira.get_user_groups"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/groups", query = {"accountId", "username"} },
    ["jira.get_user_property"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/properties/{propertyKey}", path = {"propertyKey"}, query = {"accountId", "userKey", "username"} },
    ["jira.get_user_property_keys"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/user/properties", query = {"accountId", "userKey", "username"} },
    ["jira.get_users_from_group"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/group/member", query = {"groupname", "groupId", "includeInactiveUsers", "startAt", "maxResults"} },
    ["jira.get_valid_project_key"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/projectvalidate/validProjectKey" },
    ["jira.get_valid_project_name"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/projectvalidate/validProjectName", query = {"name"} },
    ["jira.get_version"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/version/{id}", path = {"id"}, query = {"expand"} },
    ["jira.get_version_related_issues"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/version/{id}/relatedIssueCounts", path = {"id"} },
    ["jira.get_version_unresolved_issues"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/version/{id}/unresolvedIssueCount", path = {"id"} },
    ["jira.get_visible_issue_field_options"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/field/{fieldKey}/option/suggestions/search", path = {"fieldKey"}, query = {"startAt", "maxResults", "projectId"} },
    ["jira.get_votes"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/votes", path = {"issueIdOrKey"} },
    ["jira.get_workflow"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/workflow", path = {"id"}, query = {"workflowName", "returnDraftIfExists"} },
    ["jira.get_workflow_scheme"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}", path = {"id"}, query = {"returnDraftIfExists"} },
    ["jira.get_workflow_scheme_draft"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft", path = {"id"} },
    ["jira.get_workflow_scheme_draft_issue_type"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/issuetype/{issueType}", path = {"id", "issueType"} },
    ["jira.get_workflow_scheme_issue_type"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/issuetype/{issueType}", path = {"id", "issueType"}, query = {"returnDraftIfExists"} },
    ["jira.get_workflow_scheme_project_associations"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflowscheme/project", query = {"projectId"} },
    ["jira.get_workflow_transition_properties"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflow/transitions/{transitionId}/properties", path = {"transitionId"}, query = {"includeReservedKeys", "workflowName", "workflowMode"} },
    ["jira.get_workflow_transition_rule_configurations"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflow/rule/config", query = {"startAt", "maxResults", "types", "keys", "workflowNames", "withTags", "draft", "expand"} },
    ["jira.get_workflows_paginated"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/workflow/search", query = {"startAt", "maxResults", "workflowName", "expand", "queryString", "orderBy", "isActive"} },
    ["jira.get_worklog"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog/{id}", path = {"issueIdOrKey", "id"}, query = {"expand"} },
    ["jira.get_worklog_property"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}", path = {"issueIdOrKey", "worklogId", "propertyKey"} },
    ["jira.get_worklog_property_keys"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties", path = {"issueIdOrKey", "worklogId"} },
    ["jira.get_worklogs_for_ids"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/worklog/list", query = {"expand"}, body = {"ids"} },
    ["jira.link_issues"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issueLink", body = {"comment", "inwardIssue", "outwardIssue", "type"} },
    ["jira.match_issues"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/jql/match", body = {"issueIds", "jqls"} },
    ["jira.merge_versions"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/version/{id}/mergeto/{moveIssuesTo}", path = {"id", "moveIssuesTo"} },
    ["jira.migrate_queries"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/jql/pdcleaner", body = {"queryStrings"} },
    ["jira.migration_resource_update_entity_properties_value_put"] = { method = "PUT", url = "https://api.atlassian.com/rest/atlassian-connect/1/migration/properties/{entityType}", path = {"entityType"}, header = {"Atlassian-Transfer-Id"} },
    ["jira.migration_resource_workflow_rule_search_post"] = { method = "POST", url = "https://api.atlassian.com/rest/atlassian-connect/1/migration/workflow/rule/search", header = {"Atlassian-Transfer-Id"}, body = {"expand", "ruleIds", "workflowEntityId"} },
    ["jira.move_priorities"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/priority/move", body = {"after", "ids", "position"} },
    ["jira.move_resolutions"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/resolution/move", body = {"after", "ids", "position"} },
    ["jira.move_screen_tab"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs/{tabId}/move/{pos}", path = {"screenId", "tabId", "pos"} },
    ["jira.move_screen_tab_field"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs/{tabId}/fields/{id}/move", path = {"screenId", "tabId", "id"}, body = {"after", "position"} },
    ["jira.move_version"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/version/{id}/move", path = {"id"}, body = {"after", "position"} },
    ["jira.notify"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/notify", path = {"issueIdOrKey"}, body = {"htmlBody", "restrict", "subject", "textBody", "to"} },
    ["jira.parse_jql_queries"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/jql/parse", query = {"validation"}, body = {"queries"} },
    ["jira.partial_update_project_role"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/role/{id}", path = {"id"}, body = {"description", "name"} },
    ["jira.publish_draft_workflow_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/publish", path = {"id"}, query = {"validateOnly"}, body = {"statusMappings"} },
    ["jira.refresh_webhooks"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/webhook/refresh", body = {"webhookIds"} },
    ["jira.register_dynamic_webhooks"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/webhook", body = {"url", "webhooks"} },
    ["jira.remove_attachment"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/attachment/{id}", path = {"id"} },
    ["jira.remove_custom_field_context_from_projects"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/project/remove", path = {"fieldId", "contextId"}, body = {"projectIds"} },
    ["jira.remove_gadget"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/dashboard/{dashboardId}/gadget/{gadgetId}", path = {"dashboardId", "gadgetId"} },
    ["jira.remove_group"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/group", query = {"groupname", "groupId", "swapGroup", "swapGroupId"} },
    ["jira.remove_issue_type_from_issue_type_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issuetypescheme/{issueTypeSchemeId}/issuetype/{issueTypeId}", path = {"issueTypeSchemeId", "issueTypeId"} },
    ["jira.remove_issue_types_from_context"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/issuetype/remove", path = {"fieldId", "contextId"}, body = {"issueTypeIds"} },
    ["jira.remove_issue_types_from_global_field_configuration_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme/{id}/mapping/delete", path = {"id"}, body = {"issueTypeIds"} },
    ["jira.remove_mappings_from_issue_type_screen_scheme"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping/remove", path = {"issueTypeScreenSchemeId"}, body = {"issueTypeIds"} },
    ["jira.remove_notification_from_notification_scheme"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/notificationscheme/{notificationSchemeId}/notification/{notificationId}", path = {"notificationSchemeId", "notificationId"} },
    ["jira.remove_preference"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/mypreferences" },
    ["jira.remove_project_category"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/projectCategory/{id}", path = {"id"} },
    ["jira.remove_screen_tab_field"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs/{tabId}/fields/{id}", path = {"screenId", "tabId", "id"} },
    ["jira.remove_user"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/user", query = {"accountId", "username"} },
    ["jira.remove_user_from_group"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/group/user", query = {"groupname", "groupId", "username", "accountId"} },
    ["jira.remove_vote"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/votes", path = {"issueIdOrKey"} },
    ["jira.remove_watcher"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/watchers", path = {"issueIdOrKey"}, query = {"username", "accountId"} },
    ["jira.rename_screen_tab"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}/tabs/{tabId}", path = {"screenId", "tabId"}, body = {"id", "name"} },
    ["jira.reorder_custom_field_options"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/option/move", path = {"fieldId", "contextId"}, body = {"after", "customFieldOptionIds", "position"} },
    ["jira.reorder_issue_types_in_issue_type_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetypescheme/{issueTypeSchemeId}/issuetype/move", path = {"issueTypeSchemeId"}, body = {"after", "issueTypeIds", "position"} },
    ["jira.replace_issue_field_option"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/field/{fieldKey}/option/{optionId}/issue", path = {"fieldKey", "optionId"}, query = {"replaceWith", "jql", "overrideScreenSecurity", "overrideEditableFlag"} },
    ["jira.reset_columns"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/filter/{id}/columns", path = {"id"} },
    ["jira.reset_user_columns"] = { method = "DELETE", url = "https://api.atlassian.com/rest/api/3/user/columns", query = {"accountId", "username"} },
    ["jira.restore"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/restore", path = {"projectIdOrKey"} },
    ["jira.restore_custom_field"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field/{id}/restore", path = {"id"} },
    ["jira.sanitise_jql_queries"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/jql/sanitize", body = {"queries"} },
    ["jira.search"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/statuses/search", query = {"expand", "projectId", "startAt", "maxResults", "searchString", "statusCategory"} },
    ["jira.search_for_issues_using_jql"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/search", query = {"jql", "startAt", "maxResults", "validateQuery", "fields", "expand", "properties", "fieldsByKeys"} },
    ["jira.search_for_issues_using_jql_post"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/search", body = {"expand", "fields", "fieldsByKeys", "jql", "maxResults", "properties", "startAt", "validateQuery"} },
    ["jira.search_priorities"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/priority/search", query = {"startAt", "maxResults", "id", "onlyDefault"} },
    ["jira.search_projects"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/project/search", query = {"startAt", "maxResults", "orderBy", "id", "keys", "query", "typeKey", "categoryId", "action", "expand", "status", "properties", "propertyQuery"} },
    ["jira.search_resolutions"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/resolution/search", query = {"startAt", "maxResults", "id", "onlyDefault"} },
    ["jira.select_time_tracking_implementation"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/configuration/timetracking", body = {"name", "url"} },
    ["jira.set_actors"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/role/{id}", path = {"projectIdOrKey", "id"}, body = {"categorisedActors", "id"} },
    ["jira.set_application_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/application-properties/{id}", path = {"id"}, body = {"id", "value"} },
    ["jira.set_banner"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/announcementBanner", body = {"isDismissible", "isEnabled", "message", "visibility"} },
    ["jira.set_columns"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/filter/{id}/columns", path = {"id"} },
    ["jira.set_comment_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/comment/{commentId}/properties/{propertyKey}", path = {"commentId", "propertyKey"} },
    ["jira.set_dashboard_item_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}", path = {"dashboardId", "itemId", "propertyKey"} },
    ["jira.set_default_priority"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/priority/default", body = {"id"} },
    ["jira.set_default_resolution"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/resolution/default", body = {"id"} },
    ["jira.set_default_share_scope"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/filter/defaultShareScope", body = {"scope"} },
    ["jira.set_default_values"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/defaultValue", path = {"fieldId"}, body = {"defaultValues"} },
    ["jira.set_favourite_for_filter"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/filter/{id}/favourite", path = {"id"}, query = {"expand"} },
    ["jira.set_field_configuration_scheme_mapping"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme/{id}/mapping", path = {"id"}, body = {"mappings"} },
    ["jira.set_issue_navigator_default_columns"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/settings/columns" },
    ["jira.set_issue_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/properties/{propertyKey}", path = {"issueIdOrKey", "propertyKey"} },
    ["jira.set_issue_type_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetype/{issueTypeId}/properties/{propertyKey}", path = {"issueTypeId", "propertyKey"} },
    ["jira.set_preference"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/mypreferences" },
    ["jira.set_project_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/properties/{propertyKey}", path = {"projectIdOrKey", "propertyKey"} },
    ["jira.set_shared_time_tracking_configuration"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/configuration/timetracking/options", body = {"defaultUnit", "timeFormat", "workingDaysPerWeek", "workingHoursPerDay"} },
    ["jira.set_user_columns"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/user/columns", query = {"accountId"} },
    ["jira.set_user_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/user/properties/{propertyKey}", path = {"propertyKey"}, query = {"accountId", "userKey", "username"} },
    ["jira.set_workflow_scheme_draft_issue_type"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/issuetype/{issueType}", path = {"id", "issueType"}, body = {"issueType", "updateDraftIfNeeded", "workflow"} },
    ["jira.set_workflow_scheme_issue_type"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/issuetype/{issueType}", path = {"id", "issueType"}, body = {"issueType", "updateDraftIfNeeded", "workflow"} },
    ["jira.set_worklog_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}", path = {"issueIdOrKey", "worklogId", "propertyKey"} },
    ["jira.store_avatar"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/universal_avatar/type/{type}/owner/{entityId}", path = {"type", "entityId"}, query = {"x", "y", "size"} },
    ["jira.toggle_feature_for_project"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/features/{featureKey}", path = {"projectIdOrKey", "featureKey"}, body = {"state"} },
    ["jira.trash_custom_field"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/field/{id}/trash", path = {"id"} },
    ["jira.update_comment"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/comment/{id}", path = {"issueIdOrKey", "id"}, query = {"notifyUsers", "overrideEditableFlag", "expand"}, body = {"author", "body", "created", "id", "jsdAuthorCanSeeRequest", "jsdPublic", "properties", "renderedBody", "self", "updateAuthor", "updated", "visibility"} },
    ["jira.update_component"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/component/{id}", path = {"id"}, body = {"assignee", "assigneeType", "description", "id", "isAssigneeTypeValid", "lead", "leadAccountId", "leadUserName", "name", "project", "projectId", "realAssignee", "realAssigneeType", "self"} },
    ["jira.update_custom_field"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}", path = {"fieldId"}, body = {"description", "name", "searcherKey"} },
    ["jira.update_custom_field_configuration"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/app/field/{fieldIdOrKey}/context/configuration", path = {"fieldIdOrKey"}, body = {"configurations"} },
    ["jira.update_custom_field_context"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}", path = {"fieldId", "contextId"}, body = {"description", "name"} },
    ["jira.update_custom_field_option"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/field/{fieldId}/context/{contextId}/option", path = {"fieldId", "contextId"}, body = {"options"} },
    ["jira.update_custom_field_value"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/app/field/{fieldIdOrKey}/value", path = {"fieldIdOrKey"}, query = {"generateChangelog"}, body = {"updates"} },
    ["jira.update_dashboard"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/dashboard/{id}", path = {"id"}, body = {"description", "editPermissions", "name", "sharePermissions"} },
    ["jira.update_default_screen_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping/default", path = {"issueTypeScreenSchemeId"}, body = {"screenSchemeId"} },
    ["jira.update_default_workflow"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/default", path = {"id"}, body = {"updateDraftIfNeeded", "workflow"} },
    ["jira.update_draft_default_workflow"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/default", path = {"id"}, body = {"updateDraftIfNeeded", "workflow"} },
    ["jira.update_draft_workflow_mapping"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft/workflow", path = {"id"}, query = {"workflowName"}, body = {"defaultMapping", "issueTypes", "updateDraftIfNeeded", "workflow"} },
    ["jira.update_field_configuration"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/fieldconfiguration/{id}", path = {"id"}, body = {"description", "name"} },
    ["jira.update_field_configuration_items"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/fieldconfiguration/{id}/fields", path = {"id"}, body = {"fieldConfigurationItems"} },
    ["jira.update_field_configuration_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/fieldconfigurationscheme/{id}", path = {"id"}, body = {"description", "name"} },
    ["jira.update_filter"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/filter/{id}", path = {"id"}, query = {"expand", "overrideSharePermissions"}, body = {"description", "editPermissions", "favourite", "favouritedCount", "id", "jql", "name", "owner", "searchUrl", "self", "sharePermissions", "sharedUsers", "subscriptions", "viewUrl"} },
    ["jira.update_gadget"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/dashboard/{dashboardId}/gadget/{gadgetId}", path = {"dashboardId", "gadgetId"}, body = {"color", "position", "title"} },
    ["jira.update_issue_field_option"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/field/{fieldKey}/option/{optionId}", path = {"fieldKey", "optionId"}, body = {"config", "id", "properties", "value"} },
    ["jira.update_issue_link_type"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issueLinkType/{issueLinkTypeId}", path = {"issueLinkTypeId"}, body = {"id", "inward", "name", "outward", "self"} },
    ["jira.update_issue_type"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetype/{id}", path = {"id"}, body = {"avatarId", "description", "name"} },
    ["jira.update_issue_type_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetypescheme/{issueTypeSchemeId}", path = {"issueTypeSchemeId"}, body = {"defaultIssueTypeId", "description", "name"} },
    ["jira.update_issue_type_screen_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}", path = {"issueTypeScreenSchemeId"}, body = {"description", "name"} },
    ["jira.update_multiple_custom_field_values"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/app/field/value", query = {"generateChangelog"}, body = {"updates"} },
    ["jira.update_notification_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/notificationscheme/{id}", path = {"id"}, body = {"description", "name"} },
    ["jira.update_permission_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/permissionscheme/{schemeId}", path = {"schemeId"}, query = {"expand"}, body = {"description", "expand", "id", "name", "permissions", "scope", "self"} },
    ["jira.update_precomputations"] = { method = "POST", url = "https://api.atlassian.com/rest/api/3/jql/function/computation", body = {"values"} },
    ["jira.update_priority"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/priority/{id}", path = {"id"}, body = {"description", "iconUrl", "name", "statusColor"} },
    ["jira.update_project"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}", path = {"projectIdOrKey"}, query = {"expand"}, body = {"assigneeType", "avatarId", "categoryId", "description", "issueSecurityScheme", "lead", "leadAccountId", "name", "notificationScheme", "permissionScheme", "url"} },
    ["jira.update_project_avatar"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/project/{projectIdOrKey}/avatar", path = {"projectIdOrKey"}, body = {"fileName", "id", "isDeletable", "isSelected", "isSystemAvatar", "owner", "urls"} },
    ["jira.update_project_category"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/projectCategory/{id}", path = {"id"}, body = {"description", "id", "name", "self"} },
    ["jira.update_project_email"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/project/{projectId}/email", path = {"projectId"}, body = {"emailAddress", "emailAddressStatus"} },
    ["jira.update_remote_issue_link"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/remotelink/{linkId}", path = {"issueIdOrKey", "linkId"}, body = {"application", "globalId", "object", "relationship"} },
    ["jira.update_resolution"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/resolution/{id}", path = {"id"}, body = {"description", "name"} },
    ["jira.update_screen"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/screens/{screenId}", path = {"screenId"}, body = {"description", "name"} },
    ["jira.update_screen_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/screenscheme/{screenSchemeId}", path = {"screenSchemeId"}, body = {"description", "name", "screens"} },
    ["jira.update_statuses"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/statuses", body = {"statuses"} },
    ["jira.update_ui_modification"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/uiModifications/{uiModificationId}", path = {"uiModificationId"}, body = {"contexts", "data", "description", "name"} },
    ["jira.update_version"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/version/{id}", path = {"id"}, body = {"archived", "description", "expand", "id", "issuesStatusForFixVersion", "moveUnfixedIssuesTo", "name", "operations", "overdue", "project", "projectId", "releaseDate", "released", "self", "startDate", "userReleaseDate", "userStartDate"} },
    ["jira.update_workflow_mapping"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/workflow", path = {"id"}, query = {"workflowName"}, body = {"defaultMapping", "issueTypes", "updateDraftIfNeeded", "workflow"} },
    ["jira.update_workflow_scheme"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}", path = {"id"}, body = {"defaultWorkflow", "description", "draft", "id", "issueTypeMappings", "issueTypes", "lastModified", "lastModifiedUser", "name", "originalDefaultWorkflow", "originalIssueTypeMappings", "self", "updateDraftIfNeeded"} },
    ["jira.update_workflow_scheme_draft"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflowscheme/{id}/draft", path = {"id"}, body = {"defaultWorkflow", "description", "draft", "id", "issueTypeMappings", "issueTypes", "lastModified", "lastModifiedUser", "name", "originalDefaultWorkflow", "originalIssueTypeMappings", "self", "updateDraftIfNeeded"} },
    ["jira.update_workflow_transition_property"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflow/transitions/{transitionId}/properties", path = {"transitionId"}, query = {"workflowName", "workflowMode"}, body = {"id", "value"} },
    ["jira.update_workflow_transition_rule_configurations"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/workflow/rule/config", body = {"workflows"} },
    ["jira.update_worklog"] = { method = "PUT", url = "https://api.atlassian.com/rest/api/3/issue/{issueIdOrKey}/worklog/{id}", path = {"issueIdOrKey", "id"}, query = {"notifyUsers", "adjustEstimate", "newEstimate", "expand", "overrideEditableFlag"}, body = {"author", "comment", "created", "id", "issueId", "properties", "self", "started", "timeSpent", "timeSpentSeconds", "updateAuthor", "updated", "visibility"} },
    ["jira.validate_project_key"] = { method = "GET", url = "https://api.atlassian.com/rest/api/3/projectvalidate/key" },
  },
}
