-- Box — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/box/box-openapi/main/openapi.json
-- Published by box, the vendor's own GitHub organisation.
-- 295 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "box",
  name = "Box",
  base = "https://api.box.com",
  docs = "https://nango.dev/docs/api-integrations/box",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "BOX_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["box.delete_ai_agents_id"] = { method = "DELETE", url = "https://api.box.com/ai_agents/{agent_id}", path = {"agent_id"} },
    ["box.delete_collaboration_whitelist_entries_id"] = { method = "DELETE", url = "https://api.box.com/collaboration_whitelist_entries/{collaboration_whitelist_entry_id}", path = {"collaboration_whitelist_entry_id"} },
    ["box.delete_collaboration_whitelist_exempt_targets_id"] = { method = "DELETE", url = "https://api.box.com/collaboration_whitelist_exempt_targets/{collaboration_whitelist_exempt_target_id}", path = {"collaboration_whitelist_exempt_target_id"} },
    ["box.delete_collaborations_id"] = { method = "DELETE", url = "https://api.box.com/collaborations/{collaboration_id}", path = {"collaboration_id"} },
    ["box.delete_comments_id"] = { method = "DELETE", url = "https://api.box.com/comments/{comment_id}", path = {"comment_id"} },
    ["box.delete_device_pinners_id"] = { method = "DELETE", url = "https://api.box.com/device_pinners/{device_pinner_id}", path = {"device_pinner_id"} },
    ["box.delete_file_requests_id"] = { method = "DELETE", url = "https://api.box.com/file_requests/{file_request_id}", path = {"file_request_id"} },
    ["box.delete_files_id"] = { method = "DELETE", url = "https://api.box.com/files/{file_id}", path = {"file_id"}, header = {"if-match"} },
    ["box.delete_files_id_metadata_enterprise_security_classification_6_vmvochw_uwo"] = { method = "DELETE", url = "https://api.box.com/files/{file_id}/metadata/enterprise/securityClassification-6VMVochwUWo", path = {"file_id"} },
    ["box.delete_files_id_metadata_global_box_skills_cards"] = { method = "DELETE", url = "https://api.box.com/files/{file_id}/metadata/global/boxSkillsCards", path = {"file_id"} },
    ["box.delete_files_id_metadata_id_id"] = { method = "DELETE", url = "https://api.box.com/files/{file_id}/metadata/{scope}/{template_key}", path = {"file_id", "scope", "template_key"} },
    ["box.delete_files_id_trash"] = { method = "DELETE", url = "https://api.box.com/files/{file_id}/trash", path = {"file_id"} },
    ["box.delete_files_id_versions_id"] = { method = "DELETE", url = "https://api.box.com/files/{file_id}/versions/{file_version_id}", path = {"file_id", "file_version_id"}, header = {"if-match"} },
    ["box.delete_files_id_watermark"] = { method = "DELETE", url = "https://api.box.com/files/{file_id}/watermark", path = {"file_id"} },
    ["box.delete_files_upload_sessions_id"] = { method = "DELETE", url = "https://api.box.com/files/upload_sessions/{upload_session_id}", path = {"upload_session_id"} },
    ["box.delete_folder_locks_id"] = { method = "DELETE", url = "https://api.box.com/folder_locks/{folder_lock_id}", path = {"folder_lock_id"} },
    ["box.delete_folders_id"] = { method = "DELETE", url = "https://api.box.com/folders/{folder_id}", path = {"folder_id"}, query = {"recursive"}, header = {"if-match"} },
    ["box.delete_folders_id_metadata_enterprise_security_classification_6_vmvochw_uwo"] = { method = "DELETE", url = "https://api.box.com/folders/{folder_id}/metadata/enterprise/securityClassification-6VMVochwUWo", path = {"folder_id"} },
    ["box.delete_folders_id_metadata_id_id"] = { method = "DELETE", url = "https://api.box.com/folders/{folder_id}/metadata/{scope}/{template_key}", path = {"folder_id", "scope", "template_key"} },
    ["box.delete_folders_id_trash"] = { method = "DELETE", url = "https://api.box.com/folders/{folder_id}/trash", path = {"folder_id"} },
    ["box.delete_folders_id_watermark"] = { method = "DELETE", url = "https://api.box.com/folders/{folder_id}/watermark", path = {"folder_id"} },
    ["box.delete_group_memberships_id"] = { method = "DELETE", url = "https://api.box.com/group_memberships/{group_membership_id}", path = {"group_membership_id"} },
    ["box.delete_groups_id"] = { method = "DELETE", url = "https://api.box.com/groups/{group_id}", path = {"group_id"} },
    ["box.delete_integration_mappings_slack_id"] = { method = "DELETE", url = "https://api.box.com/integration_mappings/slack/{integration_mapping_id}", path = {"integration_mapping_id"} },
    ["box.delete_integration_mappings_teams_id"] = { method = "DELETE", url = "https://api.box.com/integration_mappings/teams/{integration_mapping_id}", path = {"integration_mapping_id"} },
    ["box.delete_legal_hold_policies_id"] = { method = "DELETE", url = "https://api.box.com/legal_hold_policies/{legal_hold_policy_id}", path = {"legal_hold_policy_id"} },
    ["box.delete_legal_hold_policy_assignments_id"] = { method = "DELETE", url = "https://api.box.com/legal_hold_policy_assignments/{legal_hold_policy_assignment_id}", path = {"legal_hold_policy_assignment_id"} },
    ["box.delete_metadata_cascade_policies_id"] = { method = "DELETE", url = "https://api.box.com/metadata_cascade_policies/{metadata_cascade_policy_id}", path = {"metadata_cascade_policy_id"} },
    ["box.delete_metadata_taxonomies_id_id"] = { method = "DELETE", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}", path = {"namespace", "taxonomy_key"} },
    ["box.delete_metadata_taxonomies_id_id_nodes_id"] = { method = "DELETE", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/nodes/{node_id}", path = {"namespace", "taxonomy_key", "node_id"} },
    ["box.delete_metadata_templates_id_id_schema"] = { method = "DELETE", url = "https://api.box.com/metadata_templates/{scope}/{template_key}/schema", path = {"scope", "template_key"} },
    ["box.delete_retention_policies_id"] = { method = "DELETE", url = "https://api.box.com/retention_policies/{retention_policy_id}", path = {"retention_policy_id"} },
    ["box.delete_retention_policy_assignments_id"] = { method = "DELETE", url = "https://api.box.com/retention_policy_assignments/{retention_policy_assignment_id}", path = {"retention_policy_assignment_id"} },
    ["box.delete_shield_information_barrier_segment_members_id"] = { method = "DELETE", url = "https://api.box.com/shield_information_barrier_segment_members/{shield_information_barrier_segment_member_id}", path = {"shield_information_barrier_segment_member_id"} },
    ["box.delete_shield_information_barrier_segment_restrictions_id"] = { method = "DELETE", url = "https://api.box.com/shield_information_barrier_segment_restrictions/{shield_information_barrier_segment_restriction_id}", path = {"shield_information_barrier_segment_restriction_id"} },
    ["box.delete_shield_information_barrier_segments_id"] = { method = "DELETE", url = "https://api.box.com/shield_information_barrier_segments/{shield_information_barrier_segment_id}", path = {"shield_information_barrier_segment_id"} },
    ["box.delete_storage_policy_assignments_id"] = { method = "DELETE", url = "https://api.box.com/storage_policy_assignments/{storage_policy_assignment_id}", path = {"storage_policy_assignment_id"} },
    ["box.delete_task_assignments_id"] = { method = "DELETE", url = "https://api.box.com/task_assignments/{task_assignment_id}", path = {"task_assignment_id"} },
    ["box.delete_tasks_id"] = { method = "DELETE", url = "https://api.box.com/tasks/{task_id}", path = {"task_id"} },
    ["box.delete_users_id"] = { method = "DELETE", url = "https://api.box.com/users/{user_id}", path = {"user_id"}, query = {"notify", "force"} },
    ["box.delete_users_id_avatar"] = { method = "DELETE", url = "https://api.box.com/users/{user_id}/avatar", path = {"user_id"} },
    ["box.delete_users_id_email_aliases_id"] = { method = "DELETE", url = "https://api.box.com/users/{user_id}/email_aliases/{email_alias_id}", path = {"user_id", "email_alias_id"} },
    ["box.delete_web_links_id"] = { method = "DELETE", url = "https://api.box.com/web_links/{web_link_id}", path = {"web_link_id"} },
    ["box.delete_web_links_id_trash"] = { method = "DELETE", url = "https://api.box.com/web_links/{web_link_id}/trash", path = {"web_link_id"} },
    ["box.delete_webhooks_id"] = { method = "DELETE", url = "https://api.box.com/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["box.get_ai_agent_default"] = { method = "GET", url = "https://api.box.com/ai_agent_default", query = {"mode", "language", "model"} },
    ["box.get_ai_agents"] = { method = "GET", url = "https://api.box.com/ai_agents", query = {"mode", "fields", "agent_state", "include_box_default", "marker", "limit"} },
    ["box.get_ai_agents_id"] = { method = "GET", url = "https://api.box.com/ai_agents/{agent_id}", path = {"agent_id"}, query = {"fields"} },
    ["box.get_authorize"] = { method = "GET", url = "https://api.box.com/authorize", query = {"response_type", "client_id", "redirect_uri", "state", "scope"} },
    ["box.get_collaboration_whitelist_entries"] = { method = "GET", url = "https://api.box.com/collaboration_whitelist_entries", query = {"marker", "limit"} },
    ["box.get_collaboration_whitelist_entries_id"] = { method = "GET", url = "https://api.box.com/collaboration_whitelist_entries/{collaboration_whitelist_entry_id}", path = {"collaboration_whitelist_entry_id"} },
    ["box.get_collaboration_whitelist_exempt_targets"] = { method = "GET", url = "https://api.box.com/collaboration_whitelist_exempt_targets", query = {"marker", "limit"} },
    ["box.get_collaboration_whitelist_exempt_targets_id"] = { method = "GET", url = "https://api.box.com/collaboration_whitelist_exempt_targets/{collaboration_whitelist_exempt_target_id}", path = {"collaboration_whitelist_exempt_target_id"} },
    ["box.get_collaborations"] = { method = "GET", url = "https://api.box.com/collaborations", query = {"status", "fields", "offset", "limit"} },
    ["box.get_collaborations_id"] = { method = "GET", url = "https://api.box.com/collaborations/{collaboration_id}", path = {"collaboration_id"}, query = {"fields"} },
    ["box.get_collections"] = { method = "GET", url = "https://api.box.com/collections", query = {"fields", "offset", "limit"} },
    ["box.get_collections_id"] = { method = "GET", url = "https://api.box.com/collections/{collection_id}", path = {"collection_id"} },
    ["box.get_collections_id_items"] = { method = "GET", url = "https://api.box.com/collections/{collection_id}/items", path = {"collection_id"}, query = {"fields", "offset", "limit"} },
    ["box.get_comments_id"] = { method = "GET", url = "https://api.box.com/comments/{comment_id}", path = {"comment_id"}, query = {"fields"} },
    ["box.get_device_pinners_id"] = { method = "GET", url = "https://api.box.com/device_pinners/{device_pinner_id}", path = {"device_pinner_id"} },
    ["box.get_enterprises_id_device_pinners"] = { method = "GET", url = "https://api.box.com/enterprises/{enterprise_id}/device_pinners", path = {"enterprise_id"}, query = {"marker", "limit", "direction"} },
    ["box.get_events"] = { method = "GET", url = "https://api.box.com/events", query = {"stream_type", "stream_position", "limit", "event_type", "created_after", "created_before"} },
    ["box.get_file_requests_id"] = { method = "GET", url = "https://api.box.com/file_requests/{file_request_id}", path = {"file_request_id"} },
    ["box.get_file_version_legal_holds"] = { method = "GET", url = "https://api.box.com/file_version_legal_holds", query = {"policy_id", "marker", "limit"} },
    ["box.get_file_version_legal_holds_id"] = { method = "GET", url = "https://api.box.com/file_version_legal_holds/{file_version_legal_hold_id}", path = {"file_version_legal_hold_id"} },
    ["box.get_file_version_retentions"] = { method = "GET", url = "https://api.box.com/file_version_retentions", query = {"file_id", "file_version_id", "policy_id", "disposition_action", "disposition_before", "disposition_after", "limit", "marker"} },
    ["box.get_file_version_retentions_id"] = { method = "GET", url = "https://api.box.com/file_version_retentions/{file_version_retention_id}", path = {"file_version_retention_id"} },
    ["box.get_files_id"] = { method = "GET", url = "https://api.box.com/files/{file_id}", path = {"file_id"}, query = {"fields"}, header = {"if-none-match", "boxapi", "x-rep-hints"} },
    ["box.get_files_id_app_item_associations"] = { method = "GET", url = "https://api.box.com/files/{file_id}/app_item_associations", path = {"file_id"}, query = {"limit", "marker", "application_type"} },
    ["box.get_files_id_collaborations"] = { method = "GET", url = "https://api.box.com/files/{file_id}/collaborations", path = {"file_id"}, query = {"fields", "limit", "marker"} },
    ["box.get_files_id_comments"] = { method = "GET", url = "https://api.box.com/files/{file_id}/comments", path = {"file_id"}, query = {"fields", "limit", "offset"} },
    ["box.get_files_id_content"] = { method = "GET", url = "https://api.box.com/files/{file_id}/content", path = {"file_id"}, query = {"version"}, header = {"range", "boxapi"} },
    ["box.get_files_id_get_shared_link"] = { method = "GET", url = "https://api.box.com/files/{file_id}#get_shared_link", path = {"file_id"}, query = {"fields"} },
    ["box.get_files_id_metadata"] = { method = "GET", url = "https://api.box.com/files/{file_id}/metadata", path = {"file_id"}, query = {"view"} },
    ["box.get_files_id_metadata_enterprise_security_classification_6_vmvochw_uwo"] = { method = "GET", url = "https://api.box.com/files/{file_id}/metadata/enterprise/securityClassification-6VMVochwUWo", path = {"file_id"} },
    ["box.get_files_id_metadata_global_box_skills_cards"] = { method = "GET", url = "https://api.box.com/files/{file_id}/metadata/global/boxSkillsCards", path = {"file_id"} },
    ["box.get_files_id_metadata_id_id"] = { method = "GET", url = "https://api.box.com/files/{file_id}/metadata/{scope}/{template_key}", path = {"file_id", "scope", "template_key"}, query = {"view"} },
    ["box.get_files_id_tasks"] = { method = "GET", url = "https://api.box.com/files/{file_id}/tasks", path = {"file_id"} },
    ["box.get_files_id_thumbnail_id"] = { method = "GET", url = "https://api.box.com/files/{file_id}/thumbnail.{extension}", path = {"file_id", "extension"}, query = {"min_height", "min_width", "max_height", "max_width"} },
    ["box.get_files_id_trash"] = { method = "GET", url = "https://api.box.com/files/{file_id}/trash", path = {"file_id"}, query = {"fields"} },
    ["box.get_files_id_versions"] = { method = "GET", url = "https://api.box.com/files/{file_id}/versions", path = {"file_id"}, query = {"fields", "limit", "offset"} },
    ["box.get_files_id_versions_id"] = { method = "GET", url = "https://api.box.com/files/{file_id}/versions/{file_version_id}", path = {"file_id", "file_version_id"}, query = {"fields"} },
    ["box.get_files_id_watermark"] = { method = "GET", url = "https://api.box.com/files/{file_id}/watermark", path = {"file_id"} },
    ["box.get_files_upload_sessions_id"] = { method = "GET", url = "https://api.box.com/files/upload_sessions/{upload_session_id}", path = {"upload_session_id"} },
    ["box.get_files_upload_sessions_id_parts"] = { method = "GET", url = "https://api.box.com/files/upload_sessions/{upload_session_id}/parts", path = {"upload_session_id"}, query = {"offset", "limit"} },
    ["box.get_folder_locks"] = { method = "GET", url = "https://api.box.com/folder_locks", query = {"folder_id"} },
    ["box.get_folders_id"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}", path = {"folder_id"}, query = {"fields", "sort", "direction", "offset", "limit"}, header = {"if-none-match", "boxapi"} },
    ["box.get_folders_id_app_item_associations"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}/app_item_associations", path = {"folder_id"}, query = {"limit", "marker", "application_type"} },
    ["box.get_folders_id_collaborations"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}/collaborations", path = {"folder_id"}, query = {"fields", "limit", "marker"} },
    ["box.get_folders_id_get_shared_link"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}#get_shared_link", path = {"folder_id"}, query = {"fields"} },
    ["box.get_folders_id_items"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}/items", path = {"folder_id"}, query = {"fields", "usemarker", "marker", "offset", "limit", "sort", "direction"}, header = {"boxapi"} },
    ["box.get_folders_id_metadata"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}/metadata", path = {"folder_id"}, query = {"view"} },
    ["box.get_folders_id_metadata_enterprise_security_classification_6_vmvochw_uwo"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}/metadata/enterprise/securityClassification-6VMVochwUWo", path = {"folder_id"} },
    ["box.get_folders_id_metadata_id_id"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}/metadata/{scope}/{template_key}", path = {"folder_id", "scope", "template_key"} },
    ["box.get_folders_id_trash"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}/trash", path = {"folder_id"}, query = {"fields"} },
    ["box.get_folders_id_watermark"] = { method = "GET", url = "https://api.box.com/folders/{folder_id}/watermark", path = {"folder_id"} },
    ["box.get_folders_trash_items"] = { method = "GET", url = "https://api.box.com/folders/trash/items", query = {"fields", "limit", "offset", "usemarker", "marker", "direction", "sort"} },
    ["box.get_group_memberships_id"] = { method = "GET", url = "https://api.box.com/group_memberships/{group_membership_id}", path = {"group_membership_id"}, query = {"fields"} },
    ["box.get_groups"] = { method = "GET", url = "https://api.box.com/groups", query = {"filter_term", "fields", "limit", "offset"} },
    ["box.get_groups_id"] = { method = "GET", url = "https://api.box.com/groups/{group_id}", path = {"group_id"}, query = {"fields"} },
    ["box.get_groups_id_collaborations"] = { method = "GET", url = "https://api.box.com/groups/{group_id}/collaborations", path = {"group_id"}, query = {"limit", "offset"} },
    ["box.get_groups_id_memberships"] = { method = "GET", url = "https://api.box.com/groups/{group_id}/memberships", path = {"group_id"}, query = {"limit", "offset"} },
    ["box.get_integration_mappings_slack"] = { method = "GET", url = "https://api.box.com/integration_mappings/slack", query = {"marker", "limit", "partner_item_type", "partner_item_id", "box_item_id", "box_item_type", "is_manually_created"} },
    ["box.get_integration_mappings_teams"] = { method = "GET", url = "https://api.box.com/integration_mappings/teams", query = {"partner_item_type", "partner_item_id", "box_item_id", "box_item_type"} },
    ["box.get_invites_id"] = { method = "GET", url = "https://api.box.com/invites/{invite_id}", path = {"invite_id"}, query = {"fields"} },
    ["box.get_legal_hold_policies"] = { method = "GET", url = "https://api.box.com/legal_hold_policies", query = {"policy_name", "fields", "marker", "limit"} },
    ["box.get_legal_hold_policies_id"] = { method = "GET", url = "https://api.box.com/legal_hold_policies/{legal_hold_policy_id}", path = {"legal_hold_policy_id"} },
    ["box.get_legal_hold_policy_assignments"] = { method = "GET", url = "https://api.box.com/legal_hold_policy_assignments", query = {"policy_id", "assign_to_type", "assign_to_id", "marker", "limit", "fields"} },
    ["box.get_legal_hold_policy_assignments_id"] = { method = "GET", url = "https://api.box.com/legal_hold_policy_assignments/{legal_hold_policy_assignment_id}", path = {"legal_hold_policy_assignment_id"} },
    ["box.get_legal_hold_policy_assignments_id_file_versions_on_hold"] = { method = "GET", url = "https://api.box.com/legal_hold_policy_assignments/{legal_hold_policy_assignment_id}/file_versions_on_hold", path = {"legal_hold_policy_assignment_id"}, query = {"marker", "limit", "fields"} },
    ["box.get_legal_hold_policy_assignments_id_files_on_hold"] = { method = "GET", url = "https://api.box.com/legal_hold_policy_assignments/{legal_hold_policy_assignment_id}/files_on_hold", path = {"legal_hold_policy_assignment_id"}, query = {"marker", "limit", "fields"} },
    ["box.get_metadata_cascade_policies"] = { method = "GET", url = "https://api.box.com/metadata_cascade_policies", query = {"folder_id", "owner_enterprise_id", "marker", "offset"} },
    ["box.get_metadata_cascade_policies_id"] = { method = "GET", url = "https://api.box.com/metadata_cascade_policies/{metadata_cascade_policy_id}", path = {"metadata_cascade_policy_id"} },
    ["box.get_metadata_taxonomies_id"] = { method = "GET", url = "https://api.box.com/metadata_taxonomies/{namespace}", path = {"namespace"}, query = {"marker", "limit"} },
    ["box.get_metadata_taxonomies_id_id"] = { method = "GET", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}", path = {"namespace", "taxonomy_key"} },
    ["box.get_metadata_taxonomies_id_id_nodes"] = { method = "GET", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/nodes", path = {"namespace", "taxonomy_key"}, query = {"level", "parent", "ancestor", "query", "include-total-result-count", "marker", "limit"} },
    ["box.get_metadata_taxonomies_id_id_nodes_id"] = { method = "GET", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/nodes/{node_id}", path = {"namespace", "taxonomy_key", "node_id"} },
    ["box.get_metadata_templates"] = { method = "GET", url = "https://api.box.com/metadata_templates", query = {"metadata_instance_id", "marker", "limit"} },
    ["box.get_metadata_templates_enterprise"] = { method = "GET", url = "https://api.box.com/metadata_templates/enterprise", query = {"marker", "limit"} },
    ["box.get_metadata_templates_enterprise_security_classification_6_vmvochw_uwo_schema"] = { method = "GET", url = "https://api.box.com/metadata_templates/enterprise/securityClassification-6VMVochwUWo/schema" },
    ["box.get_metadata_templates_global"] = { method = "GET", url = "https://api.box.com/metadata_templates/global", query = {"marker", "limit"} },
    ["box.get_metadata_templates_id"] = { method = "GET", url = "https://api.box.com/metadata_templates/{template_id}", path = {"template_id"} },
    ["box.get_metadata_templates_id_id_fields_id_options"] = { method = "GET", url = "https://api.box.com/metadata_templates/{namespace}/{template_key}/fields/{field_key}/options", path = {"namespace", "template_key", "field_key"}, query = {"level", "parent", "ancestor", "query", "include-total-result-count", "only-selectable-options", "marker", "limit"} },
    ["box.get_metadata_templates_id_id_schema"] = { method = "GET", url = "https://api.box.com/metadata_templates/{scope}/{template_key}/schema", path = {"scope", "template_key"} },
    ["box.get_recent_items"] = { method = "GET", url = "https://api.box.com/recent_items", query = {"fields", "limit", "marker"} },
    ["box.get_retention_policies"] = { method = "GET", url = "https://api.box.com/retention_policies", query = {"policy_name", "policy_type", "created_by_user_id", "fields", "limit", "marker"} },
    ["box.get_retention_policies_id"] = { method = "GET", url = "https://api.box.com/retention_policies/{retention_policy_id}", path = {"retention_policy_id"}, query = {"fields"} },
    ["box.get_retention_policies_id_assignments"] = { method = "GET", url = "https://api.box.com/retention_policies/{retention_policy_id}/assignments", path = {"retention_policy_id"}, query = {"type", "fields", "marker", "limit"} },
    ["box.get_retention_policy_assignments_id"] = { method = "GET", url = "https://api.box.com/retention_policy_assignments/{retention_policy_assignment_id}", path = {"retention_policy_assignment_id"}, query = {"fields"} },
    ["box.get_retention_policy_assignments_id_file_versions_under_retention"] = { method = "GET", url = "https://api.box.com/retention_policy_assignments/{retention_policy_assignment_id}/file_versions_under_retention", path = {"retention_policy_assignment_id"}, query = {"marker", "limit"} },
    ["box.get_retention_policy_assignments_id_files_under_retention"] = { method = "GET", url = "https://api.box.com/retention_policy_assignments/{retention_policy_assignment_id}/files_under_retention", path = {"retention_policy_assignment_id"}, query = {"marker", "limit"} },
    ["box.get_search"] = { method = "GET", url = "https://api.box.com/search", query = {"query", "scope", "file_extensions", "created_at_range", "updated_at_range", "size_range", "owner_user_ids", "recent_updater_user_ids", "ancestor_folder_ids", "content_types", "type", "trash_content", "mdfilters", "sort", "direction", "limit", "include_recent_shared_links", "fields", "offset", "deleted_user_ids", "deleted_at_range"} },
    ["box.get_shared_items"] = { method = "GET", url = "https://api.box.com/shared_items", query = {"fields"}, header = {"if-none-match", "boxapi"} },
    ["box.get_shared_items_app_items"] = { method = "GET", url = "https://api.box.com/shared_items#app_items", header = {"boxapi"} },
    ["box.get_shared_items_folders"] = { method = "GET", url = "https://api.box.com/shared_items#folders", query = {"fields"}, header = {"if-none-match", "boxapi"} },
    ["box.get_shared_items_web_links"] = { method = "GET", url = "https://api.box.com/shared_items#web_links", query = {"fields"}, header = {"if-none-match", "boxapi"} },
    ["box.get_shield_information_barrier_reports"] = { method = "GET", url = "https://api.box.com/shield_information_barrier_reports", query = {"shield_information_barrier_id", "marker", "limit"} },
    ["box.get_shield_information_barrier_reports_id"] = { method = "GET", url = "https://api.box.com/shield_information_barrier_reports/{shield_information_barrier_report_id}", path = {"shield_information_barrier_report_id"} },
    ["box.get_shield_information_barrier_segment_members"] = { method = "GET", url = "https://api.box.com/shield_information_barrier_segment_members", query = {"shield_information_barrier_segment_id", "marker", "limit"} },
    ["box.get_shield_information_barrier_segment_members_id"] = { method = "GET", url = "https://api.box.com/shield_information_barrier_segment_members/{shield_information_barrier_segment_member_id}", path = {"shield_information_barrier_segment_member_id"} },
    ["box.get_shield_information_barrier_segment_restrictions"] = { method = "GET", url = "https://api.box.com/shield_information_barrier_segment_restrictions", query = {"shield_information_barrier_segment_id", "marker", "limit"} },
    ["box.get_shield_information_barrier_segment_restrictions_id"] = { method = "GET", url = "https://api.box.com/shield_information_barrier_segment_restrictions/{shield_information_barrier_segment_restriction_id}", path = {"shield_information_barrier_segment_restriction_id"} },
    ["box.get_shield_information_barrier_segments"] = { method = "GET", url = "https://api.box.com/shield_information_barrier_segments", query = {"shield_information_barrier_id", "marker", "limit"} },
    ["box.get_shield_information_barrier_segments_id"] = { method = "GET", url = "https://api.box.com/shield_information_barrier_segments/{shield_information_barrier_segment_id}", path = {"shield_information_barrier_segment_id"} },
    ["box.get_shield_information_barriers"] = { method = "GET", url = "https://api.box.com/shield_information_barriers", query = {"marker", "limit"} },
    ["box.get_shield_information_barriers_id"] = { method = "GET", url = "https://api.box.com/shield_information_barriers/{shield_information_barrier_id}", path = {"shield_information_barrier_id"} },
    ["box.get_sign_requests"] = { method = "GET", url = "https://api.box.com/sign_requests", query = {"marker", "limit", "senders", "shared_requests"} },
    ["box.get_sign_requests_id"] = { method = "GET", url = "https://api.box.com/sign_requests/{sign_request_id}", path = {"sign_request_id"} },
    ["box.get_sign_templates"] = { method = "GET", url = "https://api.box.com/sign_templates", query = {"marker", "limit"} },
    ["box.get_sign_templates_id"] = { method = "GET", url = "https://api.box.com/sign_templates/{template_id}", path = {"template_id"} },
    ["box.get_storage_policies"] = { method = "GET", url = "https://api.box.com/storage_policies", query = {"fields", "marker", "limit"} },
    ["box.get_storage_policies_id"] = { method = "GET", url = "https://api.box.com/storage_policies/{storage_policy_id}", path = {"storage_policy_id"} },
    ["box.get_storage_policy_assignments"] = { method = "GET", url = "https://api.box.com/storage_policy_assignments", query = {"marker", "resolved_for_type", "resolved_for_id"} },
    ["box.get_storage_policy_assignments_id"] = { method = "GET", url = "https://api.box.com/storage_policy_assignments/{storage_policy_assignment_id}", path = {"storage_policy_assignment_id"} },
    ["box.get_task_assignments_id"] = { method = "GET", url = "https://api.box.com/task_assignments/{task_assignment_id}", path = {"task_assignment_id"} },
    ["box.get_tasks_id"] = { method = "GET", url = "https://api.box.com/tasks/{task_id}", path = {"task_id"} },
    ["box.get_tasks_id_assignments"] = { method = "GET", url = "https://api.box.com/tasks/{task_id}/assignments", path = {"task_id"} },
    ["box.get_terms_of_service_user_statuses"] = { method = "GET", url = "https://api.box.com/terms_of_service_user_statuses", query = {"tos_id", "user_id"} },
    ["box.get_terms_of_services"] = { method = "GET", url = "https://api.box.com/terms_of_services", query = {"tos_type"} },
    ["box.get_terms_of_services_id"] = { method = "GET", url = "https://api.box.com/terms_of_services/{terms_of_service_id}", path = {"terms_of_service_id"} },
    ["box.get_users"] = { method = "GET", url = "https://api.box.com/users", query = {"filter_term", "user_type", "external_app_user_id", "fields", "offset", "limit", "usemarker", "marker"} },
    ["box.get_users_id"] = { method = "GET", url = "https://api.box.com/users/{user_id}", path = {"user_id"}, query = {"fields"} },
    ["box.get_users_id_avatar"] = { method = "GET", url = "https://api.box.com/users/{user_id}/avatar", path = {"user_id"} },
    ["box.get_users_id_email_aliases"] = { method = "GET", url = "https://api.box.com/users/{user_id}/email_aliases", path = {"user_id"} },
    ["box.get_users_id_memberships"] = { method = "GET", url = "https://api.box.com/users/{user_id}/memberships", path = {"user_id"}, query = {"limit", "offset"} },
    ["box.get_users_me"] = { method = "GET", url = "https://api.box.com/users/me", query = {"fields"} },
    ["box.get_web_links_id"] = { method = "GET", url = "https://api.box.com/web_links/{web_link_id}", path = {"web_link_id"}, header = {"boxapi"} },
    ["box.get_web_links_id_get_shared_link"] = { method = "GET", url = "https://api.box.com/web_links/{web_link_id}#get_shared_link", path = {"web_link_id"}, query = {"fields"} },
    ["box.get_web_links_id_trash"] = { method = "GET", url = "https://api.box.com/web_links/{web_link_id}/trash", path = {"web_link_id"}, query = {"fields"} },
    ["box.get_webhooks"] = { method = "GET", url = "https://api.box.com/webhooks", query = {"marker", "limit"} },
    ["box.get_webhooks_id"] = { method = "GET", url = "https://api.box.com/webhooks/{webhook_id}", path = {"webhook_id"} },
    ["box.get_workflows"] = { method = "GET", url = "https://api.box.com/workflows", query = {"folder_id", "trigger_type", "limit", "marker"} },
    ["box.get_zip_downloads_id_content"] = { method = "GET", url = "https://api.box.com/zip_downloads/{zip_download_id}/content", path = {"zip_download_id"} },
    ["box.get_zip_downloads_id_status"] = { method = "GET", url = "https://api.box.com/zip_downloads/{zip_download_id}/status", path = {"zip_download_id"} },
    ["box.patch_metadata_taxonomies_id_id"] = { method = "PATCH", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}", path = {"namespace", "taxonomy_key"}, body = {"displayName"} },
    ["box.patch_metadata_taxonomies_id_id_levels_id"] = { method = "PATCH", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/levels/{level_index}", path = {"namespace", "taxonomy_key", "level_index"}, body = {"displayName", "description"} },
    ["box.patch_metadata_taxonomies_id_id_nodes_id"] = { method = "PATCH", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/nodes/{node_id}", path = {"namespace", "taxonomy_key", "node_id"}, body = {"displayName"} },
    ["box.post_ai_agents"] = { method = "POST", url = "https://api.box.com/ai_agents", body = {"type", "name", "access_state", "icon_reference", "allowed_entities", "ask", "text_gen", "extract"} },
    ["box.post_ai_ask"] = { method = "POST", url = "https://api.box.com/ai/ask", body = {"mode", "prompt", "items", "dialogue_history", "include_citations", "ai_agent"} },
    ["box.post_ai_extract"] = { method = "POST", url = "https://api.box.com/ai/extract", body = {"prompt", "items", "ai_agent"} },
    ["box.post_ai_extract_structured"] = { method = "POST", url = "https://api.box.com/ai/extract_structured", body = {"items", "metadata_template", "fields", "ai_agent", "include_confidence_score", "include_reference", "taxonomy_sources"} },
    ["box.post_ai_text_gen"] = { method = "POST", url = "https://api.box.com/ai/text_gen", body = {"prompt", "items", "dialogue_history", "ai_agent"} },
    ["box.post_collaboration_whitelist_entries"] = { method = "POST", url = "https://api.box.com/collaboration_whitelist_entries", body = {"domain", "direction"} },
    ["box.post_collaboration_whitelist_exempt_targets"] = { method = "POST", url = "https://api.box.com/collaboration_whitelist_exempt_targets", body = {"user"} },
    ["box.post_collaborations"] = { method = "POST", url = "https://api.box.com/collaborations", query = {"fields", "notify"}, body = {"item", "accessible_by", "role", "is_access_only", "can_view_path", "expires_at"} },
    ["box.post_comments"] = { method = "POST", url = "https://api.box.com/comments", query = {"fields"}, body = {"message", "tagged_message", "item"} },
    ["box.post_file_requests_id_copy"] = { method = "POST", url = "https://api.box.com/file_requests/{file_request_id}/copy", path = {"file_request_id"}, body = {"title", "description", "status", "is_email_required", "is_description_required", "expires_at"} },
    ["box.post_files_content"] = { method = "POST", url = "https://api.box.com/files/content", query = {"fields"}, header = {"content-md5"}, body = {"attributes", "file"} },
    ["box.post_files_id"] = { method = "POST", url = "https://api.box.com/files/{file_id}", path = {"file_id"}, query = {"fields"}, body = {"name", "parent"} },
    ["box.post_files_id_content"] = { method = "POST", url = "https://api.box.com/files/{file_id}/content", path = {"file_id"}, query = {"fields"}, header = {"if-match", "content-md5"}, body = {"attributes", "file"} },
    ["box.post_files_id_copy"] = { method = "POST", url = "https://api.box.com/files/{file_id}/copy", path = {"file_id"}, query = {"fields"}, body = {"name", "version", "parent"} },
    ["box.post_files_id_metadata_enterprise_security_classification_6_vmvochw_uwo"] = { method = "POST", url = "https://api.box.com/files/{file_id}/metadata/enterprise/securityClassification-6VMVochwUWo", path = {"file_id"}, body = {"Box__Security__Classification__Key"} },
    ["box.post_files_id_metadata_global_box_skills_cards"] = { method = "POST", url = "https://api.box.com/files/{file_id}/metadata/global/boxSkillsCards", path = {"file_id"}, body = {"cards"} },
    ["box.post_files_id_metadata_id_id"] = { method = "POST", url = "https://api.box.com/files/{file_id}/metadata/{scope}/{template_key}", path = {"file_id", "scope", "template_key"} },
    ["box.post_files_id_upload_sessions"] = { method = "POST", url = "https://api.box.com/files/{file_id}/upload_sessions", path = {"file_id"}, body = {"file_size", "file_name"} },
    ["box.post_files_id_versions_current"] = { method = "POST", url = "https://api.box.com/files/{file_id}/versions/current", path = {"file_id"}, query = {"fields"}, body = {"id", "type"} },
    ["box.post_files_upload_sessions"] = { method = "POST", url = "https://api.box.com/files/upload_sessions", body = {"folder_id", "file_size", "file_name"} },
    ["box.post_files_upload_sessions_id_commit"] = { method = "POST", url = "https://api.box.com/files/upload_sessions/{upload_session_id}/commit", path = {"upload_session_id"}, header = {"digest", "if-match", "if-none-match"}, body = {"parts"} },
    ["box.post_files_upload_sessions_id_plan"] = { method = "POST", url = "https://api.box.com/files/upload_sessions/{upload_session_id}/plan", path = {"upload_session_id"}, body = {"parts"} },
    ["box.post_folder_locks"] = { method = "POST", url = "https://api.box.com/folder_locks", body = {"locked_operations", "folder"} },
    ["box.post_folders"] = { method = "POST", url = "https://api.box.com/folders", query = {"fields"}, body = {"name", "parent", "folder_upload_email", "sync_state"} },
    ["box.post_folders_id"] = { method = "POST", url = "https://api.box.com/folders/{folder_id}", path = {"folder_id"}, query = {"fields"}, body = {"name", "parent"} },
    ["box.post_folders_id_copy"] = { method = "POST", url = "https://api.box.com/folders/{folder_id}/copy", path = {"folder_id"}, query = {"fields"}, body = {"name", "parent"} },
    ["box.post_folders_id_metadata_enterprise_security_classification_6_vmvochw_uwo"] = { method = "POST", url = "https://api.box.com/folders/{folder_id}/metadata/enterprise/securityClassification-6VMVochwUWo", path = {"folder_id"}, body = {"Box__Security__Classification__Key"} },
    ["box.post_folders_id_metadata_id_id"] = { method = "POST", url = "https://api.box.com/folders/{folder_id}/metadata/{scope}/{template_key}", path = {"folder_id", "scope", "template_key"} },
    ["box.post_group_memberships"] = { method = "POST", url = "https://api.box.com/group_memberships", query = {"fields"}, body = {"user", "group", "role", "configurable_permissions"} },
    ["box.post_groups"] = { method = "POST", url = "https://api.box.com/groups", query = {"fields"}, body = {"name", "provenance", "external_sync_identifier", "description", "invitability_level", "member_viewability_level"} },
    ["box.post_groups_terminate_sessions"] = { method = "POST", url = "https://api.box.com/groups/terminate_sessions", body = {"group_ids"} },
    ["box.post_integration_mappings_slack"] = { method = "POST", url = "https://api.box.com/integration_mappings/slack", body = {"partner_item", "box_item", "options"} },
    ["box.post_integration_mappings_teams"] = { method = "POST", url = "https://api.box.com/integration_mappings/teams", body = {"partner_item", "box_item"} },
    ["box.post_invites"] = { method = "POST", url = "https://api.box.com/invites", query = {"fields"}, body = {"enterprise", "actionable_by"} },
    ["box.post_legal_hold_policies"] = { method = "POST", url = "https://api.box.com/legal_hold_policies", body = {"policy_name", "description", "filter_started_at", "filter_ended_at", "is_ongoing"} },
    ["box.post_legal_hold_policy_assignments"] = { method = "POST", url = "https://api.box.com/legal_hold_policy_assignments", body = {"policy_id", "assign_to"} },
    ["box.post_metadata_cascade_policies"] = { method = "POST", url = "https://api.box.com/metadata_cascade_policies", body = {"folder_id", "scope", "templateKey"} },
    ["box.post_metadata_cascade_policies_id_apply"] = { method = "POST", url = "https://api.box.com/metadata_cascade_policies/{metadata_cascade_policy_id}/apply", path = {"metadata_cascade_policy_id"}, body = {"conflict_resolution"} },
    ["box.post_metadata_queries_execute_read"] = { method = "POST", url = "https://api.box.com/metadata_queries/execute_read", body = {"from", "query", "query_params", "ancestor_folder_id", "order_by", "limit", "marker", "fields"} },
    ["box.post_metadata_taxonomies"] = { method = "POST", url = "https://api.box.com/metadata_taxonomies", body = {"displayName", "namespace"} },
    ["box.post_metadata_taxonomies_id_id_levels"] = { method = "POST", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/levels", path = {"namespace", "taxonomy_key"} },
    ["box.post_metadata_taxonomies_id_id_levels_append"] = { method = "POST", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/levels:append", path = {"namespace", "taxonomy_key"}, body = {"displayName", "description"} },
    ["box.post_metadata_taxonomies_id_id_levels_trim"] = { method = "POST", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/levels:trim", path = {"namespace", "taxonomy_key"} },
    ["box.post_metadata_taxonomies_id_id_nodes"] = { method = "POST", url = "https://api.box.com/metadata_taxonomies/{namespace}/{taxonomy_key}/nodes", path = {"namespace", "taxonomy_key"}, body = {"displayName", "level", "parentId"} },
    ["box.post_metadata_templates_schema"] = { method = "POST", url = "https://api.box.com/metadata_templates/schema", body = {"scope", "templateKey", "displayName", "hidden", "fields", "copyInstanceOnItemCopy"} },
    ["box.post_metadata_templates_schema_classifications"] = { method = "POST", url = "https://api.box.com/metadata_templates/schema#classifications", body = {"scope", "templateKey", "displayName", "hidden", "copyInstanceOnItemCopy", "fields"} },
    ["box.post_oauth2_revoke"] = { method = "POST", url = "https://api.box.com/oauth2/revoke", body = {"client_id", "client_secret"} },
    ["box.post_oauth2_token"] = { method = "POST", url = "https://api.box.com/oauth2/token", body = {"grant_type", "client_id", "client_secret", "code", "refresh_token", "assertion", "subject_token", "subject_token_type", "actor_token", "actor_token_type", "scope", "resource", "box_subject_type", "box_subject_id", "box_shared_link"} },
    ["box.post_oauth2_token_refresh"] = { method = "POST", url = "https://api.box.com/oauth2/token#refresh", body = {"grant_type", "client_id", "client_secret", "refresh_token"} },
    ["box.post_retention_policies"] = { method = "POST", url = "https://api.box.com/retention_policies", body = {"policy_name", "description", "policy_type", "disposition_action", "retention_length", "retention_type", "can_owner_extend_retention", "max_extension_length", "are_owners_notified", "custom_notification_recipients"} },
    ["box.post_retention_policy_assignments"] = { method = "POST", url = "https://api.box.com/retention_policy_assignments", body = {"policy_id", "assign_to", "filter_fields", "start_date_field"} },
    ["box.post_shield_information_barrier_reports"] = { method = "POST", url = "https://api.box.com/shield_information_barrier_reports", body = {"shield_information_barrier"} },
    ["box.post_shield_information_barrier_segment_members"] = { method = "POST", url = "https://api.box.com/shield_information_barrier_segment_members", body = {"type", "shield_information_barrier", "shield_information_barrier_segment", "user"} },
    ["box.post_shield_information_barrier_segment_restrictions"] = { method = "POST", url = "https://api.box.com/shield_information_barrier_segment_restrictions", body = {"type", "shield_information_barrier", "shield_information_barrier_segment", "restricted_segment"} },
    ["box.post_shield_information_barrier_segments"] = { method = "POST", url = "https://api.box.com/shield_information_barrier_segments", body = {"shield_information_barrier", "name", "description"} },
    ["box.post_shield_information_barriers"] = { method = "POST", url = "https://api.box.com/shield_information_barriers", body = {"enterprise"} },
    ["box.post_shield_information_barriers_change_status"] = { method = "POST", url = "https://api.box.com/shield_information_barriers/change_status", body = {"id", "status"} },
    ["box.post_sign_requests"] = { method = "POST", url = "https://api.box.com/sign_requests", body = {"is_document_preparation_needed", "redirect_url", "declined_redirect_url", "are_text_signatures_enabled", "email_subject", "email_message", "are_reminders_enabled", "name", "prefill_tags", "days_valid", "external_id", "template_id", "external_system_name", "request_flow"} },
    ["box.post_sign_requests_id_cancel"] = { method = "POST", url = "https://api.box.com/sign_requests/{sign_request_id}/cancel", path = {"sign_request_id"}, body = {"reason"} },
    ["box.post_sign_requests_id_resend"] = { method = "POST", url = "https://api.box.com/sign_requests/{sign_request_id}/resend", path = {"sign_request_id"} },
    ["box.post_storage_policy_assignments"] = { method = "POST", url = "https://api.box.com/storage_policy_assignments", body = {"storage_policy", "assigned_to"} },
    ["box.post_task_assignments"] = { method = "POST", url = "https://api.box.com/task_assignments", body = {"task", "assign_to"} },
    ["box.post_tasks"] = { method = "POST", url = "https://api.box.com/tasks", body = {"item", "action", "message", "due_at", "completion_rule"} },
    ["box.post_terms_of_service_user_statuses"] = { method = "POST", url = "https://api.box.com/terms_of_service_user_statuses", body = {"tos", "user", "is_accepted"} },
    ["box.post_terms_of_services"] = { method = "POST", url = "https://api.box.com/terms_of_services", body = {"status", "tos_type", "text"} },
    ["box.post_users"] = { method = "POST", url = "https://api.box.com/users", query = {"fields"}, body = {"name", "login", "is_platform_access_only", "role", "language", "is_sync_enabled", "job_title", "phone", "address", "space_amount", "tracking_codes", "can_see_managed_users", "timezone", "is_external_collab_restricted", "is_exempt_from_device_limits", "is_exempt_from_login_verification", "status", "external_app_user_id"} },
    ["box.post_users_id_avatar"] = { method = "POST", url = "https://api.box.com/users/{user_id}/avatar", path = {"user_id"}, body = {"pic"} },
    ["box.post_users_id_email_aliases"] = { method = "POST", url = "https://api.box.com/users/{user_id}/email_aliases", path = {"user_id"}, body = {"email"} },
    ["box.post_users_terminate_sessions"] = { method = "POST", url = "https://api.box.com/users/terminate_sessions", body = {"user_ids", "user_logins"} },
    ["box.post_web_links"] = { method = "POST", url = "https://api.box.com/web_links", body = {"url", "parent", "name", "description"} },
    ["box.post_web_links_id"] = { method = "POST", url = "https://api.box.com/web_links/{web_link_id}", path = {"web_link_id"}, query = {"fields"}, body = {"name", "parent"} },
    ["box.post_webhooks"] = { method = "POST", url = "https://api.box.com/webhooks", body = {"target", "address", "triggers"} },
    ["box.post_workflows_id_start"] = { method = "POST", url = "https://api.box.com/workflows/{workflow_id}/start", path = {"workflow_id"}, body = {"type", "flow", "files", "folder", "outcomes"} },
    ["box.post_zip_downloads"] = { method = "POST", url = "https://api.box.com/zip_downloads", body = {"items", "download_file_name"} },
    ["box.put_ai_agents_id"] = { method = "PUT", url = "https://api.box.com/ai_agents/{agent_id}", path = {"agent_id"}, body = {"type", "name", "access_state", "icon_reference", "allowed_entities", "ask", "text_gen", "extract"} },
    ["box.put_collaborations_id"] = { method = "PUT", url = "https://api.box.com/collaborations/{collaboration_id}", path = {"collaboration_id"}, body = {"role", "status", "expires_at", "can_view_path"} },
    ["box.put_comments_id"] = { method = "PUT", url = "https://api.box.com/comments/{comment_id}", path = {"comment_id"}, query = {"fields"}, body = {"message"} },
    ["box.put_file_requests_id"] = { method = "PUT", url = "https://api.box.com/file_requests/{file_request_id}", path = {"file_request_id"}, header = {"if-match"}, body = {"title", "description", "status", "is_email_required", "is_description_required", "expires_at"} },
    ["box.put_files_id"] = { method = "PUT", url = "https://api.box.com/files/{file_id}", path = {"file_id"}, query = {"fields"}, header = {"if-match"}, body = {"name", "description", "parent", "shared_link", "lock", "disposition_at", "permissions", "collections", "tags"} },
    ["box.put_files_id_add_shared_link"] = { method = "PUT", url = "https://api.box.com/files/{file_id}#add_shared_link", path = {"file_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_files_id_metadata_enterprise_security_classification_6_vmvochw_uwo"] = { method = "PUT", url = "https://api.box.com/files/{file_id}/metadata/enterprise/securityClassification-6VMVochwUWo", path = {"file_id"} },
    ["box.put_files_id_metadata_global_box_skills_cards"] = { method = "PUT", url = "https://api.box.com/files/{file_id}/metadata/global/boxSkillsCards", path = {"file_id"} },
    ["box.put_files_id_metadata_id_id"] = { method = "PUT", url = "https://api.box.com/files/{file_id}/metadata/{scope}/{template_key}", path = {"file_id", "scope", "template_key"} },
    ["box.put_files_id_remove_shared_link"] = { method = "PUT", url = "https://api.box.com/files/{file_id}#remove_shared_link", path = {"file_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_files_id_update_shared_link"] = { method = "PUT", url = "https://api.box.com/files/{file_id}#update_shared_link", path = {"file_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_files_id_versions_id"] = { method = "PUT", url = "https://api.box.com/files/{file_id}/versions/{file_version_id}", path = {"file_id", "file_version_id"}, body = {"trashed_at"} },
    ["box.put_files_id_watermark"] = { method = "PUT", url = "https://api.box.com/files/{file_id}/watermark", path = {"file_id"}, body = {"watermark"} },
    ["box.put_files_upload_sessions_id"] = { method = "PUT", url = "https://api.box.com/files/upload_sessions/{upload_session_id}", path = {"upload_session_id"}, header = {"digest", "content-range"} },
    ["box.put_folders_id"] = { method = "PUT", url = "https://api.box.com/folders/{folder_id}", path = {"folder_id"}, query = {"fields"}, header = {"if-match"}, body = {"name", "description", "sync_state", "can_non_owners_invite", "parent", "shared_link", "folder_upload_email", "tags", "is_collaboration_restricted_to_enterprise", "collections", "can_non_owners_view_collaborators"} },
    ["box.put_folders_id_add_shared_link"] = { method = "PUT", url = "https://api.box.com/folders/{folder_id}#add_shared_link", path = {"folder_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_folders_id_metadata_enterprise_security_classification_6_vmvochw_uwo"] = { method = "PUT", url = "https://api.box.com/folders/{folder_id}/metadata/enterprise/securityClassification-6VMVochwUWo", path = {"folder_id"} },
    ["box.put_folders_id_metadata_id_id"] = { method = "PUT", url = "https://api.box.com/folders/{folder_id}/metadata/{scope}/{template_key}", path = {"folder_id", "scope", "template_key"} },
    ["box.put_folders_id_remove_shared_link"] = { method = "PUT", url = "https://api.box.com/folders/{folder_id}#remove_shared_link", path = {"folder_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_folders_id_update_shared_link"] = { method = "PUT", url = "https://api.box.com/folders/{folder_id}#update_shared_link", path = {"folder_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_folders_id_watermark"] = { method = "PUT", url = "https://api.box.com/folders/{folder_id}/watermark", path = {"folder_id"}, body = {"watermark"} },
    ["box.put_group_memberships_id"] = { method = "PUT", url = "https://api.box.com/group_memberships/{group_membership_id}", path = {"group_membership_id"}, query = {"fields"}, body = {"role", "configurable_permissions"} },
    ["box.put_groups_id"] = { method = "PUT", url = "https://api.box.com/groups/{group_id}", path = {"group_id"}, query = {"fields"}, body = {"name", "provenance", "external_sync_identifier", "description", "invitability_level", "member_viewability_level"} },
    ["box.put_integration_mappings_slack_id"] = { method = "PUT", url = "https://api.box.com/integration_mappings/slack/{integration_mapping_id}", path = {"integration_mapping_id"}, body = {"box_item", "options"} },
    ["box.put_integration_mappings_teams_id"] = { method = "PUT", url = "https://api.box.com/integration_mappings/teams/{integration_mapping_id}", path = {"integration_mapping_id"}, body = {"box_item"} },
    ["box.put_legal_hold_policies_id"] = { method = "PUT", url = "https://api.box.com/legal_hold_policies/{legal_hold_policy_id}", path = {"legal_hold_policy_id"}, body = {"policy_name", "description", "release_notes"} },
    ["box.put_metadata_templates_enterprise_security_classification_6_vmvochw_uwo_schema_add"] = { method = "PUT", url = "https://api.box.com/metadata_templates/enterprise/securityClassification-6VMVochwUWo/schema#add" },
    ["box.put_metadata_templates_enterprise_security_classification_6_vmvochw_uwo_schema_update"] = { method = "PUT", url = "https://api.box.com/metadata_templates/enterprise/securityClassification-6VMVochwUWo/schema#update" },
    ["box.put_metadata_templates_id_id_schema"] = { method = "PUT", url = "https://api.box.com/metadata_templates/{scope}/{template_key}/schema", path = {"scope", "template_key"} },
    ["box.put_retention_policies_id"] = { method = "PUT", url = "https://api.box.com/retention_policies/{retention_policy_id}", path = {"retention_policy_id"}, body = {"policy_name", "description", "disposition_action", "retention_type", "retention_length", "status", "can_owner_extend_retention", "max_extension_length", "are_owners_notified", "custom_notification_recipients"} },
    ["box.put_shield_information_barrier_segments_id"] = { method = "PUT", url = "https://api.box.com/shield_information_barrier_segments/{shield_information_barrier_segment_id}", path = {"shield_information_barrier_segment_id"}, body = {"name", "description"} },
    ["box.put_skill_invocations_id"] = { method = "PUT", url = "https://api.box.com/skill_invocations/{skill_id}", path = {"skill_id"}, body = {"status", "metadata", "file", "file_version", "usage"} },
    ["box.put_storage_policy_assignments_id"] = { method = "PUT", url = "https://api.box.com/storage_policy_assignments/{storage_policy_assignment_id}", path = {"storage_policy_assignment_id"}, body = {"storage_policy"} },
    ["box.put_task_assignments_id"] = { method = "PUT", url = "https://api.box.com/task_assignments/{task_assignment_id}", path = {"task_assignment_id"}, body = {"message", "resolution_state"} },
    ["box.put_tasks_id"] = { method = "PUT", url = "https://api.box.com/tasks/{task_id}", path = {"task_id"}, body = {"action", "message", "due_at", "completion_rule"} },
    ["box.put_terms_of_service_user_statuses_id"] = { method = "PUT", url = "https://api.box.com/terms_of_service_user_statuses/{terms_of_service_user_status_id}", path = {"terms_of_service_user_status_id"}, body = {"is_accepted"} },
    ["box.put_terms_of_services_id"] = { method = "PUT", url = "https://api.box.com/terms_of_services/{terms_of_service_id}", path = {"terms_of_service_id"}, body = {"status", "text"} },
    ["box.put_users_id"] = { method = "PUT", url = "https://api.box.com/users/{user_id}", path = {"user_id"}, query = {"fields"}, body = {"enterprise", "notify", "name", "login", "role", "language", "is_sync_enabled", "job_title", "phone", "address", "tracking_codes", "can_see_managed_users", "timezone", "is_external_collab_restricted", "is_exempt_from_device_limits", "is_exempt_from_login_verification", "is_password_reset_required", "is_collaborated_content_available_when_owner_inactive", "status", "space_amount", "notification_email", "external_app_user_id"} },
    ["box.put_users_id_folders_0"] = { method = "PUT", url = "https://api.box.com/users/{user_id}/folders/0", path = {"user_id"}, query = {"fields", "notify"}, body = {"owned_by"} },
    ["box.put_web_links_id"] = { method = "PUT", url = "https://api.box.com/web_links/{web_link_id}", path = {"web_link_id"}, body = {"url", "parent", "name", "description", "shared_link"} },
    ["box.put_web_links_id_add_shared_link"] = { method = "PUT", url = "https://api.box.com/web_links/{web_link_id}#add_shared_link", path = {"web_link_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_web_links_id_remove_shared_link"] = { method = "PUT", url = "https://api.box.com/web_links/{web_link_id}#remove_shared_link", path = {"web_link_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_web_links_id_update_shared_link"] = { method = "PUT", url = "https://api.box.com/web_links/{web_link_id}#update_shared_link", path = {"web_link_id"}, query = {"fields"}, body = {"shared_link"} },
    ["box.put_webhooks_id"] = { method = "PUT", url = "https://api.box.com/webhooks/{webhook_id}", path = {"webhook_id"}, body = {"target", "address", "triggers"} },
  },
}
