-- HeyGen — every call this API accepts, as data.
--
-- GENERATED from https://docs.heygen.com/openapi.yaml
-- Published on the vendor's own documentation site (https://docs.heygen.com).
-- 53 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "heygen",
  name = "HeyGen",
  base = "https://api2.heygen.com",
  docs = "https://nango.dev/docs/api-integrations/heygen",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "HEYGEN_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["heygen.add_a_webhook_endpoint"] = { method = "POST", url = "https://api2.heygen.com/v1/webhook/endpoint.add", body = {"url", "events", "entity_id"} },
    ["heygen.add_looks_to_photo_avatar_group"] = { method = "POST", url = "https://api2.heygen.com/v2/photo_avatar/avatar_group/add", body = {"group_id", "image_keys", "name", "generation_id"} },
    ["heygen.add_motion"] = { method = "POST", url = "https://api2.heygen.com/v2/photo_avatar/add_motion", body = {"id"} },
    ["heygen.add_sound_effect"] = { method = "POST", url = "https://api2.heygen.com/v2/photo_avatar/add_sound_effect", body = {"id"} },
    ["heygen.check_photolook_generation_status"] = { method = "GET", url = "https://api2.heygen.com/v2/photo_avatar/generation/{generation_id}", path = {"generation_id"} },
    ["heygen.check_video_avatar_generation_status"] = { method = "GET", url = "https://api2.heygen.com/v2/video_avatar/{avatar_id}", path = {"avatar_id"} },
    ["heygen.close_session"] = { method = "POST", url = "https://api2.heygen.com/v1/streaming.stop", body = {"session_id"} },
    ["heygen.create_a_webm_video"] = { method = "POST", url = "https://api2.heygen.com/v1/video.webm", header = {"x-api-key"}, body = {"avatar_pose_id", "avatar_style", "input_text", "voice_id", "input_audio", "dimension"} },
    ["heygen.create_an_avatar_video_v2"] = { method = "POST", url = "https://api2.heygen.com/v2/video/generate", body = {"caption", "title", "callback_id", "dimension", "video_inputs", "folder_id", "callback_url"} },
    ["heygen.create_folder"] = { method = "POST", url = "https://api2.heygen.com/v1/folders/create", body = {"name", "project_type", "parent_id"} },
    ["heygen.create_photo_avatar_group"] = { method = "POST", url = "https://api2.heygen.com/v2/photo_avatar/avatar_group/create", body = {"name", "image_key", "generation_id"} },
    ["heygen.create_session_token"] = { method = "POST", url = "https://api2.heygen.com/v1/streaming.create_token", body = {"RAW_BODY"} },
    ["heygen.delete_a_video"] = { method = "DELETE", url = "https://api2.heygen.com/v1/video.delete", query = {"video_id"} },
    ["heygen.delete_a_webhook_endpoint"] = { method = "DELETE", url = "https://api2.heygen.com/v1/webhook/endpoint.delete", query = {"endpoint_id"} },
    ["heygen.delete_video_avatar"] = { method = "DELETE", url = "https://api2.heygen.com/v2/video_avatar/{avatar_id}", path = {"avatar_id"} },
    ["heygen.generate_from_template_v2"] = { method = "POST", url = "https://api2.heygen.com/v2/template/{template_id}/generate", path = {"template_id"}, body = {"caption", "callback_id", "title", "variables", "dimension", "include_gif", "enable_sharing", "folder_id", "brand_voice_id"} },
    ["heygen.generate_photo_avatar_looks"] = { method = "POST", url = "https://api2.heygen.com/v2/photo_avatar/look/generate", body = {"group_id", "prompt", "orientation", "pose", "style"} },
    ["heygen.generate_photo_avatar_photos"] = { method = "POST", url = "https://api2.heygen.com/v2/photo_avatar/photo/generate", body = {"name", "age", "gender", "ethnicity", "orientation", "pose", "style", "appearance"} },
    ["heygen.get_current_user_information"] = { method = "GET", url = "https://api2.heygen.com/v1/user/me" },
    ["heygen.get_remaining_quota_v2"] = { method = "GET", url = "https://api2.heygen.com/v2/user/remaining_quota" },
    ["heygen.get_template_v2"] = { method = "GET", url = "https://api2.heygen.com/v2/template/{template_id}", path = {"template_id"} },
    ["heygen.get_template_v3"] = { method = "GET", url = "https://api2.heygen.com/v3/template/{template_id}", path = {"template_id"} },
    ["heygen.get_training_job_status"] = { method = "GET", url = "https://api2.heygen.com/v2/photo_avatar/train/status/{group_id}", path = {"group_id"} },
    ["heygen.interrupt_task"] = { method = "POST", url = "https://api2.heygen.com/v1/streaming.interrupt", body = {"session_id"} },
    ["heygen.list_all_avatar_groups"] = { method = "GET", url = "https://api2.heygen.com/v2/avatar_group.list", query = {"include_public"} },
    ["heygen.list_all_avatars_in_one_avatar_group"] = { method = "GET", url = "https://api2.heygen.com/v2/avatar_group/{group_id}/avatars", path = {"group_id"} },
    ["heygen.list_available_webhook_events"] = { method = "GET", url = "https://api2.heygen.com/v1/webhook/webhook.list" },
    ["heygen.list_avatars_v2"] = { method = "GET", url = "https://api2.heygen.com/v2/avatars" },
    ["heygen.list_brand_voices"] = { method = "GET", url = "https://api2.heygen.com/v1/brand_voice/list", query = {"limit", "name_only"} },
    ["heygen.list_folders"] = { method = "GET", url = "https://api2.heygen.com/v1/folders", query = {"limit", "parent_id", "name_filter", "is_trash"} },
    ["heygen.list_sessions"] = { method = "GET", url = "https://api2.heygen.com/v1/streaming.list" },
    ["heygen.list_supported_languages"] = { method = "GET", url = "https://api2.heygen.com/v2/video_translate/target_languages" },
    ["heygen.list_templates_v2"] = { method = "GET", url = "https://api2.heygen.com/v2/templates" },
    ["heygen.list_voices_v2"] = { method = "GET", url = "https://api2.heygen.com/v2/voices" },
    ["heygen.list_webhook_endpoints"] = { method = "GET", url = "https://api2.heygen.com/v1/webhook/endpoint.list" },
    ["heygen.new_session"] = { method = "POST", url = "https://api2.heygen.com/v1/streaming.new", body = {"quality", "avatar_id", "voice_name", "voice", "knowledge_base", "video_encoding", "disable_idle_timeout", "version"} },
    ["heygen.photo_avatar_details"] = { method = "GET", url = "https://api2.heygen.com/v2/photo_avatar/{id}", path = {"id"} },
    ["heygen.restore_folder"] = { method = "POST", url = "https://api2.heygen.com/v1/folders/{folder_id}/restore", path = {"folder_id"} },
    ["heygen.send_task"] = { method = "POST", url = "https://api2.heygen.com/v1/streaming.task", body = {"RAW_BODY"} },
    ["heygen.start_session"] = { method = "POST", url = "https://api2.heygen.com/v1/streaming.start", body = {"session_id"} },
    ["heygen.streaming_avatar_list"] = { method = "GET", url = "https://api2.heygen.com/v1/streaming/avatar.list" },
    ["heygen.submit_video_avatar_creation_request"] = { method = "POST", url = "https://api2.heygen.com/v2/video_avatar", body = {"training_footage_url", "video_consent_url", "avatar_name", "avatar_group_id", "callback_id", "callback_url"} },
    ["heygen.train_photo_avatar_group"] = { method = "POST", url = "https://api2.heygen.com/v2/photo_avatar/train", body = {"group_id"} },
    ["heygen.trash_folder"] = { method = "POST", url = "https://api2.heygen.com/v1/folders/{folder_id}/trash", path = {"folder_id"} },
    ["heygen.update_a_webhook_endpoint"] = { method = "PATCH", url = "https://api2.heygen.com/v1/webhook/endpoint.update", body = {"endpoint_id", "url", "events"} },
    ["heygen.update_brand_voice"] = { method = "POST", url = "https://api2.heygen.com/v1/brand_voice/{brand_voice_id}", path = {"brand_voice_id"}, body = {"name", "blacklist", "whitelist", "tones", "vocabulary", "tone"} },
    ["heygen.update_folder"] = { method = "POST", url = "https://api2.heygen.com/v1/folders/{folder_id}", path = {"folder_id"}, body = {"name"} },
    ["heygen.upload_asset"] = { method = "POST", url = "https://api2.heygen.com/v1/asset", header = {"Content-Type"} },
    ["heygen.upscale_an_avatar"] = { method = "POST", url = "https://api2.heygen.com/v2/photo_avatar/upscale", body = {"id"} },
    ["heygen.video_list"] = { method = "GET", url = "https://api2.heygen.com/v1/video.list", query = {"limit", "folder_id", "title"} },
    ["heygen.video_status"] = { method = "GET", url = "https://api2.heygen.com/v1/video_status.get", query = {"video_id"} },
    ["heygen.video_translate"] = { method = "POST", url = "https://api2.heygen.com/v2/video_translate", body = {"video_url", "title", "output_language", "translate_audio_only", "speaker_num", "callback_id", "enable_dynamic_duration", "brand_voice_id", "callback_url"} },
    ["heygen.video_translate_status"] = { method = "GET", url = "https://api2.heygen.com/v2/video_translate/{video_translate_id}", path = {"video_translate_id"} },
  },
}
