-- LeadMagic — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/LeadMagic/leadmagic-openapi/main/leadmagic-openapi-3.1.json
-- Published by LeadMagic, the vendor's own GitHub organisation.
-- 90 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "leadmagic",
  name = "LeadMagic",
  base = "https://api.leadmagic.io",
  docs = "https://nango.dev/docs/integrations/all/leadmagic",
  auth = {
    kind = "key",
    header = "x-api-key",
    format = "{token}",
    env = "LEADMAGIC_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["leadmagic.add_suppression_emails"] = { method = "POST", url = "https://api.leadmagic.io/v1/batch/suppression-lists/{listId}/emails", path = {"listId"}, body = {"emails"} },
    ["leadmagic.analytics_credits"] = { method = "GET", url = "https://api.leadmagic.io/v1/analytics/credits", query = {"days"} },
    ["leadmagic.analytics_daily"] = { method = "GET", url = "https://api.leadmagic.io/v1/analytics/daily", query = {"days"} },
    ["leadmagic.analytics_dashboard"] = { method = "GET", url = "https://api.leadmagic.io/v1/analytics/dashboard" },
    ["leadmagic.analytics_day"] = { method = "GET", url = "https://api.leadmagic.io/v1/analytics/day/{date}", path = {"date"} },
    ["leadmagic.analytics_products"] = { method = "GET", url = "https://api.leadmagic.io/v1/analytics/products", query = {"days"} },
    ["leadmagic.analytics_summary"] = { method = "GET", url = "https://api.leadmagic.io/v1/analytics/summary", query = {"start_date", "end_date"} },
    ["leadmagic.analytics_usage"] = { method = "GET", url = "https://api.leadmagic.io/v1/analytics/usage", query = {"days"} },
    ["leadmagic.b2b_ad_details"] = { method = "POST", url = "https://api.leadmagic.io/v1/ads/b2b-ads-details", body = {"ad_url"} },
    ["leadmagic.b2b_ads_search"] = { method = "POST", url = "https://api.leadmagic.io/v1/ads/b2b-ads-search", body = {"company_domain", "company_name", "limit"} },
    ["leadmagic.b2b_profile_email"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/b2b-profile-email", body = {"profile_url"} },
    ["leadmagic.batch_campaign_metrics"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/campaign/{campaignId}/metrics", path = {"campaignId"} },
    ["leadmagic.batch_client_create"] = { method = "POST", url = "https://api.leadmagic.io/v1/batch/clients", body = {"name", "display_name", "contact_email", "billing_rate", "notes", "industry", "website", "phone", "address", "custom_fields"} },
    ["leadmagic.batch_client_list"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/clients" },
    ["leadmagic.batch_client_metrics"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/clients/{clientId}/metrics", path = {"clientId"} },
    ["leadmagic.batch_client_webhook_create"] = { method = "POST", url = "https://api.leadmagic.io/v1/batch/clients/{clientId}/webhooks", path = {"clientId"} },
    ["leadmagic.batch_client_webhook_list"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/clients/{clientId}/webhooks", path = {"clientId"} },
    ["leadmagic.batch_list"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch", query = {"product", "status", "client_id", "limit", "offset"} },
    ["leadmagic.batch_provider_create"] = { method = "POST", url = "https://api.leadmagic.io/v1/batch/providers", body = {"name", "baseUrl", "authType", "authCredentialName", "authCredentialValue", "defaultMethod", "defaultHeaders", "rateLimitRpm", "responseMapping", "healthCheckUrl", "healthCheckExpectedStatus"} },
    ["leadmagic.batch_provider_list"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/providers" },
    ["leadmagic.batch_status"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/{batchId}", path = {"batchId"} },
    ["leadmagic.batch_submit"] = { method = "POST", url = "https://api.leadmagic.io/v1/batch", body = {"items", "idempotencyKey", "metadata", "client_id", "client_name", "budget_user_id", "webhook_url", "priority"} },
    ["leadmagic.batch_update"] = { method = "PATCH", url = "https://api.leadmagic.io/v1/{product}/batch/{batchId}", path = {"product", "batchId"}, body = {"metadata", "client_id"} },
    ["leadmagic.budget_status"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/budgets/status" },
    ["leadmagic.bulk_capabilities"] = { method = "GET", url = "https://api.leadmagic.io/bulk/capabilities" },
    ["leadmagic.bulk_job_download"] = { method = "GET", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/download", path = {"jobId"} },
    ["leadmagic.bulk_job_errors"] = { method = "GET", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/errors", path = {"jobId"}, query = {"limit", "offset", "status"} },
    ["leadmagic.bulk_job_events"] = { method = "GET", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/events", path = {"jobId"}, query = {"limit"} },
    ["leadmagic.bulk_job_list"] = { method = "GET", url = "https://api.leadmagic.io/bulk/jobs", query = {"status", "product", "limit", "offset"} },
    ["leadmagic.bulk_job_pause"] = { method = "POST", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/pause", path = {"jobId"} },
    ["leadmagic.bulk_job_priority"] = { method = "PATCH", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/priority", path = {"jobId"}, body = {"priority"} },
    ["leadmagic.bulk_job_progress"] = { method = "GET", url = "https://api.leadmagic.io/bulk/progress", query = {"jobId"} },
    ["leadmagic.bulk_job_restart"] = { method = "POST", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/restart", path = {"jobId"}, body = {"mode", "startRowIndex", "startShardIndex"} },
    ["leadmagic.bulk_job_results"] = { method = "GET", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/results", path = {"jobId"}, query = {"limit", "offset", "status"} },
    ["leadmagic.bulk_job_resume"] = { method = "POST", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/resume", path = {"jobId"} },
    ["leadmagic.bulk_job_review"] = { method = "POST", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/review", path = {"jobId"}, body = {"action"} },
    ["leadmagic.bulk_job_status"] = { method = "GET", url = "https://api.leadmagic.io/bulk/jobs/{jobId}", path = {"jobId"} },
    ["leadmagic.bulk_job_stream"] = { method = "GET", url = "https://api.leadmagic.io/bulk/jobs/{jobId}/stream", path = {"jobId"} },
    ["leadmagic.bulk_local_leads"] = { method = "POST", url = "https://api.leadmagic.io/bulk/local-leads", body = {"keywords", "cities", "countryCodes", "fileName", "magicKey"} },
    ["leadmagic.bulk_submit"] = { method = "POST", url = "https://api.leadmagic.io/bulk/submit", body = {"product", "rows", "csv", "fileUrl", "format", "scrape", "inputMapping", "callback", "idempotencyKey", "metadata", "presetId", "outputTransform", "priority", "fileName"} },
    ["leadmagic.bulk_validate"] = { method = "POST", url = "https://api.leadmagic.io/bulk/validate", body = {"product", "rows", "csv", "fileUrl", "format", "scrape", "inputMapping", "callback", "idempotencyKey", "metadata", "presetId", "outputTransform", "priority", "fileName"} },
    ["leadmagic.check_credits"] = { method = "GET", url = "https://api.leadmagic.io/v1/credits" },
    ["leadmagic.company_funding"] = { method = "POST", url = "https://api.leadmagic.io/v1/companies/company-funding", body = {"company_name", "company_domain"} },
    ["leadmagic.company_lookalike_v3"] = { method = "POST", url = "https://api.leadmagic.io/v3/companies/lookalike", body = {"company_domain", "domain", "website", "company_website", "company_name", "name", "description", "company_description", "seed", "company_filters", "filters", "limit", "offset"} },
    ["leadmagic.company_search"] = { method = "POST", url = "https://api.leadmagic.io/v1/companies/company-search", body = {"profile_url", "company_domain", "company_name"} },
    ["leadmagic.company_search_v3"] = { method = "POST", url = "https://api.leadmagic.io/v3/companies/search", body = {"company_domain", "domain", "website", "company_name", "profile_url", "linkedin_url", "company_filters", "query", "limit", "cursor", "offset"} },
    ["leadmagic.competitors_search"] = { method = "POST", url = "https://api.leadmagic.io/v1/companies/competitors-search", body = {"company_domain", "company_url", "company_name"} },
    ["leadmagic.create_budget"] = { method = "POST", url = "https://api.leadmagic.io/v1/batch/budgets", body = {"scope", "scope_value", "max_credits", "period", "alert_threshold_pct", "alert_email"} },
    ["leadmagic.create_suppression_list"] = { method = "POST", url = "https://api.leadmagic.io/v1/batch/suppression-lists", body = {"list_id", "emails"} },
    ["leadmagic.delete_budget"] = { method = "DELETE", url = "https://api.leadmagic.io/v1/batch/budgets/{id}", path = {"id"} },
    ["leadmagic.delete_suppression_list"] = { method = "DELETE", url = "https://api.leadmagic.io/v1/batch/suppression-lists/{listId}", path = {"listId"} },
    ["leadmagic.email_finder"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/email-finder", body = {"first_name", "last_name", "full_name", "domain", "company_name"} },
    ["leadmagic.email_to_b2b_profile"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/b2b-profile", body = {"work_email", "personal_email"} },
    ["leadmagic.email_validation"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/email-validation", body = {"email"} },
    ["leadmagic.employee_finder"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/employee-finder", body = {"company_domain", "company_name", "limit"} },
    ["leadmagic.get_suppression_list"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/suppression-lists/{listId}", path = {"listId"}, query = {"limit", "offset"} },
    ["leadmagic.google_ads_search"] = { method = "POST", url = "https://api.leadmagic.io/v1/ads/google-ads-search", body = {"company_domain", "company_name", "limit"} },
    ["leadmagic.job_board_stats"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/job-board/stats" },
    ["leadmagic.job_change_detector"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/job-change-detector", body = {"profile_url", "company_name", "company_domain"} },
    ["leadmagic.job_company_types"] = { method = "GET", url = "https://api.leadmagic.io/v1/jobs/company-types" },
    ["leadmagic.job_country"] = { method = "GET", url = "https://api.leadmagic.io/v1/jobs/countries" },
    ["leadmagic.job_industry"] = { method = "GET", url = "https://api.leadmagic.io/v1/jobs/industries" },
    ["leadmagic.job_regions"] = { method = "GET", url = "https://api.leadmagic.io/v1/jobs/regions" },
    ["leadmagic.job_search"] = { method = "POST", url = "https://api.leadmagic.io/v3/jobs/search", body = {"titles", "occupationTaxonomy", "companies", "location", "tags", "salary", "seniority", "postedAfter", "postedBefore", "postedWithin", "languages", "hasRemote", "jobTypeIds", "industryIds", "companyTypeIds", "companySizeCodes", "limit", "cursor", "includeDescription", "includeFacets", "totalMode", "mode", "autoResolve"} },
    ["leadmagic.job_search_alias"] = { method = "POST", url = "https://api.leadmagic.io/v3/jobs-search", body = {"titles", "location", "tags", "limit", "totalMode", "mode"} },
    ["leadmagic.job_search_catalogs"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/catalogs" },
    ["leadmagic.job_search_companies"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/companies", query = {"q", "domain", "limit"} },
    ["leadmagic.job_search_export"] = { method = "POST", url = "https://api.leadmagic.io/v3/jobs/search/export", body = {"titles", "companies", "location", "tags", "occupationTaxonomy", "salary", "workModes", "postedWithin", "includeDescription", "includeCompany", "limit"} },
    ["leadmagic.job_search_locations"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/locations", query = {"q", "type", "limit"} },
    ["leadmagic.job_search_occupation_taxonomy"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/occupation-taxonomy", query = {"q", "level", "limit"} },
    ["leadmagic.job_search_resolve"] = { method = "POST", url = "https://api.leadmagic.io/v3/jobs/search/resolve", body = {"companies", "tags", "occupationTaxonomy", "location", "titles"} },
    ["leadmagic.job_search_roles"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/roles", query = {"q", "limit"} },
    ["leadmagic.job_search_stats"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/stats" },
    ["leadmagic.job_search_tags"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/tags", query = {"q", "tag_type", "limit"} },
    ["leadmagic.job_search_titles"] = { method = "GET", url = "https://api.leadmagic.io/v3/jobs/search/titles", query = {"q", "limit"} },
    ["leadmagic.job_types"] = { method = "GET", url = "https://api.leadmagic.io/v1/jobs/job-types" },
    ["leadmagic.jobs_finder"] = { method = "POST", url = "https://api.leadmagic.io/v1/jobs/jobs-finder", body = {"company_name", "company_website", "job_title", "location", "experience_level", "job_description", "city_name", "country_id", "region_id", "job_type_id", "company_type_id", "company_industry_id", "min_employees", "max_employees", "has_remote", "posted_within", "posted_after", "posted_before", "page", "per_page"} },
    ["leadmagic.list_budgets"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/budgets" },
    ["leadmagic.list_suppression_lists"] = { method = "GET", url = "https://api.leadmagic.io/v1/batch/suppression-lists" },
    ["leadmagic.meta_ads_search"] = { method = "POST", url = "https://api.leadmagic.io/v1/ads/meta-ads-search", body = {"company_domain", "company_name", "limit"} },
    ["leadmagic.mobile_finder"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/mobile-finder", body = {"profile_url", "work_email", "personal_email"} },
    ["leadmagic.people_search"] = { method = "POST", url = "https://api.leadmagic.io/v3/people/search", body = {"company_domain", "company_name", "linkedin_url", "company_filters", "people_filters", "title", "job_title", "titles", "roles", "query", "required_email", "required_mobile", "channels", "channel_match", "include_company", "include_domain_intel", "include_contact_details", "include_email", "include_mobile", "confirm_credit_charge", "limit", "cursor", "offset"} },
    ["leadmagic.personal_email_finder"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/personal-email-finder", body = {"profile_url"} },
    ["leadmagic.preview_cost_mixed"] = { method = "POST", url = "https://api.leadmagic.io/v1/batch/preview-cost", body = {"items", "budget_user_id", "client_id", "client_name", "metadata"} },
    ["leadmagic.profile_search"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/profile-search", body = {"profile_url"} },
    ["leadmagic.remove_suppression_emails"] = { method = "DELETE", url = "https://api.leadmagic.io/v1/batch/suppression-lists/{listId}/emails", path = {"listId"}, body = {"emails"} },
    ["leadmagic.role_finder"] = { method = "POST", url = "https://api.leadmagic.io/v1/people/role-finder", body = {"company_name", "company_domain", "job_title"} },
    ["leadmagic.search_stats_v3"] = { method = "POST", url = "https://api.leadmagic.io/v3/search/stats", body = {"products", "sections", "limit"} },
    ["leadmagic.technographics"] = { method = "POST", url = "https://api.leadmagic.io/v1/companies/technographics", body = {"company_domain"} },
    ["leadmagic.update_budget"] = { method = "PATCH", url = "https://api.leadmagic.io/v1/batch/budgets/{id}", path = {"id"}, body = {"max_credits", "period", "alert_threshold_pct", "alert_email"} },
  },
}
