-- Apify — every call this API accepts, as data.
--
-- GENERATED from https://docs.apify.com/api/openapi.json
-- Published on the vendor's own documentation site (https://docs.apify.com).
-- 224 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "apify",
  name = "Apify",
  base = "https://api.apify.com",
  docs = "https://nango.dev/docs/integrations/all/apify",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "APIFY_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["apify.actor_build_abort_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-builds/{buildId}/abort", path = {"buildId"} },
    ["apify.actor_build_default_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/builds/default", path = {"actorId"}, query = {"waitForFinish"} },
    ["apify.actor_build_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-builds/{buildId}", path = {"buildId"} },
    ["apify.actor_build_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-builds/{buildId}", path = {"buildId"}, query = {"waitForFinish"} },
    ["apify.actor_build_log_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-builds/{buildId}/log", path = {"buildId"}, query = {"stream", "download"} },
    ["apify.actor_build_openapi_json_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-builds/{buildId}/openapi.json", path = {"buildId"} },
    ["apify.actor_builds_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-builds", query = {"offset", "limit", "desc"} },
    ["apify.actor_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}", path = {"actorId"} },
    ["apify.actor_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}", path = {"actorId"} },
    ["apify.actor_openapi_json_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/builds/{buildId}/openapi.json", path = {"actorId", "buildId"} },
    ["apify.actor_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}", path = {"actorId"}, body = {"name", "description", "isPublic", "actorPermissionLevel", "seoTitle", "seoDescription", "title", "restartOnError", "versions", "pricingInfos", "categories", "defaultRunOptions", "taggedBuilds", "actorStandby", "exampleRunInput", "isDeprecated"} },
    ["apify.actor_run_abort_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/abort", path = {"runId"}, query = {"gracefully"} },
    ["apify.actor_run_dataset_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-runs/{runId}/dataset", path = {"runId"} },
    ["apify.actor_run_dataset_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/dataset", path = {"runId"} },
    ["apify.actor_run_dataset_items_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/dataset/items", path = {"runId"}, query = {"format", "clean", "offset", "limit", "fields", "outputFields", "omit", "unwind", "flatten", "desc", "attachment", "delimiter", "bom", "xmlRoot", "xmlRow", "skipHeaderRow", "skipHidden", "skipEmpty", "simplified", "view", "skipFailedPages", "feedTitle", "feedDescription", "signature"} },
    ["apify.actor_run_dataset_items_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/dataset/items", path = {"runId"}, header = {"Content-Encoding"} },
    ["apify.actor_run_dataset_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-runs/{runId}/dataset", path = {"runId"}, body = {"name", "generalAccess"} },
    ["apify.actor_run_dataset_statistics_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/dataset/statistics", path = {"runId"} },
    ["apify.actor_run_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-runs/{runId}", path = {"runId"} },
    ["apify.actor_run_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}", path = {"runId"}, query = {"waitForFinish"} },
    ["apify.actor_run_key_value_store_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store", path = {"runId"} },
    ["apify.actor_run_key_value_store_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store", path = {"runId"} },
    ["apify.actor_run_key_value_store_keys_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store/keys", path = {"runId"}, query = {"exclusiveStartKey", "limit", "collection", "prefix", "signature"} },
    ["apify.actor_run_key_value_store_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store", path = {"runId"}, body = {"name", "generalAccess"} },
    ["apify.actor_run_key_value_store_record_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store/records/{recordKey}", path = {"runId", "recordKey"} },
    ["apify.actor_run_key_value_store_record_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store/records/{recordKey}", path = {"runId", "recordKey"}, query = {"signature", "attachment"} },
    ["apify.actor_run_key_value_store_record_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store/records/{recordKey}", path = {"runId", "recordKey"}, header = {"Content-Encoding"} },
    ["apify.actor_run_key_value_store_record_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store/records/{recordKey}", path = {"runId", "recordKey"}, header = {"Content-Encoding"} },
    ["apify.actor_run_key_value_store_records_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/key-value-store/records", path = {"runId"}, query = {"collection", "prefix", "signature"} },
    ["apify.actor_run_log_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/log", path = {"runId"}, query = {"stream", "download", "raw"} },
    ["apify.actor_run_metamorph_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/metamorph", path = {"runId"}, query = {"targetActorId", "build"} },
    ["apify.actor_run_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-runs/{runId}", path = {"runId"}, body = {"runId", "statusMessage", "isStatusMessageTerminal", "generalAccess"} },
    ["apify.actor_run_reboot_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/reboot", path = {"runId"} },
    ["apify.actor_run_request_queue_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue", path = {"runId"} },
    ["apify.actor_run_request_queue_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue", path = {"runId"} },
    ["apify.actor_run_request_queue_head_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/head", path = {"runId"}, query = {"limit", "clientKey"} },
    ["apify.actor_run_request_queue_head_lock_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/head/lock", path = {"runId"}, query = {"lockSecs", "limit", "clientKey"} },
    ["apify.actor_run_request_queue_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue", path = {"runId"}, body = {"name", "generalAccess"} },
    ["apify.actor_run_request_queue_request_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests/{requestId}", path = {"runId", "requestId"}, query = {"clientKey"} },
    ["apify.actor_run_request_queue_request_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests/{requestId}", path = {"runId", "requestId"} },
    ["apify.actor_run_request_queue_request_lock_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests/{requestId}/lock", path = {"runId", "requestId"}, query = {"clientKey", "forefront"} },
    ["apify.actor_run_request_queue_request_lock_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests/{requestId}/lock", path = {"runId", "requestId"}, query = {"lockSecs", "clientKey", "forefront"} },
    ["apify.actor_run_request_queue_request_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests/{requestId}", path = {"runId", "requestId"}, query = {"forefront", "clientKey"}, body = {"uniqueKey", "url", "method", "retryCount", "loadedUrl", "payload", "headers", "userData", "noRetry", "errorMessages", "handledAt"} },
    ["apify.actor_run_request_queue_requests_batch_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests/batch", path = {"runId"}, query = {"clientKey"}, header = {"Content-Type"} },
    ["apify.actor_run_request_queue_requests_batch_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests/batch", path = {"runId"}, query = {"clientKey", "forefront"} },
    ["apify.actor_run_request_queue_requests_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests", path = {"runId"}, query = {"clientKey", "exclusiveStartId", "limit", "cursor", "filter"} },
    ["apify.actor_run_request_queue_requests_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests", path = {"runId"}, query = {"clientKey", "forefront"}, body = {"uniqueKey", "url", "method", "retryCount", "loadedUrl", "payload", "headers", "userData", "noRetry", "errorMessages", "handledAt"} },
    ["apify.actor_run_request_queue_requests_unlock_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/request-queue/requests/unlock", path = {"runId"}, query = {"clientKey"} },
    ["apify.actor_run_resurrect_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/{runId}/resurrect", path = {"actorId", "runId"}, query = {"build", "timeout", "memory", "restartOnError"} },
    ["apify.actor_run_sync_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/run-sync", path = {"actorId"}, query = {"outputRecordKey", "timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError", "build", "webhooks"} },
    ["apify.actor_run_sync_get_dataset_items_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/run-sync-get-dataset-items", path = {"actorId"}, query = {"timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError", "build", "webhooks", "format", "clean", "offset", "limit", "fields", "outputFields", "omit", "unwind", "flatten", "desc", "attachment", "delimiter", "bom", "xmlRoot", "xmlRow", "skipHeaderRow", "skipHidden", "skipEmpty", "simplified", "view", "skipFailedPages", "feedTitle", "feedDescription"} },
    ["apify.actor_run_sync_get_dataset_items_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/run-sync-get-dataset-items", path = {"actorId"}, query = {"timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError", "build", "webhooks", "format", "clean", "offset", "limit", "fields", "outputFields", "omit", "unwind", "flatten", "desc", "attachment", "delimiter", "bom", "xmlRoot", "xmlRow", "skipHeaderRow", "skipHidden", "skipEmpty", "simplified", "view", "skipFailedPages", "feedTitle", "feedDescription"} },
    ["apify.actor_run_sync_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/run-sync", path = {"actorId"}, query = {"outputRecordKey", "timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError", "build", "webhooks"} },
    ["apify.actor_runs_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-runs", query = {"offset", "limit", "desc", "status", "startedAfter", "startedBefore"} },
    ["apify.actor_runs_last_abort_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/abort", path = {"actorId"}, query = {"status", "origin", "gracefully"} },
    ["apify.actor_runs_last_dataset_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/dataset", path = {"actorId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_dataset_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/dataset", path = {"actorId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_dataset_items_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/dataset/items", path = {"actorId"}, query = {"status", "origin", "format", "clean", "offset", "limit", "fields", "outputFields", "omit", "unwind", "flatten", "desc", "attachment", "delimiter", "bom", "xmlRoot", "xmlRow", "skipHeaderRow", "skipHidden", "skipEmpty", "simplified", "view", "skipFailedPages", "feedTitle", "feedDescription", "signature"} },
    ["apify.actor_runs_last_dataset_items_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/dataset/items", path = {"actorId"}, query = {"status", "origin"}, header = {"Content-Encoding"} },
    ["apify.actor_runs_last_dataset_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/dataset", path = {"actorId"}, query = {"status", "origin"}, body = {"name", "generalAccess"} },
    ["apify.actor_runs_last_dataset_statistics_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/dataset/statistics", path = {"actorId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last", path = {"actorId"}, query = {"status", "origin", "waitForFinish"} },
    ["apify.actor_runs_last_key_value_store_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store", path = {"actorId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_key_value_store_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store", path = {"actorId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_key_value_store_keys_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store/keys", path = {"actorId"}, query = {"status", "origin", "exclusiveStartKey", "limit", "collection", "prefix", "signature"} },
    ["apify.actor_runs_last_key_value_store_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store", path = {"actorId"}, query = {"status", "origin"}, body = {"name", "generalAccess"} },
    ["apify.actor_runs_last_key_value_store_record_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store/records/{recordKey}", path = {"actorId", "recordKey"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_key_value_store_record_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store/records/{recordKey}", path = {"actorId", "recordKey"}, query = {"status", "origin", "signature", "attachment"} },
    ["apify.actor_runs_last_key_value_store_record_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store/records/{recordKey}", path = {"actorId", "recordKey"}, query = {"status", "origin"}, header = {"Content-Encoding"} },
    ["apify.actor_runs_last_key_value_store_record_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store/records/{recordKey}", path = {"actorId", "recordKey"}, query = {"status", "origin"}, header = {"Content-Encoding"} },
    ["apify.actor_runs_last_key_value_store_records_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/key-value-store/records", path = {"actorId"}, query = {"status", "origin", "collection", "prefix", "signature"} },
    ["apify.actor_runs_last_log_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/log", path = {"actorId"}, query = {"status", "origin", "stream", "download", "raw"} },
    ["apify.actor_runs_last_metamorph_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/metamorph", path = {"actorId"}, query = {"status", "origin", "targetActorId", "build"} },
    ["apify.actor_runs_last_reboot_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/reboot", path = {"actorId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_request_queue_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue", path = {"actorId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_request_queue_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue", path = {"actorId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_request_queue_head_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/head", path = {"actorId"}, query = {"status", "origin", "limit", "clientKey"} },
    ["apify.actor_runs_last_request_queue_head_lock_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/head/lock", path = {"actorId"}, query = {"status", "origin", "lockSecs", "limit", "clientKey"} },
    ["apify.actor_runs_last_request_queue_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue", path = {"actorId"}, query = {"status", "origin"}, body = {"name", "generalAccess"} },
    ["apify.actor_runs_last_request_queue_request_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}", path = {"actorId", "requestId"}, query = {"status", "origin", "clientKey"} },
    ["apify.actor_runs_last_request_queue_request_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}", path = {"actorId", "requestId"}, query = {"status", "origin"} },
    ["apify.actor_runs_last_request_queue_request_lock_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}/lock", path = {"actorId", "requestId"}, query = {"status", "origin", "clientKey", "forefront"} },
    ["apify.actor_runs_last_request_queue_request_lock_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}/lock", path = {"actorId", "requestId"}, query = {"status", "origin", "lockSecs", "clientKey", "forefront"} },
    ["apify.actor_runs_last_request_queue_request_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}", path = {"actorId", "requestId"}, query = {"status", "origin", "forefront", "clientKey"}, body = {"uniqueKey", "url", "method", "retryCount", "loadedUrl", "payload", "headers", "userData", "noRetry", "errorMessages", "handledAt"} },
    ["apify.actor_runs_last_request_queue_requests_batch_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests/batch", path = {"actorId"}, query = {"status", "origin", "clientKey"}, header = {"Content-Type"} },
    ["apify.actor_runs_last_request_queue_requests_batch_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests/batch", path = {"actorId"}, query = {"status", "origin", "clientKey", "forefront"} },
    ["apify.actor_runs_last_request_queue_requests_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests", path = {"actorId"}, query = {"status", "origin", "clientKey", "exclusiveStartId", "limit", "cursor", "filter"} },
    ["apify.actor_runs_last_request_queue_requests_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests", path = {"actorId"}, query = {"status", "origin", "clientKey", "forefront"}, body = {"uniqueKey", "url", "method", "retryCount", "loadedUrl", "payload", "headers", "userData", "noRetry", "errorMessages", "handledAt"} },
    ["apify.actor_runs_last_request_queue_requests_unlock_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs/last/request-queue/requests/unlock", path = {"actorId"}, query = {"status", "origin", "clientKey"} },
    ["apify.actor_task_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}", path = {"actorTaskId"} },
    ["apify.actor_task_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}", path = {"actorTaskId"} },
    ["apify.actor_task_input_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/input", path = {"actorTaskId"} },
    ["apify.actor_task_input_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/input", path = {"actorTaskId"} },
    ["apify.actor_task_last_log_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/log", path = {"actorTaskId"}, query = {"status", "origin", "stream", "download", "raw"} },
    ["apify.actor_task_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}", path = {"actorTaskId"}, body = {"name", "options", "input", "title", "description", "actorStandby", "publicConfig", "isPublic"} },
    ["apify.actor_task_run_sync_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/run-sync", path = {"actorTaskId"}, query = {"timeout", "memory", "maxItems", "maxTotalChargeUsd", "build", "outputRecordKey", "webhooks"} },
    ["apify.actor_task_run_sync_get_dataset_items_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/run-sync-get-dataset-items", path = {"actorTaskId"}, query = {"timeout", "memory", "maxItems", "maxTotalChargeUsd", "build", "webhooks", "format", "clean", "offset", "limit", "fields", "outputFields", "omit", "unwind", "flatten", "desc", "attachment", "delimiter", "bom", "xmlRoot", "xmlRow", "skipHeaderRow", "skipHidden", "skipEmpty", "simplified", "view", "skipFailedPages", "feedTitle", "feedDescription"} },
    ["apify.actor_task_run_sync_get_dataset_items_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/run-sync-get-dataset-items", path = {"actorTaskId"}, query = {"timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError", "build", "webhooks", "format", "clean", "offset", "limit", "fields", "outputFields", "omit", "unwind", "flatten", "desc", "attachment", "delimiter", "bom", "xmlRoot", "xmlRow", "skipHeaderRow", "skipHidden", "skipEmpty", "simplified", "view", "skipFailedPages", "feedTitle", "feedDescription"} },
    ["apify.actor_task_run_sync_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/run-sync", path = {"actorTaskId"}, query = {"timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError", "build", "outputRecordKey", "webhooks"} },
    ["apify.actor_task_runs_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs", path = {"actorTaskId"}, query = {"offset", "limit", "desc", "status"} },
    ["apify.actor_task_runs_last_abort_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/abort", path = {"actorTaskId"}, query = {"status", "origin", "gracefully"} },
    ["apify.actor_task_runs_last_dataset_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/dataset", path = {"actorTaskId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_dataset_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/dataset", path = {"actorTaskId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_dataset_items_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/dataset/items", path = {"actorTaskId"}, query = {"status", "origin", "format", "clean", "offset", "limit", "fields", "outputFields", "omit", "unwind", "flatten", "desc", "attachment", "delimiter", "bom", "xmlRoot", "xmlRow", "skipHeaderRow", "skipHidden", "skipEmpty", "simplified", "view", "skipFailedPages", "feedTitle", "feedDescription", "signature"} },
    ["apify.actor_task_runs_last_dataset_items_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/dataset/items", path = {"actorTaskId"}, query = {"status", "origin"}, header = {"Content-Encoding"} },
    ["apify.actor_task_runs_last_dataset_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/dataset", path = {"actorTaskId"}, query = {"status", "origin"}, body = {"name", "generalAccess"} },
    ["apify.actor_task_runs_last_dataset_statistics_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/dataset/statistics", path = {"actorTaskId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last", path = {"actorTaskId"}, query = {"status", "origin", "waitForFinish"} },
    ["apify.actor_task_runs_last_key_value_store_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store", path = {"actorTaskId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_key_value_store_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store", path = {"actorTaskId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_key_value_store_keys_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/keys", path = {"actorTaskId"}, query = {"status", "origin", "exclusiveStartKey", "limit", "collection", "prefix", "signature"} },
    ["apify.actor_task_runs_last_key_value_store_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store", path = {"actorTaskId"}, query = {"status", "origin"}, body = {"name", "generalAccess"} },
    ["apify.actor_task_runs_last_key_value_store_record_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records/{recordKey}", path = {"actorTaskId", "recordKey"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_key_value_store_record_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records/{recordKey}", path = {"actorTaskId", "recordKey"}, query = {"status", "origin", "signature", "attachment"} },
    ["apify.actor_task_runs_last_key_value_store_record_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records/{recordKey}", path = {"actorTaskId", "recordKey"}, query = {"status", "origin"}, header = {"Content-Encoding"} },
    ["apify.actor_task_runs_last_key_value_store_record_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records/{recordKey}", path = {"actorTaskId", "recordKey"}, query = {"status", "origin"}, header = {"Content-Encoding"} },
    ["apify.actor_task_runs_last_key_value_store_records_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records", path = {"actorTaskId"}, query = {"status", "origin", "collection", "prefix", "signature"} },
    ["apify.actor_task_runs_last_metamorph_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/metamorph", path = {"actorTaskId"}, query = {"status", "origin", "targetActorId", "build"} },
    ["apify.actor_task_runs_last_reboot_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/reboot", path = {"actorTaskId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_request_queue_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue", path = {"actorTaskId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_request_queue_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue", path = {"actorTaskId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_request_queue_head_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/head", path = {"actorTaskId"}, query = {"status", "origin", "limit", "clientKey"} },
    ["apify.actor_task_runs_last_request_queue_head_lock_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/head/lock", path = {"actorTaskId"}, query = {"status", "origin", "lockSecs", "limit", "clientKey"} },
    ["apify.actor_task_runs_last_request_queue_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue", path = {"actorTaskId"}, query = {"status", "origin"}, body = {"name", "generalAccess"} },
    ["apify.actor_task_runs_last_request_queue_request_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}", path = {"actorTaskId", "requestId"}, query = {"status", "origin", "clientKey"} },
    ["apify.actor_task_runs_last_request_queue_request_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}", path = {"actorTaskId", "requestId"}, query = {"status", "origin"} },
    ["apify.actor_task_runs_last_request_queue_request_lock_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}/lock", path = {"actorTaskId", "requestId"}, query = {"status", "origin", "clientKey", "forefront"} },
    ["apify.actor_task_runs_last_request_queue_request_lock_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}/lock", path = {"actorTaskId", "requestId"}, query = {"status", "origin", "lockSecs", "clientKey", "forefront"} },
    ["apify.actor_task_runs_last_request_queue_request_put"] = { method = "PUT", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}", path = {"actorTaskId", "requestId"}, query = {"status", "origin", "forefront", "clientKey"}, body = {"uniqueKey", "url", "method", "retryCount", "loadedUrl", "payload", "headers", "userData", "noRetry", "errorMessages", "handledAt"} },
    ["apify.actor_task_runs_last_request_queue_requests_batch_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/batch", path = {"actorTaskId"}, query = {"status", "origin", "clientKey"}, header = {"Content-Type"} },
    ["apify.actor_task_runs_last_request_queue_requests_batch_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/batch", path = {"actorTaskId"}, query = {"status", "origin", "clientKey", "forefront"} },
    ["apify.actor_task_runs_last_request_queue_requests_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests", path = {"actorTaskId"}, query = {"status", "origin", "clientKey", "exclusiveStartId", "limit", "cursor", "filter"} },
    ["apify.actor_task_runs_last_request_queue_requests_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests", path = {"actorTaskId"}, query = {"status", "origin", "clientKey", "forefront"}, body = {"uniqueKey", "url", "method", "retryCount", "loadedUrl", "payload", "headers", "userData", "noRetry", "errorMessages", "handledAt"} },
    ["apify.actor_task_runs_last_request_queue_requests_unlock_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/unlock", path = {"actorTaskId"}, query = {"status", "origin", "clientKey"} },
    ["apify.actor_task_runs_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/runs", path = {"actorTaskId"}, query = {"timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError", "build", "waitForFinish", "webhooks"} },
    ["apify.actor_task_webhooks_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks/{actorTaskId}/webhooks", path = {"actorTaskId"}, query = {"offset", "limit", "desc"} },
    ["apify.actor_tasks_get"] = { method = "GET", url = "https://api.apify.com/v2/actor-tasks", query = {"offset", "limit", "desc"} },
    ["apify.actor_tasks_post"] = { method = "POST", url = "https://api.apify.com/v2/actor-tasks", body = {"actId", "name", "options", "input", "title", "description", "actorStandby", "publicConfig"} },
    ["apify.actor_validate_input_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/validate-input", path = {"actorId"}, query = {"build"} },
    ["apify.actor_version_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}", path = {"actorId", "versionNumber"} },
    ["apify.actor_version_env_var_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}", path = {"actorId", "versionNumber", "envVarName"} },
    ["apify.actor_version_env_var_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}", path = {"actorId", "versionNumber", "envVarName"} },
    ["apify.actor_version_env_var_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}", path = {"actorId", "versionNumber", "envVarName"}, body = {"name", "value", "isSecret"} },
    ["apify.actor_version_env_var_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}", path = {"actorId", "versionNumber", "envVarName"}, body = {"name", "value", "isSecret"} },
    ["apify.actor_version_env_vars_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}/env-vars", path = {"actorId", "versionNumber"} },
    ["apify.actor_version_env_vars_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}/env-vars", path = {"actorId", "versionNumber"}, body = {"name", "value", "isSecret"} },
    ["apify.actor_version_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}", path = {"actorId", "versionNumber"} },
    ["apify.actor_version_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}", path = {"actorId", "versionNumber"}, body = {"versionNumber", "sourceType", "envVars", "applyEnvVarsToBuild", "buildTag", "sourceFiles", "gitRepoUrl", "tarballUrl", "gitHubGistUrl"} },
    ["apify.actor_version_put"] = { method = "PUT", url = "https://api.apify.com/v2/actors/{actorId}/versions/{versionNumber}", path = {"actorId", "versionNumber"}, body = {"versionNumber", "sourceType", "envVars", "applyEnvVarsToBuild", "buildTag", "sourceFiles", "gitRepoUrl", "tarballUrl", "gitHubGistUrl"} },
    ["apify.actor_versions_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/versions", path = {"actorId"} },
    ["apify.actor_versions_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/versions", path = {"actorId"}, body = {"versionNumber", "sourceType", "envVars", "applyEnvVarsToBuild", "buildTag", "sourceFiles", "gitRepoUrl", "tarballUrl", "gitHubGistUrl"} },
    ["apify.actor_webhooks_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/webhooks", path = {"actorId"}, query = {"offset", "limit", "desc"} },
    ["apify.actors_builds_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/builds", path = {"actorId"}, query = {"offset", "limit", "desc"} },
    ["apify.actors_builds_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/builds", path = {"actorId"}, query = {"version", "useCache", "betaPackages", "tag", "waitForFinish"} },
    ["apify.actors_get"] = { method = "GET", url = "https://api.apify.com/v2/actors", query = {"my", "offset", "limit", "desc", "sortBy"} },
    ["apify.actors_post"] = { method = "POST", url = "https://api.apify.com/v2/actors", body = {"name", "description", "title", "isPublic", "seoTitle", "seoDescription", "restartOnError", "versions", "categories", "defaultRunOptions", "actorStandby", "exampleRunInput", "isDeprecated"} },
    ["apify.actors_runs_get"] = { method = "GET", url = "https://api.apify.com/v2/actors/{actorId}/runs", path = {"actorId"}, query = {"offset", "limit", "desc", "status", "startedAfter", "startedBefore"} },
    ["apify.actors_runs_post"] = { method = "POST", url = "https://api.apify.com/v2/actors/{actorId}/runs", path = {"actorId"}, query = {"timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError", "build", "waitForFinish", "webhooks", "forcePermissionLevel"} },
    ["apify.dataset_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/datasets/{datasetId}", path = {"datasetId"} },
    ["apify.dataset_get"] = { method = "GET", url = "https://api.apify.com/v2/datasets/{datasetId}", path = {"datasetId"} },
    ["apify.dataset_items_get"] = { method = "GET", url = "https://api.apify.com/v2/datasets/{datasetId}/items", path = {"datasetId"}, query = {"format", "clean", "offset", "limit", "fields", "outputFields", "omit", "unwind", "flatten", "desc", "attachment", "delimiter", "bom", "xmlRoot", "xmlRow", "skipHeaderRow", "skipHidden", "skipEmpty", "simplified", "view", "skipFailedPages", "feedTitle", "feedDescription", "signature"} },
    ["apify.dataset_items_post"] = { method = "POST", url = "https://api.apify.com/v2/datasets/{datasetId}/items", path = {"datasetId"}, header = {"Content-Encoding"} },
    ["apify.dataset_put"] = { method = "PUT", url = "https://api.apify.com/v2/datasets/{datasetId}", path = {"datasetId"}, body = {"name", "generalAccess"} },
    ["apify.dataset_statistics_get"] = { method = "GET", url = "https://api.apify.com/v2/datasets/{datasetId}/statistics", path = {"datasetId"} },
    ["apify.datasets_get"] = { method = "GET", url = "https://api.apify.com/v2/datasets", query = {"offset", "limit", "desc", "unnamed", "ownership"} },
    ["apify.datasets_post"] = { method = "POST", url = "https://api.apify.com/v2/datasets", query = {"name"} },
    ["apify.key_value_store_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/key-value-stores/{storeId}", path = {"storeId"} },
    ["apify.key_value_store_get"] = { method = "GET", url = "https://api.apify.com/v2/key-value-stores/{storeId}", path = {"storeId"} },
    ["apify.key_value_store_keys_get"] = { method = "GET", url = "https://api.apify.com/v2/key-value-stores/{storeId}/keys", path = {"storeId"}, query = {"exclusiveStartKey", "limit", "collection", "prefix", "signature"} },
    ["apify.key_value_store_put"] = { method = "PUT", url = "https://api.apify.com/v2/key-value-stores/{storeId}", path = {"storeId"}, body = {"name", "generalAccess"} },
    ["apify.key_value_store_record_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/key-value-stores/{storeId}/records/{recordKey}", path = {"storeId", "recordKey"} },
    ["apify.key_value_store_record_get"] = { method = "GET", url = "https://api.apify.com/v2/key-value-stores/{storeId}/records/{recordKey}", path = {"storeId", "recordKey"}, query = {"attachment", "signature"} },
    ["apify.key_value_store_record_post"] = { method = "POST", url = "https://api.apify.com/v2/key-value-stores/{storeId}/records/{recordKey}", path = {"storeId", "recordKey"}, header = {"Content-Encoding"} },
    ["apify.key_value_store_record_put"] = { method = "PUT", url = "https://api.apify.com/v2/key-value-stores/{storeId}/records/{recordKey}", path = {"storeId", "recordKey"}, header = {"Content-Encoding"} },
    ["apify.key_value_store_records_get"] = { method = "GET", url = "https://api.apify.com/v2/key-value-stores/{storeId}/records", path = {"storeId"}, query = {"collection", "prefix", "signature"} },
    ["apify.key_value_stores_get"] = { method = "GET", url = "https://api.apify.com/v2/key-value-stores", query = {"offset", "limit", "desc", "unnamed", "ownership"} },
    ["apify.key_value_stores_post"] = { method = "POST", url = "https://api.apify.com/v2/key-value-stores", query = {"name"} },
    ["apify.log_get"] = { method = "GET", url = "https://api.apify.com/v2/logs/{buildOrRunId}", path = {"buildOrRunId"}, query = {"stream", "download", "raw"} },
    ["apify.post_charge_run"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/charge", path = {"runId"}, header = {"idempotency-key"}, body = {"eventName", "count"} },
    ["apify.post_resurrect_run"] = { method = "POST", url = "https://api.apify.com/v2/actor-runs/{runId}/resurrect", path = {"runId"}, query = {"build", "timeout", "memory", "maxItems", "maxTotalChargeUsd", "restartOnError"} },
    ["apify.request_queue_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/request-queues/{queueId}", path = {"queueId"} },
    ["apify.request_queue_get"] = { method = "GET", url = "https://api.apify.com/v2/request-queues/{queueId}", path = {"queueId"} },
    ["apify.request_queue_head_get"] = { method = "GET", url = "https://api.apify.com/v2/request-queues/{queueId}/head", path = {"queueId"}, query = {"limit", "clientKey"} },
    ["apify.request_queue_head_lock_post"] = { method = "POST", url = "https://api.apify.com/v2/request-queues/{queueId}/head/lock", path = {"queueId"}, query = {"lockSecs", "limit", "clientKey"} },
    ["apify.request_queue_put"] = { method = "PUT", url = "https://api.apify.com/v2/request-queues/{queueId}", path = {"queueId"}, body = {"name", "generalAccess"} },
    ["apify.request_queue_request_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/request-queues/{queueId}/requests/{requestId}", path = {"queueId", "requestId"}, query = {"clientKey"} },
    ["apify.request_queue_request_get"] = { method = "GET", url = "https://api.apify.com/v2/request-queues/{queueId}/requests/{requestId}", path = {"queueId", "requestId"} },
    ["apify.request_queue_request_lock_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/request-queues/{queueId}/requests/{requestId}/lock", path = {"queueId", "requestId"}, query = {"clientKey", "forefront"} },
    ["apify.request_queue_request_lock_put"] = { method = "PUT", url = "https://api.apify.com/v2/request-queues/{queueId}/requests/{requestId}/lock", path = {"queueId", "requestId"}, query = {"lockSecs", "clientKey", "forefront"} },
    ["apify.request_queue_request_put"] = { method = "PUT", url = "https://api.apify.com/v2/request-queues/{queueId}/requests/{requestId}", path = {"queueId", "requestId"}, query = {"forefront", "clientKey"}, body = {"uniqueKey", "url", "method", "retryCount", "loadedUrl", "payload", "headers", "userData", "noRetry", "errorMessages", "handledAt"} },
    ["apify.request_queue_requests_batch_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/request-queues/{queueId}/requests/batch", path = {"queueId"}, query = {"clientKey"}, header = {"Content-Type"} },
    ["apify.request_queue_requests_batch_post"] = { method = "POST", url = "https://api.apify.com/v2/request-queues/{queueId}/requests/batch", path = {"queueId"}, query = {"clientKey", "forefront"} },
    ["apify.request_queue_requests_get"] = { method = "GET", url = "https://api.apify.com/v2/request-queues/{queueId}/requests", path = {"queueId"}, query = {"clientKey", "exclusiveStartId", "limit", "cursor", "filter"} },
    ["apify.request_queue_requests_post"] = { method = "POST", url = "https://api.apify.com/v2/request-queues/{queueId}/requests", path = {"queueId"}, query = {"clientKey", "forefront"}, body = {"uniqueKey", "url", "method", "retryCount", "loadedUrl", "payload", "headers", "userData", "noRetry", "errorMessages", "handledAt"} },
    ["apify.request_queue_requests_unlock_post"] = { method = "POST", url = "https://api.apify.com/v2/request-queues/{queueId}/requests/unlock", path = {"queueId"}, query = {"clientKey"} },
    ["apify.request_queues_get"] = { method = "GET", url = "https://api.apify.com/v2/request-queues", query = {"offset", "limit", "desc", "unnamed", "ownership"} },
    ["apify.request_queues_post"] = { method = "POST", url = "https://api.apify.com/v2/request-queues", query = {"name"} },
    ["apify.schedule_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/schedules/{scheduleId}", path = {"scheduleId"} },
    ["apify.schedule_get"] = { method = "GET", url = "https://api.apify.com/v2/schedules/{scheduleId}", path = {"scheduleId"} },
    ["apify.schedule_log_get"] = { method = "GET", url = "https://api.apify.com/v2/schedules/{scheduleId}/log", path = {"scheduleId"} },
    ["apify.schedule_put"] = { method = "PUT", url = "https://api.apify.com/v2/schedules/{scheduleId}", path = {"scheduleId"}, body = {"name", "isEnabled", "isExclusive", "cronExpression", "timezone", "description", "title", "actions"} },
    ["apify.schedules_get"] = { method = "GET", url = "https://api.apify.com/v2/schedules", query = {"offset", "limit", "desc"} },
    ["apify.schedules_post"] = { method = "POST", url = "https://api.apify.com/v2/schedules", body = {"name", "isEnabled", "isExclusive", "cronExpression", "timezone", "description", "title", "actions"} },
    ["apify.store_get"] = { method = "GET", url = "https://api.apify.com/v2/store", query = {"limit", "offset", "search", "sortBy", "category", "username", "pricingModel", "allowsAgenticUsers", "responseFormat", "includeUnrunnableActors"} },
    ["apify.tools_browser_info_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/browser-info", query = {"skipHeaders", "rawHeaders"} },
    ["apify.tools_browser_info_get"] = { method = "GET", url = "https://api.apify.com/v2/browser-info", query = {"skipHeaders", "rawHeaders"} },
    ["apify.tools_browser_info_post"] = { method = "POST", url = "https://api.apify.com/v2/browser-info", query = {"skipHeaders", "rawHeaders"} },
    ["apify.tools_browser_info_put"] = { method = "PUT", url = "https://api.apify.com/v2/browser-info", query = {"skipHeaders", "rawHeaders"} },
    ["apify.tools_decode_and_verify_post"] = { method = "POST", url = "https://api.apify.com/v2/tools/decode-and-verify", body = {"encoded"} },
    ["apify.tools_encode_and_sign_post"] = { method = "POST", url = "https://api.apify.com/v2/tools/encode-and-sign" },
    ["apify.user_get"] = { method = "GET", url = "https://api.apify.com/v2/users/{userId}", path = {"userId"} },
    ["apify.users_me_get"] = { method = "GET", url = "https://api.apify.com/v2/users/me" },
    ["apify.users_me_limits_get"] = { method = "GET", url = "https://api.apify.com/v2/users/me/limits" },
    ["apify.users_me_limits_put"] = { method = "PUT", url = "https://api.apify.com/v2/users/me/limits", body = {"maxMonthlyUsageUsd", "dataRetentionDays"} },
    ["apify.users_me_usage_monthly_get"] = { method = "GET", url = "https://api.apify.com/v2/users/me/usage/monthly", query = {"date"} },
    ["apify.webhook_delete"] = { method = "DELETE", url = "https://api.apify.com/v2/webhooks/{webhookId}", path = {"webhookId"} },
    ["apify.webhook_dispatch_get"] = { method = "GET", url = "https://api.apify.com/v2/webhook-dispatches/{dispatchId}", path = {"dispatchId"} },
    ["apify.webhook_dispatches_get"] = { method = "GET", url = "https://api.apify.com/v2/webhook-dispatches", query = {"offset", "limit", "desc"} },
    ["apify.webhook_get"] = { method = "GET", url = "https://api.apify.com/v2/webhooks/{webhookId}", path = {"webhookId"} },
    ["apify.webhook_put"] = { method = "PUT", url = "https://api.apify.com/v2/webhooks/{webhookId}", path = {"webhookId"}, body = {"isAdHoc", "eventTypes", "condition", "ignoreSslErrors", "doNotRetry", "requestUrl", "payloadTemplate", "headersTemplate", "description", "shouldInterpolateStrings"} },
    ["apify.webhook_test_post"] = { method = "POST", url = "https://api.apify.com/v2/webhooks/{webhookId}/test", path = {"webhookId"} },
    ["apify.webhook_webhook_dispatches_get"] = { method = "GET", url = "https://api.apify.com/v2/webhooks/{webhookId}/dispatches", path = {"webhookId"}, query = {"offset", "limit", "desc"} },
    ["apify.webhooks_get"] = { method = "GET", url = "https://api.apify.com/v2/webhooks", query = {"offset", "limit", "desc"} },
    ["apify.webhooks_post"] = { method = "POST", url = "https://api.apify.com/v2/webhooks", body = {"isAdHoc", "eventTypes", "condition", "idempotencyKey", "ignoreSslErrors", "doNotRetry", "requestUrl", "payloadTemplate", "headersTemplate", "description", "shouldInterpolateStrings"} },
  },
}
