-- ScrollStash — every call this API accepts, as data.
--
-- GENERATED from https://api.scrollstash.com/v1/openapi.json
-- Published on the vendor's own documentation site (https://api.scrollstash.com).
-- 58 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "scrollstash-mcp",
  name = "ScrollStash",
  base = "https://mcp.scrollstash.com",
  docs = "https://nango.dev/docs/api-integrations/scrollstash-mcp",
  auth = {
    kind = "oauth",
    header = "authorization",
    format = "Bearer {token}",
    env = "SCROLLSTASH_MCP_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["scrollstash-mcp.ads_by_brand"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/ads", path = {"brandId"}, query = {"limit", "cursor", "status", "format"} },
    ["scrollstash-mcp.ads_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/ads/{adId}", path = {"adId"} },
    ["scrollstash-mcp.ads_search"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/ads", query = {"limit", "cursor", "q", "brand_id", "format", "status", "country", "started_after"} },
    ["scrollstash-mcp.alerts_create"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts", path = {"ws"}, body = {"name", "event_type", "brand_ids", "cadence", "enabled", "email", "webhook_url", "webhook_kind"} },
    ["scrollstash-mcp.alerts_delete"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts/{alertId}", path = {"ws", "alertId"} },
    ["scrollstash-mcp.alerts_deliveries"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alert-deliveries", path = {"ws"}, query = {"alert_id", "limit", "cursor"} },
    ["scrollstash-mcp.alerts_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.alerts_rotate_webhook_secret"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts/webhook-secret", path = {"ws"} },
    ["scrollstash-mcp.alerts_test"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts/{alertId}/test", path = {"ws", "alertId"} },
    ["scrollstash-mcp.alerts_update"] = { method = "PATCH", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/alerts/{alertId}", path = {"ws", "alertId"}, body = {"name", "event_type", "brand_ids", "cadence", "enabled", "email", "webhook_url", "webhook_kind"} },
    ["scrollstash-mcp.api_keys_create"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys", path = {"ws"}, body = {"name", "scopes"} },
    ["scrollstash-mcp.api_keys_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.api_keys_revoke"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys/{keyId}", path = {"ws", "keyId"} },
    ["scrollstash-mcp.api_keys_revoke_unused"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys/revoke-unused", path = {"ws"}, body = {"unused_days"} },
    ["scrollstash-mcp.api_keys_rotate"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/api-keys/{keyId}/rotate", path = {"ws", "keyId"} },
    ["scrollstash-mcp.audience_segments"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/audience/{segment}", path = {"segment"}, query = {"limit", "cursor", "category_id"} },
    ["scrollstash-mcp.brands_breakdown"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/breakdown", path = {"brandId"} },
    ["scrollstash-mcp.brands_demographics"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/demographics", path = {"brandId"} },
    ["scrollstash-mcp.brands_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}", path = {"brandId"} },
    ["scrollstash-mcp.brands_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands", query = {"limit", "cursor", "category_id", "country", "q", "letter", "sort"} },
    ["scrollstash-mcp.brands_similar"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/similar", path = {"brandId"}, query = {"limit"} },
    ["scrollstash-mcp.brands_sitemap"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/sitemap", query = {"limit", "cursor", "category_id"} },
    ["scrollstash-mcp.brands_tech_stack"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/tech-stack", path = {"brandId"} },
    ["scrollstash-mcp.brands_track"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/tracked-brands", path = {"ws"}, body = {"brand_id", "cadence"} },
    ["scrollstash-mcp.brands_tracked"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/tracked-brands", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.brands_tracked_freshness"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/tracked-brands/freshness", path = {"ws"} },
    ["scrollstash-mcp.brands_trajectory"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/trajectory", path = {"brandId"} },
    ["scrollstash-mcp.brands_untrack"] = { method = "DELETE", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/tracked-brands/{brandId}", path = {"ws", "brandId"} },
    ["scrollstash-mcp.brands_velocity"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/velocity", path = {"brandId"}, query = {"weeks"} },
    ["scrollstash-mcp.briefs_feedback"] = { method = "PATCH", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/briefs/{briefId}", path = {"ws", "briefId"}, body = {"feedback"} },
    ["scrollstash-mcp.briefs_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/briefs/{briefId}", path = {"ws", "briefId"} },
    ["scrollstash-mcp.briefs_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/briefs", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.categories_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/categories/{categoryId}", path = {"categoryId"} },
    ["scrollstash-mcp.categories_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/categories", query = {"limit", "cursor", "parent_id", "slug"} },
    ["scrollstash-mcp.categories_sitemap"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/categories/sitemap", query = {"limit", "cursor"} },
    ["scrollstash-mcp.categories_stats"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/categories/{categoryId}/stats", path = {"categoryId"} },
    ["scrollstash-mcp.creatives_for_ad"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/ads/{adId}/creatives", path = {"adId"} },
    ["scrollstash-mcp.creatives_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/creatives/{creativeId}", path = {"creativeId"} },
    ["scrollstash-mcp.creatives_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/creatives", query = {"limit", "cursor", "ad_id", "brand_id"} },
    ["scrollstash-mcp.me_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/me" },
    ["scrollstash-mcp.operators_family"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/brands/{brandId}/operators", path = {"brandId"} },
    ["scrollstash-mcp.operators_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/operators/{operatorId}", path = {"operatorId"} },
    ["scrollstash-mcp.operators_hubs"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/hubs", query = {"limit", "cursor"} },
    ["scrollstash-mcp.operators_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/operators", query = {"limit", "cursor", "q"} },
    ["scrollstash-mcp.pages_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/pages/{pageId}", path = {"pageId"} },
    ["scrollstash-mcp.pages_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/pages", query = {"limit", "cursor", "brand_id", "page_type", "category_id", "q", "sort"} },
    ["scrollstash-mcp.radar_feed"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/radar", path = {"ws"}, query = {"days", "limit", "cursor"} },
    ["scrollstash-mcp.radar_signals"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/radar/signals", path = {"ws"}, query = {"days", "limit", "cursor"} },
    ["scrollstash-mcp.rankings_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/rankings", query = {"limit", "cursor", "category_id", "country", "sort"} },
    ["scrollstash-mcp.rankings_new_advertisers"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/rankings/new-advertisers", query = {"limit", "cursor", "category_id", "days"} },
    ["scrollstash-mcp.rankings_risers"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/rankings/risers", query = {"limit", "cursor", "category_id"} },
    ["scrollstash-mcp.reports_create"] = { method = "POST", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/reports", path = {"ws"}, body = {"kind", "title", "brand_ids", "from", "to", "idempotency_key"} },
    ["scrollstash-mcp.reports_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/reports/{reportId}", path = {"ws", "reportId"} },
    ["scrollstash-mcp.reports_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/workspaces/{ws}/reports", path = {"ws"}, query = {"limit", "cursor"} },
    ["scrollstash-mcp.system_freshness"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/system/freshness" },
    ["scrollstash-mcp.tools_brands"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/tools/{toolSlug}/brands", path = {"toolSlug"}, query = {"limit", "cursor", "category_id", "country"} },
    ["scrollstash-mcp.tools_get"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/tools/{toolSlug}", path = {"toolSlug"} },
    ["scrollstash-mcp.tools_list"] = { method = "GET", url = "https://mcp.scrollstash.com/v1/tools", query = {"limit", "cursor"} },
  },
}
