-- DiscoLike — every call this API accepts, as data.
--
-- GENERATED from https://api.discolike.com/v1/openapi.json
-- Published on the vendor's own documentation site (https://api.discolike.com).
-- 57 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "discolike",
  name = "DiscoLike",
  base = "https://api.discolike.com",
  docs = "https://nango.dev/docs/api-integrations/discolike",
  auth = {
    kind = "key",
    header = "x-discolike-key",
    format = "{token}",
    env = "DISCOLIKE_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["discolike.append_endpoint_append_post"] = { method = "POST", url = "https://api.discolike.com/append", query = {"domain_column", "csv", "dataset", "query_id"}, body = {"file"} },
    ["discolike.authorize_crm_provider_authorize_get"] = { method = "GET", url = "https://api.discolike.com/crm/{provider}/authorize", path = {"provider"} },
    ["discolike.batch_enumerate_email_find_batch_post"] = { method = "POST", url = "https://api.discolike.com/email/find/batch", body = {"source_query_id", "refs", "round", "requests"} },
    ["discolike.bizdata_bizdata_get"] = { method = "GET", url = "https://api.discolike.com/bizdata", query = {"domain"} },
    ["discolike.bulk_contact_match_api_contacts_bulk_match_post"] = { method = "POST", url = "https://api.discolike.com/contacts/bulk-match", body = {"queries", "enrich", "limit"} },
    ["discolike.bulk_match_bulkmatch_post"] = { method = "POST", url = "https://api.discolike.com/bulkmatch", query = {"name_column", "phone_column", "city_column", "state_column", "country_column", "zip_code_column", "strict", "local_mode", "min_match_confidence"}, body = {"file"} },
    ["discolike.cancel_ongoing_task_task_cancel_task_id_delete"] = { method = "DELETE", url = "https://api.discolike.com/{task}/cancel/{task_id}", path = {"task", "task_id"} },
    ["discolike.clear_default_search_provider_search_providers_integration_id_default_delete"] = { method = "DELETE", url = "https://api.discolike.com/search-providers/{integration_id}/default", path = {"integration_id"} },
    ["discolike.contact_match_api_contacts_match_get"] = { method = "GET", url = "https://api.discolike.com/contacts/match", query = {"name", "company_name", "domain", "person_country", "limit"} },
    ["discolike.contacts_api_contacts_get"] = { method = "GET", url = "https://api.discolike.com/contacts", query = {"filter_industry", "negate_filter_industry", "filter_country", "negate_filter_country", "filter_state", "negate_filter_state", "employee_range", "revenue_range", "seniority", "negate_seniority", "department", "negate_department", "skills", "name", "title", "negate_title", "summary", "negate_summary", "person_country", "negate_person_country", "person_state", "has_email", "email_validated", "has_phone", "has_mobile", "has_linkedin", "min_connections", "jobstart_date", "persona_id", "icp_text", "negate_icp_text", "icp_prompt", "domain", "inclusion_query_id", "exclusion_query_id", "max_records", "max_companies", "offset", "results_by_company", "include_search_contacts", "consensus"} },
    ["discolike.contacts_count_api_contacts_count_get"] = { method = "GET", url = "https://api.discolike.com/contacts/count", query = {"filter_industry", "negate_filter_industry", "filter_country", "negate_filter_country", "filter_state", "negate_filter_state", "employee_range", "revenue_range", "seniority", "negate_seniority", "department", "negate_department", "skills", "name", "title", "negate_title", "summary", "negate_summary", "person_country", "negate_person_country", "person_state", "has_email", "email_validated", "has_phone", "has_mobile", "has_linkedin", "min_connections", "jobstart_date", "persona_id", "icp_text", "negate_icp_text", "icp_prompt", "domain", "inclusion_query_id", "exclusion_query_id", "max_records", "max_companies", "offset", "results_by_company", "include_search_contacts", "consensus"} },
    ["discolike.contacts_discover_contacts_discover_post"] = { method = "POST", url = "https://api.discolike.com/contacts/discover", body = {"filter_industry", "negate_filter_industry", "filter_country", "negate_filter_country", "filter_state", "negate_filter_state", "employee_range", "revenue_range", "seniority", "negate_seniority", "department", "negate_department", "skills", "name", "title", "negate_title", "summary", "negate_summary", "person_country", "negate_person_country", "person_state", "has_email", "email_validated", "has_phone", "has_mobile", "has_linkedin", "min_connections", "jobstart_date", "persona_id", "icp_text", "negate_icp_text", "icp_prompt", "domain", "inclusion_query_id", "exclusion_query_id", "max_records", "max_companies", "offset", "results_by_company", "include_search_contacts", "consensus"} },
    ["discolike.contacts_discover_generate_contacts_discover_generate_post"] = { method = "POST", url = "https://api.discolike.com/contacts/discover/generate", body = {"icp_text", "domains", "context_mode", "integration_id", "search_provider_id", "search_context_size", "max_contacts_per_domain", "max_company_records", "full_domains", "partial_domains", "initial_contact_counts"} },
    ["discolike.count_api_count_get"] = { method = "GET", url = "https://api.discolike.com/count", query = {"phrase_match", "negate_phrase_match", "subdomain", "negate_subdomain", "tech_stack", "negate_tech_stack", "category", "negate_category", "min_digital_footprint", "max_digital_footprint", "state", "negate_state", "country", "negate_country", "start_date", "redirect", "social", "negate_social", "language", "negate_language", "employee_range", "revenue_range", "business_model", "negate_business_model", "exclude_leadgen", "exact_match", "negate_exact_match", "vendor", "negate_vendor", "min_score", "max_score"} },
    ["discolike.create_exclusion_list_queries_exclusion_list_post"] = { method = "POST", url = "https://api.discolike.com/queries/exclusion-list", body = {"query_name", "domains", "persona_ids", "tags"} },
    ["discolike.create_llm_integration_llm_providers_config_post"] = { method = "POST", url = "https://api.discolike.com/llm-providers/config", body = {"integration_name", "provider", "model_name", "base_url"} },
    ["discolike.create_public_signup_public_signup_post"] = { method = "POST", url = "https://api.discolike.com/public/signup", body = {"email", "first_name", "last_name", "agent"} },
    ["discolike.create_search_provider_search_providers_post"] = { method = "POST", url = "https://api.discolike.com/search-providers", body = {"integration_name", "provider", "search_model", "base_url"} },
    ["discolike.delete_connection_crm_provider_connection_delete"] = { method = "DELETE", url = "https://api.discolike.com/crm/{provider}/connection", path = {"provider"} },
    ["discolike.delete_llm_integration_llm_providers_config_integration_id_delete"] = { method = "DELETE", url = "https://api.discolike.com/llm-providers/config/{integration_id}", path = {"integration_id"} },
    ["discolike.delete_query_queries_query_id_delete"] = { method = "DELETE", url = "https://api.discolike.com/queries/{query_id}", path = {"query_id"} },
    ["discolike.delete_search_provider_search_providers_integration_id_delete"] = { method = "DELETE", url = "https://api.discolike.com/search-providers/{integration_id}", path = {"integration_id"} },
    ["discolike.discogen_process_discogen_process_post"] = { method = "POST", url = "https://api.discolike.com/discogen/process", body = {"query", "integration_id", "web_search", "include_x_search", "search_provider_id", "search_context_size", "domains", "context_mode", "previous_discogen_data"} },
    ["discolike.discogen_process_personas_discogen_process_personas_post"] = { method = "POST", url = "https://api.discolike.com/discogen/process-personas", body = {"query", "integration_id", "web_search", "include_x_search", "search_provider_id", "search_context_size", "persona_ids", "context_mode", "previous_discogen_data"} },
    ["discolike.discover_api_discover_get"] = { method = "GET", url = "https://api.discolike.com/discover", query = {"phrase_match", "negate_phrase_match", "subdomain", "negate_subdomain", "tech_stack", "negate_tech_stack", "category", "negate_category", "min_digital_footprint", "max_digital_footprint", "state", "negate_state", "country", "negate_country", "start_date", "redirect", "social", "negate_social", "language", "negate_language", "employee_range", "revenue_range", "business_model", "negate_business_model", "exclude_leadgen", "exact_match", "negate_exact_match", "vendor", "negate_vendor", "min_score", "max_score", "domain", "negate_domain", "exclude_domain", "icp_text", "negate_icp_text", "retrieval", "enhanced", "include_search_domains", "max_records", "consensus", "min_similarity", "variance", "offset", "exclusion_query_id", "inclusion_query_id", "auto_icp_text", "auto_phrase_match", "icp_prompt", "nl_match", "negate_nl_match"} },
    ["discolike.enumerate_email_email_find_post"] = { method = "POST", url = "https://api.discolike.com/email/find", body = {"first_name", "last_name", "domain", "known_pattern"} },
    ["discolike.extract_extract_get"] = { method = "GET", url = "https://api.discolike.com/extract", query = {"url", "domain"} },
    ["discolike.get_batch_results_email_batch_batch_id_results_get"] = { method = "GET", url = "https://api.discolike.com/email/batch/{batch_id}/results", path = {"batch_id"} },
    ["discolike.get_job_email_jobs_job_id_get"] = { method = "GET", url = "https://api.discolike.com/email/jobs/{job_id}", path = {"job_id"} },
    ["discolike.get_llm_config_llm_providers_config_get"] = { method = "GET", url = "https://api.discolike.com/llm-providers/config" },
    ["discolike.get_llm_integration_llm_providers_config_integration_id_get"] = { method = "GET", url = "https://api.discolike.com/llm-providers/config/{integration_id}", path = {"integration_id"} },
    ["discolike.get_task_status_task_status_task_id_get"] = { method = "GET", url = "https://api.discolike.com/{task}/status/{task_id}", path = {"task", "task_id"} },
    ["discolike.get_usage_usage_get"] = { method = "GET", url = "https://api.discolike.com/usage" },
    ["discolike.growth_growth_get"] = { method = "GET", url = "https://api.discolike.com/growth", query = {"domain"} },
    ["discolike.list_connections_crm_connections_get"] = { method = "GET", url = "https://api.discolike.com/crm/connections", query = {"probe"} },
    ["discolike.list_models_discogen_models_get"] = { method = "GET", url = "https://api.discolike.com/discogen/models" },
    ["discolike.list_saved_queries_queries_saved_get"] = { method = "GET", url = "https://api.discolike.com/queries/saved", query = {"max_records", "offset", "action", "tags"} },
    ["discolike.list_search_models_search_providers_models_get"] = { method = "GET", url = "https://api.discolike.com/search-providers/models" },
    ["discolike.list_search_providers_search_providers_get"] = { method = "GET", url = "https://api.discolike.com/search-providers" },
    ["discolike.lookup_contact_contacts_lookup_get"] = { method = "GET", url = "https://api.discolike.com/contacts/lookup", query = {"persona_id", "linkedin", "email"} },
    ["discolike.match_api_match_get"] = { method = "GET", url = "https://api.discolike.com/match", query = {"name", "phone", "city", "state", "country", "zip_code", "strict", "local_mode", "min_match_confidence"} },
    ["discolike.publiclink_api_publiclink_get"] = { method = "GET", url = "https://api.discolike.com/publiclink", query = {"domain", "source"} },
    ["discolike.redirects_redirects_get"] = { method = "GET", url = "https://api.discolike.com/redirects", query = {"domain", "match"} },
    ["discolike.save_results_queries_save_results_post"] = { method = "POST", url = "https://api.discolike.com/queries/save-results", body = {"query_name", "action", "query_params", "data", "domain_column", "tags"} },
    ["discolike.score_score_get"] = { method = "GET", url = "https://api.discolike.com/score", query = {"domain"} },
    ["discolike.segment_api_segment_get"] = { method = "GET", url = "https://api.discolike.com/segment", query = {"domains", "query_id", "max_segments"} },
    ["discolike.segment_file_segment_post"] = { method = "POST", url = "https://api.discolike.com/segment", query = {"domain_column", "max_segments", "query_id"}, body = {"file"} },
    ["discolike.set_default_llm_integration_llm_providers_config_integration_id_set_default_post"] = { method = "POST", url = "https://api.discolike.com/llm-providers/config/{integration_id}/set-default", path = {"integration_id"} },
    ["discolike.set_default_search_provider_search_providers_integration_id_default_put"] = { method = "PUT", url = "https://api.discolike.com/search-providers/{integration_id}/default", path = {"integration_id"} },
    ["discolike.subsidiaries_subsidiaries_get"] = { method = "GET", url = "https://api.discolike.com/subsidiaries", query = {"domain", "match"} },
    ["discolike.suppress_crm_provider_suppress_post"] = { method = "POST", url = "https://api.discolike.com/crm/{provider}/suppress", path = {"provider"}, query = {"kind"} },
    ["discolike.test_provider_connection_llm_providers_test_connection_post"] = { method = "POST", url = "https://api.discolike.com/llm-providers/test-connection", body = {"integration_name", "provider", "model_name", "base_url"} },
    ["discolike.update_llm_integration_llm_providers_config_integration_id_put"] = { method = "PUT", url = "https://api.discolike.com/llm-providers/config/{integration_id}", path = {"integration_id"}, body = {"integration_name", "provider", "model_name", "base_url"} },
    ["discolike.update_query_queries_query_id_patch"] = { method = "PATCH", url = "https://api.discolike.com/queries/{query_id}", path = {"query_id"}, body = {"query_name", "tags"} },
    ["discolike.update_search_provider_search_providers_integration_id_put"] = { method = "PUT", url = "https://api.discolike.com/search-providers/{integration_id}", path = {"integration_id"}, body = {"integration_name", "provider", "search_model", "base_url"} },
    ["discolike.validate_icp_validate_icp_post"] = { method = "POST", url = "https://api.discolike.com/validate/icp", body = {"icp_text", "domains", "context_mode", "integration_id", "web_search", "search_provider_id"} },
    ["discolike.vendors_vendors_get"] = { method = "GET", url = "https://api.discolike.com/vendors", query = {"domain", "match"} },
  },
}
