-- ShopVox — every call this API accepts, as data.
--
-- GENERATED from https://developers.shopvox.com/openapi.yaml
-- Published on the vendor's own documentation site (https://developers.shopvox.com).
-- 42 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "shopvox",
  name = "ShopVox",
  base = "https://api.shopvox.com",
  docs = "https://nango.dev/docs/api-integrations/shopvox",
  auth = {
    kind = "manual",
    header = "authorization",
    format = "Bearer {token}",
    env = "SHOPVOX_TOKEN",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["shopvox.complete_job_step"] = { method = "POST", url = "https://api.shopvox.com/v1/jobs/{job_id}/steps/{id}/complete", path = {"job_id", "id"} },
    ["shopvox.create_company"] = { method = "POST", url = "https://api.shopvox.com/v1/companies", body = {"company"} },
    ["shopvox.create_contact"] = { method = "POST", url = "https://api.shopvox.com/v1/contacts", body = {"contact"} },
    ["shopvox.create_job"] = { method = "POST", url = "https://api.shopvox.com/v1/jobs", body = {"job"} },
    ["shopvox.create_note"] = { method = "POST", url = "https://api.shopvox.com/v1/notes", query = {"company_id"}, body = {"note"} },
    ["shopvox.create_payment"] = { method = "POST", url = "https://api.shopvox.com/v1/payments", body = {"payment"} },
    ["shopvox.create_sales_lead"] = { method = "POST", url = "https://api.shopvox.com/v1/sales_leads", body = {"title", "details", "qualified", "company_id", "company_name", "primary_contact_id", "primary_contact_name", "email", "phone_number", "sales_rep_id", "sales_rep_name", "deal_value_in_dollars", "workflow_state", "next_contact_date", "expected_close_date", "lead_source_id", "lead_source_name", "pipeline_id", "pipeline_name", "pipeline_stage_id", "pipeline_stage_name", "division_id", "lead_source_real_name", "asset"} },
    ["shopvox.create_sales_order"] = { method = "POST", url = "https://api.shopvox.com/v1/sales_orders", body = {"sales_order"} },
    ["shopvox.delete_company"] = { method = "DELETE", url = "https://api.shopvox.com/v1/companies/{id}", path = {"id"} },
    ["shopvox.delete_contact"] = { method = "DELETE", url = "https://api.shopvox.com/v1/contacts/{id}", path = {"id"} },
    ["shopvox.delete_note"] = { method = "DELETE", url = "https://api.shopvox.com/v1/notes/{id}", path = {"id"} },
    ["shopvox.delete_sales_lead"] = { method = "DELETE", url = "https://api.shopvox.com/v1/sales_leads/{id}", path = {"id"} },
    ["shopvox.get_company"] = { method = "GET", url = "https://api.shopvox.com/v1/companies/{id}", path = {"id"} },
    ["shopvox.get_connection"] = { method = "GET", url = "https://api.shopvox.com/v1/connections" },
    ["shopvox.get_contact"] = { method = "GET", url = "https://api.shopvox.com/v1/contacts/{id}", path = {"id"} },
    ["shopvox.get_invoice"] = { method = "GET", url = "https://api.shopvox.com/v1/invoices/{id}", path = {"id"}, query = {"txn_number"} },
    ["shopvox.get_job"] = { method = "GET", url = "https://api.shopvox.com/v1/jobs/{id}", path = {"id"} },
    ["shopvox.get_quote"] = { method = "GET", url = "https://api.shopvox.com/v1/quotes/{id}", path = {"id"} },
    ["shopvox.get_sales_lead"] = { method = "GET", url = "https://api.shopvox.com/v1/sales_leads/{id}", path = {"id"} },
    ["shopvox.get_sales_lead_stages"] = { method = "GET", url = "https://api.shopvox.com/v1/sales_leads_stages", query = {"pipeline_id"} },
    ["shopvox.get_sales_order"] = { method = "GET", url = "https://api.shopvox.com/v1/sales_orders/{id}", path = {"id"}, query = {"txn_number"} },
    ["shopvox.list_assets"] = { method = "GET", url = "https://api.shopvox.com/v1/{assetable_type}/{assetable_id}/assets", path = {"assetable_type", "assetable_id"}, query = {"page", "per_page"} },
    ["shopvox.list_companies"] = { method = "GET", url = "https://api.shopvox.com/v1/companies", query = {"name", "active", "page", "per_page"} },
    ["shopvox.list_contacts"] = { method = "GET", url = "https://api.shopvox.com/v1/contacts", query = {"company_id", "active", "name", "search", "with_email", "cportal", "page", "per_page"} },
    ["shopvox.list_invoices"] = { method = "GET", url = "https://api.shopvox.com/v1/invoices", query = {"page", "per_page"} },
    ["shopvox.list_jobs"] = { method = "GET", url = "https://api.shopvox.com/v1/jobs", query = {"txn_type", "txn_number", "page", "per_page"} },
    ["shopvox.list_notes"] = { method = "GET", url = "https://api.shopvox.com/v1/notes", query = {"page", "per_page"} },
    ["shopvox.list_orders"] = { method = "GET", url = "https://api.shopvox.com/v1/orders" },
    ["shopvox.list_payments"] = { method = "GET", url = "https://api.shopvox.com/v1/payments", query = {"page", "per_page"} },
    ["shopvox.list_quotes"] = { method = "GET", url = "https://api.shopvox.com/v1/quotes", query = {"page", "per_page"} },
    ["shopvox.list_sales_leads"] = { method = "GET", url = "https://api.shopvox.com/v1/sales_leads", query = {"page", "per_page"} },
    ["shopvox.list_sales_orders"] = { method = "GET", url = "https://api.shopvox.com/v1/sales_orders", query = {"page", "per_page", "txn_date_from", "txn_date_to"} },
    ["shopvox.login"] = { method = "POST", url = "https://api.shopvox.com/v1/login", body = {"user", "password"} },
    ["shopvox.sign_invoice"] = { method = "POST", url = "https://api.shopvox.com/v1/invoices/{id}/signature", path = {"id"}, body = {"name", "location", "file"} },
    ["shopvox.sign_sales_order"] = { method = "POST", url = "https://api.shopvox.com/v1/sales_orders/{id}/signature", path = {"id"}, body = {"name", "location", "file"} },
    ["shopvox.start_job_step"] = { method = "POST", url = "https://api.shopvox.com/v1/jobs/{job_id}/steps/{id}/start", path = {"job_id", "id"} },
    ["shopvox.stop_job_step"] = { method = "POST", url = "https://api.shopvox.com/v1/jobs/{job_id}/steps/{id}/stop", path = {"job_id", "id"} },
    ["shopvox.update_company"] = { method = "PATCH", url = "https://api.shopvox.com/v1/companies/{id}", path = {"id"}, body = {"company"} },
    ["shopvox.update_contact"] = { method = "PATCH", url = "https://api.shopvox.com/v1/contacts/{id}", path = {"id"}, body = {"contact"} },
    ["shopvox.update_note"] = { method = "PATCH", url = "https://api.shopvox.com/v1/notes/{id}", path = {"id"}, body = {"note"} },
    ["shopvox.update_sales_lead"] = { method = "PATCH", url = "https://api.shopvox.com/v1/sales_leads/{id}", path = {"id"}, body = {"title", "details", "qualified", "company_id", "company_name", "primary_contact_id", "primary_contact_name", "email", "phone_number", "sales_rep_id", "sales_rep_name", "deal_value_in_dollars", "workflow_state", "next_contact_date", "expected_close_date", "lead_source_id", "lead_source_name", "pipeline_id", "pipeline_name", "pipeline_stage_id", "pipeline_stage_name", "division_id", "lead_source_real_name", "asset"} },
    ["shopvox.update_sales_order"] = { method = "PATCH", url = "https://api.shopvox.com/v1/sales_orders/{id}", path = {"id"}, body = {"sales_order"} },
  },
}
