-- Trading Economics — every call this API accepts, as data.
--
-- GENERATED from https://api.tradingeconomics.com/swagger/v1/swagger.json
-- Published on the vendor's own documentation site (https://api.tradingeconomics.com).
-- 168 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "trading-economics",
  name = "Trading Economics",
  base = "https://api.tradingeconomics.com",
  docs = "https://nango.dev/docs/api-integrations/trading-economics",
  auth = {
    kind = "key",
    header = "authorization",
    format = "{token}",
    env = "TRADING_ECONOMICS_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["trading-economics.get_calendar"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar", query = {"limit", "importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_calendarid_ids"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/calendarid/{ids}", path = {"ids"}, query = {"lang", "values", "f"} },
    ["trading-economics.get_calendar_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{country}", path = {"country"}, query = {"limit", "importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_country_country_event_eventName"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{country}/event/{eventName}", path = {"country", "eventName"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_country_country_event_eventName_from_to"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{country}/event/{eventName}/{from}/{to}", path = {"country", "eventName", "from", "to"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_country_country_from_to"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{country}/{from}/{to}", path = {"country", "from", "to"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_country_country_group_group"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{country}/group/{group}", path = {"country", "group"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_country_country_group_group_from_to"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{country}/group/{group}/{from}/{to}", path = {"country", "group", "from", "to"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_country_country_indicator_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{country}/indicator/{indicator}", path = {"country", "indicator"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_country_country_indicator_indicator_from_to"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{country}/indicator/{indicator}/{from}/{to}", path = {"country", "indicator", "from", "to"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_country_from_to"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/country/{from}/{to}", path = {"from", "to"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_events"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/events", query = {"lang", "values", "f"} },
    ["trading-economics.get_calendar_events_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/events/country/{country}", path = {"country"}, query = {"lang", "values", "f"} },
    ["trading-economics.get_calendar_events_indicator_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/events/indicator/{indicator}", path = {"indicator"}, query = {"lang", "values", "f"} },
    ["trading-economics.get_calendar_group_group"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/group/{group}", path = {"group"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_group_group_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/group/{group}/country/{country}", path = {"country", "group"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_group_group_from_to"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/group/{group}/{from}/{to}", path = {"group", "from", "to"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_indicator_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/indicator/{indicator}", path = {"indicator"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_indicator_indicator_from_to"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/indicator/{indicator}/{from}/{to}", path = {"indicator", "from", "to"}, query = {"importance", "lang", "values", "f"} },
    ["trading-economics.get_calendar_ticker_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/ticker/{ticker}", path = {"ticker"}, query = {"lang", "values", "f"} },
    ["trading-economics.get_calendar_ticker_ticker_from_to"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/ticker/{ticker}/{from}/{to}", path = {"ticker", "from", "to"}, query = {"lang", "values", "f"} },
    ["trading-economics.get_calendar_upcoming_country"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/upcoming/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_calendar_updates"] = { method = "GET", url = "https://api.tradingeconomics.com/calendar/updates", query = {"lang", "values", "f"} },
    ["trading-economics.get_changes"] = { method = "GET", url = "https://api.tradingeconomics.com/changes", query = {"f"} },
    ["trading-economics.get_changes_date"] = { method = "GET", url = "https://api.tradingeconomics.com/changes/{date}", path = {"date"}, query = {"f"} },
    ["trading-economics.get_comtrade"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade", query = {"f"} },
    ["trading-economics.get_comtrade_categories"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade/categories", query = {"f"} },
    ["trading-economics.get_comtrade_countries"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade/countries", query = {"f"} },
    ["trading-economics.get_comtrade_country_country1_country2"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade/country/{country1}/{country2}", path = {"country1", "country2"}, query = {"type", "f"} },
    ["trading-economics.get_comtrade_historical_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade/historical/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_comtrade_type_country"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade/{type}/{country}", path = {"type", "country"}, query = {"f"} },
    ["trading-economics.get_comtrade_type_country_category"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade/{type}/{country}/{category}", path = {"type", "country", "category"}, query = {"f"} },
    ["trading-economics.get_comtrade_updates"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade/updates", query = {"f"} },
    ["trading-economics.get_comtrade_updates_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/comtrade/updates/country/{country}", path = {"country"}, query = {"from", "f"} },
    ["trading-economics.get_country"] = { method = "GET", url = "https://api.tradingeconomics.com/country", query = {"f"} },
    ["trading-economics.get_country_all_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/country/all/{indicator}", path = {"indicator"}, query = {"f"} },
    ["trading-economics.get_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/country/{country}", path = {"country"}, query = {"group", "cd", "f"} },
    ["trading-economics.get_country_country_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/country/{country}/{indicator}", path = {"country", "indicator"}, query = {"f"} },
    ["trading-economics.get_credit_ratings"] = { method = "GET", url = "https://api.tradingeconomics.com/credit-ratings", query = {"f"} },
    ["trading-economics.get_credit_ratings_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/credit-ratings/country/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_credit_ratings_historical"] = { method = "GET", url = "https://api.tradingeconomics.com/credit-ratings/historical", query = {"country", "d1", "d2", "f"} },
    ["trading-economics.get_credit_ratings_historical_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/credit-ratings/historical/country/{country}", path = {"country"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_credit_ratings_updates"] = { method = "GET", url = "https://api.tradingeconomics.com/credit-ratings/updates", query = {"country", "d1", "d2", "f"} },
    ["trading-economics.get_dividends"] = { method = "GET", url = "https://api.tradingeconomics.com/dividends", query = {"d1", "d2", "f"} },
    ["trading-economics.get_dividends_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/dividends/symbol/{symbol}", path = {"symbol"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_earnings"] = { method = "GET", url = "https://api.tradingeconomics.com/earnings", query = {"d1", "d2", "type", "f"} },
    ["trading-economics.get_earnings_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/earnings/country/{country}", path = {"country"}, query = {"d1", "d2", "type", "f"} },
    ["trading-economics.get_earnings_revenues"] = { method = "GET", url = "https://api.tradingeconomics.com/earnings-revenues", query = {"d1", "d2", "f"} },
    ["trading-economics.get_earnings_revenues_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/earnings-revenues/country/{country}", path = {"country"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_earnings_revenues_index_index"] = { method = "GET", url = "https://api.tradingeconomics.com/earnings-revenues/index/{index}", path = {"index"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_earnings_revenues_sector_sector"] = { method = "GET", url = "https://api.tradingeconomics.com/earnings-revenues/sector/{sector}", path = {"sector"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_earnings_revenues_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/earnings-revenues/symbol/{symbol}", path = {"symbol"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_earnings_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/earnings/symbol/{symbol}", path = {"symbol"}, query = {"d1", "d2", "type", "f"} },
    ["trading-economics.get_eurostat"] = { method = "GET", url = "https://api.tradingeconomics.com/eurostat", query = {"category", "category_group", "f"} },
    ["trading-economics.get_eurostat_categories"] = { method = "GET", url = "https://api.tradingeconomics.com/eurostat/categories", query = {"f"} },
    ["trading-economics.get_eurostat_countries"] = { method = "GET", url = "https://api.tradingeconomics.com/eurostat/countries", query = {"f"} },
    ["trading-economics.get_eurostat_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/eurostat/country/{country}", path = {"country"}, query = {"category", "category_group", "f"} },
    ["trading-economics.get_eurostat_historical_id"] = { method = "GET", url = "https://api.tradingeconomics.com/eurostat/historical/{id}", path = {"id"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_eurostat_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/eurostat/symbol/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_financials_categories"] = { method = "GET", url = "https://api.tradingeconomics.com/financials/categories", query = {"f"} },
    ["trading-economics.get_financials_category_category"] = { method = "GET", url = "https://api.tradingeconomics.com/financials/category/{category}", path = {"category"}, query = {"f"} },
    ["trading-economics.get_financials_companies"] = { method = "GET", url = "https://api.tradingeconomics.com/financials/companies", query = {"country", "f"} },
    ["trading-economics.get_financials_historical_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/financials/historical/{symbol}", path = {"symbol"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_financials_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/financials/symbol/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_forecast_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/forecast/country/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_forecast_country_country_indicator_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/forecast/country/{country}/indicator/{indicator}", path = {"country", "indicator"}, query = {"f"} },
    ["trading-economics.get_forecast_indicator_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/forecast/indicator/{indicator}", path = {"indicator"}, query = {"f"} },
    ["trading-economics.get_forecast_ticker_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/forecast/ticker/{ticker}", path = {"ticker"}, query = {"f"} },
    ["trading-economics.get_forecast_updates"] = { method = "GET", url = "https://api.tradingeconomics.com/forecast/updates", query = {"country", "date", "f"} },
    ["trading-economics.get_fred_counties_state"] = { method = "GET", url = "https://api.tradingeconomics.com/fred/counties/{state}", path = {"state"}, query = {"f"} },
    ["trading-economics.get_fred_historical_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/fred/historical/{symbol}", path = {"symbol"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_fred_snapshot_country_country_p"] = { method = "GET", url = "https://api.tradingeconomics.com/fred/snapshot/country/{country}/{p}", path = {"country", "p"}, query = {"info", "f"} },
    ["trading-economics.get_fred_snapshot_county_county_p"] = { method = "GET", url = "https://api.tradingeconomics.com/fred/snapshot/county/{county}/{p}", path = {"county", "p"}, query = {"info", "f"} },
    ["trading-economics.get_fred_snapshot_state_state"] = { method = "GET", url = "https://api.tradingeconomics.com/fred/snapshot/state/{state}", path = {"state"}, query = {"info", "f"} },
    ["trading-economics.get_fred_snapshot_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/fred/snapshot/symbol/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_fred_snapshot_url"] = { method = "GET", url = "https://api.tradingeconomics.com/fred/snapshot/url", query = {"url", "info", "f"} },
    ["trading-economics.get_fred_states"] = { method = "GET", url = "https://api.tradingeconomics.com/fred/states", query = {"f"} },
    ["trading-economics.get_gis_collections"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections" },
    ["trading-economics.get_gis_collections_comtrade_exports_country_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/comtrade/exports/{country}/items", path = {"country"}, query = {"partners", "yearFrom", "yearTo"} },
    ["trading-economics.get_gis_collections_comtrade_imports_country_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/comtrade/imports/{country}/items", path = {"country"}, query = {"partners", "yearFrom", "yearTo"} },
    ["trading-economics.get_gis_collections_fred_counties_indicator_indicator_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/fred/counties/indicator/{indicator}/items", path = {"indicator"}, query = {"states", "geometry"} },
    ["trading-economics.get_gis_collections_fred_counties_indicator_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/fred/counties/indicator/items", query = {"indicator", "states", "geometry"} },
    ["trading-economics.get_gis_collections_fred_counties_state_indicator_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/fred/counties/{state}/indicator/items", path = {"state"}, query = {"geometry"} },
    ["trading-economics.get_gis_collections_fred_states_indicator_indicator_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/fred/states/indicator/{indicator}/items", path = {"indicator"}, query = {"states", "geometry"} },
    ["trading-economics.get_gis_collections_fred_states_indicator_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/fred/states/indicator/items", query = {"states", "indicator", "geometry"} },
    ["trading-economics.get_gis_collections_fred_states_state_indicator_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/fred/states/{state}/indicator/items", path = {"state"}, query = {"geometry"} },
    ["trading-economics.get_gis_collections_indicator_indicator_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/indicator/{indicator}/items", path = {"indicator"}, query = {"countries", "geometry", "date", "yearFrom", "yearTo"} },
    ["trading-economics.get_gis_collections_indicator_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/indicator/items", query = {"indicators", "countries", "geometry", "date", "yearFrom", "yearTo"} },
    ["trading-economics.get_gis_collections_map_usa_counties_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/map/usa/counties/items", query = {"geometry"} },
    ["trading-economics.get_gis_collections_map_usa_states_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/map/usa/states/items", query = {"geometry"} },
    ["trading-economics.get_gis_collections_map_world_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/map/world/items", query = {"geometry"} },
    ["trading-economics.get_gis_collections_market_bonds_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/market/bonds/items", query = {"country", "geometry"} },
    ["trading-economics.get_gis_collections_market_currencies_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/market/currencies/items", query = {"country", "cross", "geometry"} },
    ["trading-economics.get_gis_collections_market_indexes_items"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/collections/market/indexes/items", query = {"country", "geometry"} },
    ["trading-economics.get_gis_conformance"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/conformance" },
    ["trading-economics.get_gis_health"] = { method = "GET", url = "https://api.tradingeconomics.com/gis/health" },
    ["trading-economics.get_historical_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/historical/country/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_historical_country_country_indicator_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/historical/country/{country}/indicator/{indicator}", path = {"country", "indicator"}, query = {"d1", "d2", "lu", "f"} },
    ["trading-economics.get_historical_country_country_indicator_indicator_d1_d2"] = { method = "GET", url = "https://api.tradingeconomics.com/historical/country/{country}/indicator/{indicator}/{d1}/{d2}", path = {"country", "indicator", "d1", "d2"}, query = {"lu", "f"} },
    ["trading-economics.get_historical_latest"] = { method = "GET", url = "https://api.tradingeconomics.com/historical/latest", query = {"country", "date", "f"} },
    ["trading-economics.get_historical_symbol_symbol_d1"] = { method = "GET", url = "https://api.tradingeconomics.com/historical/symbol/{symbol}/{d1}", path = {"symbol", "d1"}, query = {"d2", "lu", "f"} },
    ["trading-economics.get_historical_ticker_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/historical/ticker/{ticker}", path = {"ticker"}, query = {"d1", "d2", "lu", "f"} },
    ["trading-economics.get_historical_ticker_ticker_d1_d2"] = { method = "GET", url = "https://api.tradingeconomics.com/historical/ticker/{ticker}/{d1}/{d2}", path = {"ticker", "d1", "d2"}, query = {"lu", "f"} },
    ["trading-economics.get_historical_updates"] = { method = "GET", url = "https://api.tradingeconomics.com/historical/updates", query = {"f"} },
    ["trading-economics.get_icalendar_country_country_indicator_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/icalendar/country/{country}/indicator/{indicator}", path = {"country", "indicator"}, query = {"f"} },
    ["trading-economics.get_icalendar_ticker_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/icalendar/ticker/{ticker}", path = {"ticker"}, query = {"f"} },
    ["trading-economics.get_indicators"] = { method = "GET", url = "https://api.tradingeconomics.com/indicators", query = {"calendar", "country", "f"} },
    ["trading-economics.get_indicators_calendar_country"] = { method = "GET", url = "https://api.tradingeconomics.com/indicators/calendar/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_indicators_country"] = { method = "GET", url = "https://api.tradingeconomics.com/indicators/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_indicators_descriptions"] = { method = "GET", url = "https://api.tradingeconomics.com/indicators/descriptions", query = {"lang", "country", "category", "f"} },
    ["trading-economics.get_indicators_descriptions_all"] = { method = "GET", url = "https://api.tradingeconomics.com/indicators/descriptions/all", query = {"lang", "f"} },
    ["trading-economics.get_indicators_new"] = { method = "GET", url = "https://api.tradingeconomics.com/indicators/new", query = {"from", "f"} },
    ["trading-economics.get_ipo"] = { method = "GET", url = "https://api.tradingeconomics.com/ipo", query = {"d1", "d2", "f"} },
    ["trading-economics.get_ipo_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/ipo/country/{country}", path = {"country"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_ipo_ticker_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/ipo/ticker/{ticker}", path = {"ticker"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_markets_bond"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/bond", query = {"country", "f"} },
    ["trading-economics.get_markets_commodity"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/commodity", query = {"country", "f"} },
    ["trading-economics.get_markets_components_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/components/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_markets_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/country/{country}", path = {"country"}, query = {"cat", "info", "f"} },
    ["trading-economics.get_markets_cross"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/cross", query = {"country", "f"} },
    ["trading-economics.get_markets_crypto"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/crypto", query = {"country", "f"} },
    ["trading-economics.get_markets_currency"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/currency", query = {"country", "f"} },
    ["trading-economics.get_markets_discontinued"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/discontinued", query = {"country", "f"} },
    ["trading-economics.get_markets_forecasts_category"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/forecasts/{category}", path = {"category"}, query = {"f"} },
    ["trading-economics.get_markets_forecasts_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/forecasts/symbol/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_markets_historical_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/historical/{symbol}", path = {"symbol"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_markets_index"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/index", query = {"country", "f"} },
    ["trading-economics.get_markets_intraday_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/intraday/{symbol}", path = {"symbol"}, query = {"d1", "d2", "agr", "f"} },
    ["trading-economics.get_markets_market"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/{market}", path = {"market"}, query = {"country", "f"} },
    ["trading-economics.get_markets_peers_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/peers/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_markets_search_term"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/search/{term}", path = {"term"}, query = {"category", "f"} },
    ["trading-economics.get_markets_stock"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/stock", query = {"country", "f"} },
    ["trading-economics.get_markets_stockdescriptions_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/stockdescriptions/country/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_markets_stockdescriptions_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/stockdescriptions/symbol/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_markets_stocks_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/stocks/country/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_markets_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/symbol/{symbol}", path = {"symbol"}, query = {"s", "f"} },
    ["trading-economics.get_markets_symbology_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/symbology/country/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_markets_symbology_isin_isin"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/symbology/isin/{isin}", path = {"isin"}, query = {"f"} },
    ["trading-economics.get_markets_symbology_symbol_symbol"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/symbology/symbol/{symbol}", path = {"symbol"}, query = {"f"} },
    ["trading-economics.get_markets_symbology_ticker_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/symbology/ticker/{ticker}", path = {"ticker"}, query = {"f"} },
    ["trading-economics.get_markets_v2"] = { method = "GET", url = "https://api.tradingeconomics.com/markets/v2", query = {"s", "f"} },
    ["trading-economics.get_news"] = { method = "GET", url = "https://api.tradingeconomics.com/news", query = {"type", "d1", "d2", "f"} },
    ["trading-economics.get_news_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/news/country/{country}", path = {"country"}, query = {"type", "d1", "d2", "f"} },
    ["trading-economics.get_news_country_country_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/news/country/{country}/{indicator}", path = {"country", "indicator"}, query = {"type", "d1", "d2", "f"} },
    ["trading-economics.get_news_indicator_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/news/indicator/{indicator}", path = {"indicator"}, query = {"type", "d1", "d2", "f"} },
    ["trading-economics.get_news_ticker_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/news/ticker/{ticker}", path = {"ticker"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_peers_country_country_category"] = { method = "GET", url = "https://api.tradingeconomics.com/peers/country/{country}/{category}", path = {"country", "category"}, query = {"f"} },
    ["trading-economics.get_peers_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/peers/{ticker}", path = {"ticker"}, query = {"f"} },
    ["trading-economics.get_ratings"] = { method = "GET", url = "https://api.tradingeconomics.com/ratings", query = {"country", "f"} },
    ["trading-economics.get_ratings_country"] = { method = "GET", url = "https://api.tradingeconomics.com/ratings/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_ratings_historical_all_date"] = { method = "GET", url = "https://api.tradingeconomics.com/ratings/historical/all/{date}", path = {"date"}, query = {"f"} },
    ["trading-economics.get_ratings_historical_country"] = { method = "GET", url = "https://api.tradingeconomics.com/ratings/historical/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_ratings_historical_country_d1_d2"] = { method = "GET", url = "https://api.tradingeconomics.com/ratings/historical/{country}/{d1}/{d2}", path = {"country", "d1", "d2"}, query = {"f"} },
    ["trading-economics.get_search_categories"] = { method = "GET", url = "https://api.tradingeconomics.com/search/categories", query = {"f"} },
    ["trading-economics.get_search_term"] = { method = "GET", url = "https://api.tradingeconomics.com/search/{term}", path = {"term"}, query = {"category", "f"} },
    ["trading-economics.get_sectors"] = { method = "GET", url = "https://api.tradingeconomics.com/sectors", query = {"f"} },
    ["trading-economics.get_splits"] = { method = "GET", url = "https://api.tradingeconomics.com/splits", query = {"d1", "d2", "f"} },
    ["trading-economics.get_splits_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/splits/country/{country}", path = {"country"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_splits_ticker_ticker"] = { method = "GET", url = "https://api.tradingeconomics.com/splits/ticker/{ticker}", path = {"ticker"}, query = {"d1", "d2", "f"} },
    ["trading-economics.get_updates"] = { method = "GET", url = "https://api.tradingeconomics.com/updates", query = {"f"} },
    ["trading-economics.get_updates_country_country"] = { method = "GET", url = "https://api.tradingeconomics.com/updates/country/{country}", path = {"country"}, query = {"f"} },
    ["trading-economics.get_updates_country_country_date"] = { method = "GET", url = "https://api.tradingeconomics.com/updates/country/{country}/{date}", path = {"country", "date"}, query = {"f"} },
    ["trading-economics.get_updates_date"] = { method = "GET", url = "https://api.tradingeconomics.com/updates/{date}", path = {"date"}, query = {"time", "f"} },
    ["trading-economics.get_worldbank_categories"] = { method = "GET", url = "https://api.tradingeconomics.com/worldbank/categories", query = {"f"} },
    ["trading-economics.get_worldbank_category_category_page"] = { method = "GET", url = "https://api.tradingeconomics.com/worldbank/category/{category}/{page}", path = {"category", "page"}, query = {"f"} },
    ["trading-economics.get_worldbank_country_country_page"] = { method = "GET", url = "https://api.tradingeconomics.com/worldbank/country/{country}/{page}", path = {"country", "page"}, query = {"f"} },
    ["trading-economics.get_worldbank_historical"] = { method = "GET", url = "https://api.tradingeconomics.com/worldbank/historical", query = {"s", "f"} },
    ["trading-economics.get_worldbank_indicator"] = { method = "GET", url = "https://api.tradingeconomics.com/worldbank/indicator", query = {"s", "url", "f"} },
  },
}
