-- Razorpay — every call this API accepts, as data.
--
-- GENERATED from https://razorpay.com/openapi.json
-- Published on the vendor's own documentation site (https://razorpay.com).
-- 136 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "razorpay",
  name = "Razorpay",
  base = "https://api.razorpay.com",
  docs = "https://nango.dev/docs/integrations/all/razorpay",
  auth = {
    kind = "basic",
    header = "authorization",
    format = "Bearer {token}",
    env = nil,
    user_env = "RAZORPAY_USER",
    pass_env = "RAZORPAY_PASS",
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["razorpay.accept_dispute"] = { method = "POST", url = "https://api.razorpay.com/v1/disputes/{id}/accept", path = {"id"} },
    ["razorpay.activate_deactivate_fund_account"] = { method = "PATCH", url = "https://api.razorpay.com/v1/fund_accounts/{fund_account_id}", path = {"fund_account_id"}, body = {"active"} },
    ["razorpay.add_allowed_payer"] = { method = "POST", url = "https://api.razorpay.com/v1/virtual_accounts/{va_id}/allowed_payers", path = {"va_id"}, body = {"type", "bank_account", "vpa"} },
    ["razorpay.add_vpa_receiver"] = { method = "POST", url = "https://api.razorpay.com/v1/virtual_accounts/{id}/receivers", path = {"id"}, body = {"types"} },
    ["razorpay.approve_payout"] = { method = "POST", url = "https://api.razorpay.com/v1/payouts/{payout_id}/approve", path = {"payout_id"}, body = {"remarks"} },
    ["razorpay.cancel_invoice"] = { method = "POST", url = "https://api.razorpay.com/v1/invoices/{id}/cancel", path = {"id"} },
    ["razorpay.cancel_payment_link"] = { method = "POST", url = "https://api.razorpay.com/v1/payment_links/{id}/cancel", path = {"id"} },
    ["razorpay.cancel_payout"] = { method = "POST", url = "https://api.razorpay.com/v1/payouts/{payout_id}/cancel", path = {"payout_id"} },
    ["razorpay.cancel_payout_link"] = { method = "POST", url = "https://api.razorpay.com/v1/payout-links/{payout_link_id}/cancel", path = {"payout_link_id"} },
    ["razorpay.cancel_subscription"] = { method = "POST", url = "https://api.razorpay.com/v1/subscriptions/{id}/cancel", path = {"id"}, body = {"cancel_at_cycle_end"} },
    ["razorpay.cancel_subscription_scheduled_changes"] = { method = "POST", url = "https://api.razorpay.com/v1/subscriptions/{id}/cancel_scheduled_changes", path = {"id"} },
    ["razorpay.capture_payment"] = { method = "POST", url = "https://api.razorpay.com/v1/payments/{id}/capture", path = {"id"}, body = {"amount", "currency"} },
    ["razorpay.close_qr_code"] = { method = "POST", url = "https://api.razorpay.com/v1/payments/qr_codes/{id}/close", path = {"id"} },
    ["razorpay.close_virtual_account"] = { method = "POST", url = "https://api.razorpay.com/v1/virtual_accounts/{id}/close", path = {"id"}, body = {"status"} },
    ["razorpay.contest_dispute"] = { method = "PATCH", url = "https://api.razorpay.com/v1/disputes/{id}/contest", path = {"id"}, body = {"action", "amount", "summary", "shipping_proof", "billing_proof", "cancellation_proof", "customer_communication", "proof_of_service", "explanation_letter", "refund_confirmation", "access_activity_log", "refund_cancellation_policy", "term_and_conditions", "others"} },
    ["razorpay.create_bill"] = { method = "POST", url = "https://api.razorpay.com/v1/bills", body = {"business_type", "business_category", "customer", "receipt_timestamp", "receipt_number", "receipt_type", "receipt_delivery", "store_code", "order_number", "line_items", "receipt_summary", "taxes", "payments"} },
    ["razorpay.create_contact"] = { method = "POST", url = "https://api.razorpay.com/v1/contacts", body = {"name", "email", "contact", "type", "reference_id", "notes"} },
    ["razorpay.create_customer"] = { method = "POST", url = "https://api.razorpay.com/v1/customers", body = {"name", "contact", "email", "gstin", "notes"} },
    ["razorpay.create_direct_transfer"] = { method = "POST", url = "https://api.razorpay.com/v1/transfers", header = {"X-Transfer-Idempotency"}, body = {"account", "amount", "currency", "notes", "linked_account_notes", "on_hold", "on_hold_until"} },
    ["razorpay.create_fund_account"] = { method = "POST", url = "https://api.razorpay.com/v1/fund_accounts", body = {"contact_id", "account_type", "bank_account", "vpa", "card", "wallet"} },
    ["razorpay.create_instant_settlement"] = { method = "POST", url = "https://api.razorpay.com/v1/settlements/ondemand", body = {"amount", "settle_full_balance", "description", "notes"} },
    ["razorpay.create_invoice"] = { method = "POST", url = "https://api.razorpay.com/v1/invoices", body = {"type", "description", "customer_id", "customer", "line_items", "currency", "receipt", "comment", "terms", "partial_payment", "first_payment_min_amount", "expire_by", "notes"} },
    ["razorpay.create_item"] = { method = "POST", url = "https://api.razorpay.com/v1/items", body = {"name", "description", "amount", "currency"} },
    ["razorpay.create_linked_account"] = { method = "POST", url = "https://api.razorpay.com/v1/v2/accounts", body = {"email", "phone", "legal_business_name", "business_type", "type", "profile", "legal_info", "notes"} },
    ["razorpay.create_order"] = { method = "POST", url = "https://api.razorpay.com/v1/orders", body = {"amount", "currency", "receipt", "notes", "partial_payment"} },
    ["razorpay.create_partner_webhook"] = { method = "POST", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/webhooks", path = {"account_id"}, body = {"url", "alert_email", "active", "events"} },
    ["razorpay.create_payment_link"] = { method = "POST", url = "https://api.razorpay.com/v1/payment_links", body = {"amount", "currency", "upi_link", "accept_partial", "first_min_partial_amount", "expire_by", "reference_id", "description", "customer", "notify", "reminder_enable", "callback_url", "callback_method", "notes", "options"} },
    ["razorpay.create_payout"] = { method = "POST", url = "https://api.razorpay.com/v1/payouts", header = {"X-Payout-Idempotency"}, body = {"account_number", "fund_account_id", "fund_account", "amount", "currency", "mode", "purpose", "narration", "reference_id", "notes", "queue_if_low_balance"} },
    ["razorpay.create_payout_link"] = { method = "POST", url = "https://api.razorpay.com/v1/payout-links", body = {"contact_id", "amount", "currency", "purpose", "description", "receipt", "send_sms", "send_email", "notes", "expire_by"} },
    ["razorpay.create_plan"] = { method = "POST", url = "https://api.razorpay.com/v1/plans", body = {"period", "interval", "item", "notes"} },
    ["razorpay.create_qr_code"] = { method = "POST", url = "https://api.razorpay.com/v1/payments/qr_codes", body = {"type", "name", "usage", "fixed_amount", "payment_amount", "description", "customer_id", "close_by", "notes"} },
    ["razorpay.create_refund"] = { method = "POST", url = "https://api.razorpay.com/v1/payments/{id}/refund", path = {"id"}, body = {"amount", "speed", "notes", "receipt"} },
    ["razorpay.create_stakeholder"] = { method = "POST", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/stakeholders", path = {"account_id"}, body = {"name", "email", "percentage_ownership", "relationship", "phone", "addresses", "kyc", "notes"} },
    ["razorpay.create_subscription"] = { method = "POST", url = "https://api.razorpay.com/v1/subscriptions", body = {"plan_id", "total_count", "quantity", "customer_notify", "start_at", "expire_by", "addons", "offer_id", "notify_info", "notes"} },
    ["razorpay.create_transfers_from_payment"] = { method = "POST", url = "https://api.razorpay.com/v1/payments/{id}/transfers", path = {"id"}, body = {"transfers"} },
    ["razorpay.create_virtual_account"] = { method = "POST", url = "https://api.razorpay.com/v1/virtual_accounts", body = {"receivers", "description", "amount", "customer_id", "close_by", "notes"} },
    ["razorpay.delete_allowed_payer"] = { method = "DELETE", url = "https://api.razorpay.com/v1/virtual_accounts/{va_id}/allowed_payers/{id}", path = {"va_id", "id"} },
    ["razorpay.delete_bill"] = { method = "DELETE", url = "https://api.razorpay.com/v1/bills/{bill_id}", path = {"bill_id"} },
    ["razorpay.delete_invoice"] = { method = "DELETE", url = "https://api.razorpay.com/v1/invoices/{id}", path = {"id"} },
    ["razorpay.delete_item"] = { method = "DELETE", url = "https://api.razorpay.com/v1/items/{id}", path = {"id"} },
    ["razorpay.delete_partner_account"] = { method = "DELETE", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}", path = {"account_id"} },
    ["razorpay.delete_partner_webhook"] = { method = "DELETE", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/webhooks/{webhook_id}", path = {"account_id", "webhook_id"} },
    ["razorpay.delete_subscription_offer"] = { method = "DELETE", url = "https://api.razorpay.com/v1/subscriptions/{sub_id}/{offer_id}", path = {"sub_id", "offer_id"} },
    ["razorpay.fetch_account_documents"] = { method = "GET", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/documents", path = {"account_id"} },
    ["razorpay.fetch_all_customers"] = { method = "GET", url = "https://api.razorpay.com/v1/customers", query = {"count", "skip"} },
    ["razorpay.fetch_all_disputes"] = { method = "GET", url = "https://api.razorpay.com/v1/disputes", query = {"count", "skip", "expand[]"} },
    ["razorpay.fetch_all_instant_settlements"] = { method = "GET", url = "https://api.razorpay.com/v1/settlements/ondemand", query = {"from", "to", "count", "skip", "expand[]"} },
    ["razorpay.fetch_all_orders"] = { method = "GET", url = "https://api.razorpay.com/v1/orders", query = {"from", "to", "count", "skip", "authorized", "receipt", "expand[]"} },
    ["razorpay.fetch_all_payment_links"] = { method = "GET", url = "https://api.razorpay.com/v1/payment_links", query = {"payment_id", "reference_id"} },
    ["razorpay.fetch_all_payments"] = { method = "GET", url = "https://api.razorpay.com/v1/payments", query = {"from", "to", "count", "skip"} },
    ["razorpay.fetch_all_qr_codes"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/qr_codes", query = {"from", "to", "count", "skip", "customer_id", "payment_id"} },
    ["razorpay.fetch_all_refunds"] = { method = "GET", url = "https://api.razorpay.com/v1/refunds", query = {"from", "to", "count", "skip"} },
    ["razorpay.fetch_all_settlements"] = { method = "GET", url = "https://api.razorpay.com/v1/settlements", query = {"from", "to", "count", "skip"} },
    ["razorpay.fetch_all_stakeholders"] = { method = "GET", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/stakeholders", path = {"account_id"} },
    ["razorpay.fetch_bank_transfer"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/{id}/bank_transfer", path = {"id"} },
    ["razorpay.fetch_banking_balances"] = { method = "GET", url = "https://api.razorpay.com/v1/banking_balances", query = {"account_type", "bank_code"} },
    ["razorpay.fetch_contact"] = { method = "GET", url = "https://api.razorpay.com/v1/contacts/{contact_id}", path = {"contact_id"} },
    ["razorpay.fetch_customer"] = { method = "GET", url = "https://api.razorpay.com/v1/customers/{id}", path = {"id"} },
    ["razorpay.fetch_dispute"] = { method = "GET", url = "https://api.razorpay.com/v1/disputes/{id}", path = {"id"} },
    ["razorpay.fetch_document"] = { method = "GET", url = "https://api.razorpay.com/v1/documents/{id}", path = {"id"} },
    ["razorpay.fetch_document_content"] = { method = "POST", url = "https://api.razorpay.com/v1/documents/{id}/content", path = {"id"} },
    ["razorpay.fetch_fund_account"] = { method = "GET", url = "https://api.razorpay.com/v1/fund_accounts/{fund_account_id}", path = {"fund_account_id"} },
    ["razorpay.fetch_fund_account_validation"] = { method = "GET", url = "https://api.razorpay.com/v1/fund_accounts/validations/{validation_id}", path = {"validation_id"} },
    ["razorpay.fetch_instant_settlement"] = { method = "GET", url = "https://api.razorpay.com/v1/settlements/ondemand/{id}", path = {"id"}, query = {"expand[]"} },
    ["razorpay.fetch_invoice"] = { method = "GET", url = "https://api.razorpay.com/v1/invoices/{id}", path = {"id"} },
    ["razorpay.fetch_item"] = { method = "GET", url = "https://api.razorpay.com/v1/items/{id}", path = {"id"} },
    ["razorpay.fetch_linked_account"] = { method = "GET", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}", path = {"account_id"} },
    ["razorpay.fetch_order"] = { method = "GET", url = "https://api.razorpay.com/v1/orders/{id}", path = {"id"} },
    ["razorpay.fetch_order_payments"] = { method = "GET", url = "https://api.razorpay.com/v1/orders/{id}/payments", path = {"id"} },
    ["razorpay.fetch_partner_webhook"] = { method = "GET", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/webhooks/{webhook_id}", path = {"account_id", "webhook_id"} },
    ["razorpay.fetch_payment"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/{id}", path = {"id"} },
    ["razorpay.fetch_payment_downtime"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/downtimes/{id}", path = {"id"} },
    ["razorpay.fetch_payment_downtimes"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/downtimes" },
    ["razorpay.fetch_payment_link"] = { method = "GET", url = "https://api.razorpay.com/v1/payment_links/{id}", path = {"id"} },
    ["razorpay.fetch_payment_refund"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/{payment_id}/refunds/{refund_id}", path = {"payment_id", "refund_id"} },
    ["razorpay.fetch_payment_refunds"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/{payment_id}/refunds", path = {"payment_id"}, query = {"from", "to", "count", "skip"} },
    ["razorpay.fetch_payout"] = { method = "GET", url = "https://api.razorpay.com/v1/payouts/{payout_id}", path = {"payout_id"} },
    ["razorpay.fetch_payout_link"] = { method = "GET", url = "https://api.razorpay.com/v1/payout-links/{payout_link_id}", path = {"payout_link_id"} },
    ["razorpay.fetch_plan"] = { method = "GET", url = "https://api.razorpay.com/v1/plans/{id}", path = {"id"} },
    ["razorpay.fetch_product_config"] = { method = "GET", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/products/{product_id}", path = {"account_id", "product_id"} },
    ["razorpay.fetch_qr_code"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/qr_codes/{id}", path = {"id"} },
    ["razorpay.fetch_qr_code_payments"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/qr_codes/{id}/payments", path = {"id"}, query = {"from", "to", "count", "skip"} },
    ["razorpay.fetch_refund"] = { method = "GET", url = "https://api.razorpay.com/v1/refunds/{id}", path = {"id"} },
    ["razorpay.fetch_settlement"] = { method = "GET", url = "https://api.razorpay.com/v1/settlements/{id}", path = {"id"} },
    ["razorpay.fetch_settlement_recon"] = { method = "GET", url = "https://api.razorpay.com/v1/settlements/recon/combined", query = {"year", "month", "day", "count", "skip"} },
    ["razorpay.fetch_stakeholder_documents"] = { method = "GET", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/stakeholders/{stakeholder_id}/documents", path = {"account_id", "stakeholder_id"} },
    ["razorpay.fetch_subscription"] = { method = "GET", url = "https://api.razorpay.com/v1/subscriptions/{id}", path = {"id"} },
    ["razorpay.fetch_subscription_scheduled_changes"] = { method = "GET", url = "https://api.razorpay.com/v1/subscriptions/{id}/retrieve_scheduled_changes", path = {"id"} },
    ["razorpay.fetch_transaction"] = { method = "GET", url = "https://api.razorpay.com/v1/transactions/{transaction_id}", path = {"transaction_id"} },
    ["razorpay.fetch_transfer"] = { method = "GET", url = "https://api.razorpay.com/v1/transfers/{id}", path = {"id"} },
    ["razorpay.fetch_transfers_for_payment"] = { method = "GET", url = "https://api.razorpay.com/v1/payments/{id}/transfers", path = {"id"} },
    ["razorpay.fetch_virtual_account"] = { method = "GET", url = "https://api.razorpay.com/v1/virtual_accounts/{id}", path = {"id"} },
    ["razorpay.fetch_virtual_account_payments"] = { method = "GET", url = "https://api.razorpay.com/v1/virtual_accounts/{id}/payments", path = {"id"} },
    ["razorpay.issue_invoice"] = { method = "POST", url = "https://api.razorpay.com/v1/invoices/{id}/issue", path = {"id"} },
    ["razorpay.list_contacts"] = { method = "GET", url = "https://api.razorpay.com/v1/contacts", query = {"name", "email", "contact", "reference_id", "from", "to", "count", "skip"} },
    ["razorpay.list_fund_account_validations"] = { method = "GET", url = "https://api.razorpay.com/v1/fund_accounts/validations", query = {"from", "to", "count", "skip"} },
    ["razorpay.list_fund_accounts"] = { method = "GET", url = "https://api.razorpay.com/v1/fund_accounts", query = {"contact_id", "account_type", "count", "skip"} },
    ["razorpay.list_invoices"] = { method = "GET", url = "https://api.razorpay.com/v1/invoices", query = {"type", "payment_id", "customer_id", "subscription_id", "from", "to", "count", "skip"} },
    ["razorpay.list_items"] = { method = "GET", url = "https://api.razorpay.com/v1/items", query = {"count", "skip"} },
    ["razorpay.list_partner_webhooks"] = { method = "GET", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/webhooks", path = {"account_id"} },
    ["razorpay.list_payout_links"] = { method = "GET", url = "https://api.razorpay.com/v1/payout-links", query = {"contact_id", "from", "to", "count", "skip"} },
    ["razorpay.list_payouts"] = { method = "GET", url = "https://api.razorpay.com/v1/payouts", query = {"account_number", "contact_id", "fund_account_id", "from", "to", "count", "skip"} },
    ["razorpay.list_plans"] = { method = "GET", url = "https://api.razorpay.com/v1/plans", query = {"count", "skip"} },
    ["razorpay.list_reversals"] = { method = "GET", url = "https://api.razorpay.com/v1/transfers/{id}/reversals", path = {"id"} },
    ["razorpay.list_subscriptions"] = { method = "GET", url = "https://api.razorpay.com/v1/subscriptions", query = {"plan_id", "from", "to", "count", "skip"} },
    ["razorpay.list_transactions"] = { method = "GET", url = "https://api.razorpay.com/v1/transactions", query = {"account_number", "from", "to", "count", "skip"} },
    ["razorpay.list_transfers"] = { method = "GET", url = "https://api.razorpay.com/v1/transfers", query = {"from", "to", "count", "skip", "recipient_settlement_id", "expand[]"} },
    ["razorpay.list_virtual_accounts"] = { method = "GET", url = "https://api.razorpay.com/v1/virtual_accounts", query = {"from", "to", "count", "skip"} },
    ["razorpay.modify_transfer_settlement_hold"] = { method = "PATCH", url = "https://api.razorpay.com/v1/transfers/{id}", path = {"id"}, body = {"on_hold", "on_hold_until"} },
    ["razorpay.pause_subscription"] = { method = "POST", url = "https://api.razorpay.com/v1/subscriptions/{id}/pause", path = {"id"}, body = {"pause_at"} },
    ["razorpay.reject_payout"] = { method = "POST", url = "https://api.razorpay.com/v1/payouts/{payout_id}/reject", path = {"payout_id"}, body = {"remarks"} },
    ["razorpay.request_product_config"] = { method = "POST", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/products", path = {"account_id"}, body = {"product_name", "tnc_accepted", "applicable_identified"} },
    ["razorpay.resend_payment_link_notification"] = { method = "POST", url = "https://api.razorpay.com/v1/payment_links/{id}/notify_by/{medium}", path = {"id", "medium"} },
    ["razorpay.resume_subscription"] = { method = "POST", url = "https://api.razorpay.com/v1/subscriptions/{id}/resume", path = {"id"}, body = {"resume_at"} },
    ["razorpay.reverse_transfer"] = { method = "POST", url = "https://api.razorpay.com/v1/transfers/{id}/reversals", path = {"id"}, body = {"amount", "notes"} },
    ["razorpay.send_invoice_notification"] = { method = "POST", url = "https://api.razorpay.com/v1/invoices/{id}/notify_by/{medium}", path = {"id", "medium"} },
    ["razorpay.update_bill"] = { method = "PATCH", url = "https://api.razorpay.com/v1/bills/{bill_id}", path = {"bill_id"}, body = {"id", "business_type", "business_category", "customer", "employee", "loyalty", "store_code", "receipt_timestamp", "receipt_number", "receipt_type", "receipt_delivery", "tags", "bar_code_number", "qr_code_number", "billing_pos_number", "pos_category", "order_number", "order_service_type", "delivery_status_url", "line_items", "receipt_summary", "taxes", "payments", "event", "irn", "receipt_url", "created_at"} },
    ["razorpay.update_contact"] = { method = "PATCH", url = "https://api.razorpay.com/v1/contacts/{contact_id}", path = {"contact_id"}, body = {"name", "email", "contact", "type", "reference_id", "notes", "active"} },
    ["razorpay.update_customer"] = { method = "PUT", url = "https://api.razorpay.com/v1/customers/{id}", path = {"id"}, body = {"name", "contact", "email"} },
    ["razorpay.update_invoice"] = { method = "PATCH", url = "https://api.razorpay.com/v1/invoices/{id}", path = {"id"}, body = {"description", "receipt", "comment", "terms", "partial_payment", "expire_by", "notes", "line_items"} },
    ["razorpay.update_item"] = { method = "PATCH", url = "https://api.razorpay.com/v1/items/{id}", path = {"id"}, body = {"name", "description", "amount", "currency", "active"} },
    ["razorpay.update_linked_account"] = { method = "PATCH", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}", path = {"account_id"}, body = {"phone", "legal_business_name", "profile", "legal_info", "contact_name", "contact_info", "apps", "notes"} },
    ["razorpay.update_order"] = { method = "PATCH", url = "https://api.razorpay.com/v1/orders/{id}", path = {"id"}, body = {"notes"} },
    ["razorpay.update_partner_webhook"] = { method = "PATCH", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/webhooks/{webhook_id}", path = {"account_id", "webhook_id"}, body = {"id", "entity", "owner_id", "owner_type", "url", "alert_email", "secret_exists", "active", "events", "service", "context", "disabled_at", "created_at", "updated_at"} },
    ["razorpay.update_payment"] = { method = "PATCH", url = "https://api.razorpay.com/v1/payments/{id}", path = {"id"}, body = {"notes"} },
    ["razorpay.update_payment_link"] = { method = "PATCH", url = "https://api.razorpay.com/v1/payment_links/{id}", path = {"id"}, body = {"reference_id", "expire_by", "reminder_enable", "accept_partial", "notes"} },
    ["razorpay.update_product_config"] = { method = "PATCH", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/products/{product_id}", path = {"account_id", "product_id"}, body = {"settlements", "tnc_accepted"} },
    ["razorpay.update_qr_code"] = { method = "PATCH", url = "https://api.razorpay.com/v1/payments/qr_codes/{id}", path = {"id"}, body = {"notes"} },
    ["razorpay.update_refund"] = { method = "PATCH", url = "https://api.razorpay.com/v1/refunds/{id}", path = {"id"}, body = {"notes"} },
    ["razorpay.update_stakeholder"] = { method = "PATCH", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/stakeholders/{stakeholder_id}", path = {"account_id", "stakeholder_id"}, body = {"name", "percentage_ownership", "relationship", "phone", "addresses", "kyc", "notes"} },
    ["razorpay.update_subscription"] = { method = "PATCH", url = "https://api.razorpay.com/v1/subscriptions/{id}", path = {"id"}, body = {"plan_id", "quantity", "remaining_count", "schedule_change_at", "customer_notify", "notes"} },
    ["razorpay.update_virtual_account"] = { method = "PATCH", url = "https://api.razorpay.com/v1/virtual_accounts/{id}", path = {"id"}, body = {"amount", "close_by", "description"} },
    ["razorpay.upload_account_documents"] = { method = "POST", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/documents", path = {"account_id"}, body = {"document_type", "file"} },
    ["razorpay.upload_document"] = { method = "POST", url = "https://api.razorpay.com/v1/documents", body = {"file", "purpose"} },
    ["razorpay.upload_stakeholder_documents"] = { method = "POST", url = "https://api.razorpay.com/v1/v2/accounts/{account_id}/stakeholders/{stakeholder_id}/documents", path = {"account_id", "stakeholder_id"}, body = {"document_type", "file"} },
    ["razorpay.validate_fund_account"] = { method = "POST", url = "https://api.razorpay.com/v1/fund_accounts/validations", body = {"account_type", "fund_account", "amount", "currency", "notes", "receipt", "validation_type"} },
  },
}
