-- ClickSend — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/clicksend.com/1.0.0/openapi.json
-- APIs.guru's mirror of clicksend.com, matched on clicksend.com. A mirror lags the vendor.
-- 205 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "clicksend",
  name = "ClickSend",
  base = "https://rest.clicksend.com",
  docs = "https://nango.dev/docs/integrations/all/clicksend",
  auth = {
    kind = "basic",
    header = "authorization",
    format = "Bearer {token}",
    env = nil,
    user_env = "CLICKSEND_USER",
    pass_env = "CLICKSEND_PASS",
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["clicksend.account_usage"] = { method = "GET", url = "https://rest.clicksend.com/v3/account/usage/{year}/{month}/{type}", path = {"year", "month", "type"} },
    ["clicksend.add_a_test_delivery_receipt"] = { method = "POST", url = "https://rest.clicksend.com/v3/fax/receipts" },
    ["clicksend.add_a_test_inbound_sms"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms/inbound" },
    ["clicksend.buy_dedicated_number"] = { method = "POST", url = "https://rest.clicksend.com/v3/numbers/buy/{dedicated_number}", path = {"dedicated_number"} },
    ["clicksend.calculate_direct_mail_campaign_price"] = { method = "POST", url = "https://rest.clicksend.com/v3/post/direct-mail/campaigns/price", body = {"areas", "file_urls", "name", "schedule", "size", "source"} },
    ["clicksend.calculate_price"] = { method = "POST", url = "https://rest.clicksend.com/v3/email-campaigns/price" },
    ["clicksend.calculate_price_for_sms_campaign"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms-campaigns/price", body = {"body", "from", "list_id", "name"} },
    ["clicksend.calculate_pricing"] = { method = "POST", url = "https://rest.clicksend.com/v3/post/postcards/price", body = {"file_urls", "recipients"} },
    ["clicksend.cancel_a_scheduled_message"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms/{message_id}/cancel", path = {"message_id"} },
    ["clicksend.cancel_a_specific_voice_call"] = { method = "PUT", url = "https://rest.clicksend.com/v3/voice/{message_id}/cancel", path = {"message_id"} },
    ["clicksend.cancel_all_mms"] = { method = "PUT", url = "https://rest.clicksend.com/v3/mms/cancel-all" },
    ["clicksend.cancel_all_scheduled_messages"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms/cancel-all" },
    ["clicksend.cancel_all_voice_calls"] = { method = "PUT", url = "https://rest.clicksend.com/v3/voice/cancel-all" },
    ["clicksend.cancel_an_sms_campaign"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms-campaigns/{sms_campaign_id}/cancel", path = {"sms_campaign_id"} },
    ["clicksend.cancel_email_campaign"] = { method = "PUT", url = "https://rest.clicksend.com/v3/email-campaigns/{email_campaign_id}/cancel", path = {"email_campaign_id"} },
    ["clicksend.cancel_mms"] = { method = "PUT", url = "https://rest.clicksend.com/v3/mms/{message_id}/cancel", path = {"message_id"} },
    ["clicksend.create_a_new_account"] = { method = "POST", url = "https://rest.clicksend.com/v3/account", body = {"account_name", "country", "password", "user_email", "user_first_name", "user_last_name", "user_phone", "username"} },
    ["clicksend.create_a_new_contact"] = { method = "POST", url = "https://rest.clicksend.com/v3/lists/{list_id}/contacts", path = {"list_id"}, body = {"address_city", "address_country", "address_line_1", "address_line_2", "address_postal_code", "address_state", "custom_1", "custom_2", "custom_3", "custom_4", "email", "fax_number", "first_name", "last_name", "organization_name", "phone_number"} },
    ["clicksend.create_a_new_contact_list"] = { method = "POST", url = "https://rest.clicksend.com/v3/lists", body = {"list_name"} },
    ["clicksend.create_a_new_rule"] = { method = "POST", url = "https://rest.clicksend.com/v3/automations/fax/receipts", body = {"action", "action_address", "enabled", "match_type", "rule_name"} },
    ["clicksend.create_a_new_rule"] = { method = "POST", url = "https://rest.clicksend.com/v3/automations/sms/inbound/", body = {"action", "action_address", "dedicated_number", "enabled", "message_search_term", "message_search_type", "rule_name"} },
    ["clicksend.create_a_new_subaccount"] = { method = "POST", url = "https://rest.clicksend.com/v3/subaccounts", body = {"access_billing", "access_contacts", "access_reporting", "access_settings", "access_users", "api_username", "email", "first_name", "last_name", "password", "phone_number", "share_campaigns"} },
    ["clicksend.create_a_post_return_address"] = { method = "POST", url = "https://rest.clicksend.com/v3/post/return-addresses" },
    ["clicksend.create_a_template"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms/templates", body = {"body", "template_name"} },
    ["clicksend.create_allowed_email_address"] = { method = "POST", url = "https://rest.clicksend.com/v3/email/addresses", body = {"Body", "email_address"} },
    ["clicksend.create_delivery_issue"] = { method = "POST", url = "https://rest.clicksend.com/v3/delivery-issues", body = {"client_comments", "description", "email_address", "message_id", "type"} },
    ["clicksend.create_email_campaign"] = { method = "POST", url = "https://rest.clicksend.com/v3/email-campaigns/send" },
    ["clicksend.create_email_to_sms_allowed_address"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms/email-sms", body = {"email_address", "from"} },
    ["clicksend.create_new_campaign"] = { method = "POST", url = "https://rest.clicksend.com/v3/post/direct-mail/campaigns/send", body = {"areas", "file_urls", "name", "schedule", "size", "source"} },
    ["clicksend.create_new_email_template_from_master_template"] = { method = "POST", url = "https://rest.clicksend.com/v3/email/templates", body = {"template_id_master", "template_name"} },
    ["clicksend.create_reseller_account"] = { method = "POST", url = "https://rest.clicksend.com/v3/reseller/accounts" },
    ["clicksend.create_reseller_account_public"] = { method = "POST", url = "https://rest.clicksend.com/v3/reseller/accounts-public", body = {"account_name", "country", "password", "reseller_user_id", "user_email", "user_first_name", "user_last_name", "user_phone", "username"} },
    ["clicksend.create_stripped_string"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms/email-sms-stripped-strings", body = {"strip_string"} },
    ["clicksend.delete_a_rule"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/automations/fax/receipts/{rule_id}", path = {"rule_id"} },
    ["clicksend.delete_a_rule"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/automations/sms/inbound/{inbound_rule_id}", path = {"inbound_rule_id"} },
    ["clicksend.delete_a_specific_contact"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/lists/{list_id}/contacts/{contact_id}", path = {"list_id", "contact_id"} },
    ["clicksend.delete_a_specific_contact_list"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/lists/{list_id}", path = {"list_id"} },
    ["clicksend.delete_a_specific_subaccount"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/subaccounts/{subaccount_id}", path = {"subaccount_id"} },
    ["clicksend.delete_a_template"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/sms/templates/{template_id}", path = {"template_id"} },
    ["clicksend.delete_allowed_email_address"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/email/addresses/{email_address_id}", path = {"email_address_id"} },
    ["clicksend.delete_automations_email_receipt_rule_id"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/automations/email/receipt/{rule_id}", path = {"rule_id"} },
    ["clicksend.delete_automations_fax_inbound_inbound_rule_id"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/automations/fax/inbound/{inbound_rule_id}", path = {"inbound_rule_id"} },
    ["clicksend.delete_automations_sms_receipts_receipt_rule_id"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/automations/sms/receipts/{receipt_rule_id}", path = {"receipt_rule_id"} },
    ["clicksend.delete_automations_voice_receipts_receipt_rule_id"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/automations/voice/receipts/{receipt_rule_id}", path = {"receipt_rule_id"} },
    ["clicksend.delete_email_template"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/email/templates/{template_id}", path = {"template_id"} },
    ["clicksend.delete_email_to_sms_allowed_address"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/sms/email-sms/{email_address_id}", path = {"email_address_id"} },
    ["clicksend.delete_post_return_address"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/post/return-addresses/{return_address_id}", path = {"return_address_id"} },
    ["clicksend.delete_stripped_string"] = { method = "DELETE", url = "https://rest.clicksend.com/v3/sms/email-sms-stripped-strings/{rule_id}", path = {"rule_id"} },
    ["clicksend.detect_address"] = { method = "POST", url = "https://rest.clicksend.com/v3/post/letters/detect-address" },
    ["clicksend.email_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/history" },
    ["clicksend.email_price"] = { method = "POST", url = "https://rest.clicksend.com/v3/email/price", body = {"attachments", "bcc", "body", "cc", "from.email_address_id", "from.name", "subject", "to"} },
    ["clicksend.email_send"] = { method = "POST", url = "https://rest.clicksend.com/v3/email/send", body = {"attachments", "bcc", "body", "cc", "from.email_address_id", "from.name", "schedule", "to"} },
    ["clicksend.export_contacts_list"] = { method = "GET", url = "https://rest.clicksend.com/v3/lists/{list_id}/export?filename={filename}", path = {"filename", "list_id"} },
    ["clicksend.export_fax_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/fax/history/export?filename={filename}", path = {"filename"} },
    ["clicksend.export_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/history/export?filename={filename}", path = {"filename"} },
    ["clicksend.export_mms_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/mms/history/export?filename={filename}", path = {"filename"} },
    ["clicksend.export_post_letter_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/post/letters/history/export?filename={filename}", path = {"filename"} },
    ["clicksend.export_postcard_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/post/postcards/export?filename={filename}", path = {"filename"} },
    ["clicksend.export_sms_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/history/export?filename={filename}", path = {"filename"} },
    ["clicksend.export_voice_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/voice/history/export?filename={filename}", path = {"filename"} },
    ["clicksend.find_specific_stripped_string"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/email-sms-stripped-strings/{rule_id}", path = {"rule_id"} },
    ["clicksend.forgot_password"] = { method = "PUT", url = "https://rest.clicksend.com/v3/forgot-password", body = {"username"} },
    ["clicksend.forgot_username"] = { method = "PUT", url = "https://rest.clicksend.com/v3/forgot-username", body = {"country", "email", "phone_number"} },
    ["clicksend.get_a_specific_contact"] = { method = "GET", url = "https://rest.clicksend.com/v3/lists/{list_id}/contacts/{contact_id}", path = {"list_id", "contact_id"} },
    ["clicksend.get_a_specific_contact_list"] = { method = "GET", url = "https://rest.clicksend.com/v3/lists/{list_id}", path = {"list_id"} },
    ["clicksend.get_a_specific_delivery_receipt"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/receipts/{message_id}", path = {"message_id"} },
    ["clicksend.get_a_specific_fax_delivery_receipt"] = { method = "GET", url = "https://rest.clicksend.com/v3/fax/receipts/{message_id}", path = {"message_id"} },
    ["clicksend.get_a_specific_rule"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/fax/receipts/{rule_id}", path = {"rule_id"} },
    ["clicksend.get_a_specific_rule"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/sms/inbound/{inbound_rule_id}", path = {"inbound_rule_id"} },
    ["clicksend.get_a_specific_subaccount"] = { method = "GET", url = "https://rest.clicksend.com/v3/subaccounts/{subaccount_id}", path = {"subaccount_id"} },
    ["clicksend.get_a_specific_transaction"] = { method = "GET", url = "https://rest.clicksend.com/v3/recharge/transactions/{transaction_id}", path = {"transaction_id"} },
    ["clicksend.get_account"] = { method = "GET", url = "https://rest.clicksend.com/v3/account" },
    ["clicksend.get_all_allowed_email_addresses"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/addresses" },
    ["clicksend.get_all_contact_lists"] = { method = "GET", url = "https://rest.clicksend.com/v3/lists" },
    ["clicksend.get_all_contacts_in_a_list"] = { method = "GET", url = "https://rest.clicksend.com/v3/lists/{list_id}/contacts", path = {"list_id"} },
    ["clicksend.get_all_countries"] = { method = "GET", url = "https://rest.clicksend.com/v3/countries" },
    ["clicksend.get_all_dedicated_numbers"] = { method = "GET", url = "https://rest.clicksend.com/v3/numbers" },
    ["clicksend.get_all_delivery_receipts"] = { method = "GET", url = "https://rest.clicksend.com/v3/mms/receipts" },
    ["clicksend.get_all_email_campaigns"] = { method = "GET", url = "https://rest.clicksend.com/v3/email-campaigns" },
    ["clicksend.get_all_email_templates"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/templates" },
    ["clicksend.get_all_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/history?date_from={date_from}&date_to={date_to}", path = {"date_from", "date_to"} },
    ["clicksend.get_all_inbound_sms_pull"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/inbound" },
    ["clicksend.get_all_master_email_templates"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/master-templates" },
    ["clicksend.get_all_master_template_categories"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/master-templates-categories" },
    ["clicksend.get_all_subaccounts"] = { method = "GET", url = "https://rest.clicksend.com/v3/subaccounts" },
    ["clicksend.get_all_templates_for_category"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/master-templates-categories/{category_id}/master-templates", path = {"category_id"} },
    ["clicksend.get_automations_email_receipt"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/email/receipt" },
    ["clicksend.get_automations_email_receipt_rule_id"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/email/receipt/{rule_id}", path = {"rule_id"} },
    ["clicksend.get_automations_fax_inbound"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/fax/inbound" },
    ["clicksend.get_automations_fax_inbound_inbound_rule_id"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/fax/inbound/{inbound_rule_id}", path = {"inbound_rule_id"} },
    ["clicksend.get_automations_sms_receipts"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/sms/receipts" },
    ["clicksend.get_automations_sms_receipts_receipt_rule_id"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/sms/receipts/{receipt_rule_id}", path = {"receipt_rule_id"} },
    ["clicksend.get_automations_voice_receipts"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/voice/receipts" },
    ["clicksend.get_automations_voice_receipts_receipt_rule_id"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/voice/receipts/{receipt_rule_id}", path = {"receipt_rule_id"} },
    ["clicksend.get_country_pricing"] = { method = "GET", url = "https://rest.clicksend.com/v3/pricing/{country}?currency={currency}", path = {"country", "currency"} },
    ["clicksend.get_credit_card_info"] = { method = "GET", url = "https://rest.clicksend.com/v3/recharge/credit-card" },
    ["clicksend.get_delivery_issues"] = { method = "GET", url = "https://rest.clicksend.com/v3/delivery-issues" },
    ["clicksend.get_delivery_receipt"] = { method = "GET", url = "https://rest.clicksend.com/v3/mms/receipts/{message_id}", path = {"message_id"} },
    ["clicksend.get_fax_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/fax/history?date_from={date_from}&date_to={date_to}&q={q}&order_by={order_by}", path = {"date_from", "date_to", "q", "order_by"} },
    ["clicksend.get_list_of_acceptable_import_fields"] = { method = "GET", url = "https://rest.clicksend.com/v3/lists/{list_id}/import-fields", path = {"list_id"} },
    ["clicksend.get_list_of_post_return_addresses"] = { method = "GET", url = "https://rest.clicksend.com/v3/post/return-addresses" },
    ["clicksend.get_list_of_referral_accounts"] = { method = "GET", url = "https://rest.clicksend.com/v3/referral/accounts" },
    ["clicksend.get_list_of_sms_campaigns"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms-campaigns" },
    ["clicksend.get_mms_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/mms/history?q={q}&order_by={order_by}&date_from={date_from}&date_to={date_to}", path = {"q", "order_by", "date_from", "date_to"} },
    ["clicksend.get_post_letter_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/post/letters/history" },
    ["clicksend.get_post_return_address"] = { method = "GET", url = "https://rest.clicksend.com/v3/post/return-addresses/{return_address_id}", path = {"return_address_id"} },
    ["clicksend.get_postcard_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/post/postcards/history" },
    ["clicksend.get_price"] = { method = "POST", url = "https://rest.clicksend.com/v3/mms/price", body = {"body", "country", "custom_string", "from", "from_email", "list_id", "media_file", "schedule", "source", "subject", "to"} },
    ["clicksend.get_reseller_account"] = { method = "GET", url = "https://rest.clicksend.com/v3/reseller/accounts/{client_user_id}", path = {"client_user_id"} },
    ["clicksend.get_reseller_setting"] = { method = "GET", url = "https://rest.clicksend.com/v3/reseller" },
    ["clicksend.get_sms_campaign"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms-campaigns/{sms_campaign_id}", path = {"sms_campaign_id"} },
    ["clicksend.get_sms_receipts"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/receipts" },
    ["clicksend.get_sms_statistics"] = { method = "GET", url = "https://rest.clicksend.com/v3/statistics/sms" },
    ["clicksend.get_specific_allowed_email_address"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/addresses/{email_address_id}", path = {"email_address_id"} },
    ["clicksend.get_specific_email_campaign"] = { method = "GET", url = "https://rest.clicksend.com/v3/email-campaigns/{email_campaign_id}", path = {"email_campaign_id"} },
    ["clicksend.get_specific_email_campaign_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/email-campaigns/{campaign_id}/history", path = {"campaign_id"} },
    ["clicksend.get_specific_email_template"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/templates/{template_id}", path = {"template_id"} },
    ["clicksend.get_specific_email_template_category"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/master-templates-categories/{category_id}", path = {"category_id"} },
    ["clicksend.get_specific_email_to_sms_allowed_address"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/email-sms/{email_address_id}", path = {"email_address_id"} },
    ["clicksend.get_specific_inbound_pull"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/inbound/{outbound_message_id}", path = {"outbound_message_id"} },
    ["clicksend.get_specific_master_template"] = { method = "GET", url = "https://rest.clicksend.com/v3/email/master-templates/{template_id}", path = {"template_id"} },
    ["clicksend.get_specific_voice_receipt"] = { method = "GET", url = "https://rest.clicksend.com/v3/voice/receipts/{message_id}", path = {"message_id"} },
    ["clicksend.get_timezones"] = { method = "GET", url = "https://rest.clicksend.com/v3/timezones" },
    ["clicksend.get_transactions"] = { method = "GET", url = "https://rest.clicksend.com/v3/recharge/transactions" },
    ["clicksend.get_voice_history"] = { method = "GET", url = "https://rest.clicksend.com/v3/voice/history?date_from={date_from}&date_to={date_to}", path = {"date_from", "date_to"} },
    ["clicksend.get_voice_receipts"] = { method = "GET", url = "https://rest.clicksend.com/v3/voice/receipts" },
    ["clicksend.get_voice_statistics"] = { method = "GET", url = "https://rest.clicksend.com/v3/statistics/voice" },
    ["clicksend.import_contacts_to_list"] = { method = "POST", url = "https://rest.clicksend.com/v3/lists/{list_id}/import", path = {"list_id"}, body = {"field_order", "file_url"} },
    ["clicksend.link_statistics"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms-campaigns/{campaign_id}/link-statistics", path = {"campaign_id"} },
    ["clicksend.link_tracking"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms-campaigns/{campaign_id}/link-tracking", path = {"campaign_id"} },
    ["clicksend.link_tracking_export"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms-campaigns/{campaign_id}/link-export?filename={filename}", path = {"campaign_id", "filename"} },
    ["clicksend.list_contact_suggestions"] = { method = "GET", url = "https://rest.clicksend.com/v3/contact-suggestions" },
    ["clicksend.list_direct_mail_campaigns"] = { method = "GET", url = "https://rest.clicksend.com/v3/post/direct-mail/campaigns" },
    ["clicksend.list_of_email_to_sms_allowed_address"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/email-sms" },
    ["clicksend.list_of_fax_delivery_receipts"] = { method = "GET", url = "https://rest.clicksend.com/v3/fax/receipts" },
    ["clicksend.list_of_packages"] = { method = "GET", url = "https://rest.clicksend.com/v3/recharge/packages?country={country}", path = {"country"} },
    ["clicksend.list_of_reseller_accounts"] = { method = "GET", url = "https://rest.clicksend.com/v3/reseller/accounts" },
    ["clicksend.list_of_templates"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/templates" },
    ["clicksend.list_rules"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/fax/receipts" },
    ["clicksend.list_rules"] = { method = "GET", url = "https://rest.clicksend.com/v3/automations/sms/inbound" },
    ["clicksend.list_stripped_strings"] = { method = "GET", url = "https://rest.clicksend.com/v3/sms/email-sms-stripped-strings" },
    ["clicksend.mark_a_specific_inbound_sms_as_read"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms/inbound-read/{message_id}", path = {"message_id"} },
    ["clicksend.mark_all_inbound_sms_as_read"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms/inbound-read", body = {"date_before"} },
    ["clicksend.mark_delivery_receipts_as_read"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms/receipts-read", body = {"date_before"} },
    ["clicksend.mark_fax_delivery_receipts_as_read"] = { method = "PUT", url = "https://rest.clicksend.com/v3/fax/receipts-read", body = {"date_before"} },
    ["clicksend.mark_receipts_as_read"] = { method = "PUT", url = "https://rest.clicksend.com/v3/mms/receipts-read" },
    ["clicksend.marked_voice_receipts_as_read"] = { method = "PUT", url = "https://rest.clicksend.com/v3/voice/receipts-read?date_before={date_before}", path = {"date_before"} },
    ["clicksend.post_automations_email_receipt"] = { method = "POST", url = "https://rest.clicksend.com/v3/automations/email/receipt", body = {"action", "action_address", "enabled", "match_type", "rule_name"} },
    ["clicksend.post_automations_fax_inbound"] = { method = "POST", url = "https://rest.clicksend.com/v3/automations/fax/inbound" },
    ["clicksend.post_automations_sms_receipts"] = { method = "POST", url = "https://rest.clicksend.com/v3/automations/sms/receipts" },
    ["clicksend.post_automations_voice_receipts"] = { method = "POST", url = "https://rest.clicksend.com/v3/automations/voice/receipts" },
    ["clicksend.post_email_receipts"] = { method = "POST", url = "https://rest.clicksend.com/v3/email/receipts" },
    ["clicksend.post_fax_price"] = { method = "POST", url = "https://rest.clicksend.com/v3/fax/price" },
    ["clicksend.post_post_letters_price"] = { method = "POST", url = "https://rest.clicksend.com/v3/post/letters/price", body = {"colour", "duplex", "file_url", "priority_post", "recipients", "template_used"} },
    ["clicksend.post_sms_price"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms/price", body = {"body", "country", "custom_string", "from", "list_id", "schedule", "source", "to"} },
    ["clicksend.post_sms_receipts"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms/receipts" },
    ["clicksend.post_voice_price"] = { method = "POST", url = "https://rest.clicksend.com/v3/voice/price", body = {"body", "country", "custom_string", "lang", "list_id", "require_input", "schedule", "source", "to", "voice"} },
    ["clicksend.post_voice_receipts"] = { method = "POST", url = "https://rest.clicksend.com/v3/voice/receipts" },
    ["clicksend.purchase_a_package"] = { method = "PUT", url = "https://rest.clicksend.com/v3/recharge/purchase/{package_id}", path = {"package_id"} },
    ["clicksend.put_automations_email_receipt_rule_id"] = { method = "PUT", url = "https://rest.clicksend.com/v3/automations/email/receipt/{rule_id}", path = {"rule_id"}, body = {"action", "action_address", "enabled", "match_type", "rule_name"} },
    ["clicksend.put_automations_fax_inbound_inbound_rule_id"] = { method = "PUT", url = "https://rest.clicksend.com/v3/automations/fax/inbound/{inbound_rule_id}", path = {"inbound_rule_id"} },
    ["clicksend.put_automations_sms_receipts_receipt_rule_id"] = { method = "PUT", url = "https://rest.clicksend.com/v3/automations/sms/receipts/{receipt_rule_id}", path = {"receipt_rule_id"} },
    ["clicksend.put_automations_voice_receipts_receipt_rule_id"] = { method = "PUT", url = "https://rest.clicksend.com/v3/automations/voice/receipts/{receipt_rule_id}", path = {"receipt_rule_id"} },
    ["clicksend.regenerate_api_key"] = { method = "PUT", url = "https://rest.clicksend.com/v3/subaccounts/{subaccount_id}/regen-api-key", path = {"subaccount_id"} },
    ["clicksend.remove_duplicate_contacts"] = { method = "PUT", url = "https://rest.clicksend.com/v3/lists/{list_id}/remove-duplicates", path = {"list_id"}, body = {"fields"} },
    ["clicksend.remove_opted_out_contacts"] = { method = "PUT", url = "https://rest.clicksend.com/v3/lists/{list_id}/remove-opted-out-contacts/{opt_out_list_id}", path = {"list_id", "opt_out_list_id"} },
    ["clicksend.reseller_by_subdomain"] = { method = "GET", url = "https://rest.clicksend.com/v3/reseller/{subdomain}", path = {"subdomain"} },
    ["clicksend.sdk_download"] = { method = "GET", url = "https://rest.clicksend.com/v3/sdk-download/{type}", path = {"type"} },
    ["clicksend.search_contacts_lists"] = { method = "GET", url = "https://rest.clicksend.com/v3/search/contacts-lists?q={q}", path = {"q"} },
    ["clicksend.search_dedicated_numbers_by_country"] = { method = "GET", url = "https://rest.clicksend.com/v3/numbers/search/{country}?{search}=1&{search_type}=2", path = {"country", "search", "search_type"} },
    ["clicksend.search_locations"] = { method = "GET", url = "https://rest.clicksend.com/v3/post/direct-mail/locations/search/{country}/?q={query}", path = {"country", "query"} },
    ["clicksend.send_a_voice_call"] = { method = "POST", url = "https://rest.clicksend.com/v3/voice/send", body = {"body", "country", "custom_string", "lang", "list_id", "machine_detection", "require_input", "schedule", "source", "to", "voice"} },
    ["clicksend.send_account_activation_token"] = { method = "PUT", url = "https://rest.clicksend.com/v3/account-verify/send", body = {"country", "type", "user_phone"} },
    ["clicksend.send_an_sms"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms/send", body = {"body", "country", "custom_string", "from", "from_email", "list_id", "schedule", "source", "to"} },
    ["clicksend.send_fax"] = { method = "POST", url = "https://rest.clicksend.com/v3/fax/send" },
    ["clicksend.send_mms"] = { method = "POST", url = "https://rest.clicksend.com/v3/mms/send", body = {"body", "country", "custom_string", "from", "from_email", "list_id", "media_file", "schedule", "source", "subject", "to"} },
    ["clicksend.send_post_letter"] = { method = "POST", url = "https://rest.clicksend.com/v3/post/letters/send", body = {"colour", "duplex", "file_url", "priority_post", "recipients", "template_used"} },
    ["clicksend.send_postcard"] = { method = "POST", url = "https://rest.clicksend.com/v3/post/postcards/send", body = {"file_urls", "recipients"} },
    ["clicksend.send_verification_token"] = { method = "PUT", url = "https://rest.clicksend.com/v3/email/address-verify/{email_address_id}/send", path = {"email_address_id"} },
    ["clicksend.show_csv_import_file_preview"] = { method = "POST", url = "https://rest.clicksend.com/v3/lists/{list_id}/import-csv-preview", path = {"list_id"}, body = {"file_url"} },
    ["clicksend.transfer_a_contact"] = { method = "PUT", url = "https://rest.clicksend.com/v3/lists/{from_list_id}/contacts/{contact_id}/{to_list_id}", path = {"from_list_id", "contact_id", "to_list_id"} },
    ["clicksend.transfer_credit"] = { method = "PUT", url = "https://rest.clicksend.com/v3/reseller/transfer-credit", body = {"balance", "client_user_id", "currency"} },
    ["clicksend.update_a_rule"] = { method = "PUT", url = "https://rest.clicksend.com/v3/automations/fax/receipts/{rule_id}", path = {"rule_id"}, body = {"action", "action_address", "enabled", "match_type", "rule_name"} },
    ["clicksend.update_a_rule"] = { method = "PUT", url = "https://rest.clicksend.com/v3/automations/sms/inbound/{inbound_rule_id}", path = {"inbound_rule_id"}, body = {"action", "action_address", "dedicated_number", "enabled", "message_search_term", "message_search_type"} },
    ["clicksend.update_a_specific_contact"] = { method = "PUT", url = "https://rest.clicksend.com/v3/lists/{list_id}/contacts/{contact_id}", path = {"list_id", "contact_id"}, body = {"address_city", "address_country", "address_line_1", "address_line_2", "address_postal_code", "address_state", "custom_1", "custom_2", "custom_3", "custom_4", "email", "fax_number", "first_name", "last_name", "organization_name", "phone_number"} },
    ["clicksend.update_a_specific_contact_list"] = { method = "PUT", url = "https://rest.clicksend.com/v3/lists/{list_id}", path = {"list_id"}, body = {"list_name"} },
    ["clicksend.update_a_specific_subaccount"] = { method = "PUT", url = "https://rest.clicksend.com/v3/subaccounts/{subaccount_id}", path = {"subaccount_id"}, body = {"access_billing", "access_contacts", "access_reporting", "access_settings", "access_users", "email", "first_name", "last_name", "password", "phone_number", "share_campaigns"} },
    ["clicksend.update_a_template"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms/templates/{template_id}", path = {"template_id"}, body = {"body", "template_name"} },
    ["clicksend.update_account"] = { method = "PUT", url = "https://rest.clicksend.com/v3/account", body = {"account_name", "country", "password", "private_uploads", "setting_sms_hide_business_name", "setting_sms_hide_your_number", "timezone", "user_email", "user_first_name", "user_last_name", "user_phone", "username"} },
    ["clicksend.update_an_email_template"] = { method = "PUT", url = "https://rest.clicksend.com/v3/email/templates/{template_id}", path = {"template_id"}, body = {"body", "template_name"} },
    ["clicksend.update_an_sms_campaign"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms-campaigns/{sms_campaign_id}", path = {"sms_campaign_id"}, body = {"body", "from", "list_id", "name", "schedule"} },
    ["clicksend.update_credit_card_info"] = { method = "PUT", url = "https://rest.clicksend.com/v3/recharge/credit-card", body = {"bank_name", "cvc", "expiry_month", "expiry_year", "name", "number"} },
    ["clicksend.update_email_campaign"] = { method = "PUT", url = "https://rest.clicksend.com/v3/email-campaigns/{email_campaign_id}", path = {"email_campaign_id"}, body = {"from_email_address_id", "from_name", "list_id", "name", "schedule", "subject", "template_id"} },
    ["clicksend.update_email_to_sms_allowed_address"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms/email-sms/{email_address_id}", path = {"email_address_id"}, body = {"email_address", "from"} },
    ["clicksend.update_post_return_address"] = { method = "PUT", url = "https://rest.clicksend.com/v3/post/return-addresses/{return_address_id}", path = {"return_address_id"} },
    ["clicksend.update_reseller_account"] = { method = "PUT", url = "https://rest.clicksend.com/v3/reseller/accounts/{client_user_id}", path = {"client_user_id"} },
    ["clicksend.update_reseller_setting"] = { method = "PUT", url = "https://rest.clicksend.com/v3/reseller", body = {"allow_public_signups", "colour_navigation", "company_name", "default_margin", "default_margin_numbers", "logo_url_dark", "logo_url_light", "subdomain", "trial_balance"} },
    ["clicksend.update_stripped_string"] = { method = "PUT", url = "https://rest.clicksend.com/v3/sms/email-sms-stripped-strings/{rule_id}", path = {"rule_id"}, body = {"strip_string"} },
    ["clicksend.upload_a_file"] = { method = "POST", url = "https://rest.clicksend.com/v3/uploads?convert={convert}" },
    ["clicksend.upload_image_to_specific_template"] = { method = "POST", url = "https://rest.clicksend.com/v3/email/templates-images/{template_id}", path = {"template_id"}, body = {"image", "url"} },
    ["clicksend.use_short_url"] = { method = "POST", url = "https://rest.clicksend.com/v3/sms-campaigns/send", body = {"body", "from", "list_id", "name", "schedule", "url_to_shorten"} },
    ["clicksend.verify_allowed_email_address"] = { method = "PUT", url = "https://rest.clicksend.com/v3/email/address-verify/{email_address_id}/verify/{activation_token}", path = {"email_address_id", "activation_token"} },
    ["clicksend.verify_forgot_password"] = { method = "PUT", url = "https://rest.clicksend.com/v3/forgot-password/verify", body = {"activation_token", "password", "subaccount_id"} },
    ["clicksend.verify_new_account"] = { method = "PUT", url = "https://rest.clicksend.com/v3/account-verify/verify/{activation_token}", path = {"activation_token"} },
    ["clicksend.voice_languages"] = { method = "GET", url = "https://rest.clicksend.com/v3/voice/lang" },
  },
}
