-- Streak — every call this API accepts, as data.
--
-- GENERATED from https://api.streak.com/api/openapi.json
-- Published on the vendor's own documentation site (https://api.streak.com).
-- 58 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "streak",
  name = "Streak",
  base = "https://api.streak.com/api",
  docs = "https://nango.dev/docs/api-integrations/streak",
  auth = {
    kind = "basic",
    header = "authorization",
    format = "Bearer {token}",
    env = nil,
    user_env = "STREAK_USER",
    pass_env = "STREAK_PASS",
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["streak.delete_v1_apikeys_apiKeyKey"] = { method = "DELETE", url = "https://api.streak.com/api/v1/apikeys/{apiKeyKey}", path = {"apiKeyKey"} },
    ["streak.delete_v1_pipelines_pipelineKey_fields_fieldKey"] = { method = "DELETE", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/fields/{fieldKey}", path = {"fieldKey", "pipelineKey"} },
    ["streak.delete_v2_comments_commentKey"] = { method = "DELETE", url = "https://api.streak.com/api/v2/comments/{commentKey}", path = {"commentKey"} },
    ["streak.delete_v2_contacts_contactKey"] = { method = "DELETE", url = "https://api.streak.com/api/v2/contacts/{contactKey}", path = {"contactKey"} },
    ["streak.delete_v2_meetings_meetingKey"] = { method = "DELETE", url = "https://api.streak.com/api/v2/meetings/{meetingKey}", path = {"meetingKey"} },
    ["streak.delete_v2_organizations_organizationKey"] = { method = "DELETE", url = "https://api.streak.com/api/v2/organizations/{organizationKey}", path = {"organizationKey"} },
    ["streak.delete_v2_pipelines_pipelineKey"] = { method = "DELETE", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}", path = {"pipelineKey"} },
    ["streak.delete_v2_pipelines_pipelineKey_stages_stageKey"] = { method = "DELETE", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages/{stageKey}", path = {"pipelineKey", "stageKey"} },
    ["streak.delete_v2_tasks_taskKey"] = { method = "DELETE", url = "https://api.streak.com/api/v2/tasks/{taskKey}", path = {"taskKey"} },
    ["streak.get_v1_apikeys"] = { method = "GET", url = "https://api.streak.com/api/v1/apikeys", query = {"limit", "page"} },
    ["streak.get_v1_boxes_boxKey_md"] = { method = "GET", url = "https://api.streak.com/api/v1/boxes/{boxKey}/md", path = {"boxKey"}, query = {"maxTokens"} },
    ["streak.get_v1_pipelines_pipelineKey_fields"] = { method = "GET", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/fields", path = {"pipelineKey"} },
    ["streak.get_v1_pipelines_pipelineKey_fields_fieldKey"] = { method = "GET", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/fields/{fieldKey}", path = {"fieldKey", "pipelineKey"} },
    ["streak.get_v1_search"] = { method = "GET", url = "https://api.streak.com/api/v1/search", query = {"name", "page", "pipelineKey", "query", "stageKey", "teamKey"} },
    ["streak.get_v1_users_me"] = { method = "GET", url = "https://api.streak.com/api/v1/users/me" },
    ["streak.get_v1_users_userKey"] = { method = "GET", url = "https://api.streak.com/api/v1/users/{userKey}", path = {"userKey"} },
    ["streak.get_v2_boxes_boxKey_comments"] = { method = "GET", url = "https://api.streak.com/api/v2/boxes/{boxKey}/comments", path = {"boxKey"} },
    ["streak.get_v2_boxes_boxKey_meetings"] = { method = "GET", url = "https://api.streak.com/api/v2/boxes/{boxKey}/meetings", path = {"boxKey"}, query = {"limit", "page"} },
    ["streak.get_v2_boxes_boxKey_tasks"] = { method = "GET", url = "https://api.streak.com/api/v2/boxes/{boxKey}/tasks", path = {"boxKey"}, query = {"limit", "page"} },
    ["streak.get_v2_comments_commentKey"] = { method = "GET", url = "https://api.streak.com/api/v2/comments/{commentKey}", path = {"commentKey"} },
    ["streak.get_v2_contacts_contactKey"] = { method = "GET", url = "https://api.streak.com/api/v2/contacts/{contactKey}", path = {"contactKey"} },
    ["streak.get_v2_meetings_meetingKey"] = { method = "GET", url = "https://api.streak.com/api/v2/meetings/{meetingKey}", path = {"meetingKey"} },
    ["streak.get_v2_organizations_organizationKey"] = { method = "GET", url = "https://api.streak.com/api/v2/organizations/{organizationKey}", path = {"organizationKey"} },
    ["streak.get_v2_pipelines"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines", query = {"sortBy", "limit", "page"} },
    ["streak.get_v2_pipelines_pipelineKey"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}", path = {"pipelineKey"} },
    ["streak.get_v2_pipelines_pipelineKey_stages"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages", path = {"pipelineKey"} },
    ["streak.get_v2_pipelines_pipelineKey_stages_stageKey"] = { method = "GET", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages/{stageKey}", path = {"pipelineKey", "stageKey"} },
    ["streak.get_v2_tasks"] = { method = "GET", url = "https://api.streak.com/api/v2/tasks", query = {"direction", "includeCompleted", "limit", "pipelineKey", "sortOrder", "userKeys"} },
    ["streak.get_v2_tasks_taskKey"] = { method = "GET", url = "https://api.streak.com/api/v2/tasks/{taskKey}", path = {"taskKey"} },
    ["streak.get_v2_teams_teamKey"] = { method = "GET", url = "https://api.streak.com/api/v2/teams/{teamKey}", path = {"teamKey"} },
    ["streak.get_v2_teams_teamKey_contacts"] = { method = "GET", url = "https://api.streak.com/api/v2/teams/{teamKey}/contacts", path = {"teamKey"}, query = {"after", "cursor", "limit"} },
    ["streak.get_v2_teams_teamKey_organizations"] = { method = "GET", url = "https://api.streak.com/api/v2/teams/{teamKey}/organizations", path = {"teamKey"}, query = {"cursor", "limit"} },
    ["streak.get_v2_teams_teamKey_users"] = { method = "GET", url = "https://api.streak.com/api/v2/teams/{teamKey}/users", path = {"teamKey"} },
    ["streak.get_v2_users_me_teams"] = { method = "GET", url = "https://api.streak.com/api/v2/users/me/teams", query = {"limit", "page"} },
    ["streak.post_v1_pipelines_pipelineKey_fields_fieldKey"] = { method = "POST", url = "https://api.streak.com/api/v1/pipelines/{pipelineKey}/fields/{fieldKey}", path = {"fieldKey", "pipelineKey"}, query = {"addOnly"}, body = {"name", "defaultValue", "dropdownSettings", "tagSettings", "aiSettings"} },
    ["streak.post_v1_users_userKey"] = { method = "POST", url = "https://api.streak.com/api/v1/users/{userKey}", path = {"userKey"}, body = {"timezoneId", "firstName", "lastName", "automaticallySendInvoiceEmails", "emailsToSendInvoiceTo", "customerSpecifiedInvoiceData"} },
    ["streak.post_v2_boxes_boxKey_comments"] = { method = "POST", url = "https://api.streak.com/api/v2/boxes/{boxKey}/comments", path = {"boxKey"}, body = {"message", "mentions", "parent", "searchForAtMentions"} },
    ["streak.post_v2_boxes_boxKey_meetings"] = { method = "POST", url = "https://api.streak.com/api/v2/boxes/{boxKey}/meetings", path = {"boxKey"}, body = {"meetingType", "startTimestamp", "duration", "notes", "taskKeys", "isDraft"} },
    ["streak.post_v2_boxes_boxKey_tasks"] = { method = "POST", url = "https://api.streak.com/api/v2/boxes/{boxKey}/tasks", path = {"boxKey"}, body = {"text", "dueDate", "assignedTo", "meetingKey", "isDraft", "teamContactKey", "draft"} },
    ["streak.post_v2_comments_commentKey"] = { method = "POST", url = "https://api.streak.com/api/v2/comments/{commentKey}", path = {"commentKey"}, body = {"message", "mentions"} },
    ["streak.post_v2_comments_commentKey_react"] = { method = "POST", url = "https://api.streak.com/api/v2/comments/{commentKey}/react", path = {"commentKey"}, body = {"emoji"} },
    ["streak.post_v2_comments_commentKey_unreact"] = { method = "POST", url = "https://api.streak.com/api/v2/comments/{commentKey}/unreact", path = {"commentKey"}, body = {"emoji"} },
    ["streak.post_v2_contacts_batch_get"] = { method = "POST", url = "https://api.streak.com/api/v2/contacts/batch/get" },
    ["streak.post_v2_contacts_contactKey"] = { method = "POST", url = "https://api.streak.com/api/v2/contacts/{contactKey}", path = {"contactKey"}, body = {"givenName", "familyName", "title", "other", "emailAddresses", "phoneNumbers", "addresses", "domains", "twitterHandle", "facebookHandle", "linkedinHandle", "instagramHandle", "photoUrl", "fields", "contactLinks", "orgLinks"} },
    ["streak.post_v2_meetings_meetingKey"] = { method = "POST", url = "https://api.streak.com/api/v2/meetings/{meetingKey}", path = {"meetingKey"}, body = {"meetingType", "startTimestamp", "duration", "notes", "isDraft", "taskKeys"} },
    ["streak.post_v2_organizations_batch_get"] = { method = "POST", url = "https://api.streak.com/api/v2/organizations/batch/get" },
    ["streak.post_v2_organizations_organizationKey"] = { method = "POST", url = "https://api.streak.com/api/v2/organizations/{organizationKey}", path = {"organizationKey"}, body = {"name", "other", "domains", "industry", "phoneNumbers", "addresses", "employeeCount", "logoURL", "twitterHandle", "facebookHandle", "linkedinHandle", "instagramHandle", "contactLinks", "orgLinks", "fields"} },
    ["streak.post_v2_pipelines"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines", body = {"name", "teamKey", "stages", "icon", "description", "templateType", "fields", "defaultPermissionSetName", "sharingRestrictedToTeam"} },
    ["streak.post_v2_pipelines_pipelineKey"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}", path = {"pipelineKey"}, body = {"teamKey", "icon", "name", "description", "sharingRestrictedToTeam", "stageOrder", "stageColorTheme", "customPermissionSets", "defaultPermissionSetName", "aclEntries"} },
    ["streak.post_v2_pipelines_pipelineKey_fields"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/fields", path = {"pipelineKey"}, body = {"name", "type", "defaultValue"} },
    ["streak.post_v2_pipelines_pipelineKey_stages"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages", path = {"pipelineKey"}, body = {"name", "color"} },
    ["streak.post_v2_pipelines_pipelineKey_stages_stageKey"] = { method = "POST", url = "https://api.streak.com/api/v2/pipelines/{pipelineKey}/stages/{stageKey}", path = {"pipelineKey", "stageKey"}, body = {"name", "color"} },
    ["streak.post_v2_tasks_taskKey"] = { method = "POST", url = "https://api.streak.com/api/v2/tasks/{taskKey}", path = {"taskKey"}, body = {"text", "dueDate", "status", "assignedTo", "meetingKey", "isDraft", "draft"} },
    ["streak.post_v2_teams"] = { method = "POST", url = "https://api.streak.com/api/v2/teams", body = {"name", "members"} },
    ["streak.post_v2_teams_teamKey"] = { method = "POST", url = "https://api.streak.com/api/v2/teams/{teamKey}", path = {"teamKey"}, body = {"name", "sharingRestrictedToTeam", "automaticallyApproveJoinRequests", "automaticallySendInvoiceEmails", "emailsToSendInvoiceTo", "members", "contactOrgListPermissions", "contactSettings", "organizationSettings"} },
    ["streak.post_v2_teams_teamKey_contacts"] = { method = "POST", url = "https://api.streak.com/api/v2/teams/{teamKey}/contacts", path = {"teamKey"}, query = {"getIfExisting"}, body = {"givenName", "familyName", "title", "other", "emailAddresses", "phoneNumbers", "addresses", "domains", "twitterHandle", "facebookHandle", "linkedinHandle", "instagramHandle", "photoUrl"} },
    ["streak.post_v2_teams_teamKey_organizations"] = { method = "POST", url = "https://api.streak.com/api/v2/teams/{teamKey}/organizations", path = {"teamKey"}, query = {"getIfExisting"}, body = {"name", "other", "domains", "industry", "phoneNumbers", "addresses", "employeeCount", "logoURL", "twitterHandle", "facebookHandle", "linkedinHandle", "instagramHandle"} },
    ["streak.put_v1_apikeys"] = { method = "PUT", url = "https://api.streak.com/api/v1/apikeys", query = {"teamKey"} },
  },
}
