-- AWS Inspector2 — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/amazonaws.com/inspector/2016-02-16/openapi.json
-- APIs.guru's mirror of amazonaws.com:inspector, matched on amazonaws.com. A mirror lags the vendor.
-- 37 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "aws-inspector2",
  name = "AWS Inspector2",
  base = "https://inspector2.{region}.amazonaws.com",
  docs = "https://nango.dev/docs/api-integrations/aws-inspector2",
  auth = {
    kind = "basic",
    header = "authorization",
    format = "Bearer {token}",
    env = nil,
    user_env = "AWS_INSPECTOR2_USER",
    pass_env = "AWS_INSPECTOR2_PASS",
    param = nil,
  },
  config = { ["region"] = "AWS_INSPECTOR2_REGION" },
  headers = {},
  operations = {
    ["aws-inspector2.add_attributes_to_findings"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.AddAttributesToFindings", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"findingArns", "attributes"} },
    ["aws-inspector2.create_assessment_target"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.CreateAssessmentTarget", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTargetName", "resourceGroupArn"} },
    ["aws-inspector2.create_assessment_template"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.CreateAssessmentTemplate", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTargetArn", "assessmentTemplateName", "durationInSeconds", "rulesPackageArns", "userAttributesForFindings"} },
    ["aws-inspector2.create_exclusions_preview"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.CreateExclusionsPreview", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTemplateArn"} },
    ["aws-inspector2.create_resource_group"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.CreateResourceGroup", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"resourceGroupTags"} },
    ["aws-inspector2.delete_assessment_run"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DeleteAssessmentRun", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentRunArn"} },
    ["aws-inspector2.delete_assessment_target"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DeleteAssessmentTarget", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTargetArn"} },
    ["aws-inspector2.delete_assessment_template"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DeleteAssessmentTemplate", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTemplateArn"} },
    ["aws-inspector2.describe_assessment_runs"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DescribeAssessmentRuns", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentRunArns"} },
    ["aws-inspector2.describe_assessment_targets"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DescribeAssessmentTargets", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTargetArns"} },
    ["aws-inspector2.describe_assessment_templates"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DescribeAssessmentTemplates", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTemplateArns"} },
    ["aws-inspector2.describe_cross_account_access_role"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DescribeCrossAccountAccessRole", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"} },
    ["aws-inspector2.describe_exclusions"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DescribeExclusions", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"exclusionArns", "locale"} },
    ["aws-inspector2.describe_findings"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DescribeFindings", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"findingArns", "locale"} },
    ["aws-inspector2.describe_resource_groups"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DescribeResourceGroups", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"resourceGroupArns"} },
    ["aws-inspector2.describe_rules_packages"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.DescribeRulesPackages", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"rulesPackageArns", "locale"} },
    ["aws-inspector2.get_assessment_report"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.GetAssessmentReport", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentRunArn", "reportFileFormat", "reportType"} },
    ["aws-inspector2.get_exclusions_preview"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.GetExclusionsPreview", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTemplateArn", "previewToken", "nextToken", "maxResults", "locale"} },
    ["aws-inspector2.get_telemetry_metadata"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.GetTelemetryMetadata", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentRunArn"} },
    ["aws-inspector2.list_assessment_run_agents"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListAssessmentRunAgents", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentRunArn", "filter", "nextToken", "maxResults"} },
    ["aws-inspector2.list_assessment_runs"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListAssessmentRuns", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTemplateArns", "filter", "nextToken", "maxResults"} },
    ["aws-inspector2.list_assessment_targets"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListAssessmentTargets", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"filter", "nextToken", "maxResults"} },
    ["aws-inspector2.list_assessment_templates"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListAssessmentTemplates", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTargetArns", "filter", "nextToken", "maxResults"} },
    ["aws-inspector2.list_event_subscriptions"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListEventSubscriptions", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"resourceArn", "nextToken", "maxResults"} },
    ["aws-inspector2.list_exclusions"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListExclusions", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentRunArn", "nextToken", "maxResults"} },
    ["aws-inspector2.list_findings"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListFindings", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentRunArns", "filter", "nextToken", "maxResults"} },
    ["aws-inspector2.list_rules_packages"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListRulesPackages", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"nextToken", "maxResults"} },
    ["aws-inspector2.list_tags_for_resource"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.ListTagsForResource", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"resourceArn"} },
    ["aws-inspector2.preview_agents"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.PreviewAgents", query = {"maxResults", "nextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"previewAgentsArn", "nextToken", "maxResults"} },
    ["aws-inspector2.register_cross_account_access_role"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.RegisterCrossAccountAccessRole", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"roleArn"} },
    ["aws-inspector2.remove_attributes_from_findings"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.RemoveAttributesFromFindings", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"findingArns", "attributeKeys"} },
    ["aws-inspector2.set_tags_for_resource"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.SetTagsForResource", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"resourceArn", "tags"} },
    ["aws-inspector2.start_assessment_run"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.StartAssessmentRun", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTemplateArn", "assessmentRunName"} },
    ["aws-inspector2.stop_assessment_run"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.StopAssessmentRun", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentRunArn", "stopAction"} },
    ["aws-inspector2.subscribe_to_event"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.SubscribeToEvent", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"resourceArn", "event", "topicArn"} },
    ["aws-inspector2.unsubscribe_from_event"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.UnsubscribeFromEvent", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"resourceArn", "event", "topicArn"} },
    ["aws-inspector2.update_assessment_target"] = { method = "POST", url = "https://inspector2.{region}.amazonaws.com/#X-Amz-Target=InspectorService.UpdateAssessmentTarget", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"assessmentTargetArn", "assessmentTargetName", "resourceGroupArn"} },
  },
}
