-- Klaviyo — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/klaviyo/openapi/main/openapi/stable.json
-- Published by klaviyo, the vendor's own GitHub organisation.
-- 345 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "klaviyo",
  name = "Klaviyo",
  base = "https://a.klaviyo.com",
  docs = "https://nango.dev/docs/integrations/all/klaviyo",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Klaviyo-API-Key {token}",
    env = "KLAVIYO_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = { ["revision"] = "2024-07-15" },
  operations = {
    ["klaviyo.add_categories_to_catalog_item"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-items/{id}/relationships/categories", path = {"id"}, header = {"revision"} },
    ["klaviyo.add_items_to_catalog_category"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-categories/{id}/relationships/items", path = {"id"}, header = {"revision"} },
    ["klaviyo.add_profiles_to_list"] = { method = "POST", url = "https://a.klaviyo.com/api/lists/{id}/relationships/profiles", path = {"id"}, header = {"revision"} },
    ["klaviyo.assign_template_to_campaign_message"] = { method = "POST", url = "https://a.klaviyo.com/api/campaign-message-assign-template", query = {"fields[campaign-message]"}, header = {"revision"} },
    ["klaviyo.bulk_create_catalog_categories"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-category-bulk-create-jobs", query = {"fields[catalog-category-bulk-create-job]"}, header = {"revision"} },
    ["klaviyo.bulk_create_catalog_items"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-item-bulk-create-jobs", query = {"fields[catalog-item-bulk-create-job]"}, header = {"revision"} },
    ["klaviyo.bulk_create_catalog_variants"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-variant-bulk-create-jobs", query = {"fields[catalog-variant-bulk-create-job]"}, header = {"revision"} },
    ["klaviyo.bulk_create_client_events"] = { method = "POST", url = "https://a.klaviyo.com/client/event-bulk-create", query = {"company_id"}, header = {"revision"} },
    ["klaviyo.bulk_create_coupon_codes"] = { method = "POST", url = "https://a.klaviyo.com/api/coupon-code-bulk-create-jobs", query = {"fields[coupon-code-bulk-create-job]"}, header = {"revision"} },
    ["klaviyo.bulk_create_data_source_records"] = { method = "POST", url = "https://a.klaviyo.com/api/data-source-record-bulk-create-jobs", header = {"revision"} },
    ["klaviyo.bulk_create_events"] = { method = "POST", url = "https://a.klaviyo.com/api/event-bulk-create-jobs", header = {"revision"} },
    ["klaviyo.bulk_delete_catalog_categories"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-category-bulk-delete-jobs", query = {"fields[catalog-category-bulk-delete-job]"}, header = {"revision"} },
    ["klaviyo.bulk_delete_catalog_items"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-item-bulk-delete-jobs", query = {"fields[catalog-item-bulk-delete-job]"}, header = {"revision"} },
    ["klaviyo.bulk_delete_catalog_variants"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-variant-bulk-delete-jobs", query = {"fields[catalog-variant-bulk-delete-job]"}, header = {"revision"} },
    ["klaviyo.bulk_delete_object_records"] = { method = "POST", url = "https://a.klaviyo.com/api/object-record-bulk-delete-jobs", header = {"revision"} },
    ["klaviyo.bulk_import_profiles"] = { method = "POST", url = "https://a.klaviyo.com/api/profile-bulk-import-jobs", query = {"fields[profile-bulk-import-job]"}, header = {"revision"} },
    ["klaviyo.bulk_subscribe_profiles"] = { method = "POST", url = "https://a.klaviyo.com/api/profile-subscription-bulk-create-jobs", header = {"revision"} },
    ["klaviyo.bulk_suppress_profiles"] = { method = "POST", url = "https://a.klaviyo.com/api/profile-suppression-bulk-create-jobs", query = {"fields[profile-suppression-bulk-create-job]"}, header = {"revision"} },
    ["klaviyo.bulk_unsubscribe_profiles"] = { method = "POST", url = "https://a.klaviyo.com/api/profile-subscription-bulk-delete-jobs", header = {"revision"} },
    ["klaviyo.bulk_unsuppress_profiles"] = { method = "POST", url = "https://a.klaviyo.com/api/profile-suppression-bulk-delete-jobs", query = {"fields[profile-suppression-bulk-delete-job]"}, header = {"revision"} },
    ["klaviyo.bulk_update_catalog_categories"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-category-bulk-update-jobs", query = {"fields[catalog-category-bulk-update-job]"}, header = {"revision"} },
    ["klaviyo.bulk_update_catalog_items"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-item-bulk-update-jobs", query = {"fields[catalog-item-bulk-update-job]"}, header = {"revision"} },
    ["klaviyo.bulk_update_catalog_variants"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-variant-bulk-update-jobs", query = {"fields[catalog-variant-bulk-update-job]"}, header = {"revision"} },
    ["klaviyo.cancel_campaign_send"] = { method = "PATCH", url = "https://a.klaviyo.com/api/campaign-send-jobs/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.clone_template"] = { method = "POST", url = "https://a.klaviyo.com/api/template-clone", query = {"fields[template]"}, header = {"revision"} },
    ["klaviyo.create_back_in_stock_subscription"] = { method = "POST", url = "https://a.klaviyo.com/api/back-in-stock-subscriptions", header = {"revision"} },
    ["klaviyo.create_campaign"] = { method = "POST", url = "https://a.klaviyo.com/api/campaigns", query = {"fields[campaign]"}, header = {"revision"} },
    ["klaviyo.create_campaign_clone"] = { method = "POST", url = "https://a.klaviyo.com/api/campaign-clone", query = {"fields[campaign]"}, header = {"revision"} },
    ["klaviyo.create_catalog_category"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-categories", query = {"fields[catalog-category]"}, header = {"revision"} },
    ["klaviyo.create_catalog_item"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-items", query = {"fields[catalog-item]"}, header = {"revision"} },
    ["klaviyo.create_catalog_variant"] = { method = "POST", url = "https://a.klaviyo.com/api/catalog-variants", query = {"fields[catalog-variant]"}, header = {"revision"} },
    ["klaviyo.create_client_back_in_stock_subscription"] = { method = "POST", url = "https://a.klaviyo.com/client/back-in-stock-subscriptions", query = {"company_id"}, header = {"revision"} },
    ["klaviyo.create_client_event"] = { method = "POST", url = "https://a.klaviyo.com/client/events", query = {"company_id"}, header = {"revision"} },
    ["klaviyo.create_client_profile"] = { method = "POST", url = "https://a.klaviyo.com/client/profiles", query = {"company_id"}, header = {"revision"} },
    ["klaviyo.create_client_push_token"] = { method = "POST", url = "https://a.klaviyo.com/client/push-tokens", query = {"company_id"}, header = {"revision"} },
    ["klaviyo.create_client_review"] = { method = "POST", url = "https://a.klaviyo.com/client/reviews", query = {"company_id"}, header = {"revision"} },
    ["klaviyo.create_client_subscription"] = { method = "POST", url = "https://a.klaviyo.com/client/subscriptions", query = {"company_id"}, header = {"revision"} },
    ["klaviyo.create_conversation_message"] = { method = "POST", url = "https://a.klaviyo.com/api/conversation-messages", header = {"revision"} },
    ["klaviyo.create_coupon"] = { method = "POST", url = "https://a.klaviyo.com/api/coupons", query = {"fields[coupon]"}, header = {"revision"} },
    ["klaviyo.create_coupon_code"] = { method = "POST", url = "https://a.klaviyo.com/api/coupon-codes", query = {"fields[coupon-code]"}, header = {"revision"} },
    ["klaviyo.create_custom_metric"] = { method = "POST", url = "https://a.klaviyo.com/api/custom-metrics", query = {"fields[custom-metric]"}, header = {"revision"} },
    ["klaviyo.create_data_source"] = { method = "POST", url = "https://a.klaviyo.com/api/data-sources", query = {"fields[data-source]"}, header = {"revision"} },
    ["klaviyo.create_data_source_record"] = { method = "POST", url = "https://a.klaviyo.com/api/data-source-record-create-jobs", header = {"revision"} },
    ["klaviyo.create_event"] = { method = "POST", url = "https://a.klaviyo.com/api/events", header = {"revision"} },
    ["klaviyo.create_flow"] = { method = "POST", url = "https://a.klaviyo.com/api/flows", query = {"additional-fields[flow]", "fields[flow]"}, header = {"revision"} },
    ["klaviyo.create_form"] = { method = "POST", url = "https://a.klaviyo.com/api/forms", query = {"fields[form]"}, header = {"revision"} },
    ["klaviyo.create_list"] = { method = "POST", url = "https://a.klaviyo.com/api/lists", query = {"fields[list]"}, header = {"revision"} },
    ["klaviyo.create_object_schema"] = { method = "POST", url = "https://a.klaviyo.com/api/object-schemas", query = {"fields[object-schema]"}, header = {"revision"} },
    ["klaviyo.create_object_schema_relationship"] = { method = "POST", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/object-schemas", path = {"id"}, header = {"revision"} },
    ["klaviyo.create_object_type"] = { method = "POST", url = "https://a.klaviyo.com/api/object-types", query = {"fields[object-type]"}, header = {"revision"} },
    ["klaviyo.create_or_update_profile"] = { method = "POST", url = "https://a.klaviyo.com/api/profile-import", query = {"additional-fields[profile]", "fields[profile]"}, header = {"revision"} },
    ["klaviyo.create_profile"] = { method = "POST", url = "https://a.klaviyo.com/api/profiles", query = {"additional-fields[profile]", "fields[profile]"}, header = {"revision"} },
    ["klaviyo.create_profile_schema_relationship"] = { method = "POST", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/profile-object-schemas", path = {"id"}, header = {"revision"} },
    ["klaviyo.create_push_token"] = { method = "POST", url = "https://a.klaviyo.com/api/push-tokens", header = {"revision"} },
    ["klaviyo.create_segment"] = { method = "POST", url = "https://a.klaviyo.com/api/segments", query = {"fields[segment]"}, header = {"revision"} },
    ["klaviyo.create_tag"] = { method = "POST", url = "https://a.klaviyo.com/api/tags", query = {"fields[tag]"}, header = {"revision"} },
    ["klaviyo.create_tag_group"] = { method = "POST", url = "https://a.klaviyo.com/api/tag-groups", query = {"fields[tag-group]"}, header = {"revision"} },
    ["klaviyo.create_template"] = { method = "POST", url = "https://a.klaviyo.com/api/templates", query = {"additional-fields[template]", "fields[template]"}, header = {"revision"} },
    ["klaviyo.create_universal_content"] = { method = "POST", url = "https://a.klaviyo.com/api/template-universal-content", query = {"fields[template-universal-content]"}, header = {"revision"} },
    ["klaviyo.create_web_feed"] = { method = "POST", url = "https://a.klaviyo.com/api/web-feeds", query = {"fields[web-feed]"}, header = {"revision"} },
    ["klaviyo.create_webhook"] = { method = "POST", url = "https://a.klaviyo.com/api/webhooks", query = {"fields[webhook]"}, header = {"revision"} },
    ["klaviyo.delete_campaign"] = { method = "DELETE", url = "https://a.klaviyo.com/api/campaigns/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_catalog_category"] = { method = "DELETE", url = "https://a.klaviyo.com/api/catalog-categories/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_catalog_item"] = { method = "DELETE", url = "https://a.klaviyo.com/api/catalog-items/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_catalog_variant"] = { method = "DELETE", url = "https://a.klaviyo.com/api/catalog-variants/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_coupon"] = { method = "DELETE", url = "https://a.klaviyo.com/api/coupons/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_coupon_code"] = { method = "DELETE", url = "https://a.klaviyo.com/api/coupon-codes/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_custom_metric"] = { method = "DELETE", url = "https://a.klaviyo.com/api/custom-metrics/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_data_source"] = { method = "DELETE", url = "https://a.klaviyo.com/api/data-sources/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_flow"] = { method = "DELETE", url = "https://a.klaviyo.com/api/flows/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_flow_action"] = { method = "DELETE", url = "https://a.klaviyo.com/api/flow-actions/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_form"] = { method = "DELETE", url = "https://a.klaviyo.com/api/forms/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_list"] = { method = "DELETE", url = "https://a.klaviyo.com/api/lists/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_object_schema_relationship"] = { method = "DELETE", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/object-schemas", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_object_type"] = { method = "DELETE", url = "https://a.klaviyo.com/api/object-types/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_profile_schema_relationship"] = { method = "DELETE", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/profile-object-schemas", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_push_token"] = { method = "DELETE", url = "https://a.klaviyo.com/api/push-tokens/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_segment"] = { method = "DELETE", url = "https://a.klaviyo.com/api/segments/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_tag"] = { method = "DELETE", url = "https://a.klaviyo.com/api/tags/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_tag_group"] = { method = "DELETE", url = "https://a.klaviyo.com/api/tag-groups/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_template"] = { method = "DELETE", url = "https://a.klaviyo.com/api/templates/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_universal_content"] = { method = "DELETE", url = "https://a.klaviyo.com/api/template-universal-content/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_web_feed"] = { method = "DELETE", url = "https://a.klaviyo.com/api/web-feeds/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.delete_webhook"] = { method = "DELETE", url = "https://a.klaviyo.com/api/webhooks/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_account"] = { method = "GET", url = "https://a.klaviyo.com/api/accounts/{id}", path = {"id"}, query = {"fields[account]"}, header = {"revision"} },
    ["klaviyo.get_accounts"] = { method = "GET", url = "https://a.klaviyo.com/api/accounts", query = {"fields[account]"}, header = {"revision"} },
    ["klaviyo.get_action_for_flow_message"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-messages/{id}/flow-action", path = {"id"}, query = {"fields[flow-action]"}, header = {"revision"} },
    ["klaviyo.get_action_id_for_flow_message"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-messages/{id}/relationships/flow-action", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_action_ids_for_flow"] = { method = "GET", url = "https://a.klaviyo.com/api/flows/{id}/relationships/flow-actions", path = {"id"}, query = {"filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_actions_for_flow"] = { method = "GET", url = "https://a.klaviyo.com/api/flows/{id}/flow-actions", path = {"id"}, query = {"fields[flow-action]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_all_universal_content"] = { method = "GET", url = "https://a.klaviyo.com/api/template-universal-content", query = {"fields[template-universal-content]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_bulk_create_catalog_items_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-item-bulk-create-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-item-bulk-create-job]", "fields[catalog-item]", "include"}, header = {"revision"} },
    ["klaviyo.get_bulk_create_catalog_items_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-item-bulk-create-jobs", query = {"fields[catalog-item-bulk-create-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_create_categories_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-category-bulk-create-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-category-bulk-create-job]", "fields[catalog-category]", "include"}, header = {"revision"} },
    ["klaviyo.get_bulk_create_categories_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-category-bulk-create-jobs", query = {"fields[catalog-category-bulk-create-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_create_coupon_code_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/coupon-code-bulk-create-jobs", query = {"fields[coupon-code-bulk-create-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_create_coupon_codes_job"] = { method = "GET", url = "https://a.klaviyo.com/api/coupon-code-bulk-create-jobs/{job_id}", path = {"job_id"}, query = {"fields[coupon-code-bulk-create-job]", "fields[coupon-code]", "include"}, header = {"revision"} },
    ["klaviyo.get_bulk_create_variants_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-variant-bulk-create-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-variant-bulk-create-job]", "fields[catalog-variant]", "include"}, header = {"revision"} },
    ["klaviyo.get_bulk_create_variants_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-variant-bulk-create-jobs", query = {"fields[catalog-variant-bulk-create-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_delete_catalog_items_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-item-bulk-delete-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-item-bulk-delete-job]"}, header = {"revision"} },
    ["klaviyo.get_bulk_delete_catalog_items_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-item-bulk-delete-jobs", query = {"fields[catalog-item-bulk-delete-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_delete_categories_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-category-bulk-delete-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-category-bulk-delete-job]"}, header = {"revision"} },
    ["klaviyo.get_bulk_delete_categories_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-category-bulk-delete-jobs", query = {"fields[catalog-category-bulk-delete-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_delete_variants_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-variant-bulk-delete-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-variant-bulk-delete-job]"}, header = {"revision"} },
    ["klaviyo.get_bulk_delete_variants_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-variant-bulk-delete-jobs", query = {"fields[catalog-variant-bulk-delete-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_import_profiles_job"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-bulk-import-jobs/{job_id}", path = {"job_id"}, query = {"fields[list]", "fields[profile-bulk-import-job]", "include"}, header = {"revision"} },
    ["klaviyo.get_bulk_import_profiles_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-bulk-import-jobs", query = {"fields[profile-bulk-import-job]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_bulk_suppress_profiles_job"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-suppression-bulk-create-jobs/{job_id}", path = {"job_id"}, query = {"fields[profile-suppression-bulk-create-job]"}, header = {"revision"} },
    ["klaviyo.get_bulk_suppress_profiles_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-suppression-bulk-create-jobs", query = {"fields[profile-suppression-bulk-create-job]", "filter", "page[cursor]", "sort"}, header = {"revision"} },
    ["klaviyo.get_bulk_unsuppress_profiles_job"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-suppression-bulk-delete-jobs/{job_id}", path = {"job_id"}, query = {"fields[profile-suppression-bulk-delete-job]"}, header = {"revision"} },
    ["klaviyo.get_bulk_unsuppress_profiles_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-suppression-bulk-delete-jobs", query = {"fields[profile-suppression-bulk-delete-job]", "filter", "page[cursor]", "sort"}, header = {"revision"} },
    ["klaviyo.get_bulk_update_catalog_items_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-item-bulk-update-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-item-bulk-update-job]", "fields[catalog-item]", "include"}, header = {"revision"} },
    ["klaviyo.get_bulk_update_catalog_items_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-item-bulk-update-jobs", query = {"fields[catalog-item-bulk-update-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_update_categories_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-category-bulk-update-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-category-bulk-update-job]", "fields[catalog-category]", "include"}, header = {"revision"} },
    ["klaviyo.get_bulk_update_categories_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-category-bulk-update-jobs", query = {"fields[catalog-category-bulk-update-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_bulk_update_variants_job"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-variant-bulk-update-jobs/{job_id}", path = {"job_id"}, query = {"fields[catalog-variant-bulk-update-job]", "fields[catalog-variant]", "include"}, header = {"revision"} },
    ["klaviyo.get_bulk_update_variants_jobs"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-variant-bulk-update-jobs", query = {"fields[catalog-variant-bulk-update-job]", "filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_campaign"] = { method = "GET", url = "https://a.klaviyo.com/api/campaigns/{id}", path = {"id"}, query = {"fields[campaign-message]", "fields[campaign]", "fields[tag]", "include"}, header = {"revision"} },
    ["klaviyo.get_campaign_for_campaign_message"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-messages/{id}/campaign", path = {"id"}, query = {"fields[campaign]"}, header = {"revision"} },
    ["klaviyo.get_campaign_id_for_campaign_message"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-messages/{id}/relationships/campaign", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_campaign_ids_for_tag"] = { method = "GET", url = "https://a.klaviyo.com/api/tags/{id}/relationships/campaigns", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_campaign_message"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-messages/{id}", path = {"id"}, query = {"fields[campaign-message]", "fields[campaign]", "fields[image]", "fields[template]", "include"}, header = {"revision"} },
    ["klaviyo.get_campaign_recipient_estimation"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-recipient-estimations/{id}", path = {"id"}, query = {"fields[campaign-recipient-estimation]"}, header = {"revision"} },
    ["klaviyo.get_campaign_recipient_estimation_job"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-recipient-estimation-jobs/{id}", path = {"id"}, query = {"fields[campaign-recipient-estimation-job]"}, header = {"revision"} },
    ["klaviyo.get_campaign_send_job"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-send-jobs/{id}", path = {"id"}, query = {"fields[campaign-send-job]"}, header = {"revision"} },
    ["klaviyo.get_campaigns"] = { method = "GET", url = "https://a.klaviyo.com/api/campaigns", query = {"fields[campaign-message]", "fields[campaign]", "fields[tag]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_catalog_categories"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-categories", query = {"fields[catalog-category]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_catalog_category"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-categories/{id}", path = {"id"}, query = {"fields[catalog-category]"}, header = {"revision"} },
    ["klaviyo.get_catalog_item"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-items/{id}", path = {"id"}, query = {"fields[catalog-item]", "fields[catalog-variant]", "include"}, header = {"revision"} },
    ["klaviyo.get_catalog_items"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-items", query = {"fields[catalog-item]", "fields[catalog-variant]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_catalog_variant"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-variants/{id}", path = {"id"}, query = {"fields[catalog-variant]"}, header = {"revision"} },
    ["klaviyo.get_catalog_variants"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-variants", query = {"fields[catalog-variant]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_categories_for_catalog_item"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-items/{id}/categories", path = {"id"}, query = {"fields[catalog-category]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_category_ids_for_catalog_item"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-items/{id}/relationships/categories", path = {"id"}, query = {"filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_client_geofences"] = { method = "GET", url = "https://a.klaviyo.com/client/geofences", query = {"company_id", "fields[geofence]", "page[cursor]", "page[size]"}, header = {"X-Klaviyo-API-Filters", "revision"} },
    ["klaviyo.get_client_ip_allowlist"] = { method = "GET", url = "https://a.klaviyo.com/client/ip-allowlists/{id}", path = {"id"}, query = {"company_id", "fields[ip-allowlist]"}, header = {"revision"} },
    ["klaviyo.get_client_review_values_reports"] = { method = "GET", url = "https://a.klaviyo.com/client/review-values-reports", query = {"company_id", "fields[review-values-report]", "filter", "group_by", "page[cursor]", "page[size]", "statistics", "timeframe"}, header = {"revision"} },
    ["klaviyo.get_client_reviews"] = { method = "GET", url = "https://a.klaviyo.com/client/reviews", query = {"company_id", "fields[review]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_conversation_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/conversation", path = {"id"}, query = {"fields[conversation]"}, header = {"revision"} },
    ["klaviyo.get_conversation_id_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/relationships/conversation", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_conversation_ids_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/relationships/conversations", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_conversations_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/conversations", path = {"id"}, query = {"fields[conversation]"}, header = {"revision"} },
    ["klaviyo.get_coupon"] = { method = "GET", url = "https://a.klaviyo.com/api/coupons/{id}", path = {"id"}, query = {"fields[coupon]"}, header = {"revision"} },
    ["klaviyo.get_coupon_code"] = { method = "GET", url = "https://a.klaviyo.com/api/coupon-codes/{id}", path = {"id"}, query = {"fields[coupon-code]", "fields[coupon]", "include"}, header = {"revision"} },
    ["klaviyo.get_coupon_code_ids_for_coupon"] = { method = "GET", url = "https://a.klaviyo.com/api/coupons/{id}/relationships/coupon-codes", path = {"id"}, query = {"filter", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_coupon_codes"] = { method = "GET", url = "https://a.klaviyo.com/api/coupon-codes", query = {"fields[coupon-code]", "fields[coupon]", "filter", "include", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_coupon_codes_for_coupon"] = { method = "GET", url = "https://a.klaviyo.com/api/coupons/{id}/coupon-codes", path = {"id"}, query = {"fields[coupon-code]", "filter", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_coupon_for_coupon_code"] = { method = "GET", url = "https://a.klaviyo.com/api/coupon-codes/{id}/coupon", path = {"id"}, query = {"fields[coupon]"}, header = {"revision"} },
    ["klaviyo.get_coupon_id_for_coupon_code"] = { method = "GET", url = "https://a.klaviyo.com/api/coupon-codes/{id}/relationships/coupon", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_coupons"] = { method = "GET", url = "https://a.klaviyo.com/api/coupons", query = {"fields[coupon]", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_current_schema_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/current-schema", path = {"id"}, query = {"fields[object-schema]"}, header = {"revision"} },
    ["klaviyo.get_current_schema_id_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/relationships/current-schema", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_custom_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/custom-metrics/{id}", path = {"id"}, query = {"fields[custom-metric]", "fields[metric]", "include"}, header = {"revision"} },
    ["klaviyo.get_custom_metric_for_mapped_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/mapped-metrics/{id}/custom-metric", path = {"id"}, query = {"fields[custom-metric]"}, header = {"revision"} },
    ["klaviyo.get_custom_metric_id_for_mapped_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/mapped-metrics/{id}/relationships/custom-metric", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_custom_metrics"] = { method = "GET", url = "https://a.klaviyo.com/api/custom-metrics", query = {"fields[custom-metric]", "fields[metric]", "include"}, header = {"revision"} },
    ["klaviyo.get_data_source"] = { method = "GET", url = "https://a.klaviyo.com/api/data-sources/{id}", path = {"id"}, query = {"fields[data-source]"}, header = {"revision"} },
    ["klaviyo.get_data_sources"] = { method = "GET", url = "https://a.klaviyo.com/api/data-sources", query = {"fields[data-source]", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_draft_schema_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/draft-schema", path = {"id"}, query = {"fields[object-schema]"}, header = {"revision"} },
    ["klaviyo.get_draft_schema_id_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/relationships/draft-schema", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_errors_for_bulk_import_profiles_job"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-bulk-import-jobs/{id}/import-errors", path = {"id"}, query = {"fields[import-error]", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_event"] = { method = "GET", url = "https://a.klaviyo.com/api/events/{id}", path = {"id"}, query = {"fields[attribution]", "fields[event]", "fields[metric]", "fields[profile]", "include"}, header = {"revision"} },
    ["klaviyo.get_events"] = { method = "GET", url = "https://a.klaviyo.com/api/events", query = {"fields[attribution]", "fields[event]", "fields[metric]", "fields[profile]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_flow"] = { method = "GET", url = "https://a.klaviyo.com/api/flows/{id}", path = {"id"}, query = {"additional-fields[flow]", "fields[flow-action]", "fields[flow]", "fields[tag]", "include"}, header = {"revision"} },
    ["klaviyo.get_flow_action"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-actions/{id}", path = {"id"}, query = {"fields[flow-action]", "fields[flow-message]", "fields[flow]", "include"}, header = {"revision"} },
    ["klaviyo.get_flow_action_messages"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-actions/{id}/flow-messages", path = {"id"}, query = {"fields[flow-message]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_flow_for_flow_action"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-actions/{id}/flow", path = {"id"}, query = {"fields[flow]"}, header = {"revision"} },
    ["klaviyo.get_flow_id_for_flow_action"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-actions/{id}/relationships/flow", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_flow_ids_for_tag"] = { method = "GET", url = "https://a.klaviyo.com/api/tags/{id}/relationships/flows", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_flow_message"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-messages/{id}", path = {"id"}, query = {"fields[flow-action]", "fields[flow-message]", "fields[template]", "include"}, header = {"revision"} },
    ["klaviyo.get_flows"] = { method = "GET", url = "https://a.klaviyo.com/api/flows", query = {"fields[flow-action]", "fields[flow]", "fields[tag]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_flows_triggered_by_list"] = { method = "GET", url = "https://a.klaviyo.com/api/lists/{id}/flow-triggers", path = {"id"}, query = {"fields[flow]"}, header = {"revision"} },
    ["klaviyo.get_flows_triggered_by_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/metrics/{id}/flow-triggers", path = {"id"}, query = {"fields[flow]"}, header = {"revision"} },
    ["klaviyo.get_flows_triggered_by_segment"] = { method = "GET", url = "https://a.klaviyo.com/api/segments/{id}/flow-triggers", path = {"id"}, query = {"fields[flow]"}, header = {"revision"} },
    ["klaviyo.get_form"] = { method = "GET", url = "https://a.klaviyo.com/api/forms/{id}", path = {"id"}, query = {"fields[form]"}, header = {"revision"} },
    ["klaviyo.get_form_for_form_version"] = { method = "GET", url = "https://a.klaviyo.com/api/form-versions/{id}/form", path = {"id"}, query = {"fields[form]"}, header = {"revision"} },
    ["klaviyo.get_form_id_for_form_version"] = { method = "GET", url = "https://a.klaviyo.com/api/form-versions/{id}/relationships/form", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_form_version"] = { method = "GET", url = "https://a.klaviyo.com/api/form-versions/{id}", path = {"id"}, query = {"fields[form-version]", "fields[form]", "include"}, header = {"revision"} },
    ["klaviyo.get_forms"] = { method = "GET", url = "https://a.klaviyo.com/api/forms", query = {"fields[form]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_ids_for_flows_triggered_by_list"] = { method = "GET", url = "https://a.klaviyo.com/api/lists/{id}/relationships/flow-triggers", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_ids_for_flows_triggered_by_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/metrics/{id}/relationships/flow-triggers", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_ids_for_flows_triggered_by_segment"] = { method = "GET", url = "https://a.klaviyo.com/api/segments/{id}/relationships/flow-triggers", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_image"] = { method = "GET", url = "https://a.klaviyo.com/api/images/{id}", path = {"id"}, query = {"fields[image]"}, header = {"revision"} },
    ["klaviyo.get_image_for_campaign_message"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-messages/{id}/image", path = {"id"}, query = {"fields[image]"}, header = {"revision"} },
    ["klaviyo.get_image_id_for_campaign_message"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-messages/{id}/relationships/image", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_images"] = { method = "GET", url = "https://a.klaviyo.com/api/images", query = {"fields[image]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_ingestion_log_ids_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/relationships/object-ingestion-logs", path = {"id"}, query = {"filter", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_ingestion_logs_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/object-ingestion-logs", path = {"id"}, query = {"fields[object-ingestion-log]", "fields[object-record]", "fields[object-type]", "filter", "include", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_item_ids_for_catalog_category"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-categories/{id}/relationships/items", path = {"id"}, query = {"filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_items_for_catalog_category"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-categories/{id}/items", path = {"id"}, query = {"fields[catalog-item]", "fields[catalog-variant]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_list"] = { method = "GET", url = "https://a.klaviyo.com/api/lists/{id}", path = {"id"}, query = {"additional-fields[list]", "fields[flow]", "fields[list]", "fields[tag]", "include"}, header = {"revision"} },
    ["klaviyo.get_list_for_bulk_import_profiles_job"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-bulk-import-jobs/{id}/lists", path = {"id"}, query = {"fields[list]"}, header = {"revision"} },
    ["klaviyo.get_list_ids_for_bulk_import_profiles_job"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-bulk-import-jobs/{id}/relationships/lists", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_list_ids_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/relationships/lists", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_list_ids_for_tag"] = { method = "GET", url = "https://a.klaviyo.com/api/tags/{id}/relationships/lists", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_lists"] = { method = "GET", url = "https://a.klaviyo.com/api/lists", query = {"fields[flow]", "fields[list]", "fields[tag]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_lists_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/lists", path = {"id"}, query = {"fields[list]"}, header = {"revision"} },
    ["klaviyo.get_mapped_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/mapped-metrics/{id}", path = {"id"}, query = {"fields[custom-metric]", "fields[mapped-metric]", "fields[metric]", "include"}, header = {"revision"} },
    ["klaviyo.get_mapped_metrics"] = { method = "GET", url = "https://a.klaviyo.com/api/mapped-metrics", query = {"fields[custom-metric]", "fields[mapped-metric]", "fields[metric]", "include"}, header = {"revision"} },
    ["klaviyo.get_message_ids_for_campaign"] = { method = "GET", url = "https://a.klaviyo.com/api/campaigns/{id}/relationships/campaign-messages", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_message_ids_for_flow_action"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-actions/{id}/relationships/flow-messages", path = {"id"}, query = {"filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_messages_for_campaign"] = { method = "GET", url = "https://a.klaviyo.com/api/campaigns/{id}/campaign-messages", path = {"id"}, query = {"fields[campaign-message]", "fields[campaign]", "fields[image]", "fields[template]", "include"}, header = {"revision"} },
    ["klaviyo.get_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/metrics/{id}", path = {"id"}, query = {"fields[flow]", "fields[metric]", "include"}, header = {"revision"} },
    ["klaviyo.get_metric_for_event"] = { method = "GET", url = "https://a.klaviyo.com/api/events/{id}/metric", path = {"id"}, query = {"fields[metric]"}, header = {"revision"} },
    ["klaviyo.get_metric_for_mapped_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/mapped-metrics/{id}/metric", path = {"id"}, query = {"fields[metric]"}, header = {"revision"} },
    ["klaviyo.get_metric_for_metric_property"] = { method = "GET", url = "https://a.klaviyo.com/api/metric-properties/{id}/metric", path = {"id"}, query = {"fields[metric]"}, header = {"revision"} },
    ["klaviyo.get_metric_id_for_event"] = { method = "GET", url = "https://a.klaviyo.com/api/events/{id}/relationships/metric", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_metric_id_for_mapped_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/mapped-metrics/{id}/relationships/metric", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_metric_id_for_metric_property"] = { method = "GET", url = "https://a.klaviyo.com/api/metric-properties/{id}/relationships/metric", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_metric_ids_for_custom_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/custom-metrics/{id}/relationships/metrics", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_metric_property"] = { method = "GET", url = "https://a.klaviyo.com/api/metric-properties/{id}", path = {"id"}, query = {"additional-fields[metric-property]", "fields[metric-property]", "fields[metric]", "include"}, header = {"revision"} },
    ["klaviyo.get_metrics"] = { method = "GET", url = "https://a.klaviyo.com/api/metrics", query = {"fields[flow]", "fields[metric]", "filter", "include", "page[cursor]"}, header = {"revision"} },
    ["klaviyo.get_metrics_for_custom_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/custom-metrics/{id}/metrics", path = {"id"}, query = {"fields[metric]"}, header = {"revision"} },
    ["klaviyo.get_object_record"] = { method = "GET", url = "https://a.klaviyo.com/api/object-records/{id}", path = {"id"}, query = {"fields[object-record]"}, header = {"revision"} },
    ["klaviyo.get_object_schema"] = { method = "GET", url = "https://a.klaviyo.com/api/object-schemas/{id}", path = {"id"}, query = {"fields[object-schema]", "fields[profile-object-schema]", "fields[source-mapping]", "include"}, header = {"revision"} },
    ["klaviyo.get_object_schema_relationships"] = { method = "GET", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/object-schemas", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}", path = {"id"}, query = {"fields[object-schema]", "fields[object-type]", "fields[profile-object-type]", "include"}, header = {"revision"} },
    ["klaviyo.get_object_type_relationships"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/relationships/object-types", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_object_types"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types", query = {"fields[object-schema]", "fields[object-type]", "filter", "include"}, header = {"revision"} },
    ["klaviyo.get_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}", path = {"id"}, query = {"additional-fields[profile]", "fields[conversation]", "fields[list]", "fields[profile]", "fields[push-token]", "fields[segment]", "include"}, header = {"revision"} },
    ["klaviyo.get_profile_for_event"] = { method = "GET", url = "https://a.klaviyo.com/api/events/{id}/profile", path = {"id"}, query = {"additional-fields[profile]", "fields[profile]"}, header = {"revision"} },
    ["klaviyo.get_profile_for_push_token"] = { method = "GET", url = "https://a.klaviyo.com/api/push-tokens/{id}/profile", path = {"id"}, query = {"additional-fields[profile]", "fields[profile]"}, header = {"revision"} },
    ["klaviyo.get_profile_id_for_event"] = { method = "GET", url = "https://a.klaviyo.com/api/events/{id}/relationships/profile", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_profile_id_for_push_token"] = { method = "GET", url = "https://a.klaviyo.com/api/push-tokens/{id}/relationships/profile", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_profile_ids_for_bulk_import_profiles_job"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-bulk-import-jobs/{id}/relationships/profiles", path = {"id"}, query = {"page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_profile_ids_for_list"] = { method = "GET", url = "https://a.klaviyo.com/api/lists/{id}/relationships/profiles", path = {"id"}, query = {"filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_profile_ids_for_segment"] = { method = "GET", url = "https://a.klaviyo.com/api/segments/{id}/relationships/profiles", path = {"id"}, query = {"filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_profile_schema_relationships"] = { method = "GET", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/profile-object-schemas", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_profile_type_relationships"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/relationships/profile-object-types", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_profiles"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles", query = {"additional-fields[profile]", "fields[conversation]", "fields[profile]", "fields[push-token]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_profiles_for_bulk_import_profiles_job"] = { method = "GET", url = "https://a.klaviyo.com/api/profile-bulk-import-jobs/{id}/profiles", path = {"id"}, query = {"additional-fields[profile]", "fields[profile]", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_profiles_for_list"] = { method = "GET", url = "https://a.klaviyo.com/api/lists/{id}/profiles", path = {"id"}, query = {"additional-fields[profile]", "fields[profile]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_profiles_for_segment"] = { method = "GET", url = "https://a.klaviyo.com/api/segments/{id}/profiles", path = {"id"}, query = {"additional-fields[profile]", "fields[profile]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_properties_for_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/metrics/{id}/metric-properties", path = {"id"}, query = {"additional-fields[metric-property]", "fields[metric-property]"}, header = {"revision"} },
    ["klaviyo.get_property_ids_for_metric"] = { method = "GET", url = "https://a.klaviyo.com/api/metrics/{id}/relationships/metric-properties", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_push_token"] = { method = "GET", url = "https://a.klaviyo.com/api/push-tokens/{id}", path = {"id"}, query = {"fields[profile]", "fields[push-token]", "include"}, header = {"revision"} },
    ["klaviyo.get_push_token_ids_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/relationships/push-tokens", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_push_tokens"] = { method = "GET", url = "https://a.klaviyo.com/api/push-tokens", query = {"fields[profile]", "fields[push-token]", "filter", "include", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_push_tokens_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/push-tokens", path = {"id"}, query = {"fields[push-token]"}, header = {"revision"} },
    ["klaviyo.get_record_ids_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/relationships/object-records", path = {"id"}, query = {"page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_records_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/object-records", path = {"id"}, query = {"fields[object-record]", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_review"] = { method = "GET", url = "https://a.klaviyo.com/api/reviews/{id}", path = {"id"}, query = {"fields[event]", "fields[review]", "include"}, header = {"revision"} },
    ["klaviyo.get_reviews"] = { method = "GET", url = "https://a.klaviyo.com/api/reviews", query = {"fields[event]", "fields[review]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_schema_version_ids_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/relationships/schema-versions", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_schema_versions_for_object_type"] = { method = "GET", url = "https://a.klaviyo.com/api/object-types/{id}/schema-versions", path = {"id"}, query = {"fields[object-schema]"}, header = {"revision"} },
    ["klaviyo.get_segment"] = { method = "GET", url = "https://a.klaviyo.com/api/segments/{id}", path = {"id"}, query = {"additional-fields[segment]", "fields[flow]", "fields[segment]", "fields[tag]", "include"}, header = {"revision"} },
    ["klaviyo.get_segment_ids_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/relationships/segments", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_segment_ids_for_tag"] = { method = "GET", url = "https://a.klaviyo.com/api/tags/{id}/relationships/segments", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_segments"] = { method = "GET", url = "https://a.klaviyo.com/api/segments", query = {"fields[flow]", "fields[segment]", "fields[tag]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_segments_for_profile"] = { method = "GET", url = "https://a.klaviyo.com/api/profiles/{id}/segments", path = {"id"}, query = {"fields[segment]"}, header = {"revision"} },
    ["klaviyo.get_source_mapping"] = { method = "GET", url = "https://a.klaviyo.com/api/source-mappings/{id}", path = {"id"}, query = {"fields[source-mapping]"}, header = {"revision"} },
    ["klaviyo.get_source_mapping_for_object_schema"] = { method = "GET", url = "https://a.klaviyo.com/api/object-schemas/{id}/source-mapping", path = {"id"}, query = {"fields[source-mapping]"}, header = {"revision"} },
    ["klaviyo.get_source_mapping_id_for_object_schema"] = { method = "GET", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/source-mapping", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_tag"] = { method = "GET", url = "https://a.klaviyo.com/api/tags/{id}", path = {"id"}, query = {"fields[tag-group]", "fields[tag]", "include"}, header = {"revision"} },
    ["klaviyo.get_tag_group"] = { method = "GET", url = "https://a.klaviyo.com/api/tag-groups/{id}", path = {"id"}, query = {"fields[tag-group]"}, header = {"revision"} },
    ["klaviyo.get_tag_group_for_tag"] = { method = "GET", url = "https://a.klaviyo.com/api/tags/{id}/tag-group", path = {"id"}, query = {"fields[tag-group]"}, header = {"revision"} },
    ["klaviyo.get_tag_group_id_for_tag"] = { method = "GET", url = "https://a.klaviyo.com/api/tags/{id}/relationships/tag-group", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_tag_groups"] = { method = "GET", url = "https://a.klaviyo.com/api/tag-groups", query = {"fields[tag-group]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_tag_ids_for_campaign"] = { method = "GET", url = "https://a.klaviyo.com/api/campaigns/{id}/relationships/tags", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_tag_ids_for_flow"] = { method = "GET", url = "https://a.klaviyo.com/api/flows/{id}/relationships/tags", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_tag_ids_for_list"] = { method = "GET", url = "https://a.klaviyo.com/api/lists/{id}/relationships/tags", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_tag_ids_for_segment"] = { method = "GET", url = "https://a.klaviyo.com/api/segments/{id}/relationships/tags", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_tag_ids_for_tag_group"] = { method = "GET", url = "https://a.klaviyo.com/api/tag-groups/{id}/relationships/tags", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_tags"] = { method = "GET", url = "https://a.klaviyo.com/api/tags", query = {"fields[tag-group]", "fields[tag]", "filter", "include", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_tags_for_campaign"] = { method = "GET", url = "https://a.klaviyo.com/api/campaigns/{id}/tags", path = {"id"}, query = {"fields[tag]"}, header = {"revision"} },
    ["klaviyo.get_tags_for_flow"] = { method = "GET", url = "https://a.klaviyo.com/api/flows/{id}/tags", path = {"id"}, query = {"fields[tag]"}, header = {"revision"} },
    ["klaviyo.get_tags_for_list"] = { method = "GET", url = "https://a.klaviyo.com/api/lists/{id}/tags", path = {"id"}, query = {"fields[tag]"}, header = {"revision"} },
    ["klaviyo.get_tags_for_segment"] = { method = "GET", url = "https://a.klaviyo.com/api/segments/{id}/tags", path = {"id"}, query = {"fields[tag]"}, header = {"revision"} },
    ["klaviyo.get_tags_for_tag_group"] = { method = "GET", url = "https://a.klaviyo.com/api/tag-groups/{id}/tags", path = {"id"}, query = {"fields[tag]"}, header = {"revision"} },
    ["klaviyo.get_template"] = { method = "GET", url = "https://a.klaviyo.com/api/templates/{id}", path = {"id"}, query = {"additional-fields[template]", "fields[template]"}, header = {"revision"} },
    ["klaviyo.get_template_for_campaign_message"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-messages/{id}/template", path = {"id"}, query = {"fields[template]"}, header = {"revision"} },
    ["klaviyo.get_template_for_flow_message"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-messages/{id}/template", path = {"id"}, query = {"fields[template]"}, header = {"revision"} },
    ["klaviyo.get_template_id_for_campaign_message"] = { method = "GET", url = "https://a.klaviyo.com/api/campaign-messages/{id}/relationships/template", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_template_id_for_flow_message"] = { method = "GET", url = "https://a.klaviyo.com/api/flow-messages/{id}/relationships/template", path = {"id"}, header = {"revision"} },
    ["klaviyo.get_templates"] = { method = "GET", url = "https://a.klaviyo.com/api/templates", query = {"additional-fields[template]", "fields[template]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_tracking_setting"] = { method = "GET", url = "https://a.klaviyo.com/api/tracking-settings/{id}", path = {"id"}, query = {"fields[tracking-setting]"}, header = {"revision"} },
    ["klaviyo.get_tracking_settings"] = { method = "GET", url = "https://a.klaviyo.com/api/tracking-settings", query = {"fields[tracking-setting]", "page[cursor]", "page[size]"}, header = {"revision"} },
    ["klaviyo.get_universal_content"] = { method = "GET", url = "https://a.klaviyo.com/api/template-universal-content/{id}", path = {"id"}, query = {"fields[template-universal-content]"}, header = {"revision"} },
    ["klaviyo.get_variant_ids_for_catalog_item"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-items/{id}/relationships/variants", path = {"id"}, query = {"filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_variants_for_catalog_item"] = { method = "GET", url = "https://a.klaviyo.com/api/catalog-items/{id}/variants", path = {"id"}, query = {"fields[catalog-variant]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_version_ids_for_form"] = { method = "GET", url = "https://a.klaviyo.com/api/forms/{id}/relationships/form-versions", path = {"id"}, query = {"filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_versions_for_form"] = { method = "GET", url = "https://a.klaviyo.com/api/forms/{id}/form-versions", path = {"id"}, query = {"fields[form-version]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_web_feed"] = { method = "GET", url = "https://a.klaviyo.com/api/web-feeds/{id}", path = {"id"}, query = {"fields[web-feed]"}, header = {"revision"} },
    ["klaviyo.get_web_feeds"] = { method = "GET", url = "https://a.klaviyo.com/api/web-feeds", query = {"fields[web-feed]", "filter", "page[cursor]", "page[size]", "sort"}, header = {"revision"} },
    ["klaviyo.get_webhook"] = { method = "GET", url = "https://a.klaviyo.com/api/webhooks/{id}", path = {"id"}, query = {"fields[webhook-topic]", "fields[webhook]", "include"}, header = {"revision"} },
    ["klaviyo.get_webhook_topic"] = { method = "GET", url = "https://a.klaviyo.com/api/webhook-topics/{id}", path = {"id"}, query = {"fields[webhook-topic]"}, header = {"revision"} },
    ["klaviyo.get_webhook_topics"] = { method = "GET", url = "https://a.klaviyo.com/api/webhook-topics", query = {"fields[webhook-topic]"}, header = {"revision"} },
    ["klaviyo.get_webhooks"] = { method = "GET", url = "https://a.klaviyo.com/api/webhooks", query = {"fields[webhook-topic]", "fields[webhook]", "include"}, header = {"revision"} },
    ["klaviyo.merge_profiles"] = { method = "POST", url = "https://a.klaviyo.com/api/profile-merge", query = {"fields[profile]"}, header = {"revision"} },
    ["klaviyo.query_campaign_values"] = { method = "POST", url = "https://a.klaviyo.com/api/campaign-values-reports", query = {"fields[campaign-values-report]", "page_cursor"}, header = {"revision"} },
    ["klaviyo.query_flow_series"] = { method = "POST", url = "https://a.klaviyo.com/api/flow-series-reports", query = {"fields[flow-series-report]", "page_cursor"}, header = {"revision"} },
    ["klaviyo.query_flow_values"] = { method = "POST", url = "https://a.klaviyo.com/api/flow-values-reports", query = {"fields[flow-values-report]", "page_cursor"}, header = {"revision"} },
    ["klaviyo.query_form_series"] = { method = "POST", url = "https://a.klaviyo.com/api/form-series-reports", query = {"fields[form-series-report]"}, header = {"revision"} },
    ["klaviyo.query_form_values"] = { method = "POST", url = "https://a.klaviyo.com/api/form-values-reports", query = {"fields[form-values-report]"}, header = {"revision"} },
    ["klaviyo.query_metric_aggregates"] = { method = "POST", url = "https://a.klaviyo.com/api/metric-aggregates", query = {"fields[metric-aggregate]"}, header = {"revision"} },
    ["klaviyo.query_segment_series"] = { method = "POST", url = "https://a.klaviyo.com/api/segment-series-reports", query = {"fields[segment-series-report]"}, header = {"revision"} },
    ["klaviyo.query_segment_values"] = { method = "POST", url = "https://a.klaviyo.com/api/segment-values-reports", query = {"fields[segment-values-report]"}, header = {"revision"} },
    ["klaviyo.refresh_campaign_recipient_estimation"] = { method = "POST", url = "https://a.klaviyo.com/api/campaign-recipient-estimation-jobs", query = {"fields[campaign-recipient-estimation-job]"}, header = {"revision"} },
    ["klaviyo.remove_categories_from_catalog_item"] = { method = "DELETE", url = "https://a.klaviyo.com/api/catalog-items/{id}/relationships/categories", path = {"id"}, header = {"revision"} },
    ["klaviyo.remove_items_from_catalog_category"] = { method = "DELETE", url = "https://a.klaviyo.com/api/catalog-categories/{id}/relationships/items", path = {"id"}, header = {"revision"} },
    ["klaviyo.remove_profiles_from_list"] = { method = "DELETE", url = "https://a.klaviyo.com/api/lists/{id}/relationships/profiles", path = {"id"}, header = {"revision"} },
    ["klaviyo.remove_tag_from_campaigns"] = { method = "DELETE", url = "https://a.klaviyo.com/api/tags/{id}/relationships/campaigns", path = {"id"}, header = {"revision"} },
    ["klaviyo.remove_tag_from_flows"] = { method = "DELETE", url = "https://a.klaviyo.com/api/tags/{id}/relationships/flows", path = {"id"}, header = {"revision"} },
    ["klaviyo.remove_tag_from_lists"] = { method = "DELETE", url = "https://a.klaviyo.com/api/tags/{id}/relationships/lists", path = {"id"}, header = {"revision"} },
    ["klaviyo.remove_tag_from_segments"] = { method = "DELETE", url = "https://a.klaviyo.com/api/tags/{id}/relationships/segments", path = {"id"}, header = {"revision"} },
    ["klaviyo.render_template"] = { method = "POST", url = "https://a.klaviyo.com/api/template-render", query = {"fields[template]"}, header = {"revision"} },
    ["klaviyo.request_profile_deletion"] = { method = "POST", url = "https://a.klaviyo.com/api/data-privacy-deletion-jobs", header = {"revision"} },
    ["klaviyo.send_campaign"] = { method = "POST", url = "https://a.klaviyo.com/api/campaign-send-jobs", query = {"fields[campaign-send-job]"}, header = {"revision"} },
    ["klaviyo.tag_campaigns"] = { method = "POST", url = "https://a.klaviyo.com/api/tags/{id}/relationships/campaigns", path = {"id"}, header = {"revision"} },
    ["klaviyo.tag_flows"] = { method = "POST", url = "https://a.klaviyo.com/api/tags/{id}/relationships/flows", path = {"id"}, header = {"revision"} },
    ["klaviyo.tag_lists"] = { method = "POST", url = "https://a.klaviyo.com/api/tags/{id}/relationships/lists", path = {"id"}, header = {"revision"} },
    ["klaviyo.tag_segments"] = { method = "POST", url = "https://a.klaviyo.com/api/tags/{id}/relationships/segments", path = {"id"}, header = {"revision"} },
    ["klaviyo.unregister_client_push_token"] = { method = "POST", url = "https://a.klaviyo.com/client/push-token-unregister", query = {"company_id"}, header = {"revision"} },
    ["klaviyo.update_campaign"] = { method = "PATCH", url = "https://a.klaviyo.com/api/campaigns/{id}", path = {"id"}, query = {"fields[campaign]"}, header = {"revision"} },
    ["klaviyo.update_campaign_message"] = { method = "PATCH", url = "https://a.klaviyo.com/api/campaign-messages/{id}", path = {"id"}, query = {"fields[campaign-message]"}, header = {"revision"} },
    ["klaviyo.update_catalog_category"] = { method = "PATCH", url = "https://a.klaviyo.com/api/catalog-categories/{id}", path = {"id"}, query = {"fields[catalog-category]"}, header = {"revision"} },
    ["klaviyo.update_catalog_item"] = { method = "PATCH", url = "https://a.klaviyo.com/api/catalog-items/{id}", path = {"id"}, query = {"fields[catalog-item]"}, header = {"revision"} },
    ["klaviyo.update_catalog_variant"] = { method = "PATCH", url = "https://a.klaviyo.com/api/catalog-variants/{id}", path = {"id"}, query = {"fields[catalog-variant]"}, header = {"revision"} },
    ["klaviyo.update_categories_for_catalog_item"] = { method = "PATCH", url = "https://a.klaviyo.com/api/catalog-items/{id}/relationships/categories", path = {"id"}, header = {"revision"} },
    ["klaviyo.update_coupon"] = { method = "PATCH", url = "https://a.klaviyo.com/api/coupons/{id}", path = {"id"}, query = {"fields[coupon]"}, header = {"revision"} },
    ["klaviyo.update_coupon_code"] = { method = "PATCH", url = "https://a.klaviyo.com/api/coupon-codes/{id}", path = {"id"}, query = {"fields[coupon-code]"}, header = {"revision"} },
    ["klaviyo.update_custom_metric"] = { method = "PATCH", url = "https://a.klaviyo.com/api/custom-metrics/{id}", path = {"id"}, query = {"fields[custom-metric]"}, header = {"revision"} },
    ["klaviyo.update_flow"] = { method = "PATCH", url = "https://a.klaviyo.com/api/flows/{id}", path = {"id"}, query = {"fields[flow]"}, header = {"revision"} },
    ["klaviyo.update_flow_action"] = { method = "PATCH", url = "https://a.klaviyo.com/api/flow-actions/{id}", path = {"id"}, query = {"fields[flow-action]"}, header = {"revision"} },
    ["klaviyo.update_image"] = { method = "PATCH", url = "https://a.klaviyo.com/api/images/{id}", path = {"id"}, query = {"fields[image]"}, header = {"revision"} },
    ["klaviyo.update_image_for_campaign_message"] = { method = "PATCH", url = "https://a.klaviyo.com/api/campaign-messages/{id}/relationships/image", path = {"id"}, header = {"revision"} },
    ["klaviyo.update_items_for_catalog_category"] = { method = "PATCH", url = "https://a.klaviyo.com/api/catalog-categories/{id}/relationships/items", path = {"id"}, header = {"revision"} },
    ["klaviyo.update_list"] = { method = "PATCH", url = "https://a.klaviyo.com/api/lists/{id}", path = {"id"}, query = {"fields[list]"}, header = {"revision"} },
    ["klaviyo.update_mapped_metric"] = { method = "PATCH", url = "https://a.klaviyo.com/api/mapped-metrics/{id}", path = {"id"}, query = {"fields[mapped-metric]"}, header = {"revision"} },
    ["klaviyo.update_object_schema"] = { method = "PATCH", url = "https://a.klaviyo.com/api/object-schemas/{id}", path = {"id"}, query = {"fields[object-schema]"}, header = {"revision"} },
    ["klaviyo.update_object_schema_relationship"] = { method = "PATCH", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/object-schemas", path = {"id"}, header = {"revision"} },
    ["klaviyo.update_profile"] = { method = "PATCH", url = "https://a.klaviyo.com/api/profiles/{id}", path = {"id"}, query = {"additional-fields[profile]", "fields[profile]"}, header = {"revision"} },
    ["klaviyo.update_profile_schema_relationship"] = { method = "PATCH", url = "https://a.klaviyo.com/api/object-schemas/{id}/relationships/profile-object-schemas", path = {"id"}, header = {"revision"} },
    ["klaviyo.update_review"] = { method = "PATCH", url = "https://a.klaviyo.com/api/reviews/{id}", path = {"id"}, query = {"fields[review]"}, header = {"revision"} },
    ["klaviyo.update_segment"] = { method = "PATCH", url = "https://a.klaviyo.com/api/segments/{id}", path = {"id"}, query = {"fields[segment]"}, header = {"revision"} },
    ["klaviyo.update_source_mapping"] = { method = "PATCH", url = "https://a.klaviyo.com/api/source-mappings/{id}", path = {"id"}, query = {"fields[source-mapping]"}, header = {"revision"} },
    ["klaviyo.update_tag"] = { method = "PATCH", url = "https://a.klaviyo.com/api/tags/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.update_tag_group"] = { method = "PATCH", url = "https://a.klaviyo.com/api/tag-groups/{id}", path = {"id"}, header = {"revision"} },
    ["klaviyo.update_template"] = { method = "PATCH", url = "https://a.klaviyo.com/api/templates/{id}", path = {"id"}, query = {"additional-fields[template]", "fields[template]"}, header = {"revision"} },
    ["klaviyo.update_tracking_setting"] = { method = "PATCH", url = "https://a.klaviyo.com/api/tracking-settings/{id}", path = {"id"}, query = {"fields[tracking-setting]"}, header = {"revision"} },
    ["klaviyo.update_universal_content"] = { method = "PATCH", url = "https://a.klaviyo.com/api/template-universal-content/{id}", path = {"id"}, query = {"fields[template-universal-content]"}, header = {"revision"} },
    ["klaviyo.update_web_feed"] = { method = "PATCH", url = "https://a.klaviyo.com/api/web-feeds/{id}", path = {"id"}, query = {"fields[web-feed]"}, header = {"revision"} },
    ["klaviyo.update_webhook"] = { method = "PATCH", url = "https://a.klaviyo.com/api/webhooks/{id}", path = {"id"}, query = {"fields[webhook]"}, header = {"revision"} },
    ["klaviyo.upload_image_from_file"] = { method = "POST", url = "https://a.klaviyo.com/api/image-upload", query = {"fields[image]"}, header = {"revision"}, body = {"file", "name", "hidden"} },
    ["klaviyo.upload_image_from_url"] = { method = "POST", url = "https://a.klaviyo.com/api/images", query = {"fields[image]"}, header = {"revision"} },
  },
}
