-- Loops.so — every call this API accepts, as data.
--
-- GENERATED from https://loops.so/openapi.json
-- Published on the vendor's own documentation site (https://loops.so).
-- 64 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "loops-so",
  name = "Loops.so",
  base = "https://app.loops.so/api",
  docs = "https://nango.dev/docs/integrations/all/loops-so",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "LOOPS_SO_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["loops-so.add_workflow_branch"] = { method = "POST", url = "https://app.loops.so/api/v1/workflows/{workflowId}/nodes/{nodeId}/add-branch", path = {"workflowId", "nodeId"}, body = {"expectedRevisionId"} },
    ["loops-so.change_workflow_mailing_list"] = { method = "POST", url = "https://app.loops.so/api/v1/workflows/{workflowId}/mailing-list", path = {"workflowId"}, body = {"expectedRevisionId", "mailingListId", "dryRun", "queuedContactPolicy"} },
    ["loops-so.complete_upload"] = { method = "POST", url = "https://app.loops.so/api/v1/uploads/{emailAssetId}/complete", path = {"emailAssetId"} },
    ["loops-so.create_audience_segment"] = { method = "POST", url = "https://app.loops.so/api/v1/audience-segments", body = {"name", "description", "filter"} },
    ["loops-so.create_campaign"] = { method = "POST", url = "https://app.loops.so/api/v1/campaigns", body = {"name", "campaignGroupId", "mailingListId", "audienceSegmentId", "audienceFilter", "scheduling"} },
    ["loops-so.create_campaign_group"] = { method = "POST", url = "https://app.loops.so/api/v1/campaign-groups", body = {"name", "description"} },
    ["loops-so.create_component"] = { method = "POST", url = "https://app.loops.so/api/v1/components", body = {"name", "lmx"} },
    ["loops-so.create_contact"] = { method = "POST", url = "https://app.loops.so/api/v1/contacts/create", body = {"email", "firstName", "lastName", "source", "subscribed", "userGroup", "userId", "mailingLists"} },
    ["loops-so.create_contact_property"] = { method = "POST", url = "https://app.loops.so/api/v1/contacts/properties", body = {"name", "type"} },
    ["loops-so.create_theme"] = { method = "POST", url = "https://app.loops.so/api/v1/themes", body = {"name", "styles"} },
    ["loops-so.create_transactional_email"] = { method = "POST", url = "https://app.loops.so/api/v1/transactional-emails", body = {"name", "transactionalGroupId"} },
    ["loops-so.create_transactional_group"] = { method = "POST", url = "https://app.loops.so/api/v1/transactional-groups", body = {"name", "description"} },
    ["loops-so.create_upload"] = { method = "POST", url = "https://app.loops.so/api/v1/uploads", body = {"contentType", "contentLength"} },
    ["loops-so.create_workflow"] = { method = "POST", url = "https://app.loops.so/api/v1/workflows", body = {"name", "description", "mailingListId"} },
    ["loops-so.create_workflow_node"] = { method = "POST", url = "https://app.loops.so/api/v1/workflows/{workflowId}/nodes", path = {"workflowId"} },
    ["loops-so.delete_contact"] = { method = "POST", url = "https://app.loops.so/api/v1/contacts/delete", body = {"email", "userId"} },
    ["loops-so.delete_workflow"] = { method = "DELETE", url = "https://app.loops.so/api/v1/workflows/{workflowId}", path = {"workflowId"}, body = {"expectedRevisionId", "confirmDelete"} },
    ["loops-so.delete_workflow_node"] = { method = "DELETE", url = "https://app.loops.so/api/v1/workflows/{workflowId}/nodes/{nodeId}", path = {"workflowId", "nodeId"}, body = {"expectedRevisionId", "dryRun", "queuedContactPolicy"} },
    ["loops-so.delete_workflow_node_recursively"] = { method = "DELETE", url = "https://app.loops.so/api/v1/workflows/{workflowId}/nodes/{nodeId}/recursive", path = {"workflowId", "nodeId"}, body = {"expectedRevisionId", "dryRun", "queuedContactPolicy"} },
    ["loops-so.ensure_transactional_draft"] = { method = "POST", url = "https://app.loops.so/api/v1/transactional-emails/{transactionalId}/draft", path = {"transactionalId"} },
    ["loops-so.find_contact"] = { method = "GET", url = "https://app.loops.so/api/v1/contacts/find", query = {"email", "userId"} },
    ["loops-so.get_audience_segment"] = { method = "GET", url = "https://app.loops.so/api/v1/audience-segments/{audienceSegmentId}", path = {"audienceSegmentId"} },
    ["loops-so.get_campaign"] = { method = "GET", url = "https://app.loops.so/api/v1/campaigns/{campaignId}", path = {"campaignId"} },
    ["loops-so.get_campaign_group"] = { method = "GET", url = "https://app.loops.so/api/v1/campaign-groups/{campaignGroupId}", path = {"campaignGroupId"} },
    ["loops-so.get_component"] = { method = "GET", url = "https://app.loops.so/api/v1/components/{componentId}", path = {"componentId"} },
    ["loops-so.get_contact_suppression"] = { method = "GET", url = "https://app.loops.so/api/v1/contacts/suppression", query = {"email", "userId"} },
    ["loops-so.get_email_message"] = { method = "GET", url = "https://app.loops.so/api/v1/email-messages/{emailMessageId}", path = {"emailMessageId"} },
    ["loops-so.get_email_message_guardian"] = { method = "GET", url = "https://app.loops.so/api/v1/email-messages/{emailMessageId}/guardian", path = {"emailMessageId"} },
    ["loops-so.get_event_pattern"] = { method = "GET", url = "https://app.loops.so/api/v1/event-patterns/{eventPatternId}", path = {"eventPatternId"} },
    ["loops-so.get_event_pattern_by_name"] = { method = "GET", url = "https://app.loops.so/api/v1/event-patterns/by-name/{eventName}", path = {"eventName"} },
    ["loops-so.get_theme"] = { method = "GET", url = "https://app.loops.so/api/v1/themes/{themeId}", path = {"themeId"} },
    ["loops-so.get_transactional_email"] = { method = "GET", url = "https://app.loops.so/api/v1/transactional-emails/{transactionalId}", path = {"transactionalId"} },
    ["loops-so.get_transactional_group"] = { method = "GET", url = "https://app.loops.so/api/v1/transactional-groups/{transactionalGroupId}", path = {"transactionalGroupId"} },
    ["loops-so.get_workflow"] = { method = "GET", url = "https://app.loops.so/api/v1/workflows/{workflowId}", path = {"workflowId"} },
    ["loops-so.get_workflow_node"] = { method = "GET", url = "https://app.loops.so/api/v1/workflows/{workflowId}/nodes/{nodeId}", path = {"workflowId", "nodeId"} },
    ["loops-so.list_audience_segments"] = { method = "GET", url = "https://app.loops.so/api/v1/audience-segments", query = {"perPage", "cursor"} },
    ["loops-so.list_campaign_groups"] = { method = "GET", url = "https://app.loops.so/api/v1/campaign-groups", query = {"perPage", "cursor"} },
    ["loops-so.list_campaigns"] = { method = "GET", url = "https://app.loops.so/api/v1/campaigns", query = {"perPage", "cursor"} },
    ["loops-so.list_components"] = { method = "GET", url = "https://app.loops.so/api/v1/components", query = {"perPage", "cursor"} },
    ["loops-so.list_contact_properties"] = { method = "GET", url = "https://app.loops.so/api/v1/contacts/properties", query = {"list"} },
    ["loops-so.list_dedicated_sending_ips"] = { method = "GET", url = "https://app.loops.so/api/v1/dedicated-sending-ips" },
    ["loops-so.list_event_patterns"] = { method = "GET", url = "https://app.loops.so/api/v1/event-patterns", query = {"perPage", "cursor"} },
    ["loops-so.list_mailing_lists"] = { method = "GET", url = "https://app.loops.so/api/v1/lists" },
    ["loops-so.list_themes"] = { method = "GET", url = "https://app.loops.so/api/v1/themes", query = {"perPage", "cursor"} },
    ["loops-so.list_transactional_emails"] = { method = "GET", url = "https://app.loops.so/api/v1/transactional-emails", query = {"perPage", "cursor"} },
    ["loops-so.list_transactional_groups"] = { method = "GET", url = "https://app.loops.so/api/v1/transactional-groups", query = {"perPage", "cursor"} },
    ["loops-so.list_workflows"] = { method = "GET", url = "https://app.loops.so/api/v1/workflows", query = {"perPage", "cursor"} },
    ["loops-so.preview_email_message"] = { method = "POST", url = "https://app.loops.so/api/v1/email-messages/{emailMessageId}/preview", path = {"emailMessageId"}, body = {"emails", "contactProperties", "eventProperties", "dataVariables"} },
    ["loops-so.publish_transactional_email"] = { method = "POST", url = "https://app.loops.so/api/v1/transactional-emails/{transactionalId}/publish", path = {"transactionalId"} },
    ["loops-so.remove_contact_suppression"] = { method = "DELETE", url = "https://app.loops.so/api/v1/contacts/suppression", query = {"email", "userId"} },
    ["loops-so.reroute_node_connection"] = { method = "POST", url = "https://app.loops.so/api/v1/workflows/{workflowId}/nodes/{nodeId}/reroute", path = {"workflowId", "nodeId"}, body = {"expectedRevisionId", "newTargetNodeId"} },
    ["loops-so.send_event"] = { method = "POST", url = "https://app.loops.so/api/v1/events/send", header = {"Idempotency-Key"}, body = {"email", "userId", "eventName", "eventProperties", "mailingLists"} },
    ["loops-so.send_transactional_email"] = { method = "POST", url = "https://app.loops.so/api/v1/transactional", header = {"Idempotency-Key"}, body = {"email", "transactionalId", "addToAudience", "dataVariables", "attachments"} },
    ["loops-so.test_api_key"] = { method = "GET", url = "https://app.loops.so/api/v1/api-key" },
    ["loops-so.update_campaign"] = { method = "POST", url = "https://app.loops.so/api/v1/campaigns/{campaignId}", path = {"campaignId"}, body = {"name", "campaignGroupId", "mailingListId", "audienceSegmentId", "audienceFilter", "scheduling"} },
    ["loops-so.update_campaign_group"] = { method = "POST", url = "https://app.loops.so/api/v1/campaign-groups/{campaignGroupId}", path = {"campaignGroupId"}, body = {"name", "description"} },
    ["loops-so.update_component"] = { method = "POST", url = "https://app.loops.so/api/v1/components/{componentId}", path = {"componentId"}, body = {"name", "lmx"} },
    ["loops-so.update_contact"] = { method = "PUT", url = "https://app.loops.so/api/v1/contacts/update", body = {"email", "firstName", "lastName", "source", "subscribed", "userGroup", "userId", "mailingLists"} },
    ["loops-so.update_email_message"] = { method = "POST", url = "https://app.loops.so/api/v1/email-messages/{emailMessageId}", path = {"emailMessageId"}, body = {"expectedRevisionId", "subject", "previewText", "fromName", "fromEmail", "replyToEmail", "ccEmail", "bccEmail", "languageCode", "emailFormat", "lmx", "contactPropertiesFallbacks", "eventPropertiesFallbacks", "dataVariablesFallbacks"} },
    ["loops-so.update_theme"] = { method = "POST", url = "https://app.loops.so/api/v1/themes/{themeId}", path = {"themeId"}, body = {"name", "styles"} },
    ["loops-so.update_transactional_email"] = { method = "POST", url = "https://app.loops.so/api/v1/transactional-emails/{transactionalId}", path = {"transactionalId"}, body = {"name", "transactionalGroupId"} },
    ["loops-so.update_transactional_group"] = { method = "POST", url = "https://app.loops.so/api/v1/transactional-groups/{transactionalGroupId}", path = {"transactionalGroupId"}, body = {"name", "description"} },
    ["loops-so.update_workflow_node"] = { method = "POST", url = "https://app.loops.so/api/v1/workflows/{workflowId}/nodes/{nodeId}", path = {"workflowId", "nodeId"}, body = {"expectedRevisionId", "payload"} },
    ["loops-so.update_workflow_properties"] = { method = "POST", url = "https://app.loops.so/api/v1/workflows/{workflowId}", path = {"workflowId"}, body = {"expectedRevisionId", "name", "description"} },
  },
}
