-- AWS IAM — every call this API accepts, as data.
--
-- GENERATED from https://api.apis.guru/v2/specs/amazonaws.com/ce/2017-10-25/openapi.json
-- APIs.guru's mirror, matched on amazonaws.com. A mirror lags the vendor.
-- 37 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "aws-iam",
  name = "AWS IAM",
  base = "https://iam.amazonaws.com",
  docs = "https://nango.dev/docs/api-integrations/aws-iam",
  auth = {
    kind = "basic",
    header = "authorization",
    format = "Bearer {token}",
    env = nil,
    user_env = "AWS_IAM_USER",
    pass_env = "AWS_IAM_PASS",
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["aws-iam.create_anomaly_monitor"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.CreateAnomalyMonitor", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"AnomalyMonitor", "ResourceTags"} },
    ["aws-iam.create_anomaly_subscription"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.CreateAnomalySubscription", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"AnomalySubscription", "ResourceTags"} },
    ["aws-iam.create_cost_category_definition"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.CreateCostCategoryDefinition", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"Name", "EffectiveStart", "RuleVersion", "Rules", "DefaultValue", "SplitChargeRules", "ResourceTags"} },
    ["aws-iam.delete_anomaly_monitor"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.DeleteAnomalyMonitor", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"MonitorArn"} },
    ["aws-iam.delete_anomaly_subscription"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.DeleteAnomalySubscription", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"SubscriptionArn"} },
    ["aws-iam.delete_cost_category_definition"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.DeleteCostCategoryDefinition", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"CostCategoryArn"} },
    ["aws-iam.describe_cost_category_definition"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.DescribeCostCategoryDefinition", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"CostCategoryArn", "EffectiveOn"} },
    ["aws-iam.get_anomalies"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetAnomalies", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"MonitorArn", "DateInterval", "Feedback", "TotalImpact", "NextPageToken", "MaxResults"} },
    ["aws-iam.get_anomaly_monitors"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetAnomalyMonitors", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"MonitorArnList", "NextPageToken", "MaxResults"} },
    ["aws-iam.get_anomaly_subscriptions"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetAnomalySubscriptions", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"SubscriptionArnList", "MonitorArn", "NextPageToken", "MaxResults"} },
    ["aws-iam.get_cost_and_usage"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetCostAndUsage", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "Granularity", "Filter", "Metrics", "GroupBy", "NextPageToken"} },
    ["aws-iam.get_cost_and_usage_with_resources"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetCostAndUsageWithResources", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "Granularity", "Filter", "Metrics", "GroupBy", "NextPageToken"} },
    ["aws-iam.get_cost_categories"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetCostCategories", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"SearchString", "TimePeriod", "CostCategoryName", "Filter", "SortBy", "MaxResults", "NextPageToken"} },
    ["aws-iam.get_cost_forecast"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetCostForecast", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "Metric", "Granularity", "Filter", "PredictionIntervalLevel"} },
    ["aws-iam.get_dimension_values"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetDimensionValues", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"SearchString", "TimePeriod", "Dimension", "Context", "Filter", "SortBy", "MaxResults", "NextPageToken"} },
    ["aws-iam.get_reservation_coverage"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetReservationCoverage", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "GroupBy", "Granularity", "Filter", "Metrics", "NextPageToken", "SortBy", "MaxResults"} },
    ["aws-iam.get_reservation_purchase_recommendation"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetReservationPurchaseRecommendation", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"AccountId", "Service", "Filter", "AccountScope", "LookbackPeriodInDays", "TermInYears", "PaymentOption", "ServiceSpecification", "PageSize", "NextPageToken"} },
    ["aws-iam.get_reservation_utilization"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetReservationUtilization", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "GroupBy", "Granularity", "Filter", "SortBy", "NextPageToken", "MaxResults"} },
    ["aws-iam.get_rightsizing_recommendation"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetRightsizingRecommendation", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"Filter", "Configuration", "Service", "PageSize", "NextPageToken"} },
    ["aws-iam.get_savings_plans_coverage"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetSavingsPlansCoverage", query = {"MaxResults", "NextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "GroupBy", "Granularity", "Filter", "Metrics", "NextToken", "MaxResults", "SortBy"} },
    ["aws-iam.get_savings_plans_purchase_recommendation"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetSavingsPlansPurchaseRecommendation", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"SavingsPlansType", "TermInYears", "PaymentOption", "AccountScope", "NextPageToken", "PageSize", "LookbackPeriodInDays", "Filter"} },
    ["aws-iam.get_savings_plans_utilization"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetSavingsPlansUtilization", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "Granularity", "Filter", "SortBy"} },
    ["aws-iam.get_savings_plans_utilization_details"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetSavingsPlansUtilizationDetails", query = {"MaxResults", "NextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "Filter", "DataType", "NextToken", "MaxResults", "SortBy"} },
    ["aws-iam.get_tags"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetTags", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"SearchString", "TimePeriod", "TagKey", "Filter", "SortBy", "MaxResults", "NextPageToken"} },
    ["aws-iam.get_usage_forecast"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.GetUsageForecast", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"TimePeriod", "Metric", "Granularity", "Filter", "PredictionIntervalLevel"} },
    ["aws-iam.list_cost_allocation_tags"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.ListCostAllocationTags", query = {"MaxResults", "NextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"Status", "TagKeys", "Type", "NextToken", "MaxResults"} },
    ["aws-iam.list_cost_category_definitions"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.ListCostCategoryDefinitions", query = {"MaxResults", "NextToken"}, header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"EffectiveOn", "NextToken", "MaxResults"} },
    ["aws-iam.list_savings_plans_purchase_recommendation_generation"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.ListSavingsPlansPurchaseRecommendationGeneration", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"GenerationStatus", "RecommendationIds", "PageSize", "NextPageToken"} },
    ["aws-iam.list_tags_for_resource"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.ListTagsForResource", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"ResourceArn"} },
    ["aws-iam.provide_anomaly_feedback"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.ProvideAnomalyFeedback", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"AnomalyId", "Feedback"} },
    ["aws-iam.start_savings_plans_purchase_recommendation_generation"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.StartSavingsPlansPurchaseRecommendationGeneration", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"} },
    ["aws-iam.tag_resource"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.TagResource", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"ResourceArn", "ResourceTags"} },
    ["aws-iam.untag_resource"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.UntagResource", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"ResourceArn", "ResourceTagKeys"} },
    ["aws-iam.update_anomaly_monitor"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.UpdateAnomalyMonitor", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"MonitorArn", "MonitorName"} },
    ["aws-iam.update_anomaly_subscription"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.UpdateAnomalySubscription", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"SubscriptionArn", "Threshold", "Frequency", "MonitorArnList", "Subscribers", "SubscriptionName", "ThresholdExpression"} },
    ["aws-iam.update_cost_allocation_tags_status"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.UpdateCostAllocationTagsStatus", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"CostAllocationTagsStatus"} },
    ["aws-iam.update_cost_category_definition"] = { method = "POST", url = "https://iam.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.UpdateCostCategoryDefinition", header = {"X-Amz-Content-Sha256", "X-Amz-Date", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Security-Token", "X-Amz-Signature", "X-Amz-SignedHeaders", "X-Amz-Target"}, body = {"CostCategoryArn", "EffectiveStart", "RuleVersion", "Rules", "DefaultValue", "SplitChargeRules"} },
  },
}
