-- OpenAI — every call this API accepts, as data.
--
-- GENERATED from https://raw.githubusercontent.com/openai/openai-openapi/main/openapi.json
-- Published by openai, the vendor's own GitHub organisation.
-- 337 operations · do not edit
--
-- The credential is never in here. `auth.env` names an environment variable; the value
-- stays in the environment, which is what makes this file safe to publish.
return {
  provider = "openai-admin",
  name = "OpenAI",
  base = "https://api.openai.com",
  docs = "https://nango.dev/docs/integrations/all/openai-admin",
  auth = {
    kind = "key",
    header = "authorization",
    format = "Bearer {token}",
    env = "OPENAI_ADMIN_API_KEY",
    user_env = nil,
    pass_env = nil,
    param = nil,
  },
  config = {},
  headers = {},
  operations = {
    ["openai-admin.accept_live_session"] = { method = "POST", url = "https://api.openai.com/v1/live/sessions/{session_id}/accept", path = {"session_id"}, body = {"session"} },
    ["openai-admin.accept_realtime_call"] = { method = "POST", url = "https://api.openai.com/v1/realtime/calls/{call_id}/accept", path = {"call_id"}, body = {"type", "output_modalities", "model", "instructions", "audio", "include", "tracing", "tools", "tool_choice", "parallel_tool_calls", "reasoning", "max_output_tokens", "truncation", "prompt"} },
    ["openai-admin.activate_organization_certificates"] = { method = "POST", url = "https://api.openai.com/v1/organization/certificates/activate", body = {"certificate_ids"} },
    ["openai-admin.activate_project_certificates"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/certificates/activate", path = {"project_id"}, body = {"certificate_ids"} },
    ["openai-admin.add_group_user"] = { method = "POST", url = "https://api.openai.com/v1/organization/groups/{group_id}/users", path = {"group_id"}, body = {"user_id"} },
    ["openai-admin.add_project_group"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/groups", path = {"project_id"}, body = {"group_id", "role"} },
    ["openai-admin.add_upload_part"] = { method = "POST", url = "https://api.openai.com/v1/uploads/{upload_id}/parts", path = {"upload_id"}, body = {"data"} },
    ["openai-admin.admin_api_keys_create"] = { method = "POST", url = "https://api.openai.com/v1/organization/admin_api_keys", body = {"name", "expires_in_seconds"} },
    ["openai-admin.admin_api_keys_delete"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/admin_api_keys/{key_id}", path = {"key_id"} },
    ["openai-admin.admin_api_keys_get"] = { method = "GET", url = "https://api.openai.com/v1/organization/admin_api_keys/{key_id}", path = {"key_id"} },
    ["openai-admin.admin_api_keys_list"] = { method = "GET", url = "https://api.openai.com/v1/organization/admin_api_keys", query = {"after", "order", "limit"} },
    ["openai-admin.archive_project"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/archive", path = {"project_id"} },
    ["openai-admin.assign_group_role"] = { method = "POST", url = "https://api.openai.com/v1/organization/groups/{group_id}/roles", path = {"group_id"}, body = {"role_id"} },
    ["openai-admin.assign_project_group_role"] = { method = "POST", url = "https://api.openai.com/v1/projects/{project_id}/groups/{group_id}/roles", path = {"project_id", "group_id"}, body = {"role_id"} },
    ["openai-admin.assign_project_user_role"] = { method = "POST", url = "https://api.openai.com/v1/projects/{project_id}/users/{user_id}/roles", path = {"project_id", "user_id"}, body = {"role_id"} },
    ["openai-admin.assign_user_role"] = { method = "POST", url = "https://api.openai.com/v1/organization/users/{user_id}/roles", path = {"user_id"}, body = {"role_id"} },
    ["openai-admin.beta_cancel_response"] = { method = "POST", url = "https://api.openai.com/v1/responses/{response_id}/cancel?beta=true", path = {"response_id"}, header = {"openai-beta"} },
    ["openai-admin.beta_compactconversation"] = { method = "POST", url = "https://api.openai.com/v1/responses/compact?beta=true", header = {"openai-beta"}, body = {"model", "input", "previous_response_id", "instructions", "prompt_cache_key", "prompt_cache_retention", "prompt_cache_options", "service_tier"} },
    ["openai-admin.beta_create_response"] = { method = "POST", url = "https://api.openai.com/v1/responses?beta=true", header = {"openai-beta"} },
    ["openai-admin.beta_delete_response"] = { method = "DELETE", url = "https://api.openai.com/v1/responses/{response_id}?beta=true", path = {"response_id"}, header = {"openai-beta"} },
    ["openai-admin.beta_get_response"] = { method = "GET", url = "https://api.openai.com/v1/responses/{response_id}?beta=true", path = {"response_id"}, query = {"include", "stream", "starting_after", "include_obfuscation"}, header = {"openai-beta"} },
    ["openai-admin.beta_getinputtokencounts"] = { method = "POST", url = "https://api.openai.com/v1/responses/input_tokens?beta=true", header = {"openai-beta"}, body = {"model", "input", "previous_response_id", "tools", "text", "reasoning", "truncation", "instructions", "personality", "conversation", "tool_choice", "parallel_tool_calls"} },
    ["openai-admin.beta_list_input_items"] = { method = "GET", url = "https://api.openai.com/v1/responses/{response_id}/input_items?beta=true", path = {"response_id"}, query = {"limit", "order", "after", "include"}, header = {"openai-beta"} },
    ["openai-admin.cancel_batch"] = { method = "POST", url = "https://api.openai.com/v1/batches/{batch_id}/cancel", path = {"batch_id"} },
    ["openai-admin.cancel_chat_session_method"] = { method = "POST", url = "https://api.openai.com/v1/chatkit/sessions/{session_id}/cancel", path = {"session_id"} },
    ["openai-admin.cancel_eval_run"] = { method = "POST", url = "https://api.openai.com/v1/evals/{eval_id}/runs/{run_id}", path = {"eval_id", "run_id"} },
    ["openai-admin.cancel_fine_tuning_job"] = { method = "POST", url = "https://api.openai.com/v1/fine_tuning/jobs/{fine_tuning_job_id}/cancel", path = {"fine_tuning_job_id"} },
    ["openai-admin.cancel_response"] = { method = "POST", url = "https://api.openai.com/v1/responses/{response_id}/cancel", path = {"response_id"} },
    ["openai-admin.cancel_run"] = { method = "POST", url = "https://api.openai.com/v1/threads/{thread_id}/runs/{run_id}/cancel", path = {"thread_id", "run_id"} },
    ["openai-admin.cancel_upload"] = { method = "POST", url = "https://api.openai.com/v1/uploads/{upload_id}/cancel", path = {"upload_id"} },
    ["openai-admin.cancel_vector_store_file_batch"] = { method = "POST", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/cancel", path = {"vector_store_id", "batch_id"} },
    ["openai-admin.compactconversation"] = { method = "POST", url = "https://api.openai.com/v1/responses/compact", body = {"model", "input", "previous_response_id", "instructions", "prompt_cache_key", "prompt_cache_retention", "prompt_cache_options", "service_tier"} },
    ["openai-admin.complete_upload"] = { method = "POST", url = "https://api.openai.com/v1/uploads/{upload_id}/complete", path = {"upload_id"}, body = {"part_ids", "md5"} },
    ["openai-admin.create_agent"] = { method = "POST", url = "https://api.openai.com/v1/agents", body = {"metadata", "name", "model", "reasoning", "text", "service_tier", "instructions", "tools", "multi_agent"} },
    ["openai-admin.create_agent_environment_file"] = { method = "POST", url = "https://api.openai.com/v1/agents/environments/{environment_id}/files", path = {"environment_id"} },
    ["openai-admin.create_agent_environment_template"] = { method = "POST", url = "https://api.openai.com/v1/agents/environments/templates", body = {"packages", "setup_commands", "network", "env", "capability_directories", "skills", "plugins", "files", "name"} },
    ["openai-admin.create_agent_session"] = { method = "POST", url = "https://api.openai.com/v1/agents/sessions", body = {"metadata", "agent", "agent_id", "environment", "vault_ids", "input", "stream"} },
    ["openai-admin.create_agent_session_events"] = { method = "POST", url = "https://api.openai.com/v1/agents/sessions/{session_id}/events", path = {"session_id"}, header = {"Idempotency-Key"}, body = {"events"} },
    ["openai-admin.create_batch"] = { method = "POST", url = "https://api.openai.com/v1/batches", body = {"input_file_id", "endpoint", "completion_window", "metadata", "output_expires_after"} },
    ["openai-admin.create_chat_completion"] = { method = "POST", url = "https://api.openai.com/v1/chat/completions" },
    ["openai-admin.create_chat_session_method"] = { method = "POST", url = "https://api.openai.com/v1/chatkit/sessions", body = {"workflow", "user", "expires_after", "rate_limits", "chatkit_configuration"} },
    ["openai-admin.create_completion"] = { method = "POST", url = "https://api.openai.com/v1/completions", body = {"model", "prompt", "best_of", "echo", "frequency_penalty", "logit_bias", "logprobs", "max_tokens", "n", "presence_penalty", "seed", "stop", "stream", "stream_options", "suffix", "temperature", "top_p", "user"} },
    ["openai-admin.create_container"] = { method = "POST", url = "https://api.openai.com/v1/containers", body = {"name", "file_ids", "expires_after", "skills", "memory_limit", "network_policy"} },
    ["openai-admin.create_container_file"] = { method = "POST", url = "https://api.openai.com/v1/containers/{container_id}/files", path = {"container_id"}, body = {"file_id", "file"} },
    ["openai-admin.create_conversation"] = { method = "POST", url = "https://api.openai.com/v1/conversations", body = {"metadata", "items"} },
    ["openai-admin.create_conversation_items"] = { method = "POST", url = "https://api.openai.com/v1/conversations/{conversation_id}/items", path = {"conversation_id"}, query = {"include"}, body = {"items"} },
    ["openai-admin.create_embedding"] = { method = "POST", url = "https://api.openai.com/v1/embeddings", body = {"input", "model", "encoding_format", "dimensions", "user"} },
    ["openai-admin.create_eval"] = { method = "POST", url = "https://api.openai.com/v1/evals", body = {"name", "metadata", "data_source_config", "testing_criteria"} },
    ["openai-admin.create_eval_run"] = { method = "POST", url = "https://api.openai.com/v1/evals/{eval_id}/runs", path = {"eval_id"}, body = {"name", "metadata", "data_source"} },
    ["openai-admin.create_file"] = { method = "POST", url = "https://api.openai.com/v1/files", body = {"file", "purpose", "expires_after"} },
    ["openai-admin.create_fine_tuning_checkpoint_permission"] = { method = "POST", url = "https://api.openai.com/v1/fine_tuning/checkpoints/{fine_tuned_model_checkpoint}/permissions", path = {"fine_tuned_model_checkpoint"}, body = {"project_ids"} },
    ["openai-admin.create_fine_tuning_job"] = { method = "POST", url = "https://api.openai.com/v1/fine_tuning/jobs", body = {"model", "training_file", "hyperparameters", "suffix", "validation_file", "integrations", "seed", "method", "metadata"} },
    ["openai-admin.create_group"] = { method = "POST", url = "https://api.openai.com/v1/organization/groups", body = {"name"} },
    ["openai-admin.create_image"] = { method = "POST", url = "https://api.openai.com/v1/images/generations", body = {"prompt", "model", "n", "quality", "response_format", "output_format", "output_compression", "stream", "partial_images", "size", "moderation", "background", "style", "user"} },
    ["openai-admin.create_image_edit"] = { method = "POST", url = "https://api.openai.com/v1/images/edits", body = {"model", "images", "mask", "prompt", "n", "quality", "input_fidelity", "size", "user", "output_format", "output_compression", "moderation", "background", "stream", "partial_images"} },
    ["openai-admin.create_image_variation"] = { method = "POST", url = "https://api.openai.com/v1/images/variations", body = {"image", "model", "n", "response_format", "size", "user"} },
    ["openai-admin.create_live"] = { method = "POST", url = "https://api.openai.com/v1/live/sessions", body = {"session", "transport"} },
    ["openai-admin.create_message"] = { method = "POST", url = "https://api.openai.com/v1/threads/{thread_id}/messages", path = {"thread_id"}, body = {"role", "content", "attachments", "metadata"} },
    ["openai-admin.create_moderation"] = { method = "POST", url = "https://api.openai.com/v1/moderations", body = {"input", "model"} },
    ["openai-admin.create_organization_spend_alert"] = { method = "POST", url = "https://api.openai.com/v1/organization/spend_alerts", body = {"threshold_amount", "currency", "interval", "notification_channel"} },
    ["openai-admin.create_project"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects", body = {"name", "geography", "residency", "external_key_id"} },
    ["openai-admin.create_project_role"] = { method = "POST", url = "https://api.openai.com/v1/projects/{project_id}/roles", path = {"project_id"}, body = {"role_name", "permissions", "description"} },
    ["openai-admin.create_project_service_account"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/service_accounts", path = {"project_id"}, body = {"name", "create_service_account_only", "expires_in_seconds"} },
    ["openai-admin.create_project_spend_alert"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/spend_alerts", path = {"project_id"}, body = {"threshold_amount", "currency", "interval", "notification_channel"} },
    ["openai-admin.create_project_user"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/users", path = {"project_id"}, body = {"user_id", "email", "role"} },
    ["openai-admin.create_realtime_call"] = { method = "POST", url = "https://api.openai.com/v1/realtime/calls", body = {"sdp", "session"} },
    ["openai-admin.create_realtime_client_secret"] = { method = "POST", url = "https://api.openai.com/v1/realtime/client_secrets", body = {"expires_after", "session"} },
    ["openai-admin.create_realtime_session"] = { method = "POST", url = "https://api.openai.com/v1/realtime/sessions", body = {"client_secret", "modalities", "instructions", "voice", "input_audio_format", "output_audio_format", "input_audio_transcription", "speed", "tracing", "turn_detection", "tools", "tool_choice", "temperature", "max_response_output_tokens", "truncation", "prompt"} },
    ["openai-admin.create_realtime_transcription_session"] = { method = "POST", url = "https://api.openai.com/v1/realtime/transcription_sessions", body = {"turn_detection", "input_audio_noise_reduction", "input_audio_format", "input_audio_transcription", "include"} },
    ["openai-admin.create_realtime_translation_client_secret"] = { method = "POST", url = "https://api.openai.com/v1/realtime/translations/client_secrets", body = {"expires_after", "session"} },
    ["openai-admin.create_response"] = { method = "POST", url = "https://api.openai.com/v1/responses" },
    ["openai-admin.create_role"] = { method = "POST", url = "https://api.openai.com/v1/organization/roles", body = {"role_name", "permissions", "description"} },
    ["openai-admin.create_run"] = { method = "POST", url = "https://api.openai.com/v1/threads/{thread_id}/runs", path = {"thread_id"}, query = {"include[]"}, body = {"assistant_id", "model", "reasoning_effort", "instructions", "additional_instructions", "additional_messages", "tools", "metadata", "temperature", "top_p", "stream", "max_prompt_tokens", "max_completion_tokens", "truncation_strategy", "tool_choice", "parallel_tool_calls", "response_format"} },
    ["openai-admin.create_skill"] = { method = "POST", url = "https://api.openai.com/v1/skills", body = {"files"} },
    ["openai-admin.create_skill_version"] = { method = "POST", url = "https://api.openai.com/v1/skills/{skill_id}/versions", path = {"skill_id"}, body = {"files", "default"} },
    ["openai-admin.create_speech"] = { method = "POST", url = "https://api.openai.com/v1/audio/speech", body = {"model", "input", "instructions", "voice", "response_format", "speed", "stream_format"} },
    ["openai-admin.create_thread"] = { method = "POST", url = "https://api.openai.com/v1/threads", body = {"messages", "tool_resources", "metadata"} },
    ["openai-admin.create_thread_and_run"] = { method = "POST", url = "https://api.openai.com/v1/threads/runs", body = {"assistant_id", "thread", "model", "instructions", "tools", "tool_resources", "metadata", "temperature", "top_p", "stream", "max_prompt_tokens", "max_completion_tokens", "truncation_strategy", "tool_choice", "parallel_tool_calls", "response_format"} },
    ["openai-admin.create_transcription"] = { method = "POST", url = "https://api.openai.com/v1/audio/transcriptions", body = {"file", "model", "language", "languages", "keywords", "prompt", "response_format", "temperature", "include", "timestamp_granularities", "stream", "chunking_strategy", "known_speaker_names", "known_speaker_references"} },
    ["openai-admin.create_translation"] = { method = "POST", url = "https://api.openai.com/v1/audio/translations", body = {"file", "model", "prompt", "response_format", "temperature"} },
    ["openai-admin.create_upload"] = { method = "POST", url = "https://api.openai.com/v1/uploads", body = {"filename", "purpose", "bytes", "mime_type", "expires_after"} },
    ["openai-admin.create_vault"] = { method = "POST", url = "https://api.openai.com/v1/vaults", body = {"name", "metadata"} },
    ["openai-admin.create_vault_credential"] = { method = "POST", url = "https://api.openai.com/v1/vaults/{vault_id}/credentials", path = {"vault_id"}, body = {"name"} },
    ["openai-admin.create_vector_store"] = { method = "POST", url = "https://api.openai.com/v1/vector_stores", body = {"file_ids", "name", "description", "expires_after", "chunking_strategy", "metadata"} },
    ["openai-admin.create_vector_store_file"] = { method = "POST", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/files", path = {"vector_store_id"}, body = {"file_id", "chunking_strategy", "attributes"} },
    ["openai-admin.create_vector_store_file_batch"] = { method = "POST", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/file_batches", path = {"vector_store_id"}, body = {"file_ids", "files", "chunking_strategy", "attributes"} },
    ["openai-admin.create_voice"] = { method = "POST", url = "https://api.openai.com/v1/audio/voices", body = {"name", "audio_sample", "consent"} },
    ["openai-admin.create_voice_consent"] = { method = "POST", url = "https://api.openai.com/v1/audio/voice_consents", body = {"name", "recording", "language"} },
    ["openai-admin.create_webhook_endpoint"] = { method = "POST", url = "https://api.openai.com/v1/webhook_endpoints", body = {"name", "url", "event_types"} },
    ["openai-admin.createan_apikeyforaserviceaccount"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/service_accounts/{service_account_id}/api_keys", path = {"project_id", "service_account_id"}, body = {"name", "scopes", "expires_in_seconds"} },
    ["openai-admin.createanexternalstorageconfiguration"] = { method = "POST", url = "https://api.openai.com/v1/organization/external_storage", body = {"project_id", "provider"} },
    ["openai-admin.createcontentprovenancecheck"] = { method = "POST", url = "https://api.openai.com/v1/content_provenance_checks", body = {"file"} },
    ["openai-admin.deactivate_organization_certificates"] = { method = "POST", url = "https://api.openai.com/v1/organization/certificates/deactivate", body = {"certificate_ids"} },
    ["openai-admin.deactivate_project_certificates"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/certificates/deactivate", path = {"project_id"}, body = {"certificate_ids"} },
    ["openai-admin.delete_agent"] = { method = "DELETE", url = "https://api.openai.com/v1/agents/{agent_id}", path = {"agent_id"} },
    ["openai-admin.delete_agent_environment_template"] = { method = "DELETE", url = "https://api.openai.com/v1/agents/environments/templates/{environment_template_id}", path = {"environment_template_id"} },
    ["openai-admin.delete_agent_session"] = { method = "DELETE", url = "https://api.openai.com/v1/agents/sessions/{session_id}", path = {"session_id"} },
    ["openai-admin.delete_agent_session_artifact"] = { method = "DELETE", url = "https://api.openai.com/v1/agents/sessions/{session_id}/artifacts/{artifact_id}", path = {"session_id", "artifact_id"} },
    ["openai-admin.delete_certificate"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/certificates/{certificate_id}", path = {"certificate_id"} },
    ["openai-admin.delete_chat_completion"] = { method = "DELETE", url = "https://api.openai.com/v1/chat/completions/{completion_id}", path = {"completion_id"} },
    ["openai-admin.delete_container"] = { method = "DELETE", url = "https://api.openai.com/v1/containers/{container_id}", path = {"container_id"} },
    ["openai-admin.delete_container_file"] = { method = "DELETE", url = "https://api.openai.com/v1/containers/{container_id}/files/{file_id}", path = {"container_id", "file_id"} },
    ["openai-admin.delete_conversation"] = { method = "DELETE", url = "https://api.openai.com/v1/conversations/{conversation_id}", path = {"conversation_id"} },
    ["openai-admin.delete_conversation_item"] = { method = "DELETE", url = "https://api.openai.com/v1/conversations/{conversation_id}/items/{item_id}", path = {"conversation_id", "item_id"} },
    ["openai-admin.delete_eval"] = { method = "DELETE", url = "https://api.openai.com/v1/evals/{eval_id}", path = {"eval_id"} },
    ["openai-admin.delete_eval_run"] = { method = "DELETE", url = "https://api.openai.com/v1/evals/{eval_id}/runs/{run_id}", path = {"eval_id", "run_id"} },
    ["openai-admin.delete_file"] = { method = "DELETE", url = "https://api.openai.com/v1/files/{file_id}", path = {"file_id"} },
    ["openai-admin.delete_fine_tuning_checkpoint_permission"] = { method = "DELETE", url = "https://api.openai.com/v1/fine_tuning/checkpoints/{fine_tuned_model_checkpoint}/permissions/{permission_id}", path = {"fine_tuned_model_checkpoint", "permission_id"} },
    ["openai-admin.delete_group"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/groups/{group_id}", path = {"group_id"} },
    ["openai-admin.delete_invite"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/invites/{invite_id}", path = {"invite_id"} },
    ["openai-admin.delete_message"] = { method = "DELETE", url = "https://api.openai.com/v1/threads/{thread_id}/messages/{message_id}", path = {"thread_id", "message_id"} },
    ["openai-admin.delete_model"] = { method = "DELETE", url = "https://api.openai.com/v1/models/{model}", path = {"model"} },
    ["openai-admin.delete_organization_spend_alert"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/spend_alerts/{alert_id}", path = {"alert_id"} },
    ["openai-admin.delete_project_api_key"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/projects/{project_id}/api_keys/{api_key_id}", path = {"project_id", "api_key_id"} },
    ["openai-admin.delete_project_model_permissions"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/projects/{project_id}/model_permissions", path = {"project_id"} },
    ["openai-admin.delete_project_role"] = { method = "DELETE", url = "https://api.openai.com/v1/projects/{project_id}/roles/{role_id}", path = {"project_id", "role_id"} },
    ["openai-admin.delete_project_service_account"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/projects/{project_id}/service_accounts/{service_account_id}", path = {"project_id", "service_account_id"} },
    ["openai-admin.delete_project_spend_alert"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/projects/{project_id}/spend_alerts/{alert_id}", path = {"project_id", "alert_id"} },
    ["openai-admin.delete_project_user"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/projects/{project_id}/users/{user_id}", path = {"project_id", "user_id"} },
    ["openai-admin.delete_response"] = { method = "DELETE", url = "https://api.openai.com/v1/responses/{response_id}", path = {"response_id"} },
    ["openai-admin.delete_role"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/roles/{role_id}", path = {"role_id"} },
    ["openai-admin.delete_skill"] = { method = "DELETE", url = "https://api.openai.com/v1/skills/{skill_id}", path = {"skill_id"} },
    ["openai-admin.delete_skill_version"] = { method = "DELETE", url = "https://api.openai.com/v1/skills/{skill_id}/versions/{version}", path = {"skill_id", "version"} },
    ["openai-admin.delete_thread"] = { method = "DELETE", url = "https://api.openai.com/v1/threads/{thread_id}", path = {"thread_id"} },
    ["openai-admin.delete_thread_method"] = { method = "DELETE", url = "https://api.openai.com/v1/chatkit/threads/{thread_id}", path = {"thread_id"} },
    ["openai-admin.delete_user"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/users/{user_id}", path = {"user_id"} },
    ["openai-admin.delete_vault"] = { method = "DELETE", url = "https://api.openai.com/v1/vaults/{vault_id}", path = {"vault_id"} },
    ["openai-admin.delete_vault_credential"] = { method = "DELETE", url = "https://api.openai.com/v1/vaults/{vault_id}/credentials/{credential_id}", path = {"vault_id", "credential_id"} },
    ["openai-admin.delete_vector_store"] = { method = "DELETE", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}", path = {"vector_store_id"} },
    ["openai-admin.delete_vector_store_file"] = { method = "DELETE", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/files/{file_id}", path = {"vector_store_id", "file_id"} },
    ["openai-admin.delete_voice_consent"] = { method = "DELETE", url = "https://api.openai.com/v1/audio/voice_consents/{consent_id}", path = {"consent_id"} },
    ["openai-admin.delete_webhook_endpoint"] = { method = "DELETE", url = "https://api.openai.com/v1/webhook_endpoints/{webhook_endpoint_id}", path = {"webhook_endpoint_id"} },
    ["openai-admin.deleteanexternalstorageconfiguration"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/external_storage/{external_storage_id}", path = {"external_storage_id"} },
    ["openai-admin.deleteorganizationspendlimit"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/spend_limit" },
    ["openai-admin.deleteprojectspendlimit"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/projects/{project_id}/spend_limit", path = {"project_id"} },
    ["openai-admin.download_file"] = { method = "GET", url = "https://api.openai.com/v1/files/{file_id}/content", path = {"file_id"} },
    ["openai-admin.download_live_recording"] = { method = "GET", url = "https://api.openai.com/v1/live/sessions/{session_id}/content", path = {"session_id"} },
    ["openai-admin.fork_live_session"] = { method = "POST", url = "https://api.openai.com/v1/live/sessions/{session_id}/fork", path = {"session_id"}, body = {"session", "transport"} },
    ["openai-admin.get_certificate"] = { method = "GET", url = "https://api.openai.com/v1/organization/certificates/{certificate_id}", path = {"certificate_id"}, query = {"include"} },
    ["openai-admin.get_chat_completion"] = { method = "GET", url = "https://api.openai.com/v1/chat/completions/{completion_id}", path = {"completion_id"} },
    ["openai-admin.get_chat_completion_messages"] = { method = "GET", url = "https://api.openai.com/v1/chat/completions/{completion_id}/messages", path = {"completion_id"}, query = {"after", "limit", "order"} },
    ["openai-admin.get_conversation"] = { method = "GET", url = "https://api.openai.com/v1/conversations/{conversation_id}", path = {"conversation_id"} },
    ["openai-admin.get_conversation_item"] = { method = "GET", url = "https://api.openai.com/v1/conversations/{conversation_id}/items/{item_id}", path = {"conversation_id", "item_id"}, query = {"include"} },
    ["openai-admin.get_eval"] = { method = "GET", url = "https://api.openai.com/v1/evals/{eval_id}", path = {"eval_id"} },
    ["openai-admin.get_eval_run"] = { method = "GET", url = "https://api.openai.com/v1/evals/{eval_id}/runs/{run_id}", path = {"eval_id", "run_id"} },
    ["openai-admin.get_eval_run_output_item"] = { method = "GET", url = "https://api.openai.com/v1/evals/{eval_id}/runs/{run_id}/output_items/{output_item_id}", path = {"eval_id", "run_id", "output_item_id"} },
    ["openai-admin.get_eval_run_output_items"] = { method = "GET", url = "https://api.openai.com/v1/evals/{eval_id}/runs/{run_id}/output_items", path = {"eval_id", "run_id"}, query = {"after", "limit", "status", "order"} },
    ["openai-admin.get_eval_runs"] = { method = "GET", url = "https://api.openai.com/v1/evals/{eval_id}/runs", path = {"eval_id"}, query = {"after", "limit", "order", "status"} },
    ["openai-admin.get_message"] = { method = "GET", url = "https://api.openai.com/v1/threads/{thread_id}/messages/{message_id}", path = {"thread_id", "message_id"} },
    ["openai-admin.get_response"] = { method = "GET", url = "https://api.openai.com/v1/responses/{response_id}", path = {"response_id"}, query = {"include", "stream", "starting_after", "include_obfuscation"} },
    ["openai-admin.get_run"] = { method = "GET", url = "https://api.openai.com/v1/threads/{thread_id}/runs/{run_id}", path = {"thread_id", "run_id"} },
    ["openai-admin.get_run_step"] = { method = "GET", url = "https://api.openai.com/v1/threads/{thread_id}/runs/{run_id}/steps/{step_id}", path = {"thread_id", "run_id", "step_id"}, query = {"include[]"} },
    ["openai-admin.get_skill"] = { method = "GET", url = "https://api.openai.com/v1/skills/{skill_id}", path = {"skill_id"} },
    ["openai-admin.get_skill_content"] = { method = "GET", url = "https://api.openai.com/v1/skills/{skill_id}/content", path = {"skill_id"} },
    ["openai-admin.get_skill_version"] = { method = "GET", url = "https://api.openai.com/v1/skills/{skill_id}/versions/{version}", path = {"skill_id", "version"} },
    ["openai-admin.get_skill_version_content"] = { method = "GET", url = "https://api.openai.com/v1/skills/{skill_id}/versions/{version}/content", path = {"skill_id", "version"} },
    ["openai-admin.get_thread"] = { method = "GET", url = "https://api.openai.com/v1/threads/{thread_id}", path = {"thread_id"} },
    ["openai-admin.get_thread_method"] = { method = "GET", url = "https://api.openai.com/v1/chatkit/threads/{thread_id}", path = {"thread_id"} },
    ["openai-admin.get_vector_store"] = { method = "GET", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}", path = {"vector_store_id"} },
    ["openai-admin.get_vector_store_file"] = { method = "GET", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/files/{file_id}", path = {"vector_store_id", "file_id"} },
    ["openai-admin.get_vector_store_file_batch"] = { method = "GET", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}", path = {"vector_store_id", "batch_id"} },
    ["openai-admin.get_voice_consent"] = { method = "GET", url = "https://api.openai.com/v1/audio/voice_consents/{consent_id}", path = {"consent_id"} },
    ["openai-admin.getanexternalstorageconfiguration"] = { method = "GET", url = "https://api.openai.com/v1/organization/external_storage/{external_storage_id}", path = {"external_storage_id"} },
    ["openai-admin.getinputtokencounts"] = { method = "POST", url = "https://api.openai.com/v1/responses/input_tokens", body = {"model", "input", "previous_response_id", "tools", "text", "reasoning", "truncation", "instructions", "personality", "conversation", "tool_choice", "parallel_tool_calls"} },
    ["openai-admin.getorganizationspendlimit"] = { method = "GET", url = "https://api.openai.com/v1/organization/spend_limit" },
    ["openai-admin.getprojectsafetyalert"] = { method = "GET", url = "https://api.openai.com/v1/safety/alerts/{id}", path = {"id"} },
    ["openai-admin.getprojectspendlimit"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/spend_limit", path = {"project_id"} },
    ["openai-admin.getsafetycase"] = { method = "GET", url = "https://api.openai.com/v1/safety/cases/{id}", path = {"id"} },
    ["openai-admin.hangup_live_session"] = { method = "POST", url = "https://api.openai.com/v1/live/sessions/{session_id}/hangup", path = {"session_id"} },
    ["openai-admin.hangup_realtime_call"] = { method = "POST", url = "https://api.openai.com/v1/realtime/calls/{call_id}/hangup", path = {"call_id"} },
    ["openai-admin.invite_user"] = { method = "POST", url = "https://api.openai.com/v1/organization/invites", body = {"email", "role", "projects"} },
    ["openai-admin.list_agent_environment_files"] = { method = "GET", url = "https://api.openai.com/v1/agents/environments/{environment_id}/files", path = {"environment_id"}, query = {"path", "limit", "order", "page"} },
    ["openai-admin.list_agent_environment_templates"] = { method = "GET", url = "https://api.openai.com/v1/agents/environments/templates", query = {"limit", "order", "after"} },
    ["openai-admin.list_agent_session_artifacts"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/artifacts", path = {"session_id"}, query = {"order", "environment_id", "limit", "after"} },
    ["openai-admin.list_agent_session_events"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/events", path = {"session_id"} },
    ["openai-admin.list_agent_session_items"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/items", path = {"session_id"}, query = {"limit", "order", "after"} },
    ["openai-admin.list_agent_session_subagent_items"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/subagents/{subagent_id}/items", path = {"session_id", "subagent_id"}, query = {"limit", "order", "after"} },
    ["openai-admin.list_agent_session_subagent_turn_items"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/subagents/{subagent_id}/turns/{turn_id}/items", path = {"session_id", "subagent_id", "turn_id"}, query = {"limit", "order", "after"} },
    ["openai-admin.list_agent_session_subagent_turns"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/subagents/{subagent_id}/turns", path = {"session_id", "subagent_id"}, query = {"limit", "order", "after"} },
    ["openai-admin.list_agent_session_subagents"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/subagents", path = {"session_id"}, query = {"limit", "order", "after"} },
    ["openai-admin.list_agent_session_turns"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/turns", path = {"session_id"}, query = {"limit", "order", "after"} },
    ["openai-admin.list_agent_sessions"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions", query = {"limit", "order", "agent_id", "after"} },
    ["openai-admin.list_agents"] = { method = "GET", url = "https://api.openai.com/v1/agents", query = {"limit", "order", "after"} },
    ["openai-admin.list_audit_logs"] = { method = "GET", url = "https://api.openai.com/v1/organization/audit_logs", query = {"effective_at", "project_ids[]", "event_types[]", "actor_ids[]", "actor_emails[]", "resource_ids[]", "tenant_only", "limit", "after", "before"} },
    ["openai-admin.list_batches"] = { method = "GET", url = "https://api.openai.com/v1/batches", query = {"after", "limit"} },
    ["openai-admin.list_chat_completions"] = { method = "GET", url = "https://api.openai.com/v1/chat/completions", query = {"model", "metadata", "after", "limit", "order"} },
    ["openai-admin.list_container_files"] = { method = "GET", url = "https://api.openai.com/v1/containers/{container_id}/files", path = {"container_id"}, query = {"limit", "order", "after"} },
    ["openai-admin.list_containers"] = { method = "GET", url = "https://api.openai.com/v1/containers", query = {"limit", "order", "after", "name"} },
    ["openai-admin.list_conversation_items"] = { method = "GET", url = "https://api.openai.com/v1/conversations/{conversation_id}/items", path = {"conversation_id"}, query = {"limit", "order", "after", "include"} },
    ["openai-admin.list_evals"] = { method = "GET", url = "https://api.openai.com/v1/evals", query = {"after", "limit", "order", "order_by"} },
    ["openai-admin.list_files"] = { method = "GET", url = "https://api.openai.com/v1/files", query = {"purpose", "limit", "order", "after"} },
    ["openai-admin.list_files_in_vector_store_batch"] = { method = "GET", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/files", path = {"vector_store_id", "batch_id"}, query = {"limit", "order", "after", "before", "filter"} },
    ["openai-admin.list_fine_tuning_checkpoint_permissions"] = { method = "GET", url = "https://api.openai.com/v1/fine_tuning/checkpoints/{fine_tuned_model_checkpoint}/permissions", path = {"fine_tuned_model_checkpoint"}, query = {"project_id", "after", "limit", "order"} },
    ["openai-admin.list_fine_tuning_events"] = { method = "GET", url = "https://api.openai.com/v1/fine_tuning/jobs/{fine_tuning_job_id}/events", path = {"fine_tuning_job_id"}, query = {"after", "limit"} },
    ["openai-admin.list_fine_tuning_job_checkpoints"] = { method = "GET", url = "https://api.openai.com/v1/fine_tuning/jobs/{fine_tuning_job_id}/checkpoints", path = {"fine_tuning_job_id"}, query = {"after", "limit"} },
    ["openai-admin.list_group_role_assignments"] = { method = "GET", url = "https://api.openai.com/v1/organization/groups/{group_id}/roles", path = {"group_id"}, query = {"limit", "after", "order"} },
    ["openai-admin.list_group_users"] = { method = "GET", url = "https://api.openai.com/v1/organization/groups/{group_id}/users", path = {"group_id"}, query = {"limit", "after", "order"} },
    ["openai-admin.list_groups"] = { method = "GET", url = "https://api.openai.com/v1/organization/groups", query = {"limit", "after", "order"} },
    ["openai-admin.list_input_items"] = { method = "GET", url = "https://api.openai.com/v1/responses/{response_id}/input_items", path = {"response_id"}, query = {"limit", "order", "after", "include"} },
    ["openai-admin.list_invites"] = { method = "GET", url = "https://api.openai.com/v1/organization/invites", query = {"limit", "after"} },
    ["openai-admin.list_messages"] = { method = "GET", url = "https://api.openai.com/v1/threads/{thread_id}/messages", path = {"thread_id"}, query = {"limit", "order", "after", "before", "run_id"} },
    ["openai-admin.list_models"] = { method = "GET", url = "https://api.openai.com/v1/models" },
    ["openai-admin.list_organization_certificates"] = { method = "GET", url = "https://api.openai.com/v1/organization/certificates", query = {"limit", "after", "order"} },
    ["openai-admin.list_organization_spend_alerts"] = { method = "GET", url = "https://api.openai.com/v1/organization/spend_alerts", query = {"limit", "order", "after", "before"} },
    ["openai-admin.list_paginated_fine_tuning_jobs"] = { method = "GET", url = "https://api.openai.com/v1/fine_tuning/jobs", query = {"after", "limit", "metadata"} },
    ["openai-admin.list_project_api_keys"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/api_keys", path = {"project_id"}, query = {"limit", "after", "owner_project_access"} },
    ["openai-admin.list_project_certificates"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/certificates", path = {"project_id"}, query = {"limit", "after", "order"} },
    ["openai-admin.list_project_group_role_assignments"] = { method = "GET", url = "https://api.openai.com/v1/projects/{project_id}/groups/{group_id}/roles", path = {"project_id", "group_id"}, query = {"limit", "after", "order"} },
    ["openai-admin.list_project_groups"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/groups", path = {"project_id"}, query = {"limit", "after", "order"} },
    ["openai-admin.list_project_rate_limits"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/rate_limits", path = {"project_id"}, query = {"limit", "after", "before"} },
    ["openai-admin.list_project_roles"] = { method = "GET", url = "https://api.openai.com/v1/projects/{project_id}/roles", path = {"project_id"}, query = {"limit", "after", "order"} },
    ["openai-admin.list_project_service_accounts"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/service_accounts", path = {"project_id"}, query = {"limit", "after"} },
    ["openai-admin.list_project_spend_alerts"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/spend_alerts", path = {"project_id"}, query = {"limit", "order", "after", "before"} },
    ["openai-admin.list_project_user_role_assignments"] = { method = "GET", url = "https://api.openai.com/v1/projects/{project_id}/users/{user_id}/roles", path = {"project_id", "user_id"}, query = {"limit", "after", "order"} },
    ["openai-admin.list_project_users"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/users", path = {"project_id"}, query = {"limit", "after"} },
    ["openai-admin.list_projects"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects", query = {"limit", "after", "include_archived"} },
    ["openai-admin.list_roles"] = { method = "GET", url = "https://api.openai.com/v1/organization/roles", query = {"limit", "after", "order"} },
    ["openai-admin.list_run_steps"] = { method = "GET", url = "https://api.openai.com/v1/threads/{thread_id}/runs/{run_id}/steps", path = {"thread_id", "run_id"}, query = {"limit", "order", "after", "before", "include[]"} },
    ["openai-admin.list_runs"] = { method = "GET", url = "https://api.openai.com/v1/threads/{thread_id}/runs", path = {"thread_id"}, query = {"limit", "order", "after", "before"} },
    ["openai-admin.list_skill_versions"] = { method = "GET", url = "https://api.openai.com/v1/skills/{skill_id}/versions", path = {"skill_id"}, query = {"limit", "order", "after"} },
    ["openai-admin.list_skills"] = { method = "GET", url = "https://api.openai.com/v1/skills", query = {"limit", "order", "after"} },
    ["openai-admin.list_thread_items_method"] = { method = "GET", url = "https://api.openai.com/v1/chatkit/threads/{thread_id}/items", path = {"thread_id"}, query = {"limit", "order", "after", "before"} },
    ["openai-admin.list_threads_method"] = { method = "GET", url = "https://api.openai.com/v1/chatkit/threads", query = {"limit", "order", "after", "before", "user"} },
    ["openai-admin.list_user_role_assignments"] = { method = "GET", url = "https://api.openai.com/v1/organization/users/{user_id}/roles", path = {"user_id"}, query = {"limit", "after", "order"} },
    ["openai-admin.list_users"] = { method = "GET", url = "https://api.openai.com/v1/organization/users", query = {"limit", "after", "emails"} },
    ["openai-admin.list_vault_credentials"] = { method = "GET", url = "https://api.openai.com/v1/vaults/{vault_id}/credentials", path = {"vault_id"}, query = {"order", "limit", "status", "after"} },
    ["openai-admin.list_vaults"] = { method = "GET", url = "https://api.openai.com/v1/vaults", query = {"order", "limit", "status", "after"} },
    ["openai-admin.list_vector_store_files"] = { method = "GET", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/files", path = {"vector_store_id"}, query = {"limit", "order", "after", "before", "filter"} },
    ["openai-admin.list_vector_stores"] = { method = "GET", url = "https://api.openai.com/v1/vector_stores", query = {"limit", "order", "after", "before"} },
    ["openai-admin.list_voice_consents"] = { method = "GET", url = "https://api.openai.com/v1/audio/voice_consents", query = {"after", "limit"} },
    ["openai-admin.list_webhook_endpoints"] = { method = "GET", url = "https://api.openai.com/v1/webhook_endpoints", query = {"limit", "after"} },
    ["openai-admin.list_webhook_event_types"] = { method = "GET", url = "https://api.openai.com/v1/webhook_event_types" },
    ["openai-admin.listexternalstorageconfigurations"] = { method = "GET", url = "https://api.openai.com/v1/organization/external_storage", query = {"project_id", "after", "order", "limit"} },
    ["openai-admin.modify_certificate"] = { method = "POST", url = "https://api.openai.com/v1/organization/certificates/{certificate_id}", path = {"certificate_id"}, body = {"name"} },
    ["openai-admin.modify_message"] = { method = "POST", url = "https://api.openai.com/v1/threads/{thread_id}/messages/{message_id}", path = {"thread_id", "message_id"}, body = {"metadata"} },
    ["openai-admin.modify_project"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}", path = {"project_id"}, body = {"name", "external_key_id", "geography"} },
    ["openai-admin.modify_project_user"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/users/{user_id}", path = {"project_id", "user_id"}, body = {"role"} },
    ["openai-admin.modify_run"] = { method = "POST", url = "https://api.openai.com/v1/threads/{thread_id}/runs/{run_id}", path = {"thread_id", "run_id"}, body = {"metadata"} },
    ["openai-admin.modify_thread"] = { method = "POST", url = "https://api.openai.com/v1/threads/{thread_id}", path = {"thread_id"}, body = {"tool_resources", "metadata"} },
    ["openai-admin.modify_user"] = { method = "POST", url = "https://api.openai.com/v1/organization/users/{user_id}", path = {"user_id"}, body = {"role", "role_id", "technical_level", "developer_persona"} },
    ["openai-admin.modify_vector_store"] = { method = "POST", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}", path = {"vector_store_id"}, body = {"name", "expires_after", "metadata"} },
    ["openai-admin.pause_fine_tuning_job"] = { method = "POST", url = "https://api.openai.com/v1/fine_tuning/jobs/{fine_tuning_job_id}/pause", path = {"fine_tuning_job_id"} },
    ["openai-admin.refer_live_session"] = { method = "POST", url = "https://api.openai.com/v1/live/sessions/{session_id}/refer", path = {"session_id"}, body = {"target_uri"} },
    ["openai-admin.refer_realtime_call"] = { method = "POST", url = "https://api.openai.com/v1/realtime/calls/{call_id}/refer", path = {"call_id"}, body = {"target_uri"} },
    ["openai-admin.reject_live_session"] = { method = "POST", url = "https://api.openai.com/v1/live/sessions/{session_id}/reject", path = {"session_id"}, body = {"status_code"} },
    ["openai-admin.reject_realtime_call"] = { method = "POST", url = "https://api.openai.com/v1/realtime/calls/{call_id}/reject", path = {"call_id"}, body = {"status_code"} },
    ["openai-admin.remove_group_user"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/groups/{group_id}/users/{user_id}", path = {"group_id", "user_id"} },
    ["openai-admin.remove_project_group"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/projects/{project_id}/groups/{group_id}", path = {"project_id", "group_id"} },
    ["openai-admin.resume_fine_tuning_job"] = { method = "POST", url = "https://api.openai.com/v1/fine_tuning/jobs/{fine_tuning_job_id}/resume", path = {"fine_tuning_job_id"} },
    ["openai-admin.retrieve_agent"] = { method = "GET", url = "https://api.openai.com/v1/agents/{agent_id}", path = {"agent_id"} },
    ["openai-admin.retrieve_agent_environment"] = { method = "GET", url = "https://api.openai.com/v1/agents/environments/{environment_id}", path = {"environment_id"} },
    ["openai-admin.retrieve_agent_environment_template"] = { method = "GET", url = "https://api.openai.com/v1/agents/environments/templates/{environment_template_id}", path = {"environment_template_id"} },
    ["openai-admin.retrieve_agent_session"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}", path = {"session_id"} },
    ["openai-admin.retrieve_agent_session_artifact"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/artifacts/{artifact_id}", path = {"session_id", "artifact_id"} },
    ["openai-admin.retrieve_agent_session_artifact_content"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/artifacts/{artifact_id}/content", path = {"session_id", "artifact_id"} },
    ["openai-admin.retrieve_agent_session_subagent"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/subagents/{subagent_id}", path = {"session_id", "subagent_id"} },
    ["openai-admin.retrieve_agent_session_subagent_turn"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/subagents/{subagent_id}/turns/{turn_id}", path = {"session_id", "subagent_id", "turn_id"} },
    ["openai-admin.retrieve_agent_session_turn"] = { method = "GET", url = "https://api.openai.com/v1/agents/sessions/{session_id}/turns/{turn_id}", path = {"session_id", "turn_id"} },
    ["openai-admin.retrieve_batch"] = { method = "GET", url = "https://api.openai.com/v1/batches/{batch_id}", path = {"batch_id"} },
    ["openai-admin.retrieve_container"] = { method = "GET", url = "https://api.openai.com/v1/containers/{container_id}", path = {"container_id"} },
    ["openai-admin.retrieve_container_file"] = { method = "GET", url = "https://api.openai.com/v1/containers/{container_id}/files/{file_id}", path = {"container_id", "file_id"} },
    ["openai-admin.retrieve_container_file_content"] = { method = "GET", url = "https://api.openai.com/v1/containers/{container_id}/files/{file_id}/content", path = {"container_id", "file_id"} },
    ["openai-admin.retrieve_file"] = { method = "GET", url = "https://api.openai.com/v1/files/{file_id}", path = {"file_id"} },
    ["openai-admin.retrieve_fine_tuning_job"] = { method = "GET", url = "https://api.openai.com/v1/fine_tuning/jobs/{fine_tuning_job_id}", path = {"fine_tuning_job_id"} },
    ["openai-admin.retrieve_group"] = { method = "GET", url = "https://api.openai.com/v1/organization/groups/{group_id}", path = {"group_id"} },
    ["openai-admin.retrieve_group_role"] = { method = "GET", url = "https://api.openai.com/v1/organization/groups/{group_id}/roles/{role_id}", path = {"group_id", "role_id"} },
    ["openai-admin.retrieve_group_user"] = { method = "GET", url = "https://api.openai.com/v1/organization/groups/{group_id}/users/{user_id}", path = {"group_id", "user_id"} },
    ["openai-admin.retrieve_invite"] = { method = "GET", url = "https://api.openai.com/v1/organization/invites/{invite_id}", path = {"invite_id"} },
    ["openai-admin.retrieve_model"] = { method = "GET", url = "https://api.openai.com/v1/models/{model}", path = {"model"} },
    ["openai-admin.retrieve_organization_data_retention"] = { method = "GET", url = "https://api.openai.com/v1/organization/data_retention" },
    ["openai-admin.retrieve_organization_spend_alert"] = { method = "GET", url = "https://api.openai.com/v1/organization/spend_alerts/{alert_id}", path = {"alert_id"} },
    ["openai-admin.retrieve_project"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}", path = {"project_id"} },
    ["openai-admin.retrieve_project_api_key"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/api_keys/{api_key_id}", path = {"project_id", "api_key_id"} },
    ["openai-admin.retrieve_project_data_retention"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/data_retention", path = {"project_id"} },
    ["openai-admin.retrieve_project_group"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/groups/{group_id}", path = {"project_id", "group_id"}, query = {"group_type"} },
    ["openai-admin.retrieve_project_group_role"] = { method = "GET", url = "https://api.openai.com/v1/projects/{project_id}/groups/{group_id}/roles/{role_id}", path = {"project_id", "group_id", "role_id"} },
    ["openai-admin.retrieve_project_hosted_tool_permissions"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/hosted_tool_permissions", path = {"project_id"} },
    ["openai-admin.retrieve_project_model_permissions"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/model_permissions", path = {"project_id"} },
    ["openai-admin.retrieve_project_role"] = { method = "GET", url = "https://api.openai.com/v1/projects/{project_id}/roles/{role_id}", path = {"project_id", "role_id"} },
    ["openai-admin.retrieve_project_service_account"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/service_accounts/{service_account_id}", path = {"project_id", "service_account_id"} },
    ["openai-admin.retrieve_project_spend_alert"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/spend_alerts/{alert_id}", path = {"project_id", "alert_id"} },
    ["openai-admin.retrieve_project_user"] = { method = "GET", url = "https://api.openai.com/v1/organization/projects/{project_id}/users/{user_id}", path = {"project_id", "user_id"} },
    ["openai-admin.retrieve_project_user_role"] = { method = "GET", url = "https://api.openai.com/v1/projects/{project_id}/users/{user_id}/roles/{role_id}", path = {"project_id", "user_id", "role_id"} },
    ["openai-admin.retrieve_role"] = { method = "GET", url = "https://api.openai.com/v1/organization/roles/{role_id}", path = {"role_id"} },
    ["openai-admin.retrieve_user"] = { method = "GET", url = "https://api.openai.com/v1/organization/users/{user_id}", path = {"user_id"} },
    ["openai-admin.retrieve_user_role"] = { method = "GET", url = "https://api.openai.com/v1/organization/users/{user_id}/roles/{role_id}", path = {"user_id", "role_id"} },
    ["openai-admin.retrieve_vault"] = { method = "GET", url = "https://api.openai.com/v1/vaults/{vault_id}", path = {"vault_id"} },
    ["openai-admin.retrieve_vault_credential"] = { method = "GET", url = "https://api.openai.com/v1/vaults/{vault_id}/credentials/{credential_id}", path = {"vault_id", "credential_id"} },
    ["openai-admin.retrieve_vector_store_file_content"] = { method = "GET", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/files/{file_id}/content", path = {"vector_store_id", "file_id"} },
    ["openai-admin.retrieve_webhook_endpoint"] = { method = "GET", url = "https://api.openai.com/v1/webhook_endpoints/{webhook_endpoint_id}", path = {"webhook_endpoint_id"} },
    ["openai-admin.rotate_vault_credential"] = { method = "POST", url = "https://api.openai.com/v1/vaults/{vault_id}/credentials/{credential_id}", path = {"vault_id", "credential_id"} },
    ["openai-admin.rotate_webhook_endpoint_signing_secret"] = { method = "POST", url = "https://api.openai.com/v1/webhook_endpoints/{webhook_endpoint_id}/rotate_secret", path = {"webhook_endpoint_id"}, body = {"keep_old_secret_active_for_24_hours"} },
    ["openai-admin.run_grader"] = { method = "POST", url = "https://api.openai.com/v1/fine_tuning/alpha/graders/run", body = {"grader", "item", "model_sample"} },
    ["openai-admin.search_vector_store"] = { method = "POST", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/search", path = {"vector_store_id"}, body = {"query", "rewrite_query", "max_num_results", "filters", "ranking_options"} },
    ["openai-admin.submit_tool_ouputs_to_run"] = { method = "POST", url = "https://api.openai.com/v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs", path = {"thread_id", "run_id"}, body = {"tool_outputs", "stream"} },
    ["openai-admin.test_webhook_endpoint"] = { method = "POST", url = "https://api.openai.com/v1/webhook_endpoints/{webhook_endpoint_id}/test", path = {"webhook_endpoint_id"}, body = {"event_type"} },
    ["openai-admin.unassign_group_role"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/groups/{group_id}/roles/{role_id}", path = {"group_id", "role_id"} },
    ["openai-admin.unassign_project_group_role"] = { method = "DELETE", url = "https://api.openai.com/v1/projects/{project_id}/groups/{group_id}/roles/{role_id}", path = {"project_id", "group_id", "role_id"} },
    ["openai-admin.unassign_project_user_role"] = { method = "DELETE", url = "https://api.openai.com/v1/projects/{project_id}/users/{user_id}/roles/{role_id}", path = {"project_id", "user_id", "role_id"} },
    ["openai-admin.unassign_user_role"] = { method = "DELETE", url = "https://api.openai.com/v1/organization/users/{user_id}/roles/{role_id}", path = {"user_id", "role_id"} },
    ["openai-admin.update_agent"] = { method = "POST", url = "https://api.openai.com/v1/agents/{agent_id}", path = {"agent_id"}, body = {"model", "reasoning", "text", "service_tier", "instructions", "multi_agent", "metadata", "name", "tools"} },
    ["openai-admin.update_agent_environment_template"] = { method = "POST", url = "https://api.openai.com/v1/agents/environments/templates/{environment_template_id}", path = {"environment_template_id"}, body = {"name", "packages", "setup_commands", "network", "env", "capability_directories", "skills", "plugins", "files"} },
    ["openai-admin.update_agent_session"] = { method = "POST", url = "https://api.openai.com/v1/agents/sessions/{session_id}", path = {"session_id"}, body = {"agent", "metadata"} },
    ["openai-admin.update_chat_completion"] = { method = "POST", url = "https://api.openai.com/v1/chat/completions/{completion_id}", path = {"completion_id"}, body = {"metadata"} },
    ["openai-admin.update_conversation"] = { method = "POST", url = "https://api.openai.com/v1/conversations/{conversation_id}", path = {"conversation_id"}, body = {"metadata"} },
    ["openai-admin.update_eval"] = { method = "POST", url = "https://api.openai.com/v1/evals/{eval_id}", path = {"eval_id"}, body = {"name", "metadata"} },
    ["openai-admin.update_group"] = { method = "POST", url = "https://api.openai.com/v1/organization/groups/{group_id}", path = {"group_id"}, body = {"name"} },
    ["openai-admin.update_organization_data_retention"] = { method = "POST", url = "https://api.openai.com/v1/organization/data_retention", body = {"retention_type"} },
    ["openai-admin.update_organization_spend_alert"] = { method = "POST", url = "https://api.openai.com/v1/organization/spend_alerts/{alert_id}", path = {"alert_id"}, body = {"threshold_amount", "currency", "interval", "notification_channel"} },
    ["openai-admin.update_project_data_retention"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/data_retention", path = {"project_id"}, body = {"retention_type"} },
    ["openai-admin.update_project_hosted_tool_permissions"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/hosted_tool_permissions", path = {"project_id"}, body = {"file_search", "web_search", "image_generation", "mcp", "code_interpreter"} },
    ["openai-admin.update_project_model_permissions"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/model_permissions", path = {"project_id"}, body = {"mode", "model_ids"} },
    ["openai-admin.update_project_rate_limits"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/rate_limits/{rate_limit_id}", path = {"project_id", "rate_limit_id"}, body = {"max_requests_per_1_minute", "max_tokens_per_1_minute", "max_images_per_1_minute", "max_audio_megabytes_per_1_minute", "max_requests_per_1_day", "batch_1_day_max_input_tokens"} },
    ["openai-admin.update_project_role"] = { method = "POST", url = "https://api.openai.com/v1/projects/{project_id}/roles/{role_id}", path = {"project_id", "role_id"}, body = {"permissions", "description", "role_name"} },
    ["openai-admin.update_project_service_account"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/service_accounts/{service_account_id}", path = {"project_id", "service_account_id"}, body = {"name", "role"} },
    ["openai-admin.update_project_spend_alert"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/spend_alerts/{alert_id}", path = {"project_id", "alert_id"}, body = {"threshold_amount", "currency", "interval", "notification_channel"} },
    ["openai-admin.update_role"] = { method = "POST", url = "https://api.openai.com/v1/organization/roles/{role_id}", path = {"role_id"}, body = {"permissions", "description", "role_name"} },
    ["openai-admin.update_skill_default_version"] = { method = "POST", url = "https://api.openai.com/v1/skills/{skill_id}", path = {"skill_id"}, body = {"default_version"} },
    ["openai-admin.update_vector_store_file_attributes"] = { method = "POST", url = "https://api.openai.com/v1/vector_stores/{vector_store_id}/files/{file_id}", path = {"vector_store_id", "file_id"}, body = {"attributes"} },
    ["openai-admin.update_voice_consent"] = { method = "POST", url = "https://api.openai.com/v1/audio/voice_consents/{consent_id}", path = {"consent_id"}, body = {"name"} },
    ["openai-admin.update_webhook_endpoint"] = { method = "POST", url = "https://api.openai.com/v1/webhook_endpoints/{webhook_endpoint_id}", path = {"webhook_endpoint_id"}, body = {"name", "url", "event_types"} },
    ["openai-admin.updateorganizationspendlimit"] = { method = "POST", url = "https://api.openai.com/v1/organization/spend_limit", body = {"threshold_amount", "currency", "interval"} },
    ["openai-admin.updateprojectspendlimit"] = { method = "POST", url = "https://api.openai.com/v1/organization/projects/{project_id}/spend_limit", path = {"project_id"}, body = {"threshold_amount", "currency", "interval"} },
    ["openai-admin.upload_certificate"] = { method = "POST", url = "https://api.openai.com/v1/organization/certificates", body = {"name", "certificate"} },
    ["openai-admin.usage_audio_speeches"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/audio_speeches", query = {"start_time", "end_time", "bucket_width", "project_ids", "user_ids", "api_key_ids", "models", "group_by", "limit", "page"} },
    ["openai-admin.usage_audio_transcriptions"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/audio_transcriptions", query = {"start_time", "end_time", "bucket_width", "project_ids", "user_ids", "api_key_ids", "models", "group_by", "limit", "page"} },
    ["openai-admin.usage_code_interpreter_sessions"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/code_interpreter_sessions", query = {"start_time", "end_time", "bucket_width", "project_ids", "group_by", "limit", "page"} },
    ["openai-admin.usage_completions"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/completions", query = {"start_time", "end_time", "bucket_width", "project_ids", "user_ids", "api_key_ids", "models", "batch", "group_by", "limit", "page"} },
    ["openai-admin.usage_costs"] = { method = "GET", url = "https://api.openai.com/v1/organization/costs", query = {"start_time", "end_time", "bucket_width", "project_ids", "api_key_ids", "line_items", "group_by", "limit", "page"} },
    ["openai-admin.usage_embeddings"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/embeddings", query = {"start_time", "end_time", "bucket_width", "project_ids", "user_ids", "api_key_ids", "models", "group_by", "limit", "page"} },
    ["openai-admin.usage_file_search_calls"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/file_search_calls", query = {"start_time", "end_time", "bucket_width", "project_ids", "user_ids", "api_key_ids", "vector_store_ids", "group_by", "limit", "page"} },
    ["openai-admin.usage_images"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/images", query = {"start_time", "end_time", "bucket_width", "sources", "sizes", "project_ids", "user_ids", "api_key_ids", "models", "group_by", "limit", "page"} },
    ["openai-admin.usage_moderations"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/moderations", query = {"start_time", "end_time", "bucket_width", "project_ids", "user_ids", "api_key_ids", "models", "group_by", "limit", "page"} },
    ["openai-admin.usage_vector_stores"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/vector_stores", query = {"start_time", "end_time", "bucket_width", "project_ids", "group_by", "limit", "page"} },
    ["openai-admin.usage_web_search_calls"] = { method = "GET", url = "https://api.openai.com/v1/organization/usage/web_search_calls", query = {"start_time", "end_time", "bucket_width", "project_ids", "user_ids", "api_key_ids", "models", "context_levels", "group_by", "limit", "page"} },
    ["openai-admin.validate_grader"] = { method = "POST", url = "https://api.openai.com/v1/fine_tuning/alpha/graders/validate", body = {"grader"} },
    ["openai-admin.validateanexternalstorageconfiguration"] = { method = "POST", url = "https://api.openai.com/v1/organization/external_storage/{external_storage_id}/validate", path = {"external_storage_id"} },
  },
}
